        	<div class="fav_txt_rt">
            	<h3 class='text-blue'><?php echo $this->translate('Favorieten')?></h3>
            	
                <?php if(count($this->topStores) > 0) :?>
	                <div class="sub_hdr">
	                	<img src="<?php echo HTTP_PATH_CDN?>images/front_end/fav_icon.png" alt="" />
	                    <?php echo $this->translate('Zoek op winkelnaam: Bol.com, Wehkamp, Zalando, etc.')?>
	                </div>
                
	                <div class="shops_fav" id='suggestedShops' style='margin-top:0;'>
	                	<?php 
	                		foreach ($this->topStores as $key => $suggestion) :
	                			$img = ltrim($suggestion['shop']['logo']['imgpath'],"/").'thum_medium_store_'.$suggestion['shop']['logo']['imgname'];
	                	?>
		                	<div class="shops_fav_txt">
		                    	<div class="shops_fav_top"><a href="<?php echo HTTP_PATH_LOCALE . $suggestion['shop']['permaLink']?>" ><img src="<?php echo PUBLIC_PATH_CDN . $img;?>" alt="<?php echo $suggestion['shop']['name']?>" /></a></div>
		                        <div class="shops_fav_btm" onclick="addFavoriteShops(<?php echo $suggestion['shop']['id']?>,<?php echo Auth_VisitorAdapter::getIdentity()->id?>);"><?php echo $this->translate('Toevoegen')?></div>
		                    </div>
	                    <?php endforeach;?>
		            </div>
                <?php endif;?>
                
                <?php if(count($this->favShops) > 0) :?>
	                <div class="sub_hdr">
	                	<img src="<?php echo HTTP_PATH_CDN?>images/front_end/fav_icon.png" alt="" />
	                    <?php echo $this->translate('Cree&euml;r Favorieten');?>
	                </div>
                
	                <div class="shops_fav" id='favoriteShops' style='margin-top:0;'>
	                	<?php 
	                		foreach ($this->favShops as $key => $favShops) :
	                				if($favShops['shops']):
	                				$img = $favShops['shops'][0]['logo']['path'].'thum_medium_store_'.$favShops['shops'][0]['logo']['name'];
	                			   
	                	?>
				                	<div class="shops_fav_txt">
				                    	<div class="shops_fav_top"><a href="<?php echo HTTP_PATH_LOCALE . $favShops['shops'][0]['permaLink']?>" ><img src="<?php echo PUBLIC_PATH_CDN . $img;?>" alt="<?php echo $favShops['shops'][0]['name']?>" /></a></div>
				                        <div class="shops_fav_btmnew" onclick="deleteFavoriteShops(<?php echo $favShops['shops'][0]['id']?>,<?php echo Auth_VisitorAdapter::getIdentity()->id?>)"><?php echo $this->translate('verwijderen')?></div>
				                    </div>
	                    <?php
	                    	endif;
	                    	endforeach;
	                    ?>
	                </div>
                 <?php endif;?>
                 
                <?php if(count($this->paginator)>0): ?>
	                <div class="sub_hdr" style="margin-bottom: 25px;">
	                	<img src="<?php echo HTTP_PATH_CDN?>images/front_end/fav_icon.png" alt="" />
	                    <?php echo $this->translate('Kortingscodes, speciaal voor jouw geselecteerd')?>
	                </div>
	                
	                 <div class="shops_fav">
	                 
	                     <?php echo $this->partialLoop('partials/offer.phtml', $this->paginator); ?>
		                  <!-- Voucher Col1 Ends -->
		                     <!-- Voucher Paging Outer Starts -->
		                 <div  class="voucher-paging-outer">
		                 	<div class="voucher-paging-inner">
		
		                    		<?php 
		                    			echo $this->paginationControl($this->paginator,
		                                    'Sliding',
		                                    '/partials/_pagination.phtml'); 
		                    		?>
		                            
		                    </div>
		                 </div>
		                 <!-- Voucher Paging Outer Ends -->
	                 </div>
                <?php endif;?>
                
            </div>
         