
                <?php if(count($this->paginator)>0): ?>
	                <div class="sub_hdr" style="margin-bottom: 25px;">
	                	<img src="<?php echo HTTP_PATH?>public/images/front_end/fav_icon.png" alt="" />
	                    <?php echo $this->translate('Kortingscodes, speciaal voor jouw geselecteerd')?>
	                </div>
	                
	                 <div class="shops_fav">
	                		<?php echo $this->partialLoop('partials/offer.phtml', $this->paginator); ?>
		                  <!-- Voucher Col1 Ends -->
		                     <!-- Voucher Paging Outer Starts -->
		                 <div  class="voucher-paging-outer">
		                 	<div class="voucher-paging-inner">
		
		                    		<?php 
		                    			echo $this->paginationControl($this->paginator,
		                                    'Sliding',
		                                    '/partials/_pagination.phtml'); 
		                    		?>
		                            
		                    </div>
		                 </div>
		                 <!-- Voucher Paging Outer Ends -->
	                 </div>
                <?php endif;?>
                
          
         