<?php 
$this->minifyHeadScript()->appendFile(HTTP_PATH."public/js/back_end/bootbox.min.js");
$this->minifyHeadScript()->appendFile(HTTP_PATH."public/js/jquery.iframe-transport.js");
$this->minifyHeadScript()->appendFile(HTTP_PATH."public/js/jquery.fileupload.js");
$this->minifyHeadScript()->appendFile(HTTP_PATH."public/js/front_end/profileImage.js");
?>

<div class="fav_img_outer">
		<div id='showHide' class="user-pic pos_relative">
			
		<form class="image-form" method="POST" enctype=multipart/form-data name="profileImage" id="profileImage" action="<?php echo HTTP_PATH_LOCALE.'myfavorite/savefile'?>">
		
			<?php 
			 if($this->userdetail!=null)
			 {
				$img = HTTP_PATH_CDN.'images/front_end/per_icon.png';
				$cls = 'mt24';
			 	if( count($this->userdetail['visitorimage'])){
	         		$cls = '';
	         		$img = PUBLIC_PATH_CDN.ltrim($this->userdetail['visitorimage']['path'],"/").'thum_'.$this->userdetail['visitorimage']['name'];
	         		
				 }
			 }
			?>
		<img  class='<?php echo $cls ; ?>' src="<?php echo $img ?>" alt="User Image" />
		<div class="uploder">
        	  <div class="text"><?php echo $this->translate('Upload Image')?></div><input class="uplodelink" style="position: absolute;width: 190px;z-index: 9999; left:0;font-size: 30px;" type="file" id="fileupload" name="files" multiple>
        </div> 
        
    	</form>
    	</div>
    	
        <div class="user-profile-txt">
        	<h2><?php echo $this->userdetail['firstName']?></h2>
			<!-- show welcome message if a visitor has subscribed newsletter -->
			<div class="welcome-message-cont">
        		<?php echo $this->translate(utf8_encode('Welkom terug&#33; Voeg een aantal van je favoriete winkels toe zodat je altijd op de hoogte blijft van de beste acties &#38; kortingscodes&#33;'))?>
        	</div>
            <div id="messageDiv" class="yellow-box-error-box-code myprofile-messagebox" style="<?php echo $this->messageSuccess != '' ? '' : 'display:none;'?>"><strong><?php echo $this->messageSuccess;?></strong>
        	</div>
        </div>
        	<br class="clr" />
			<!-- show  a message saying you are unsubscribed from weekly newsletter -->
			<div class="newsletter-unsubscribed-cont <?php echo $this->userdetail['weeklyNewsLetter'] ? 'hide' : '' ; ?>">
	        	<h2><?php echo $this->translate('Toch weer niewsbrieven ontvangen ?')?></h2>
	        	<p>
					<?php echo $this->translate(utf8_encode('Wil jij toch nog op de hoogte blijven van de beste kortingscodes via onze nieuwsbrief? Vink dan de box hieronder aan bij wekelijkse nieuwsbrief en klik op update instellingen.'))?>
	        	</p>
	        </div>
	
</div>