<?php 
$this->minifyHeadScript()->appendFile(HTTP_PATH."public/js/back_end/bootbox.min.js");
$this->minifyHeadScript()->appendFile(HTTP_PATH."public/js/jquery.iframe-transport.js");
$this->minifyHeadScript()->appendFile(HTTP_PATH."public/js/jquery.fileupload.js");
$this->minifyHeadScript()->appendFile(HTTP_PATH."public/js/front_end/profileImage.js");
?>

<div class="fav_img_outer">
		<div id='showHide' class="user-pic pos_relative">
			
		<form class="image-form" method="POST" enctype=multipart/form-data name="profileImage" id="profileImage" action="<?php echo HTTP_PATH_LOCALE.'myfavorite/savefile'?>">
		
			<?php 
			 if($this->userdetail!=null)
			 {
				$img = HTTP_PATH.'public/images/front_end/per_icon.png';
				$cls = 'mt24';
			 	if( count($this->userdetail['visitorimage'])){
	         	if( file_exists ( ROOT_PATH.$this->userdetail['visitorimage']['path'] .'thum_'. $this->userdetail['visitorimage']['name'] )) {
	         		$cls = '';
	         		$img = PUBLIC_PATH.ltrim($this->userdetail['visitorimage']['path'],"/").'thum_'.$this->userdetail['visitorimage']['name'];
	         		}
				 }
			 }
			?>
		<img  class='<?php echo $cls ; ?>' src="<?php echo $img ?>" alt="User Image" />
		<div class="uploder">
        	  <div class="text"><?php echo $this->translate('Upload Image')?></div><input class="uplodelink" style="position: absolute;width: 190px;z-index: 9999; left:0;font-size: 30px;" type="file" id="fileupload" name="files" multiple>
        </div> 
        
    	</form>
    	</div>
    	
        <div class="user-profile-txt">
        	<h2><?php echo $this->userdetail['firstName']?></h2>
            <?php echo $this->translate(utf8_encode('Welkom terug&#33; Voeg een aantal van je favoriete winkels toe zodat je altijd op de hoogte blijft van de beste acties &#38; kortingscodes&#33;'))?>
        </div>
        
</div>