<?php
echo $this->HeadScript()->prependFile (HTTP_PATH ."public/js/front_end/myfavorite.js");
?>
        <!-- Search Outer2 Ends -->
<div class='new-outer'>
	<div id="messageDiv" class="yellow-box-error-box-code" style="margin : 20px auto !important; <?php echo $this->messageSuccess != '' ? '' : 'display:none;'?>"><strong><?php echo $this->messageSuccess;?></strong></div>     
	 <?php echo $this->render('/myfavorite/header.phtml')?>
    
	<div class="new-signup-outer-round mt40">
    	
        <!--Favourite Txt Bg-->
        <div class="fav_txt_bg">
        	<!--Lt Side-->
        	 <?php echo $this->render('/myfavorite/leftpanel.phtml')?>
            <!--//Lt Side-->
            <!--Rt Side-->
            <?php echo $this->render('/myfavorite/favorite.phtml',$this->topStores)?>
            <!--Rt Side-->
        </div>
         <!--//Favourite Txt Bg-->
    </div>
</div>    