<?php $this->minifyHeadScript()->prependFile (HTTP_PATH."public/js/front_end/profile.js" ); ?>
<!-- Search Outer2 Ends -->
<div class='new-outer'>        
	 <?php echo $this->render('/myfavorite/header.phtml')?>
		<div class="new-signup-outer-round mt40">
    	
        <!--Favourite Txt Bg-->
        <div class="fav_txt_bg">
        	<!--Lt Side-->
        	 <?php echo $this->render('/myfavorite/leftpanel.phtml')?>
            <!--//Lt Side-->
            <!--Rt Side-->
            
            <?php echo $this->render('/myfavorite/membercodes.phtml')?>
            <!--Rt Side-->
        </div>
         <!--//Favourite Txt Bg-->
    </div>
</div>    