LocaleSettings:
  type: entity
  table: locale_settings
  fields:
    id:
      id: true
      type: bigint
      generator:
        strategy: IDENTITY
    locale:
      type: string
      length: 10
      nullable: true
    timezone:
      type: string
      length: 255
      nullable: true
