<?php 
/*$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/datepicker.css" );
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/timepicker.css" );
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/back_end/bootstrap-combobox.css" );
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/bootstrap-typeahead.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/bootstrap-combobox.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/date.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/bootstrap-datepicker.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/bootstrap-timepicker.js");

$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/bootbox.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/jquery.textareaCounter.plugin.js");

$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/editusergeneratedoffer.js");
*/

$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/datepicker.css" );
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/timepicker.css" );
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/back_end/bootstrap-combobox.css" );
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/bootstrap-typeahead.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/select2.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/editusergeneratedoffer.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/bootbox.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/jquery.textareaCounter.plugin.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/bootstrap-datepicker.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/bootstrap-timepicker.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/date.js");

$date = date("Y-m-d");// current date
$today = time();
$twoMonthsLater = strtotime("+2 months", $today);
$u = Auth_StaffAdapter::getIdentity();
$role = $u->users->id;
?>
<?php echo $this->headTitle()->append('Edit User Generated Offer');?>
<div class="wrap columns-2">
         <form action="<?php echo HTTP_PATH; ?>admin/usergeneratedoffer/updateoffer" name="addOffer" id="addOffer" method="POST" enctype="multipart/form-data">
          <h1><?php echo $this->translate('Edit User Generated Offer');?><button type="button" onClick="window.location.href='<?php echo HTTP_PATH; ?>admin/usergeneratedoffer'" href="#" class="btn ml10"><?php echo $this->translate('Cancel'); ?></button></h1>
          <input type="hidden" name='qString' id='qString' value='<?php echo $this->qstring; ?>' />
            <div class="mainpage-content">
            	<div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><strong><?php echo $this->translate('Approved'); ?></strong></div>
                    <div class="mainpage-content-right">
                    	<div data-toggle="buttons-checkbox" class="btn-group">
                            <button type="button"  class="btn " id="yes" onClick="selectOfferType('yes')"><?php echo $this->translate('Yes'); ?></button>                     
                            <input type="checkbox" checked="checked" class="display-none" name="yesoffercheckbox" id="yesoffercheckbox" value="defaultoffercheckbox">
                            <?php if($role!= 4){?> 
                            <button type="button" style="border-radius:  0 4px 4px 0 ;" class="btn btn-primary" id="no" onClick="selectOfferType('no')"><?php echo $this->translate('No'); ?></button>
                            <input type="checkbox" name="nocheckbox" class="display-none" id="nocheckbox" value="nooffercheckbox">
                            <?php } ?>
                          </div>
                    </div>          
                </div>
            </div>
           <span id="shopDetailDiv" >
            <div class="mainpage-content">
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><strong><?php echo $this->translate('For which shop?'); ?></strong></div>
                    <div class="mainpage-content-right">
                                <div class="mainpage-content-right-inner-right-other"></div>
                                <div class="mainpage-content-right-inner-left-other">
                                
 

							<select style="display: none; width : 250px;" class="combobox" id="whichshop">
								<option value=""></option>
		<?php
		
for($i = 0; $i < count ( $this->shopList ); $i ++) {
			if (trim ( $this->shopList [$i] ['name'] ) != '') {
				$shopname = substr ( $this->shopList [$i] ['name'], 0, 70 );
				?>
		     	<option value="<?php echo $this->shopList[$i]['id']; ?>"><?php echo $shopname; ?></option>
		<?php
			}
		}
		?>
	</select> <input type="hidden" name="selctedshop" id="selctedshop" value="">

                                  
                              </div>
                          </div>
                </div>
            </div>
            <div class="mainpage-content" id="aboutShopDiv" style="display:none;">
                <div class="mainpage-content-line mb10" id="aboutShopNoteDiv">
                    <div class="mainpage-content-left"><strong><?php echo $this->translate('Note from this shop:'); ?></strong></div>
                    <div class="mainpage-content-right" id="shopNotes">
                      &nbsp;
                  </div>
                </div>
                <div class="mainpage-content-line mb10" id="aboutManagerDiv">
                    <div class="mainpage-content-left"><strong><?php echo $this->translate('Account manager'); ?></strong></div>
                    <div class="mainpage-content-right" id="shopManager">
                       &nbsp;
                  </div>
                </div>
                <div class="mainpage-content-line mb10" id="aboutNertworkDiv">
                    <div class="mainpage-content-left"><strong><?php echo $this->translate('Network'); ?></strong></div>
                    <div class="mainpage-content-right" id="shopNetwork">
                       &nbsp;
                  </div>
                </div>
            </div>
        </span>  
            <div class="mainpage-content">
                <div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><strong><?php echo $this->translate('Type of Discount'); ?></strong></div>
                    <div class="mainpage-content-right">
                       <div data-toggle="buttons-checkbox" class="btn-group mb20">
                        <input type="checkbox" id="couponCodeCheckbox" name="couponCodeCheckbox" checked="checked" value="coupon" style="display:none;"> 
                        <input type="checkbox" id="saleCheckbox" name="saleCheckbox" value="sale" style="display:none;"> 
                        <input type="checkbox" id="printableCheckbox" name="printableCheckbox" value="printable" style="display:none;"> 
                        <button type="button" style="border-radius:  4px 0 0 4px ;" class="btn btn-primary" id="couponCode" onClick="selectDiscountType('couponCode')"><?php echo $this->translate('Coupon'); ?></button>   
                        <button type="button" class="btn" id="sale" onClick="selectDiscountType('sale')"><?php echo $this->translate('Sale'); ?></button>                     
                        <button type="button" class="btn" id="printable" onClick="selectDiscountType('printable')"><?php echo $this->translate('Printable'); ?></button>
                      </div>
                     <span id="couponDiv">
		                     <div class="clear line"></div>
		                     	  <div class="mainpage-content-right-inner-left"><label><?php echo $this->translate('Coupon code'); ?></label></div>
		                          <div class="mainpage-content-right-inner-right-other">
		                     	</div>
		                      	  <div class="mainpage-content-right-inner-right-full"><input type="text" id="couponCodeTxt" name="couponCode" placeholder="centerparks" class="span3"></div>
		                      <div class="mainpage-content-right-inner-left-other" id="categoryListdiv">
		                       <?php for($i=0;$i<count($this->catList['aaData']);$i++){
		                           if(trim($this->catList['aaData'][$i]['name'])!=''){ 
		                      	?>
		                      	<input type="checkbox" style="display:none;" id="category-<?php echo $this->catList['aaData'][$i]['id'];?>" value="<?php echo $this->catList['aaData'][$i]['id'];?>" name="selectedcategories[]">
		                      	<button type="button" id="categoryBtn-<?php echo $this->catList['aaData'][$i]['id'];?>" class="btn square-btn" onClick="addCategory(event,'<?php echo $this->catList['aaData'][$i]['id']; ?>')" title="<?php echo($this->catList['aaData'][$i]['name'])?>"><?php echo strlen($this->catList['aaData'][$i]['name']) < 20 ? $this->catList['aaData'][$i]['name'] : substr($this->catList['aaData'][$i]['name'],0,20).'..'; ?></button>
		                      	<?php }
		                          }?>
		                       
		                      </div>
                    </span>  
                    
                    <span id="printDiv" style="display:none;">
	                      <div class="clear line"></div>
	                      <div data-toggle="buttons-checkbox" class="btn-group mb20">
	                        <button type="button" class="btn btn-primary" id="uploadOfferOption" onClick="printOption('uploadOfferOption')" ><?php echo $this->translate('Upload Offer (pdf or jpg)'); ?></button>   
	                        <button type="button" class="btn" id="userefurlOption" onClick="printOption('userefurlOption')" ><?php echo $this->translate('Use Ref URL / URL'); ?></button>                     
	                      </div>
	                      <input type="checkbox" value="uploadoffer" id="uploadoffercheck" name="uploadoffercheck" style="display:none;" checked="checked">
	                        <div class="mainpage-content-right-inner-right-other uploadOfferMessage"></div>
	                      <span id="offerLogoId">
	                      </span>
	                      <div class="mainpage-content-right-inner-left-other" id="uploadofferDiv">
	                      <input type="file" class="ignore"  name="uploadoffer" id = "uploadoffer" onchange="checkFileType(event)"/>
	                      </div>
	                       <input type="checkbox" value="offerrefurl" id="offerrefurlcheck" name="offerrefurlcheck" style="display:none;">
	                        <div class="mainpage-content-right-inner-right-other offerrefurlMessage"></div>
	                      <div class="mainpage-content-right-inner-left-other" id="offerrefurlDiv" style="display:none;">
	                      <input type="text" class="span3" name="offerrefurlPR" id = "offerrefurlPR" placeholder="Ref url" />
	                      </div>
                    </span>  
                  </div>
                  
                </div>
            </div>
            <div class="mainpage-content">
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Title'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                            <input type="text" id="addofferTitle" name="addofferTitle" maxlength="60" placeholder="This account is important, etc" class="span3 mbot bbot">
                            <input type="text" disabled="" placeholder="<?php echo $this->translate("Usergenerated offer title length 60 characters");?>" id="metaTextLeft" class="input-xlarge disabled btop word-count">
                        </div>
                    </div>
                </div>
                <div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Deeplinking is'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                    	<div data-toggle="buttons-checkbox" class="btn-group ">
                        <button type="button" id="deepLinkOnbtn" class="btn"><?php echo $this->translate('On'); ?></button>                   
                        <button type="button" id="deepLinkoofbtn" style="border-radius:  0 4px 4px 0 ;" class="btn mr10 btn-primary"><?php echo $this->translate('Off'); ?></button>
  						<input type="checkbox" name="deepLinkStatus" value="1" id="deepLinkStatus" style="display:none;">                                   
                       </div>
                        
                    </div>
                                       
                </div>
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Ref URL'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                    	<div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                        	<input type="text" id="offerRefUrl"  name = "offerRefUrl"  placeholder="Ref. Url" class="span3">
                        </div>
                    </div>
                        
                </div>
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Description'); ?></strong></label></div>
                    
                </div>
                <div class="mainpage-content-line" id="termsAndCondition">
                <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                            <textarea id="couponInfo" name="description" rows="7"   placeholder="Description" class="span3 mbot bbot ignore"></textarea>
                        </div>
                    </div>
 
            </div>
           </div>
            
			 <div class="mainpage-content">
            	<div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Start Date'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                    	<div class="mainpage-content-right-inner-right-other dateValidationMessage1"></div>
                    	
	                        <div class="mainpage-content-right-inner-left-other" style="width: 269px ! important;">
	                        	<div data-date-format="dd-mm-yyyy" data-date="<?php echo date('d-m-Y');?>" id="dp3" class="input-append date">
	                        		<input readonly="readonly" type="text"  style="width:120px !important;" value="<?php echo date('d-m-Y');?>"  placeholder="Sunday, April 1" class="span2 ignore2" id="offerStartDate" name="offerStartDate">
	                        			<span class="add-on"><i class="icon-th"></i></span>
								</div>
			                     <div class="input-append bootstrap-timepicker-component" style="display: inline-block;">
			                          <input style='width: 120px!important;' readonly="readonly" type="text" id="offerstartTime" name="offerstartTime" class="input-small timepicker-default ignore2"><span class="add-on" style="margin-left: 3px;"><i class="icon-time"></i></span>
			                     </div>
	                        </div>
                        
                    </div>
                                       
                </div>
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('End Date'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                    	<div class="mainpage-content-right-inner-right-other dateValidationMessage2"></div>
	                        <div class="mainpage-content-right-inner-left-other" style="width: 269px ! important;">
	                        	<div data-date-format="dd-mm-yyyy" data-date="<?php echo @date("d-m-Y", $twoMonthsLater);?>" id="dp4" class="input-append date">
	                        		<input readonly="readonly"  type="text" style="width:120px !important;" value="<?php echo date('d-m-Y');?>" placeholder="Sunday, April 1" id="offerEndDate" name="offerEndDate" class="span2 ignore2">
	                        	<span class="add-on"><i class="icon-th"></i></span>
								</div>	
		                    	<div class="input-append bootstrap-timepicker-component" style="display: inline-block;">
		                           <input style='width: 120px!important;' readonly="readonly" type="text" name="offerendTime" id="offerendTime" class="input-small timepicker-default ignore2"><span class="add-on" style="margin-left: 3px;"><i class="icon-time"></i></span>
		                         </div>
	                        </div>
                     </div>
                                       
                </div>
                
            </div>
            <!-- <div class="mainpage-content">
            	<div class="mainpage-content-line">
                    <div class="mainpage-content-left">
                    <label><strong><?php // echo $this->translate('Attach to pages'); ?></strong></label>
                    </div>
                    <div class="mainpage-content-right">
                    	
                        	<div class="web-address-list multiselect">
                        	<ul>
                        	<?php // for($i=0;$i<count($this->pages);$i++){?>
                        	<li class="list_1" style ="font-weight:normal;">
                        		<input type="checkbox" id="attachedPage-<?php // echo $this->pages[$i]['id']; ?>"  value="<?php // echo $this->pages[$i]['id']; ?>" name="attachedpages[]" style="display: none;"> &nbsp;<?php //echo $this->pages[$i]['pageTitle']; ?>
                        	</li>
                        	<?php // }?>
                        	</ul>
                        	</div>
                        
                    </div>
                                       
                </div>
 
            </div>-->
            <div class="mainpage-content-colorbox">
            	<button type="submit" class="btn btn-large btn-primary fl"><?php echo $this->translate('SAVE'); ?></button>
                <a href="<?php echo HTTP_PATH; ?>admin/usergeneratedoffer" class="fl m10"><strong class="ml10"><?php echo $this->translate('CANCEL'); ?></strong></a>
                <!--<a id="deleteButton" href="javascript:void(0);"  onclick="deleteOffer(event);" class="fl red mt10"><strong><?php echo $this->translate('DELETE'); ?></strong></a>  -->
            </div>
            <input type="hidden" name="offerId" id="offerId" value="<?php echo $this->offerId; ?>"> 
         </form>   
            <!-- /poststuff -->
            <h1><?php echo $this->translate('Votes & Savings');?></h1>
            <table class="table table-bordered table-striped" id="voteListTable">
                <thead>
                  <tr>
                  	<th><?php echo $this->translate('Date'); ?></th>
                    <th><?php echo $this->translate('Vote');?></th>
                    <th><?php echo $this->translate('Money Saved');?></th>
                    <th><?php echo $this->translate('Product');?></th>
                    <th><?php echo $this->translate('Delete');?></th>
                  </tr>
                </thead>  
                  <?php if(count($this->offerVoteList) != 0 ){ ?>
                  <?php for($i=0;$i<count($this->offerVoteList);$i++){?>
                  <tr>
                  	<td><?php echo date('d-m-Y',strtotime($this->offerVoteList[$i]['date'])); ?></td>
                  	<td><?php echo $this->offerVoteList[$i]['vote']; ?></td>
                  	<td>&euro;<?php echo number_format($this->offerVoteList[$i]['moneySaved'],2); ?></td>
                  	<td><?php echo $this->offerVoteList[$i]['product']; ?></td>
                  	<td><a href="#" onClick="deleteVotes(<?php echo $this->offerVoteList[$i]['id']; ?>, <?php echo $this->offerId; ?>);"><?php echo $this->translate('Delete')?></a></td>  
                  </tr>
                  <?php }
		            } else {
		                	?>
		            <tr>
                  	<td colspan="5">No Record Found!</td>
                  
                   </tr>    	
		                	<?php 
		                }
		                
                  ?>
                
             </table>
            
        </div>