<?php
$footer = FrontEnd_Helper_viewHelper::getFooterData();
?>
<footer id="footer">
    <div class="bottom-panel">
        <div class="container" id ="footer-signup-form"></div>
    </div>
    <div class="container bottom-nav">
        <div class="row">
            <?php echo $footer['middleColumn1'];?>
            <?php echo FrontEnd_Helper_viewHelper::replaceStringVariable($footer['middleColumn2']);?>
            <?php echo $footer['middleColumn3'];?>
        </div>
    </div>
    <div class="container add-block">
    <?php echo $footer['middleColumn4'];?>
    <?php echo $footer['bottomFooter'];?>
    </div>
</footer>