<!DOCTYPE html>
<html>
<head>
<?php
if (FrontEnd_Helper_LayoutContent::loadVWOScript() === true) :
    echo $this->render('partials/_vwo_script.phtml');
endif;
?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $this->landingPage->getMetaTitle(); ?></title>
    <meta http-equiv="Content-type" content="text/html; charset=UTF-8" >
    <meta name="robots" content="noindex,nofollow" />
    <meta name="description" content="<?php echo $this->landingPage->getMetaDescription(); ?>">
    <?php
        $this->headLink(FrontEnd_Helper_LayoutContent::loadFavicon());
        echo $this->render('landingpage/layout_css.phtml');
    ?>
    <script type="text/javascript">
        dataLayer = [];
        function gtmDataBuilder(eventName, variant, clickedElement, eventType, eventId, isExpired) {
            var gtmData = {
                'event' : eventName,
                'variant' : variant,
                'clickedElement' : clickedElement,
                'sourceType' : 'glp'
            };
            if ( 'Retailer' == eventType ) {
                gtmData['retailerId'] = eventId;
            } else {
                gtmData['offerId'] = eventId;
                gtmData['isExpired'] = isExpired;
            }
            dataLayer.push(gtmData);
            return true;
        }
    </script>
    <script type="text/javascript">
        function OpenInNewTab(url)
        {
            var windowObject=window.open(url, '_blank');
            windowObject.focus();
        }
    </script>
</head>
<body>
<?php echo FrontEnd_Helper_LayoutContent::loadGoogleTagManager(); ?>
<?php
$httpScheme = FrontEnd_Helper_viewHelper::getServerNameScheme();
$viewPath = APPLICATION_PATH . '/views/';
$partialsPath = 'landingpage/';

if(LOCALE == ''):
    $logoCssClass = 'logo kortingscode';
    $logoPath = HTTP_PATH.'public/images/kortingscode-logo.png';
    $websiteName = 'http://'.$httpScheme.'.kortingscode.nl';
else :
    $logoCssClass = 'logo flipit';
    $logoPath = HTTP_PATH.'public/images/flipit-logo-'.LOCALE.'.png';
    $websiteName = 'http://'.$httpScheme.'.flipit.com/'.LOCALE;
    $localeViewPath = APPLICATION_PATH . '/modules/'. LOCALE .'/views/';
    $localePartialPath = $localeViewPath.'scripts/landingpage/';
endif;

$landingPageHelper = new FrontEnd_Helper_LandingPageFunctions();
$count = 1;
$numOfOffersBeforeSignUpForm = 6;
$offersCount = count($this->offers);
$offerPartial = new FrontEnd_Helper_OffersPartialFunctions();
$column1 = '';
$column2 = '';
$column3 = '';
$column4 = '';
$column5 = '';
$column6 = '';
foreach ($this->offers as $offer) {
    $offer = (object)$offer;
    $esiLocale = LOCALE != 'en' ? LOCALE . '/' : '';

    $daysTillOfferExpires = $offerPartial->getDaysTillOfferExpires($offer->endDate);
    $offerBottomDaysTillExpireText = '';
    if ($daysTillOfferExpires <= 3) {
        $offerBottomDaysTillExpireText = $landingPageHelper->getDaysTillExpire($daysTillOfferExpires);
    }

    $termsAndConditions = $offerPartial->getOfferTermsAndCondition($offer);

    $urlToShow = $offerPartial->getUrlToShow($offer);
    $isExpired = isset($currentOffer->expiredOffer) ? 'True' : 'False';
    $onClick = '';
    if (isset($offer->discountType) && $offer->discountType == 'CD') {
        $popupLink = $offerPartial->getPopupLink($offer, $urlToShow);
        $onClick .= "OpenInNewTab('".HTTP_PATH_LOCALE."glp/".$this->landingPage->getPermalink().$popupLink."');";
    }
    $clickoutURL = HTTP_PATH_LOCALE.'out/offer/'.$offer->id;

    $defaultText = '';
    if ($offer->userGenerated == '1') {
        $websiteName = FrontEnd_Helper_viewHelper::getWebsiteName($esiLocale);
        $defaultText = FrontEnd_Helper_viewHelper::__translate(
            'This code has been added by one of our users and not by the [websiteName] deal hunters'
        );
        $defaultText = str_replace('[websiteName]', $websiteName, $defaultText);
    }

    $offerDiv = '';
    if (isset($offer->discountType) && $offer->discountType == 'CD') {
        $gtmTitleClick = "gtmDataBuilder('voucherClickout', 'Code', 'Title', 'Offer', ".$offer->id.", '".$isExpired."');";
        $gtmButtonClick = "gtmDataBuilder('voucherClickout', 'Code', 'Button', 'Offer', ".$offer->id.", '".$isExpired."');";
        $offerDiv ='<a rel="nofollow" href="'.$clickoutURL.'" onclick="'.$gtmTitleClick.$onClick.'">
                        <h2 class="common-height">'.$offer->title.'</h2>
                    </a>
                    <a rel="nofollow" href="'.$clickoutURL.'" onclick="'.$gtmButtonClick.$onClick.'">
                        <div id="offerButton'.$offer->id.'" class="buttons offer-teaser-button-wrapper">
                            <div class="offer-teaser-button-wrapper-inner">
                                <span class="offer-teaser-button kccode">
                                '.FrontEnd_Helper_viewHelper::__translate('Bekijk de korting').'
                                </span>
                                <span class="show-code">'.
                                    FrontEnd_Helper_OffersPartialFunctions::generateRandomCharactersForOfferTeaser(4)
                                .'</span>
                                <span class="blue-corner"></span>
                            </div>
                        </div>
                    </a>
                    <div class="the-code" id="offerCodeDiv'.$offer->id.'">
                        <strong class="code-value">'.$offer->couponCode.'</strong>
                    </div>';
    } elseif (isset($offer->discountType) && $offer->discountType == 'SL') {
        $gtmTitleClick = "gtmDataBuilder('voucherClickout', 'Deal', 'Title', 'Offer', ".$offer->id.", '".$isExpired."');";
        $gtmButtonClick = "gtmDataBuilder('voucherClickout', 'Deal', 'Button', 'Offer', ".$offer->id.", '".$isExpired."');";
        $offerDiv = '<a rel="nofollow" href="'.$clickoutURL.'" onclick="'.$gtmTitleClick.$onClick.'" target="_blank">
                        <h2 class="common-height">'.$offer->title.'</h2>
                    </a>
                    <div id="offerButton'.$offer->id.'">
                        <div class="btn-blue-wrapper">
                            <a target="_blank" rel="nofollow" vote="0" href="'.$clickoutURL.'"
                            class="btn-code" id="'.$offer->id.'" onclick="'.$gtmButtonClick.'">
                                '.FrontEnd_Helper_viewHelper::__translate('Bekijk deze korting').'
                            </a>
                        </div>
                    </div>';
    } else {
        $gtmTitleClick = "gtmDataBuilder('voucherClickout', 'Deal', 'Title', 'Offer', ".$offer->id.", '".$isExpired."');";
        $gtmButtonClick = "gtmDataBuilder('voucherClickout', 'Deal', 'Button', 'Offer', ".$offer->id.", '".$isExpired."');";
        $offerDiv = '<a rel="nofollow" href="'.$clickoutURL.'" onclick="'.$gtmTitleClick.$onClick.'" target="_blank">
                        <h2 class="common-height">'.$offer->title.'</h2>
                    </a>
                    <div id="offerButton'.$offer->id.'">
                        <div class="btn-blue-wrapper">
                            <a rel="nofollow" target="_blank" vote="0" href="'.$urlToShow.'"
                            class="btn-code" id="'.$offer->id.'" onclick="'.$gtmButtonClick.'">
                                '.FrontEnd_Helper_viewHelper::__translate('Bekijk deze korting').'
                            </a>
                        </div>
                    </div>';
    }

    $termsAndConditionsLink = '<span class="">&nbsp;</span>';
    $termsAndConditionsDiv = "";
    if($termsAndConditions != '' || $offer->userGenerated == 1) {
        $termsAndConditionsLink =  '<span class="link-terms">
                                        <a id="termAndConditionLink'.$offer->id.'"
                                            onclick="showTermAndConditions('.$offer->id.')" class="terms"
                                            href="javascript:void(0);">
                                            '.FrontEnd_Helper_viewHelper::__translate('Terms &amp; Conditions').'
                                        </a>
                                    </span>
                                    ';

        if (empty($defaultText)) {
            $termsText = $this->translate('Terms and Conditions');
        } else {
            $termsText = '<span class="social-term-font">' .$defaultText.'</span>';
        }

        $termsAndConditionsDiv = '<div class="terms-block" id="termAndConditions'.$offer->id.'">
                                        <div class="term-and-condition">'.$termsText.'</div>
                                        <ol class="num-list">'.$termsAndConditions.'</ol>
                                    </div>';
    }

    $offerPanel = '';
    $offerPanel ='<div class="panel panel-default">
                    <div class="panel-body">
                        '.$offerDiv.'
                    </div>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                                '.$offerBottomDaysTillExpireText.'
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 text-right">
                                '.$termsAndConditionsLink.'
                            </div>
                        </div>
                    </div>
                    '.$termsAndConditionsDiv.'
                </div>
                ';

    if ($count <= $numOfOffersBeforeSignUpForm) {
        if ($count % 3 == 1) {
            $column1 .= $offerPanel;
        } elseif ($count % 3 == 2) {
            $column2 .= $offerPanel;
        } elseif ($count % 3 == 0) {
            $column3 .= $offerPanel;
        }
    } else {
        if ($count % 3 == 1) {
            $column4 .= $offerPanel;
        } elseif ($count % 3 == 2) {
            $column5 .= $offerPanel;
        } elseif ($count % 3 == 0) {
            $column6 .= $offerPanel;
        }
    }
    $count++;
}
?>
<div id="wrapper">
    <header id="header">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                    <div class="<?php echo $logoCssClass; ?>">
                        <img src="<?php echo $logoPath; ?>"
                             alt="<?php echo FrontEnd_Helper_viewHelper::__form('form_website logo alt');?>"
                             title="<?php echo FrontEnd_Helper_viewHelper::__form('form_website logo title');?>"
                             height="50" />
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-8 col-lg-8 text-right">
                    <span class="slogan"><?php echo FrontEnd_Helper_viewHelper::__translate('Number 1 saving platform worldwide!'); ?></span>
                </div>
            </div>
        </div>
    </header>
<main id="main">
    <div class="container">
        <div class="heading-block">
            <div class="logo-holder">
                <?php
                    echo $landingPageHelper->getShopHeader($this->landingPage->getShop());
                ?>
            </div>
            <div class="description">
                <h1><?php echo $this->landingPage->getTitle(); ?></h1>
                <h2><?php echo $this->landingPage->getSubTitle(); ?></h2>
                <?php
                $offersAdded = '';
                if (!empty($this->offersAddedInShop) && $this->offersAddedInShop['offersInfo'] != '') :
                    $offersAdded = '<li><span><i class="icon-timer"></i>  '
                        .FrontEnd_Helper_viewHelper::__translate('This '.$this->offersAddedInShop['type'])
                        . ' '
                        .$this->offersAddedInShop['offersInfo']['amountOffers']
                        .' '
                        .FrontEnd_Helper_viewHelper::__translate('offers have been added').'</span></li>';
                endif;
                ?>
                <ul class="action-list">
                   <?php echo $offersAdded; ?>
                    <li>
                        <span class="icon-check-circle"></span><?php echo count($this->offers).' '.FrontEnd_Helper_viewHelper::__translate('current offers'); ?>
                    </li>
                </ul>
            </div>
        </div>
        <div class="discount-blocks">
            <div class="row same-height">
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4"><?php echo $column1; ?></div>
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4"><?php echo $column2; ?></div>
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4"><?php echo $column3; ?></div>
            </div>
            <?php
            echo $this->partial('partials/_landingpage_signup.phtml', array());
            if ($offersCount > $numOfOffersBeforeSignUpForm):
            ?>
            <div class="row same-height">
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4"><?php echo $column4; ?></div>
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4"><?php echo $column5; ?></div>
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4"><?php echo $column6; ?></div>
            </div>
            <?php
            endif;
            ?>
            <?php if ($this->landingPage->getContent() != '' ): ?>
            <article class="about">
                <?php echo $this->landingPage->getContent(); ?>
            </article>
            <?php endif; ?>
        </div>
    </div>
</main>
</div>
<?php
$partialViewPath = new Zend_View();
if(isset($localePartialPath) && file_exists($localePartialPath .  '_footer.phtml')):
    $partialViewPath->setBasePath($localeViewPath);
    echo $partialViewPath->render($partialsPath. '_footer.phtml');
else:
    $partialViewPath->setBasePath($viewPath);
    echo $partialViewPath->render($partialsPath. '_footer.phtml');
endif;

if(isset($localePartialPath) && file_exists($localePartialPath . '_pop_up.phtml')):
    $partialViewPath->setBasePath($localeViewPath);
    echo $partialViewPath->render($partialsPath. '_pop_up.phtml');
else :
    $partialViewPath->setBasePath($viewPath);
    echo $partialViewPath->render($partialsPath. '_pop_up.phtml');
endif;
?>
<?php
echo $this->render('landingpage/layout_js.phtml');
?>
</body>
</html>