<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $this->landingPage->getMetaTitle(); ?></title>
    <meta http-equiv="Content-type" content="text/html; charset=UTF-8" >
    <meta name="description" content="<?php echo $this->landingPage->getMetaDescription(); ?>">
    <link rel="stylesheet" href="/public/css/landingpages/all.css">
    <link rel="stylesheet/less" href="/public/css/landingpages/landingPage.less">
    <script type="text/javascript">
        function OpenInNewTab(url)
        {
            var windowObject=window.open(url, '_blank');
            windowObject.focus();
        }
    </script>
</head>
<body>
<?php
$httpScheme = FrontEnd_Helper_viewHelper::getServerNameScheme();
$viewPath = APPLICATION_PATH . '/views/';
$partialsPath = 'landingpage/';

if(LOCALE == ''):
    $logoCssClass = 'logo kortingscode';
    $logoPath = HTTP_PATH.'public/images/kortingscode-logo.png';
    $websiteName = 'http://'.$httpScheme.'.kortingscode.nl';
else :
    $logoCssClass = 'logo flipit';
    $logoPath = HTTP_PATH.'public/images/flipit-logo-'.LOCALE.'.png';
    $websiteName = 'http://'.$httpScheme.'.flipit.com/'.LOCALE;
    $localeViewPath = APPLICATION_PATH . '/modules/'. LOCALE .'/views/';
    $localePartialPath = $localeViewPath.'scripts/landingpage/';
endif;
?>
<div id="wrapper">
<header id="header">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                <div class="logo"><a href="<?php echo $websiteName;?>"><img src="<?php echo $logoPath; ?>" alt="<?php echo FrontEnd_Helper_viewHelper::__form('form_website logo alt');?>" title="<?php echo FrontEnd_Helper_viewHelper::__form('form_website logo title');?>" width="199" height="50"></a></div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-8 col-lg-8 text-right">
                <span class="slogan">Number 1 saving platform worldwide!</span>
            </div>
        </div>
    </div>
</header>
<main id="main">
<div class="container">
<div class="heading-block">
    <div class="logo-holder">
        <?php
            $landingPageHelper = new FrontEnd_Helper_LandingPageFunctions();
            echo $landingPageHelper->getShopHeader($this->landingPage->getShop());
        ?>
    </div>
    <div class="description">
        <h1><?php echo $this->landingPage->getTitle(); ?></h1>
        <?php
        $offersAdded = '';
        if (!empty($this->offersAddedInShop) && $this->offersAddedInShop['offersInfo'] != '') {
            $offersAdded = '<li><span><i class="icon-timer"></i>  '
                .FrontEnd_Helper_viewHelper::__translate('This '.$this->offersAddedInShop['type'])
                . ' '
                .$this->offersAddedInShop['offersInfo']['amountOffers']
                .' '
                .FrontEnd_Helper_viewHelper::__translate('offers have been added').'</span></li>';
        }
        ?>
        <ul class="action-list">
           <?php echo $offersAdded; ?>
            <li>
                <span class="icon-check-circle"></span><?php echo count($this->offers).' '.FrontEnd_Helper_viewHelper::__translate('current offers'); ?>
            </li>
        </ul>
    </div>
</div>
<div class="discount-blocks">
    <?php $count = 1;
    $offersCount = count($this->offers);
    $offerPartial = new FrontEnd_Helper_OffersPartialFunctions();
    ?>
    <?php foreach($this->offers as $offer) :
        $offer = (object) $offer;
        $esiLocale = LOCALE != 'en' ? LOCALE . '/' : '';
        $daysTillOfferExpires = $offerPartial->getDaysTillOfferExpires($offer->endDate);
        $offerBottomDaysTillExpireText = '';
        if ($daysTillOfferExpires <= 3) {
            $offerBottomDaysTillExpireText = $landingPageHelper->getDaysTillExpire($daysTillOfferExpires);
        }
        $termsAndConditions = $offerPartial->getOfferTermsAndCondition($offer);
        $urlToShow = $offerPartial->getUrlToShow($offer);
        $onClick = '';
        if (isset($offer->discountType) && $offer->discountType == 'CD') {
            $popupLink = $offerPartial->getPopupLink($offer, $urlToShow);
            $onClick .= "OpenInNewTab('".HTTP_PATH_LOCALE.'gad/'.$this->landingPage->getPermalink().$popupLink."');";
        }
        $clickoutURL = HTTP_PATH_LOCALE.'out/offer/'.$offer->id;
        $defaultText = '';
        if ($offer->userGenerated == '1') {
            $websiteName = FrontEnd_Helper_viewHelper::getWebsiteName($esiLocale);
            $defaultText = FrontEnd_Helper_viewHelper::__translate(
                'This code has been added by one of our users and not by the [websiteName] deal hunters'
            );
            $defaultText = str_replace('[websiteName]', $websiteName, $defaultText);
        }
        ?>
        <?php if($count==1 || $count==7): ?>
            <div class="row same-height">
        <?php endif; ?>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a rel="nofollow" href="<?php echo $clickoutURL; ?>" onclick="<?php echo $onClick; ?>">
                        <h2 class="common-height offer-title"><?php echo $offer->title; ?></h2>
                    </a>
                    <?php if(isset($offer->discountType) && $offer->discountType == 'CD' ): ?>
                        <a rel="nofollow" href="<?php echo $clickoutURL; ?>" onclick="<?php echo $onClick; ?>">
                            <div id="offerButton<?php echo $offer->id; ?>" class="buttons offer-teaser-button-wrapper">
                                <div class="offer-teaser-button-wrapper-inner">
                                    <span class="offer-teaser-button kccode">Bekijk de code</span>
                                    <span class="show-code"><?php echo FrontEnd_Helper_OffersPartialFunctions::generateRandomCharactersForOfferTeaser(4); ?></span>
                                    <span class="blue-corner"></span>
                                </div>
                            </div>
                        </a>
                        <div class="the-code" id="offerCodeDiv<?php echo $offer->id ;?>">
                            <strong class="code-value"><?php echo $offer->couponCode;?></strong>
                        </div>
                    <?php else: ?>
                        <div id="offerButton<?php echo $offer->id; ?>">
                            <div class="btn-blue-wrapper">
                                <a onclick="<?php echo $onClick; ?>" rel="nofollow" vote="0" href="<?php echo $clickoutURL; ?>" class="btn-code " id="<?php echo $offer->id; ?>">
                                    Bekijk deze korting</a>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
                <div class="panel-footer">
                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                            <?php echo $offerBottomDaysTillExpireText; ?>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 text-right">
                            <?php if($termsAndConditions != '' || $offer->userGenerated == 1): ?>
                                <span class="link-terms">
                                    <a id="termAndConditionLink<?php echo $offer->id; ?>"
                                       onclick="showTermAndConditions(<?php echo $offer->id; ?>)" class="terms"
                                       href="javascript:void(0);">
                                        Terms &amp; conditions
                                    </a></span>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <div class="terms-block" id='termAndConditions<?php echo $offer->id; ?>'>
                    <div class='term-and-condition'>
                    <?php
                    if (empty($defaultText)) {
                        echo $this->translate('Terms &amp; Conditions');
                    } else {
                        echo '<span class="social-term-font">' .$defaultText.'</span>';
                    }
                    ?>
                    </div>
                    <ol class="num-list">
                        <?php echo $termsAndConditions;?>
                    </ol>
                </div>
            </div>
        </div>
    <?php if($count==6 || ($count<6 && $count == $offersCount)): ?>
        </div>
        <?php echo $this->partial('partials/_landingpage_signup.phtml', array());
        endif;
        $count++;
    endforeach; ?>
</div>
<?php if( 0 == $offersCount) :
    echo $this->partial('partials/_landingpage_signup.phtml', array());
endif; ?>

<article class="about">
    <?php echo $this->landingPage->getContent(); ?>
</article>
</div>
</div>
</main>
</div>
<?php
$partialViewPath = new Zend_View();
if(isset($localePartialPath) && file_exists($localePartialPath .  '_footer.phtml')):
    $partialViewPath->setBasePath($localeViewPath);
    echo $partialViewPath->render($partialsPath. '_footer.phtml');
else:
    $partialViewPath->setBasePath($viewPath);
    echo $partialViewPath->render($partialsPath. '_footer.phtml');
endif;

if(isset($localePartialPath) && file_exists($localePartialPath . '_pop_up.phtml')):
    $partialViewPath->setBasePath($localeViewPath);
    echo $partialViewPath->render($partialsPath. '_pop_up.phtml');
else :
    $partialViewPath->setBasePath($viewPath);
    echo $partialViewPath->render($partialsPath. '_pop_up.phtml');
endif;
?>
<script type="text/javascript">
    var domainName = "<?php echo HTTP_PATH; ?>";
    var LOCALE = "<?php echo LOCALE; ?>";
    var HOST_PATH_LOCALE = "<?php echo HTTP_PATH_LOCALE; ?>";
</script>
<script type="text/javascript" src="/public/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="/public/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/public/js/front_end/jquery.validate.js"></script>
<script type="text/javascript" src="/public/js/front_end/modalPopLite.min.js"></script>
<script type="text/javascript" src="/public/js/front_end/zeroclipboard/ZeroClipboard.js"></script>
<script type="text/javascript" src="/public/js/front_end/partialOffer.js"></script>
<script type="text/javascript" src="/public/js/front_end/bigtext.js"></script>
<script type="text/javascript" src="/public/js/landingpages/jquery.landingPage.js"></script>
<script type="text/javascript" src="/public/js/front_end/less/dist/less-1.7.0.js"></script>
</body>
</html>