<div class="carousel-area">
    <div class="container">
        <div class="flexslider carousel">
            <div class="mask">
                <div class="slideset">
                <?php
                foreach ($this->popularStores as $popularStore) { 
                    $popularStoreImage =
                        PUBLIC_PATH_CDN
                        .ltrim($popularStore['popularshops']['logo']['path'], '/')
                        .'thum_medium_'
                        .$popularStore['popularshops']['logo']['name'];  
                    ?>
                    <div class="slide">
                        <a href="<?php echo HTTP_PATH_LOCALE.$popularStore['popularshops']['permaLink'];?>">
                            <img class="lazy" data-original="<?php echo $popularStoreImage; ?>"
                            width ="100" height= "50"
                            alt="<?php echo $popularStore['popularshops']['name']; ?>"
                            title="<?php echo $popularStore['popularshops']['name']; ?>">
                            <noscript>
                                <img src="<?php echo $popularStoreImage; ?>" width ="100" height = "50"
                                alt="<?php echo $popularStore['popularshops']['name']; ?>"
                                title="<?php echo $popularStore['popularshops']['name']; ?>">
                            </noscript>
                        </a>
                    </div>
                    <?php
                }
                ?>      
                </div>
            </div>
        </div>
    </div>
</div>