<?php

/**
 * refOfferCategoryTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleChapterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object refOfferCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArticleChapter');
    }
}
