<?php

/**
 * ChainTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChainTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChainTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Chain');
    }
}
