<?php

/**
 * CodeAlertVisitorsTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CodeAlertVisitorsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CodeAlertVisitorsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CodeAlertVisitors');
    }
}
