<?php

/**
 * CodeAlertQueueTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CodeAlertQueueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CodeAlertQueueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CodeAlertQueue');
    }
}
