<?php

/**
 * CodeAlertSettingsTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CodeAlertSettingsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CodeAlertSettingsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CodeAlertSettings');
    }
}
