<?php

/**
 * HowToUseSmallImageTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HowToUseSmallImageTable extends ImageTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object HowToUseSmallImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HowToUseSmallImage');
    }
}
