<?php

/**
 * HowToUseBigImageTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HowToUseBigImageTable extends ImageTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object HowToUseBigImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HowToUseBigImage');
    }
}
