<?php

/**
 * menuTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class menuTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object menuTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('menu');
    }
}
