<?php

/**
 * MoneysavingArticle
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##Er.kundal## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */

class MoneysavingArticle extends BaseMoneysavingArticle
{
    public static function searchTopTenSaving($keyword, $flag)
    {
        $lastdata=self :: getSaving();
        if(sizeof($lastdata)>0){
            for($i=0;$i<sizeof($lastdata);$i++){
                $codevalues[$i]=$lastdata[$i]['articleId'];
            }

            $codevalues = implode(",", $codevalues);

        }else{
            $codevalues = '0';
        }

        $data = Doctrine_Query::create()->select('o.title as title')
        ->from("Articles o")->where('o.deleted=' . "'$flag'")
        ->andWhere("o.title LIKE ?", "$keyword%")
        ->andWhere("o.id NOT IN ($codevalues)")
        ->orderBy("o.title ASC")->limit(10)->fetchArray();
        return $data;
    }


    /**
     * Get article for Money saving article from database
     * @author Er.Kundal
     * @version 1.0
     * @return array $data
     */
    public static function getSaving()
    {
        $data = Doctrine_Query::create()
        ->select('p.id,o.title,p.type,p.position,p.articleId')
        ->from('MoneysavingArticle p')->leftJoin('p.article o')
        ->orderBy('p.position ASC')->fetchArray();

        return $data;

    }


    /**
     * add Article in Money Saving Article
     * @author Er.Kundal
     * @version 1.0
     * @return integer $flag
     */
    public static function addSaving($title)
    {
        //find Money Saving Article by title
        $title = addslashes($title);
        $article = Doctrine_query::create()->from('Articles')
        ->where('title=' . "'$title'")->limit(1)->fetchArray();
        $flag = '2';


        if (sizeof($article) > 0) {

            //checkArticle exist or not
            $pc = Doctrine_Core::getTable('MoneysavingArticle')
            ->findBy('articleId', $article[0]['id']);

            if (sizeof($pc) > 0) {


            } else {

                $flag = '1';
                //find last postion  from database
                $data = Doctrine_Query::create()->select('p.position')
                ->from('MoneysavingArticle p')->orderBy('p.position DESC')
                ->limit(1)->fetchArray();
                if(sizeof($data) > 0){

                    $NewPos = $data[0]['position'];

                } else {

                    $NewPos = 1;
                }				//add new Article if not exist in datbase
                $pc = new MoneysavingArticle();
                $pc->type = 'MN';
                $pc->articleId = $article[0]['id'];
                $pc->position = (intval($NewPos) + 1);
                $pc->save();
                $flag = $pc->toArray();
            }
        }
        $art_id = $article[0]['id'];
        $authorId = self::getAuthorId($art_id);

        $uid = $authorId[0]['authorid'];
        $mostreadkey ="all_". "mostread".$uid ."_list";
        FrontEnd_Helper_viewHelper::clearCacheByKeyOrAll($mostreadkey);

        FrontEnd_Helper_viewHelper::clearCacheByKeyOrAll('all_moneySaving_list');
        return $flag;
    }
    /**
     * delete Money Saving Article
     * @param integer $id
     * @param integer $position
     * @author Er.kundal
     * @version 1.0
     */

    public static function deleteSaving($id, $position)
    {
        if ($id) {
            //delete popular code from list
            $pc = Doctrine_Query::create()->delete('MoneysavingArticle')
            ->where('id=' . $id)->execute();
            //change position by 1 of each below element
            $q = Doctrine_Query::create()->update('MoneysavingArticle p')
            ->set('p.position', 'p.position -1')
            ->where('p.position >' . $position)->execute();
        }
        FrontEnd_Helper_viewHelper::clearCacheByKeyOrAll('all_moneySaving_list');

        $art_id = $id;
        $authorId = self::getAuthorId($art_id);

        @$uid = $authorId[0]['authorid'];
        @$mostreadkey ="all_". "mostread".$uid ."_list";
        @FrontEnd_Helper_viewHelper::clearCacheByKeyOrAll($mostreadkey);

        return true ;
    }


    /**
     * move up Money Saving Article from Article list
     * @param integer $id
     * @param integer $position
     * @author Er.kundal
     * @version 1.0
     */
    public static function moveUpSaving($id, $position)
    {
        $pos = (intval($position) - 1);
        //find prev element from database based of current
        $PrevPc = Doctrine_Core::getTable('MoneysavingArticle')
        ->findBy('position', $pos)->toArray();
        //change position of prev element with current
        //$flag =  1;
        if(count($PrevPc) > 0) {

            //$flag =2;
            $changePrevPc = Doctrine_Core::getTable('MoneysavingArticle')
            ->find($PrevPc[0]['id']);
            $changePrevPc->position = $position;
            $changePrevPc->save();
            //change position of current element with postition + 1
            $pc = Doctrine_Core::getTable('MoneysavingArticle')->find($id);
            $pc->position = $pos;
            $pc->save();
            FrontEnd_Helper_viewHelper::clearCacheByKeyOrAll('all_moneySaving_list');

            return true ;
        }
        return false ;
        //return $flag;
    }

    /**
     * move down popular Category from list
     * @param integer $id
     * @param integer $position
     * @author Er.kundal
     * @version 1.0
     */
    public static function moveDownSaving($id, $position)
    {
        $pos = (intval($position) + 1);
        //find next element from database based of current
        $PrevPc = Doctrine_Core::getTable('MoneysavingArticle')
        ->findBy('position', $pos)->toArray();
        //change position of next element with current
        if(count($PrevPc) > 0) {

            $changePrevPc = Doctrine_Core::getTable('MoneysavingArticle')
            ->find($PrevPc[0]['id']);
            $changePrevPc->position = $position;
            $changePrevPc->save();
            //change position of current element with postition - 1
            $pc = Doctrine_Core::getTable('MoneysavingArticle')->find($id);
            $pc->position = $pos;
            $pc->save();
            FrontEnd_Helper_viewHelper::clearCacheByKeyOrAll('all_moneySaving_list');

            return true ;
        }
            return false;
    }



    /**
     * Get article for Money saving article from database for front home page
     * @author Raman
     * @version 1.0
     * @return array $data
     */
    public static function getmoneySavingArticle($flag)
    {
        $data = Doctrine_Query::create()
        ->select('p.*,o.*,a.*')
        ->from('MoneysavingArticle p')
        ->leftJoin('p.article o')
        ->leftJoin('o.articleImage a')
        ->limit($flag)
        ->orderBy('p.position ASC')->fetchArray();

        return $data;
    }


    /**
     * Get user Id from Article id
     * @author Raman
     * @return array $userId
     * @version 1.0
     */
    public static function getAuthorId($artId)
    {
        $userId = Doctrine_Query::create()
        ->select('a.authorid')
        ->from("Articles a")
        ->where("a.id =$artId")
        ->fetchArray();

        return $userId;
    }


}
