<?php

/**
 * PopularCategoryTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PopularCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PopularCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PopularCategory');
    }
}
