<?php

/**
 * PopularArticlesTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PopularArticlesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PopularArticlesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PopularArticles');
    }
}
