<?php
/**
 * RoutePermalink
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##cbhopal## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class RoutePermalink extends BaseRoutePermalink
{
    /**
     * Retrieve permalink and exact link on the basis of REQUEST_URI
     * @author cbhopal
     * @version 1.0
     */
    public static function getRoute($permalink)
    {
        $permalink= trim($permalink, '/');
        $data = Doctrine_Query::create()
            ->select('r.permalink, r.exactlink')
            ->from('RoutePermalink r')
            ->where("r.permalink = ?", FrontEnd_Helper_viewHelper::sanitize($permalink))
            ->fetchArray();
        return $data;
    }
    public static function getPageProperties($permalink)
    {
        $permalink= trim($permalink, '/');
        $pageDetails = Doctrine_Query::create()
        ->select('p.id')
        ->from('Page p')
        ->where("permalink = ?", FrontEnd_Helper_viewHelper::sanitize($permalink))
        ->fetchArray();
        return $pageDetails;
    }
    public static function getPermalinks($exactLink)
    {
        $permalinks = Doctrine_Query::create()
        ->select('rp.permalink')->from('RoutePermalink rp')
        ->where("rp.exactlink='?'", FrontEnd_Helper_viewHelper::sanitize($exactLink))
        ->andWhere('deleted = 0')
        ->fetchArray();
        return $permalinks;
    }

    public static function getDefaultPageProperties($slug)
    {
        $data = Doctrine_Query::create()->select('p.*')
        ->from('Page p')
        ->where("slug = ?", $slug)
        ->fetchArray();
        return $data;
    }

    public static function updateRoutePermalink($permalink, $exactlink, $validatedPermalink)
    {
        Doctrine_Query::create()
            ->update('RoutePermalink p')
            ->set('p.permalink', "'".$permalink."'")
            ->set('p.type', "'SHP'")
            ->set('p.exactlink', "'".$exactlink."'")
            ->where('p.type = "SHP"')
            ->andWhere("p.permalink = '".$validatedPermalink."'")
            ->execute();
        return true;
    }

    public static function saveRoutePermalink($permalink, $exactlink)
    {
        $routePermalink = new RoutePermalink();
        $routePermalink->permalink = $permalink;
        $routePermalink->type = 'SHP';
        $routePermalink->exactlink = $exactlink;
        $routePermalink->save();
        return true;
    }

    public static function validatePermalink($permalink)
    {
        $validatedPermalink = Doctrine_Query::create()
            ->select('p.permalink')
            ->from('RoutePermalink p')
            ->where("p.permalink = '".$permalink."'")
            ->andWhere('p.type = "SHP"')
            ->fetchArray();
        return $validatedPermalink;
    }
}
