<?php

/**
 * SeenInTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeenInTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SeenInTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SeenIn');
    }
}
