<?php

/**
 * ShopHowToChapterTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopHowToChapterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShopHowToChapterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShopHowToChapter');
    }
}
