<?php

/**
 * SpecialTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SpecialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SpecialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Special');
    }
}
