<?php

/**
 * WebsiteTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WebsiteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WebsiteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Website');
    }
}
