<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link href="http://www.flipit.com" rel="canonical" />
<link href="<?php echo PUBLIC_PATH;?>flipit/css/splashpage.css" media="screen" rel="stylesheet" type="text/css" />
<link href="<?php echo PUBLIC_PATH;?>flipit/images/favicon.ico" rel="shortcut icon" type="image/x-icon" />
<script type="text/javascript" src="<?php echo PUBLIC_PATH;?>js/front_end/socialmedia.js"></script>
<meta name="msvalidate.01" content="44C2028411B932A2DCC28359FD20685F" />
<meta property="og:title" content="Flipit.com">
<meta property="og:description" content="Changing The Way We Save" />
<meta property="og:image" content="http://www.flipit.com/public/be/images/upload/media/flipit.png">
<meta property="og:url" content="http://www.flipit.com">
<meta property="og:site_name" content="Flipit.com" />
<meta name="description" content="Flipit offers a new way in saving money online in 7 languages. Use our local discount codes and saving tips for free." />

<title>Flipit.com | Changing The Way We Save</title>
</head>

<body>
        
  <div class="container">
    <div class="push"></div>
    <div class="nojsselectblock">
      <ul class="languages">
        <li><a href="http://www.flipit.com/be">Belgi&#235;</a></li>
        <li><a href="http://www.flipit.com/de">Deutschland</a></li>
        <li><a href="http://www.flipit.com/es">Espa&#241;a</a></li>
        <li><a href="http://www.flipit.com/fr">France</a></li>
        <li><a href="http://www.flipit.com/in">India</a></li>
        <li><a href="http://www.flipit.com/pl">Polska</a></li>
        <li><a href="http://www.flipit.com/ch">Schweiz</a></li>
      </ul>
    </div> 

    <div class="selectblock" style="display:none">
      <form name="form1aa" method="post" action="" id="form1a" align="center" >
        <div class="styled-select">
          <select name="country" id="href" onchange=" fill_language(document.form1aa.country.selectedIndex);" class="select1 styled-select">
            <option>Country</option>
            <option value="http://www.flipit.com/be">Belgi&#235;</option>
            <option value="http://www.flipit.com/de">Deutschland</option>
            <option value="http://www.flipit.com/es">Espa&#241;a</option>
            <option value="http://www.flipit.com/fr">France</option>
            <option value="http://www.flipit.com/in">India</option>
            <option value="http://www.flipit.com/pl">Polska</option>
            <option value="http://www.flipit.com/ch">Schweiz</option>
          </select>
        </div>
        <div class="styled-select">
          <select name="language" class="styled-select" >
            <option value="Language"  selected="selected">Language</option>
          </select>
        </div>
        <a class="btn" id="submitorder" type="button" onclick="javascript:goToProperPage();" href="javascript:void(0)">Go!</a>
      </form>
      <?php 
      $url = HTTP_PATH;;
      $title = $this->translate("");
      ?>
      <div class="thestory">
      First time on Flipit.com? Check out <a href="#" id="trigger">The Flipit.com Adventure</a><img src="<?php echo PUBLIC_PATH;?>flipit/images/arrow-small.png" />
        <div class="social">
          <div class='social-likes social-likes-new'>
            <div class='flike-outer'>
              <div id='fb-root'></div>
              <div class='fb-like' data-href='<?php echo $url; ?>' data-send='false' data-layout='button_count' data-width='50' data-show-faces='false'>&nbsp;
              </div>
            </div>
            <div class='flike-outer'>
              <a href='https://twitter.com/share' data-url='<?php echo $url; ?>' class='twitter-share-button'  data-lang='<?php echo LOCALE; ?>'></a>
            </div>
            <div class='flike-outer'>
              <div class='g-plusone'  data-href='<?php echo $url; ?>' data-size='medium' data-annotation='none'></div>
            </div>
          </div>
        </div>
      </div>
      <div id="target">

        <div class="adventure">
          <h2>Welcome. You have found us!</h2>
          <p>This adventure started more than a year ago. For quite some time, we have managed large couponing portals in Europe. But we felt we could still add more to the shopping experience. Don't you agree? Online shopping can be much more effective - cheaper and much more fun! This is exactly our ambition: to create a global couponing environment which adapts to your wishes and needs perfectly.</p>
          <p>How do we make this happen? Well, you decide. It might result in a geo-based couponing App for Google Glass, or a postal service that delivers customized coupons to your door. What we do know is that our developers are ready to build exactly what you want based on your reviews and feedback.</p>
          <p>We’re giving this journey a jumpstart by rolling out our 'starting' websites in 50 (!) local languages on this domain. Belgium and Poland are lucky enough to serve as our testing grounds. Other countries will follow shortly.</p>
          <p>Become part of our journey. Use our website, give us feedback and let's give our development team some work to do!</p>
          <p>Let's Flipit!</p>
          <p class="right"><i><a href="http://nl.linkedin.com/in/jochemvroom" target="_blank" rel="nofollow">- Jochem Vroom</a></i></p>
          <p class="right"><i>Founder Flipit.com</i></p>
    		</div>	
      </div>
    </div>
  </div>
  <div class="footerpush"></div>

</body>
<script>
document.getElementById('form1a').reset();
</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-17691171-3', 'flipit.com');
  ga('send', 'pageview');

</script>
<script type="text/javascript" src="<?php echo PUBLIC_PATH;?>flipit/js/jquery-1.9.1.min.js"></script> 
<script type="text/javascript" src="<?php echo PUBLIC_PATH;?>flipit/js/splashpage.js"></script>   
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "96dd1eba-e0de-4147-ae74-e2430944f8ef", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
</html>
