<?php
echo $this->doctype("XHTML1_RDFA");

// manage the kc_session_active by checking the front_login session, we need this cookie for Varnish

$lang_locale = Signupmaxaccount::getallmaxaccounts();
$lang = !empty($lang_locale[0]['locale']) ? $lang_locale[0]['locale'] : 'nl_NL';
$langArray = explode('_', $lang);
$language = $langArray[0];
?>
<html lang="<?php echo $language; ?>" xml:lang="<?php echo $language; ?>" xmlns="http://www.w3.org/1999/xhtml">

<head>
<?php


//set cononical 
if(isset($this->canonical)):

	$skipEnLocale = '';
	if(LOCALE!='en'){
		
		$skipEnLocale = HTTP_PATH_LOCALE;
	}else{
		
		$skipEnLocale = HTTP_PATH;
	}

	if($this->canonical=='' || $this->canonical==null):
		$this->headLink( array( 'rel' => 'canonical',
		'href' => rtrim($skipEnLocale, '/')));

	else:
	
		$this->headLink( array( 'rel' => 'canonical',
		'href' => $skipEnLocale. strtolower($this->canonical)));
	
	endif;
endif;
if($this->serverUrl() == 'http://admin.kortingscode.nl'){
	
	$this->headMeta()->appendName('robots', 'noindex, nofollow');
	header("Location: http://admin.kortingscode.nl/admin");

}else{
	if(isset($this->param) && $this->param != '' && $this->controllerName == 'search'):
		//it checks if search query is there in URL then add noindex on search page
		$this->headMeta()->appendName('robots', 'noindex, follow');
	elseif (strtolower($this->controllerName) == 'login' && strtolower($this->actionName == 'forgotpassword')):
		$this->headMeta()->appendName('robots', 'noindex, follow');
	else:
		//it checks if search query is not there in URL then add index on search page
	
		#add noindex for every page after first page
		if(Zend_Controller_Front::getInstance()->getRequest()->getParam('page' , null) > 1 ) :
			$this->headMeta()->appendName('robots', 'noindex, follow');
		else:
			# robot keyword property is set by any action 
			if($this->layout()->robotKeywords)
			{
				$this->headMeta()->appendName('robots', $this->layout()->robotKeywords);
			}else
			{
				$this->headMeta()->appendName('robots', 'index, follow');
			}
		endif;
	endif;
}
 
echo $this->headTitle();
echo $this->layout()->customHeader ;
echo $this->headLink( array( 'rel' => 'shortcut icon',
						'href' => HTTP_PATH . 'public/flipit/images/favicon.ico',
						'type' => 'image/x-icon' 
					   )
			   		);
		  // ->headLink( array( 'rel' => 'alternate',
				// 		'href' => 'http://www.flipit.com/'.LOCALE,
				// 		'hreflang' => str_replace("_","-", Zend_Registry::get('Zend_Locale') )
				// 	   ))

$fb = new Zend_View();
$fb->setScriptPath(APPLICATION_PATH . '/layouts/scripts/');
$fb->assign('fbtitle', $this->fbtitle);
$fb->assign('fbshareUrl', $this->fbshareUrl);
$fb->assign('fbImg', $this->fbImg);
echo $fb->render('fbmeta.phtml');
echo $this->headMeta();

echo $this->minifyHeadLink()
		->prependStylesheet("public/nz/css/style.css")
		->prependStylesheet("public/css/placeholder_polyfill.css")
		->prependStylesheet("public/css/bootstrap.min.css")    
		->prependStylesheet("public/css/bootstrap.css")
		->prependStylesheet("public/flipit/css/general_style.css")
		->prependStylesheet("public/css/front_end/style.css");
echo $this->headStyle();
echo $this->minifyHeadScript()->prependFile ("public/js/common.js" )
							  ->prependFile ("public/js/front_end/jquery-bigtext.js" )
    							  ->prependFile ("public/" . LOCALE . "/js/front_end/json/translation.js" )
							  ->prependFile ("public/" . LOCALE . "/js/front_end/json/shops.js" )
							  ->prependFile ("public/js/front_end/layout.js" )
							  ->prependFile ("public/js/Gettext.js" )
							  ->prependFile ("public/js/jquery-ui-1.8.16.custom.min.js" )
							  ->prependFile ("public/js/back_end/jquery.validate.js" )
							  ->prependFile ("public/js/bootstrap.js" )
							  ->prependFile ("public/js/jquery-1.7.2.min.js" )
							  ->prependScript('var HOST_PATH = "'.HTTP_PATH.'";')
							  ->prependScript('var HOST_PATH_LOCALE = "'.HTTP_PATH_LOCALE.'";')
 							  ->prependScript('var HOST_PATH_PUBLIC = "'.PUBLIC_PATH.'";')
 							  ->prependScript('var PUBLIC_PATH_CDN = "'.PUBLIC_PATH_CDN.'";');
 
$controller = $this->controller;

$googleCodeErrorPage = "<script type='text/javascript'>
						
						
							  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
							  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
							  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
							  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
							
							  ga('create', 'UA-17691171-3', 'flipit.com');
							  ga('send', 'pageview');
							  ga('send', 'event', 'error', '404', 'page:ref' , document.location.pathname + document.location.search + ':' + document.referrer  );
		</script>";
							  
						

$googleCodeFooter = "<script>
							  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
							  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
							  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
							  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
							
							  ga('create', 'UA-17691171-3', 'flipit.com');
							  ga('send', 'pageview');
					
					</script>";

if($controller == 'error'){
	echo $googleCodeErrorPage;
}else{
	echo $googleCodeFooter;
}
?>
</head>
<body>
	<div class="outerwrapper <?php
			if(Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == "index" && Zend_Controller_Front::getInstance()->getRequest()->getActionName() == "index") {
				echo "home";
			}
			
		?>">
		<!-- hidden field for apply selected class on menu -->
		<input type="hidden" name='cName' id='cName' value='<?php echo strtolower($this->controllerName);?>'/>
		<input type="hidden" name='aName' id='aName' value='<?php echo strtolower($this->action);?>'/>
			<div class="nav-bg"></div>
			<div class="innerwrapper">
				<?php 
				
				$modulePath = APPLICATION_PATH . '/modules/'. LOCALE .'/views/' ;
				$view = new Zend_View();
				$view->setBasePath(APPLICATION_PATH . '/views/');
				
				if(file_exists($modulePath . 'scripts/partials/_header.phtml' ))
				{
					$headerView = new Zend_View();
					$headerView->setBasePath($modulePath);
					echo $headerView->render('partials/_header.phtml');
				}else
				{
					echo $view->render('partials/_header.phtml');
				}
				?>
				<div class="content-section">
					<?php 
						if(file_exists($modulePath . 'scripts/partials/_top_nav.phtml' ))
						{
							$headerView = new Zend_View();
							$headerView->setBasePath($modulePath);
							echo $headerView->render('partials/_top_nav.phtml');
						} else	{
							echo $view->render('partials/_top_nav.phtml');
						}

					echo $this->layout()->content;?>
				</div>  	      
				<?php 
				if(file_exists($modulePath . 'scripts/partials/_footer.phtml' ))
				{
					$headerView = new Zend_View();
					$headerView->setBasePath($modulePath);
					echo $headerView->render('partials/_footer.phtml');
				}else
				{
					echo $view->render('partials/_footer.phtml');
				}
				?>
			</div>
	 </div>
 <?php 	if(file_exists($modulePath . 'scripts/partials/_pop_up.phtml' ))
		{
			$headerView = new Zend_View();
			$headerView->setBasePath($modulePath);
			echo $headerView->render('partials/_pop_up.phtml');
		}else
		{
			echo $view->render('partials/_pop_up.phtml');
		} ?>
</body>
</html>