<script src='https://www.google.com/recaptcha/api.js'></script>
<?php
$socialCodeForm = $this->zendForm;
foreach ($socialCodeForm->getElements() as $formElement) {
    $formElement->getDecorator('label')->setOption('tag', null);
}
?>
<div class="widget">
    <form id="socialCodeForm" class="widget-form" name="socialCodeForm" method="POST" action="">
        <h3><?php echo $this->translate('Social Code');?></h3>
        <p><?php echo $this->translate('Share a code with our users');?></p>
        <?php
        if ($this->errorMessege) {
            ?>
            <label class='error-message'>
                <?php echo $this->translate('Problem in your data');?>
            </label>
            <?php
        }
        echo $socialCodeForm->shops->renderViewHelper();
        echo $socialCodeForm->code->renderViewHelper();
        echo $socialCodeForm->offerDetails->renderViewHelper();
        echo $socialCodeForm->expireDate->renderViewHelper();
        $siteKey = FrontEnd_Helper_viewHelper::getCaptchaKey('captchaSiteKey');
        $captchaErrorMessage = new Zend_Session_Namespace('captchaErrorMessage');
        if (isset($captchaErrorMessage->captchaErrorMessage)) {
            ?>
            <label class='error-message'>
            <?php
            echo $captchaErrorMessage->captchaErrorMessage;
            $captchaErrorMessage->captchaErrorMessage = '';
            ?>
            </label>
            <?php
        }
        ?>
        <div class="g-recaptcha" data-sitekey="<?php echo $siteKey;?>">&nbsp;</div>
        <?php
        echo $this->formSubmit(
            'shareCode',
            FrontEnd_Helper_viewHelper::__form('form_share vouchercode'),
            array('class'=>'btn btn-primary', 'id'=>'shareCode')
        );
        ?>
        <div class='clear-both'></div>
    </form>
</div>