<?php
$socialCodeForm = $this->zendForm;
foreach ($socialCodeForm->getElements() as $formElement) {
    $formElement->getDecorator('label')->setOption('tag', null);
}
?>
<div class="widget">
    <form id="socialCodeForm" class="widget-form" name="socialCodeForm" method="POST" action="">
        <h3><?php echo $this->translate('Social Code');?></h3>
        <p><?php echo $this->translate('Share a code with our users');?></p>
        <?php
        if ($this->errorMessege) {
            ?>
            <label class='errorMessage'>
                <?php echo FrontEnd_Helper_viewHelper::__translate('Problem in your data');?>
            </label>
            <?php
        }
        echo $socialCodeForm->shops->renderViewHelper();
        echo $socialCodeForm->code->renderViewHelper();
        echo $socialCodeForm->offerDetails->renderViewHelper();
        echo $socialCodeForm->expireDate->renderViewHelper();
        echo $this->formSubmit(
            'shareCode',
            FrontEnd_Helper_viewHelper::__form('form_share vouchercode'),
            array('class'=>'btn btn-primary', 'id'=>'shareCode')
        );
        ?>
        <div class='clear-both'></div>
    </form>
</div>