<?php
$websiteName = FrontEnd_Helper_viewHelper::getWebsiteName(LOCALE);
?>
<div id='socialCodeDiv' class="widget">
    <h3><?php echo FrontEnd_Helper_viewHelper::__form('form_Social Code');?></h3>
    <strong class="sub-title"><?php echo FrontEnd_Helper_viewHelper::__form('form_Thank you for sharing your offer');?></strong>
    <div class="sub-text">
        <p>
        <?php 
        $translatableText = FrontEnd_Helper_viewHelper::__form('form_Thanks for sharing your coupon with the [websitename] Community Our team will check the details and publish the code');
        echo str_replace('[websitename]', $websiteName, $translatableText);
        ?>
        </p>
    </div>
    <a href="javascript:void(0);" onclick="loadSocialCodeForm();">
    <?php echo FrontEnd_Helper_viewHelper::__form('form_Share coupon codes for other shops');?>
    </a>
</div>