
<?php 
	$this->headScript ()->appendFile ( PUBLIC_PATH . "js/back_end/ckeditor/ckeditor.js" );
	$this->headScript ()->appendFile ( PUBLIC_PATH . "js/back_end/ckeditor/config.js" );
	$this->headScript()->appendFile(PUBLIC_PATH  . "js/back_end/jquery.validate.js");
	$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/bootbox.min.js");
	$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/addwidget.js");
	?>
	<?php echo $this->headTitle()->append('Create Widget');?>
<script type="text/javascript">
	var CKEDITOR_BASEPATH = "<?php echo PUBLIC_PATH . "js/back_end/ckeditor" ; ?>" ;
</script>
	
<!-- addwidget div starts -->
         <div class="wrap columns-2">
        <div id="addNewWidgetDiv" class="wrap columns-2">
        <?php //echo $this->headTitle()->append('Create Widget');?>
          <h1><span id="create"><?php echo $this->translate('Create Widget');?></span><button class="btn ml10" type="button" onClick="window.location.href='<?php echo HTTP_PATH ;?>admin/widget'"><?php echo $this->translate('Cancel'); ?></button></h1>
         	<form name="createWidget" id="createWidget" enctype="multipart/form-data" method="post">
         	<input type="hidden" name='editedWidgetId' id='editedWidgetId' value="" />
         	<input type="hidden" name='loggedInUser' id='loggedInUser' value="<?php echo $this->id; ?>" />
         	<input type="hidden" name='textValue' id='textValue'/>
            
            
            <div id="poststuff" class="metabox-holder has-right-sidebar">
              <div id="post-body">
              	<div>
              		<div class="mainpage-content margin_widget_editor">
                    	<div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Title');?> </strong></label></div>
                            <div class="mainpage-content-right">
                                <div class="mainpage-content-right-inner-right-other"></div>
                                <div class="mainpage-content-right-inner-left-other">
                                <input type="text" placeholder="" name="title" id="title" class="span3" onchange="this.value=this.value.trim()">
                                </div>                        
                            </div>
                        </div>
                    </div>
                    <!--<img class="mb10" src="<?php //echo IMG_PATH.'back_end/content-small.jpg';?>" border="0" />--> 
               
                <textarea name="content" id="content"></textarea>
               
              </div>
             </div>
              <br class="clear">
            </div>
            <br>
            <div class="mainpage-content-colorbox margin_widget_content">
            	<button class="btn btn-large btn-primary fl" type="submit" id="widgetSubmit"><span id="save"><?php echo $this->translate('CREATE WIDGET');?></span></button>
                <a href="<?php echo HTTP_PATH.'admin/widget';?>" class="fl m10"><strong><?php echo $this->translate('CANCEL');?></strong></a>
               
            </div>
            <!-- /poststuff -->
             </form>
        </div>
        </div>
<!-- addwidget div end -->