<!-- Voucher Outer Left Col1 Starts -->
<div class="voucher-outer-left-col1">
	<h1><?php echo $this->pageTitle; ?></h1>
	<div class="nieuw-popular-outer">
		<a class="text-black2-link <?php echo $this->active=='top20' ? "active" : '';?>" href="<?php echo HTTP_PATH_LOCALE. FrontEnd_Helper_viewHelper::__link('link_top-20')?>"><?php echo $this->translate('TOP 20'); ?></a>
		&nbsp;&nbsp;&nbsp;&nbsp;
		<a class="text-black2-link <?php echo $this->active=='new' ? "active" : '';?>" href="<?php echo HTTP_PATH_LOCALE. FrontEnd_Helper_viewHelper::__link('link_nieuw')?>"><?php echo $this->translate('NIEUW'); ?></a>
		&nbsp;&nbsp;&nbsp;&nbsp;
		<a class="text-black2-link <?php echo $this->active=='popular' ? "active" : '';?>" href="<?php echo HTTP_PATH_LOCALE. FrontEnd_Helper_viewHelper::__link('link_populair')?>"><?php echo $this->translate('POPULER'); ?></a>
	</div>
</div>
