<?php 
$this->headTitle()->append($this->translate('backend_Add Editor Widget Data'));
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/editorwidget.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.dataTables.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/dataTableComman.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
$this->headLink()->appendStylesheet(PUBLIC_PATH . "css/jquery-ui-1.8.16.custom.css");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/ckeditor/ckeditor.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/ckeditor/config.js");
?>
<h1>
    <?php echo $this->translate('backend_Add/Update Editor Widget Information for pages'); ?>
    <button class="btn ml10" type="button" onClick="window.location.href='<?php echo HTTP_PATH ;?>admin/popularcode'"><?php echo $this->translate('Cancel'); ?></button>
</h1>
<div class='wrap columns-2'>
    <?php 
    if ($this->messageSuccess!='' || $this->messageError!='' ) 
    {
        ?>
        <br><div class ="mainpage-content-colorbox success">
        <?php 
        if ($this->messageSuccess!='') 
        {
            ?>
            <span class="successserver"><?php echo $this->messageSuccess;?></span>
            <?php 
        }
        if ($this->messageError!='') {?>
            <span class="errorserver"><?php echo $this->messageError;?></span>
            <?php 
        } ?>
        </div>
    <?php } ?>
</div>
<form method="POST" enctype=multipart/form-data name="addEditorWidgetForm" id="addEditorWidgetForm">
    <div class="mainpage-content">
        <div class="mainpage-content-line">
           <div class="mainpage-content-left">
                <label>
                    <strong><?php echo $this->translate('backend_Page Type'); ?></strong>
                </label>
            </div>
            <div class="mainpage-content-right">
                <div class="mainpage-content-right-inner-right-other"></div>
                <div class="mainpage-content-right-inner-left-other">
                    <select class="mainpage-content-right-select" id="pageType" name="type" onChange="getPageTypeData()">
                        <option default="default" value=""><?php echo $this->translate('None'); ?></option>
                        <option value="top20"><?php echo $this->translate('backend_Top 20 Page'); ?></option>
                        <option value="category"><?php echo $this->translate('backend_Catgeory Page'); ?></option>
                        <option value="special"><?php echo $this->translate('backend_Special Page'); ?></option>
                        <option value="newPage"><?php echo $this->translate('backend_new Offers Page'); ?></option>
                    </select>
               </div>  
            </div>
        </div>
        <div class="mainpage-content-line">
            <div class="mainpage-content-left">
                <label>
                    <strong><?php echo $this->translate('backend_Editor Name'); ?></strong>
                </label>
            </div>
            <div class="mainpage-content-right">
                <div class="mainpage-content-right-inner-right-other"></div>
                <div class="mainpage-content-right-inner-left-other">
                   <select class="mainpage-content-right-select"  id="selecteditors" name="selecteditors">
                    <option default="default" value=""><?php echo $this->translate('None'); ?></option>
                    <?php for($i=0;$i<count($this->MangersList['editors']);$i++){?>
                    <option value="<?php echo $this->MangersList['editors'][$i]['id'];?>"><?php echo ucfirst( $this->MangersList['editors'][$i]['fname']. " " . $this->MangersList['editors'][$i]['lname']);?></option>
                    
                    <?php }?>
                  </select>
               </div>   
            </div>
        </div>
        <div class="mainpage-content-line">
           <div class="mainpage-content-left">
                <label>
                    <strong><?php echo $this->translate('backend_Sub Title'); ?></strong>
                </label>
            </div>
            <div class="mainpage-content-right">
                <div class="mainpage-content-right-inner-right-other" style="width:250px;"></div>
                <div class="mainpage-content-right-inner-left-other">
                    <input id = "subtitle" type="text" class="span3" placeholder="<?php echo $this->translate('subTitle'); ?>"  name="subtitle">
                </div>
            </div>
        </div>
        <div class="mainpage-content-line">
            <div class="mainpage-content-left">
                <label><strong><?php echo $this->translate('backeend_Editor text'); ?></strong></label>
            </div>
            <div class="mainpage-content-right">
                <div class="mainpage-content-right-inner-right-other"></div>
                <div class="mainpage-content-right-inner-left-other">
                    <textarea rows="3" id="description" name="description" placeholder="<?php echo $this->translate('backend_Description about the Editor')?>" class="input-xlarge mbot bbot ignore word_count"></textarea>            
                </div>
            </div>
        </div>    
        <div class="mainpage-content-line">
            <div class="mainpage-content-left">
                <label><strong><?php echo $this->translate('backend_show on FrontEnd'); ?></strong></label>
            </div>
            <div class="mainpage-content-right">
                <div class="mainpage-content-right-inner-left-other">
                    <div data-toggle="buttons-checkbox" class="btn-group">
                        <button id='btnNo' type="button" onclick="changeAction(this,0)" name="redirect" class="btn"><?php echo $this->translate("No") ; ?></button>    
                        <button id='btnYes' style="border-radius: 0 4px 4px 0;" type="button" onclick="changeAction(this,1)" name="connect" class="btn btn-primary default"><?php echo $this->translate("Yes") ; ?></button>
                        <input value="<?php echo "1"?>" class="display-none" type="checkbox"  name="actionType" id="actionType" checked="checked"/>
                    </div>
                </div>
            </div>
        </div>          
        <div class="mainpage-content-colorbox">
            <button type="submit" id="createEditorWidget" class="btn btn-large btn-primary fl"><?php echo $this->translate('CREATE'); ?></button>
            <a href="javascript:void(0);" onclick="window.location.href='<?php echo HTTP_PATH ;?>admin/popularcode'" class="fl m10" ><strong><?php echo $this->translate('CANCEL'); ?></strong></a>
        </div>
    </div>
</form>