<?php
$this->headTitle()->append($this->translate('Users List'));
$role =  Zend_Auth::getInstance()->getIdentity()->users->id;
if($role=='1' || $role=='2')
{
//$this->headMeta('keyword', 'noF');asdafasfasfasfa
//file for upload imagesjquery-ui-1.8.16.custom.min.js
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.dataTables.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/dataTableComman.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.ui.widget.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.iframe-transport.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.fileupload.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.fileupload-fp.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.fileupload-ui.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/userList.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "/css/jquery-ui-1.8.16.custom.css" );
?>

<!-- Div for user list  -->

 <div id='userListDiv'>
		<div class='wrap columns-2'>
		<?php if($this->messageSuccess!='' || $this->messageError!='' ){?>
		<br><div class ="mainpage-content-colorbox success">
		<?php if($this->messageSuccess!=''){?>
		<span class="successserver"><?php echo $this->messageSuccess; ?></span>
		<?php }?>
		<?php if($this->messageError!=''){?>
		<span class="errorserver"><?php echo $this->messageError; ?></span>
		<?php } ?>
		</div>
		<?php 
		}?>
		
<h1 class="fl"><?php echo $this->translate('Users');?><input type="button" onClick="window.location.href='<?php echo HTTP_PATH; ?>admin/user/adduser'" Value='<?php echo $this->translate('Add New User'); ?>' name='addNew' class="btn ml10" /></h1><a href="<?php echo HTTP_PATH.'admin/user/trash/';?>" class="red trash-link"><strong><?php echo $this->translate('Trash');?></strong></a>
          	<div class="clear"></div>
          <p class="text-right"><a href="<?php echo HTTP_PATH ?>admin/user/exportuserlist"><?php echo $this->translate('Export List'); ?></a></p>
        
     
            
         <div class="mainpage-content-colorbox">
                <form class="form-search" onSubmit="return false;">
                    <div class="fl">                   
                         <input type="text" id='tags' name='search' placeholder="Search User" class="span5">
                        <button id="searchButton" type='button'  class="btn btn-primary">Search</button>
                    
                    </div>             	
                    <div class="fl ml15 fillterDiv"> 
                      <select id='selectRole'>
                      </select>
                    </div>                         
                </form>
            
            </div>  
            
		<table width="100%" id="userList" class="table table-bordered table-striped">
			<thead>
	            <tr>
	             	<th><?php echo $this->translate('Id'); ?></th>
	                <th><?php echo $this->translate('Name'); ?></th>
	                <th class='maxWidth'><?php echo $this->translate('Email'); ?></th>
	                <th><?php echo $this->translate('Role'); ?></th>
	            </tr>
	        </thead>
	    </table>
	</div>
</div>
<!-- End code of list users -->

<?php 
}
?>
