<?php 
 $this->headTitle()->append($this->translate('Tag Manager'));
 $this->headScript()->appendFile(PUBLIC_PATH . "js/jquery.dataTables.min.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "js/dataTableComman.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/urlSettings.js");
?>
<div id="UrlSettingsList">
   <div class="wrap columns-2">
       <?php echo $this->flashMessages(); ?>
        <h1 class="fl"><?php echo $this->translate('Tag Manager'); ?>
            <button class="btn ml10" type="button" onClick="window.location.href='<?php echo HTTP_PATH ;?>admin/urlsettings/create'">
            <?php echo $this->translate('Add Tag'); ?>
            </button>
        </h1>
        <div class="clear"></div>
        <table class="table table-bordered table-striped" id="UrlSettingsListTbl" cellpadding="0" cellspacing="0">
            <thead>
                <tr>
                    <th><?php echo $this->translate('id');?></th>
                    <th><?php echo $this->translate('URL');?></th>
                    <th><?php echo $this->translate('VWO');?></th>
                    <th><?php echo $this->translate('Hotjar');?></th>
                    <th><?php echo $this->translate('Delete');?></th>
                </tr>
            </thead>
        </table> 
  </div>
</div>
        