<?php
foreach ($this->categoriesWithSpecialPagesList as $category) {
    $featuredCategoryClass = '';
    $featuredCategoryImageDimensions = 'width= 174 height=175';
    $featuredCategorySpan = '';
    
    if(isset($category['featured_category']) && $category['featured_category'] != '') {
        $featuredCategoryClass = "box-top"; 
        $featuredCategoryImageDimensions = 'width= 366 height=367';
        $featuredCategorySpan = '<span class="label">'.$this->translate('special').'</span>';
    }

    $categoryImage = isset($category['categoryicon']) ? $category['categoryicon'] : $category['logo'];
    $categoryImageSource = PUBLIC_PATH_CDN.$categoryImage['path']."".$categoryImage['name']; 
    ?>
    <article class="box <?php echo $featuredCategoryClass; ?>">
        <a href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('categorieen').'/'. $category['permaLink']; ?>">
            <div class="image">
                <img src ="<?php echo $categoryImageSource; ?>" <?php echo  $featuredCategoryImageDimensions; ?> alt="<?php echo $category['name'];?>" />
            </div>
            <div class="caption">
                <?php echo $featuredCategorySpan; ?>
                <strong><?php echo $category['name']; ?></strong>
            </div>
        </a>
    </article>
    <?php  
    }