<div class="row">
        <div class="col-md-12 content-box">
          <div class="section">
            <div class="panel panel-default">
              <div class="panel-body">
                All Popular Categories and Special Topics
              </div>
            </div>
            <div class="catigories">
              <article class="box box-top">
                <a href="#">
                  <div class="image">
                    <img src="images/img-05.jpg" alt="image description">
                  </div>
                  <div class="caption">
                    <span class="label">special</span>
                    <strong>Student Vouchers</strong>
                  </div>
                </a>
              </article>
              <article class="box">
                <a href="#">
                  <div class="image">
                    <img src="images/img-06.jpg" alt="image description">
                  </div>
                  <div class="caption">
                    <strong>Sports &amp; Outdoors</strong>
                  </div>
                </a>
              </article>
              <article class="box">
                <a href="#">
                  <div class="image">
                    <img src="images/img-07.jpg" alt="image description">
                  </div>
                  <div class="caption">
                    <strong>Mens Fashion</strong>
                  </div>
                </a>
              </article>
              <article class="box">
                <a href="#">
                  <div class="image">
                    <img src="images/img-08.jpg" alt="image description">
                  </div>
                  <div class="caption">
                    <strong>Going Out</strong>
                  </div>
                </a>
              </article>
              <article class="box">
                <a href="#">
                  <div class="image">
                    <img src="images/img-09.jpg" alt="image description">
                  </div>
                  <div class="caption">
                    <strong>Travel</strong>
                  </div>
                </a>
              </article>
              <article class="box">
                <a href="#">
                  <div class="image">
                    <img src="images/img-10.jpg" alt="image description">
                  </div>
                  <div class="caption">
                    <strong>Food &amp; Drink</strong>
                  </div>
                </a>
              </article>
              <article class="box">
                <a href="#">
                  <div class="image">
                    <img src="images/img-11.jpg" alt="image description">
                  </div>
                  <div class="caption">
                    <strong>Technology</strong>
                  </div>
                </a>
              </article>
              <article class="box">
                <a href="#">
                  <div class="image">
                    <img src="images/img-12.jpg" alt="image description">
                  </div>
                  <div class="caption">
                    <strong>Home &amp; Garden</strong>
                  </div>
                </a>
              </article>
              <article class="box">
                <a href="#">
                  <div class="image">
                    <img src="images/img-13.jpg" alt="image description">
                  </div>
                  <div class="caption">
                    <strong>Womens Fashion</strong>
                  </div>
                </a>
              </article>
              <article class="box">
                <a href="#">
                  <div class="image">
                    <img src="images/img-14.jpg" alt="image description">
                  </div>
                  <div class="caption">
                    <strong>Finance</strong>
                  </div>
                </a>
              </article>
              <article class="box">
                <a href="#">
                  <div class="image">
                    <img src="images/img-15.jpg" alt="image description">
                  </div>
                  <div class="caption">
                    <strong>Baby &amp; Child</strong>
                  </div>
                </a>
              </article>
              <article class="box">
                <a href="#">
                  <div class="image">
                    <img src="images/img-16.jpg" alt="image description">
                  </div>
                  <div class="caption">
                    <strong>Games &amp; Movies</strong>
                  </div>
                </a>
              </article>
              <article class="box">
                <a href="#">
                  <div class="image">
                    <img src="images/img-17.jpg" alt="image description">
                  </div>
                  <div class="caption">
                    <strong>Health &amp; Beauty</strong>
                  </div>
                </a>
              </article>
              <article class="box">
                <a href="#">
                  <div class="image">
                    <img src="images/img-18.jpg" alt="image description">
                  </div>
                  <div class="caption">
                    <strong>Gifts &amp; Flowers</strong>
                  </div>
                </a>
              </article>
              <article class="box">
                <a href="#">
                  <div class="image">
                    <img src="images/img-19.jpg" alt="image description">
                  </div>
                  <div class="caption">
                    <strong>Books, Music</strong>
                  </div>
                </a>
              </article>
              <article class="box">
                <a href="#">
                  <div class="image">
                    <img src="images/img-20.jpg" alt="image description">
                  </div>
                  <div class="caption">
                    <span class="label">special</span>
                    <strong>Fathers day <br>Coupons</strong>
                  </div>
                </a>
              </article>
              <article class="box">
                <a href="#">
                  <div class="image">
                    <img src="images/img-21.jpg" alt="image description">
                  </div>
                  <div class="caption">
                    <span class="label">special</span>
                    <strong>Easter Coupon Codes</strong>
                  </div>
                </a>
              </article>
              <article class="box">
                <a href="#">
                  <div class="image">
                    <img src="images/img-22.jpg" alt="image description">
                  </div>
                  <div class="caption">
                    <span class="label">special</span>
                    <strong>Valentine's Day Coupons</strong>
                  </div>
                </a>
              </article>
              <article class="box">
                <a href="#">
                  <div class="image">
                    <img src="images/img-23.jpg" alt="image description">
                  </div>
                  <div class="caption">
                    <strong>Nearly <br> Expired Coupons</strong>
                  </div>
                </a>
              </article>
              <article class="box">
                <a href="#">
                  <div class="image">
                    <img src="images/img-24.jpg" alt="image description">
                  </div>
                  <div class="caption">
                    <strong>Exclusive Offers</strong>
                  </div>
                </a>
              </article>
              <article class="box">
                <a href="#">
                  <div class="image">
                    <img src="images/img-25.jpg" alt="image description">
                  </div>
                  <div class="caption">
                    <span class="label">special</span>
                    <strong>Hip Moms Coupons</strong>
                  </div>
                </a>
              </article>
            </div>
          </div>
          <div class="section section-newsletter">
            <form role="form" class="form-signin newsletter">
              <h2 class="form-signin-heading">Sign up for our newsletter and receive discounts inside your mailbox!</h2>
              <input type="email" placeholder="Email Address" class="form-control">
              <button type="submit" class="btn blue btn-lg btn-primary">sign up!</button>
            </form>
          </div>
        </div>
      </div>
        <!-- Search Outer2 Ends -->
        <!-- Alle Winkels Starts -->
        <div class="alle-winkels-outer">
        
          <!-- Alle Winkels Left Starts -->
          <div class="mt20 fl" id='left_container'>
              <h1><?php echo $this->pageTitle;?></h1>

            
          <!-- Separator Starts -->
          <div class="separator mt20">&nbsp;</div>
          <!-- Separator Ends -->
            
             <!-- Icon Description Outer Starts -->
              <?php 
              $i=1;
              if(count($this->catIcons) > 0){
              foreach($this->catIcons as $icons ){
              	$id =  $icons['id'];
              	
              	$class = '';
              	if($i%6 == 0)
              	{
              	   $class = 'mr-none';
              	}
              	
               $categoryIconPath = '';
               $categoryName = '';
                $categoryIconPath = PUBLIC_PATH_CDN.$icons['categoryicon']['path']."thum_medium_".$icons['categoryicon']['name']; 
			   $categoryName = $icons['name'];
			   
			    ?>
			   
			    <a class="image-description-outer <?php echo $class; ?>" href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('categorieen').'/'. $icons['permaLink']; ?>">
				   
				    <span class="image-description-img">
				    	<img src ="<?php echo $categoryIconPath;?>" alt="<?php echo $categoryName;?>" />
				    </span>
				    <span class="image-description-text">	  			   
		              <?php
		                echo $categoryName;
		              ?>	  			    
				    </span>
				   
			    </a>
			    
			    
			   <?php  
			   ++$i;
              }
              }
              else{
              ?>
             <div style="text-align:center;font-size:14px;font-weight:bold;"><?php echo $this->translate('No record found'); ?></div> 
             <?php } ?> 
            <!-- Icon Description Outer Ends -->
             
                      
     <!-- Gesorteerde Outer Starts -->
         <div class="gesorteerde-outer mt40">
          <div class="gesorteerde-heading">
            <h2><?php echo $this->translate('Gesorteerde lijsten')?></h2>
          </div>
           <!-- Separator Starts -->
          <div class="separator mt20">&nbsp;</div>
          <!-- Separator Ends -->
          
            <div class="gesorteerde-text1"><?php echo $this->desc;?></div>
	 		 <div class="gesorteerde-bot">
		 		    <!-- Gesorteerde Col1 Outer Starts -->
		 <?php 
		
		  $specialList = $this->specialCat;
		  for($s=0;$s<count($specialList);$s++)
		  {
		  	$img = '';
		  	if(count($specialList)>0){
			 	$img = PUBLIC_PATH_CDN.$specialList[$s]['logo']['path']."thum_page_small".$specialList[$s]['logo']['name'];
			 
		?>
		     <div class="gesorteerde-col1-outer">
	      	 <div class="gesorteerde-col1">
	      	 <a href="<?php echo HTTP_PATH_LOCALE . $specialList[$s]['permaLink'];  ?>" >
	      	   <span class="gesorteerde-col1-img">
	      	   		<img src ="<?php echo $img;?>" alt="<?php echo $specialList[$s]['pageTitle'];?>"/>
	      	   </span>
			   <span title='<?php echo $specialList[$s]['pageTitle']; ?>' class="gesorteerde-col1-text text-black-link"><?php echo strlen($specialList[$s]['pageTitle'])<= 24 ?  $specialList[$s]['pageTitle'] : substr($specialList[$s]['pageTitle'], 0,24).'..'; ?>
			   </span>
			</a>    
		    </div>
		   </div>
		   
		<?php } } ?>
		     		
		     		
	         <!-- Gesorteerde Col1 Outer Ends -->
	          </div>
             <!-- Gesorteerde Bot Starts -->
          </div>
           <!-- Gesorteerde Outer Ends -->
         
       </div>
       <!-- Alle Winkels Left Ends -->
            
           <!-- Alle Winkels Right Starts -->
            <div class="alle-winkels-right" id='right_container'>
            
            <!-- Waardebon Starts -->
             
             <?php 
                 echo FrontEnd_Helper_viewHelper::getSidebarWidgetViaId(9);
             ?>
             <!-- Waardebon Ends -->
            </div>
            <!-- Alle Winkels Right Ends -->
        </div>
     <!-- Alle Winkels Ends -->

        
 