<?php
$categoriesWithSpecialPagesList = '';
if (count($this->categoriesWithSpecialPagesList) > 0) {
    $categoriesWithSpecialPagesList = $this->partial(
        'category/_categories-overview.phtml',
        array('categoriesWithSpecialPagesList'=> $this->categoriesWithSpecialPagesList)
    );
}
?>
<div class="row">
    <div class="col-md-12 content-box">
        <div class="section">
            <div class="panel panel-default">
                <div class="panel-body">
                <?php echo $this->translate('Browse Categories'); ?>
                </div>
            </div>
            <div class="catigories">
            <?php echo $categoriesWithSpecialPagesList; ?>
            </div>
        </div>
    </div>
</div>

