<?php
$categoryFeaturedImage = PUBLIC_PATH_CDN.$this->categoryDetail[0]['categoryicon']['path'].
                         "thum_large_".$this->categoryDetail[0]['categoryicon']['name'];
$categoryPartial = new FrontEnd_Helper_PageHeaderPartialFunctions();
echo $categoryPartial->getCategoryOrPageHeader($this->categoryDetail[0]['name'], $categoryFeaturedImage);

$partialsViewPath = 'partials/';
$offers = '';
if (count($this->offersWithPagination)>0) {
    $offers = $this->partial(
        $partialsViewPath.'_offer.phtml',
        array(
        'offers'=> $this->offersWithPagination,
        'offersType'=>$this->offersType,
        'shopName'=> '',
        'shop'=>'',
        'zendForm'=>$this->form,
        'categoryPermaLink'=>$this->categoryDetail[0]['permaLink']
        )
    );
} else {
    $offers ='<div class = "no-record">' . $this->translate('No record found') .'</div>';
}
$signUpWidgetForm = $this->partial(
    $partialsViewPath.'_signupForm.phtml',
    array(
        'zendForm' => $this->sidebarWidgetForm,
        'SignupFormWidgetType'=> 'sidebarWidget',
        'shopId'=>'',
        'shopLogoOrDefaultImage'=>''
    )
);
?> 
<div class="row">
    <div class="col-md-8 col-sm-8" id="content">
    <?php echo $offers; ?>
    </div>
    <aside class="col-md-4 col-sm-4" id="sidebar">
    <?php 
    $frontendViewHelper = new FrontEnd_Helper_viewHelper();
    echo $frontendViewHelper->popularCategoryWidget();
    echo FrontEnd_Helper_viewHelper::socialMediaWidget();
    echo FrontEnd_Helper_viewHelper::popularShopWidget();
    echo $frontendViewHelper->browseByStoreWidget();
    echo $signUpWidgetForm;
    ?>
    </aside>
</div>