<?php 
$categoryIconPath = '';
$categoryName = '';
$id = $this->id;
$categoryIconPath = PUBLIC_PATH_CDN.$this->categoryicon['path'].'thum_'.$this->categoryicon['name'];
$categoryName = $this->name;
?>  
<div class="gesorteerde-col1-outer">
    <div class="gesorteerde-col1">
        <a href="<?php echo HTTP_PATH_LOCALE . $this->permaLink; ?>">
            <div class="gesorteerde-col1-img">
                <img src="<?php echo $categoryIconPath; ?>" width="60" height="41" />
            </div>
            <div class="gesorteerde-col1-text">
                <?php echo $categoryName; ?>
            </div>
        </a>    
    </div>
</div>