     <?php 
       $categoryIconPath = '';
      	$categoryName = '';
      	$id = $this->id;
      	if(file_exists($this->categoryicon['path'].'thum_'.$this->categoryicon['name'])) :
      	            $categoryIconPath = PUBLIC_PATH.$this->categoryicon['path'].'thum_'.$this->categoryicon['name'];
      	       		$categoryName = $this->name;
      	       	else :
      	       
      	       		$categoryIconPath = HTTP_PATH ."public/images/upload/no.jpg";
      	           $categoryName = $this->name;
      	       	endif;
      
      ?>
       
           <div class="gesorteerde-col1-outer">
	      	 <div class="gesorteerde-col1">
	      	 <a href="<?php echo HTTP_PATH_LOCALE . $this->permaLink; ?>">
	      	      <div class="gesorteerde-col1-img"><img src="<?php echo $categoryIconPath; ?>" width="60" height="41" /></div>
				  <div class="gesorteerde-col1-text" style="color:#6A6A6A;"><?php echo strlen($categoryName)<= 10 ?  $categoryName : substr($categoryName, 0,10).'...'; ?></div>
			</a>    
		    </div>
		   </div>
	     
	     
      
        
      	
        