<?php

/**
 * GlobalEditorBallonTextTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EditorBallonTextTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GlobalExportPasswordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EditorBallonText');
    }
}
