<?php

/**
 * FavoriteShopTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FavoriteShopTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FavoriteShopTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FavoriteShop');
    }
}
