<?php

/**
 * PopularVouchercodesTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PopularVouchercodesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PopularVouchercodesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PopularVouchercodes');
    }
}
