<?php

/**
 * VisitorImageTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VisitorImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VisitorImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VisitorImage');
    }
}
