<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width" />
	<title><?php echo $this->translate('Kortingscode.nl');?></title>
	<link href="<?php echo PUBLIC_PATH ?>css/marktplaatsmobilefeed/style.css" rel="stylesheet" type="text/css" />
</head>
<body>
  <div class="container">
    	    <?php
    	# check popular cods available or not
    	if($this->topCode):

    		# render all popular codes
	    	foreach ($this->topCode as $value) :
			?>
		    	<div class="leftbox">
			    	<?php
						# check an image is available or not
	    				  	$img = PUBLIC_PATH_CDN.ltrim($value['offer']['shopOffers']['logo']['path'], "/") .'thum_medium_'. $value['offer']['shopOffers']['logo']['name'];
							
                    ?>
			    	<a target="_blank" onClick="ga('send', 'event', 'marktplaats', 'click', 'shop logo');" href="<?php echo HTTP_PATH_LOCALE . $value['offer']['shopOffers']['permaLink'];  ?>" class="zalando"><img src="<?php echo $img; ?>" alt="<?php echo $this->translate($value['offer']['shopOffers']['name'])?>" title="<?php echo $this->translate($value['offer']['shopOffers']['name'])?>" />&nbsp;</a>
		    			<div class="number">
				    	<div class="textkorting">
				    		<p>
									 <a target="_blank" onClick="ga('send', 'event', 'marktplaats', 'click', 'offer title');"  href="<?php echo HTTP_PATH_LOCALE.$value['offer']['shopOffers']['permaLink'];  ?>">
                            		<?php 
                            			# trim  shop title if its length is gretaer that 28 chras
                            				if(mb_strlen($value['offer']['title'], 'UTF-8') > 68) {

                            					echo mb_substr($value['offer']['title'], 0,68, 'UTF-8').'...';

                            				} else { echo $value['offer']['title'];  }   ?>
                        		</a></p>
					    	<a target="_blank" onClick="ga('send', 'event', 'marktplaats', 'click', 'offer button');" href="<?php echo HTTP_PATH_LOCALE . $value['offer']['shopOffers']['permaLink'];  ?>" class="button"><?php echo $this->translate('Pak deze code!')?></a>
				    	</div>
			    	</div>
			    	
		    	</div>
   <?php  	
   
	    	endforeach;
    	endif;
    ?>
 
 
 </div>
      <script type='text/javascript'>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		ga('create', 'UA-17691171-4', 'kortingscode.nl');
		ga('send', 'pageview');

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-17691171-1']);
        _gaq.push(['_trackPageview']);
        (function()
        { var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true; ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js'; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s); }
        )();
    </script>
</body>
</html>
