<?php
$categoryHeaderImage =
    isset($this->categoryDetails[0]['categoryHeaderImage']['path'])
    ? PUBLIC_PATH_CDN.$this->categoryDetails[0]['categoryHeaderImage']['path']
    .$this->categoryDetails[0]['categoryHeaderImage']['name'] : '';
$categoryPartial = new FrontEnd_Helper_PageHeaderPartialFunctions();
echo $categoryPartial->getCategoryOrPageHeader($this->categoryDetails[0]['name'], $categoryHeaderImage);
$partialsViewPath = 'partials/';

$offers = '';
if (count($this->offersWithPagination)>0) {
    $offers = $this->partial(
        $partialsViewPath.'_offer.phtml',
        array(
        'offers'=> $this->offersWithPagination,
        'offersType'=>$this->offersType,
        'shopName'=> '',
        'shop'=>'',
        'zendForm'=>$this->form,
        'categoryPermaLink'=>$this->categoryDetails[0]['permaLink'],
        'widgetPosition'=>$this->widgetPosition
        )
    );
} else {
    $offers ='<div class = "no-record no-offers">' . $this->translate('Unfortunately there aren\'t any coupons available in this category. Come back later for some awesome coupons!') .'</div>';
}
?> 
<div class="row">
    <div class="col-md-8 col-sm-8" id="content">
    <?php echo $offers; ?>
    </div>
    <aside class="col-md-4 col-sm-4" id="sidebar">
    <?php
    $this->locale = LOCALE != 'en' ? LOCALE . '/' : '';
    $frontendSidebarHelper = new FrontEnd_Helper_SidebarWidgetFunctions();
    echo $frontendSidebarHelper->sidebarWidgets('categories', $this, $this->categoryDetails[0]['id']);
    ?>
    </aside>
</div>