<script type="text/javascript">
CKEDITOR.replace( 'content_<?php echo $this->partialCounter ?>',
    {
        customConfig : 'config.js',  
        toolbar :  'BasicToolbar'  
    }
);
</script>
<div class="multidivchild">
    <div class="mainpage-content-line mb10">
        <div class="mainpage-content-left">
            <label>
                <strong><?php echo $this->translate('Editor Ballon Text'); ?></strong>
            </label>
        </div>
        <?php if ($this->partialCounter != 1) { ?>
        <div class="mainpage-content-line mb10">
            <div class="mainpage-content-right">
                <div class="mainpage-content-right-inner-left-other">
                    <div data-toggle="buttons-checkbox" class="btn-group">
                        <button type="button" style="border-radius: 4px 4px 4px 4px;" 
                        name="remove_tab" rel="<?php echo $this->id; ?>" onclick="removeballontexthtml(this)"
                        class="btn "><?php echo $this->translate('Remove'); ?>
                        </button>
                        <p style="color:red; padding:5px; float:left; margin:0; font-size:13px;">
                        &laquo; <?php echo $this->translate('Remove Text Editor'); ?></p>
                    </div>
                </div>
            </div>
        </div>
        <?php } ?>
        <div class="mainpage-content-right">
            <div class="mainpage-content-line">
                <div class="mainpage-content-line">
                    <div class="mainpage-content-right-inner-right-other"></div>
                    <div class="">
                        <textarea name="ballontextcontent[]"  class="ckeditor" id="content_<?php echo $this->partialCounter;?>">
                        <?php echo isset($this->ballontext) ? $this->ballontext : '';?>
                        </textarea>
                    </div>
                </div>
            </div>  
        </div>
    </div>
</div>
            
        