<?php 
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/edit-shop.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/jquery.textareaCounter.plugin.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
$this->headLink()->appendStylesheet(PUBLIC_PATH . "css/jquery-ui-1.8.16.custom.css");
$this->headLink()->appendStylesheet(PUBLIC_PATH . "js/back_end/openwysiwyg_v1.4.7/styles/wysiwyg.css");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.NobleCount.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/ckeditor/ckeditor.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/ckeditor/config.js" );
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/widget-location.js");
$howToIntroductionText = '';
$howToIntroductionText = $this->partial(
    'shop/_how-to-introduction-text.phtml',
    array('howToIntroductionText'=> $this->data['howToIntroductionText'])
);

echo $this->headTitle()->append('Edit Shop');?>
<div id="imbullbody-content" style="overflow: hidden;">
      
 
 <!-- Create shops Start -->
   <div id="createNewShop">        
    <form method="POST" name="createShop" id="createShop" enctype=multipart/form-data>
      <div class="wrap columns-2">
        <?php if($this->data['status'] == 0):  ?>
           <div class="alert alert-danger bs-alert-old-docs text-center mt10 ">
                <strong><?php echo $this->translate("THIS SHOP IS OFFLINE ATM"); ?></strong>
            </div>
       <?php endif; ?>
        <!-- Start addUser form -->
         
            <h1>
                <?php echo $this->translate('Edit Shop');
                 $httpScheme = FrontEnd_Helper_viewHelper::getServerNameScheme(); ?>
                <button class="btn ml10" type="button" onClick="window.location.href='<?php echo HTTP_PATH ;?>admin/shop<?php echo '#'.$this->qstring; ?>'"><?php echo $this->translate('Cancel'); ?></button>
                <button type="button" class="btn btn-primary ml10" id='prefillData'><?php echo $this->translate('Pre-fill'); ?></button>	
                <?php 
                $httpScheme = FrontEnd_Helper_viewHelper::getServerNameScheme();
                $host = $httpScheme.'.kortingscode.nl';
                if ($_COOKIE['site_name'] != 'kortingscode.nl') 
                {
                    $host = $httpScheme.'.flipit.com/admin';
                } 
                date_default_timezone_set('Europe/Amsterdam');
                $hash = md5($this->data['id'].date('Y').'-'.date('m').'-'.date('d').':'.date('H')); 
                ?>
                <a href="<?php echo 'http://'.$host.'/branding/start?storeUrl=http://'.$httpScheme.'.'.$_COOKIE['site_name'].'/' ?><?php echo $this->data['permaLink'].'&shopID='.$this->data['id'].'&hash='.$hash; ?>" class="btn btn-primary">Brand this shop</a>
            </h1>

         
			<input type="hidden" name='qString' id='qString' value='<?php echo $this->qstring; ?>' />
             <div class="mainpage-content">
             
            	<div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Online'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                    	<div class="btn-group" data-toggle="buttons-checkbox">
                            
                            <?php 
                            
                            		if( $this->data['status'] )
                            		{
                            			?>
                            			
											<button type="button" class="btn btn-primary" onClick="setOnOff(event,'onlineStatus','on');"><?php echo $this->translate('Yes'); ?></button>                     
				                            <button type="button" class="btn  default" onClick="setOnOff(event,'onlineStatus','off');"><?php echo $this->translate('No'); ?></button>
                            			                            
                            	<?php } else { ?>
                            	
											<button type="button" class="btn" onClick="setOnOff(event,'onlineStatus','on');"><?php echo $this->translate('Yes'); ?></button>                     
                            				<button type="button" class="btn btn-primary default" onClick="setOnOff(event,'onlineStatus','off');"><?php echo $this->translate('No'); ?></button>
                            	
                            	<?php }?>
                            	
                            
                          </div>
                    </div>          
                </div>
            </div>
            <div class="mainpage-content">
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Shop Name'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                              <input value="<?php echo $this->data['name'] ; ?>" type="text" class="span3"  id="shopName" name="shopName"  placeholder=<?php echo $this->translate('Shop Name'); ?> style="margin-bottom: 0;">
                              <input type="text" id="shopNameLeft" class="input-xlarge  btop word-count" value="<?php echo $this->translate("Shop name length "). strlen($this->data['name']) . $this->translate(' characters');?>" placeholder="<?php echo $this->translate('0 characters');?>" disabled="disabled">
</div>
                    </div>
                </div>
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Navigational URL'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                    	<div class="mainpage-content-right-inner-left"><label id="navigationalSite"><?php echo $this->translate('http://www.kortingscode.nl/'); ?></label></div>
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-right-full">
                        <input <?php echo ($this->role == '3' || $this->role == '4') ? "disabled=disabled" : "" ;  ?> value="<?php echo $this->data['permaLink'] ; ?>" type="text" class="span3" placeholder="<?php echo $this->translate('Navigational URL'); ?>" name="shopNavUrl" id="shopNavUrl"></div>
                        <?php if($this->role == '3' || $this->role == '4'):?><input value="<?php echo $this->data['permaLink'] ; ?>" type="hidden" name="shopNavUrl" id="shopNavUrl"></div> <?php endif;?>
                    </div>
                </div>
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Overwrite title'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                        	<input value="<?php echo $this->data['overriteTitle'] ; ?>" type="text" class="span3 ignore" placeholder="<?php echo $this->translate('Overwrite Title'); ?>" name="shopOverwriteTitle" id="shopOverwriteTitle" style="margin-bottom: 0;">
                            <span id="shopOverwriteTitleLeft" class="nobel disabled btop word-count shop-wordcount-width"></span>
                        </div>
                    </div>    
                </div>
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Meta Description'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
	                        <textarea class="input-xlarge mbot bbot ignore" id="shopMetaDescription" name="shopMetaDescription" placeholder="<?php echo $this->translate ( 'Meta Description' );?>" rows="3"><?php echo $this->data['metaDescription']; ?></textarea>
                            <span id="metaTextLeft" class="nobel disabled btop word-count shop-wordcount-width"></span>
                        </div>
                    </div>
                </div>
                
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Title'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
							<input value="<?php echo $this->data['title'] ; ?>" type="text" class="span3 mbot bbot"  name="shopTitle" id="shopTitle" placeholder="<?php echo $this->translate('Shop Title'); ?>">
							<input type="text" id="shopTitleLeft" class="input-xlarge  btop word-count" value="<?php echo $this->translate("Shop title length "). strlen($this->data['title']) . $this->translate(' characters');?>" placeholder="<?php echo $this->translate('0 characters');?>" disabled="disabled">
                        </div>
                    </div>
                </div>
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Sub-title'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                        
                        <input value="<?php echo $this->data['subTitle'] ; ?>" type="text" class="span3 mbot bbot"  name="shopSubTitle" id="shopSubTitle" placeholder="<?php echo $this->translate('Shop Sub-Title'); ?>">
                        <input type="text" id="shopSubTitleLeft" class="input-xlarge  btop word-count" value="<?php echo $this->translate("Shop sub-title length ").strlen($this->data['subTitle']) . $this->translate(' characters');?>"   placeholder="<?php echo $this->translate('0 characters');?>" disabled="disabled">
                        
                        </div>
                    </div>
                </div>
				<div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Custom Header Text'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                        	<textarea class="input-xlarge mbot bbot ignore" id="shopCustomHeader" name="shopCustomHeader" placeholder="<?php echo $this->translate ( 'Custom Header Text' );?>" rows="3"><?php echo $this->data['customHeader']; ?></textarea>
							<input type="text" disabled="disabled" value="<?php echo $this->translate("Shop custom header length ").strlen($this->data['customHeader']). $this->translate(' characters');?>" id="shopCustomHeaderLeft" class="input-xlarge disabled btop word-count">
                     	</div>
                    </div>
                </div>
            </div>
        
            <div class="mainpage-content">
            	<div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Notes'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                        	
                        	<textarea class="input-xlarge mbot bbot ignore word_count" id="shopNotes" placeholder="<?php echo $this->translate('Short note about the shop'); ?>" rows="3" name="shopNotes" ><?php echo $this->data['notes'] ; ?></textarea>
                    		<input type="text" class="input-xlarge disabled btop word-count"  id="shopNotesLeft" value = "" placeholder="" disabled="disabled">
                         </div>
                    </div>
                </div>
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Shop Editor Backend'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                           <select class="mainpage-content-right-select"  id="selecteditors" name="selecteditors" onChange="getMangerName($(this).find(':selected').text(),4)">
                           	<option default="default" value=""><?php echo $this->translate('None'); ?></option>
                            <?php for($i=0;$i<count($this->MangersList['editors']);$i++){?>
                           
                            <?php  if( $this->MangersList['editors'][$i]['id'] == $this->data['contentManagerId'] ) { ?>
                           
                           		<option selected="selected" value="<?php echo $this->MangersList['editors'][$i]['id'];?>"><?php echo ucfirst($this->MangersList['editors'][$i]['fname'] . " " . $this->MangersList['editors'][$i]['lname']);?></option>
                           
                            <?php } else { ?>
                            
                         	    <option value="<?php echo $this->MangersList['editors'][$i]['id'];?>"><?php echo $this->MangersList['editors'][$i]['fname']. " " . $this->MangersList['editors'][$i]['lname'];?></option>
                            
                            <?php } }?>
                          </select>
                       </div>   
                  </div>
                </div>
            </div>
            
            <div class="mainpage-content position-r">
                <div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Category'); ?></strong></label></div>
                    
                    <div class="mainpage-content-right">
                      <div class="category-error"></div>
                      <div class="categories" style="position:relative;">
              <?php 
              for($i = 0;  $i < count($this->categoryList) ; $i++){ ?>
              	<div class="square-btn-offer">
              <?php 
              			if( @in_array( $this->categoryList[$i][0]['id'] , $this->catArray ) )
              				{
              					$checked = 'checked="checked"' ;
              				
              				} else {
              					
              					$checked = '' ;
              				}
              				?>
				<input type="checkbox" <?php echo $checked ;?> value="<?php echo $this->categoryList[$i][0]['id']; ?>" class="" name="selectedCategoryies[]" id="category-<?php echo $this->categoryList[$i][0]['id']; ?>" />
				 <?php
							
	                       
	                           if(trim($this->categoryList[$i][0]['name'])!=''){ 
	                           	
	                           	$categoryIconPath = '';
	                           	 
	                           	 
	                           	$icons = $this->categoryList[$i][0]['categoryicon'];
	                           	 

	                           	# check an icon is available of not
	                           	if(file_exists(ROOT_PATH.$icons['path']."thum_medium_".$icons['name'])){
	                           		$categoryIconPath = PUBLIC_PATH_LOCALE.$icons['path']."thum_medium_".$icons['name'];
	                           	}else {
	                           		$categoryIconPath = HTTP_PATH ."public/images/NoImage/NoImage50x50.jpg";
	                           	}
	                           	
	                           	
	                      	?>
	                      	<button type="button" title="<?php echo $this->categoryList[$i][0]['name'];?>" class="btn square-btn <?php echo  @in_array( $this->categoryList[$i][0]['id'] , $this->catArray )  ? "btn-primary" : "" ?>" id="categoryBtn-<?php echo $this->categoryList[$i][0]['id'];?>" onClick="addCategory(event,'<?php echo $this->categoryList[$i][0]['id']; ?>')">
	                      		<img onclick="$('#categoryBtn-<?php echo $this->categoryList[$i][0]['id'];?>').click();" alt="Baby &amp; Kinderen" src="<?php echo $categoryIconPath ;?>">
	                      	</button>
                      		<div class="clear"></div>
				        	<span class="image-description-text">	  			   
									<?php echo strlen($this->categoryList[$i][0]['name']) < 20 ? $this->categoryList[$i][0]['name'] : substr($this->categoryList[$i][0]['name'],0,20).'..'; ?>			    
		  					</span>
	                      	<?php } ?>
	                              	</div>
				              <?php } ?>
                    
                    	</div>
                  </div>
                  
                </div>
            </div>
            <div id="post-body-content">                         
                <div class="mainpage-content">
                    <div class="mainpage-content-line mb10">
                        <div class="mainpage-content-left">
                            <h3>
                                <strong><?php echo $this->translate('Ballon Text'); ?></strong>
                            </h3>
                        </div>
                        <div class="mainpage-content-right">&nbsp;</div>
                    </div>
                            
                    <div id="multidiv" >   
                    <?php echo $this->partialLoop('shop/addballontext.phtml',$this->ballonData);?>
                    </div>
                    <div class="mainpage-content-colorbox">
                        <a href="javascript:;" style="float:right;margin-top: 7px;" 
                        onclick="getBallonTexthtml(this);" rel="<?php echo count($this->ballonData) ?>"><strong>
                        <?php echo $this->translate('+ Add another Text'); ?></strong></a>
                    </div>
                <div class="clear"></div>
                </div> 
            </div> 
            <?php
                if (empty($this->shopReasons)) { 
            ?>
            <div class="mainpage-content">
                <div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><strong><?php echo $this->translate("add reasons to buy"); ?></strong></div>
                    <div class="mainpage-content-right">
                        <div class="btn-group" data-toggle="buttons-checkbox">
                            <button type="button" class="btn" onClick="setOnOff(event,'reasons','on');$('#buyReasons').removeClass('display-none');"><?php echo $this->translate('Yes'); ?></button>                     
                            <button type="button" class="btn btn-primary default" onClick="setOnOff(event,'reasons','off');$('#buyReasons').addClass('display-none')"><?php echo $this->translate('No'); ?></button>
                          </div>
                    </div>          
                </div>
            </div>
            <?php } ?>
            <div class="mainpage-content" id = "buyReasons">
                <div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate("6 Reasons to Choose Shop");?></strong></label>
                    </div>
                </div>
                <br/>
                <div id="reasons">
                    <div class="mainpage-content-line">
                        <div class="mainpage-content-left">
                            <label><strong><?php echo $this->translate("Title");?></strong></label>
                        </div>
                        <div class="mainpage-content-right">
                            <div class="mainpage-content-right-inner-right-other"></div>
                            <div class="mainpage-content-right-inner-left-other">
                                <input id="reasontitle1" class="span3 ignore" style="margin-bottom: 0;" type="text" value = "<?php echo $value = !empty($this->shopReasons[0]['fieldvalue']) ? $this->shopReasons[0]['fieldvalue'] : '';?>" name="reasontitle1">
                            </div>    
                        </div>
                    </div>
                    <div class="mainpage-content-line">      
                        <div class="mainpage-content-left">
                            <label><strong><?php echo $this->translate("Sub-Title");?></strong></label>
                        </div>
                        <div class="mainpage-content-right">
                            <div class="mainpage-content-right-inner-right-other"></div>
                            <div class="mainpage-content-right-inner-left-other">
                                <textarea id="reasonsubtitle1" class="input-xlarge mbot bbot ignore" name="reasonsubtitle1" rows="3" ><?php echo $value =  !empty($this->shopReasons[1]['fieldvalue']) ? $this->shopReasons[1]['fieldvalue'] : '';?></textarea>
                                <div class="charleft originalTextareaInfo" style="display: none; width: 669px;"></div>
                                <span id="reasonsubtitle1count" class="nobel disabled btop word-count shop-wordcount-width"><?php echo $this->translate('Shop reason sub title length 512 characters remaining');?></span>
                            </div>
                        </div>
                    </div>    

                    <div class="mainpage-content-line">
                        <div class="mainpage-content-left">
                            <label><strong><?php echo $this->translate("Title");?></strong></label>
                        </div>
                        <div class="mainpage-content-right">
                            <div class="mainpage-content-right-inner-right-other"></div>
                            <div class="mainpage-content-right-inner-left-other">
                                <input id="reasontitle2" class="span3 ignore" style="margin-bottom: 0;" type="text" value = "<?php echo $value = !empty($this->shopReasons[2]['fieldvalue']) ?  $this->shopReasons[2]['fieldvalue'] : '';?>" name="reasontitle2">
                            </div>
                        </div>
                    </div>
                    <div class="mainpage-content-line">  
                        <div class="mainpage-content-left">
                            <label><strong><?php echo $this->translate("Sub-Title");?></strong></label>
                        </div>
                        <div class="mainpage-content-right">
                            <div class="mainpage-content-right-inner-right-other"></div>
                            <div class="mainpage-content-right-inner-left-other">
                                <textarea id="reasonsubtitle2" class="input-xlarge mbot bbot ignore" name="reasonsubtitle2" rows="3"><?php echo $value = !empty($this->shopReasons[3]['fieldvalue']) ? $this->shopReasons[3]['fieldvalue'] : '';?></textarea>
                                <div class="charleft originalTextareaInfo" style="display: none; width: 669px;"></div>
                                <span id="reasonsubtitle2count" class="nobel disabled btop word-count shop-wordcount-width"><?php echo $this->translate('Shop reason sub title length 512 characters remaining');?></span>
                            </div>    
                        </div>
                    </div>
                    <div class="mainpage-content-line">
                        <div class="mainpage-content-right">
                            <div class="coupon-sidebar-content-box-shop mb10">
                                <button class="btn down" id="addreason1" href="#" type="button"><?php echo $this->translate('Add More Reason');?></button>
                                <button class="btn" href="#" type="button" id="deletereason" onclick="deleteShopReason('reasontitle1','reasonsubtitle1', 'reasontitle2', 'reasonsubtitle2',<?php echo $shopId = !empty($this->shopReasons) ? $this->shopReasons[0]['shopid'] : '';?>)"><?php echo $this->translate('Delete Reasons');?></button>
                            </div>
                        </div>
                    </div>  
                </div>
                <div id="reasons3">
                    <div class="mainpage-content-line">
                        <div class="mainpage-content-left">
                            <label><strong><?php echo $this->translate("Title");?></strong></label>
                        </div>
                        <div class="mainpage-content-right">
                            <div class="mainpage-content-right-inner-right-other"></div>
                            <div class="mainpage-content-right-inner-left-other">
                                <input id="reasontitle3" class="span3 ignore" style="margin-bottom: 0;" type="text" value = "<?php echo $value = !empty($this->shopReasons[4]['fieldvalue']) ? $this->shopReasons[4]['fieldvalue'] : '';?>" name="reasontitle3">
                            </div>    
                        </div>
                    </div>
                    <div class="mainpage-content-line"> 
                        <div class="mainpage-content-left">
                            <label><strong><?php echo $this->translate("Sub-Title");?></strong></label>
                        </div>
                        <div class="mainpage-content-right">
                            <div class="mainpage-content-right-inner-right-other"></div>
                            <div class="mainpage-content-right-inner-left-other">
                                <textarea id="reasonsubtitle3" class="input-xlarge mbot bbot ignore" name="reasonsubtitle3" rows="3"><?php echo $value = !empty($this->shopReasons[5]['fieldvalue']) ? $this->shopReasons[5]['fieldvalue'] : '';?></textarea>
                                <div class="charleft originalTextareaInfo" style="display: none; width: 669px;"></div>
                                <span id="reasonsubtitle3count" class="nobel disabled btop word-count shop-wordcount-width"><?php echo $this->translate('Shop reason sub title length 512 characters remaining');?></span>
                            </div>    
                        </div>
                    </div>
                    <div class="mainpage-content-line">
                        <div class="mainpage-content-left">
                            <label><strong><?php echo $this->translate("Title");?></strong></label>
                        </div>
                        <div class="mainpage-content-right">
                            <div class="mainpage-content-right-inner-right-other"></div>
                            <div class="mainpage-content-right-inner-left-other">
                                <input id="reasontitle4" class="span3 ignore" style="margin-bottom: 0;" type="text" value = "<?php echo $value = !empty($this->shopReasons[6]['fieldvalue']) ? $this->shopReasons[6]['fieldvalue'] : '';?>" name="reasontitle4">
                            </div>    
                        </div>
                    </div>
                    <div class="mainpage-content-line"> 
                        <div class="mainpage-content-left">
                            <label><strong><?php echo $this->translate("Sub-Title");?></strong></label>
                        </div>
                        <div class="mainpage-content-right">
                            <div class="mainpage-content-right-inner-right-other"></div>
                            <div class="mainpage-content-right-inner-left-other">
                                <textarea id="reasonsubtitle4" class="input-xlarge mbot bbot ignore" name="reasonsubtitle4" rows="3"><?php echo $value = !empty($this->shopReasons[7]['fieldvalue']) ? $this->shopReasons[7]['fieldvalue'] : '';?></textarea>
                                <div class="charleft originalTextareaInfo" style="display: none; width: 669px;"></div>
                                <span id="reasonsubtitle4count" class="nobel disabled btop word-count shop-wordcount-width"><?php echo $this->translate('Shop reason sub title length 512 characters remaining');?></span>
                            </div>    
                        </div>
                    </div>
                    <div class="mainpage-content-line">
                        <div class="mainpage-content-right">
                            <div class="coupon-sidebar-content-box-shop mb10">
                                <button class="btn down" id="addreason2" href="#" type="button"><?php echo $this->translate('Add More Reason');?></button>
                                <button class="btn" href="#" type="button" id="deletereason1" onclick="deleteShopReason('reasontitle3','reasonsubtitle3','reasontitle4','reasonsubtitle4',<?php echo $shopId = !empty($this->shopReasons) ? $this->shopReasons[0]['shopid'] : '';?>)"><?php echo $this->translate('Delete Reasons');?></button>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="reasons4">
                    <div class="mainpage-content-line">
                        <div class="mainpage-content-left">
                            <label><strong><?php echo $this->translate("Title");?></strong></label>
                        </div>
                        <div class="mainpage-content-right">
                            <div class="mainpage-content-right-inner-right-other"></div>
                            <div class="mainpage-content-right-inner-left-other">
                                <input id="reasontitle5" class="span3 ignore" style="margin-bottom: 0;" type="text"  value = "<?php echo $value = !empty($this->shopReasons[8]['fieldvalue']) ? $this->shopReasons[8]['fieldvalue'] : '';?>" name="reasontitle5">
                            </div>    
                        </div>
                    </div>
                    <div class="mainpage-content-line"> 
                        <div class="mainpage-content-left">
                            <label><strong><?php echo $this->translate("Sub-Title");?></strong></label>
                        </div>
                        <div class="mainpage-content-right">
                            <div class="mainpage-content-right-inner-right-other"></div>
                            <div class="mainpage-content-right-inner-left-other">
                                <textarea id="reasonsubtitle5" class="input-xlarge mbot bbot ignore" name="reasonsubtitle5" rows="3"><?php echo $value = !empty($this->shopReasons[9]['fieldvalue']) ? $this->shopReasons[9]['fieldvalue'] : '';?></textarea>
                                <div class="charleft originalTextareaInfo" style="display: none; width: 669px;"></div>
                                <span id="reasonsubtitle5count" class="nobel disabled btop word-count shop-wordcount-width"><?php echo $this->translate('Shop reason sub title length 512 characters remaining');?></span>
                            </div>    
                        </div>
                    </div>
                    <div class="mainpage-content-line">
                        <div class="mainpage-content-left">
                            <label><strong><?php echo $this->translate("Title");?></strong></label>
                        </div>
                        <div class="mainpage-content-right">
                            <div class="mainpage-content-right-inner-right-other"></div>
                            <div class="mainpage-content-right-inner-left-other">
                                <input id="reasontitle6" class="span3 ignore" style="margin-bottom: 0;" type="text" value = "<?php echo $value = !empty($this->shopReasons[10]['fieldvalue']) ? $this->shopReasons[10]['fieldvalue'] : '';?>" name="reasontitle6">
                            </div>    
                        </div>
                    </div>
                    <div class="mainpage-content-line"> 
                        <div class="mainpage-content-left">
                            <label><strong><?php echo $this->translate("Sub-Title");?></strong></label>
                        </div>
                        <div class="mainpage-content-right">
                            <div class="mainpage-content-right-inner-right-other"></div>
                            <div class="mainpage-content-right-inner-left-other">
                                <textarea id="reasonsubtitle6" class="input-xlarge mbot bbot ignore" name="reasonsubtitle6" rows="3"><?php echo $value = !empty($this->shopReasons[11]['fieldvalue']) ? $this->shopReasons[11]['fieldvalue'] : '';?></textarea>
                                <div class="charleft originalTextareaInfo" style="display: none; width: 669px;"></div>
                                <span id="reasonsubtitle6count" class="nobel disabled btop word-count shop-wordcount-width"><?php echo $this->translate('Shop reason sub title length 512 characters remaining');?></span>
                            </div>    
                        </div>
                    </div>
                    <div class="mainpage-content-line">
                        <div class="mainpage-content-right">
                            <div class="coupon-sidebar-content-box-shop mb10">
                                <button class="btn" href="#" type="button" onclick="deleteShopReason('reasontitle5','reasonsubtitle5','reasontitle6','reasonsubtitle6',<?php echo $shopId = !empty($this->shopReasons) ? $this->shopReasons[0]['shopid'] : '';?>)" id="deletereason2"><?php echo $this->translate('Delete Reasons');?></button>
                            </div>
                        </div>
                    </div>
                </div>  
            </div>

                <div class="mainpage-content">
            	<div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Similar Shops'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other-shop">
                <div style="overflow-y:scroll;height:169px;width:160px !important;" class="sidebar-content-box-left">
                    <ul id="similarshopListul-li" style='margin : 0px;'>
                    <?php
                    if (!empty($this->data['relatedshops'])) {
                        for($r=0;$r < count ($this->data['relatedshops']);$r++) { 
                            $className = 'grid-line2';
                            if ($r % 2 == 0) {
                                $className = 'grid-line1';
                            }
                            ?> 
                            <li class="<?php echo $className; ?>" 
                                value="<?php echo $this->data['relatedshops'][$r]['relatedshopId']; ?>">
                                <?php echo !empty($this->relatedShopName[$r]) ?
                                    $this->relatedShopName[$r][0]['name'] : ''; ?>
                            </li>
                            <?php 
                        }
                    }
                    ?>                          
                    </ul> 
                </div>      
                 <input type="hidden" name="selectedShop" id="selectedShop" value="" />
                 <input type="hidden" name="similarstoreord" id="similarstoreord" value="" />
                  <div class="coupon-sidebar-outer-shop">
                    <div class="coupon-sidebar-heading-shop">
	                    <input type="text" class="input-medium search-query" id="searchsimilarshop" style="width:295px !important;">
                    </div>
                    <div class="coupon-sidebar-content-box-shop mb10">
                        <button class="btn up" id="moveupBtnbutton" type="button" href="#">MOVE UP</button>
                        <button class="btn" type="button" href="#" id="addsimilarstorebtn" >ADD SIMILAR SHOP</button>
                      </div>
                    
                     <div class="coupon-sidebar-content-box-shop mb10">
                        <button class="btn down" id="movedownBtnbutton" href="#" type="button">MOVE DOWN</button>
                        <button class="btn" href="#" type="button" id="deletesimistorebtn">DELETE</button>
                    </div>
                  
                </div>
                        	
                        </div>
                    </div>    
                </div>

                <div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate("Display similar shops");?></strong></label></div>
                     <div class="mainpage-content-right">
                        <div data-toggle="buttons-checkbox" class="btn-group">
                            <button onClick="setOnOff(event,'similarShops','on');" class="btn <?php if($this->data['showSimliarShops']=='1'){ echo 'btn-primary'; }  ?>" type="button"><?php echo $this->translate('Yes'); ?></button>                     
                            <button onClick="setOnOff(event,'similarShops','off');" class="btn <?php if($this->data['showSimliarShops']=='0' || $this->data['showSimliarShops']==''){ echo 'btn-primary'; }  ?>" style="border-radius: 0 4px 4px 0;" type="button"><?php echo $this->translate('No'); ?></button>
                            <input type="hidden" value="<?php echo $this->data['showSimliarShops'] ? 1 : 0 ;?>" id="similarShops" name="similarShops" style="display:none;"> 
                        </div>
                     </div>
                </div>
                <div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate("Future Code");?></strong></label></div>
                     <div class="mainpage-content-right">
                        <div data-toggle="buttons-checkbox" class="btn-group">
                            <button onClick="setOnOff(event,'futurecode','on');" class="btn <?php if($this->data['futurecode']=='1'){ echo 'btn-primary'; }  ?>" type="button"><?php echo $this->translate('Yes'); ?></button>                     
                            <button onClick="setOnOff(event,'futurecode','off');" class="btn <?php if($this->data['futurecode']=='0' || $this->data['futurecode']==''){ echo 'btn-primary'; }  ?> future-code-radius" type="button"><?php echo $this->translate('No'); ?></button>
                            <input type="hidden" value="<?php echo $this->data['futurecode'] ? 1 : 0 ;?>" id="futurecode" name="futurecode" style="display:none;"> 
                        </div>
                     </div>
                </div>
            </div>
            
            
            <div class="mainpage-content">
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Affiliate network'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                           <select class="mainpage-content-right-select ignore" id="select01" name="shopAffiliateNetwork">
                           	<option default="default" value=""><?php echo $this->translate('None'); ?></option>
                           <?php for($i=0;$i<count($this->affiliateNetworkList);$i++){
                             if(trim( $this->affiliateNetworkList[$i]['name'])!=''){
                           	?>
                           	
                           	  <?php  if( $this->affiliateNetworkList[$i]['id'] == $this->data['affliatenetwork']['id'] ) { ?>
                           
                           		 <option selected="selected"  value="<?php echo $this->affiliateNetworkList[$i]['id']; ?>">
                            
		                            <?php echo $this->affiliateNetworkList[$i]['name']; ?>
		                         </option>
                            <?php } else { ?>
                            
                           	 <option value="<?php echo $this->affiliateNetworkList[$i]['id']; ?>">
                            
                            <?php echo $this->affiliateNetworkList[$i]['name']; ?>
                            </option>
                            
                            <?php } }
                           } ?>
                          </select>
                        </div>
                  </div>
                </div>
    <?php /*    <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Deeplinking code'); ?></strong></label></div>
                    <div class="mainpage-content-right"><div class="mainpage-content-right-inner-left"><div class="btn-group" data-toggle="buttons-checkbox">
                           
                                 <?php 
                            
                            		if( $this->data['deepLinkStatus'] )
                            		{
                            			?>
                            			
                            	
			                            <button type="button" class="btn btn-primary" onClick="setOnOff(event,'deepLink','on')"><?php echo $this->translate('On'); ?></button>                     
			                            <button type="button" class="btn  default" onClick="setOnOff(event,'deepLink','off')"><?php echo $this->translate('Off'); ?></button>
                            			                            
                            	<?php } else { ?>
                            	
                            			                            	
				                            <button type="button" class="btn" onClick="setOnOff(event,'deepLink','on')"><?php echo $this->translate('On'); ?></button>                     
				                            <button type="button" class="btn btn-primary default" onClick="setOnOff(event,'deepLink','off')"><?php echo $this->translate('Off'); ?></button>
                            	
                            	<?php }?>
                           
                          </div></div>
                          <div class="mainpage-content-right-inner-right-other"></div>
                          <div class="mainpage-content-right-inner-right-full"><?php 
                            
                            		if( $this->data['deepLinkStatus'] )
                            		{
                            			?>
                            			<input value="<?php echo $this->data['deepLink'] ; ?>" type="text"  id = "shopDeepLinkUrl" name="shopDeepLinkUrl" class="span3" placeholder="<?php echo $this->translate('Deeplink URL'); ?>">
                            			<?php } else { ?>  <input type="text" disabled="disabled" id = "shopDeepLinkUrl" name="shopDeepLinkUrl" class="span3" placeholder="<?php echo $this->translate('Deeplink URL'); ?>">                           	<?php }?></div></div>
                </div>  */?>
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Ref URL'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                        	<input value="<?php echo $this->data['refUrl'] ; ?>" type="text" class="span3" placeholder="<?php echo $this->translate('Ref URL'); ?>" name="shopRefUrl">
                        </div>
                    </div>
                </div>
                
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Actual URL '); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                        	<input value="<?php echo $this->data['actualUrl'] ; ?>" type="text" class="span3" placeholder="<?php echo $this->translate('Actual URL'); ?>" name="shopActualUrl">
                        </div>
                     </div>
                </div>
                <div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Money shop'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                    	<div class="btn-group" data-toggle="buttons-checkbox">
                            
                            <?php 
                            
                            		if( $this->data['affliateProgram'] )
                            		{
                            			?>
                            			
                            			<button type="button" class="btn btn-primary" onClick="setOnOff(event,'affiliate','on')"><?php echo $this->translate('On'); ?></button>
                            			<button type="button" class="btn  default" onClick="setOnOff(event,'affiliate','off')"><?php echo $this->translate('Off'); ?></button>
                            			                            
                            	<?php } else { ?>
                            	
                            			<button type="button" class="btn" onClick="setOnOff(event,'affiliate','on')"><?php echo $this->translate('On'); ?></button>
                            			<button type="button" class="btn btn-primary default" onClick="setOnOff(event,'affiliate','off')"><?php echo $this->translate('Off'); ?></button>
                            	
                            	<?php }?>
                              
                          </div>
                    </div>
                </div>
                
            </div>
            <div class="mainpage-content">
            	<div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Shop Logo'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                    	<div class="mainpage-content-right-inner-right-other"></div>
                        <?php       
                        $shopPicture = '';
                        if(isset( $this->data['logo']['name'] ) && $this->data['logo']['name'] != '' ) {
                            $shopPicture = PUBLIC_PATH_CDN.  $this->data['logo']['path']. $this->data['logo']['name'] ;
                            }				  
                        ?> 
                        <div class='browse-container'>    
                            <img class='image-container' 
                            alt="<?php echo $this->translate('Shop logo'); ?>" 
                            src="<?php echo $shopPicture ; ?>">
                        </div>
                    	<div class="mainpage-content-right-inner-left-other">
                            <div>
                        	   <input data-max-size="2097152" type="file" name="logoFile" 
                               onchange="checkFileType(event)" class="ignore" />
                           </div>
                    		<div 
                            class="help-inline">
                            <?php echo $this->translate('Image Size: 300px x 150px (*.jpg or *.png file only)'); 
                            ?>
                            </div>
						</div>
                    </div>
                </div>
            </div>
            <div class="mainpage-content">
            	<div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Shoptext'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                        <textarea class="input-xlarge mbot bbot ignore word_count"   id="shopDescription" name="shopDescription" placeholder="<?php echo $this->translate('Small description about the shop.'); ?>" rows="3"><?php echo $this->data['shopText'] ; ?></textarea>
                        <input type="text" id='shopDescription_count' class="input-xlarge disabled btop word-count" disabled="disabled">
                        </div>
                    </div>
                </div>
                <div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left">
                        <label><strong><?php echo $this->translate("backend_Set widget location");?></strong></label>
                    </div>
                    <div class="mainpage-content-right">
                        <div data-toggle="buttons-checkbox" class="btn-group">
                            <button type = "button" onclick="showLightBoxForWidgetLocation()" class="btn">
                                <?php echo $this->translate('backend_Set widget location'); ?>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate("Display singup option");?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div data-toggle="buttons-checkbox" class="btn-group">
                             <button type="button" class="btn <?php if($this->data['showSignupOption']=='1'){ echo 'btn-primary'; }  ?>" onClick="setOnOff(event,'signupOption','on');"><?php echo $this->translate('Yes'); ?></button>                     
                            <button type="button" class="btn <?php if($this->data['showSignupOption']=='0'){ echo 'btn-primary'; }  ?>" onClick="setOnOff(event,'signupOption','off');"><?php echo $this->translate('No'); ?></button> 
                          </div>
                    </div>
                </div>
                <div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Allow user generated content'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div data-toggle="buttons-checkbox" class="btn-group">
                            <button onclick="usergenrated(event,'usergenrated','on')" class="btn <?php if($this->data['usergenratedcontent']=='1'){ echo 'btn-primary'; }  ?>" type="button"><?php echo $this->translate('On'); ?></button>                     
                            <button style="border-radius:0 4px 4px 0" onclick="usergenrated(event,'usergenrated','off')" class="btn <?php if($this->data['usergenratedcontent']=='0'){ echo 'btn-primary'; }  ?>" type="button"><?php echo $this->translate('Off'); ?></button>
                            <input type="checkbox" id="usergenratedchk" <?php if($this->data['usergenratedcontent']=='1'){ echo 'checked'; }  ?>  name="usergenratedchk" style="display:none;"> 
                      </div>
                  </div>    
                </div>
                <div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left">
                        <label><strong><?php echo $this->translate('Allow Discussions'); ?></strong></label>
                    </div>
                    <div class="mainpage-content-right">
                        <div data-toggle="buttons-checkbox" class="btn-group">
                                <button onclick="discussionCheck(event,'on')" class="btn <?php if($this->data['discussions']=='1'){ echo 'btn-primary'; }  ?>" type="button"><?php echo $this->translate('Yes'); ?></button>                     

                                <button style="border-radius:0 4px 4px 0" onclick="discussionCheck(event,'off')" class="btn <?php if($this->data['discussions']=='0' || $this->data['discussions']==''){ echo 'btn-primary'; }  ?>" type="button"><?php echo $this->translate('No'); ?></button>
                                
                                <input type="checkbox" id="discussions" <?php if($this->data['discussions']=='1'){ echo 'checked'; }  ?>  name="discussions" style="display:none;"> 
                        </div>
                    </div>
                </div>
                
                <div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate("Display chains");?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div data-toggle="buttons-checkbox" class="btn-group">
                            <button onClick="setOnOff(event,'showChains','on');" class="btn <?php if($this->data['showChains']=='1'){ echo 'btn-primary'; }  ?>" type="button"><?php echo $this->translate('Yes'); ?></button>                     
                            <button onClick="setOnOff(event,'showChains','off');" class="btn <?php if($this->data['showChains']=='0' || $this->data['showChains']==''){ echo 'btn-primary'; }  ?>" style="border-radius: 0 4px 4px 0;" type="button"><?php echo $this->translate('No'); ?></button>
                          </div>
                    </div>
                </div>
                <div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php 
                        echo $this->translate("Strict Confirmation");?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div data-toggle="buttons-checkbox" class="btn-group">
                            <button onClick="setOnOff(event,'strictConfirmation','on');" class="btn <?php if($this->data['strictConfirmation']=='1'){ echo 'btn-primary'; }  ?>" type="button"><?php echo $this->translate('Yes'); ?></button>                     
                            <button onClick="setOnOff(event,'strictConfirmation','off');" class="btn <?php if($this->data['strictConfirmation']=='0' || $this->data['strictConfirmation']==''){ echo 'btn-primary'; }  ?>" style="border-radius: 0 4px 4px 0;" type="button"><?php echo $this->translate('No'); ?></button>
                          </div>
                    </div>
                </div>
            </div>
<!-- Start New changes Extra Shop properties-->
        <div class="mainpage-content">
            	<div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><strong><?php echo $this->translate("Extra options"); ?></strong></div>
                    <div class="mainpage-content-right">
                    
                    	<div class="mainpage-content-right-inner-left"><div data-toggle="buttons-checkbox" class="btn-group">
                            
                            <?php if($this->data['displayExtraProperties']) : ?>
                            
	                            <button class="btn  btn-primary default" type="button" onClick="setOnOff(event,'displayExtraProperties','on'); $('div.extra-properties-btn-container,div.service-number-outer').removeClass('display-none'); ">On</button>                     
	                            <button class="btn" type="button" onClick="setOnOff(event,'displayExtraProperties','off'); $('div.extra-properties-btn-container,div.service-number-outer').addClass('display-none');">Off</button>

                            <?php else :?>
                            
	                            <button class="btn " type="button" onClick="setOnOff(event,'displayExtraProperties','on'); $('div.extra-properties-btn-container, div.service-number-outer').removeClass('display-none'); ">On</button>                     
	                            <button class="btn  btn-primary default" type="button" onClick="setOnOff(event,'displayExtraProperties','off'); $('div.extra-properties-btn-container,div.service-number-outer').addClass('display-none');">Off</button>
	                            
                            <?php endif;?>
                            
                        </div></div>
                          
                       <div class="mainpage-content-right-inner-right-full">    
	                    	<div class="btn-group" data-toggle="buttons-checkbox">
	                    		<div class="extra-properties-btn-container <?php echo $this->data['displayExtraProperties']== 1 ? '' : 'display-none' ;  ?>">
		                            <button type="button" class="btn <?php echo $this->data['ideal']== 1 ? 'btn-primary' : '' ;  ?>" onClick="setOnOff(event,'ideal','toggle-btn');"><?php echo $this->translate('Ideal'); ?></button>                     
		                            <button type="button" class="btn <?php echo $this->data['qShops']== 1 ? 'btn-primary' : '' ;  ?>" onClick="setOnOff(event,'qShops','toggle-btn');"><?php echo $this->translate('Qshops'); ?></button> 	
		                            <button type="button" class="btn <?php echo $this->data['freeReturns']== 1 ? 'btn-primary' : '' ;  ?>" onClick="setOnOff(event,'freeReturns','toggle-btn');"><?php echo $this->translate('Free returns'); ?></button>                     
		                            <button type="button" class="btn <?php echo $this->data['pickupPoints']== 1 ? 'btn-primary' : '' ; ?>" onClick="setOnOff(event,'pickupPoints','toggle-btn');"><?php echo $this->translate('Many pickup points'); ?></button>                     
		                            <button type="button" class="btn <?php echo $this->data['mobileShop']== 1 ? 'btn-primary' : '' ;  ?>" onClick="setOnOff(event,'mobileShop','toggle-btn');"><?php echo $this->translate('Mobile shop'); ?></button>                     
		                            <button type="button" class="btn <?php echo $this->data['service']== 1 ? 'btn-primary' : '' ;  ?>" onClick="setOnOff(event,'service','toggle-btn'); $('#serviceNumberContainer').hasClass('display-none') ?  $('#serviceNumberContainer').removeClass('display-none') :  $('#serviceNumberContainer').addClass('display-none') ; "><?php echo $this->translate('Service');?></button>                     
	                        	</div>
							</div>
						</div>
                    </div>          
                </div>
                   <div class="service-number-outer <?php echo $this->data['displayExtraProperties']== 1 ? '' : 'display-none' ;  ?>">  
	                    <div class="mainpage-content-right <?php echo $this->data['service']== 1 ? '' : 'display-none' ;  ?>" id="serviceNumberContainer">
	                        <div class="mainpage-content-right-inner-right-other"></div>
	                        <div class="mainpage-content-right-inner-left-other">
	                        	<input type="text" class="span3"  maxlength="60" placeholder="Phone number" name="serviceNumber" value="<?php echo $this->data['service']== 1  ? $this->data['serviceNumber']: '' ; ?>">
	                        </div>
	                     </div>
                     </div>
                </div>
 
<!-- End New changes Extra Shop properties -->  
            <div class="mainpage-content">
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left">
                        <label><strong><?php echo $this->translate('Light box first text'); ?></strong></label>
                    </div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                            <input type="text" class="span3" value="<?php echo $this->data['lightboxfirsttext'] ; ?>"
                            placeholder="<?php echo $this->translate('Light box first text'); ?>" 
                            name="lightboxfirsttext">
                        </div>
                    </div>
                </div>
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left">
                        <label><strong><?php echo $this->translate('Light box second text'); ?></strong></label>
                    </div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                            <input type="text" class="span3" value="<?php echo $this->data['lightboxsecondtext'] ; ?>"
                            placeholder="<?php echo $this->translate('Light box second text'); ?>"
                            name="lightboxsecondtext">
                        </div>
                    </div>
                </div>
            </div>
            <div class="mainpage-content">
                <div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php
                         echo $this->translate("Show Shop Custom Text");?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div data-toggle="buttons-checkbox" class="btn-group">
                             <button type="button"
                             class="btn <?php if($this->data['showcustomtext']=='1'){ echo 'btn-primary'; }  ?>" onClick="setOnOff(event,'customText','on');"><?php echo $this->translate('Yes'); ?></button>                     
                            <button type="button"
                            class="btn <?php if($this->data['showcustomtext']=='0' || $this->data['showcustomtext']==''){ echo 'btn-primary'; }  ?>" onClick="setOnOff(event,'customText','off');"><?php echo $this->translate('No'); ?></button>
                            <input type="hidden" value="<?php echo $this->data['showcustomtext'] ; ?>" id="showcustomtext" name="showcustomtext" style="display:none;"> 
                          </div>
                    </div>
                </div>
                <div id="customText" class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Shop Custom text'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                        <textarea rows="3" id="shopCustomText" name="shopCustomText"
                        class="input-xlarge mbot bbot ignore word_count"><?php echo $value = !empty($this->data['customtext']) ? $this->data['customtext'] : '';?></textarea>
                        </div>
                    </div>
                </div>
                <div id="customtextposition" class="mainpage-content-line">
                    <div class="mainpage-content-left">
                        <label>
                            <strong><?php echo $this->translate('Custom text Under Offer number'); ?></strong>
                        </label>
                    </div>
                    <div class="mainpage-content-right" >
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                            <input type="text" class="span3" 
                            placeholder="<?php echo $this->translate('Custom text Under Offer number'); ?>" 
                            name="customtextposition"  value="<?php echo $value = !empty($this->data['customtextposition']) ? $this->data['customtextposition'] : '';?>">
                        </div>
                    </div>
                </div>
                <div id="moreTextForShop" class="mainpage-content-line mb10">
                    <div class="mainpage-content-left">
                        <label><strong><?php echo $this->translate('More text for shop'); ?></strong></label>
                    </div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                        <textarea rows="3" id="moretextforshop" name="moretextforshop"
                        class="input-xlarge mbot bbot ignore word_count">
                        <?php 
                        echo $value = !empty($this->data['moretextforshop']) 
                        ? $this->data['moretextforshop'] 
                        : '';?>
                        </textarea>
                        </div>
                    </div>
                </div>
            </div> 
            <div class="mainpage-content">
            	<div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left">
                        <strong><?php echo $this->translate("Add a 'How to use the code'"); ?></strong></div>
                    <div class="mainpage-content-right">
                    	<div class="btn-group" data-toggle="buttons-checkbox">
                            
                            <?php 
                            
                            		if( $this->data['howToUse'] )
                            		{
                            			?>
                            			
											<button type="button" class="btn btn-primary" onClick="setOnOff(event,'howtouse','on');$('#howToUseContent').removeClass('display-none');"><?php echo $this->translate('Yes'); ?></button>                     
				                            <button type="button" class="btn  default" onClick="setOnOff(event,'howtouse','off');$('#howToUseContent').addClass('display-none')"><?php echo $this->translate('No'); ?></button>
                            			                            
                            	<?php } else { ?>
                            	
											<button type="button" class="btn" onClick="setOnOff(event,'howtouse','on');$('#howToUseContent').removeClass('display-none');"><?php echo $this->translate('Yes'); ?></button>                     
                            				<button type="button" class="btn btn-primary default" onClick="setOnOff(event,'howtouse','off');$('#howToUseContent').addClass('display-none')"><?php echo $this->translate('No'); ?></button>
                            	
                            	<?php }?>
                            	
                            
                          </div>
                    </div>          
                </div>
            </div>
            
            
            <div class="mainpage-content <?php echo ( $this->data['howToUse'] ) ? "" : "display-none"  ; ?>" id="howToUseContent">
            	<div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Upload main image lightbox'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                         <div class="mainpage-content-right-inner-right-other"></div>
                  		  <?php       
	                     	$smallLogo = ''; 
	                        if(
                                isset($this->data['howtousesmallimage']['name']) 
                                && $this->data['howtousesmallimage']['name'] != '' 
                            ) {
	                         	$smallLogo = PUBLIC_PATH_CDN . $this->data['howtousesmallimage']['path']  
                                .$this->data['howtousesmallimage']['name'] ;	
	                      	}	
					  
                 		 ?>
                            <div class='browse-container'>
                                <img class='image-container' alt="<?php echo $this->translate('main image'); ?>" 
                                src="<?php echo $smallLogo ; ?>">
                            </div>
                            <div>
                                <input data-max-size="2097152" onchange="checkFileType(event)"
                                type="file" class="input-file ignore"  name="smallLogoFile"/>
                            </div>
                            <div>
                            <?php echo $this->translate('Image Size: min 300px (*.jpg or *.png file only)'); ?>
                            </div>
                    </div>   
                </div>
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label style="padding:0 14px 0 0;"><strong><?php echo $this->translate('Upload second image lightbox'); ?></strong></label></div>
	                    <div class="mainpage-content-right">
	                        <div class="mainpage-content-right-inner-right-other"></div>
                            <?php       
                            $bigLogo = '';
                            if(
                                isset($this->data['howtousebigimage']['name'] ) 
                                && $this->data['howtousebigimage']['name'] != ''
                            ) {
                                $bigLogo = PUBLIC_PATH_CDN . $this->data['howtousebigimage']['path']
                                . $this->data['howtousebigimage']['name'] ;
                            }
                            ?>
                            <div class='browse-container'>
                                <img class='image-container'
                                alt="<?php echo $this->translate('second image'); ?>" src="<?php echo $bigLogo ; ?>">
                            </div>
                            <div>
                                <input data-max-size="2097152" onchange="checkFileType(event)" type="file" 
                                class="input-file ignore" name="bigLogoFile" >
                            </div>
                            <div>
                            <?php echo $this->translate('Image Size: min 300px (*.jpg or *.png file only)'); ?>
                            </div>
                   </div>
                                       
                </div>
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left">
                        <label><strong><?php echo $this->translate('Page slug'); ?></strong></label>
                    </div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-left-other">
                            <input type="text" name="howToPageSlug" id="howToPageSlug" class="span3" 
                            placeholder="<?php echo $this->translate('Page slug'); ?>" 
                            value="<?php echo $this->data['howtoguideslug'] ; ?>" style="margin-bottom: 0;">
                            <input type="text" id="howToPageSlugLeft" class="input-xlarge  btop word-count" 
                            value="<?php echo $this->translate("Page slug length ")
                            . strlen($this->data['howtoguideslug']) 
                            . $this->translate(' characters');?>"
                            placeholder="<?php echo $this->translate('0 characters');?>" disabled="disabled">
                        </div>
                    </div>
                </div>
            	<div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Page title'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                    	<div class="mainpage-content-right-inner-left-other">
                    		<input type="text" name="pageTitle" id="pageTitle" class="span3" placeholder="<?php echo $this->translate('Page title'); ?>" value="<?php echo $this->data['howtoTitle'] ; ?>" style="margin-bottom: 0;">
                            <input type="text" id="pageTitleLeft" class="input-xlarge  btop word-count" value="<?php echo $this->translate("Page title length "). strlen($this->data['howtoTitle']) . $this->translate(' characters');?>" placeholder="<?php echo $this->translate('0 characters');?>" disabled="disabled">
                    	</div>
                    </div>
                </div>
                        
                <div class="mainpage-content-line">
                     <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Page Subtitle'); ?></strong></label></div>
                     <div class="mainpage-content-right">
                     	<div class="mainpage-content-right-inner-left-other">
                     		<input type="text" name="pageSubTitle" id="pageSubTitle" class="span3" placeholder="<?php echo $this->translate('Page Subtitle'); ?>" value="<?php echo $this->data['howtoSubtitle'] ; ?>" style="margin-bottom: 0;">
                        <input type="text" id="pageSubTitleLeft" class="input-xlarge  btop word-count" value="<?php echo $this->translate("Page sub title length "). strlen($this->data['howtoSubtitle']) . $this->translate(' characters');?>" placeholder="<?php echo $this->translate('0 characters');?>" disabled="disabled">
                     	</div>
                     </div>	
                </div>

                <div class="mainpage-content-line">
                    <div class="mainpage-content-left">
                        <label><strong><?php echo $this->translate('Page Sub Subtitle'); ?></strong></label>
                    </div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-left-other">
                            <input type="text" name="pageSubSubTitle" id="pageSubSubTitle" 
                            class="span3" placeholder="<?php echo $this->translate('Page Sub Subtitle'); ?>" 
                            value="<?php echo $this->data['howtoSubSubTitle'] ; ?>" style="margin-bottom: 0;">
                            <input type="text" id="pageSubSubTitleLeft" class="input-xlarge  btop word-count" 
                            value="<?php echo $this->translate("Page Sub sub title length ")
                            . strlen($this->data['howtoSubSubTitle']) . $this->translate(' characters');?>" 
                            placeholder="<?php echo $this->translate('0 characters');?>" disabled="disabled">
                        </div>
                    </div> 
                </div>
                        
                <div class="mainpage-content-line">
                   	 <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Meta title'); ?></strong></label></div>
                     <div class="mainpage-content-right">
                     	<div class="mainpage-content-right-inner-left-other">
		                     <input type="text" name="pagemetaTitle" id="pagemetaTitle" placeholder="<?php echo $this->translate('Meta title');?>" class="input-xlarge mbot bbot ignore" value="<?php echo $this->data['howtoMetaTitle'] ; ?>"/>
                             <span id="pagemetaTitleLeft" class="nobel disabled btop word-count shop-wordcount-width"></span>
						</div>	 
					 </div>
                </div>
                <div class="mainpage-content-line">
                     <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Meta Description'); ?></strong></label></div>
                     <div class="mainpage-content-right">
                     	<div class="mainpage-content-right-inner-left-other">
		                     <textarea class="input-xlarge mbot bbot ignore" id="pagemetaDesc" name="pagemetaDesc" placeholder="<?php echo $this->translate ( 'Meta Description' );?>" rows="3"><?php echo $this->data['howtoMetaDescription'] ; ?></textarea>
                             <span id="pagemetaDescLeft" class="nobel disabled btop word-count shop-wordcount-width"></span>
						</div>	 
					 </div>
                </div>
                <?php echo $howToIntroductionText; ?>

                <div class="mainpage-content">

							<div class="mainpage-content-line mb10">
								<div class="mainpage-content-left">
									<h3>
										<strong><?php echo $this->translate('Chapters'); ?></strong>
									</h3>
								</div>
								<div class="mainpage-content-right">&nbsp;</div>
							</div>
									
							<div id="multidiv" >   
	                	 		<?php echo $this->partialLoop('shop/chapters.phtml',$this->data['howtochapter']);?>
	                	 	</div>
							
							<div class="mainpage-content-colorbox">
								<a href="javascript:;" style="float:right;margin-top: 7px;" onclick="getchapterhtml(this)" rel='<?php echo count($this->data['howtochapter']);?>'><strong><?php echo $this->translate('+ Add another chapter'); ?></strong></a>
							</div>
							<div class="clear"></div>
		
	
				</div>             
            </div>
            
            <input type="hidden" name="shopId" id="shopId" value="<?php  echo $this->data['id']; ?>"/>
            
            <input type="hidden" name="accountManagerName" id="accountManagerName" value="<?php echo $this->data['accountManagerName'] ; ?>" />
            
            <input type="hidden" name="editorName" id="editorName" value="<?php echo $this->data['contentManagerName'] ; ?>" />
            <input type="hidden" name="offlineSince" id="offlineSince" value="<?php echo ( $this->data['status'] ) ? "" :  $this->data['offlineSicne']->format('Y-m-d') ;?>" />
            <input type="hidden" name="onlineStatus" id="onlineStatus" value="<?php echo ( $this->data['status'] ) ?  1 : 0 ; ?>" />
            <input type="hidden" name="deepLinkStatus" id="deepLinkStatus" value="<?php echo ( $this->data['deepLinkStatus'] ) ?  1 : 0 ; ?>" />
            <input type="hidden" name="affiliateProgStatus" id="affiliateProgStatus" value="<?php echo ( $this->data['affliateProgram'] ) ?  1 : 0 ; ?>" />
            <input type="hidden" name="howTouseStatus" id="howTouseStatus" value="<?php echo ( $this->data['howToUse'] ) ?  1 : 0 ; ?>" />
            
            <!-- Extra shop hidden feilds -->
             <input type="hidden" name="displayExtraProperties" id="displayExtraProperties" value="<?php echo ( $this->data['displayExtraProperties'] ); ?>" />
             
            <input type="hidden" name="ideal" id="ideal" value="<?php echo ( $this->data['ideal'] ); ?>" />
            <input type="hidden" name="qShops" id="qShops" value="<?php echo ( $this->data['qShops'] ) ; ?>" />
            <input type="hidden" name="freeReturns" id="freeReturns" value="<?php echo ( $this->data['freeReturns'] ) ; ?>" />
            <input type="hidden" name="pickupPoints" id="pickupPoints" value="<?php echo ( $this->data['pickupPoints'] ) ; ?>" />
            <input type="hidden" name="mobileShop" id="mobileShop" value="<?php echo ( $this->data['mobileShop'] ) ; ?>" />
            <input type="hidden" name="service" id="service" value="<?php echo ( $this->data['service'] ) ; ?>" />
            
            <input type="hidden" name="signupOption" id="signupOption" value="<?php echo ( $this->data['showSignupOption'] ) ; ?>" />
		    <input type="hidden" name="showChains" id="showChains" value="<?php echo ( $this->data['showChains'] ) ; ?>" />
            <input type="hidden" name="strictConfirmation" id="strictConfirmation" value="<?php echo ( $this->data['strictConfirmation'] ) ; ?>" />
            
            <div class="mainpage-content-colorbox">

            	<button type="submit" class="btn btn-large btn-primary fl"><?php echo $this->translate('PUBLISH SHOP'); ?></button>
                <a class="fl m10" href="javascript:void(0);" onClick="window.location.href='<?php echo HTTP_PATH ;?>admin/shop<?php echo '#'.$this->qstring; ?>'"  ><strong><?php echo $this->translate('CANCEL'); ?></strong></a>
                <a class="fl red mt10" onclick="moveToTrash(<?php  echo $this->data['id']; ?>);" href="javascript:void(0);" id="deleteButton"><strong><?php echo $this->translate('DELETE')?></strong></a>
            </div>
            <!-- /poststuff -->
            </form>  <!-- End addUser form -->
        </div>  
      </div>
      </div>   
     <!-- Create shops End -->
<?php 
$shopId = !empty($this->data['id']) ? $this->data['id'] : '';
echo $this->partial('widgetlocation/_widget-location.phtml', array('pageType' => 'shop', 'relatedId' => $shopId));
?>
