<?php 
	$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/jquery.validate.js");
	$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
	$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/edit-shop.js");
	$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/jquery.textareaCounter.plugin.js");
	$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
	$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/jquery-ui-1.8.16.custom.css" );
    $this->headLink ()->appendStylesheet ( PUBLIC_PATH . "js/back_end/openwysiwyg_v1.4.7/styles/wysiwyg.css" );
	$this->headScript ()->appendFile ( PUBLIC_PATH . "/js/jquery.NobleCount.js");
	$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/ckeditor/ckeditor.js");
	$this->headScript ()->appendFile (PUBLIC_PATH . "js/back_end/ckeditor/config.js" );

$howToIntroductionText = '';
$howToIntroductionText = $this->partial(
    'shop/_how-to-introduction-text.phtml',
    array('howToIntroductionText'=> $this->data['howToIntroductionText'])
);

echo $this->headTitle()->append('Edit Shop');?>
<div id="imbullbody-content" style="overflow: hidden;">
      
 
 <!-- Create shops Start -->
   <div id="createNewShop">        
    <form method="POST" name="createShop" id="createShop" enctype=multipart/form-data>
      <div class="wrap columns-2">
        <?php if($this->data['status'] == 0):  ?>
           <div class="alert alert-danger bs-alert-old-docs text-center mt10 ">
                <strong><?php echo $this->translate("THIS SHOP IS OFFLINE ATM"); ?></strong>
            </div>
       <?php endif; ?>
        <!-- Start addUser form -->
         
            <h1>
                <?php echo $this->translate('Edit Shop'); ?>
                <button class="btn ml10" type="button" onClick="window.location.href='<?php echo HTTP_PATH ;?>admin/shop<?php echo '#'.$this->qstring; ?>'"><?php echo $this->translate('Cancel'); ?></button>
                <button type="button" class="btn btn-primary ml10" id='prefillData'><?php echo $this->translate('Pre-fill'); ?></button>	
                <?php $host = 'kortingscode.nl';
                if ($_COOKIE['site_name'] != 'kortingscode.nl') {
                    $host = 'flipit.com/admin';
                } 
                ?>
                <?php $hash = md5($this->data['id'].date('Y').'-'.date('m').'-'.date('d').':'.date('H')); ?>
                <a href="<?php echo 'http://'.$host.'/branding/start?storeUrl=http://'.$_COOKIE['site_name'].'/' ?><?php echo $this->data['permaLink'].'&shopID='.$this->data['id'].'&hash='.$hash; ?>" class="btn btn-primary">Brand this shop</a>
            </h1>

         
			<input type="hidden" name='qString' id='qString' value='<?php echo $this->qstring; ?>' />
             <div class="mainpage-content">
             
            	<div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Online'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                    	<div class="btn-group" data-toggle="buttons-checkbox">
                            
                            <?php 
                            
                            		if( $this->data['status'] )
                            		{
                            			?>
                            			
											<button type="button" class="btn btn-primary" onClick="setOnOff(event,'onlineStatus','on');"><?php echo $this->translate('Yes'); ?></button>                     
				                            <button type="button" class="btn  default" onClick="setOnOff(event,'onlineStatus','off');"><?php echo $this->translate('No'); ?></button>
                            			                            
                            	<?php } else { ?>
                            	
											<button type="button" class="btn" onClick="setOnOff(event,'onlineStatus','on');"><?php echo $this->translate('Yes'); ?></button>                     
                            				<button type="button" class="btn btn-primary default" onClick="setOnOff(event,'onlineStatus','off');"><?php echo $this->translate('No'); ?></button>
                            	
                            	<?php }?>
                            	
                            
                          </div>
                    </div>          
                </div>
            </div>
            <div class="mainpage-content">
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Shop Name'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                              <input value="<?php echo $this->data['name'] ; ?>" type="text" class="span3"  id="shopName" name="shopName"  placeholder=<?php echo $this->translate('Shop Name'); ?>>
</div>
                    </div>
                </div>
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Navigational URL'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                    	<div class="mainpage-content-right-inner-left"><label id="navigationalSite"><?php echo $this->translate('http://www.kortingscode.nl/'); ?></label></div>
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-right-full">
                        <input <?php echo ($this->role == '3' || $this->role == '4') ? "disabled=disabled" : "" ;  ?> value="<?php echo $this->data['permaLink'] ; ?>" type="text" class="span3" placeholder="<?php echo $this->translate('Navigational URL'); ?>" name="shopNavUrl" id="shopNavUrl"></div>
                        <?php if($this->role == '3' || $this->role == '4'):?><input value="<?php echo $this->data['permaLink'] ; ?>" type="hidden" name="shopNavUrl" id="shopNavUrl"></div> <?php endif;?>
                    </div>
                </div>
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Overwrite title'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                        	<input value="<?php echo $this->data['overriteTitle'] ; ?>" type="text" class="span3 ignore" placeholder="<?php echo $this->translate('Overwrite Title'); ?>" name="shopOverwriteTitle">
                        </div>
                    </div>    
                </div>
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Meta Description'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
	                        <textarea class="input-xlarge mbot bbot ignore" id="shopMetaDescription" name="shopMetaDescription" placeholder="<?php echo $this->translate ( 'Meta Description' );?>" rows="3"><?php echo $this->data['metaDescription']; ?></textarea>
							<input type="text" disabled="disabled" value="<?php echo $this->translate('Shop meta description length ') . strlen($this->data['metaDescription']). $this->translate(' characters');?>" id="metaTextLeft" class="input-xlarge disabled btop word-count">
                        </div>
                    </div>
                </div>
                 <div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Allow user generated content'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                    	<div data-toggle="buttons-checkbox" class="btn-group">
                            <button onclick="usergenrated(event,'usergenrated','on')" class="btn <?php if($this->data['usergenratedcontent']=='1'){ echo 'btn-primary'; }  ?>" type="button"><?php echo $this->translate('On'); ?></button>                     
                            <button style="border-radius:0 4px 4px 0" onclick="usergenrated(event,'usergenrated','off')" class="btn <?php if($this->data['usergenratedcontent']=='0'){ echo 'btn-primary'; }  ?>" type="button"><?php echo $this->translate('Off'); ?></button>
                            <input type="checkbox" id="usergenratedchk" <?php if($this->data['usergenratedcontent']=='1'){ echo 'checked'; }  ?>  name="usergenratedchk" style="display:none;"> 
                      </div>
                  </div>    
                </div>
                <div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate("Display singup option");?></strong></label></div>
                    <div class="mainpage-content-right">
                    	<div data-toggle="buttons-checkbox" class="btn-group">
                             <button type="button" class="btn <?php if($this->data['showSignupOption']=='1'){ echo 'btn-primary'; }  ?>" onClick="setOnOff(event,'signupOption','on');"><?php echo $this->translate('Yes'); ?></button>                     
                            <button type="button" class="btn <?php if($this->data['showSignupOption']=='0'){ echo 'btn-primary'; }  ?>" onClick="setOnOff(event,'signupOption','off');"><?php echo $this->translate('No'); ?></button> 
                          </div>
                    </div>
                </div>
                <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Allow Discussions'); ?></strong></label></div>
                <div class="mainpage-content-right">
                   	<div data-toggle="buttons-checkbox" class="btn-group">
                            <button onclick="discussionCheck(event,'on')" class="btn <?php if($this->data['discussions']=='1'){ echo 'btn-primary'; }  ?>" type="button"><?php echo $this->translate('Yes'); ?></button>                     

                            <button style="border-radius:0 4px 4px 0" onclick="discussionCheck(event,'off')" class="btn <?php if($this->data['discussions']=='0' || $this->data['discussions']==''){ echo 'btn-primary'; }  ?>" type="button"><?php echo $this->translate('No'); ?></button>
                            
                            <input type="checkbox" id="discussions" <?php if($this->data['discussions']=='1'){ echo 'checked'; }  ?>  name="discussions" style="display:none;"> 
                    </div>
                </div>
				<div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate("Display similar shops");?></strong></label></div>
                     <div class="mainpage-content-right">
                     	<div data-toggle="buttons-checkbox" class="btn-group">
							<button onClick="setOnOff(event,'similarShops','on');" class="btn <?php if($this->data['showSimliarShops']=='1'){ echo 'btn-primary'; }  ?>" type="button"><?php echo $this->translate('Yes'); ?></button>                     
                            <button onClick="setOnOff(event,'similarShops','off');" class="btn <?php if($this->data['showSimliarShops']=='0' || $this->data['showSimliarShops']==''){ echo 'btn-primary'; }  ?>" style="border-radius: 0 4px 4px 0;" type="button"><?php echo $this->translate('No'); ?></button>
                            <input type="hidden" value="<?php echo $this->data['showSimliarShops'] ? 1 : 0 ;?>" id="similarShops" name="similarShops" style="display:none;"> 
                        </div>
                     </div>
                </div>
                
             	<div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate("Display chains");?></strong></label></div>
                    <div class="mainpage-content-right">
                    	<div data-toggle="buttons-checkbox" class="btn-group">
                            <button onClick="setOnOff(event,'showChains','on');" class="btn <?php if($this->data['showChains']=='1'){ echo 'btn-primary'; }  ?>" type="button"><?php echo $this->translate('Yes'); ?></button>                     
                            <button onClick="setOnOff(event,'showChains','off');" class="btn <?php if($this->data['showChains']=='0' || $this->data['showChains']==''){ echo 'btn-primary'; }  ?>" style="border-radius: 0 4px 4px 0;" type="button"><?php echo $this->translate('No'); ?></button>
                          </div>
                    </div>
                </div>
                <div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php 
                        echo $this->translate("Strict Confirmation");?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div data-toggle="buttons-checkbox" class="btn-group">
                            <button onClick="setOnOff(event,'strictConfirmation','on');" class="btn <?php if($this->data['strictConfirmation']=='1'){ echo 'btn-primary'; }  ?>" type="button"><?php echo $this->translate('Yes'); ?></button>                     
                            <button onClick="setOnOff(event,'strictConfirmation','off');" class="btn <?php if($this->data['strictConfirmation']=='0' || $this->data['strictConfirmation']==''){ echo 'btn-primary'; }  ?>" style="border-radius: 0 4px 4px 0;" type="button"><?php echo $this->translate('No'); ?></button>
                          </div>
                    </div>
                </div>
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Title'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
							<input value="<?php echo $this->data['title'] ; ?>" type="text" class="span3 mbot bbot"  name="shopTitle" id="shopTitle" placeholder="<?php echo $this->translate('Shop Title'); ?>">
							<input type="text" id="shopTitleLeft" class="input-xlarge  btop word-count" value="<?php echo $this->translate("Shop title length "). strlen($this->data['title']) . $this->translate(' characters');?>" placeholder="<?php echo $this->translate('0 characters');?>" disabled="disabled">
                        </div>
                    </div>
                </div>
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Sub-title'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                        
                        <input value="<?php echo $this->data['subTitle'] ; ?>" type="text" class="span3 mbot bbot"  name="shopSubTitle" id="shopSubTitle" placeholder="<?php echo $this->translate('Shop Sub-Title'); ?>">
                        <input type="text" id="shopSubTitleLeft" class="input-xlarge  btop word-count" value="<?php echo $this->translate("Shop sub-title length ").strlen($this->data['subTitle']) . $this->translate(' characters');?>"   placeholder="<?php echo $this->translate('0 characters');?>" disabled="disabled">
                        
                        </div>
                    </div>
                </div>
				<div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Custom Header Text'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                        	<textarea class="input-xlarge mbot bbot ignore" id="shopCustomHeader" name="shopCustomHeader" placeholder="<?php echo $this->translate ( 'Custom Header Text' );?>" rows="3"><?php echo $this->data['customHeader']; ?></textarea>
							<input type="text" disabled="disabled" value="<?php echo $this->translate("Shop custom header length ").strlen($this->data['customHeader']). $this->translate(' characters');?>" id="shopCustomHeaderLeft" class="input-xlarge disabled btop word-count">
                     	</div>
                    </div>
                </div>
            </div>
        
            <div class="mainpage-content">
            	<div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Notes'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                        	
                        	<textarea class="input-xlarge mbot bbot ignore word_count" id="shopNotes" placeholder="<?php echo $this->translate('Short note about the shop'); ?>" rows="3" name="shopNotes" ><?php echo $this->data['notes'] ; ?></textarea>
                    		<input type="text" class="input-xlarge disabled btop word-count"  id="shopNotesLeft" value = "" placeholder="" disabled="disabled">
                         </div>
                    </div>
                </div>
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Editor'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                           <select class="mainpage-content-right-select"  id="selecteditors" name="selecteditors" onChange="getMangerName($(this).find(':selected').text(),4)">
                           	<option default="default" value=""><?php echo $this->translate('None'); ?></option>
                            <?php for($i=0;$i<count($this->MangersList['editors']);$i++){?>
                           
                            <?php  if( $this->MangersList['editors'][$i]['id'] == $this->data['contentManagerId'] ) { ?>
                           
                           		<option selected="selected" value="<?php echo $this->MangersList['editors'][$i]['id'];?>"><?php echo ucfirst($this->MangersList['editors'][$i]['fname'] . " " . $this->MangersList['editors'][$i]['lname']);?></option>
                           
                            <?php } else { ?>
                            
                         	    <option value="<?php echo $this->MangersList['editors'][$i]['id'];?>"><?php echo $this->MangersList['editors'][$i]['fname']. " " . $this->MangersList['editors'][$i]['lname'];?></option>
                            
                            <?php } }?>
                          </select>
                       </div>   
                  </div>
                </div>
            </div>
            
            <div class="mainpage-content position-r">
                <div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Category'); ?></strong></label></div>
                    
                    <div class="mainpage-content-right">
                      <div class="category-error"></div>
                      <div class="categories" style="position:relative;">
              <?php   
              for($i = 0;  $i < count($this->categoryList) ; $i++){ ?>
              	<div class="square-btn-offer">
              <?php 
              			if( @in_array( $this->categoryList[$i]['id'] , $this->catArray ) )
              				{
              					$checked = 'checked="checked"' ;
              				
              				} else {
              					
              					$checked = '' ;
              				}
              				?>
				<input type="checkbox" <?php echo $checked ;?> value="<?php echo $this->categoryList[$i]['id']; ?>" class="" name="selectedCategoryies[]" id="category-<?php echo $this->categoryList[$i]['id']; ?>" />
				 <?php
							
	                       
	                           if(trim($this->categoryList[$i]['name'])!=''){ 
	                           	
	                           	$categoryIconPath = '';
	                           	 
	                           	 
	                           	$icons = $this->categoryList[$i];
	                           	 
	                           	 
	                           	# check an icon is available of not
	                           	if(file_exists(ROOT_PATH.$icons['categoryicon']['path']."thum_medium_".$icons['categoryicon']['name'])){
	                           		$categoryIconPath = PUBLIC_PATH_LOCALE.$icons['categoryicon']['path']."thum_medium_".$icons['categoryicon']['name'];
	                           	}else {
	                           		$categoryIconPath = HTTP_PATH ."public/images/NoImage/NoImage50x50.jpg";
	                           	}
	                           	
	                           	
	                      	?>
	                      	<button type="button" title="<?php echo $this->categoryList[$i]['name'];?>" class="btn square-btn <?php echo  @in_array( $this->categoryList[$i]['id'] , $this->catArray )  ? "btn-primary" : "" ?>" id="categoryBtn-<?php echo $this->categoryList[$i]['id'];?>" onClick="addCategory(event,'<?php echo $this->categoryList[$i]['id']; ?>')">
	                      		<img onclick="$('#categoryBtn-<?php echo $this->categoryList[$i]['id'];?>').click();" alt="Baby &amp; Kinderen" src="<?php echo $categoryIconPath ;?>">
	                      	</button>
                      		<div class="clear"></div>
				        	<span class="image-description-text">	  			   
									<?php echo strlen($this->categoryList[$i]['name']) < 20 ? $this->categoryList[$i]['name'] : substr($this->categoryList[$i]['name'],0,20).'..'; ?>			    
		  					</span>
	                      	<?php } ?>
	                              	</div>
				              <?php } ?>
                    
                    	</div>
                  </div>
                  
                </div>
            </div>
            
            
                <div class="mainpage-content">
            	<div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Similar Shops'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other-shop">
                 
                 
                 <div style="overflow-y:scroll;height:169px;width:160px !important;" class="sidebar-content-box-left">
                         
                         <ul id="similarshopListul-li" style='margin : 0px;'>
                          
                          <?php for($r=0;$r<count($this->data['relatedshops']);$r++){ 
                          $className = 'grid-line2';
							if ($r % 2 == 0) {
								$className = 'grid-line1';
							}
						?> 
                          <li class="<?php echo $className; ?>" value="<?php echo $this->data['relatedshops'][$r]['id']; ?>"><?php echo $this->data['relatedshops'][$r]['name']; ?></li>
                          <?php }?>                          
                         </ul> 
                </div>      
                 <input type="hidden" name="selectedShop" id="selectedShop" value="" />
                 <input type="hidden" name="similarstoreord" id="similarstoreord" value="" />
                  <div class="coupon-sidebar-outer-shop">
                    <div class="coupon-sidebar-heading-shop">
	                    <input type="text" class="input-medium search-query" id="searchsimilarshop" style="width:295px !important;">
                    </div>
                    <div class="coupon-sidebar-content-box-shop mb10">
                        <button class="btn up" id="moveupBtnbutton" type="button" href="#">MOVE UP</button>
                        <button class="btn" type="button" href="#" id="addsimilarstorebtn" >ADD SIMILAR SHOP</button>
                      </div>
                    
                     <div class="coupon-sidebar-content-box-shop mb10">
                        <button class="btn down" id="movedownBtnbutton" href="#" type="button">MOVE DOWN</button>
                        <button class="btn" href="#" type="button" id="deletesimistorebtn">DELETE</button>
                    </div>
                  
                </div>
                        	
                        </div>
                    </div>    
                </div>
            </div>
            
            
            <div class="mainpage-content">
            	
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Affiliate network'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                           <select class="mainpage-content-right-select ignore" id="select01" name="shopAffiliateNetwork">
                           	<option default="default" value=""><?php echo $this->translate('None'); ?></option>
                           <?php for($i=0;$i<count($this->affiliateNetworkList);$i++){
                             if(trim( $this->affiliateNetworkList[$i]['name'])!=''){
                           	?>
                           	
                           	  <?php  if( $this->affiliateNetworkList[$i]['id'] == $this->data['affliateNetworkId'] ) { ?>
                           
                           		 <option selected="selected"  value="<?php echo $this->affiliateNetworkList[$i]['id']; ?>">
                            
		                            <?php echo $this->affiliateNetworkList[$i]['name']; ?>
		                         </option>
                            <?php } else { ?>
                            
                           	 <option value="<?php echo $this->affiliateNetworkList[$i]['id']; ?>">
                            
                            <?php echo $this->affiliateNetworkList[$i]['name']; ?>
                            </option>
                            
                            <?php } }
                           } ?>
                          </select>
                        </div>
                  </div>
                </div>
    <?php /*    <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Deeplinking code'); ?></strong></label></div>
                    <div class="mainpage-content-right"><div class="mainpage-content-right-inner-left"><div class="btn-group" data-toggle="buttons-checkbox">
                           
                                 <?php 
                            
                            		if( $this->data['deepLinkStatus'] )
                            		{
                            			?>
                            			
                            	
			                            <button type="button" class="btn btn-primary" onClick="setOnOff(event,'deepLink','on')"><?php echo $this->translate('On'); ?></button>                     
			                            <button type="button" class="btn  default" onClick="setOnOff(event,'deepLink','off')"><?php echo $this->translate('Off'); ?></button>
                            			                            
                            	<?php } else { ?>
                            	
                            			                            	
				                            <button type="button" class="btn" onClick="setOnOff(event,'deepLink','on')"><?php echo $this->translate('On'); ?></button>                     
				                            <button type="button" class="btn btn-primary default" onClick="setOnOff(event,'deepLink','off')"><?php echo $this->translate('Off'); ?></button>
                            	
                            	<?php }?>
                           
                          </div></div>
                          <div class="mainpage-content-right-inner-right-other"></div>
                          <div class="mainpage-content-right-inner-right-full"><?php 
                            
                            		if( $this->data['deepLinkStatus'] )
                            		{
                            			?>
                            			<input value="<?php echo $this->data['deepLink'] ; ?>" type="text"  id = "shopDeepLinkUrl" name="shopDeepLinkUrl" class="span3" placeholder="<?php echo $this->translate('Deeplink URL'); ?>">
                            			<?php } else { ?>  <input type="text" disabled="disabled" id = "shopDeepLinkUrl" name="shopDeepLinkUrl" class="span3" placeholder="<?php echo $this->translate('Deeplink URL'); ?>">                           	<?php }?></div></div>
                </div>  */?>
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Ref URL'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                        	<input value="<?php echo $this->data['refUrl'] ; ?>" type="text" class="span3" placeholder="<?php echo $this->translate('Ref URL'); ?>" name="shopRefUrl">
                        </div>
                    </div>
                </div>
                
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Actual URL '); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                        	<input value="<?php echo $this->data['actualUrl'] ; ?>" type="text" class="span3" placeholder="<?php echo $this->translate('Actual URL'); ?>" name="shopActualUrl">
                        </div>
                     </div>
                </div>
                <div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Money shop'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                    	<div class="btn-group" data-toggle="buttons-checkbox">
                            
                            <?php 
                            
                            		if( $this->data['affliateProgram'] )
                            		{
                            			?>
                            			
                            			<button type="button" class="btn btn-primary" onClick="setOnOff(event,'affiliate','on')"><?php echo $this->translate('On'); ?></button>
                            			<button type="button" class="btn  default" onClick="setOnOff(event,'affiliate','off')"><?php echo $this->translate('Off'); ?></button>
                            			                            
                            	<?php } else { ?>
                            	
                            			<button type="button" class="btn" onClick="setOnOff(event,'affiliate','on')"><?php echo $this->translate('On'); ?></button>
                            			<button type="button" class="btn btn-primary default" onClick="setOnOff(event,'affiliate','off')"><?php echo $this->translate('Off'); ?></button>
                            	
                            	<?php }?>
                              
                          </div>
                    </div>
                </div>
                
            </div>
            <div class="mainpage-content">
            	<div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Shop Logo'); ?></strong></label></div>
                    <div class="mainpage-content-right ">
                    	<div class="mainpage-content-right-inner-right-other"></div>
                     <?php       
					     
	                     	$shopPicture = PUBLIC_PATH.'images/upload/no.jpg';
	                        if(isset( $this->data['logo']['name'] ) && $this->data['logo']['name'] != '' ) {
						  		
	                        	 if( file_exists ( ROOT_PATH .  $this->data['logo']['path'] .'thum_large_'. $this->data['logo']['name'] )) {
	                        	 	
	                         		$shopPicture = PUBLIC_PATH_LOCALE.  $this->data['logo']['path']  .'thum_large_'. $this->data['logo']['name'] ;
	                         
	                         	}
	                      	}	
						  
                      ?>
                        
                        <img alt="<?php echo $this->translate('Shop logo'); ?>" src="<?php echo $shopPicture ; ?>">
                    	<div style="margin-right: 0px;" class="mainpage-content-right-inner-left-other">
						</br>
                    	<input data-max-size="2097152" type="file" name="logoFile" onchange="checkFileType(event)" class="ignore" />
                    		<span class="ml15 help-inline" style="display: inline-block; padding-bottom: 5px;"><?php echo $this->translate('Upload .jpg or .png file only (Maximum file size: 2MB , Ratio 2:01)'); ?></span>
						</div>
                    </div>
                </div>
                
                   <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Website Screenshot'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                     <div class="mainpage-content-right-inner-right-other"></div>
                      <?php       
					
	                     	$shopPicture = PUBLIC_PATH.'images/upload/no.jpg';
						 			 
	                        if(isset( $this->data['screenshot']['name'] ) && $this->data['screenshot']['name'] != '' ) {
						  
	                        	 if( file_exists ( ROOT_PATH .  $this->data['screenshot']['path'] .'thum_large_'. $this->data['screenshot']['name'] )) {
	                        	 	
	                         		$shopPicture = PUBLIC_PATH_LOCALE.  $this->data['screenshot']['path']  .'thum_large_'. $this->data['screenshot']['name'] ;
	                         
	                         	}
	                      	}	
						  
                      ?>
                        
                        <img alt="<?php echo $this->translate('Shop screen shot'); ?>" src="<?php echo $shopPicture ; ?>">
                    	
                      	<div style="margin-right: 0px;" class="mainpage-content-right-inner-left-other">
                      	</br>
                        	<input  data-max-size="2097152" type="file" name="websitescreenshot" onchange="checkFileType(event)" class="ignore" />
				        	<span id="logo_file_message" class="ml15 help-inline" style="display: inline-block; padding-bottom: 5px;" ><?php echo $this->translate('Upload .jpg or .png file only (Maximum file size: 2MB,Width:450px)'); ?></span>
                    	</div>
                    </div>
                </div>
            </div>
            <div class="mainpage-content">
            	<div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Shoptext'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                        <textarea class="input-xlarge mbot bbot ignore word_count"   id="shopDescription" name="shopDescription" placeholder="<?php echo $this->translate('Small description about the shop.'); ?>" rows="3"><?php echo $this->data['shopText'] ; ?></textarea>
                        <input type="text" id='shopDescription_count' class="input-xlarge disabled btop word-count" disabled="disabled">
                        </div>
                    </div>
                </div>
            </div>
<!-- Start New changes Extra Shop properties-->
        <div class="mainpage-content">
            	<div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><strong><?php echo $this->translate("Extra options"); ?></strong></div>
                    <div class="mainpage-content-right">
                    
                    	<div class="mainpage-content-right-inner-left"><div data-toggle="buttons-checkbox" class="btn-group">
                            
                            <?php if($this->data['displayExtraProperties']) : ?>
                            
	                            <button class="btn  btn-primary default" type="button" onClick="setOnOff(event,'displayExtraProperties','on'); $('div.extra-properties-btn-container,div.service-number-outer').removeClass('display-none'); ">On</button>                     
	                            <button class="btn" type="button" onClick="setOnOff(event,'displayExtraProperties','off'); $('div.extra-properties-btn-container,div.service-number-outer').addClass('display-none');">Off</button>

                            <?php else :?>
                            
	                            <button class="btn " type="button" onClick="setOnOff(event,'displayExtraProperties','on'); $('div.extra-properties-btn-container, div.service-number-outer').removeClass('display-none'); ">On</button>                     
	                            <button class="btn  btn-primary default" type="button" onClick="setOnOff(event,'displayExtraProperties','off'); $('div.extra-properties-btn-container,div.service-number-outer').addClass('display-none');">Off</button>
	                            
                            <?php endif;?>
                            
                        </div></div>
                          
                       <div class="mainpage-content-right-inner-right-full">    
	                    	<div class="btn-group" data-toggle="buttons-checkbox">
	                    		<div class="extra-properties-btn-container <?php echo $this->data['displayExtraProperties']== 1 ? '' : 'display-none' ;  ?>">
		                            <button type="button" class="btn <?php echo $this->data['ideal']== 1 ? 'btn-primary' : '' ;  ?>" onClick="setOnOff(event,'ideal','toggle-btn');"><?php echo $this->translate('Ideal'); ?></button>                     
		                            <button type="button" class="btn <?php echo $this->data['qShops']== 1 ? 'btn-primary' : '' ;  ?>" onClick="setOnOff(event,'qShops','toggle-btn');"><?php echo $this->translate('Qshops'); ?></button> 	
		                            <button type="button" class="btn <?php echo $this->data['freeReturns']== 1 ? 'btn-primary' : '' ;  ?>" onClick="setOnOff(event,'freeReturns','toggle-btn');"><?php echo $this->translate('Free returns'); ?></button>                     
		                            <button type="button" class="btn <?php echo $this->data['pickupPoints']== 1 ? 'btn-primary' : '' ; ?>" onClick="setOnOff(event,'pickupPoints','toggle-btn');"><?php echo $this->translate('Many pickup points'); ?></button>                     
		                            <button type="button" class="btn <?php echo $this->data['mobileShop']== 1 ? 'btn-primary' : '' ;  ?>" onClick="setOnOff(event,'mobileShop','toggle-btn');"><?php echo $this->translate('Mobile shop'); ?></button>                     
		                            <button type="button" class="btn <?php echo $this->data['service']== 1 ? 'btn-primary' : '' ;  ?>" onClick="setOnOff(event,'service','toggle-btn'); $('#serviceNumberContainer').hasClass('display-none') ?  $('#serviceNumberContainer').removeClass('display-none') :  $('#serviceNumberContainer').addClass('display-none') ; "><?php echo $this->translate('Service');?></button>                     
	                        	</div>
							</div>
						</div>
                    </div>          
                </div>
                   <div class="service-number-outer <?php echo $this->data['displayExtraProperties']== 1 ? '' : 'display-none' ;  ?>">  
	                    <div class="mainpage-content-right <?php echo $this->data['service']== 1 ? '' : 'display-none' ;  ?>" id="serviceNumberContainer">
	                        <div class="mainpage-content-right-inner-right-other"></div>
	                        <div class="mainpage-content-right-inner-left-other">
	                        	<input type="text" class="span3"  maxlength="60" placeholder="Phone number" name="serviceNumber" value="<?php echo $this->data['service']== 1  ? $this->data['serviceNumber']: '' ; ?>">
	                        </div>
	                     </div>
                     </div>
                </div>
 
<!-- End New changes Extra Shop properties -->  
                 
            <div class="mainpage-content">
            	<div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><strong><?php echo $this->translate("Add a 'How to use the code'"); ?></strong></div>
                    <div class="mainpage-content-right">
                    	<div class="btn-group" data-toggle="buttons-checkbox">
                            
                            <?php 
                            
                            		if( $this->data['howToUse'] )
                            		{
                            			?>
                            			
											<button type="button" class="btn btn-primary" onClick="setOnOff(event,'howtouse','on');$('#howToUseContent').removeClass('display-none');"><?php echo $this->translate('Yes'); ?></button>                     
				                            <button type="button" class="btn  default" onClick="setOnOff(event,'howtouse','off');$('#howToUseContent').addClass('display-none')"><?php echo $this->translate('No'); ?></button>
                            			                            
                            	<?php } else { ?>
                            	
											<button type="button" class="btn" onClick="setOnOff(event,'howtouse','on');$('#howToUseContent').removeClass('display-none');"><?php echo $this->translate('Yes'); ?></button>                     
                            				<button type="button" class="btn btn-primary default" onClick="setOnOff(event,'howtouse','off');$('#howToUseContent').addClass('display-none')"><?php echo $this->translate('No'); ?></button>
                            	
                            	<?php }?>
                            	
                            
                          </div>
                    </div>          
                </div>
            </div>
            
            
            <div class="mainpage-content <?php echo ( $this->data['howToUse'] ) ? "" : "display-none"  ; ?>" id="howToUseContent">
            	<div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Upload main image lightbox'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                         <div class="mainpage-content-right-inner-right-other"></div>
                      		
                      		  <?php       
					
				                     	$smallLogo = PUBLIC_PATH.'images/upload/no.jpg';
									 			 
				                        if(isset( $this->data['howtousesmallimage']['name'] ) && $this->data['howtousesmallimage']['name'] != '' ) {
									  
				                        	 if( file_exists ( ROOT_PATH .  $this->data['howtousesmallimage']['path'] . $this->data['howtousesmallimage']['name'] )) {
				                        	 	
				                         		$smallLogo = PUBLIC_PATH_LOCALE .  $this->data['howtousesmallimage']['path']  .'thum_'. $this->data['howtousesmallimage']['name'] ;
				                         
				                         	}
				                      	}	
						  
                     		 ?>
                      		  
                      		<img alt="<?php echo $this->translate('main image'); ?>" src="<?php echo $smallLogo ; ?>">
                      		<div style="margin-right: 0px;" class="mainpage-content-right-inner-left-other">
                      		   
                      		   <br>
                    	       <input data-max-size="2097152" onchange="checkFileType(event)" type="file" class="input-file ignore"  name="smallLogoFile"/>
		                       <span class="ml15 help-inline" style="display: inline-block; padding-bottom: 5px;"><?php echo $this->translate('Upload .jpg or .png file only (Maximum file size: 2MB,width:300px)'); ?></span>
                       		</div>
                    </div>   
                </div>
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label style="padding:0 14px 0 0;"><strong><?php echo $this->translate('Upload second image lightbox'); ?></strong></label></div>
	                    <div class="mainpage-content-right">
	                        <div class="mainpage-content-right-inner-right-other"></div>
	                    	<?php       
					
				                     	$bigLogo = PUBLIC_PATH.'images/upload/no.jpg';
									 			 
				                        if(isset( $this->data['howtousebigimage']['name'] ) && $this->data['howtousebigimage']['name'] != '' ) {
									  
				                        	 if( file_exists ( ROOT_PATH .  $this->data['howtousebigimage']['path'] . $this->data['howtousebigimage']['name'] )) {
				                        	 	
				                         		$bigLogo = PUBLIC_PATH_LOCALE .  $this->data['howtousebigimage']['path']  .'thum_'. $this->data['howtousebigimage']['name'] ;
				                         
				                         	}
				                      	}	
						  
                     		 ?>
	                    	<img alt="<?php echo $this->translate('second image'); ?>" src="<?php echo $bigLogo ; ?>">
	                    	<div style="margin-right: 0px;" class="mainpage-content-right-inner-left-other">
		                    	 <br>	
		                    	 <input data-max-size="2097152" onchange="checkFileType(event)" type="file" class="input-file ignore" name="bigLogoFile" >
		                     	 <span class="ml15 help-inline" style="display: inline-block; padding-bottom: 5px;"><?php echo $this->translate('Upload .jpg or .png file only (Maximum file size: 2MB,width:300px)'); ?></span>
	                   		</div>
                   </div>
                                       
                </div>
            	<div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Page title'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                    	<div class="mainpage-content-right-inner-left-other">
                    		<input type="text" name="pageTitle" id="pageTitle" class="span3" placeholder="<?php echo $this->translate('Page title'); ?>" value="<?php echo $this->data['howtoTitle'] ; ?>">
                    	</div>
                    </div>
                </div>
                        
                <div class="mainpage-content-line">
                     <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Page Subtitle'); ?></strong></label></div>
                     <div class="mainpage-content-right">
                     	<div class="mainpage-content-right-inner-left-other">
                     		<input type="text" name="pageSubTitle" id="pageSubTitle" class="span3" placeholder="<?php echo $this->translate('Page Subtitle'); ?>" value="<?php echo $this->data['howtoSubtitle'] ; ?>">
                     	</div>
                     </div>	
                </div>
                        
                <div class="mainpage-content-line">
                   	 <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Meta title'); ?></strong></label></div>
                     <div class="mainpage-content-right">
                     	<div class="mainpage-content-right-inner-left-other">
		                     <input type="text" name="pagemetaTitle" id="pagemetaTitle" placeholder="<?php echo $this->translate('Meta title');?>" class="input-xlarge mbot bbot ignore" value="<?php echo $this->data['howtoMetaTitle'] ; ?>"/>
							 <input type="text" disabled="disabled" value="<?php echo $this->translate("Shop meta title length "). strlen($this->data['howtoMetaTitle']) . $this->translate(' characters');?>" id="pagemetaTitleLeft" class="input-xlarge disabled btop word-count">
						</div>	 
					 </div>
                </div>
                <div class="mainpage-content-line">
                     <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Meta Description'); ?></strong></label></div>
                     <div class="mainpage-content-right">
                     	<div class="mainpage-content-right-inner-left-other">
		                     <textarea class="input-xlarge mbot bbot ignore" id="pagemetaDesc" name="pagemetaDesc" placeholder="<?php echo $this->translate ( 'Meta Description' );?>" rows="3"><?php echo $this->data['howtoMetaDescription'] ; ?></textarea>
							 <input type="text" disabled="disabled" value="<?php echo $this->translate("Shop page meta description length "). strlen($this->data['howtoMetaDescription']) . $this->translate(' characters');?>" id="pagemetaDescLeft" class="input-xlarge disabled btop word-count">
						</div>	 
					 </div>
                </div>
                <?php echo $howToIntroductionText; ?>

                <div class="mainpage-content">

							<div class="mainpage-content-line mb10">
								<div class="mainpage-content-left">
									<h3>
										<strong><?php echo $this->translate('Chapters'); ?></strong>
									</h3>
								</div>
								<div class="mainpage-content-right">&nbsp;</div>
							</div>
									
							<div id="multidiv" >   
	                	 		<?php echo $this->partialLoop('shop/chapters.phtml',$this->data['howtochapter']);?>
	                	 	</div>
							
							<div class="mainpage-content-colorbox">
								<a href="javascript:;" style="float:right;margin-top: 7px;" onclick="getchapterhtml(this)" rel='<?php echo count($this->data['howtochapter']);?>'><strong><?php echo $this->translate('+ Add another chapter'); ?></strong></a>
							</div>
							<div class="clear"></div>
		
	
				</div>             
            </div>
            
            <input type="hidden" name="shopId" id="shopId" value="<?php  echo $this->data['id']; ?>"/>
            
            <input type="hidden" name="accountManagerName" id="accountManagerName" value="<?php echo $this->data['accountManagerName'] ; ?>" />
            
            <input type="hidden" name="editorName" id="editorName" value="<?php echo $this->data['contentManagerName'] ; ?>" />
            <input type="hidden" name="offlineSince" id="offlineSince" value="<?php echo ( $this->data['status'] ) ? "" :  $this->data['offlineSicne'] ;?>" />
            <input type="hidden" name="onlineStatus" id="onlineStatus" value="<?php echo ( $this->data['status'] ) ?  1 : 0 ; ?>" />
            <input type="hidden" name="deepLinkStatus" id="deepLinkStatus" value="<?php echo ( $this->data['deepLinkStatus'] ) ?  1 : 0 ; ?>" />
            <input type="hidden" name="affiliateProgStatus" id="affiliateProgStatus" value="<?php echo ( $this->data['affliateProgram'] ) ?  1 : 0 ; ?>" />
            <input type="hidden" name="howTouseStatus" id="howTouseStatus" value="<?php echo ( $this->data['howToUse'] ) ?  1 : 0 ; ?>" />
            
            <!-- Extra shop hidden feilds -->
             <input type="hidden" name="displayExtraProperties" id="displayExtraProperties" value="<?php echo ( $this->data['displayExtraProperties'] ); ?>" />
             
            <input type="hidden" name="ideal" id="ideal" value="<?php echo ( $this->data['ideal'] ); ?>" />
            <input type="hidden" name="qShops" id="qShops" value="<?php echo ( $this->data['qShops'] ) ; ?>" />
            <input type="hidden" name="freeReturns" id="freeReturns" value="<?php echo ( $this->data['freeReturns'] ) ; ?>" />
            <input type="hidden" name="pickupPoints" id="pickupPoints" value="<?php echo ( $this->data['pickupPoints'] ) ; ?>" />
            <input type="hidden" name="mobileShop" id="mobileShop" value="<?php echo ( $this->data['mobileShop'] ) ; ?>" />
            <input type="hidden" name="service" id="service" value="<?php echo ( $this->data['service'] ) ; ?>" />
            
            <input type="hidden" name="signupOption" id="signupOption" value="<?php echo ( $this->data['showSignupOption'] ) ; ?>" />
		    <input type="hidden" name="showChains" id="showChains" value="<?php echo ( $this->data['showChains'] ) ; ?>" />
            <input type="hidden" name="strictConfirmation" id="strictConfirmation" value="<?php echo ( $this->data['strictConfirmation'] ) ; ?>" />
            
            <div class="mainpage-content-colorbox">

            	<button type="submit" class="btn btn-large btn-primary fl"><?php echo $this->translate('PUBLISH SHOP'); ?></button>
                <a class="fl m10" href="javascript:void(0);" onClick="window.location.href='<?php echo HTTP_PATH ;?>admin/shop<?php echo '#'.$this->qstring; ?>'"  ><strong><?php echo $this->translate('CANCEL'); ?></strong></a>
                <a class="fl red mt10" onclick="moveToTrash(<?php  echo $this->data['id']; ?>);" href="javascript:void(0);" id="deleteButton"><strong><?php echo $this->translate('DELETE')?></strong></a>
            </div>
            <!-- /poststuff -->
            </form>  <!-- End addUser form -->
        </div>  
      </div>
      </div>   
     <!-- Create shops End -->