<?php
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.dataTables.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/dataTableComman.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/select2.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
$this->headLink()->appendStylesheet(PUBLIC_PATH . "css/jquery-ui-1.8.16.custom.css");
$this->headLink()->appendStylesheet(PUBLIC_PATH . "css/select2.css");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/shop.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/jquery.validate.js");
$this->headScript()->prependFile(PUBLIC_PATH . "js/back_end/widget-location.js");
$sessionNamespace = new Zend_Session_Namespace();
?>

<?php echo $this->headTitle()->append('Shops List');?>
<div id="imbullbody-content" style="overflow: hidden;">
        <!-- Shops list start -->

      <div id="shopList">
       <div class="wrap columns-2">
		<div class='wrap columns-2'>
			<?php if($this->messageSuccess!='' || $this->messageError!='' ){?>

			<br>
			<div class ="mainpage-content-colorbox success">

			<?php if($this->messageSuccess!=''){?>

			<span class="successserver"><?php echo $this->messageSuccess; ?></span>
			<?php }?>

			<?php if($this->messageError!=''){?>

			<span class="errorserver"><?php echo $this->messageError; ?></span>
			<?php } ?>
			</div>
		<?php
		}?>
		</div>
        <h1 class="fl">Shops<button class="btn ml10" type="button" onClick="window.location.href='<?php echo HTTP_PATH ;?>admin/shop/createshop'" ><?php echo $this->translate('Add New Shop'); ?></button></h1><?php if($this->role == '1' || $this->role == '2')  { ?><a class="red trash-link" href="<?php echo HTTP_PATH ?>admin/shop/trash"><strong><?php echo $this->translate('Trash'); ?></strong></a><?php }?>
        <div class="clear"></div>
         <p class="text-right">
              <a href='javascript:void(0)' onclick="showLightBoxForWidgetLocation()">
                  <?php echo $this->translate('Set Widget Location')?>
              </a>  / 
              <a href="<?php echo HTTP_PATH ?>admin/shop/importshops">
                  <?php echo $this->translate('Import List'); ?></a> / 
              <a href="<?php echo HTTP_PATH ?>admin/shop/local-export-xlx">
                  <?php echo $this->translate('Local Export List'); ?>
              </a>
           <?php
            # make gloabl shop export only available for superadmins
         	if ( $sessionNamespace->settings['rights']['site']['rights'] == '1' ) : ?>
                   / <a href="javascript:void(0);" onclick='sendExportPasswordEmail();'><?php echo $this->translate('Global Export List'); ?></a>
          <?php endif;?>
         </p>

          <form class="well form-search searchbarbox" name="searchform" id="searchform">
              <div class="mainpage-content-searchbart">
                  <div class="mainpage-content-right-searchbar">
                    <button id="searchByShop" type="button" class="btn btn-primary">
                      <?php echo $this->translate('Search'); ?>
                    </button>
                  </div>
                    <div class="mainpage-content-right-inner-left-searchbar">
                        <input type='hidden' id="searchShop" name="searchShop" style="width:99%;"/>
                    </div>
              </div>
            </form>

            <table  class="table table-bordered table-striped" id="shopListTable" style="position:relative;">
                <thead>
                  <tr>
					<th style="display:none;"><?php echo $this->translate('Id'); ?></th>
                    <th> <?php echo $this->translate('Shop name'); ?></th>
                    <th> <?php echo $this->translate('PermaLink'); ?></th>
                    <th><?php echo $this->translate('Money Shop') ; ?></th>
                    <th class="th_shop_start"><?php echo $this->translate('Start'); ?></th>
                    <th><?php echo $this->translate('Clickouts last 7 days'); ?></th>
                    <th><?php echo $this->translate('All Clickouts'); ?></th>
                    <th><?php echo $this->translate('Network'); ?></th>
                    <th><?php echo $this->translate('Allow Discussion'); ?></th>
                    <th><?php echo $this->translate('Display SignUp'); ?></th>
                    <th><?php echo $this->translate('Online'); ?></th>
                    <th><?php echo $this->translate('Offline Since'); ?></th>
                    <th><?php echo $this->translate('Delete'); ?></th>

                  </tr>
                </thead>
            </table>
    </div>

      <!-- Shops list End -->
 </div>

<div class="modal display-none popup-width" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" 
    aria-hidden="true">
    <div class="wrap columns-2">
        <form name="globalExportForm" id="globalExportForm" method="post" 
            action="<?php echo HTTP_PATH ?>admin/shop/global-export-xlx">
            <div class="m-item-popup-hdr"><?php echo $this->translate('Global export password');?></div>
            <div id="poststuff" class="metabox-holder has-right-sidebar">
                <div id="post-body">
                    <div class="mainpage-content-line">
                        <span class="export-password-success"><?php echo $this->translate('Password successfully sent. Please check your email for the export list password.');?></span>
                        <div class="mainpage-content-left">
                            <label>
                                <strong><?php echo $this->translate('Password');?></strong>
                            </label>
                        </div>
                        <div class="mainpage-content-right-inner-right-other display-none"></div>
                        <div class="mainpage-content-right">
                            <input type="text" placeholder="Password.." class="span3" name="password" id="password">
                        </div>
                    </div> 
              </div>
              <br class="clear">
            </div>
            <div class="m-item-popup-btm">
                <input type="hidden" id="hidimageorg" name="hidimageorg">
                <button id="submitButton" class="btn btn-large btn-primary fl export-submit-btn" 
                    type="submit"><?php echo $this->translate('Submit');?></button> 
                <button class="btn ml10 m5" data-dismiss="modal"><?php echo $this->translate('Cancel');?></button>
            </div>
        </form>
    </div>
</div>
<?php echo $this->partial('widgetlocation/_widget-location.phtml', array('pageType' => 'shop', 'relatedId' => ''));?>