<?php 

$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.dataTables.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/dataTableComman.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/select2.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/jquery-ui-1.8.16.custom.css" );
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/select2.css" );
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/trashShop.js");
?>
<?php echo $this->headTitle()->append('Trashed Shops List');?>
<div id="imbullbody-content" style="overflow: hidden;">
        <!-- Shops list start -->
      <div id="shopList">
        <div class="wrap columns-2" >
		
			<?php if($this->messageSuccess!='' || $this->messageError!='' ){?>
		
			<br><div class ="mainpage-content-colorbox success">
		
			<?php if($this->messageSuccess!=''){?>
		
			<span class="successserver"><?php echo $this->messageSuccess; ?></span>
			<?php }?>
		
			<?php if($this->messageError!=''){?>
		
			<span class="errorserver"><?php echo $this->messageError; ?></span>
			<?php } ?>
		
		</div>
		<?php 
		}?>
		
        <h1 class="fl">Trashed Shops<button class="btn ml10" type="button" onClick="window.location.href='<?php echo HTTP_PATH ;?>admin/shop'" ><?php echo $this->translate('Cancel'); ?></button></h1>
        <div class="clear"></div>
         <form class="well form-search searchbarbox" name="searchform" id="searchform">
              <div class="mainpage-content-searchbart">
                    <div class="mainpage-content-right-searchbar">
	                    <button id="search-btn" type="button" class="btn btn-primary">
	                    <?php echo $this->translate('Search'); ?>
	                    </button>
                    </div>
                    <div class="mainpage-content-right-inner-left-searchbar">
                    	<input type='hidden' id="searchShop" name="searchShop" style="width:99%;"/>
                    </div>                        
              </div>
            </form>
            
            <table class="table table-bordered table-striped" id="shopListTable">
                <thead>
                  <tr>
		     <th><?php echo $this->translate('Id'); ?></th>
                    <th> <?php echo $this->translate('Shopname'); ?></th>
                    <th><?php echo $this->translate('Affiliate program') ; ?></th>
                    <th class="th_shop_start"><?php echo $this->translate('Start'); ?></th>
                    <th><?php echo $this->translate('Network'); ?></th>
                    
                    <!-- <th><?php //echo $this->translate('Online'); ?></th>
                    <th><?php //echo $this->translate('Offline since'); ?></th> -->
                    
                    <th><?php echo $this->translate('Restore'); ?></th>
                    <th><?php echo $this->translate('Delete permanently'); ?></th>

                  </tr>
                </thead>
            </table>
    </div>  
    </div>
      <!-- Shops list End -->
 </div>
 