<?php
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/login.js");

?>
<form name="forgotpwd" id="forgotpwd" action="" method="post"><div class="login-box-outer">
	<div class="login-logo">
    	<img src="<?php echo PUBLIC_PATH?>images/back_end/imbull-login-logo.jpg" border="0" />
    </div>
	<div class="login-box">
    	<div class="login-box-heading"><?php echo $this->translate('Forgot password?');?></div>
    	<span class='login-input error' id='error-msg'> 
    	<?php
	    	 echo $this->message;
	    	 	
	    ?>
    	</span>
    	
    	<div class="input-prepend login-input">
          <span class="add-on"><i class="icon-envelope"></i></span><input type="text" name="email" id="email" maxlength="254" placeholder="Username/E-mail Address">
        </div>
        <div class="button-outer">
        <button type="submit" name="button" id="button" class="btn btn-large btn-primary" ><?php echo $this->translate('REQUEST NEW PASSWORD');?></button>
         <a id='back' href="<?php echo HTTP_PATH?>admin/auth"><?php echo $this->translate('Back');?></a>
        </div>
    </div>
</div></form>