<div class='columns-2 wrap ml20'>
	<br>
	<div class ="mainpage-content-colorbox success">
			<?php if($this->messages!='' || $this->messageError!='' ){?>
				<?php if($this->messages!=''){?>
					<span class="successserver"><?php //print_r($this->messages); ?></span>
				<?php }?>
				<?php if($this->messageError!=''){?>
					<span class="errorserver"><?php echo $this->messageError; ?></span>
				<?php } ?>
		<?php } else { #password hijnt of first landing on this page ?>
			<span class="errorserver"><?php echo $this->translate("Please update your password. Example: P@ssw0rd"); ?></span>
		<?php }?>
	</div>
</div>
		
<form name="updatePassword" id="updatePassword"  method="post"><div class="login-box-outer">
	<div class="login-box">
    	<div class="login-box-heading"><?php echo $this->translate('Update password');?></div>
    	<div class="input-prepend login-input">
          <span class="add-on"><i class="icon-lock"></i></span><input type="password" name="curPassword" id="curPassword" maxlength="254" placeholder="Current Password">
        </div>
		<div class="input-prepend login-input">
          <span class="add-on"><i class="icon-lock"></i></span><input type="password" name="newPassword" id="newPassword" maxlength="254" placeholder="New password">
        </div>
		<div class="input-prepend login-input">
          <span class="add-on"><i class="icon-lock"></i></span><input type="password" name="confirmPassword" id="confirmPassword" maxlength="254" placeholder="Confirm new password">
        </div>
        <div class="button-outer">
        <button type="submit" name="button" id="button" class="btn btn-large btn-primary" ><?php echo $this->translate('Submit');?></button>
        </div>
    </div>
</div></form>