<div class="text-block">
    <div class="container">
        <form action="<?php echo HTTP_PATH_LOCALE. FrontEnd_Helper_viewHelper::__link('search'); ?>" role="form" class="email-form form-inline">
            <fieldset>
                <h1><?php echo $this->translate('Searching for Coupons?');?></h1>
                <h2><?php echo $this->translate("We&#39;ve got a lot of them :)");?></h2>
                <div class="holder search-outer">
                    <div class="form-group">
                         <input type="search" value="<?php echo $this->translate('What deal are you looking for?');?>"
                             onblur="if(this.value=='') this.value=this.defaultValue;" 
                             onfocus="if(this.value==this.defaultValue) this.value='';" 
                             id='searchField'  name='searchField' label='searchField' type="search"  class="form-control" />
                         <input type='hidden' name='searchHidden' label='searchHidden' id='searchHidden' />
                    </div>
                    <a href="javascript:void(0);">
                        <button id='searchbuttonHP' class="orange btn btn-default searchbutton"><span class="glyphicon glyphicon-search"></span><?php echo $this->translate('Find');?>
                        </button>
                    </a>
                </div>
            </fieldset>
        </form>
    </div>
</div>
