
        
        <!-- blog-overview -->
        <div class="blog-overview-lt">            
            <div class="blog-banner-box">            	
                <img src="<?php echo HTTP_PATH;?>public/images/front_end/blog-banner.png" />
            </div>
            <a class="blog-banner-arrow-left text-blue-link" href="#"><span class="arrow-left"></span><span class="arrow-text-left">Uncate.com - An AWESOME<br />website for guys</span></a>
<a class="blog-banner-arrow-right text-blue-link" href="#"><span class="arrow-right"></span><span class="arrow-text-right">Should have the Olympics in<br />Amsterdam for economic boost?</span></a>
          <div class="blog-detail-box">
            	<span class="font-mt">What car would you buy if you would be <br />given €100.000,-?</span>
            <div class="blog-black-strip ">6 augustus 2012, door Jochem</div>
            <p class="mt20 fl"><img class="fr" src="<?php echo HTTP_PATH;?>public/images/front_end/blog-detail-img.png" /><strong class="text-black">The Money Advice Service (MAS) is the official agency 
tasked with closing the advice and knowledge gaps people 
have about financial services. It also has a new role 
distributing public funds for debt advice to the various non-
profit debt counselling agencies.</strong><br /><br />
In June I was asked to give evidence to a Treasury Select Committee 
investigation on it. Having kept schtum for a long time, I (as well as 
others) frankly let rip, with some honestly-held, but strong criticisms of 
the way it has operated (details in MAS ‘letting rip’ evidence blog), 
especially its website. However, that has never stopped me being a 
supporter of the overall aims of the MAS.
</p>
            <p>&nbsp;</p>
<p>On the back of this, last week we had a meeting scheduled. As you can imagine, I was a little worried it’d be tricky – though since the evidence session the MAS website has been upgraded, and that’s a step in the right direction.</p>
<p>&nbsp;</p>

<p>I’m pleased to say we actually ended up having a really positive meeting, focusing on shared aims and brainstorming where there was room to work together or just support good work being done on important projects.  </p>
<p>&nbsp;</p>

<p>There are many challenges coming to the public’s pockets, not least the knee-trembling thought of massive changes to benefits being brought on by Universal Credit. It will be a seismic challenge to help people even understand the basics, and it’s one I think that fills all of us with trepidation.</p>
<p>&nbsp;</p>
<p>We already have a benefits calculator on the site and are currently working on improving it to make it easier to use. The MAS is planning an education role on the same issues. These are huge projects for both of us, so on a cursory level we thought some co-ordination and cross-linking so there’s less duplication should leave a greater variety of tools and help for people trying to sort out what it means for them.</p>
<p>&nbsp;</p>

<p>We also chatted through a host of other subjects that need tackling and are under-covered, from auto-enrolment in pensions to equity release and income protection issues, and how best to communicate those complex decision trees.  </p>
<p>&nbsp;</p>

<p>And finally, there’s the more obvious case of financial education – part of the MAS’s remit and something MSE and I have been campaigning on for many years. We already both work with the charity Pfeg and hopefully there’ll be more shared aims there going forward too.</p>
<p>&nbsp;</p>

<p> As the end of the meeting, everyone had a much larger list of things to talk about when we left than when we arrived – that has to be a good sign. </p>

<span class="mt15 fl"><img src="<?php echo HTTP_PATH;?>public/images/front_end/fb-comments.jpg" /></span>
            </div>
            
            
            <div class="blog-detail-box mt20">
            	<span class="font-mt">What car would you buy if you would be <br />given €100.000,-?</span>
            <div class="blog-black-strip ">6 augustus 2012, door Jochem</div>
            <p class="mt20 fl"><img class="fr" src="<?php echo HTTP_PATH;?>public/images/front_end/blog-detail-img.png" /><strong class="text-black">The Money Advice Service (MAS) is the official agency 
tasked with closing the advice and knowledge gaps people 
have about financial services. It also has a new role 
distributing public funds for debt advice to the various non-
profit debt counselling agencies.</strong><br /><br />
In June I was asked to give evidence to a Treasury Select Committee 
investigation on it. Having kept schtum for a long time, I (as well as 
others) frankly let rip, with some honestly-held, but strong criticisms of 
the way it has operated (details in MAS ‘letting rip’ evidence blog), 
especially its website. However, that has never stopped me being a 
supporter of the overall aims of the MAS.
</p>
            <p>&nbsp;</p>
<p>On the back of this, last week we had a meeting scheduled. As you can imagine, I was a little worried it’d be tricky – though since the evidence session the MAS website has been upgraded, and that’s a step in the right direction.</p>
<p>&nbsp;</p>

<p>I’m pleased to say we actually ended up having a really positive meeting, focusing on shared aims and brainstorming where there was room to work together or just support good work being done on important projects.  </p>
<p>&nbsp;</p>

<p>There are many challenges coming to the public’s pockets, not least the knee-trembling thought of massive changes to benefits being brought on by Universal Credit. It will be a seismic challenge to help people even understand the basics, and it’s one I think that fills all of us with trepidation.</p>
<p>&nbsp;</p>
<p>We already have a benefits calculator on the site and are currently working on improving it to make it easier to use. The MAS is planning an education role on the same issues. These are huge projects for both of us, so on a cursory level we thought some co-ordination and cross-linking so there’s less duplication should leave a greater variety of tools and help for people trying to sort out what it means for them.</p>
<p>&nbsp;</p>

<p>We also chatted through a host of other subjects that need tackling and are under-covered, from auto-enrolment in pensions to equity release and income protection issues, and how best to communicate those complex decision trees.  </p>
<p>&nbsp;</p>

<p>And finally, there’s the more obvious case of financial education – part of the MAS’s remit and something MSE and I have been campaigning on for many years. We already both work with the charity Pfeg and hopefully there’ll be more shared aims there going forward too.</p>
<p>&nbsp;</p>

<p> As the end of the meeting, everyone had a much larger list of things to talk about when we left than when we arrived – that has to be a good sign. </p>

<span class="mt15 fl"><img src="<?php echo HTTP_PATH;?>public/images/front_end/fb-comments.jpg" /></span>
            </div>
            
        </div> 
        <div class="blog-right">
   	      <h3 class="bolg-heading"><strong>Recent Blog Posts</strong></h3>
            <div class="recent-blog">
              <div class="recent-blog-img"><img align="middle" src="<?php echo HTTP_PATH;?>public/images/front_end/blog-sidebar-img1.jpg"></div>            
                <div class="recent-blog-text">
                    <h5 class="text-blue">What car would you buy if you would be given €100.000,-?</h5>
                 </div>  
            </div>
            <div class="recent-blog">
                <div class="recent-blog-img"><img align="middle" src="<?php echo HTTP_PATH;?>public/images/front_end/blog-sidebar-img2.jpg"></div>            
                <div class="recent-blog-text">
                    <h5 class="text-blue">Top 10 things that annoy me in everyday life</h5>
                 </div>          
            </div>
            <div class="recent-blog">
                <div class="recent-blog-img"><img align="middle" src="<?php echo HTTP_PATH;?>public/images/front_end/blog-sidebar-img1.jpg"></div>            
                <div class="recent-blog-text">
                    <h5 class="text-blue">What car would you buy if you would be given €100.000,-?</h5>
                 </div>  
            </div>
            <div class="recent-blog">
                <div class="recent-blog-img"><img align="middle" src="<?php echo HTTP_PATH;?>public/images/front_end/blog-sidebar-img2.jpg"></div>            
                <div class="recent-blog-text">
                    <h5 class="text-blue">Top 10 things that annoy me in everyday life</h5>
                 </div>          
            </div>
            <div class="recent-blog">
                <div class="recent-blog-img"><img align="middle" src="<?php echo HTTP_PATH;?>public/images/front_end/blog-sidebar-img1.jpg"></div>            
                <div class="recent-blog-text">
                    <h5 class="text-blue">What car would you buy if you would be given €100.000,-?</h5>
                 </div>  
            </div>
            <div class="recent-blog">
                <div class="recent-blog-img"><img align="middle" src="<?php echo HTTP_PATH;?>public/images/front_end/blog-sidebar-img2.jpg"></div>            
                <div class="recent-blog-text">
                    <h5 class="text-blue">Top 10 things that annoy me in everyday life</h5>
                 </div>          
            </div><div class="recent-blog">
                <div class="recent-blog-img"><img align="middle" src="<?php echo HTTP_PATH;?>public/images/front_end/blog-sidebar-img1.jpg"></div>            
                <div class="recent-blog-text">
                    <h5 class="text-blue">What car would you buy if you would be given €100.000,-?</h5>
                 </div>  
            </div>
            <div class="recent-blog">
                <div class="recent-blog-img"><img align="middle" src="<?php echo HTTP_PATH;?>public/images/front_end/blog-sidebar-img2.jpg"></div>            
                <div class="recent-blog-text">
                    <h5 class="text-blue">Top 10 things that annoy me in everyday life</h5>
                 </div>          
            </div>
            
            <span class="fr mt10">Search Through <a href="javascript:;" class="text-blue-link">All Posts</a></span>
            <!-- blog-overview Ends -->
           
         </div>