<?php
$this->minifyHeadScript()->appendFile("/public/js/front_end/home.js");
$this->minifyHeadScript()->appendFile("/public/js/front_end/search.js");
//echo "<pre>";
//print_r($this->topCategoriesOffers); die;
$homePageTopNewOffersCategoriesAndSpecialGuidesData = array(
    'topOffers'=>$this->topOffers,
    'newOffers'=>$this->newOffers,
    'topCategories'=>$this->topCategories,
    'topCategoriesOffers'=>$this->topCategoriesOffers,
    'specialPages'=>$this->specialListPages,
    'specialPagesOffers'=>$this->specialPagesOffers,
    'moneySavingGuides'=>$this->moneySavingGuides
);

$indexViewPath = 'index/';
$topStore = '';
if(!empty($this->topStores)):
    $topStore = $this->partial(
        $indexViewPath. '_popularShops.phtml',
        array(
           'topStores' => $this->topStores,
        )
    );
endif;

$seein = '';
if(!empty($this->seeninContents)):
    $seein = $this->partial(
        $indexViewPath.'_seeinContents.phtml',
        array(
           'seeninContents' => $this->seeninContents,
        )
    );
endif;

$aboutTabs = '';
if(!empty($this->aboutTabs)):
    $aboutTabs = $this->partial(
        $indexViewPath.'_aboutTabs.phtml',
        array(
           'aboutTabs' => $this->aboutTabs,
        )
    );
endif;

$top9Stores = array_slice($this->topStores, 0, 9);
$top9StoresContents = '';
if(!empty($this->topStores)):
    $top9StoresContents = $this->partial(
        $indexViewPath.'_top9Stores.phtml',
        array(
            'top9Stores' => $top9Stores,
        )
    );
endif;
echo $top9StoresContents;
?>
<main role="main" id="main">
<div class="container best-items">
    <header class="heading">
        <h1><?php echo $this->translate('The Best of Flipit'); ?></h1>
    </header>
    <div class="columns">
    <?php
    $homePagePartial = new FrontEnd_Helper_HomePagePartialFunctions(); 
    echo $homePagePartial->getHomePageLeftColumn($homePageTopNewOffersCategoriesAndSpecialGuidesData);
    echo $homePagePartial->getHomePageRightColumnOffersList();
    ?>
    </div>
</div>
<?php echo $topStore.$seein.$aboutTabs;?>
</main>
<?php
