<?php 
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.dataTables.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/dataTableComman.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/usergeneratedoffer.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/select2.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/jquery-ui-1.8.16.custom.css" );

$role =  Zend_Auth::getInstance()->getIdentity()->users->id;
?>
<?php echo $this->headTitle()->append('User Generated Offers List');?>     
<div id="offerList">
    <div class="wrap columns-2">
        <div class='wrap columns-2'>
        <?php 
        if($this->messageSuccess!='' || $this->messageError!='' ) {
            ?>
            <br>
            <div class ="mainpage-content-colorbox success">
                <?php 
                if($this->messageSuccess!='') {
                    ?>
                    <span class="successserver"><?php echo $this->messageSuccess; ?></span>
                    <?php 
                }?>
                <?php 
                if($this->messageError!='') {
                    ?>
                    <span class="errorserver"><?php echo $this->messageError; ?></span>
                    <?php 
                } 
                ?>
            </div>
            <?php
        }?>
        </div>
        <h1 class="fl"><?php echo $this->translate('Social Offers')?></h1>
        <div class="clear"></div>
        <div class="mainpage-content-colorbox">
            <form class="form-search" id="searchform">

                <div class="mainpage-content-searchbart">
                    <div class="mainpage-content-right-searchbar-offer">
                        <button type='button' onClick='searchByShop();' 
                        id='searchShopeButton' value='searchShopeButton' 
                        class="btn btn-primary"><?php echo $this->translate('Search');?>
                        </button>
                    </div>
                    <div class="resetSearch mg-left mainpage-content-right-inner-right-searchbar-other">
                      <input type="hidden" class="span3" id="searchShop" 
                      name="searchShop">
                    </div>
                    <div class="resetSearch mainpage-content-right-inner-right-searchbar-other">
                      <input type="hidden" class="span3" id="searchCoupon" 
                      name="searchCoupon">
                    </div>
                </div>
            </form>
        </div>
        <table class="table table-bordered table-striped" id="offerListTable">
            <thead>
                <tr>
                    <th><?php echo $this->translate('Shop');?></th>
                    <th><?php echo $this->translate('Coupon Code');?></th>
                    <th><?php echo $this->translate('Start');?></th>
                    <th><?php echo $this->translate('End');?></th>
                    <th><?php echo $this->translate('Delete');?></th>
                </tr>
            </thead>
        </table>
    </div>
</div>
