<form name="campainForm" method="post" action='/admin/emailcampain/save' id='campainForm' enctype="multipart/form-data">
    <input type="hidden" name='id' id='id' value="<?php echo $this->campain['id']; ?>" />
    <div id="poststuff" class="metabox-holder has-right-sidebar">
        <div id="post-body">
            <div class="mainpage-content">

                <div class="mainpage-content-line">
                    <div class="mainpage-content-left">
                        <label><strong><?php echo $this->translate('Email address sender'); ?></strong></label>
                    </div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                            <input type="email" value="<?php echo $this->campain['sender'];?>" name="sender" id="sender" class="span3">
                        </div>                        
                    </div>
                </div>

                <div class="mainpage-content-line">
                    <div class="mainpage-content-left">
                        <label><strong><?php echo $this->translate('Subject'); ?></strong></label>
                    </div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                            <input type="text" value="<?php echo $this->campain['subject'];?>" name="subject" id="subject" class="span3">
                        </div>                        
                    </div>
                </div>
                
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left">
                        <label><strong><?php echo $this->translate('Subject'); ?></strong></label>
                    </div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div class="mainpage-content-right-inner-left-other">
                            <input type="text" value="<?php echo $this->campain['subject'];?>" name="subject" id="subject" class="span3">
                        </div>                        
                    </div>
                </div>

            </div>
            <div class="mainpage-content-colorbox">
                <button type="submit" class="btn btn-large btn-primary fl"><?php echo $this->translate('Save Campain'); ?></button>
                <a href="javascript:void(0);" class="fl m10 cancelButton"><strong>CANCEL</strong></a>
            </div>
        </div>

    </div>

</form>