<?php
    $this->headTitle()->append($this->translate('Category Offers'));
    $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
    $this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
    $this->headLink()->appendStylesheet(PUBLIC_PATH . "css/jquery-ui-1.8.16.custom.css");
    $this->headLink()->appendStylesheet(PUBLIC_PATH . "css/back_end/bootstrap-combobox.css");
    $this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/select2.min.js");
    $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/category_offers.js");
?>
<div class="wrap columns-2">
    <h1>
        <?php echo $this->translate('Category offers'); ?>
    </h1>
    <div class='mb10'> 
        <select  style="display: none; width : 389px;" class="combobox" name="categorylist" id="categorylist">
        <?php
        foreach ($this->homePageCategoriesList as $homePageCategory) { 
            if($homePageCategory['category']['id'] == $this->categoryId) {
                ?>
                <option  selected='selected' 
                value="<?php echo $homePageCategory['category']['id']; ?>"><?php echo $homePageCategory['category']['name']; ?>
                </option>
                <?php
            } else {
                ?>
                <option  value="<?php echo $homePageCategory['category']['id']; ?>"><?php echo $homePageCategory['category']['name']; ?></option>
                <?php
            }
         }?>
        </select>
    </div>
    <input type="hidden" name="selctedCategoryId" id="selctedCategoryId" value="<?php echo $this->categoryId; ?>">
    <div id="poststuff" class="metabox-holder has-right-sidebar">
        <div id="side-info-column" class="inner-sidebar-coupon">
            <div id="side-sortables" class="meta-box-sortables ui-sortable">
                <div class="coupon-sidebar-outer">
                    <div class="coupon-sidebar-heading">
                        <select  style="display: none; width : 389px;" class="combobox" name="offerlist" id="offerlist">
                            <option value=""></option>
                            <?php
                            foreach ($this->categoryOffers as $categoryOffer) { 
                                if (trim ($categoryOffer['title'] ) != '') {
                                    $offer = substr ($categoryOffer['title'], 0, 70 );
                                    ?>
                                    <option  value="<?php echo $categoryOffer['id']; ?>"><?php echo $offer; ?></option>
                                    <?php 
                                }
                            }
                            ?>
                        </select> 
                        <input type="hidden" name="selctedOffer" id="selctedOffer" value="">
                        <input type="hidden" name="selctedOfferText" id="selctedOfferText" value="">
                        <input type='hidden' name="SearchedValueIds" id="SearchedValueIds" value="">
                    </div>
                    <div class="coupon-sidebar-content-box">
                        <button id='addNewOffer' onClick='addNewOffer();'class="btn">
                        <?php echo $this->translate('ADD NEW OFFER');?>
                        </button>
                    </div>
                    <div class="coupon-sidebar-content-box mb10 image-loading-icon">
                        <button id='deleteOne' onClick='deleteOne();' class="btn">
                        <?php echo $this->translate("DELETE");?>
                        </button>
                    </div>                    
                </div>
            </div>
        </div>
        <div id="post-body">
            <div id="post-body-content-coupon">
                <div class="top-coupon-list">
                    <ul id='category'>
                    <?php 
                    if (!empty($this->currentCategoryHomePageOffers)) {
                        $date = new DateTime();
                        foreach ($this->currentCategoryHomePageOffers as $categoryOffer) {
                            $expired = '';
                            if($date > $categoryOffer['offers']['endDate']) {
                                $expired = "<i class='pull-right icon icon-time'></i></li>";
                            }
                            echo  "<li class='ui-state-default'  id='".$categoryOffer['id']."' 
                            reloffer='".$categoryOffer['offers']['id']."'
                            relpos='".$categoryOffer['position']."'>
                            <span>".$categoryOffer['offers']['title']."</span>".$expired."</li>";
                        }
                    } else {             
                        echo  "<li id='0'>". $this->translate('No record found !') ."</li>";
                    } ?>
                    </ul>
                </div>
            </div>
        </div>
        <br class="clear">
    </div>
</div>
