<?php
    $this->headTitle()->append($this->translate('Most Popular Articles'));
    $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
    $this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
    $this->headLink()->appendStylesheet(PUBLIC_PATH . "css/jquery-ui-1.8.16.custom.css");
    $this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/back_end/bootstrap-combobox.css" );
    $this->headScript ()->appendFile ( PUBLIC_PATH . "js/back_end/select2.min.js" );
    $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/popularArticles.js");
?>
<div class="wrap columns-2">
    <h1>
        <?php echo $this->translate('Most Popular Articles'); ?>
    </h1>            
    <div id="poststuff" class="metabox-holder has-right-sidebar">
        <div id="post-body">
            <div id="post-body-content-coupon">
                <div class="top-coupon-list">
                    <ul id='popularArticles'>
                    <?php 
                    if (!empty($this->articles)) { 
                        foreach ($this->articles as $articles) {
                        echo  "<li class='ui-state-default' id='".$articles['articleId']."'>
                            <span>".$articles['title']."</span></li>";
                        }
                    } else {             
                        echo  "<li id='0'>". $this->translate('No record found !') . "</li>";
                    } ?>
                    </ul>
                </div>
            </div>
        </div>
        <br class="clear">
    </div>
</div>
