<?php 
$I = new AcceptanceTester($scenario);
$I = new AcceptanceTester\LoginSteps($scenario);
$I->login();
$I->selectOption('.websites-access-list select', 'flipit.com/in');
$I->canSee('Offers');
$I->click('Offers');
$I->canSee('Create Offers');
$I->click('Create Offers');
$I->amOnPage('/admin/offer/addoffer');
$I->click('.select2-choice span');
$I->fillField('.select2-search input', 'acceptance shop');
$I->click('.select2-results .select2-result');
$I->fillField('#couponCodeTxt', 'acceptance code');
$I->wait(5);
$I->click('#offertileimg');
$I->wait(5);
$I->fillField('#addofferTitle', 'acceptance expired code');
$I->wait(5);
$I->executeJS('return document.getElementById(\'offerStartDate\').value="10-08-2014"');
$I->executeJS('return document.getElementById(\'offerEndDate\').value="11-08-2014"');
$I->wait(5);
$I->click('#addOfferBtn');
$I->amOnPage('/admin/offer');
