<?php echo FrontEnd_Helper_viewHelper::__email('Beste Kortingscode.nl bezoeker') ?>,<br><br>
 
<?php echo FrontEnd_Helper_viewHelper::__email('Je ontvang deze e-mail omdat je hebt aangeven om op de hoogte te blijven van de beste kortingscodes en acties van Kortingscode.nl.'); ?><br><br>

<?php echo FrontEnd_Helper_viewHelper::__email('Met de volgende stap bevestig je dat je deze e-mail hebt ontvangen, klik daarvoor op onderstaande link:')?><br>
<a href='<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('inschrijven').'/'.FrontEnd_Helper_viewHelper::__link('stap3').'/'. base64_encode($this->email);?>'><?php FrontEnd_Helper_viewHelper::__email('Klik hier om je e-mail adres te bevestigen')?></a><br><br>

<?php echo FrontEnd_Helper_viewHelper::__email('Alvast bedankt')?>,<br><br>

<?php echo FrontEnd_Helper_viewHelper::__email('Kortingscode.nl')?><br><br>

<span style='font-size: 9px;'><?php echo FrontEnd_Helper_viewHelper::__email('Kortingscode.nl is een onderdeel van Imbull, Weteringschans 120, 1017XT Amsterdam - KvK# 34339618'); ?></span>
