<main role="main" id="main" class="container">
			<section class="register-box">
				<form action="#">
					<fieldset>
						<div class="row">
							<div class="col-md-6">
								<div class="image">
									<img src="<?php echo PUBLIC_PATH;?>images/img-36.png" alt="image description" width="462" height="263" />
									<div class="text">Flipit! Get ready to flip over a great deal!</div>
								</div>
							</div>
							<div class="col-md-6">
								<div class="row">
									<div class="col-sm-6">
										<div class="form-group">
											<label for="text1">Email:</label>
											<input type="text" id="text1" class="form-control" />
										</div>
									</div>
									<div class="col-sm-6">
										<div class="form-group">
											<label for="text4">Password</label>
											<input type="password" id="text4" class="form-control" />
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-sm-6">
										<div class="form-group">
											<label for="text2">First name</label>
											<input type="text" id="text2" class="form-control" />
										</div>
									</div>
									<div class="col-sm-6">
										<div class="form-group">
											<label for="text5">Last name</label>
											<input type="text" id="text5" class="form-control" />
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-sm-6">
										<div class="form-group">
											<label for="text3">Date of birth</label>
											<div class="row">
												<div class="col-xs-4">
													<input type="text" id="text3" class="form-control" />
												</div>
												<div class="col-xs-4">
													<input type="text" class="form-control" />
												</div>
												<div class="col-xs-4">
													<input type="text" class="form-control" />
												</div>
											</div>
										</div>
									</div>
									<div class="col-sm-6">
										<div class="form-group">
											<label for="text6">Gender</label>
											<select id="text6" class="form-control">
												<option>Female</option>
												<option>Male</option>
											</select>
										</div>
									</div>
								</div>
								<div class="form-group alt">
									<button class="btn blue btn-lg btn-primary" type="submit">Create account</button>
								</div>
							</div>
						</div>
					</fieldset>
				</form>
			</section>
		</main>