 <?php
 $this->minifyHeadScript()->prependFile ( HTTP_PATH."public/js/front_end/step3.js" ); 
 $title = $this->emailStepStatus==true ? 'Stap 3 van 4' : 'Stap 2 van 3';
 $this->headTitle()->append($this->translate($title)); 
 ?>
<div class='new-outer'>
<div class="new-signup-outer-round mt40">
    	<div class="new-sigup-nav">
        	<ul>
            	<?php if($this->emailStepStatus):?>
            	
            	<li class="step1">1. <?php echo $this->translate('E-mailadres')?></li> 
                <li class="step2">2. <?php echo $this->translate('Bevestiging e-mailadres')?></li>
                <li class="step3 sltd">3. <?php echo $this->translate('Vertel ons wie je bent')?></li> 
                <li class="step4">4. <?php echo $this->translate('Je bent nu klaar om te beginnen')?></li>
                 
          		<?php else: ?>
          		
          		<li class="step1 liWidth">1. <?php echo $this->translate('E-mailadres')?></li> 
    			<li class="step3 liWidth sltd">2. <?php echo $this->translate('Vertel ons wie je bent')?></li> 
                <li class="step4 last-li-width">3. <?php echo $this->translate('Je bent nu klaar om te beginnen')?></li>
                 
            	<?php endif;?> 
            </ul>
        </div>
        <div class="step3_outer">
        	<h2>
            	<?php echo $this->translate('Voer je gegevens in zodat wij jou de beste en meest relevante kortingscodes kunnen aanbieden.')?>
            </h2>
            
            <!--Form Outer-->
            <div class="step3_form">
            	<form id="stepThreeForm" action="<?php echo HTTP_PATH_LOCALE .FrontEnd_Helper_viewHelper::__link('inschrijven') .'/'. FrontEnd_Helper_viewHelper::__link('compleet')?>?rnd=<?php echo rand(0,99999999999); ?>" method='POST'>
	                <!--Row-->
	                <div class="step3_form_row">
	                	<div class="f-txt"><?php echo $this->translate('Voornaam:')?></div>
	                    <div class="form-rt">
	                    	<input type="text" value="" class="f-input321" name="firstName" id="firstName"/>
	                    </div>
	                    
	                </div>
	                <!--//Row-->
	                
	                 <!--Row-->
	                <div class="step3_form_row">
	                	<div class="f-txt"><?php echo $this->translate('Achternaam:')?></div>
	                    <div class="form-rt">
	                    	<input type="text" value="" class="f-input321" name="lastName" id="lastName"/>
	                    </div>
	                    
	                </div>
	                <!--//Row-->
	                
	                 <!--Row-->
	                <div class="step3_form_row">
	                	<div class="f-txt" style="line-height:20px;"><?php echo $this->translate('Geslacht:')?></div>
	                    <div class="form-rt">
	                    	<input type="radio" name="gender" class='gender' value="female"/> <?php echo $this->translate('Vrouw')?> <br />
	                        <input type="radio" name="gender" class='gender' checked="checked" value="male"/> <?php echo $this->translate('Man')?> <br />
	                        <div class='validationPlacementGender'></div>
	                    </div>
	                   
	                </div>
	                <!--//Row-->
	                
	                 <!--Row-->
	                <div class="step3_form_row">
	                	<div class="f-txt"><?php echo $this->translate('Geboortedatum:')?></div>
	                    <div class="form-rt">
	                    	<select class="select-95 comboBox" name="birthDay" id="birthDay">
	                        	<option value=''><?php echo $this->translate('Dag')?></option>
	                        	<?php for($i=1; $i<32; $i++) :?>
			                          	<option value='<?php echo $i;?>' ><?php echo $i;?></option>
		                        <?php endfor; ?>
	                        </select>
	                        
	                        <select class="select-95 comboBox" name="birthMonth" id="birthMonth">
	                        	<option value=''><?php echo $this->translate('Maand')?></option>
	                        	<?php for($j=1; $j<13; $j++) :?>
			                           	<option value='<?php echo $j < 10 ? '0'.$j : $j;?>' ><?php echo $j < 10 ? '0'.$j : $j;?></option>
		                        <?php endfor; ?>
	                        </select>
	                        
	                        
	                         <select class="select-95 comboBox" name="birthYear" id="birthYear" >
	                        	<option value=''><?php echo $this->translate('Jaar')?></option>
	                        	<?php 
				                       $year = date("Y");
				                        	
										for ($k = $year; $k >= $year-100; $k--) :
											
								?>		
											<option value='<?php echo $k;?>' <?php echo $this->step2['years'] == $k ? 'selected = selected' : '';?>><?php echo $k;?></option>
								<?php 	
											  
										endfor;
								?>
	                        </select>
	                        <div class='validationPlacement'></div>
	                    </div>
	                    
	                   
	                </div>
	                <!--//Row-->
	                
	                <!--Row--><?php /*
	                <div class="step3_form_row">
	                	<div class="f-txt"><?php echo $this->translate('Postcode')?>:</div>
	                    <div class="form-rt-small">
	                    	<input type="text" value="" class="f-input211"  name="postCode" id="postCode"/>
	                    </div>
	                </div> */?>
	                <!--//Row-->
	                
	                
	                 <!--Row-->
	                <div class="step3_form_row">
	                	<div class="f-txt"><?php echo $this->translate('Gebruikersnaam')?>:</div>
	                    <div class="form-rt">
	                    	<span><?php echo base64_decode($this->email);?></span>
	                    	<input type='hidden' name='emailAddress' value="<?php echo $this->email?>" />
	                    </div>
	                    
	                </div>
	                <!--//Row-->
	                
	                
	                <!--Row-->
	                <div class="step3_form_row">
	                	<div class="f-txt"><?php echo $this->translate('Wachtwoord')?>:</div>
	                    <div class="form-rt-small">
	                    	<input value="" class="f-input211" type="password" name="password" id="password"/>
	                    </div>
	                   
	                </div>
	                <!--//Row-->
	                
	                <!--Row-->
	                <div class="step3_form_row">
	                	<div class="f-txt"><?php echo $this->translate('Bevestig Wachtwoord')?>:</div>
	                    <div class="form-rt-small">
	                    	<input value="" class="f-input211" type="password" name="confirmPassword" id="confirmPassword"/>
	                    </div>
	                   
	                </div>
	                <!--//Row-->
	               
	                 <!--Row-->
	                <div class="step3_form_row">
	                	<div class="f-txt"></div>
	                    <div class="form-rt">
	                    	<div class="yellow_btn">
	                        	<input type='submit' name='submitStepThree' value='<?php echo $this->translate('bevestig')?>' />
	                        </div>
	                    </div>
	                </div>
	                <!--//Row-->
            	</form>
            </div>
             <!--//Form Outer-->
        </div>
        
        
    </div>
</div>    