<?php

$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.dataTables.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/dataTableComman.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/emails.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/select2.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/jquery-ui-1.8.16.custom.css" );
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/select2.css" );

?>

     <?php echo $this->headTitle()->append('Emails');?>
      <!-- emailsList starts -->
       <div id="offerList">
        <div class="wrap columns-2">

        <div class='wrap columns-2'>
		<?php if($this->messageSuccess!='' || $this->messageError!='' ){?>
		<br><div class ="mainpage-content-colorbox success">
		<?php if($this->messageSuccess!=''){?>
		<span class="successserver"><?php echo $this->messageSuccess; ?></span>
		<?php }?>
		<?php if($this->messageError!=''){?>
		<span class="errorserver"><?php echo $this->messageError; ?></span>
		<?php } ?>
		</div>
		<?php
		}?>
		</div>
         <h1 class="fl"><?php echo $this->translate('Emails')?> </h1>
        
            <table class="table table-bordered table-striped" id="emailsListTable">
                <thead>
                  <tr>
                    <th><?php echo $this->translate('Name');?></th>
                    <th><?php echo $this->translate('Last Send Date');?></th>
                    <th><?php echo $this->translate('Number of emails send');?></th>
                  </tr>
                </thead>
             </table>
       </div>
       <!-- emailsList ends -->
	</div>
