 <?php 
	 $this->headTitle()->append($this->translate('Newsticker List'));
 
	$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.dataTables.min.js");
	$this->headScript()->appendFile(PUBLIC_PATH . "/js/dataTableComman.js");
	$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
	$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
	$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/jquery-ui-1.8.16.custom.css" );
	$this->headScript()->appendFile ( PUBLIC_PATH . "js/back_end/newsticker-list.js" );
?>

  <div id="newstickerList">
			<div class='wrap columns-2'>
			
			<?php if($this->messageSuccess!='' || $this->messageError!='' ){?>
			<br><div class ="mainpage-content-colorbox success">
			<?php if($this->messageSuccess!=''){?>
			<span class="success"><?php echo $this->messageSuccess; ?></span>
			<?php }?>
			<?php if($this->messageError!=''){?>
			<span class="error"><?php echo $this->messageError; ?></span>
			<?php } ?>
			</div>
			<?php 
			}?> 
			
		<h1><?php echo $this->translate('Newsticker');?>
	         
	          	<button  onClick="window.location.href='<?php echo HTTP_PATH ?>admin/newsticker/createnewsticker'" class="btn ml10" id="">
	          		<?php echo $this->translate('Add New Newsticker');?>
	          	</button>
        </h1>
        <div class="clear"></div>
        <p class="text-right">
            <a href='<?php echo HTTP_PATH ?>admin/newsticker/exportxlx'>
                <?php echo $this->translate('Export List'); ?>
            </a>
        </p>
          
          <!--<form class="well form-search searchbarbox"  name="searchform" id="searchform">
              	<div class="mainpage-content-searchbart" style="width: 100%; float:left;">
                    <div class="mainpage-content-right-searchbar">
                    	<button id='searchButton' type='button' class="btn btn-primary"  onClick="getCategoryList();"><?php //echo $this->translate('Search'); ?></button>
                    </div>
                    <div class="mainpage-content-right-inner-left-searchbar">
                    	<input type="text" placeholder="search" class="span3" id="SearchCategory" name="SearchCategory">
                    </div>                        
                </div>
            </form>-->
            
            <table class="table table-bordered table-striped" id="newstickerListTbl" cellpadding="0" cellspacing="0" >
            	<colgroup>
                  <col class="span7">
                  <col class="span2">
                  <col class="span1">
                </colgroup>
                <thead>
	            	<tr>
	            	 	<th><?php echo $this->translate('id'); ?></th>
	            	    <th><?php echo $this->translate('Title');?></th>
                        <th><?php echo $this->translate('Shop');?></th>
	                    <th><?php echo $this->translate('Date'); ?></th>
	                    <th><?php echo $this->translate('Ref. Url'); ?></th>
	                    <th><?php echo $this->translate('Delete'); ?></th>
	                
	            	</tr>
	        </thead>
			    	
    </table>
    </div>
    </div>
        
 