<div class="code-details">
    <article class="box">
        <h2><?php echo $this->translate('About this voucher');?></h2>
        <p><?php echo $this->offerDescription;?></p>
    </article>
    <?php
if($this->expiredMessage == 'false') { 
    echo $this->partial(
        'offer/_extendedExpiredCode.phtml',
        array('expiredOffer'=>$this->expiredOffer)
    );
}
    ?>
    <article class="box terms-block">
        <h2><?php echo $this->translate('Terms &amp; Conditions');?></h2>
        <ol class="num-list">
        <?php echo $this->termAndCondition;?>
        </ol>
    </article>
    <article class="box box-2">
        <h2><?php echo $this->translate('How to Use The Voucher Codes'); ?></h2>
        <p><?php echo $this->translate('Cras sed lorem dignissim urna porta congue. Duis tincidunt orci vel varius dignissim. Vivamus dapibus erat dapi bus lacus sodales, eu porta velit dictum. Fusce et enim pharetra, commodo purus varius.');?>
        </p>
        <div class="visual-img">
            <img src="<?php echo HTTP_PATH;?>public/images/img-02.jpg" width="700" height="200" alt="image description">
        </div>
    </article>
</div>
