<article class="box box-2">
    <h2><?php echo $this->translate('How to Use The Voucher Codes'); ?></h2>
    <p><?php echo $this->translate('Cras sed lorem dignissim urna porta congue. Duis tincidunt orci vel varius dignissim. Vivamus dapibus erat dapi bus lacus sodales, eu porta velit dictum. Fusce et enim pharetra, commodo purus varius.');?>
    </p>
    <div class="visual-img">
        <img src="<?php echo HTTP_PATH;?>public/images/img-02.jpg" width="700" height="200" alt="image description">
    </div>
</article>
    </div>
</div>
