<?php
$viewHelperObject = new FrontEnd_Helper_viewHelper();
$howToGuideBigImageDetails = $viewHelperObject->getHowToGuidesImage($this->shop['bigimage']);
$howToGuideSmallImageDetails = $viewHelperObject->getHowToGuidesImage($this->shop['smallimage']);
?>
<article class="box box-2">
    <h2><?php echo $this->translate('How to Use The Voucher Codes'); ?></h2>
    <p><?php echo $this->shop['howToIntroductionText']; ?></p>
    <?php if(!empty($howToGuideBigImageDetails) && !empty($howToGuideSmallImageDetails)) :?>
    <div class="visual-img">
        <img src="<?php echo $howToGuideSmallImageDetails['howToGuideImagePath'];?>" alt="<?php echo $howToGuideSmallImageDetails['howToGuideImageAltText'];?>">
        <img src="<?php echo $howToGuideBigImageDetails['howToGuideImagePath'];?>" alt="<?php echo $howToGuideBigImageDetails['howToGuideImageAltText'];?>">
    </div>
    <?php endif; ?>
</article>
