<?php
$offer = Offer::getOfferDetailOnShop($this->offerId);
$offer = (object) $offer;
$offerPartial = new FrontEnd_Helper_OffersPartialFunctions();
$urlToShow = $offerPartial->getUrlToShow($offer);
$offerBounceRate = "/out/offer/".$offer->id;
$permalink = $offer->shop['permalink'];
$offerTitle = FrontEnd_Helper_viewHelper::replaceStringVariable($offer->title);
echo $offerPartial->getCommonRedirectUrlForOffer(
    $offer,
    $urlToShow,
    $offerBounceRate,
    $offerTitle,
    'offerTitle'
); 