<?php
$offer = (object) $this->couponDetail[0];
$offerPartialClass = new FrontEnd_Helper_OffersPartialFunctions();
$offerUrlToShow = $offerPartialClass->getUrlToShow($offer);
$offerBounceRate = "/out/offer/".$offer->id;
$offerDayDifference = $offerPartialClass->getDaysDifference($offer->endDate);
$offerTermsAndConditions = $offerPartialClass->getOfferTermsAndCondition($offer);

$this->minifyHeadScript()->prependFile("public/js/front_end/jquery.expander.min.js");
$this->minifyHeadScript()->prependFile("public/js/front_end/storeDetail.js");
$this->minifyHeadScript()->prependFile("public/js/front_end/socialmedia.js");

if (LOCALE == '') {
	$domainName = HTTP_PATH;
} else {
	$domainName = HTTP_PATH_LOCALE;
}

$shopDiscussion = '';
$partialViewPath = 'partials/';
if($offer->shop['discussions'] == 1):
    $shopDiscussion = $this->partial($partialViewPath.'_discussion.phtml', array('shopName' => $offer->shop['name']));
endif;

?>
<div class="header-block header-block-2">
    <div class="icon">
        <?php
         $shopLink = HTTP_PATH_LOCALE.$offer->shop['permaLink'];
         $shopPicture = PUBLIC_PATH_CDN . ltrim($offer->shop['logo']['path'], "/") .'thum_big_'. $offer->shop['logo']['name'];
         ?>
        <a href= "<?php echo $shopLink; ?>">
            <img src="<?php echo $shopPicture;?>" width="176" height="89" alt="<?php echo $offer->shop['name'];?>">
        </a>
    </div>
    <div class="box">
        <h1><?php echo strlen($offer->title)<= 50 ?  $offer->title : substr($offer->title, 0, 50).'...';?></h1>
    </div>
</div>
<div class="row">
    <div id="content" class="col-md-8 col-sm-8">
        <section class="section">
            <article class="block <?php echo $offer->exclusiveCode == '1' ? "orange-block" : "active"; ?>">
                <div class="holder">
                    <a class="<?php echo $offerPartialClass->getClassNameForOffer($offer,'simple');?>" href="<?php echo $offerUrlToShow;?>" rel="nofollow"
                                target="_blank" onClick="viewCounter('onclick', 'offer', <?php echo $offer->id; ?>), ga('send', 'event', 'aff','<?php echo $offerBounceRate; ?>');">
                                <?php echo $offerPartialClass->getOfferImage($offer, $this->offersType);?>
                    </a>
                    <div class="box">
                        <div class="text">
                            <p><?php echo $offerPartialClass->dateStringFormat($offer, $offerDayDifference)?></p>
                                <a id="<?php echo $offer->id ;?>"
                                            href="<?php echo $offerUrlToShow;?>"
                                            rel="nofollow" class="link" target="_blank"
                                            onClick="<?php echo $offer->discountType == "CD" ? 'showCodePopUp(this),' : '' ?> ga('send', 'event', 'aff','<?php echo $offerBounceRate; ?>');">
                                            <?php echo $offer->title;?>
                                </a>
                        </div>
                        <div class="buttons" id="offerButton<?php echo $offer->id ;?>">
                        <?php
                        echo $offerPartialClass->getMainButtonforOffer($offer, $offerUrlToShow, $offerBounceRate);
                        echo $offerPartialClass->getSecondButtonforOffer($offer, $offerUrlToShow, $offerBounceRate);
                        ?>
                       </div>
                       <div class="the-code" id="offerCodeDiv<?php echo $offer->id ;?>">
                            <span class="instruction"><strong><?php echo $this->translate('enter this code at checkout')?></strong></span>
                            <strong class="code-value"><?php echo $offer->couponCode;?></strong>
                       </div>
                       <ul class="view-list">
                           <li>
                               <a href="<?php echo $domainName.$offer->shop['name']; ?>">
                                    <?php echo $this->translate('View all ').$offer->shop['name']. $this->translate(' Voucher Codes');?>
                               </a>
                           </li>
                       </ul>
                   </div>
               </div>
           </article>
           <div class="code-details">
               <article class="box">
                   <h2>About this voucher</h2>
                   <p><?php echo $offer->extendedFullDescription;?></p>
               </article>
               <article class="box terms-block">
                   <h2>Terms &amp; Conditions</h2>
                   <ol class="num-list">
                   <?php echo $offerTermsAndConditions;?>
                   </ol>
               </article>
               <article class="box box-2">
                   <h2><?php  echo $this->translate('How to Use The Voucher Codes'); ?></h2>
                   <p><?php  echo $this->translate('Cras sed lorem dignissim urna porta congue. Duis tincidunt orci vel varius dignissim. Vivamus dapibus erat dapi bus lacus sodales, eu porta velit dictum. Fusce et enim pharetra, commodo purus varius.');?></p>
                       <div class="visual-img">
                           <img src="<?php echo HTTP_PATH;?>public/images/img-02.jpg" width="700" height="200" alt="image description">
                       </div>
               </article>
        </div>
    </section>
    <?php echo $shopDiscussion;?>
    </div>
    <aside class="col-md-4 col-sm-4" id="sidebar">
<?php
$locale = LOCALE != 'en'? LOCALE. '/' : '';
echo $this->esi($locale.'store/signupwidget');
echo FrontEnd_Helper_viewHelper::socialmediaSmall('top20');
?>
    </aside>
</div>