<?php
$offer = (object) $this->couponDetail[0];
$offerUrlToShow = FrontEnd_Helper_OfferPartialFunctions::getUrlToShow($offer);
$offerBounceRate = "/out/offer/".$offer->id;
$offerDayDifference = FrontEnd_Helper_OfferPartialFunctions::getDaysDifference($offer->endDate);
$offerTermsAndConditions = FrontEnd_Helper_OfferPartialFunctions::getOfferTermsAndCondition($offer);
$controllerName =  $this->controllerName;
$socialMediaTitle = "<h2>".$this->translate('Share')."</h2>
<span>".$this->translate('And receive cool discounts and useful actions through google+, twitter and Facebook')."</span>";

$this->minifyHeadScript()->prependFile("public/js/front_end/jquery.expander.min.js");
$this->minifyHeadScript()->prependFile("public/js/front_end/storeDetail.js");
$this->minifyHeadScript()->prependFile("public/js/front_end/socialmedia.js");
?>
<div class="header-block header-block-2">
    <div class="icon">
        <?php
         $shopLink = HTTP_PATH_LOCALE.$offer->shop['permaLink'];
         $shopPicture = PUBLIC_PATH_CDN . ltrim($offer->shop['logo']['path'], "/") .'thum_big_'. $offer->shop['logo']['name'];
         ?>
        <a href= "<?php echo $shopLink; ?>">
            <img src="<?php echo $shopPicture;?>" width="176" height="89" alt="<?php echo $offer->shop['name'];?>">
        </a>
    </div>
    <div class="box">
        <h1><?php echo strlen($offer->title)<= 50 ?  $offer->title : substr($offer->title, 0, 50).'...';?></h1>
    </div>
</div>
<div class="row">
    <div id="content" class="col-md-8 col-sm-8">
      
          <?php   $storeViewPartialPath = 'store/';
			if(count($offer) > 0):
			  echo $this->partial(
			        $storeViewPartialPath. '_offer.phtml',
			        array(
			            'offers' => array($this->couponDetail[0]),
			            'offersType'=>'coupon',
			            'shopName' => $offer->shop['name'],
			            'shop' => $offer->shop,
			            'zendForm'=>''
			        )
			    );
			endif;?>
			  <section class="section">
            <div class="code-details">
                <article class="box">
                    <h2>About this voucher</h2>
                    <p><?php echo $offer->extendedFullDescription;?></p>
                </article>
                <article class="box terms-block">
                    <h2>Terms &amp; Conditions</h2>
                    <ol class="num-list">
                        <?php echo $offerTermsAndConditions;?>
                    </ol>
                </article>
                <article class="box box-2">
                    <h2><?php  echo $this->translate('How to Use The Voucher Codes'); ?></h2>
                    <p><?php  echo $this->translate('Cras sed lorem dignissim urna porta congue. Duis tincidunt orci vel varius dignissim. Vivamus dapibus erat dapi bus lacus sodales, eu porta velit dictum. Fusce et enim pharetra, commodo purus varius.');?></p>
                        <div class="visual-img">
                            <img src="<?php echo HTTP_PATH;?>public/images/img-02.jpg" width="700" height="200" alt="image description">
                        </div>
                </article>
            </div>
        </section>
<?php 
$shopDiscussion = '';
$partialViewPath = 'partials/';
if($offer->shop['discussions'] == 1):
    $shopDiscussion = $this->partial($partialViewPath.'_discussion.phtml', array('shopName' => $offer->shop['name']));
endif;
    echo $shopDiscussion;
?>
    </div>
    <aside class="col-md-4 col-sm-4" id="sidebar">
        <div class="block white">
<?php
$locale = LOCALE != 'en'? LOCALE. '/' : '';
echo $this->esi($locale.'store/signupwidget'); ?>
        </div>
        <article class="block">
<?php
echo FrontEnd_Helper_viewHelper::socialmediaSmall('top20', $socialMediaTitle, $controllerName);
?>
        </article>
    </aside>
</div>