<?php 
	$this->minifyHeadScript()->prependFile (HTTP_PATH."public/js/front_end/moneysaving.js" );
     $headerSearch = new FrontEnd_Helper_viewHelper(); 
     $page = $this->page;
     $breadcrumb = "<a href='".HTTP_PATH_LOCALE."moneysavingguide' style='color:#6a6a6a'>".$this->translate('Bespaar Wijzer')."</a>";
  	 $headerSearch = new FrontEnd_Helper_viewHelper(); 
		echo $this->partial('partials/_headerSearch.phtml',array('breadcrumb' => $breadcrumb));

		?> 

     <h1><strong><?php echo $this->translate('The Expired offers has been deleted Successfully!!!')?></strong></h1>