<?php
$this->minifyHeadLink()->prependStylesheet("/public/css/front_end/flipit-expired.css");
$currentDate = date('Y-m-d h:i:s ');
$offer = (object) $this->couponDetails[0];
$shopDiscussion = '';
$partialViewPath = 'partials/';
if ($offer->shopOffers['discussions'] == 1) {
    $shopDiscussion = $this->partial(
        $partialViewPath.'_discussion.phtml',
        array('shopName' => $offer->shopOffers['name'])
    );
}

$offerPartial = new FrontEnd_Helper_OffersPartialFunctions();
$expiredMessage = $offerPartial->getExpiredOfferMessage(
    $offer->endDate['date'], $currentDate);

$extendedOffer = $this->partial(
    $partialViewPath.'_offer.phtml',
    array(
    'offers' => array($expiredMessage=='' ? $this->couponDetails[0] : $this->topOfferFromStore[0]),
    'offersType'=>'extendedOffer',
    'shopName' =>'',
    'shop' =>'',
    'zendForm'=>$this->form
    )
);
$storeViewPartialPath = 'store/';

$termsAndConditions = $offerPartial->getOfferTermsAndCondition($offer);
$extendedTitle = !empty($offer->extendedoffertitle) ? $offer->extendedoffertitle : $offer->title;
$frontShopHeaderHelper = new FrontEnd_Helper_ShopHeaderPartialFunctions();
echo $headerBlock = $frontShopHeaderHelper->getShopHeader(
    $offer->shopOffers,
    $expiredMessage,
    $extendedTitle
);
?>
</div></div></div>
<div class="row">
    <div id="content" class="col-md-8 col-sm-8">
    <?php 
    echo $expiredMessage;
    echo $extendedOffer;
if ($expiredMessage != '') { ?>
         </section>
    <div class="section">
    <?php 
}
?>
    <div class="code-details">
<?php
if ($expiredMessage != '') {
    echo $this->partial(
        'offer/_extendedExpiredCode.phtml',
        array('expiredOffer'=>$this->couponDetails[0])
    );
}
?>
          <article class="box">
            <h2><?php echo $this->translate('About this voucher');?></h2>
            <p><?php echo $offer->extendedFullDescription;?></p>
        </article>
<?php if (!empty($termsAndConditions)) {?>
        <article class="box terms-block">
            <h2><?php echo $this->translate('Terms &amp; Conditions');?></h2>
            <ol class="num-list">
            <?php echo $termsAndConditions;?>
            </ol>
        </article>
    <?php
}
?>
    </div>
<?php
if ($expiredMessage != '') { ?>
    </div>
    <?php 
}
if ($expiredMessage == '') {
    ?>
         </section>
    <?php 
}
        echo $shopDiscussion;
    
    ?>
    </div>
    <aside class="col-md-4 col-sm-4" id="sidebar">
    <?php
    echo $this->partial(
        'store/_shop-sidebar.phtml',
        array(
            'shopEditor' => '',
            'latestShopUpdates'=> '',
            'shopChain' => $this->shopChain,
            'shop' => $this->currentStoreInformation[0],
            'popularStoresList'=> $this->popularStoresList
        )
    );
    if ($this->currentStoreInformation[0]['showSignupOption']) :
        $this->locale = LOCALE != 'en' ? LOCALE . '/' : '';
        echo $this->esi($this->locale.'signup/signupwidget?shopId='.$this->currentStoreInformation[0]['id']
            .'&signupFormWidgetType=sidebarWidget&shopLogoOrDefaultImage=');
    endif;
    ?>
    </aside>
</div>