<?php
$partialsViewPath = 'partials/';
$imagePath = isset($this->pageHeaderImage['path']) ? $this->pageHeaderImage['path'] : '';
$imageName = isset($this->pageHeaderImage['name']) ? $this->pageHeaderImage['name'] : '';
$pageImagePath = PUBLIC_PATH_CDN.$imagePath.$imageName;
$pageHeaderPartial = new FrontEnd_Helper_PageHeaderPartialFunctions();
echo $pageHeaderPartial->getCategoryOrPageHeader($this->pageTitle, $pageImagePath);
$storeViewPartialPath = 'store/';
$signUpWidgetForm = '';
    $signUpWidgetForm = $this->partial(
        $partialsViewPath.'_signupForm.phtml',
        array(
           'zendForm' => $this->sidebarWidgetForm,
           'signupFormWidgetType'=>'sidebarWidget',
           'shopId'=>'',
           'shopLogoOrDefaultImage'=>''
        )
    );

$newestOffers = ' <div class = "no-record">'.$this->translate('No record found') .'</div>';
if (count($this->offersWithPagination)>0) {
$newestOffers = $this->partial(
        $partialsViewPath.'_offer.phtml',
        array('offers'=> $this->offersWithPagination,
         'offersType'=>$this->offersType, 'shopName'=> '', 'shop'=>'', 'zendForm'=>$this->form)
    );
} 
?>
<div class="row">
    <div id="content" class="col-md-8 col-sm-8">
     <?php echo $newestOffers; ?>  
    </div>
    <aside class="col-md-4 col-sm-4" id="sidebar">
        <?php
        echo $signUpWidgetForm;
        $frontendViewHelper = new FrontEnd_Helper_viewHelper();
        echo $frontendViewHelper->socialMediaWidget(strtolower($this->actionName));
        ?>
    </aside>
</div>