<?php
$partialsViewPath = 'partials/';
$pageHeader = new FrontEnd_Helper_PageHeaderPartialFunctions();
echo $pageHeader->getCategoryOrPageHeader(
    $this->pageTitle,
    $pageHeader->getCategoryOrPageHeaderImage($this->pageHeaderImage)
);
$storeViewPartialPath = 'store/';

$newestOffers = ' <div class = "no-record">'.$this->translate('No record found') .'</div>';
if (count($this->offersWithPagination)>0) {
$newestOffers = $this->partial(
        $partialsViewPath.'_offer.phtml',
        array(
            'offers'=> $this->offersWithPagination,
            'offersType'=>$this->offersType, 
            'shopName'=> '', 
            'shop'=>'', 
            'zendForm'=>$this->form,
            'widgetPosition'=>$this->widgetPosition
        )
    );
} 
?>
<div class="row">
    <div id="content" class="col-md-8 col-sm-8">
     <?php echo $newestOffers; ?>  
    </div>
    <aside class="col-md-4 col-sm-4" id="sidebar">
    <?php
    $this->locale = LOCALE != 'en' ? LOCALE . '/' : '';
    $frontendSidebarHelper = new FrontEnd_Helper_SidebarWidgetFunctions();
    echo $frontendSidebarHelper->sidebarWidgets('newest-code', $this);
    ?>
    </aside>
</div>