<?php
$partialsViewPath = 'partials/';
$pageHeaderPartial = new FrontEnd_Helper_PageHeaderPartialFunctions();
echo $pageHeaderPartial->getCategoryOrPageHeader($this->pageTitle, $this->pageLogo);
$storeViewPartialPath = 'store/';
$signUpWidgetForm = '';
    $signUpWidgetForm = $this->partial(
        $partialsViewPath.'_signupForm.phtml',
        array(
           'zendForm' => $this->sidebarWidgetForm,
           'signupFormWidgetType'=>'sidebarWidget',
           'shopId'=>'',
           'shopLogoOrDefaultImage'=>''
        )
    );
?>
<div class="row">
    <div id="content" class="col-md-8 col-sm-8">
<?php
if (count($this->offersWithPagination)>0) {
    echo $this->partial(
        $partialsViewPath.'_offer.phtml',
        array('offers'=> $this->offersWithPagination,
         'offersType'=>$this->offersType, 'shopName'=> '', 'shop'=>'', 'zendForm'=>$this->form)
    );
} else {
    ?>
        <div class = "no-record">
        <?php echo $this->translate('No record found');?>
        </div>
    <?php
}
?>        
    </div>
    <aside class="col-md-4 col-sm-4" id="sidebar">
        <?php
        echo $signUpWidgetForm;
        echo FrontEnd_Helper_viewHelper::socialMediaWidget(strtolower($this->actionName));
        ?>
    </aside>
</div>