<?php
if (!empty($this->offerViewCount['viewCount']) && !empty($this->offerViewCount['offsetType'])) {
    ?>
    <span class="used text-info">
        <span class="text-over">
        <?php 
        $offsetType = 
            $this->offerViewCount['offsetType'] == 'day' 
                ? 'used today' 
                : 'used this '. $this->offerViewCount['offsetType'];
        echo $this->offerViewCount['viewCount'] . " " . FrontEnd_Helper_viewHelper::__translate($offsetType);?>
        </span>
    </span>
    <?php
}
?>
