<?php
$offer = (object) $this->offerdetail[0][0];
$offerPartial = new FrontEnd_Helper_OffersPartialFunctions();
$termsAndConditions =  $offerPartial->getOfferTermsAndCondition($offer);
$daysTillOfferExpires =  $offerPartial->getDaysTillOfferExpires($offer->endDate);
if ($this->offerImagePath == '') {
    $lightboxContent = $this->partial(
        'offer/_lightBoxPartial.phtml',
        array(
            'offer' => $offer,
            'termsAndConditions' => $termsAndConditions,
            'siteImage' => $offerPartial->getSiteLogoforPopup(),
            'couponCode' => $this->couponCode,
            'urlToShow' => $offerPartial->getUrlToShow($offer)
       )
    );
} else {
    $lightboxContent = '<img src = "'.$this->offerImagePath.'" alt = "Printable Coupon" title="Printable Coupon">';
}
?>
<section id="code-lightbox">
    <div id="popup1" class="lightbox">
    <a class="glyphicon glyphicon-remove btn-close" onclick="customPopUpClose()"></a>
        <header class="head">
            <div class="icon">
                <img src="<?php echo $this->facebookImage; ?>" 
                width="176" height="89" alt='<?php echo $offer->shopOffers['name'];?>' title='<?php echo $offer->shopOffers['name'];?>'>
            </div>
            <div class="box">
                <div class="text">
                    <p><?php echo  $offerPartial->getOfferOptionAndOfferDates($offer, $daysTillOfferExpires);?></p>
                    <h3><?php echo $offer->title; ?></h3>
                </div>
            </div>
        </header>
       <?php
        echo $lightboxContent;
       ?> 
    </div> 
</section>

