<?php
$offer = (object) $this->offerdetail[0];
$offerPartialClass = new FrontEnd_Helper_OffersPartialFunctions();
$termsAndConditions =  $offerPartialClass->getOfferTermsAndCondition($offer);
$DaysTillOfferExpires =  $offerPartialClass->getDaysTillOfferExpires($offer->endDate);
if ($this->offerImagePath == '') {
    $lightBoxcontent = $this->partial(
        'offer/_lightBoxPartial.phtml',
        array(
            'offer' => $offer,
            'termsAndConditions' => $termsAndConditions,
            'siteImage' => $offerPartialClass->getSiteLogoforPopup(),
            'code' => $this->code
       )
    );
} else {
    $lightBoxcontent = '<img src = "'.$this->offerImagePath.'" alt = "Printable Coupon">';
}
?>
<section id="code-lightbox">
    <div id="popup1" class="lightbox">
    <a class="glyphicon glyphicon-remove btn-close" onclick="customPopUpClose()"></a>
        <header class="head">
            <div class="icon">
                <img src="<?php echo $this->facebookImage; ?>" width="176" height="89" alt='<?php echo $offer->shop['name'];?>'>
            </div>
            <div class="box">
                <div class="text">
                    <p><?php echo  $offerPartialClass->getOfferOptionAndOfferDates($offer, $DaysTillOfferExpires);?></p>
                    <h1><?php echo $offer->title; ?></h1>
                </div>
            </div>
        </header>
       <?php
        echo $lightBoxcontent;
       ?> 
    </div> 
</section>

