<?php
$partialViewPath = 'partials/';
$pageHeader = new FrontEnd_Helper_PageHeaderPartialFunctions();
echo $pageHeader->getCategoryOrPageHeader(
    $this->pageTitle,
    $pageHeader->getCategoryOrPageHeaderImage($this->pageHeaderImage)
);
?>
<div class="row">
    <div id="content" class="col-md-8 col-sm-8">
<?php 
if(count($this->top20PopularOffers) > 0):
    echo $this->partial(
        $partialViewPath.'_offer.phtml',
        array(
            'offers' => $this->top20PopularOffers,
            'offersType'=>'top20',
            'shopName' =>'',
            'shopId' =>'',
            'zendForm'=>$this->form
        )
    );
endif;

$popularStores = '';
if (!empty($this->popularStores)) :
     $popularStores = $this->partial(
         $partialViewPath.'_popular-stores.phtml',
         array(
            'popularStores' => $this->popularStores,
            'headerText' => $this->translate('Popular Stores')
        )
     );
endif;
echo $popularStores; ?>

    </div>
    <aside class="col-md-4 col-sm-4" id="sidebar">
<?php
$this->locale = LOCALE != 'en' ? LOCALE . '/' : '';
$sidebarWidgetNamespace = new Zend_Session_Namespace('zendFormSidebar');
$sidebarWidgetNamespace->zendFormSidebar = serialize($this->sidebarWidgetForm);
$this->esi($this->locale.'signup/signupwidget?shopId='
    .'&signupFormWidgetType=sidebarWidget&shopLogoOrDefaultImage=');

$frontendSidebarHelper = new FrontEnd_Helper_SidebarWidgetFunctions();
echo $frontendSidebarHelper->socialMediaWidget('top20');
?>
    </aside>
</div>
