<?php
$pageLogo = $this->pageLogo;
$partialViewPath = 'partials/';
$pageHeaderPartial = new FrontEnd_Helper_PageHeaderPartialFunctions();
echo $pageHeaderPartial->getCategoryOrPageHeader($this->pageTitle, $pageLogo);
?>
<div class="row">
    <div id="content" class="col-md-8 col-sm-8">
<?php 
if(count($this->top20PopularOffers) > 0):
    echo $this->partial(
        $partialViewPath.'_offer.phtml',
        array(
            'offers' => $this->top20PopularOffers,
            'offersType'=>'top20',
            'shopName' =>'',
            'shopId' =>'',
            'zendForm'=>$this->form
        )
    );
endif;

$signUpWidgetForm = '';
$signUpWidgetForm = $this->partial(
    $partialViewPath.'_signupForm.phtml',
    array(
       'zendForm' => $this->sidebarWidgetForm,
       'signupFormWidgetType'=> 'sidebarWidget',
       'shopId'=>'',
       'shopLogoOrDefaultImage'=>''
    )
);

?>
    </div>
    <aside class="col-md-4 col-sm-4" id="sidebar">
<?php
echo $signUpWidgetForm;
echo FrontEnd_Helper_viewHelper::socialMediaWidget('top20');
?>
    </aside>
</div>
