<?php
$this->minifyHeadScript()->prependFile("public/js/front_end/partialOffer.js");
$this->minifyHeadScript()->prependFile("public/js/front_end/signupnewsletter.js");
$this->minifyHeadScript()->prependFile("public/js/front_end/modalPopLite.min.js");
$this->minifyHeadScript()->prependFile("public/js/front_end/socialmedia.js");

$subTitle = $this->content;
$pageLogo = $this->pageLogo;
$partialViewPath = 'partials/';
echo $this->partial(
    $partialViewPath.'_default_page_header.phtml',
    array('pageTitle' => $this->pageTitle, 'pageLogo'=>$pageLogo ,'subTitle'=>$subTitle )
);
?>
<div class="row">
    <div id="content" class="col-md-8 col-sm-8">
<?php 
$storeViewPartialPath = 'store/';
if(count($this->top20PopularOffers) > 0):
    echo $this->partial(
        $storeViewPartialPath .'_offer.phtml',
        array(
            'offers' => $this->top20PopularOffers,
            'offersType'=>'top20',
            'shopName' =>'',
            'shopId' =>'',
            'zendForm'=>$this->form
        )
    );
endif;

$signUpWidgetForm = '';
$signUpWidgetForm = $this->partial(
    $storeViewPartialPath.'signupwidget.phtml',
    array(
       'zendForm' => $this->sidebarWidgetForm,
       'SignupFormWidgetType'=> 'sidebarWidget',
       'shopId'=>'',
       'shopLogoOrDefaultImage'=>''
    )
);

?>
    </div>
    <aside class="col-md-4 col-sm-4" id="sidebar">
<?php
echo $signUpWidgetForm;
echo FrontEnd_Helper_viewHelper::socialMediaWidget('top20');
?>
    </aside>
</div>
