<!-- start affiliate network list -->
<?php 
  $this->headTitle()->append($this->translate('Generat RSS Feeds'));
?>
<!DOCTYPE HTML>
<html lang="en-US">
<head>
	<meta charset="UTF-8">
	<title></title>
<script src="http://localhost/fileupload/js/jquery.min.js"></script>
<script src="http://localhost/fileupload/js/jquery.ui.widget.js"></script>
<script src="http://localhost/fileupload/js/jquery.iframe-transport.js"></script>
<script src="http://localhost/fileupload/js/jquery.fileupload.js"></script>
<!-- JavaScript used to call the fileupload widget to upload files -->
  <script>
    // When the server is ready...
    $(function () {
        'use strict';
        
        // Define the url to send the image data to
        var url = '/admin/offer/importcodes';
        
        // Call the fileupload widget and set some parameters
        $('#fileupload').fileupload({
            url: url,
            dataType: 'json',
			maxFileSize: 5000000,
			acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
            done: function (e, data) {
                // Add each uploaded file name to the #files list
                $.each(data.result.files, function (index, file) {
                    $('<li/>').text(file.name).appendTo('#files');
                });

                 console.log('done');	
            	   
    	    	   jQuery("#uploadFileBtn").off("click");

   	   	   		setTimeout(function(){
                     	$('#progress').slideUp('slow',function() {
		                     	 $('#progress .bar').css('width',  '0%');
                     	});
                     },3000);

   	   	   		
            },
            add:function (e, data) {
			 
				$("#uploadFileBtn").off('click').on('click',function () {           
					  data.submit();
					  $('#progress').show('fast');
				});
					 					
              
            },
 
            progressall: function (e, data) {
                // Update the progress bar while files are being uploaded
                var progress = parseInt(data.loaded / data.total * 100, 10);
                $('#progress .bar').css(
                    'width',
                    progress + '%'
                );
            }
        }) ;
    }); 
    </script>
</head>
<body>
	
<div id="affiliateNetworkList">
   <div class="wrap columns-2">
		
		
		<?php if($this->messageSuccess!='' || $this->messageError!='' ){?>
		<br><div class ="mainpage-content-colorbox success">
		<?php if($this->messageSuccess!=''){?>
		<span class="success"><?php echo $this->messageSuccess; ?></span>
		<?php }?>
		<?php if($this->messageError!=''){?>
		<span class="error"><?php echo $this->messageError; ?></span>
		<?php } ?>
		</div>
		<?php 
		}?> 
		 
       <h1><?php echo $this->translate('Generat RSS Feeds'); ?> 
      </h1>
			<ul>
				<li><a href="rss/new-offers"><?php echo $this->translate('Newest offers');?></a></li>
				<li><a href="rss/popular-offers"><?php echo $this->translate('Popular offers');?></a></li>
     		</ul>
            
         

    </div>
    </div>
 <!-- end affiliate network -->


    
		<!-- Button to select & upload files -->

			<!-- The file input field used as target for the file upload widget -->
			<input id="fileupload" type="file" name="files[]">
	
	<div class="container">  
		<input type="button" class="btn btn-success" id="uploadFileBtn" value="Upload" />
	<br />
			<!-- The global progress bar -->
		<p>Upload progress</p>
		<div id="progress" class="progress progress-success progress-striped">
			<div class="bar"></div>
		</div>
		<!-- The list of files uploaded -->
		<p>Files uploaded:</p>
		<ul id="files"></ul>

	</div>
</body>
</html>