<header class="box head">
    <div class="code expired-code">
        <div class="center">
            <div class="code-holder">
                <strong><?php echo $this->translate('expired');?></strong>
            </div>
        </div>
        <div class="bottom"><?php echo $this->translate('code');?></div>
    </div>
    <div class="text">
        <h2>
        <?php
        echo $this->expiredOffer['shopOffers']['name']
             .  ' '. $this->translate('coupon code') 
             .' - '. $this->translate('Expired')
             . ' ' . date('Y-M-d', strtotime($this->expiredOffer['endDate']['date']));?></h2>
        <span class="meta">
            <?php echo $this->translate('Code:'). ' ' ?>
            <strong><?php echo $this->expiredOffer['couponCode'];?></strong>
        </span>
    </div>
</header>