<script type="text/javascript">
    $('#code-hint').hide();
    var clip = new ZeroClipboard($('a#code-button'));
    clip.on('error', function (client, args) {
        $('#code-hint').show();
        $('a#code-button').hide();
        var codeBox = $('#couponCode');
        codeBox.addClass("noflash");
        codeBox.focus();
        codeBox.select();
    });
    clip.on("aftercopy", function(event) {
        $('a#code-button').addClass('copied');
        $('a#code-button').html($('#copiedText').val());
    });
    if (navigator.appVersion.indexOf("MSIE 10") !== -1) {
        var codeBox = $('#couponCode');
        codeBox.addClass("noflash");
    }
</script>
<?php
$clickoutLink = isset($this->expiredOffer) && $this->expiredOffer != '' ? HTTP_PATH_LOCALE.'out/shop/'.$this->offer->shopOffers['id'] : $this->urlToShow;
?>
<div class="form">
    <form role="form">
        <input type="hidden" name="copiedText" id='copiedText'
            value='<?php echo FrontEnd_Helper_viewHelper::__form("COPIED");?>'>
        <fieldset>
            <div id="code-hint"><?php echo $this->translate('Press Ctrl + C to copy the code');?></div>
            <div class="holder">
                <input id="couponCode" class="default form-control" type="text"
                value="<?php echo $this->couponCode; ?>" readonly = "yes">
                <a data-clipboard-text="<?php echo $this->couponCode; ?>"
                 id='code-button' class="btn orange btn-warning">
                    <?php echo $this->translate('Copy Code');?>
                </a>
            </div>
            <div id="bigtextPopupShopLink">                    
                 <a href="<?php echo $clickoutLink; ?>" class="btn blue btn-primary" target="_blank">
                    <?php 
                    echo FrontEnd_Helper_viewHelper::__form('form_Open') . ' ' . $this->offer->shopOffers['name'].' ' .
                        FrontEnd_Helper_viewHelper::__form('form_New year sale code');
                    ?>
                </a>
            </div>
        </fieldset>
    </form>
</div>
<div class="meta">
<?php
if ($this->offer->userGenerated ==0 &&  $this->termsAndConditions!='' && $this->termsAndConditions!=null) { ?>
    <a id="termAndConditionLinkPopup<?php echo $this->offer->id ;?>" 
        onclick="showPopupTermAndConditions(<?php echo $this->offer->id; ?>)" class="terms"
                    href="javascript:void(0);"><?php echo $this->translate('Terms &amp; Conditions'); ?> 
    </a>
    <?php
    if ($this->termsAndConditions!='' && $this->termsAndConditions!=null && $this->extendedOffer =='1') {?>
        &nbsp; | &nbsp;
        <?php
    }
}
?>
<?php 
if ($this->expiredOffer != '') { ?>
    <span class="text">
        <?php echo FrontEnd_Helper_viewHelper::__form('form_Deze code is helaas verlopen. Vaak blijken codes nog wel te werken');?>!
    </span>
<?php 
}
?>
</div>
<div class="terms-block info-block" id='termAndConditionsPopup<?php echo $this->offer->id ;?>' style = "display:none;">
    <ol class="num-list">
        <?php echo $this->termsAndConditions;?>
    </ol>
</div>
   