<div class="mainpage-content-line">
    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Lightbox introduction text'); ?></strong></label></div>
    <div class="mainpage-content-right">
        <div class="mainpage-content-right-inner-right-other"></div>
        <div class="mainpage-content-right-inner-left-other">
            <textarea class="input-xlarge mbot bbot" id="content_1" name="howToIntroductionText" class="ckeditor required"><?php echo $this->howToIntroductionText; ?></textarea>
        </div>   
    </div>
</div>