
<?php 
 $this->headTitle()->append($this->translate('Import Excel for redirects'));
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/jquery.validate.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/importshops.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
 $this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/jquery-ui-1.8.16.custom.css" );
 
?>

<div class="wrap columns-2" id="addNewKeyword">
   <h1><?php echo $this->translate('Import Excel for shops'); ?><button class="btn ml10" type="button" onClick="window.location.href='<?php echo HTTP_PATH ;?>admin/shop'"><?php echo $this->translate('Cancel'); ?></button></h1>
      <form method="POST" enctype="multipart/form-data" name="addShopsForm" id="addShopsForm">
        <div id="poststuff" class="metabox-holder has-right-sidebar">
        <div id="post-body">
           <div>
           <div class="mainpage-content">
                         
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left"><span><strong><?php echo $this->translate('Upload Excel file for import'); ?></strong></span></div>
                            <div class="mainpage-content-right"><input style='width: 204px !important;' type="file" onchange="checkFileType(event)" class="ignore"   name="excelFile" id="excelFile"><span><?php echo $this->translate('.xlsx file only'); ?></span></div>
                        <div class="mainpage-content-left" id="imagerrorDiv" style="float: right; margin:-28px -28px 9px; height : 20px; width : 511px;"></div>
                        </div>
                </div>
               </div>
              </div>
               <br class="clear">
         </div>
         <div class="mainpage-content-colorbox">
            <button type="button" id="importShops" class="btn btn-large btn-primary fl"><?php echo $this->translate('IMPORT'); ?></button>
            <a href="javascript:void(0);" onclick="window.location.href='<?php echo HTTP_PATH ;?>admin/shop'" class="fl m10" ><strong><?php echo $this->translate('CANCEL'); ?></strong></a>
            <a href="<?php echo HTTP_PATH ;?>admin/shop/empty-xlx" class="fl m10" ><strong><?php echo $this->translate('Download empty xlsx'); ?></strong></a>
         </div>
    </form>
</div>