<?php 
$this->headScript()->appendFile(PUBLIC_PATH . "js/jquery.ui.widget.js");
$this->headScript()->appendFile(PUBLIC_PATH ."js/jquery.iframe-transport.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/jquery.fileupload.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/jquery.fileupload-fp.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/jquery.fileupload-ui.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/jquery.dataTables.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/dataTableComman.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/language.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
?>
<div class="wrap columns-2"> 
		
		<?php if($this->messageSuccess!='' || $this->messageError!='' ){?>
		<br><div class ="mainpage-content-colorbox success" style='text-align : center'>
		<?php if($this->messageSuccess!=''){?>
		<span class="success" style='position: relative; top: 8px;'><?php echo $this->messageSuccess; ?></span>
		<?php }?>
		<?php if($this->messageError!=''){?>
		<span class="error" style='position: relative; top: 8px;'><?php echo $this->messageError; ?></span>
		<?php } ?>
		</div>
		<?php 
		}?> 
		
		
         <h1><?php echo $this->translate('Language File');?></h1>

		<hr>

     	<?php
         	$httpScheme = FrontEnd_Helper_viewHelper::getServerNameScheme();
			$storeUrl 			= (empty($_COOKIE['site_name'])) ? 'http://www.kortingscode.nl' : 'http://'.$httpScheme.'.'.$_COOKIE['site_name'];
			$domainUrl 			= ($storeUrl == 'http://www.kortingscode.nl') ? $storeUrl : HTTP_PATH;
			$storeTranslateLink = $domainUrl.'/trans/startinlinetranslation?storeUrl='.$storeUrl.'&hash='.$this->inlineTranslationHash();
		?>
		<a href="<?php echo $storeTranslateLink ?>" class="btn btn-primary"><?php echo $this->translate('Start Inline Translation');?></a>
		<p>&nbsp;</p>

		<h2><?php echo $this->translate('OR');?></h2>


		<form method="POST" enctype=multipart/form-data name="languageForm" id="languageForm" action="<?php echo HTTP_PATH.'admin/language/savefile'?>"> 
			 <div id="poststuff" class="metabox-holder has-right-sidebar">
		   <div id="post-body">
		  	  <div>
		  	       <div class="mainpage-content">
		                <div class="mainpage-content-line mb10">
		                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate("PO,MO File");?></strong></label></div>
							<div class="mainpage-content-right">
		                     <div data-toggle="buttons-checkbox" class="">
								  <span class="img-btn img-btn-success img-fileinput-button " style="display: inline-block !important; float: none;">
					                    <i class="icon-edit icon-white"></i>
					                    <span><?php echo $this->translate('Upload File'); ?></span>
					                   	 <input  class="span3" id="fileupload" type="file" name="files" multiple> 
					                   
								 </span>  
								 <p style='float: right; margin-top: 10px; width: 793px;'><?php echo $this->translate('Upload both PO and MO file one by one')?></p>
		                	</div>
		                    </div>           
		                </div>
		           </div>
		           
		           <div class="mainpage-content">
		                <table class="table table-bordered table-striped" id="languageTable" cellpadding="0" cellspacing="0">
				          <thead>
				              <tr>
				                  <th><?php echo $this->translate('Files');?></th>
				                  <th><?php echo $this->translate('Download'); ?></th>
				                </tr>
				             </thead>
				           </table> 
		           </div>
						
						
		       </div>
		      </div>
              <br class="clear">
         </div>
         <br>
     
     </form> 
     </div>

