<?php 
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/jquery-ui-1.8.16.custom.css" );
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/datepicker.css" );
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/timepicker.css" );
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/addArticle.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/bootbox.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/jquery.textareaCounter.plugin.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/bootstrap-datepicker.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/bootstrap-timepicker.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/ckeditor/ckeditor.js");
$this->headScript ()->appendFile (PUBLIC_PATH . "js/back_end/ckeditor/config.js" );
$this->headScript ()->appendFile ( PUBLIC_PATH . "/js/jquery.NobleCount.js");
?>
<?php echo $this->headTitle()->append('Edit Article');
?>
<script type="text/javascript">
    var CKEDITOR_BASEPATH = "<?php echo PUBLIC_PATH . "js/back_end/ckeditor/" ; ?>" ;
</script>
<div class="wrap columns-2">         
    <h1>
    <?php echo $this->translate('Edit Article'); ?>
        <button type = "button" 
        onClick="window.location.href='<?php echo HTTP_PATH;?>admin/article<?php echo '#'.$this->qstring; ?>'" 
        class="btn ml10" href="#"><?php echo $this->translate('Cancel'); ?>
        </button>
    </h1>  
    <form id="addArticleform" name="addArticleform" 
    enctype="multipart/form-data" 
    method="POST" action="<?php echo HTTP_PATH;?>admin/article/editarticle/id/<?php echo $this->articleData[0]['id']?>">
    <input type="hidden" value="<?php echo $this->role; ?>" name='role' id='role' />
    <input type="hidden" name='qString' id='qString' value='<?php echo $this->qstring; ?>' />
    <input type="checkbox" name="selectedpageType" value="1" id="selectedpageType" class="display-none">
        <div class="metabox-holder has-right-sidebar" id="poststuff">
            <div class="inner-sidebar" id="side-info-column">
                <div class="meta-box-sortables ui-sortable" id="side-sortables">
                    <div class="postbox " id="submitdiv">
                        <div class="sidebar-heading">
                            <p><?php echo $this->translate('Publish'); ?></p>
                        </div>
                        <div class="sidebar-content-box">
                                <button class="btn" type="submit" onClick="$('#savePage').val('draft')" href="#" id="saveDraftbtn" ><?php echo $this->translate('Save Draft'); ?></button> 
                        </div>
                        <input type="hidden" name="savePagebtn" id="savePage" value="">
                        <div class="sidebar-content-box">
                        <?php echo $this->translate('Status:'); ?> 
                            <strong>
                            <?php
                                $publishDate = $this->articleData[0]['publishdate'];
                                if($this->articleData[0]['publish'] == 1 && $publishDate->format('d-m-Y H:i') <= date('d-m-Y H:i')){
                                    echo $this->translate('Published');
                                }else if ($this->articleData[0]['publish'] == 1 &&  $publishDate->format('d-m-Y H:i') > date('d-m-Y H:i')){
                                    echo $this->translate('Scheduled');
                                }else{
                                    echo $this->translate('Draft');
                                } 
                            ?>
                            </strong>
                        </div>
                     <div class="sidebar-content-box" style="width : 225px;">
                        <?php 
                        if(
                            $this->articleData[0]['publish'] == 1  && $publishDate->format('d-m-Y H:i') <= date('d-m-Y H:i'))
                        {
                            echo $this->translate('Published on:');

                        } else if (
                            $this->articleData[0]['publish'] == 1 
                            &&  $publishDate->format('d-m-Y H:i') > date('d-m-Y H:i'))
                        {
                            echo $this->translate('Scheduled for:');
                        }else{
                            echo $this->translate('Published on:');
                        }
                        ?>
                        <strong>
                        <?php 
                        echo 
                        $this->articleData[0]['publish'] == 1 
                        ?  $publishDate->format('d-m-Y H:i') 
                       : $this->translate(' immediately');?>
                       </strong> 
                        <a href="javascript:;" onClick="showPublishDate()" 
                        id="editpublishLink"><?php echo $this->translate('Edit'); ?></a>
                        <span id="publishlater" class="display-none">
                        <input type="text" style="width:110px;margin-top:3px;" 
                        value="<?php echo $publishDate->format('d-m-Y');?>" 
                        placeholder="Publish Date"  id="publishDate" name="publishDate" class="span3">
                        <input type="text" style="width:48px;margin-top:3px;" placeholder="HH" id="publishTimehh"
                         name="publishTimehh" class="span3" 
                         value="<?php echo $publishDate->format('H:i:s');?>">
                        </span>
                    </div>
                    <div class="sidebar-box-footer">
                    <?php 
                        $moveToTrashTranslate = $this->translate('Move to Trash');
                        $moveToTrash = mb_strlen($moveToTrashTranslate) > 7 ? mb_substr($moveToTrashTranslate, 0, 7)
                                            .'..' : $moveToTrashTranslate;
                    ?>
                    <a  style="margin-top: 5px!important;" title = "<?php echo $moveToTrashTranslate;?>"
                    href ='javascript:void(0)' onClick='moveToTrash("<?php echo $this->articleData[0]['id'] ?>")' 
                    class="red trash-link" id="movetotrash"><?php echo $moveToTrash;?></a>
                    <button onClick="$('#savePage').val('publish')" class="btn btn-primary fr"
                     href="#" id="publishBtn"><?php echo $this->translate('Publish'); ?></button>
                     <a class="fr m5" href="<?php echo HTTP_PATH;?>admin/article" 
                     id="publishcancelBtn"><?php echo $this->translate('Cancel'); ?></a>
                    </div>
                    </div>
                    <div class="postbox " id="submitdiv">
                        <div class="sidebar-heading">
                        <p><?php echo $this->translate('Article Attributes');?></p>
                        </div>
                        <div class="sidebar-content-box">
                        <p><?php echo $this->translate('Author'); ?></p>
                        <select id="authorList" name="authorList" onchange="validateAuthor()">
                            <option value=""><?php echo $this->translate('Select Author'); ?></option>
                            <?php
                            foreach($this->authorList as $author){ 
                                $fullName = $author['firstName']." ".$author['lastName'];
                                $fullName = substr($fullName, 0,25);
                                $selectedAuthor = "";
                                if($this->articleData[0]['authorid'] == $author['id']){
                                    $selectedAuthor = "selected=selected";
                                }
                            ?>
                            
                             <option <?php echo $selectedAuthor;?> 
                             value="<?php echo $author['id'];?>" 
                             title="<?php echo $author['firstName']." ".$author['lastName'];?>">
                             <?php echo $fullName; ?>
                             </option> 
                             <?php     }  ?>
                            </select>
                            <input type='hidden' id="authorNameHidden" 
                            name="authorNameHidden" 
                            value="<?php echo $this->articleData[0]['authorname']?>">
                        </div>
                        <div class="mainpage-content-right" style="float:left;margin:-20px 0 6px 50px;"></div>
                    </div>
                    
                    <div class="postbox " id="submitdiv" style="height: 202px;">
                        <div class="sidebar-heading">
                            <p><?php echo $this->translate('Related Categories');?></p>
                        </div>
                        <div class="sidebar-content-box" style="display:inline-block;">
                        <div class="sidebar-content-box-left" style="overflow-y:scroll;height:50px; width:222px;">
                            <ul id="RelatedCategoryListul-li" style='margin: 0;'>
                            <?php 
                            $i=0;
                            $arrayToImplode = array();
                             foreach ($this->articleCategory as $artCategory) {
                                    $class = 'grid-line1';
                                    $class1 = "";
                                    if($i%2 != 0){
                                        $class = 'grid-line2';
                                    }
                                    foreach ($this->articleData[0]['refArticleCategory'] as $relatedCat) {
                                        if($relatedCat['articlecategory']['id'] == $artCategory['id']) {
                                            $class1 = "selected";
                                            $arrayToImplode[] = $relatedCat['articlecategory']['id'];
                                            break;
                                        }
                                    }
                                    echo "<li class='".$class." ".$class1."' 
                                    value=".$artCategory['id']." type=".$i.">"
                                    .ucfirst($artCategory['name'])."</li>";
                                    $i++;
                            }
                            ?>
                             </ul> 
                         <input type="hidden" id="selectedRelatedCategory" 
                         name="selectedRelatedCategory" 
                         value="<?php echo implode(',', $arrayToImplode)?>">
                        </div>
                        </div>
                    </div>
                    
                    <div class="postbox " id="submitdiv" style='height: 254px !important;'>
                        <div class="sidebar-heading">
                            <p><?php echo $this->translate('Related Stores');?></p>
                        </div>
                        <div class="sidebar-content-box" style="display:inline-block;" >
                            <input type="text" id="selectStoreForArticle" 
                            name="selectStoreForArticle" value="" style='width : 225px;'>
                            <div id='storesDiv' class="sidebar-content-box-left" 
                            style="overflow-y:scroll;height:50px;">
                                <ul id="storeListul-li" style='margin: 0;'>
                                <?php 
                                $i=0;
                                $arrayToImplodeStores = array();                            
                                foreach ($this->articleData[0]['storearticles'] as $relatedStores) {
                                    $class = 'grid-line1';
                                    if($i%2 != 0){
                                        $class = 'grid-line2';
                                    }
                                    $arrayToImplodeStores[] = $relatedStores['articleshops']['id'];
                                    echo "<li class=".$class." 
                                    value=".$relatedStores['articleshops']['id']." type=".$i.">"
                                    .ucfirst($relatedStores['articleshops']['name'])."</li>";
                                    $i++;
                                }
                                ?>
                                </ul> 
                            <input type="hidden" id="selectedRelatedStores" name="selectedRelatedStores" 
                            value="<?php echo implode(',', $arrayToImplodeStores)?>">
                            </div>
                            <div class="sidebar-content-box-right">
                                <button type = "button" class="btn addwidget" 
                                href="#"><?php echo $this->translate('Add Store'); ?></button>
                                <button type = "button" class="btn deletewidget" 
                                href="#"><?php echo $this->translate('Delete'); ?></button>
                                <button type = "button" class="btn up" 
                                href="#"><?php echo $this->translate('Move Up');?></button>
                                <button type = "button" class="btn down" 
                                href="#"><?php echo $this->translate('Move Down'); ?></button>
                            </div>
                        </div>
                    </div>

                    <div class="postbox " id="submitdiv" style='height:86px !important;'>
                        <div class="sidebar-heading">
                            <p><?php echo $this->translate('Featured Image(yes/no)');?></p>
                        </div>
                        <div class="sidebar-content-box" style="display:inline-block;" >
                            <div data-toggle="buttons-checkbox" class="btn-group ">
                                <?php
                                $featuredImageStatus = isset($this->articleData[0]['featuredImageStatus']) 
                                   && $this->articleData[0]['featuredImageStatus'] == 1 ? '1' : '0';
                                   $backEndViewHelper = new BackEnd_Helper_viewHelper();
                                echo $featuredImageStatus == 1
                                    ? $backEndViewHelper->getOnOffButtonsForArticleFeaturedImage(1)
                                    : $backEndViewHelper->getOnOffButtonsForArticleFeaturedImage(0);
                                ?>
                                <input type="hidden" value="<?php echo $this->articleData[0]['featuredImageStatus']; ?>" 
                                    name="featuredimagecheckbox" id="featuredimagecheckbox">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="post-body">
                <div id="post-body-content">
                    <div class="mainpage-content">
                            <div class="mainpage-content-line">
                                <div class="mainpage-content-left"><label>
                                <strong><?php echo $this->translate('Article title'); ?></strong>
                                </label>
                                </div>
                                <div class="mainpage-content-right">
                                <input  type="text" value="<?php echo $this->articleData[0]['title']?>" 
                                name="articleTitle" id="articleTitle" class="" 
                                placeholder="<?php echo $this->translate('Article title'); ?>"></div>
                                <div class="mainpage-content-right" style="height : 20px; width : 511px;"></div>
                            </div>
                             
                            <div class="mainpage-content-line">
                                <div class="mainpage-content-left">
                                    <label>
                                        <strong><?php echo $this->translate('Article plus overview title'); ?></strong>
                                    </label>
                                </div>
                                <div class="mainpage-content-right">
                                    <input  type="text" value="<?php echo $this->articleData[0]['plusTitle']?>" 
                                        name="plusTitle" id="plusTitle" class="" 
                                        placeholder="<?php echo $this->translate('Article plus overview title'); ?>">
                                </div>
                                <div class="mainpage-content-right" style="height : 20px; width : 511px;"></div>
                            </div>
                            
                            <div class="mainpage-content-line">
                                <div class="mainpage-content-left"><label>
                                <strong><?php echo $this->translate('Permalink'); ?></strong></label></div>
                                <div class="mainpage-content-right">
                                <div class="mainpage-content-right-inner-left"><label>
                                <?php echo $this->translate('http://www.kortingscode.nl/'); ?>
                                </label></div><div class="mainpage-content-right-inner-right">
                                <input <?php echo ($this->role == '3' || $this->role == '4') ? "disabled=disabled" : "" ;  ?> 
                                type="text" class="span3" name="articlepermalink" id="articlepermalink" 
                                placeholder="<?php echo $this->translate('permalink'); ?>" 
                                value="<?php echo $this->articleData[0]['permalink']?>"></div>
                                <?php if($this->role == '3' || $this->role == '4'):?><input 
                                    value="<?php echo $this->articleData[0]['permalink']?>" type="hidden" 
                                    name="articlepermalink" id="articlepermalink"></div> <?php endif;?>
                                 <div class="mainpage-content-right" 
                                 style="float:left;margin:-9px 0 6px 0; height : 20px; width : 511px;"></div>
                                </div>
                         </div>
                         <div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label>
                            <strong><?php echo $this->translate('Header Image'); ?></strong></label></div>
                            <div class="mainpage-content-right">
                                <?php
                                $articlePicture = '';
                                if(
                                    isset($this->articleData[0]['articleImage']['name']) 
                                    && $this->articleData[0]['articleImage']['name'] != ''
                                ) {
                                    $articlePicture =
                                        PUBLIC_PATH_CDN 
                                        . $this->articleData[0]['articleImage']['path']
                                        . $this->articleData[0]['articleImage']['name'];     
                                }
                             ?>
                                <div class='browse-container'> 
                                     <img class='image-container' 
                                     alt="<?php echo $this->translate('Article ghghlogo'); ?>"
                                     src="<?php echo $articlePicture ; ?>"> 
                                </div>
                                <div>
                                    <input type="file" class="ignore" onchange="checkFileType(event)" 
                                    name="articleImage" id="articleImage">
                                </div>
                                <div>
                                <?php echo $this->translate('Image size: 1170px x 285px (*.jpg or *.png file only)'); ?>
                                </div>
                            </div>
                            <div class="mainpage-content-right" style="float : left; height : 20px; width : 511px;"></div>
                        </div>
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label>
                            <strong><?php echo $this->translate('Thumbnail Small'); ?></strong>
                            </label></div>
                            <div class="mainpage-content-right">
                                <?php
                                $articlePicture = '';
                                if(
                                    isset( $this->articleData[0]['thumbnail']['name'] ) 
                                    && $this->articleData[0]['thumbnail']['name'] != '' 
                                ) {
                                $articlePicture =
                                PUBLIC_PATH_CDN
                                . $this->articleData[0]['thumbnail']['path']
                                . $this->articleData[0]['thumbnail']['name'];
                                }   
                                ?>
                                <div class='browse-container'> 
                                    <img class='image-container'
                                    alt="<?php echo $this->translate('Article Thumbnail Small'); ?>" 
                                    src="<?php echo $articlePicture ; ?>">
                                </div>
                                <div>
                                    <input type="file" class="ignore" onchange="checkFileType(event)" 
                                    name="articleImageSmall" id="articleImageSmall">
                                </div>
                                <div>
                                        <?php echo $this->translate('Image Size: 370px x 300px (*.jpg or *.png file only)');?>
                                </div>
                            </div>
                                <div class="mainpage-content-right" style="float : left; height : 20px; width : 511px;"></div>
                                </div>
                                <div class="mainpage-content-line">
                                    <div class="mainpage-content-left">
                                        <label>
                                            <strong><?php echo $this->translate('Featured in header'); ?></strong>
                                        </label>
                                    </div>
                                    <div class="mainpage-content-right">
                                        <?php 
                                        $articlefeaturedimage = '';
                                        if(
                                            isset( $this->articleData[0]['featuredImage']['name'] ) 
                                            && $this->articleData[0]['featuredImage']['name'] != '' 
                                        ) {
                                        $articlefeaturedimage =
                                            PUBLIC_PATH_CDN
                                            . $this->articleData[0]['featuredImage']['path']
                                            . $this->articleData[0]['featuredImage']['name'];
                                        }   
                                        ?>
                                        <div class='browse-container'> 
                                            <img class='image-container'
                                                alt="<?php echo $this->translate('Article featured image'); ?>" 
                                                src="<?php echo $articlefeaturedimage ; ?>">
                                        </div>
                                        <div>
                                            <input type="file" class="ignore" onchange="checkFileType(event)" 
                                                name="articleFeaturedImage" id="articleFeaturedImage">
                                        </div>
                                        <div>
                                            <?php echo $this->translate('Image Size: 553px x 448px (*.jpg or *.png file only)');?>
                                        </div>
                                    </div>
                                    <div class="mainpage-content-right" style="float : left; height : 20px; width : 511px;"></div>
                                </div>
                                <div class="mainpage-content-line" style='display: inline-block;'>
                                        <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Meta title'); ?></strong></label></div>
                                        <div class="mainpage-content-right">
                                        
                                        <input type="text" id="articlemetaTitle" 
                                        name="articlemetaTitle" value="<?php echo $this->articleData[0]['metatitle']?>"
                                         placeholder="<?php echo $this->translate('Meta title');?>" class="input-xlarge mbot bbot ignore">
                                         <span id="metaTextLeft" class="disabled btop word-count nobel wordcount-width"></span>
                                </div>
                             </div>
                            <div class="mainpage-content-line">
                                <div class="mainpage-content-left"><label>
                                <strong><?php echo $this->translate('Meta Description'); ?></strong></label></div>
                                <div class="mainpage-content-right">
                                    <textarea class="input-xlarge mbot bbot ignore" 
                                    id="articlemetaDesc" name="articlemetaDesc" 
                                    placeholder="<?php echo $this->translate ( 'Meta Description' );?>" 
                                    rows="3"><?php echo trim($this->articleData[0]['metadescription']);?></textarea>
                                    <span id="metaDescriptionleft" class="disabled btop word-count nobel wordcount-width"></span>
                                </div>
                                <div class="mainpage-content-left"><label>
                                <strong><?php echo $this->translate('Introduction'); ?></strong></label></div>
                                <div class="mainpage-content-right">
                                    <textarea class="input-xlarge" 
                                    name="pageDesc" id="articlemetaDesc" 
                                    placeholder="<?php echo $this->translate('page Content'); ?>" 
                                    rows="3"><?php echo trim($this->articleData[0]['content']); ?></textarea>
                                </div>  
                                </div>
                            </div>
                        </div>
                <br>
                <div id="offerconstraint" class="display-none"> 
                
                    <div class="mainpage-content">
                    <div class="mainpage-content-line">
                        <div class="mainpage-content-left"><label>
                        <strong><?php echo $this->translate('Maximum Offers on Page'); ?></strong></label></div>
                        <div class="mainpage-content-right"><input type="text" 
                        name="maxOffer" id="maxOffer" class="span3" 
                        placeholder="<?php echo $this->translate('Maximum Offer'); ?>"></div>
                        </div>
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label>
                            <strong><?php echo $this->translate('Offers Order'); ?></strong></label></div>
                            <div class="btn-group" data-toggle="buttons-checkbox">
                                <button type="button" onClick="setOffersOrder('ascendingOffer')" 
                                id="ascendingOffer" class="btn btn-primary">ascending</button>                     
                                <button type="button" onClick="setOffersOrder('decendingOffer')" 
                                id="decendingOffer" class="btn">decending</button>
                                <input type="checkbox" id="offersOrderchk" value="1" 
                                name="offersOrderchk" checked="checked" class="display-none">
                            </div>
                        </div>
                    </div>
                    <div class="edit-page-box-new">
                        <div class="mainpage-content-line">
                            <label class="checkbox">
                                <input type="checkbox" value="1" onClick="constraint(event,'time')" 
                                id="timeCostraintchk" name="timeCostraintchk"> 
                                <strong><?php echo $this->translate('Enable time contstraint');?></strong>
                            </label>
                            <div class="line"></div>
                            <div class="edit-page-feilds display-none" id="showTimeConstraint">
                                <div class="fl">
                                <select id="postwithin" name="postwithin">
                                    <option value="1"><?php echo $this->translate('Posted within'); ?></option>
                                    <option value="2"><?php echo $this->translate('Expires in'); ?></option>
                                     </select>
                                    </div>
                                    <div class="fl ml15">
                                      <input type="text" id="numberofDays" name="numberofDays"  
                                      class="span1 ml15" placeholder="10">                                   
                                    </div>
                                    <div class="fl ml15">                                  
                                        <p class="mr15"><?php echo $this->translate('Days'); ?></p>
                                    </div>
                            </div>
                            </div>
                            
                            </div>
                            <div class="edit-page-box-new">
                                <div class="mainpage-content-line">
                                <label class="checkbox">
                                    <input type="checkbox" value="1" onClick="constraint(event,'word')" 
                                    id="wordCostraintchk" name="wordCostraintchk"> 
                                    <strong><?php echo $this->translate('Word constraint'); ?></strong>
                                </label>
                                <div class="line"></div>
                                <div class="edit-page-feilds display-none" id="wordConstraint">
                                    <div class="fl mr15">
                                        <input type="text" id="wordConstraintTxt" 
                                        name = "wordConstraintTxt" class="span5" 
                                        placeholder="<?php echo $this->translate('Word constraint'); ?>"> 
                                    </div>                                
                                 </div>
                                </div>                        
                            </div>
                            
                            <div class="edit-page-box-new">
                                <div class="mainpage-content-line">
                                        <label class="checkbox">
                                            <input type="checkbox" value="1" 
                                            onClick="constraint(event,'award')" id="awardCostraintchk" 
                                            name="awardCostraintchk" > 
                                            <strong><?php echo $this->translate('Awards');?></strong>
                                        </label>
                                        <div class="line"></div>
                                <div class="edit-page-feilds display-none" id="awardConstraint">
                                <div class="fl mr15">
                                    <select id="select02" id="awardConstraintDropdown" name="awardConstraintDropdown">
                                        <option value="1">
                                        <?php echo $this->translate('Free shipping'); ?>
                                        </option>
                                        <option value="2">
                                        <?php echo $this->translate('Order today,delivred tomorrow'); ?>
                                        </option>
                                    </select>                                        
                                </div>                                
                                </div>
                                </div>                        
                            </div>

                            <div class="edit-page-box-new">
                                <div class="mainpage-content-line">
                                    <label class="checkbox">
                                    <input type="checkbox" value="1" 
                                    onClick="constraint(event,'clicks')" 
                                    id="clickCostraintchk" name="clickCostraintchk"> 
                                    <strong><?php echo $this->translate('Clickouts'); ?></strong>
                                    </label>
                                <div class="line"></div>
                                <div class="edit-page-feilds display-none" id="clickConstraint">
                                    <div class="fl mr15">
                                    <input id="clickConstraintTxt" name="clickConstraintTxt" 
                                    type="text" class="span3" 
                                    placeholder="<?php echo $this->translate('Clickouts'); ?>"> 
                                    </div>
                                    <div class="fl">
                                            <p class="mr15"><?php echo $this->translate('Of clickouts'); ?></p>
                                    </div>                                
                                 </div>
                                </div>                        
                            </div>
                            <div class="mainpage-content">
                                <strong><?php echo $this->translate('Show offer types'); ?></strong>                               
                                <div class="line"></div>
                                <div class="mainpage-content-line mb10">
                                <div class="mainpage-content-left"><label>
                                <strong><?php echo $this->translate('Coupon'); ?></strong></label></div>
                                <div class="mainpage-content-right">
                                <div class="btn-group" data-toggle="buttons-checkbox">
                                    <button id="regularCoupon" onClick="offerType('regularCoupon','coupon','regular')" 
                                    type = "button" class="btn"><?php echo $this->translate('Regular');?></button>                     
                                    <button id="editorPickCoupon" onClick="offerType('editorPickCoupon','coupon','editor')" 
                                    type = "button" class="btn"><?php echo $this->translate('Editors pick'); ?></button>
                                    <button id="exclusiveCoupon" onClick="offerType('exclusiveCoupon','coupon','exclusive')" 
                                    type = "button" class="btn"><?php echo $this->translate('Exlusive'); ?></button>
                                </div>
                                    <input type="checkbox" id="coupconCoderegularchk" 
                                    name="coupconCoderegularchk" value="1" class="display-none"> 
                                    <input type="checkbox" id="coupconCodeeditorchk" 
                                    name="coupconCodeeditorchk" value="1" class="display-none"> 
                                    <input type="checkbox" id="coupconCodeeclusivechk" 
                                    name="coupconCodeeclusivechk" value="1" class="display-none"> 
                                </div>
                                </div>
                                <div class="mainpage-content-line mb10">
                                    <div class="mainpage-content-left"><label>
                                    <strong><?php echo $this->translate('Sale'); ?></strong></label></div>
                                    <div class="mainpage-content-right">
                                    <div class="btn-group" data-toggle="buttons-checkbox">
                                        <button id="regularSale" type = "button" 
                                        onClick="offerType('regularSale','sale','regular')" 
                                        class="btn"><?php echo $this->translate('Regular'); ?></button>                     
                                        <button id="editorPickSale" type = "button" 
                                        onClick="offerType('editorPickSale','sale','editor')" 
                                        class="btn"><?php echo $this->translate('Editors pick'); ?></button>
                                        <button id="exclusiveSale" type = "button" 
                                        onClick="offerType('exclusiveSale','sale','exclusive')" 
                                        class="btn"><?php echo $this->translate('Exlusive'); ?></button>
                                    </div>
                                     <input type="checkbox" id="saleregularchk" 
                                     name="saleregularchk" value="1" class="display-none"> 
                                     <input type="checkbox" id="saleeditorchk" 
                                     name="saleeditorchk" value="1" class="display-none"> 
                                     <input type="checkbox" id="saleeclusivechk" 
                                     name="saleeclusivechk" value="1" class="display-none">
                                    </div>
                                </div>
                                 <div class="mainpage-content-line mb10">
                                    <div class="mainpage-content-left"><label>
                                    <strong><?php echo $this->translate('Printable'); ?></strong></label></div>
                                    <div class="mainpage-content-right">
                                    <div class="btn-group" data-toggle="buttons-checkbox">
                                        <button id="regularPrintable" type = "button" 
                                        onClick="offerType('regularPrintable','printable','regular')" 
                                        class="btn"><?php echo $this->translate('Regular');?></button>                     
                                        <button id="editorPickPrintable" type = "button" 
                                        onClick="offerType('editorPickPrintable','printable','editor')" 
                                        class="btn"><?php echo $this->translate('Editors pick'); ?></button>
                                        <button id="exclusivePrintable" type = "button" 
                                        onClick="offerType('exclusivePrintable','printable','exclusive')" 
                                        class="btn"><?php echo $this->translate('Exlusive');?></button>
                                    </div>
                                         <input type="checkbox" id="printableregularchk" name="printableregularchk" 
                                         value="1" class="display-none"> 
                                         <input type="checkbox" id="printableeditorchk" name="printableeditorchk" 
                                         value="1" class="display-none"> 
                                         <input type="checkbox" id="printableexclusivechk" name="printableexclusivechk" 
                                         value="1" class="display-none">
                                    </div>
                                </div>                        
                        </div>
                    <div style="height:28px;" class="mainpage-content">
                        <div class="mainpage-content-line m10">
                            <div class="fl">
                                <strong><?php echo $this->translate('Show as page when creating offers?'); ?></strong>
                            </div>
                            <label class="checkbox fl ml15">
                            <input type="radio" name="showPage" value = "1"> <?php echo $this->translate('yes'); ?>
                            </label>
                            <label class="checkbox fl ml15">
                            <input type="radio" 
                            name="showPage" value = "0" 
                            checked="checked"> <?php echo $this->translate('No'); ?>
                            </label>                           
                        </div>                        
                    </div>
                </div>   
                <div id="post-body-content">                         
            <div class="mainpage-content">
            <div class="mainpage-content-line mb10">
                <div class="mainpage-content-left">
                    <h3>
                        <strong><?php echo $this->translate('Chapters'); ?></strong>
                    </h3>
                </div>
                <div class="mainpage-content-right">&nbsp;</div>
            </div>
                    
            <div id="multidiv" >   
            <?php echo $this->partialLoop('article/chapters.phtml',$this->articleData[0]['articleChapter']);?>
            </div>
            <div class="mainpage-content-colorbox">
                <a href="javascript:;" style="float:right;margin-top: 7px;" 
                onclick="getchapterhtml(this);" rel="<?php echo count($this->articleData[0]['articleChapter']) ?>"><strong>
                <?php echo $this->translate('+ Add another chapter'); ?></strong></a>
            </div>
            <div class="clear"></div>
        </div> 
        </div>                                    
        </div>
    </div>
    <input type="hidden" name="pageId" id="pageId" value="<?php echo $this->articleData[0]['id'];?>" >
    <input type="hidden" name="isEdit" id="isEdit" value="1" >
    </form>  
    <br class="clear">
</div>