<?php 

 $this->headTitle()->append($this->translate('Affiliate Network'));
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.validate.js");
 $this->headScript ()->appendFile ( PUBLIC_PATH . "/js/back_end/addAffiliate.js" );

?>

<!-- start add affiliate network -->
<div class="wrap columns-2" id="affiliateNetworkadd" >
  <form id="addnewaffiliateNetwork" name="addnewaffiliateNetwork" method="POST" action="<?php echo HTTP_PATH ;?>admin/affiliate/addaffiliate" enctype="multipart/form-data"> 
       
          <h1><?php echo $this->translate('Create network'); ?>
          <input type="button" class="btn ml10" onClick="window.location.href='<?php echo HTTP_PATH; ?>admin/affiliate'" Value='<?php echo $this->translate('Cancel'); ?>'/>
          </h1>
         	
            <div class="metabox-holder has-right-sidebar" id="poststuff">
              <div id="post-body">
              	<div>
              		<div class="mainpage-content">
                    	<div class="mainpage-content-line">
                            <div class="mainpage-content-left">
                            <label><strong><?php echo $this->translate('Name'); ?></strong></label>
                            </div>
                            <div class="mainpage-content-right">
                                <div class="mainpage-content-right-inner-right-other"></div>
                                <div class="mainpage-content-right-inner-left-other">
                                <input type="text" class="span3" placeholder="<?php echo $this->translate('Name');?>" name="addNetworkText" >
                                </div>                        
                            </div>
                        </div>
                        <div class="mainpage-content-line warningContainer">
                            <div class="mainpage-content-right">
                            <div class="mainpage-content-right-inner-left-other">
                                <div class="alert-custom">
                                    <div class="alert-custom-wrapper">
                                        <strong><?php echo $this->translate('Warning!');?></strong>&nbsp;<?php echo $this->translate("The subid and client id should be added correctly! For eg. for Zanox network it should be like: zpar0=[[A2ASUBID]]&zpar1=[[GOOGLEANALYTICSTRACKINCID]]");?><br>
                                        <?php echo $this->translate("If not implemented correctly then it might break the whole system!");?><br><br>
                                        <?php echo $this->translate("Subid should be A2ASUBID");?><br>
                                        <?php echo $this->translate("Clientid should be GOOGLEANALYTICSTRACKINCID");?><br>
                                        <?php echo $this->translate("For the regex pattern to work for subid it should be added like: regexPattern|_A2ASUBID-GOOGLEANALYTICSTRACKINCID");?>
                                        <br>
                                        <?php echo "Note: regexPattern can be like \_(?=[^_]*$)";?>
                                    </div> 
                                </div>    
                            </div>    
                            </div>
                        </div>
                    	<div class="mainpage-content-line">
                            <div class="mainpage-content-left">
                            <label><strong><?php echo $this->translate('Network Subid'); ?></strong></label>
                            </div>
                            <div class="mainpage-content-right">
                                <div class="mainpage-content-right-inner-right-other"></div>
                                <div class="mainpage-content-right-inner-left-other">
                                <input type="text" class="span3 ignore" placeholder="<?php echo $this->translate('Subid');?>" name="subId" >
                                </div>                        
                            </div>
                        </div>
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left">
                            <label><strong><?php echo $this->translate('backend_Extended Subid'); ?></strong></label>
                            </div>
                            <div class="mainpage-content-right">
                                <div class="mainpage-content-right-inner-right-other"></div>
                                <div class="mainpage-content-right-inner-left-other">
                                <input type="text" class="span3 ignore" placeholder="<?php echo $this->translate('backend_Extended Network Subid');?>" name="extendedSubid" >
                                </div>                        
                            </div>
                        </div>
                    </div>
                </div>
              </div>
              <br class="clear">
            </div>
            <div class="mainpage-content-colorbox">
            	<button id='addNetwork' type="submit" class="btn btn-large btn-primary fl">
            	<?php echo $this->translate('CREATE NETWORK'); ?>
            	</button>
                <a class="fl m10" href="<?php echo HTTP_PATH; ?>admin/affiliate" >
                <strong><?php echo $this->translate('CANCEL'); ?></strong>
                </a>
           </div>
   </form> 
 </div>