<?php 

 $this->headTitle()->append($this->translate('Affiliate Network'));
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.validate.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
 $this->headLink ()->appendStylesheet ( PUBLIC_PATH . "/css/jquery-ui-1.8.16.custom.css" );
 $this->headScript ()->appendFile ( PUBLIC_PATH . "/js/back_end/editAffiliate.js" );
 
?>
<div class="wrap columns-2" id="editaffiliateNetwork">
      <form action="<?php echo HTTP_PATH ;?>admin/affiliate/editaffiliate" method="POST" name='updateNetworkForm'  id="updateNetworkForm" enctype=multipart/form-data>
      
      <input type="hidden" value="<?php echo $this->editNetwork[0]['id'];?>" name='id' id='id' />
      
          <h1><?php echo $this->translate('Edit network'); ?>
          <input type="button" class="btn ml10" onClick="window.location.href='<?php echo HTTP_PATH; ?>admin/affiliate'" Value='<?php echo $this->translate('Cancel'); ?>'/>
          </h1>
         	<div class="metabox-holder has-right-sidebar" id="poststuff">
              <div id="post-body">
              	<div>
              	<div class = "customError mainpage-content" style ="color: #B94A48; line-height: 25px; padding-top: 2px; display : none;">Please fill atleast one of the fields below</div>
              		<div class="mainpage-content">
                    	<div class="mainpage-content-line">
                            <div class="mainpage-content-left">
                            <label>
                            <strong><?php echo $this->translate('Name'); ?></strong>
                            </label>
                            </div>
                            <div class="mainpage-content-right">
                                <div class="mainpage-content-right-inner-right-other"></div>
                                <div class="mainpage-content-right-inner-left-other" id="msg">
                                <input type="text" class="span3" placeholder="<?php echo $this->translate('Edit Name');?>" name="addNetworkText" id="addNetworkText" value="<?php echo $this->editNetwork[0]['name']; ?>">
                                </div>                        
                            </div>
                        </div>
						<div class="mainpage-content-line warningContainer hide">
                            <div class="mainpage-content-right">
                            	<div class="mainpage-content-right-inner-left-other">
                            	    <div class="alert-custom">
                                        <div class="alert-custom-wrapper">
    									    <strong><?php echo $this->translate('Warning!');?></strong>&nbsp;<?php echo $this->translate("The subid and client id will change all the clickout urls of this network! Only make changes if you know what you are doing!");?><br><br>
                                            <?php echo $this->translate("Subid should be A2ASUBID");?><br>
                                            <?php echo $this->translate("Clientid should be GOOGLEANALYTICSTRACKINCID");?><br>
                                            <?php echo $this->translate("For eg. for Zanox network it should be like: zpar0=[[A2ASUBID]]&zpar1=[[GOOGLEANALYTICSTRACKINCID]]");?><br>
                                            <?php echo $this->translate("For the regex pattern to work for subid it should be added like: regexPattern|_A2ASUBID-GOOGLEANALYTICSTRACKINCID");?>
                                            <br>
                                            <?php echo "Note: regexPattern can be like \_(?=[^_]*$)";?>
    								    </div>     
                                    </div>
								</div>    
                            </div>
                        </div>
                        
						<div class="mainpage-content-line">
                            <div class="mainpage-content-left">
                            <label><strong><?php echo $this->translate('Network Subid'); ?></strong></label>
                            </div>
                            <div class="mainpage-content-right">
                            	<div class="mainpage-content-right-inner-left">
                            		<a class="eidt-subid-lnk subidEdit-lnk" href="javascript:void(0);" onclick="editSubid();" ><?php echo $this->translate('Edit');?></a>
                            		<a class="eidt-subid-lnk subidCancel-lnk" style="display:none;" href="javascript:void(0);" onclick="cancelEdidSubid();" ><?php echo $this->translate('Cancel edit');?></a>
                            		</div>
                                <div class="mainpage-content-right-inner-right-other"></div>
                               <div class="mainpage-content-right-inner-right-small">
                                <input type="text" disabled="disabled" class="span3" placeholder="<?php echo $this->translate('Subid');?>" name="subId" value="<?php echo $this->editNetwork[0]['subId']; ?>">
                                </div>                        
                            </div>
                        </div>
                    </div>
                    <div class="mainpage-content">
                    	<div class="mainpage-content-line">
                            <div class="mainpage-content-left">
                            <label>
                            <strong><?php echo $this->translate('Replace with'); ?></strong>
                            </label>
                            </div>
                            <div class="mainpage-content-right">
                                <div class="mainpage-content-right-inner-right-other"></div>
                                <div class="mainpage-content-right-inner-left-other">
                                   <select class="mainpage-content-right-select" id="selectNetworkList" name="selectNetworkList"> 
                                   <option value="">Select</option>
                                   <?php for($n=0;$n<count($this->getNetworkdropdown);$n++){?>
                                    <option value="<?php echo $this->getNetworkdropdown[$n]['id']; ?>"><?php echo $this->getNetworkdropdown[$n]['name']; ?></option>
                                   <?php }?>
                                   </select>
                              </div>
                          </div>
                        </div>
                    </div>
                </div>
              </div>
              <br class="clear">
            </div>
           <div class="mainpage-content-colorbox">
             <input type="hidden" id="networkUpdatedId" value="<?php echo $this->editNetwork[0]['id'];?>" name="networkUpdatedId">
            	<button type="submit" id="updatenetrecord" class="btn btn-large btn-primary fl"> 
            	<?php echo $this->translate('UPDATE NETWORK'); ?>
            	</button>
                 <a class="fl m10" href="<?php echo HTTP_PATH; ?>admin/affiliate" >
                 <strong><?php echo $this->translate('CANCEL'); ?></strong>
                 </a>
          <a id="deleteButton" class="fl red mt10" href="javascript:void(0);"  onclick="deleteNetworkByEdit();"><strong>
           <?php echo $this->translate('DELETE'); ?></strong>
           </a>
            </div>
            <!-- /poststuff -->
   </form>
</div>