<script>
(function(){
	var qs,js,q,s,d=document,gi=d.getElementById,ce=d.createElement,gt=d.getElementsByTagName,id='typef_orm',b='/public/js/front_end/',bb='/public/css/front_end/';
	if(!gi.call(d,id)){
		js=ce.call(d,'script');js.id=id;
		js.src=b+'share.js';q=gt.call(d,'script')[0];
		q.parentNode.insertBefore(js,q)
	}
	id=id+'_';
	if(!gi.call(d,id)){
		qs=ce.call(d,'link');
		qs.rel='stylesheet';
		qs.id=id;qs.href=bb+'share-button.css';
		s=gt.call(d,'head')[0];s.appendChild(qs,s)
	}
})()</script>