<div class="block">
<?php
$currentControllerName = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
if($currentControllerName!='store') {
    ?>
    <h2 class = "popular-store-title"><?php echo $this->translate('Popular stores'); ?></h2>
    <?php
}
?>
    <ul class="shops">
<?php

$popularStoreIncrementCheck = 1;
foreach ($this->popularStores as $popularStore) :
    $popularStoreIncrementCheck++;
    if ($popularStoreIncrementCheck == 8) :
        break;
    endif;

    if (count($popularStore['popularshops']['logo']) > 0) :
        $popularStoreImage =
    		PUBLIC_PATH_CDN
    		.ltrim($popularStore['popularshops']['logo']['path'], "/")
    		."thum_medium_".$popularStore['popularshops']['logo']['name'];
    else :
        $popularStoreImage = HTTP_PATH . "public/images/NoImage/storeLogo100_50.jpg";
    endif;

    echo '<li>
        <a href="'.HTTP_PATH_LOCALE.$popularStore['popularshops']['permaLink'].'">
            <img src="' . $popularStoreImage . '"  
            alt="' .$popularStore['popularshops']['name'] . '" title="' .$popularStore['popularshops']['name'] . '" />
        </a>
    </li>';
endforeach;
?>
    </ul>
</div>