<?php
echo $this->shopEditor;
if (!empty($this->latestShopUpdates)):?>
    <?php echo $this->partial('store/_latestNews.phtml', array('latestShopUpdates' => $this->latestShopUpdates));
endif;
$frontendSidebarHelper = new FrontEnd_Helper_SidebarWidgetFunctions();
if ($this->shopChain):
    ?>
        <article class="block">
    <?php echo $this->shopChain; ?>
        </article>
    <?php
endif;
        
if(isset($this->popularStoresList)):
    echo $this->popularStoresList;
endif;
$shopsAlsoViewed = $frontendSidebarHelper->shopsAlsoViewedWidget($this->shop['id'], $this->shop['name']);
if (!empty($shopsAlsoViewed)) {
	echo $shopsAlsoViewed;
}	