<?php
$pageHeader = new FrontEnd_Helper_PageHeaderPartialFunctions();
echo $pageHeader->getCategoryOrPageHeader(
    $this->pageTitle,
    $pageHeader->getCategoryOrPageHeaderImage($this->pageHeaderImage)
);
$storeViewPath = 'store/';
$popularStores = '';
if (count($this->popularStores)) :
     $popularStores = $this->partial(
         $storeViewPath.'_popular-stores.phtml',
         array('popularStores' => $this->popularStores)
     );
endif;

$storesInformation = '';
if ($this->storesInformation != '' && $this->storesInformation != null) :
    $storesInformation = $this->partial(
        $storeViewPath.'_all-stores-listing.phtml',
        array('storesInformation' => $this->storesInformation)
    );
endif;

$allSearchAlphabetPanel = $this->partial(
    $storeViewPath.'_all-stores-searchalphabet.phtml',
    array('selectedAlphabet' => $this->selectedAlphabet)
);

?>
<div class="row">
    <div id="content" class="col-md-8 col-sm-8">
        <div class="content-holder">            
        <?php 
        echo  preg_replace('~>\\s+<~m', '><', $allSearchAlphabetPanel);
        echo $popularStores;
        echo $storesInformation;
        ?>
        </div>
    </div>
    <aside id="sidebar" class="col-md-4 col-sm-4 col-sm-4">
    <?php
    $this->locale = LOCALE != 'en' ? LOCALE . '/' : '';
    $frontendSidebarHelper = new FrontEnd_Helper_SidebarWidgetFunctions();
    echo $frontendSidebarHelper->sidebarWidgets('all-shop-page', $this);
    ?>
    </aside>
</div>