<?php
  $this->headTitle()->append($this->translate('Create Category'));
  $this->headScript ()->appendFile ( PUBLIC_PATH . "/js/back_end/jquery.validate.js" );
  $this->headScript ()->appendFile ( PUBLIC_PATH . "/js/back_end/addCategory.js" );
  //$this->headScript ()->appendFile ( PUBLIC_PATH . "/js/back_end/jquery.textareaCounter.plugin.js");
  $this->headScript ()->appendFile ( PUBLIC_PATH . "/js/jquery.NobleCount.js");
  $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/category-common.js");

?>
<div class="wrap columns-2" id="createCategory">
	<form action="<?php echo HTTP_PATH ;?>admin/category/addcategory" method="POST" id="saveCategoryForm" name="saveCategoryForm" enctype="multipart/form-data">
	<input type="hidden" value="" name='iconId' id='iconId' />
	<input type="hidden" value="" name='id' id='id' />
	<input type="hidden" name="featuredCategory" id="featuredCategory" value="0" />
		<h1><?php echo $this->translate('Create Category'); ?><input type="button"  Value='<?php echo $this->translate('Cancel'); ?>' class="btn ml10" onClick="window.location.href='<?php echo HTTP_PATH; ?>admin/category'" /></h1>

		<div id="poststuff" class="metabox-holder has-right-sidebar">
			<div id="post-body">
				<div>
					<div class="mainpage-content">

						<div class="mainpage-content-line">
							<div class="mainpage-content-left">
								<label><strong><?php echo $this->translate('Title'); ?></strong></label>
							</div>
							<div class="mainpage-content-right">
								<div class="mainpage-content-right-inner-right-other"></div>
								<div class="mainpage-content-right-inner-left-other">
									<input type="text" name="categoryName"
										placeholder="<?php echo  $this->translate ( 'Title' );?>"
										class="span3" />
								</div>
							</div>
						</div>
						<div class="mainpage-content-line">
							<div class="mainpage-content-left">
								<label><strong><?php echo $this->translate('Permalink'); ?></strong></label>
							</div>
							<div class="mainpage-content-right">
								<div class="mainpage-content-right-inner-left">
									<label><?php echo $this->translate('http://www.kortingscode.nl/categorieen/'); ?></label>
								</div>
								<div class="mainpage-content-right-inner-right-other"></div>
								<div class="mainpage-content-right-inner-right-full">
									<input type="text" name="permaLink" id="permaLink" placeholder="centerparks" class="span3">
								</div>
							</div>
						</div>
						<div class="mainpage-content-line">
							<div class="mainpage-content-left">
								<label><strong><?php echo $this->translate('Meta title'); ?></strong></label>
							</div>
							<div class="mainpage-content-right">
								<div class="mainpage-content-right-inner-right-other"></div>
								<div class="mainpage-content-right-inner-left-other">
								<input type="text" name="metaTitle" id="metaTitle" placeholder="<?php echo $this->translate('Meta title');?>" class="input-xlarge mbot bbot ignore"/>
								<span id="metaTextLeft" class="nobel"></span>
								</div>
							</div>
						</div>
					   <div class="mainpage-content-line">
							<div class="mainpage-content-left">
								<label> <strong>
	                            	<?php echo $this->translate ( 'Meta Description' );?>
	                            </strong></label>
							</div>
							<div class="mainpage-content-right">
								<div class="mainpage-content-right-inner-right-other"></div>
								<div class="mainpage-content-right-inner-left-other">
								
								<textarea class="input-xlarge mbot bbot ignore" id="metaDescription" name="metaDescription" placeholder="<?php echo $this->translate ( 'Meta Description' );?>" rows="3"></textarea>
								<span id="metaDescriptionleft" class="nobel"></span>
								
								<!--<textarea class="input-xlarge mbot bbot ignore word_count" name="metaDescription" id="metaDescription" placeholder="<?php //echo $this->translate ( 'Meta Description' );?>" rows="3"></textarea>-->
									<!--<input type="text" class="input-xlarge disabled btop word-count"  id="metaDescription_count" disabled="disabled">-->
								
							
								    
								</div>
							</div>
						</div>
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left">
                                <label>
                                	<strong><?php echo $this->translate('Category Thumbnail'); ?></strong>
                                </label>
                            </div>
                            <div class="mainpage-content-right control-group">
                            	<div class="mainpage-content-right-inner-left-other">
                                    <input class="span3 ignore" data-max-size="2097152" 
                                    onchange="checkFileType(event)" type="file" 
                                    name="categoryIconNameHidden">
                                </div>
                                <div class="upload category-image">
                                <?php echo $this->translate('Image Size: 175px x 175px (*.jpg or *.png file only)'); ?>
                                </div>
                            </div>
                        </div>
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left">
                                <label>
                                	<strong><?php echo $this->translate('Category Featured Image'); ?></strong>
                                </label>
                            </div>
                            <div class="mainpage-content-right control-group">
                             	<div class="mainpage-content-right-inner-left-other">
                                    <input class="span3 ignore" data-max-size="2097152" 
                                    onchange="checkFileType(event)" type="file" 
                                    name="categoryFeaturedImage">
                                </div>
                                <div class="upload category-image">
                                <?php echo $this->translate('Image Size: 367px x 367px (*.jpg or *.png file only)'); ?>
                                </div>
                            </div>
                        </div>
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left">
                                <label>
                                	<strong><?php echo $this->translate('Category Header Image'); ?></strong>
                                </label>
                            </div>
                            <div class="mainpage-content-right control-group">
                             	<div class="mainpage-content-right-inner-left-other">
                                	<input class="span3 ignore" data-max-size="2097152" 
                                	onchange="checkFileType(event)" type="file" 
                                	name="categoryHeaderImage">
                                </div>
                                <div class="upload category-image">
                                <?php echo $this->translate('Image Size: 1170px x 304px (*.jpg or *.png file only)'); ?>
                                </div>
                            </div>
                        </div>
						<div class="mainpage-content-line">
							<div class="mainpage-content-left">
								<label><strong><?php echo $this->translate('Description')?></strong></label>
							</div>
							<div class="mainpage-content-right">
								<div class="mainpage-content-right-inner-right-other"></div>
								<div class="mainpage-content-right-inner-left-other">
								
								<!--<textarea rows="3" name="description"
										placeholder="<?php //echo $this->translate('Description')?>"
										id="description" class="input-xlarge mbot bbot ignore"></textarea>
										<input maxlength="500" type="text" class="input-xlarge disabled btop word-count"  id="descriptionLeft" value = "Characters Left: 500" disabled="disabled">-->
										
							<textarea rows="3" id="description" name="description" placeholder="<?php echo $this->translate('Description')?>" class="input-xlarge mbot bbot ignore word_count"></textarea>
							<input type="text" class="input-xlarge disabled btop word-count"  id="description_count" disabled="disabled">
								</div>
							</div>
						</div>
                        <div class="mainpage-content-line mb10">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Featured category'); ?></strong></label></div>
                                <div class="mainpage-content-right">
                                    <div class="btn-group" data-toggle="buttons-checkbox">
                                    <button onclick="setOnOff(event,'featured-category','on');" class="btn" type="button"><?php echo $this->translate('Yes'); ?></button>                     
                                    <button onclick="setOnOff(event,'featured-category','off');" class="btn btn-primary default" type="button"><?php echo $this->translate('No'); ?></button> 
                                </div>
                            </div>
                        </div>

					</div>

				</div>
			</div>
			<br class="clear">
		</div>
		<div class="mainpage-content-colorbox">
			<button id='saveCategory' type="submit" class="btn btn-large btn-primary fl">
            		<?php echo $this->translate('CREATE CATEGORY')?>
            	</button>
			<a href="<?php echo HTTP_PATH; ?>admin/category" class="fl m10"
				id="cancelCategory"> <strong><?php echo $this->translate('CANCEL')?></strong></a>
		</div>
		<!-- /poststuff -->
	</form>
</div>