<?php 
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");	
$this->headScript()->appendFile(PUBLIC_PATH  . "/js/back_end/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/edit-media.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/jquery.textareaCounter.plugin.js");

?>
<?php echo $this->headTitle()->append('Edit Media');?>
<div class="wrap columns-2">
<h1><?php echo $this->translate('Edit Media');?><a href="<?php echo HTTP_PATH.'admin/media#'.$this->qstring;?>"><button class="btn ml10"><?php echo $this->translate('Cancel');?></button></a></h1>
   <form method="POST" name="editMediaForm" id="editMediaForm">
   <input type="hidden" name='qString' id='qString' value='<?php echo $this->qstring; ?>' />
<div id="poststuff" class="metabox-holder has-right-sidebar">
<div id="post-body">
<div>
<div class="mainpage-content">
		<div class="mainpage-content-line mb10">
			<div class="mainpage-content-left"><label><strong></strong></label></div>
			<div class="mainpage-content-right"><img src="<?php echo PUBLIC_PATH_LOCALE.'images/upload/media/thumb/'.$this->data['fileurl'];?>" border="0"></div>
		</div>
		<div class="mainpage-content-line">
			<div class="mainpage-content-left"><label><strong><?php echo $this->translate('Title:');?></strong></label></div>
			<div class="mainpage-content-right">
				 <div class="mainpage-content-right-inner-right-other"></div>
				<div class="mainpage-content-right-inner-left-other">
				<input name="name" id="name" value="<?php echo $this->data['name'];?>" type="text" placeholder="Title.." class="span3">
				</div>
			</div>
		</div>
		<div class="mainpage-content-line">
			<div class="mainpage-content-left"><label><strong><?php echo $this->translate('Alternate text:');?></strong></label></div>
			<div class="mainpage-content-right">
			  <div class="mainpage-content-right-inner-right-other"></div>
			<div class="mainpage-content-right-inner-left-other">
			<input name="alternateText" id="alternateText" value="<?php echo $this->data['alternatetext'];?>" type="text" placeholder="Alternate text.." class="span3">
			</div>
			</div>
		</div>
		<div class="mainpage-content-line mt10">
			<div class="mainpage-content-left"><label><strong><?php echo $this->translate('File URL:');?></strong></label></div>
			<div class="mainpage-content-right">
			<div class="mainpage-content-right-inner-left-other">
				<?php
					$httpScheme = FrontEnd_Helper_viewHelper::getServerNameScheme();
					$siteUrl = LOCALE != '' ? 'http://'.$httpScheme.'.flipit.com/' : 'http://'.$httpScheme.'.kortingscode.nl/';
					$locale = LOCALE == '' ? '' : LOCALE.'/';
				?>
			<input name="fileUrl" readonly type="text" placeholder="" class="span3" value="<?php echo $siteUrl .'public/'.$locale.'images/upload/media/'.$this->data['fileurl'];?>">
			</div>
			</div>
		</div>
		<div class="mainpage-content-line mb10">
			<div class="mainpage-content-left"><label><strong>&nbsp;</strong></label></div>
			<div class="mainpage-content-right">
			<input type="hidden" name="hId" id="hId" value="<?php echo $this->id;?>">
			<button type="submit" class="btn btn-large btn-primary"><?php echo $this->translate('SAVE');?></button>
			<a href="<?php echo HTTP_PATH.'admin/media#'.$this->qstring;?>" class="grey m10"><strong><?php echo $this->translate('CANCEL');?></strong></a>
			<a id="deleteButton" href="javascript:void(0);" onclick="callToPermanentDelete();" class="red mt10"><strong><?php echo $this->translate('DELETE');?></strong></a>
			</div>
		
		</div>

</div>
</div>
</div>
</div>
</form>
</div>

