<?php
$sessionNamespace = new Zend_Session_Namespace();
$controller = $this->controllerName;
$action = $this->action;
//var_dump($sessionNamespace->settings['rights']);
?>
<div id="adminmenuback"></div>
<div id="adminmenuwrap">
<div class="logo"><a href="<?php echo HTTP_PATH ?>admin/index"><img
            src="<?php echo PUBLIC_PATH; ?>images/back_end/logo.png" border="0" width="210" height="112"/></a></div>
<div class="admin-sidebar-headings"><h2><?php echo $this->translate('Content'); ?></h2></div>
<ul id="adminmenu" role="navigation">
    <li <?php if ($controller == 'offer' || $controller == 'usergeneratedoffer') { ?> class="imbull-has-submenu imbull-has-current-submenu imbull-menu-open menu-top menu-icon-offer menu-top-first" <?php } else { ?> class="imbull-has-submenu imbull-not-current-submenu imbull-menu-open menu-top menu-icon-offer menu-top-first" <?php } ?>
        id="menu-posts">

        <div class="imbull-menu-image"><a href="<?php echo HTTP_PATH ?>admin/offer"><br></a></div>
        <div class="">
            <div></div>
        </div>

        <a href="<?php echo HTTP_PATH ?>admin/offer"
           class="imbull-has-submenu imbull-has-current-submenu imbull-menu-open menu-top menu-icon-offer menu-top-first"
           tabindex="1"><?php echo $this->translate('Offers'); ?>
            <span
            <?php if ($controller == 'offer') { ?>class="arrow-down"<?php } else { ?> class="arrow-up" <?php } ?>
            </span>
        </a>

        <div class="imbull-submenu">
            <div class="imbull-submenu-wrap">
                <div class="imbull-submenu-head"><?php echo $this->translate('Offers'); ?> </div>
                <ul>
                    <li><?php if ($controller == 'offer' && $action == 'addoffer') {
                            $offerColorClass = "new-blue";
                        } else {
                            $offerColorClass = "new-gray";
                        } ?>

                        <a href="<?php echo HTTP_PATH; ?>admin/offer/addoffer" class="<?php echo $offerColorClass; ?>"
                           tabindex="1"><?php echo $this->translate('Create Offers'); ?> </a>
                    </li>
                    <li>
                        <?php
                        $offerColorClass = $controller == 'usergeneratedoffer' ? "new-blue" : "new-gray";
                        ?>
                        <a id="socialCode" href="<?php echo HTTP_PATH; ?>admin/usergeneratedoffer"
                           class="<?php echo $offerColorClass; ?>" tabindex="1">
                            <?php echo $this->translate('Social Codes'); ?>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </li>

    <li <?php if ($controller == 'article' || $controller == 'articlecategory') { ?> class="imbull-has-submenu  imbull-has-current-submenu imbull-menu-open menu-top menu-icon-categories" <?php } else { ?> class="imbull-has-submenu  imbull-not-current-submenu imbull-menu-open menu-top menu-icon-categories" <?php } ?>
        id="menu-article">

        <div class="imbull-menu-image <?php if ($controller == 'article' || $controller == 'articlecategory') {
            echo "artImageBlue";
        } else {
            echo "artImage";
        } ?>"><a href="<?php echo HTTP_PATH ?>admin/article"><br></a></div>
        <div class="">
            <div></div>
        </div>

        <a href="<?php echo HTTP_PATH ?>admin/article"
           class="imbull-has-submenu imbull-has-current-submenu imbull-menu-open menu-top menu-icon-shop"
           tabindex="1"><?php echo $this->translate('Articles'); ?>
            <span <?php if ($controller == 'article') { ?> class="arrow-down" <?php } else { ?>class="arrow-up"<?php } ?>></span>
        </a>

        <div class="imbull-submenu">
            <div class="imbull-submenu-wrap">
                <div class="imbull-submenu-head"><?php echo $this->translate('Articles'); ?></div>
                <ul>
                    <li> <?php if ($controller == 'article' && $action == 'createarticle') {
                            $class1 = "new-blue";
                        } else {
                            $class1 = "new-gray";
                        } ?>

                        <a href="<?php echo HTTP_PATH ?>admin/article/createarticle" class="<?php echo $class1; ?>"
                           tabindex="1"><?php echo $this->translate('Create Article'); ?> </a>
                    </li>

                    <li>
                        <?php if ($controller == 'articlecategory') {
                            $class = "num-blue";
                        } else {
                            $class = "num-gray";
                        } ?>

                        <a href="<?php echo HTTP_PATH ?>admin/articlecategory" class="<?php echo $class; ?>"
                           tabindex="1"><?php echo $this->translate('Article Categories'); ?> </a>
                    </li>
                </ul>
            </div>
        </div>
    </li>

    <li  <?php if ($controller == 'shop' || $controller == 'newsticker' || $controller == 'affiliate' || $controller == 'category' || $controller == 'landingpages') { ?> class="imbull-has-submenu  imbull-has-current-submenu imbull-menu-open menu-top menu-icon-shop" <?php } else { ?> class="imbull-has-submenu  imbull-not-current-submenu imbull-menu-open menu-top menu-icon-shop" <?php } ?>
        id="menu-media">

        <div class="imbull-menu-image <?php if ($controller == 'shop' || $controller == 'affiliate') {
            echo "artImageBlueShop";
        } else {
            echo "artImageGreyShop";
        } ?>"><a href="<?php echo HTTP_PATH ?>admin/shop"><br></a></div>
        <div class="">
            <div></div>
        </div>

        <a href="<?php echo HTTP_PATH ?>admin/shop"
           class="imbull-has-submenu imbull-has-current-submenu imbull-menu-open menu-top menu-icon-shop"
           tabindex="1"><?php echo $this->translate('Shops'); ?>
            <span <?php if ($controller == 'shop' || $controller == 'affiliate') { ?> class="arrow-down" <?php } else { ?>class="arrow-up" <?php } ?>></span>
        </a>

        <div class="imbull-submenu">
            <div class="imbull-submenu-wrap">
                <div class="imbull-submenu-head"><?php echo $this->translate('Shop'); ?></div>
                <ul>
                    <li><?php if ($controller == 'shop' && $action == 'createshop') {
                            $class1 = "new-blueShop";
                        } else {
                            $class1 = "new-greyShop";
                        } ?>

                        <a href="<?php echo HTTP_PATH ?>admin/shop/createshop" class="<?php echo $class1; ?>"
                           tabindex="1"><?php echo $this->translate('Create Shop'); ?> </a>
                    </li>
                    <li><?php if ($controller == 'newsticker') {
                            $class1 = "new-blueShop";
                        } else {
                            $class1 = "new-greyShop";
                        } ?>

                        <a href="<?php echo HTTP_PATH ?>admin/newsticker/" class="<?php echo $class1; ?>"
                           tabindex="1"><?php echo $this->translate('Newsticker'); ?> </a>
                    </li>
                    <li><?php if ($controller == 'category') {
                            $class = "num-blueAffiliate";
                        } else {
                            $class = "num-greyAffiliate";
                        } ?>

                        <a href="<?php echo HTTP_PATH ?>admin/category/index" class="<?php echo $class; ?>"
                           tabindex="1"><?php echo $this->translate('Category'); ?></a>
                    </li>

                    <?php if ($sessionNamespace->settings['rights']['administration']['rights'] == '1' || $sessionNamespace->settings['rights']['administration']['rights'] == '2') { ?>
                        <li><?php if ($controller == 'affiliate') {
                                $class = "num-blueAffiliate";
                            } else {
                                $class = "num-greyAffiliate";
                            } ?>

                            <a href="<?php echo HTTP_PATH ?>admin/affiliate" class="<?php echo $class; ?>"
                               tabindex="1"><?php echo $this->translate('Affiliate Networks'); ?></a>
                        </li>
                    <?php } ?>
                    <li>
                        <?php $landingPageClass = ($controller == 'landingpages') ? "new-blueShop" : "new-greyShop"; ?>
                        <a href="<?php echo HTTP_PATH ?>admin/landingpages" class="<?php echo $landingPageClass; ?>"
                           tabindex="1"><?php echo $this->translate('Landing Pages'); ?></a>
                    </li>
                </ul>
            </div>
        </div>
    </li>
    <li <?php if ($controller == 'page') { ?> class="imbull-has-submenu  imbull-has-current-submenu imbull-menu-open menu-top menu-icon-pages" <?php } else { ?> class="imbull-has-submenu  imbull-not-current-submenu imbull-menu-open menu-top menu-icon-pages" <?php } ?>
        id="menu-pages">

        <div class="imbull-menu-image"><a href="<?php echo HTTP_PATH ?>admin/page"><br></a></div>
        <div class="">
            <div></div>
        </div>

        <a href="<?php echo HTTP_PATH ?>admin/page"
           class="imbull-has-submenu imbull-has-current-submenu imbull-menu-open menu-top menu-icon-page"
           tabindex="1"><?php echo $this->translate('Pages'); ?>
            <span <?php if ($controller == 'page') { ?> class="arrow-down" <?php } else { ?>class="arrow-up"<?php } ?>></span>
        </a>

        <div class="imbull-submenu">
            <div class="imbull-submenu-wrap">
                <div class="imbull-submenu-head"><?php echo $this->translate('Pages'); ?></div>
                <ul>
                    <?php if ($controller == 'page' && $action == 'addpage') {
                        $pageColorClass = "new-blue";
                    } else {
                        $pageColorClass = "new-gray";
                    } ?>

                    <li>
                        <a href="<?php echo HTTP_PATH ?>admin/page/addpage" class="<?php echo $pageColorClass; ?>"
                           tabindex="1"><?php echo $this->translate('Create Page'); ?> </a>
                    </li>
                </ul>
            </div>
        </div>
    </li>
    <?php if ($sessionNamespace->settings['rights']['content']['rights'] == '1') { ?>
        <li <?php if ($controller == 'widget') { ?> class="imbull-has-submenu  imbull-has-current-submenu imbull-menu-open menu-top menu-icon-widgets" <?php } else { ?> class="imbull-has-submenu  imbull-not-current-submenu imbull-menu-open menu-top menu-icon-widgets" <?php } ?>
            id="menu-media">

            <div class="imbull-menu-image"><a href="<?php echo HTTP_PATH ?>admin/widget"><br></a></div>
            <div class="">
                <div></div>
            </div>

            <a href="<?php echo HTTP_PATH ?>admin/widget"
               class="imbull-has-submenu imbull-has-current-submenu imbull-menu-open menu-top menu-icon-widgets"
               tabindex="1"><?php echo $this->translate('Widgets'); ?>
                <span <?php if ($controller == 'widget') { ?> class="arrow-down" <?php } else { ?>class="arrow-up"<?php } ?>></span>
            </a>

            <div class="imbull-submenu">
                <div class="imbull-submenu-wrap">
                    <div class="imbull-submenu-head"><?php echo $this->translate('Widget'); ?></div>
                    <ul>
                        <?php if ($controller == 'widget' && $action == 'addwidget') {
                            $widgetColorClass = "new-blue";
                        } else {
                            $widgetColorClass = "new-gray";
                        } ?>

                        <li>
                            <a href="<?php echo HTTP_PATH ?>admin/widget/addwidget"
                               class="<?php echo $widgetColorClass; ?>"
                               tabindex="1"><?php echo $this->translate('Add Widget'); ?> </a>
                        </li>
                        <?php
                        if ($controller == 'widget' && $action == 'sort-widget') {
                            $widgetColorClass = "new-blue";
                        } else {
                            $widgetColorClass = "new-gray";
                        }
                        ?>
                        <li>
                            <a href="<?php echo HTTP_PATH ?>admin/widget/sort-widget"
                               class="<?php echo $widgetColorClass; ?>" tabindex="1">
                                <?php echo $this->translate('backend_Sort Widget'); ?>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </li>


        <li <?php if ($controller == 'media') { ?> class="imbull-has-submenu  imbull-has-current-submenu imbull-menu-open menu-top menu-icon-media" <?php } else { ?> class="imbull-has-submenu  imbull-not-current-submenu imbull-menu-open menu-top menu-icon-media" <?php } ?>
            id="menu-media">

            <div class="imbull-menu-image"><a href="<?php echo HTTP_PATH ?>admin/media"><br></a></div>
            <div class="">
                <div></div>
            </div>

            <a href="<?php echo HTTP_PATH ?>admin/media"
               class="imbull-has-submenu imbull-has-current-submenu imbull-menu-open menu-top menu-icon-media"
               tabindex="1"><?php echo $this->translate('Media'); ?>
                <span <?php if ($controller == 'media') { ?> class="arrow-down" <?php } else { ?>class="arrow-up"<?php } ?>></span>
            </a>

            <div class="imbull-submenu">
                <div class="imbull-submenu-wrap">
                    <div class="imbull-submenu-head"><?php echo $this->translate('Media'); ?></div>
                    <ul>
                        <?php if ($controller == 'media' && $action == 'addmedia') {
                            $mediaColorClass = "new-blue";
                        } else {
                            $mediaColorClass = "new-gray";
                        } ?>

                        <li>
                            <a href="<?php echo HTTP_PATH ?>admin/media/addmedia"
                               class="<?php echo $mediaColorClass; ?>"
                               tabindex="1"><?php echo $this->translate('Upload Media'); ?> </a>
                        </li>
                    </ul>
                </div>
            </div>
        </li>
    <?php }
    if ($sessionNamespace->settings['rights']['content']['rights'] == '1' || $sessionNamespace->settings['rights']['content']['rights'] == '2') { ?>
        <li <?php if ($controller == 'menu') { ?> class="imbull-has-submenu  menu-top menu-icon-popular imbull-has-current-submenu current" <?php } else { ?> class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-popular" <?php } ?>
            id="menu-links">

            <div class="imbull-menu-image"><a href="<?php echo HTTP_PATH; ?>admin/menu"><br></a></div>
            <div class="">
                <div></div>
            </div>

            <a href="<?php echo HTTP_PATH; ?>admin/menu"
               class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-profile"><?php echo $this->translate('Menus'); ?></a>
        </li>
    <?php } ?>
</ul>


<div class="admin-sidebar-headings"><h2><?php echo $this->translate('Administration'); ?></h2></div>
    <ul id="adminmenu" role="navigation">
    <?php if ($sessionNamespace->settings['rights']['administration']['rights'] == '1') { ?>
        <li class="menu-icon-user <?php echo $controller == 'apikeys' ? 'imbull-has-current-submenu' : 'imbull-not-current-submenu' ?>"
            id="menu-posts">
            <div class="imbull-menu-image">
                <a href="<?php echo HTTP_PATH ?>admin/apikeys"><br></a>
            </div>
            <a href="<?php echo HTTP_PATH ?>admin/apikeys" class="imbull-has-current-submenu menu-top menu-icon-user"
               tabindex="1">
                <?php echo $this->translate('API Keys'); ?>
            </a>
        </li>
    <?php
    }
    ?>

    <?php if ($sessionNamespace->settings['rights']['administration']['rights'] == '1') { ?>

        <li <?php if ($controller == 'user') { ?> class="imbull-has-submenu menu-top menu-icon-user imbull-menu-open imbull-has-current-submenu" <?php } else { ?> class="imbull-has-submenu menu-top menu-icon-user imbull-menu-open imbull-not-current-submenu" <?php } ?>
            id="menu-posts">

            <div class="imbull-menu-image"><a href="<?php echo HTTP_PATH ?>admin/user"><br></a></div>
            <div class="">
                <div></div>
            </div>

            <a href="<?php echo HTTP_PATH ?>admin/user"
               class="imbull-has-submenu imbull-has-current-submenu imbull-menu-open menu-top menu-icon-user"
               tabindex="1"><?php echo $this->translate('Users'); ?>
                <span
                    <?php if ($controller == 'user') { ?>class="arrow-down" <?php } else { ?> class="arrow-up" <?php } ?>></span>
            </a>

            <div class="imbull-submenu">
                <div class="imbull-submenu-wrap">
                    <div class="imbull-submenu-head"><?php echo $this->translate('Users'); ?> </div>
                    <ul>
                        <?php if ($controller == 'user' && $action == 'adduser') {
                            $userColorClass = "new-blue";
                        } else {
                            $userColorClass = "new-gray";
                        } ?>
                        <li>
                            <a href="<?php echo HTTP_PATH ?>admin/user/adduser" class="<?php echo $userColorClass; ?>"
                               tabindex="1"><?php echo $this->translate('Create user'); ?> </a>
                        </li>
                    </ul>
                </div>
            </div>
        </li>
        <?php
        $classHasCurrent = $controller == 'ipaddresses'
            ? 'imbull-has-current-submenu'
            : 'imbull-not-current-submenu';
        $userColorClass = $controller == 'ipaddresses' && $action == 'addipaddress' ? "new-blue" : "new-gray";
        ?>
        <li class="imbull-has-submenu menu-top menu-icon-user imbull-menu-open <?php echo $classHasCurrent; ?>"
            id="menu-posts">
            <div class="imbull-menu-image">
                <a href="<?php echo HTTP_PATH ?>admin/ipaddresses"><br></a>
            </div>
            <div class="">
                <div></div>
            </div>
            <a href="<?php echo HTTP_PATH ?>admin/ipaddresses"
               class="imbull-has-submenu imbull-has-current-submenu imbull-menu-open menu-top menu-icon-user"
               tabindex="1">
                <?php echo $this->translate('IP addresses'); ?>
                <span class="<?php echo $controller == 'ipaddresses' ? 'arrow-down' : 'arrow-up'; ?>"></span>
            </a>

            <div class="imbull-submenu">
                <div class="imbull-submenu-wrap">
                    <div class="imbull-submenu-head"><?php echo $this->translate('Users'); ?> </div>
                    <ul>
                        <li>
                            <a href="<?php echo HTTP_PATH ?>admin/ipaddresses/addipaddress"
                               class="<?php echo $userColorClass; ?>" tabindex="1">
                                <?php echo $this->translate('Create IP addresses'); ?>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </li>
    <?php
    }
    ?>

    <li <?php if ($controller == 'user' && $action == 'profile') { ?>class="imbull-has-submenu  menu-top menu-icon-profile imbull-has-current-submenu current"
        <?php } else { ?>class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-profile"
        <?php } ?>id="menu-links">

        <div class="imbull-menu-image"><a href="<?php echo HTTP_PATH; ?>admin/user/profile"><br></a></div>
        <div class="">
            <div></div>
        </div>
        <a href="<?php echo HTTP_PATH; ?>admin/user/profile"
           class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-profile"><?php echo $this->translate('Your Profile'); ?></a>
    </li>

    <?php if ($sessionNamespace->settings['rights']['administration']['rights'] == '1') { ?>
        <li <?php if ($controller == 'visitor') { ?> class="imbull-has-submenu  imbull-has-current-submenu imbull-menu-open menu-top menu-icon-visitor" <?php } else { ?> class="imbull-has-submenu  imbull-not-current-submenu imbull-menu-open menu-top menu-icon-visitor" <?php } ?>
            id="menu-media">

            <div class="imbull-menu-image"><a href="<?php echo HTTP_PATH ?>admin/visitor"><br></a></div>
            <div class="">
                <div></div>
            </div>
            <a href="<?php echo HTTP_PATH ?>admin/visitor"
               class="imbull-has-submenu imbull-has-current-submenu imbull-menu-open menu-top menu-icon-widgets"
               tabindex="1"><?php echo $this->translate('Visitors'); ?></a>
        </li>
    <?php } ?>
</ul>

<div class="admin-sidebar-headings"><h2><?php echo $this->translate('Email'); ?></h2></div>
<ul id="adminmenu" role="navigation">
    <?php if ($sessionNamespace->settings['rights']['administration']['rights'] == '1') { ?>
        <!--<li <?php if ($controller == 'email' && $action == 'index') { ?> class="imbull-has-submenu menu-top menu-icon-lightbox imbull-menu-open imbull-has-current-submenu" <?php } else { ?> class="imbull-has-submenu menu-top menu-icon-lightbox imbull-menu-open imbull-not-current-submenu" <?php } ?> id="menu-links">

      	<div class="imbull-menu-image"><a href="<?php echo HTTP_PATH; ?>admin/email/index"><br></a></div>
	    <div class=""><div></div></div>
	    <a <?php if ($controller == 'email' && $action == 'index') {
            echo 'style=color:#0088CC';
        } ?> href="<?php echo HTTP_PATH; ?>admin/email/index" class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-profile" ><?php echo $this->translate('Emails'); ?></a>
	 	</li>-->

        <li <?php if ($controller == 'email' && $action == 'email-settings') { ?> class="imbull-has-submenu menu-top menu-icon-lightbox imbull-menu-open imbull-has-current-submenu" <?php } else { ?> class="imbull-has-submenu menu-top menu-icon-lightbox imbull-menu-open imbull-not-current-submenu" <?php } ?>
            id="menu-links">

            <div class="imbull-menu-image"><a href="<?php echo HTTP_PATH; ?>admin/email/email-settings"><br></a></div>
            <div class="">
                <div></div>
            </div>
            <a <?php if ($controller == 'email' && $action == 'email-settings') {
                echo 'style=color:#0088CC';
            } ?> href="<?php echo HTTP_PATH; ?>admin/email/email-settings"
                 class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-profile"><?php echo $this->translate('Email Settings'); ?></a>
        </li>
    <?php } ?>
        <li <?php if ($controller == 'email') { ?> class="imbull-has-submenu menu-top menu-icon-lightbox imbull-menu-open imbull-has-current-submenu" <?php } else { ?> class="imbull-has-submenu menu-top menu-icon-lightbox imbull-menu-open imbull-not-current-submenu" <?php } ?>
            id="menu-posts">
            <div class="imbull-menu-image">
                <a href="<?php echo HTTP_PATH ?>admin/email/code-alert"><br></a>
            </div>
            <div class="">
                <div></div>
            </div>
            <a href="<?php echo HTTP_PATH ?>admin/email/code-alert"
               class="imbull-has-submenu imbull-has-current-submenu imbull-menu-open menu-top menu-icon-lightbox"
               tabindex="1"><?php echo $this->translate('Code alert'); ?>
                <span
                    <?php if ($controller == 'email') { ?>class="arrow-down" <?php } else { ?> class="arrow-up" <?php } ?>></span>
            </a>

            <div class="imbull-submenu">
                <div class="imbull-submenu-wrap">
                    <div class="imbull-submenu-head"><?php echo $this->translate('Code alert'); ?> </div>
                    <ul>
                        <?php if ($controller == 'email' && $action == 'code-alert-settings') {
                            $userColorClass = "new-blue";
                        } else {
                            $userColorClass = "new-gray";
                        } ?>
                        <li>
                            <a href="<?php echo HTTP_PATH ?>admin/email/code-alert-settings"
                               class="<?php echo $userColorClass; ?>"
                               tabindex="1"><?php echo $this->translate('Code alert settings'); ?> </a>
                        </li>
                        <?php if ($controller == 'email' && $action == 'code-alert-log-list') {
                            $userColorClass = "new-blue";
                        } else {
                            $userColorClass = "new-gray";
                        } ?>
                        <li>
                            <a href="<?php echo HTTP_PATH ?>admin/email/code-alert-log-list"
                               class="<?php echo $userColorClass; ?>"
                               tabindex="1"><?php echo $this->translate('Code alert log'); ?> </a>
                        </li>
                    </ul>
                </div>
            </div>
        </li>
    </ul>

<div class="admin-sidebar-headings"><h2><?php echo $this->translate('Template Settings'); ?></h2></div>
<ul id="adminmenu" role="navigation">
<?php if ($sessionNamespace->settings['rights']['administration']['rights'] == '1') : ?>
    <li <?php if ($controller == 'locale' && $action == 'locale-settings') { ?> class="imbull-has-submenu menu-top menu-icon-lightbox imbull-menu-open imbull-has-current-submenu" <?php } else { ?> class="imbull-has-submenu menu-top menu-icon-lightbox imbull-menu-open imbull-not-current-submenu" <?php } ?>
        id="menu-links">

        <div class="imbull-menu-image"><a href="<?php echo HTTP_PATH; ?>admin/locale/locale-settings"><br></a></div>
        <div class="">
            <div></div>
        </div>
        <a <?php if ($controller == 'locale' && $action == 'locale-settings') {
            echo 'style=color:#0088CC';
        } ?> href="<?php echo HTTP_PATH; ?>admin/locale/locale-settings"
             class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-profile"><?php echo $this->translate('Locale Settings'); ?></a>
    </li>
<?php endif; ?>
    <li <?php if ($controller == 'homepage') { ?> class="imbull-has-submenu imbull-has-current-submenu menu-top menu-icon-home current" <?php } else { ?> class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-home" <?php } ?>
        id="menu-links">
        <div class="imbull-menu-image"><a href="<?php echo HTTP_PATH ?>admin/homepage"><br></a></div>
        <div class="">
            <div></div>
        </div>
        <a href="<?php echo HTTP_PATH ?>admin/homepage"
           class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-home"
           tabindex="1"><?php echo $this->translate('Home Page'); ?></a>
    </li>

    <?php #make available only for admin and super admin user
    if ($sessionNamespace->settings['rights']['system manager']['rights'] == '1') :    ?>

        <li <?php if ($controller == 'accountsetting' && $action != 'emailcontent') { ?>class="imbull-has-submenu  menu-top menu-icon-profile imbull-has-current-submenu current"
            <?php } else { ?>class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-profile"
            <?php } ?>id="menu-links">

            <div class="imbull-menu-image"><a href="<?php echo HTTP_PATH; ?>admin/accountsetting"><br></a></div>
            <div class="">
                <div></div>
            </div>
            <a href="<?php echo HTTP_PATH; ?>admin/accountsetting"
               class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-profile"><?php echo $this->translate('Account Settings'); ?></a>
        </li>

        <li <?php if ($controller == 'accountsetting' && $action == 'emailcontent') { ?> class="imbull-has-submenu menu-top menu-icon-lightbox imbull-menu-open imbull-has-current-submenu" <?php } else { ?> class="imbull-has-submenu menu-top menu-icon-lightbox imbull-menu-open imbull-not-current-submenu" <?php } ?>
            id="menu-links">

            <div class="imbull-menu-image"><a href="<?php echo HTTP_PATH; ?>admin/accountsetting/emailcontent"><br></a>
            </div>
            <div class="">
                <div></div>
            </div>
            <a <?php if ($controller == 'accountsetting' && $action == 'emailcontent') {
                echo 'style=color:#0088CC';
            } ?> href="<?php echo HTTP_PATH; ?>admin/accountsetting/emailcontent"
                 class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-profile"><?php echo $this->translate('Email Management'); ?></a>
        </li>
    <?php endif; ?>
    <?php
    # make footer only editbable by superadmins
    if ($sessionNamespace->settings['rights']['content']['rights'] == '1') : ?>
        <li <?php if ($controller == 'footer') { ?>class="imbull-has-submenu imbull-has-current-submenu menu-top menu-icon-footer current" <?php } else { ?> class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-footer" <?php } ?>
            id="menu-links">
            <div class="imbull-menu-image"><a href="<?php echo HTTP_PATH ?>admin/footer"><br> </a></div>
            <div class="">
                <div></div>
            </div>
            <a href="<?php echo HTTP_PATH ?>admin/footer"
               class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-footer"
               tabindex="1"><?php echo $this->translate('Footer'); ?></a>
        </li>
    <?php endif; ?>

    <li <?php if ($controller == 'popularcode') { ?> class="imbull-has-submenu  menu-top menu-icon-popular imbull-has-current-submenu current" <?php } else { ?> class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-popular" <?php } ?>
        id="menu-links">

        <div class="imbull-menu-image"><a href="<?php echo HTTP_PATH; ?>admin/popularcode"><br></a></div>
        <div class="">
            <div></div>
        </div>
        <a href="<?php echo HTTP_PATH; ?>admin/popularcode"
           class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-profile"><?php echo $this->translate('Popular Codes'); ?></a>
    </li>

    <li
        <?php
        if ($controller == 'populararticles') {
            ?>
            class="imbull-has-submenu  menu-top menu-icon-popular imbull-has-current-submenu current"
        <?php
        } else {
            ?>
            class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-popular"
        <?php
        }
        ?> id="menu-links">
        <div class="imbull-menu-image">
            <a href="<?php echo HTTP_PATH; ?>admin/populararticles"><br></a>
        </div>
        <div class="">
            <div></div>
        </div>
        <a href="<?php echo HTTP_PATH; ?>admin/populararticles"
           class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-profile">
            <?php echo $this->translate('Popular Articles'); ?>
        </a>
    </li>

    <li
        <?php
        if ($controller == 'specialpagesoffers') {
            ?>
            class="imbull-has-submenu  menu-top menu-icon-popular imbull-has-current-submenu current"
        <?php
        } else {
            ?>
            class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-popular"
        <?php
        }
        ?> id="menu-links">
        <div class="imbull-menu-image">
            <a href="<?php echo HTTP_PATH; ?>admin/specialpagesoffers"><br></a>
        </div>
        <div class="">
            <div></div>
        </div>
        <a href="<?php echo HTTP_PATH; ?>admin/specialpagesoffers"
           class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-profile">
            <?php echo $this->translate('Special Pages Offers'); ?>
        </a>
    </li>

    <li
        <?php
        if ($controller == 'categoriesoffers') {
            ?>
            class="imbull-has-submenu  menu-top menu-icon-popular imbull-has-current-submenu current"
        <?php
        } else {
            ?>
            class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-popular"
        <?php
        }
        ?> id="menu-links">
        <div class="imbull-menu-image">
            <a href="<?php echo HTTP_PATH; ?>admin/categoriesoffers"><br></a>
        </div>
        <div class="">
            <div></div>
        </div>
        <a href="<?php echo HTTP_PATH; ?>admin/categoriesoffers"
           class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-profile">
            <?php echo $this->translate('Category Pages Offers'); ?>
        </a>
    </li>

    <li <?php if ($controller == 'searchbar') { ?>  class="imbull-has-submenu menu-top menu-icon-searchbar imbull-menu-open imbull-has-current-submenu" <?php } else { ?> class="imbull-has-submenu menu-top menu-icon-searchbar imbull-menu-open imbull-not-current-submenu" <?php } ?>
        id="menu-links">

        <div class="imbull-menu-image"><a href="<?php echo HTTP_PATH ?>admin/searchbar"><br></a></div>
        <div class="">
            <div></div>
        </div>

        <a href="<?php echo HTTP_PATH ?>admin/searchbar"
           class="iimbull-has-submenu imbull-has-current-submenu imbull-menu-open menu-top menu-icon-searchbar"
           tabindex="1"><?php echo $this->translate('Searchbar'); ?>
            <span
                <?php if ($controller == 'searchbar'){ ?>class="arrow-down" <?php } else { ?> class="arrow-up" <?php } ?>></span>
        </a>

        <div class="imbull-submenu">
            <div class="imbull-submenu-wrap">
                <div class="imbull-submenu-head"><?php echo $this->translate('Searchbar'); ?> </div>
                <ul>
                    <?php if ($controller == 'searchbar' && $action == 'addkeyword') {
                        $searchColorClass = "new-blue";
                    } else {
                        $searchColorClass = "new-gray";
                    } ?>

                    <li>
                        <a href="<?php echo HTTP_PATH ?>admin/searchbar/addkeyword"
                           class="<?php echo $searchColorClass; ?>"
                           tabindex="1"><?php echo $this->translate('Add Excluded Keyword'); ?> </a>
                    </li>
                </ul>
            </div>
        </div>
    </li>

    <!-- change by kraj  -->
    <?php if ($sessionNamespace->settings['rights']['system manager']['rights'] == '1') { ?>

        <li <?php if ($controller == 'redirect') { ?> class="imbull-has-submenu menu-top menu-icon-searchbar imbull-menu-open imbull-has-current-submenu" <?php } else { ?> class="imbull-has-submenu menu-top menu-icon-searchbar imbull-menu-open imbull-not-current-submenu" <?php } ?>
            id="menu-links">

            <div class="imbull-menu-image"><a href="<?php echo HTTP_PATH ?>admin/redirect"><br></a></div>
            <div class="">
                <div></div>
            </div>

            <a href="<?php echo HTTP_PATH ?>admin/redirect"
               class="iimbull-has-submenu imbull-has-current-submenu imbull-menu-open menu-top menu-icon-searchbar"
               tabindex="1"><?php echo $this->translate('Redirects'); ?>
                <span
                    <?php if ($controller == 'redirect'){ ?>class="arrow-down" <?php } else { ?> class="arrow-up" <?php } ?>></span>
            </a>

            <div class="imbull-submenu">
                <div class="imbull-submenu-wrap">
                    <div class="imbull-submenu-head"><?php echo $this->translate('Redirects'); ?> </div>
                    <ul>
                        <?php if ($controller == 'redirect' && $action == 'addredirect') {
                            $searchColorClass = "new-blue";
                        } else {
                            $searchColorClass = "new-gray";
                        } ?>
                        <li>
                            <a href="<?php echo HTTP_PATH ?>admin/redirect/addredirect"
                               class="<?php echo $searchColorClass; ?>"
                               tabindex="1"><?php echo $this->translate('Add Redirect'); ?> </a>
                        </li>
                    </ul>
                </div>
            </div>
        </li>

        <li <?php $color = '';
        if ($controller == 'language') {
            $color = 'style=color:#0088CC'; ?> class="imbull-has-submenu menu-top menu-icon-language imbull-menu-open imbull-has-current-submenu" <?php } else { ?> class="imbull-has-submenu menu-top menu-icon-language imbull-menu-open imbull-not-current-submenu" <?php } ?>
            id="language-menu-links">
            <div class="imbull-menu-image"><a href="<?php echo HTTP_PATH; ?>admin/popularcode"><br></a></div>
            <div class="">
                <div></div>
            </div>
            <a href="<?php echo HTTP_PATH ?>admin/language"
               class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-language" <?php echo $color; ?>><?php echo $this->translate('Language File'); ?></a>
        </li>
    <?php } ?>
    <li <?php if ($controller == 'urlsettings') : ?>
            class="imbull-has-submenu menu-top menu-icon-pages imbull-menu-open imbull-has-current-submenu"
        <?php else : ?>
            class="imbull-has-submenu menu-top menu-icon-pages imbull-menu-open imbull-not-current-submenu"
        <?php endif; ?>
        id="menu-links">

        <div class="imbull-menu-image"><a href="<?php echo HTTP_PATH; ?>admin/urlsettings"><br></a></div>
        <div class="">
            <div></div>
        </div>
        <a <?php if ($controller == 'urlsettings') :
            echo 'style=color:#0088CC';
            endif; ?>
            href="<?php echo HTTP_PATH; ?>admin/urlsettings"
            class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-pages"><?php echo $this->translate('VWO Manager'); ?></a>
    </li>
</ul>

<?php if ($sessionNamespace->settings['rights']['administration']['rights'] == '1' || $sessionNamespace->settings['rights']['administration']['rights'] == '2'): ?>
    <div class="admin-sidebar-headings"><h2><?php echo $this->translate('Global Settings'); ?></h2></div>
    <ul id="adminmenu" role="navigation">
    <?php if ($sessionNamespace->settings['rights']['administration']['rights'] == '1'): ?>
       <li <?php if ($controller == 'chain') { ?> class="imbull-has-submenu imbull-has-current-submenu menu-top menu-icon-home current" <?php } else { ?> class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-home" <?php } ?>
            id="menu-links">
            <div class="imbull-menu-image artImageGreyShop"><a href="<?php echo HTTP_PATH ?>admin/chain"><br></a></div>
            <div class="">
                <div></div>
            </div>
            <a href="<?php echo HTTP_PATH ?>admin/chain"
               class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-home"
               tabindex="1"><?php echo $this->translate('Chains'); ?></a>
       </li>
    <?php endif; ?>
        <li <?php if ($controller == 'splash') { ?> class="imbull-has-submenu imbull-has-current-submenu menu-top menu-icon-home current" <?php } else { ?> class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-home" <?php } ?>
            id="menu-links">
            <div class="imbull-menu-image artImageGreyShop"><a href="<?php echo HTTP_PATH ?>admin/splash/"><br></a>
            </div>
            <div class="">
                <div></div>
            </div>
            <a href="<?php echo HTTP_PATH ?>admin/splash/"
               class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-home"
               tabindex="1"><?php echo $this->translate('Splash'); ?></a>
        </li>
    <?php if ($sessionNamespace->settings['rights']['administration']['rights'] == '1'): ?>
        <li <?php if ($controller == 'robot') { ?> class="imbull-has-submenu imbull-has-current-submenu menu-top menu-icon-home current" <?php } else { ?> class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-home" <?php } ?>
            id="menu-links">
            <div class="imbull-menu-image artImageGreyShop"><a href="<?php echo HTTP_PATH ?>admin/robot/"><br></a></div>
            <div class="">
                <div></div>
            </div>
            <a href="<?php echo HTTP_PATH ?>admin/robot/"
               class="imbull-has-submenu imbull-not-current-submenu menu-top menu-icon-home"
               tabindex="1"><?php echo $this->translate('Robot Files'); ?></a>
        </li>
    <?php endif; ?>
    </ul>
<?php endif; ?>
<?php
$releaseInfo = @BackEnd_Helper_viewHelper::currentRelease(); ?>
<div class="clear"></div>
<div class='release-note'>
    by <a href="http://www.web-flight.nl/" target="_blank">Webflight</a><br>
    <a href="<?php echo HTTP_PATH; ?>admin/releasenotes"><?php echo $releaseInfo['version']; ?>
        , <?php echo $releaseInfo['releaseDate']; ?></a>
</div>

</div>