<div class="container">
    <div class="section tab-section">
        <ul class="tabset">
<?php
foreach ($this->aboutTabs as $aboutTabIndex => $aboutTab):
    ?>
            <li class="<?php echo $aboutTabIndex=='0' ? 'active' : ''; ?>">
                <a id="tab_<?php echo $aboutTabIndex;?>" 
                onclick="showTab('<?php echo $aboutTabIndex;?>');" href="javascript:void(0)">
                <?php echo $aboutTab['title']; ?>
                </a>
            </li>
    <?php 
endforeach;
?>
        </ul>
        <div class="tab-content">
<?php 
foreach ($this->aboutTabs as $aboutTabIndex => $aboutTab):
?>
            <div id="services_<?php echo $aboutTabIndex; ?>">
                <?php echo $aboutTab['content']; ?>
            </div>
<?php 
endforeach;
?>
        </div>
    </div>
</div>