<div class="logos-panel">
    <div class="container">
        <ul class="shops">
<?php
foreach ($this->top9Stores as $top9Store):
    $storeImage = PUBLIC_PATH_CDN.ltrim($top9Store['popularshops']['logo']['path'], "/") .'thum_medium_'
    . $top9Store['popularshops']['logo']['name'];
?>
            <li>
                <a href="<?php echo HTTP_PATH_LOCALE. $top9Store['popularshops']['permaLink'];?>">
                   <img src="<?php echo $storeImage;?>" width="100" height="50" 
                   alt="<?php echo $top9Store['popularshops']['name'];?>" title="<?php echo $top9Store['popularshops']['name'];?>">
                </a>
            </li>
<?php 
endforeach;
?>
        </ul>
    </div>
</div>