<?php 
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.dataTables.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/dataTableComman.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/select2.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/jquery-ui-1.8.16.custom.css" );
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/select2.css" );
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/page.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/jquery.validate.js");
$this->headScript ()->prependFile ( PUBLIC_PATH . "js/back_end/widget-location.js");
?>
<?php echo $this->headTitle()->append('Pages List');?>
   <!-- pageList starts -->
      	<div id="pageList">
             <div class="wrap columns-2">
                <div class='wrap columns-2'>
		<?php if($this->messageSuccess!='' || $this->messageError!='' ){?>
		<br><div class ="mainpage-content-colorbox success">
		<?php if($this->messageSuccess!=''){?>
		<span class="successserver"><?php echo $this->messageSuccess; ?></span>
		<?php }?>
		<?php if($this->messageError!=''){?>
		<span class="errorserver"><?php echo $this->messageError; ?></span>
		<?php } ?>
		</div>
		<?php 
		}?>
		</div>
          <h1 class="fl"><?php echo $this->translate('Pages')?><button onclick="window.location.href='<?php echo HTTP_PATH;?>admin/page/addpage'" class="btn ml10"><?php echo $this->translate('Add New Page')?></button></h1>
          	<div class="clear"></div>
        
          	<p class="text-right">
                <a href='javascript:void(0)' onclick="showLightBoxForWidgetLocation()">
                    <?php echo $this->translate('Set Widget Location')?>
                </a>  / 
                <a href='<?php echo HTTP_PATH;?>admin/page/exportpagelist'>
                    <?php echo $this->translate('Export List')?>
                </a>
            </p>
          <div class="mainpage-content-colorbox">	
        <form class="form-search"  name="searchform" id="searchform">
          <div class="fl ml15"> 
                        <select name="pagetype" id="pagetype">
                        	<option value="">All</option>
                            <option value="default">Default</option>
                            <option value="offer">Offer List</option>
                        </select>
                    </div>
              	<div class="mainpage-content-searchbart" style="width: 50%; float:right;">
                    <div class="mainpage-content-right-searchbar">
                    	<button id='searchButton' type='button' class="btn btn-primary" ><?php echo $this->translate('Search'); ?></button>
                    </div>
                    <div class="mainpage-content-right-inner-left-searchbar">
                      <input type='hidden' id="SearchPage" name="SearchPage" style="width:99%;"/>
                    </div>                        
                </div>
            </form>	
       	</div>
       <table class="table table-bordered table-striped" id="pageListTbl">
                <thead>
                  <tr>
                  	<th><?php echo $this->translate('Page Title'); ?></th>
                    <th><?php echo $this->translate('Type');?></th>
                    <th><?php echo $this->translate('Permalink');?></th>
                    <th><?php echo $this->translate('Created');?></th>
                    <th><?php echo $this->translate('Author');?></th>
                    <th><?php echo $this->translate('Delete');?></th>
                  </tr>
                </thead>
             </table>
         </div>
           
        </div>
       <!-- pageList end -->
<?php echo $this->partial('widgetlocation/_widget-location.phtml', array('pageType' => 'page', 'relatedId' => ''));?>