<!-- <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/> -->
<!-- <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script> -->
<?php 
echo $this->headTitle()->append('Trashed Users List');
$role =  Zend_Auth::getInstance()->getIdentity()->roleId;
if($role=='1' || $role=='2'){
$this->headTitle()->append($this->translate('Trash'));

//$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/jquery.js");	
$this->headScript()->appendFile(PUBLIC_PATH . "js/jquery.dataTables.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/dataTableComman.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/trashedVisitor.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "/css/jquery-ui-1.8.16.custom.css" );

?>
<!-- Div for user list  -->
<div class='wrap columns-2"' id='userListDiv'>

		<h1><?php echo $this->translate('Trash Member List');?>
		 <button class="btn ml10" href="#" onClick="window.location.href='<?php echo HTTP_PATH.'admin/visitor/'; ?>'"><?php echo $this->translate('Cancel');?></button>
		</h1>
		<div class="mainpage-content-colorbox">
               <form class="form-search" name="searchForm" id="searchForm">
                    <div class="fl">                   
                         <input type="text" id='searchVisitor' name='searchVisitor' placeholder="Search Visitor.." class="span5">
                        <button class="btn btn-primary" type="submit"><?php echo $this->translate('Search');?></button>
                        <!--<button onclick="javascript:getUserList(search.value,'undefined')" class="btn btn-primary">Search</button> -->
                    </div>             	
                    <!--<div class="fl ml15 fillterDiv"> 
                      <select id='selectRole'>
                      </select>
                    </div> -->                         
                </form>
         </div> 
         
         <?php if($this->messageSuccess!='' || $this->messageError!='' ){?>
<br><div class ="mainpage-content-colorbox success">
<?php if($this->messageSuccess!=''){?>
<span class="successserver"><?php echo $this->messageSuccess; ?></span>
<?php }?>
<?php if($this->messageError!=''){?>
<span class="errorserver"><?php echo $this->messageError; ?></span>
<?php } ?>
</div>
<?php }?> 
		<table id="trashVisitorListTable" class="table table-bordered table-striped">
			<thead>
	            <tr>
	            	<th><?php echo $this->translate('Id'); ?></th>
	                <th><?php echo $this->translate('First Name'); ?></th>
	                <th><?php echo $this->translate('Last Name'); ?></th>
	                <th><?php echo $this->translate('Email'); ?></th>
	               	<th><?php echo $this->translate('Date Of Registration'); ?></th>
	                <th class="minwidth"><?php echo $this->translate('Restore');?></th>
	                <th class="minwidth"><?php echo $this->translate('Delete');?></th>
  	            </tr>
	        </thead>
	    </table>
</div><!-- End code of list users -->

<?php 
}
 ?>