<?php 
 $this->headMeta('keyword', 'Description');
 
 $this->headTitle()->append($this->translate('Chain management'));
 $this->headScript ()->appendFile ( PUBLIC_PATH . "js/jquery.dataTables.min.js" );
 $this->headScript ()->appendFile ( PUBLIC_PATH . "js/dataTableComman.js" );
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");   
 $this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/jquery-ui-1.8.16.custom.css" );
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/chain-list.js");
?>

 <div id="chainList">
   <div class="wrap columns-2">
    
			<?php if($this->messageSuccess!='' || $this->messageError!='' ){?>
			<br><div class ="mainpage-content-colorbox success">
			<?php if($this->messageSuccess!=''){?>
			<span class="successserver"><?php echo $this->messageSuccess; ?></span>
			<?php }?>
			<?php if($this->messageError!=''){?>
			<span class="errorserver"><?php echo $this->messageError; ?></span>
			<?php } ?>
			</div>
			<?php 
			}?>
	  
        <h1 class="fl"><?php echo $this->translate('Chains'); ?>
        <button class="btn ml10" type="button" onClick="window.location.href='<?php echo HTTP_PATH ?>admin/chain/add-chain'"><?php echo $this->translate('Add New Chain'); ?>
        </button>
        </h1>
        <div class="clear"></div>
        <form class="well form-search searchbarbox" name="searchform" id="searchform" >
           <div class="mainpage-content-searchbart" style="width: 100%; float:left;">
            <div class="mainpage-content-right-searchbar">
             <button type='button' class="btn btn-primary" id="searchByChain"><?php echo $this->translate('Search'); ?></button></div>
              <div class="mainpage-content-right-inner-left-searchbar">
                <input type="text" class="span3" placeholder="search" id="searchChain" name="searchChain">
              </div>                        
           </div>
         </form>
         <table class="table table-bordered table-striped" id="chainTable" cellpadding="0" cellspacing="0">
          <thead>
              <tr>
                  <th><?php echo $this->translate('Name'); ?></th>
                   <th><?php echo $this->translate('Shops'); ?></th>
                   <th><?php echo $this->translate('Delete'); ?></th>
                </tr>
             </thead>
           </table> 
 <!-- End code of list keywords -->
 </div>
 </div>
        
