<?php

  $this->headTitle()->append($this->translate('Article Category'));
  $this->headScript ()->appendFile ( PUBLIC_PATH . "/js/back_end/jquery.validate.js" );
  $this->headScript ()->appendFile ( PUBLIC_PATH . "/js/back_end/addArticleCategory.js" );
  //$this->headScript ()->appendFile ( PUBLIC_PATH . "/js/back_end/jquery.textareaCounter.plugin.js");
  $this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/jquery.textareaCounter.plugin.js");
  $this->headScript ()->appendFile ( PUBLIC_PATH . "/js/jquery.NobleCount.js");
  
?>
<div class="wrap columns-2" id="createCategory">
	<form action="<?php echo HTTP_PATH ;?>admin/articlecategory/addcategory" method="POST" id="saveCategoryForm" name="saveCategoryForm" enctype="multipart/form-data">
	
		<h1><?php echo $this->translate('Create Article Category'); ?><input type="button"  Value='<?php echo $this->translate('Cancel'); ?>' class="btn ml10" onClick="window.location.href='<?php echo HTTP_PATH; ?>admin/articlecategory'" /></h1>

		<div id="poststuff" class="metabox-holder has-right-sidebar">
			<div id="post-body">
				<div>
					<div class="mainpage-content">

						<div class="mainpage-content-line">
							<div class="mainpage-content-left">
								<label><strong><?php echo $this->translate('Title'); ?></strong></label>
							</div>
							<div class="mainpage-content-right">
								<div class="mainpage-content-right-inner-right-other"></div>
								<div class="mainpage-content-right-inner-left-other">
									<input type="text" name="categoryName"
										placeholder="<?php echo $this->translate('Title');?>"
										class="span3" />
								</div>
							</div>
						</div>
						<div class="mainpage-content-line">
							<div class="mainpage-content-left">
								<label><strong><?php echo $this->translate('Permalink'); ?></strong></label>
							</div>
							<div class="mainpage-content-right">
								<div class="mainpage-content-right-inner-left">
									<label><?php echo $this->translate('http://www.kortingscode.nl/'); ?></label>
								</div>
								<div class="mainpage-content-right-inner-right-other"></div>
								<div class="mainpage-content-right-inner-right-full">
									<input type="text" name="permaLink" id="permaLink" placeholder="centerparks" class="span3">
								</div>
							</div>
						</div>
						
						<div class="mainpage-content-line">
							<div class="mainpage-content-left">
								<label><strong><?php echo $this->translate('Meta Title'); ?></strong></label>
							</div>
							<div class="mainpage-content-right">
								<div class="mainpage-content-right-inner-right-other"></div>
								<div class="mainpage-content-right-inner-left-other">
								
								<input class="input-xlarge mbot bbot ignore" type="text" name="metaTitle" id="metaTitle" placeholder="<?php echo $this->translate('Meta title');?>"/>
								<span id="metaTextLeft" class="nobel"></span>
								
								<!--<input type="text" name="metaTitle"
										placeholder="<?php //echo $this->translate('Meta Title');?>"
										class="span3" maxlength="50"/>-->
								</div>
							</div>
						</div>
						
						<div class="mainpage-content-line">
							<div class="mainpage-content-left">
								<label> <strong>
	                            	<?php echo $this->translate ( 'Meta Description' );?>
	                            </strong></label>
							</div>
							<div class="mainpage-content-right">
								<div class="mainpage-content-right-inner-right-other"></div>
								<div class="mainpage-content-right-inner-left-other">
								
								<textarea class="input-xlarge mbot bbot ignore" id="metaDescription" name="metaDescription" placeholder="<?php echo $this->translate ( 'Meta Description' );?>" rows="3"></textarea>
								<span id="metaTextLeft1" class="nobel"></span>
								
								
							<!--<textarea class="input-xlarge mbot bbot ignore" name="metaDescription" id="metaDescription" placeholder="<?php //echo $this->translate ( 'Meta Description' );?>" rows="3"></textarea>
							<input type="text" class="input-xlarge disabled btop word-count"  id="metaTextLeft" value = "Characters Left: 160" placeholder="Word Count: 28" disabled="disabled">-->
								</div>
							</div>
						</div>
						
						<div class="mainpage-content-line mb10">
		                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Related Categories'); ?></strong></label></div>
		                    
		                    <div class="mainpage-content-right">
		                      <div class="category-error"></div>
		                      <div class="categories" style="position:relative;">
				              <?php   for($i = 0;  $i < count($this->categoryList) ; $i++ ){ ?>
				              	<input type="checkbox" value="<?php echo $this->categoryList[$i]['id']; ?>" class="" name="selectedCategoryies[]" id="category-<?php echo $this->categoryList[$i]['id']; ?>" />
				           
				           <?php
							
	                       
	                           if(trim($this->categoryList[$i]['name'])!=''){ 
	                      	?>
	                      	<button type="button" title="<?php echo $this->categoryList[$i]['name'];?>" class="btn square-btn" id="categoryBtn-<?php echo $this->categoryList[$i]['id'];?>" onClick="addCategory(event,'<?php echo $this->categoryList[$i]['id']; ?>')"><?php echo strlen($this->categoryList[$i]['name']) < 20 ? $this->categoryList[$i]['name'] : substr($this->categoryList[$i]['name'],0,20).'..'; ?></button>
	                      	<?php }
	                          
				            } ?>
		                    
		                    
		                      </div>
		                  </div>
                  
                	</div>
						
						<div class="mainpage-content-line">
							<div class="mainpage-content-left">
								<label><strong><?php echo $this->translate('Category Icon'); ?></strong></label>
							</div>
							<div class="mainpage-content-right control-group">
								<div class="mainpage-content-right-inner-right-other upload"></div>
								<div class="mainpage-content-right-inner-left-other">
									<input class="span3 ignore" data-max-size="2097152" onchange="checkFileType(event)" type="file" name="categoryIconNameHidden">
									<?php echo $this->translate('Upload .jpg or .png file only (Maximum file size: 2MB)') ?>
								</div>
							</div>
						</div>
						<div class="mainpage-content-line">
							<div class="mainpage-content-left">
								<label><strong><?php echo $this->translate('Description')?></strong></label>
							</div>
							<div class="mainpage-content-right">
								<div class="mainpage-content-right-inner-right-other"></div>
								<div class="mainpage-content-right-inner-left-other">
									<textarea rows="3" id="description" name="description" placeholder="<?php echo $this->translate('Description')?>" class="input-xlarge mbot bbot ignore word_count"></textarea>
									<input type="text" class="input-xlarge disabled btop word-count" id="description_count" disabled="disabled">
								</div>
							</div>
						</div>
						<div class="mainpage-content-line">
							<div class="mainpage-content-left">
								<label><strong><?php echo $this->translate('Category Title Color'); ?></strong></label>
							</div>
							<div class="mainpage-content-right control-group">
								<div class="mainpage-content-right-inner-right-other"></div>
								<div class="mainpage-content-right-inner-left-other">
									<div class = "color-box" id = "e69342" onclick = "selectedColor('e69342')" 
										style="background-color: #e69342;">
									</div>
									<div class = "color-box" id = "f03580" onclick = "selectedColor('f03580')" 
										style="background-color: #f03580;">
									</div>
									<div class = "color-box" id = "0077cc" onclick = "selectedColor('0077cc')" 
										style="background-color: #0077cc;">
									</div>
									<div class = "color-box" id = "e6050f" onclick = "selectedColor('e6050f')"
										style="background-color: #e6050f;">
									</div>
									<div class = "color-box" id = "47e64b" onclick = "selectedColor('47e64b')"
										style="background-color: #47e64b;">
									</div>
									<input type = "hidden" id = "titlecolor" value = "" name = "titlecolor">
								</div>
							</div>
						</div>
					</div>

				</div>
			</div>
			<br class="clear">
		</div>
		<div class="mainpage-content-colorbox">
			<button id='saveCategory' type="submit" class="btn btn-large btn-primary fl">
            		<?php echo $this->translate('CREATE CATEGORY')?>
            	</button>
			<a href="<?php echo HTTP_PATH; ?>admin/articlecategory" class="fl m10"
				id="cancelCategory"> <strong><?php echo $this->translate('CANCEL')?></strong></a>
		</div>
		<!-- /poststuff -->
	</form>
</div>