<?php

//$this->headTitle()->append($this->translate('All Categories'));
$breadcrumb = "<a href='".HTTP_PATH."category/index/' style='color:#6a6a6a'>".$this->translate('Categories')."</a>";
$headerSearch = new FrontEnd_Helper_viewHelper();
echo $this->partial('partials/_headerSearch.phtml',array('breadcrumb' => $breadcrumb));
?>
<?php
$messege=$this->message;
switch ($messege)
{
case "Page not found":
if($this->pageMode == true)
{

	$width = $display= '';
	if($this->page['pageType'] != "offer"){
  		$width = 'style="width:100%"';
  		$display = 'style="display:none"';
  	}
?>
<div class="alle-winkels-outer">
   <!-- Alle Winkels Left Starts -->
  <div id="left_container" class="" <?php echo $width; ?>>
           	 	
    
  	 <!-- Start Special offer list -->          
  	<?php 
  	if($this->page['pageType'] == "offer"): 
  
  	?>
  	
  	<?php if($this->offercount >0){?>
  	
  		<div class="voucher-outer-left-col1 mt20">
        <?php 
       
        $pageIconPath = '';
        	$pageIconPath = PUBLIC_PATH_CDN.$this->pageLogo['path']."thum_page_large_".$this->pageLogo['name'];
        	
       
        	?>
        	   <div class="voucher-left">
        	   <img src ="<?php echo $pageIconPath;?>" alt="<?php echo $this->page['pageTitle']; ?>" class="radiusImg" title="<?php echo $this->page['pageTitle']; ?>"/>
        	   </div>
        	   
        	<div class="voucher-heading ml15 mt5">
            	<h1><?php echo $this->page['pageTitle']; ?></h1>
            </div>
            
            <div class="voucher-text1 ml15">
            	<span class="word-wrap-without-margin-category"><?php echo stripslashes($this->page['content']); ?></span>
            </div>
         </div>
         
       <div class="separator" style="margin-top:17px;">&nbsp;</div>
       
  		<div class="voucher-outer-left-col1 mt20">
 			<?php 
 						
 				echo $this->partialLoop('partials/offer.phtml', $this->paginator );
 			?>
            <div  class="voucher-paging-outer">
            	<div  class="voucher-paging-outer">
            	<div class="voucher-paging-inner">
            		<!-- <div class="paging-leftarrow">&nbsp;</div> -->
            		<?php echo @$this->paginationControl($this->paginator, 'Sliding', '/partials/_pagination.phtml'); ?>
            	</div>
 			</div>
           </div>
  	  </div> 
  	  
  	<?php }else{ ?> 
  <div style="text-align:center;font-size:14px;font-weight:bold;"><?php echo $this->translate('No record found'); ?></div>
  <?php } ?>       
  <?php 
  else :
  ?>
  <div class="guide-outer-new">
  
          	<div class="voucher-heading ml15 mt5">
              	<h1><?php echo $this->page['pageTitle']; ?></h1>
              </div>
              
              <div class="voucher-text1 ml15 mt20" <?php echo $width; ?>>
              	<span class="word-wrap-without-margin-category"><?php echo stripslashes($this->page['content']); ?></span>
              </div>
           </div>
  </div> 
  <?php endif; ?> 
 
  <!-- Alle Winkels Left Ends -->
  <!-- End Special offer list -->          
   
         <!-- Alle Winkels Right Starts -->
		     <div id="right_container" class="alle-winkels-right" <?php echo $display; ?>>
		 	<?php
           	  	
           	  	echo $this->widget;
//            	  	echo FrontEnd_Helper_viewHelper::welcomeRocket()
//            	  	.FrontEnd_Helper_viewHelper::PopularWinkelsWidget()
//            	  	.FrontEnd_Helper_viewHelper::PopularCategoryWidget()
//            	  	.FrontEnd_Helper_viewHelper::otherhelpfullSavingTipsWidget();
				
			?>
		   </div>
		   
          <!-- Alle Winkels Right Ends -->
</div>

<?php break;}
default: ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo $this->translate('404 error - Page does not exist');?></title><!-- Add your page title here-->

    <?php echo $this->headLink ()->appendStylesheet ( HTTP_PATH . "public/css/front_end/404.css" );?><!-- load CSS file-->
    
<!--[if lte IE 7]>
	<?php echo $this->headLink ()->appendStylesheet ( HTTP_PATH . "public/css/front_end/ie.css" );?>
<![endif]-->

	
<!--[if IE 8]>
	<?php echo $this->headLink ()->appendStylesheet ( HTTP_PATH . "public/css/front_end/ie8.css" );?>
<![endif]-->


<!-- PNG fix for Internet Explorer-->
<!--[if IE]>
	<?php echo $this->headScript()->appendFile(HTTP_PATH . "public/js/front_end/DD_belatedPNG_0.0.7a.js");?>
	<?php echo $this->headScript()->appendFile(HTTP_PATH . "public/js/front_end/png_fix_elements.js");?>
<![endif]-->

</head>

<!--BEGIN SITE -->

<body>
	
    <!-- BEGIN 404 SCREEN-->
    <div id="screen-404">
  		<h2><?php echo $this->translate('Sorry - De opgevraagde pagina bestaat helaas niet');?></h2>
      <p><?php echo $this->translate('Wellicht helpt een van onderstaande links je verder:');?></p>
      <ul>
        <li><a href="javascript: history.go(-1)"><?php echo $this->translate('Terug naar de vorige pagina');?></a></li>
        <li><a href="/"><?php echo $this->translate('Naar de homepage');?></a></li>
        <li><a href="<?php echo  HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('link_veelgestelde-vragen')?>"><?php echo $this->translate('Naar veelgestelde vragen');?></a></li>
      </ul>
      <p><?php echo $this->translate('Populair');?></p>
      <ul>
        <li><a href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('link_alle-winkels-09-e'); ?>"><?php echo $this->translate('Alle winkels');?></a></li>
        <li><a href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('link_top-20');?>"><?php echo $this->translate('Populaire Codes');?></a></li>
        <li><a href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('link_nieuw');?>"><?php echo $this->translate('Nieuwe Codes');?></a></li>
        <li><a href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('link_plus');?>"><?php echo $this->translate('plus');?></a></li>
        <li><a href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('link_categorieen');?>"><?php echo $this->translate('Categorie&euml;n');?></a></li>
      </ul>
    </div>
    <!-- END 404 SCREEN-->
<script>
		
</script>
</body>
</html>
<?php

}
?>
