<?php
$this->headTitle()->append('Email Settings');
$this->headMeta('keyword', 'Description');
$this->headScript()->appendFile(PUBLIC_PATH  . "js/back_end/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH  . "js/back_end/emailSettings.js");
?>
<div class="newsletter-setting-container wrap columns-2">
    <div class='wrap columns-2'>
        <?php if($this->messageSuccess!='' || $this->messageError!='' ){?>
        <br><div class ="mainpage-content-colorbox success">
        <?php if($this->messageSuccess!=''){?>
        <span class="successserver"><?php echo $this->messageSuccess; ?></span>
        <?php }?>
        <?php if($this->messageError!=''){?>
        <span class="errorserver"><?php echo $this->messageError; ?></span>
        <?php } ?>
        </div>
        <?php
        }?>
    </div>
    <h1><?php echo $this->translate('Create account settings'); ?></h1>
    <div class="mainpage-content">
        <form name="emailSettings" method="post" id="emailSettings">
            <div class="mainpage-content-line mb10">
                <div class="mainpage-content-left">
                    <label><strong><?php echo $this->translate('Sender Email Address'); ?></strong></label>
                </div>
                <div class="mainpage-content-right">
                    <div class="mainpage-content-right-inner-left-other">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div data-toggle="buttons-checkbox" class="mainpage-content-right-inner-left-other">
                            <input type="text" value="<?php echo !empty($this->sendersEmailAddress) ? $this->sendersEmailAddress : '';?>" placeholder=<?php echo $this->translate('Email Address')?> name="senderEmail" id="senderEmail" 
                        class="span3">
                        </div>
                    </div>
                </div>
            </div>
            <div class="mainpage-content-line mb10">
                <div class="mainpage-content-left">
                    <label><strong><?php echo $this->translate('Sender Name'); ?></strong></label>
                </div>
                <div class="mainpage-content-right">
                    <div class="mainpage-content-right-inner-left-other">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div data-toggle="buttons-checkbox" class="mainpage-content-right-inner-left-other">
                            <input type="text" value="<?php echo !empty($this->sendersName) ? $this->sendersName : '';?>" placeholder=<?php echo $this->translate('Name')?> name="senderName" id="senderName" 
                        class="span3">
                        </div>
                    </div>
                </div>
            </div>
            <div class="mainpage-content-line mb10">
                <div class="mainpage-content-left"><label></label></div>
                <div class="mainpage-content-right">
                    <div class="mainpage-content-right-inner-left-other">
                    <div class="btn-group" data-toggle="buttons-checkbox">
                        <button class="btn btn-primary" type="submit"><?php echo $this->translate('Submit'); ?></button>
                    </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>