<?php
$this->headTitle()->append($this->translate('Visitor'));
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.dataTables.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/dataTableComman.js");
//$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.ui.widget.js");
//$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.iframe-transport.js");
//$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.fileupload.js");
//$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.fileupload-fp.js");
//$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.fileupload-ui.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/editvisitor.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
//$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
//$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "/css/jquery-ui-1.8.16.custom.css" );
$gender = $this->userDetail['gender'];
?>
<!-- Div for add edit user list  -->
<div id='editUserDiv' class="wrap columns-2">
         <h1><?php echo $this->translate('Edit Visitor'); ?>
         <button class="btn ml10" onClick="window.location.href='<?php echo HTTP_PATH; ?>admin/visitor/'"><?php echo $this->translate('Cancel');?></button>
         </h1>
         <form name="editRegister" method = "POST" action = '<?php echo HTTP_PATH; ?>admin/visitor/editvisitor' id='editRegister' enctype="multipart/form-data">
			<input type="hidden" name='id' id='id' value="<?php echo $this->id;?>" />
			<input type="hidden" name='visitorId' id='visitorId' value="<?php echo $this->id;?>" />
			<input type="hidden" name='favorite' id='favorite' value="<?php echo $this->favShopId;?>" />
			<input type="hidden" name='qString' id='qString' value='<?php echo $this->qstring; ?>' />
	          <div id="poststuff" class="metabox-holder has-right-sidebar">
              <div id="post-body">
              	<div>
              		<div class="mainpage-content">
                    	 <div class="mainpage-content-line mb10">
                        <div class="mainpage-content-left"><label><strong>Online</strong></label></div>
                        <div class="mainpage-content-right">
                            <div data-toggle="buttons-checkbox" class="btn-group">
                                
                                 <?php if( $this->userDetail['status']==1){?>
                                        <button type="button" class="btn btn-primary" onClick="setOnOff(event,'onlineStatus','on')"><?php echo $this->translate('On'); ?></button>                     
			                            <button type="button" class="btn  default" onClick="setOnOff(event,'onlineStatus','off')"><?php echo $this->translate('Off'); ?></button>
                            	<?php } else { ?>
                                            <button type="button" class="btn" onClick="setOnOff(event,'onlineStatus','on')"><?php echo $this->translate('On'); ?></button>                     
				                            <button type="button" class="btn btn-primary default" onClick="setOnOff(event,'onlineStatus','off')"><?php echo $this->translate('Off'); ?></button>
                            	<?php }?>
                             </div>
                        </div>          
                    </div>
                    	<div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Email'); ?></strong></label></div>
                            <div class="mainpage-content-right">
                                <div class="mainpage-content-right-inner-right-other"></div>
                                <div class="mainpage-content-right-inner-left-other"><input type="text" value = "<?php echo $this->userDetail['email'];?>" name="email" id="email" placeholder="<?php echo $this->translate('Email'); ?>" class="span3"></div>                        
                            </div>
                        </div>
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('First Name'); ?></strong></label></div>
                            <div class="mainpage-content-right">
                                <div class="mainpage-content-right-inner-right-other"></div>
                                <div class="mainpage-content-right-inner-left-other"><input type="text" value = "<?php echo $this->userDetail['firstName'];?>" id="firstName" name="firstName"  placeholder="<?php echo $this->translate('First Name'); ?>" class="span3"></div>                        
                            </div>
                        </div>
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Last Name'); ?></strong></label></div>
                            <div class="mainpage-content-right">
                                <div class="mainpage-content-right-inner-right-other"></div>
                                <div class="mainpage-content-right-inner-left-other"><input type="text"  value = "<?php echo $this->userDetail['lastName'];?>" id="lastName" name="lastName"  placeholder="<?php echo $this->translate('Last Name'); ?>" class="span3"></div>                        
                            </div>
                        </div>
               <!--  <div class="mainpage-content-line">
                        	<div class="mainpage-content-left"><label><strong><?php //echo $this->translate('Role'); ?></strong></label></div>
                            <div class="mainpage-content-right">
                                <div class="mainpage-content-right-inner-right-other"></div>
                                    <div class="mainpage-content-right-inner-left-other">
										<select name="role" id="role" class="mainpage-content-right-select_visitor">
                                        <?php /* 
                                          
											foreach ($this->roles as $key=>$role)
											{
												 echo " <option value='" . $key . "'>". $role . "</option>";
											}*/
                                   		?>
                                       
										
                                      </select>
                                    </div>
                                </div>
                        </div> -->
                          <div class="mainpage-content-line">
                        	<div class="mainpage-content-left"><label><strong>Gender</strong></label></div>
                            <div class="mainpage-content-right">
                                <div class="mainpage-content-right-inner-right-other"></div>
                                    <div class="mainpage-content-right-inner-left-other">
                                       <select id="select01" class="mainpage-content-right-select_visitor span3" name="gender">
                                       <option><?php echo $this->translate('Select');?></option>
                                        <option value="0" <?php if($gender==0){echo 'selected=selected';}else {echo '';}?>><?php echo $this->translate('Male');?></option>
                                        <option value="1" <?php if($gender==1){echo 'selected=selected';}else{ echo '';}?>><?php echo $this->translate('Female');?></option>                                        
                                      </select>
                                    </div
                                ></div>
                        </div>
 				<div class="mainpage-content-line">
                        	<div class="mainpage-content-left"><label><strong>Date of birth</strong></label></div>
                            <div class="mainpage-content-right">
                                <div class="mainpage-content-right-inner-right-other"></div>
                                    <div class="mainpage-content-right-inner-left-other">
                                       <?php echo $this->dateofbirth;?>
                                    </div>
                            </div>
                        </div>
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label><strong>Postal code</strong></label></div>
                            <div class="mainpage-content-right">
                                <div class="mainpage-content-right-inner-right-other"></div>
                                <div class="mainpage-content-right-inner-left-other"><input type="text" name="postalCode" id="postalCode" value="<?php echo $this->userDetail['postalCode'];?>" placeholder="Postal code" class="span3" ></div>                        
                            </div>
                        </div>
                        <div class="mainpage-content-line display-none">
                        <div class="mainpage-content-right-inner-right-other"><button class="btn" id="delFavShop" type="button" onClick="javascript:deleteFavShop();">Delete</button></div>
                            <div class="mainpage-content-left clear_none"><label><strong><?php echo $this->translate('Favourite shops'); ?></strong></label></div>
                            <div class="mainpage-content-right multiselectParent">                                
                                <div id="multiselectOverlay" class="multiselectOverlay"></div>
                                <div class="web-address-list multiselect editMode ">
                                 </div>                                                  
                            </div>
                        </div>
                        
                       
                        
                         <div class="mainpage-content-line mb10">
                        <div class="mainpage-content-left"><label><strong>Weekly newsletter</strong></label></div>
                        <div class="mainpage-content-right">
                            <div data-toggle="buttons-checkbox" class="btn-group">
                                <?php if($this->userDetail['weeklyNewsLetter']==1){?>
                                        <button type="button" class="btn btn-primary" onClick="setOnOff(event,'weekly','on')"><?php echo $this->translate('On'); ?></button>                     
			                            <button type="button" class="btn  default" onClick="setOnOff(event,'weekly','off')"><?php echo $this->translate('Off'); ?></button>
                            	<?php } else { ?>
                                            <button type="button" class="btn" onClick="setOnOff(event,'weekly','on')"><?php echo $this->translate('On'); ?></button>                     
				                            <button type="button" class="btn btn-primary default" onClick="setOnOff(event,'weekly','off')"><?php echo $this->translate('Off'); ?></button>
                            	<?php }?>
                               </div>
                                
                        </div>          
                    </div>
                    <div class="mainpage-content-line mb10">
                        <div class="mainpage-content-left"><label><strong>Fashion newsletter</strong></label></div>
                        <div class="mainpage-content-right">
                           <div data-toggle="buttons-checkbox" class="btn-group">
                               <?php if($this->userDetail['fashionNewsLetter']==1){?>
                                        <button type="button" class="btn btn-primary" onClick="setOnOff(event,'fashion','on')"><?php echo $this->translate('On'); ?></button>                     
			                            <button type="button" class="btn  default" onClick="setOnOff(event,'fashion','off')"><?php echo $this->translate('Off'); ?></button>
                            	<?php } else { ?>
                                            <button type="button" class="btn" onClick="setOnOff(event,'fashion','on')"><?php echo $this->translate('On'); ?></button>                     
				                            <button type="button" class="btn btn-primary default" onClick="setOnOff(event,'fashion','off')"><?php echo $this->translate('Off'); ?></button>
                            	<?php }?>
                             
                             
                              </div>
                        </div>          
                    </div>
                   
                    <div class="mainpage-content-line mb10">
                        <div class="mainpage-content-left"><label><strong>Travel newsletter</strong></label></div>
                        <div class="mainpage-content-right">
                             <div data-toggle="buttons-checkbox" class="btn-group">
                                <?php if($this->userDetail['travelNewsLetter']==1){?>
                                        <button type="button" class="btn btn-primary" onClick="setOnOff(event,'travel','on')"><?php echo $this->translate('On'); ?></button>                     
			                            <button type="button" class="btn  default" onClick="setOnOff(event,'travel','off')"><?php echo $this->translate('Off'); ?></button>
                            	<?php } else { ?>
                                            <button type="button" class="btn" onClick="setOnOff(event,'travel','on')"><?php echo $this->translate('On'); ?></button>                     
				                            <button type="button" class="btn btn-primary default" onClick="setOnOff(event,'travel','off')"><?php echo $this->translate('Off'); ?></button>
                            	<?php }?>
                              
                              </div>
                        </div>          
                    </div>
                   
                    <div class="mainpage-content-line mb10">
                        <div class="mainpage-content-left"><label><strong>Code alert</strong></label></div>
                        <div class="mainpage-content-right">
                             <div data-toggle="buttons-checkbox" class="btn-group">
                                <?php if($this->userDetail['codeAlert']==1){?>
                                        <button type="button" class="btn btn-primary" onClick="setOnOff(event,'code','on')"><?php echo $this->translate('On'); ?></button>                     
			                            <button type="button" class="btn  default" onClick="setOnOff(event,'code','off')"><?php echo $this->translate('Off'); ?></button>
                            	<?php } else { ?>
                                            <button type="button" class="btn" onClick="setOnOff(event,'code','on')"><?php echo $this->translate('On'); ?></button>                     
				                            <button type="button" class="btn btn-primary default" onClick="setOnOff(event,'code','off')"><?php echo $this->translate('Off'); ?></button>
                            	<?php }?>
                              </div>
                        </div>          
                    </div>   
                    <div class="mainpage-content-line mb10">
                        <div class="mainpage-content-left"><label><strong>Active</strong></label></div>
                        <div class="mainpage-content-right">
                             <div data-toggle="buttons-checkbox" class="btn-group">
                                <?php if($this->userDetail['active']){?>
                                        <button type="button" class="btn btn-primary" onClick="setOnOff(event,'active','on')"><?php echo $this->translate('On'); ?></button>                     
			                            <button type="button" class="btn  default" onClick="setOnOff(event,'active','off')"><?php echo $this->translate('Off'); ?></button>
                            	<?php } else { ?>
                                            <button type="button" class="btn" onClick="setOnOff(event,'active','on')"><?php echo $this->translate('On'); ?></button>                     
				                            <button type="button" class="btn btn-primary default" onClick="setOnOff(event,'active','off')"><?php echo $this->translate('Off'); ?></button>
                            	<?php }?>
                              </div>
                        </div>          
                    </div>                           
					<div class="mainpage-content-line mt10">
						<div class="mainpage-content-left"><label><strong><?php echo $this->translate('Keyword'); ?></strong></label></div>
                            <div class="mainpage-content-right  newKeyword">
                            	<div class="mainpage-content-right-inner-right-other" style="margin-top:2px;">
                           			 <div data-toggle="buttons-checkbox" class="btn-group">
                            			<button type="button" onclick="addKeyword();" name="add_Keyword" id="add_Keyword" class="btn btn-primary"><?php echo $this->translate("ADD KEYWORD")?></button>
                            		</div>
                           		 </div>
	                            <div class="mainpage-content-right-inner-left-other">
										<input type="text" placeholder="<?php echo $this->translate('keyword'); ?>" class="span3 new-keywords ignore3" name="newKeyword" id="newKeyword">
	                           </div>
                           </div>
                       </div>

                      <div class="mainpage-content-line mt10" id="visitorKeywordsList">
                            <div class="mainpage-content-left"></div>
                            	<div class="mainpage-content-right">
                            		<div class="mainpage-content-right-inner-left-other-visitor-keywords">
	                            		<ul id="visitorKeyword-list">
	                            		
	                            			<?php
	                            			   # check visitor has one or more keyword
	                            			   if(count($this->userDetail['visitorKeyword']) > 0)
	                            			   {
	                            			   		# traverse through all keywords
		                            			 	foreach ($this->userDetail['visitorKeyword'] as $value){
		                            				
	                            			   			#create delete button  
	                            						$aTag = sprintf("<a onclick='deleteKeyword(this)' herf='javascript:void(0);'>"
	                            								."<img src='%simages/kc-search-cross.png'></a>",	PUBLIC_PATH);
	                            							
	                            			   			# print keyword
		                            			 		printf("<li class='vistor-keyword-item' type='%s'><input type='hidden' value='%s' name='visitorKeywords[]' />%s%s</li>",
		                            			 						$value['keyword'], $value['keyword'] , $value['keyword'], $aTag ) ;
		                            				}
	                            			   }		
	                            			?>
	                           			</ul> 
                            		</div>
                         
                         <div class="clear mb10"></div>
                         </div>
                         </div>
                      
                        
                    </div>
                    
                </div>
              </div>
              <br class="clear">
            </div>
            
            <h1><?php echo $this->translate('Change Password'); ?></h1>
            
            <div id="poststuff" class="metabox-holder has-right-sidebar">
              <div id="post-body">
              	<div>
              		<div class="mainpage-content">
                    	
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('New Password'); ?></strong></label></div>
                            <div class="mainpage-content-right">
                                <div class="mainpage-content-right-inner-right-other"></div>
                                <div class="mainpage-content-right-inner-left-other"><input autocomplete="off" type="password" id="newPassword" name="newPassword" class="span3 passwordField"></div>                        
                            </div>
                        </div>
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Re-type New Password'); ?></strong></label></div>
                            <div class="mainpage-content-right">
                                <div class="mainpage-content-right-inner-right-other"></div>
                                                        
                                <div class="mainpage-content-right-inner-left-other"><input type="password" id="confirmNewPassword"  name="confirmNewPassword" placeholder="<?php echo $this->translate('Re-type New Password'); ?>" class="span3 passwordField"></div>                        
                            </div>
                        </div>          
                      </div>   
                    </div>
                    
                </div>
              </div>
              <br class="clear">
          <input type="hidden" name="active" id="active" value="<?php echo $this->userDetail['active'];?>" />
           <input type="hidden" name="status" id="status" value="<?php echo $this->userDetail['status'] ;?>" />
           <input  type="hidden" name="weekly" id="weekly" value="<?php echo $this->userDetail['weeklyNewsLetter']?>"/>
             <input type="hidden" name="fashion" id="fashion" value="<?php echo $this->userDetail['fashionNewsLetter'];?>"/>
              <input type="hidden" name="travel" id="travel" value="<?php echo $this->userDetail['travelNewsLetter'];?>"/>
              <input type="hidden" name="code" id="code" value="<?php echo $this->userDetail['codeAlert'] ;?>"/>
            <div class="mainpage-content-colorbox">
            	<button type="submit" class="btn btn-large btn-primary fl"><?php echo $this->translate('EDIT PROFILE'); ?></button>
                <a href="<?php echo HTTP_PATH; ?>admin/visitor"  class="fl m10"><strong><?php echo $this->translate('CANCEL'); ?></strong></a>
                <a id="deleteButton" href="javascript:void(0);"  onclick="deleteVisitor(event);" class="fl red mt10"><strong><?php echo $this->translate('DELETE VISITOR'); ?></strong></a>
            </div>
            
            </form>
            <!--poststuff -->
            
          </div>