<?php

$this->headTitle()->append($this->translate('Members'));
//$this->headMeta('keyword', 'noF');asdafasfasfasfa
//file for upload imagesjquery-ui-1.8.16.custom.min.js

//$this->headTitle()->append($this->translate('Visitor'));
$this->headScript()->appendFile(PUBLIC_PATH . "js/jquery.dataTables.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/dataTableComman.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/jquery.ui.widget.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/jquery.iframe-transport.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/jquery.fileupload.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/jquery.fileupload-fp.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/jquery.fileupload-ui.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/visitor.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/bootbox.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/select2.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/jquery-ui-1.8.16.custom.min.js");
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/jquery-ui-1.8.16.custom.css" );
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/select2.css" );
?>

<!-- Div for user list  -->

<div class="wrap columns-2" id="visitorListDiv">
<?php if($this->messageSuccess!='' || $this->messageError!='' ){?>
<br><div class ="mainpage-content-colorbox success">
<?php if($this->messageSuccess!=''){?>
<span class="successserver"><?php echo $this->messageSuccess; ?></span>
<?php }?>
<?php if($this->messageError!=''){?>
<span class="errorserver"><?php echo $this->messageError; ?></span>
<?php } ?>
</div>
<?php }?>

<h1 class="fl"><?php echo $this->translate('Members');?><!-- <input type="button" onClick="window.location.href='<?php echo HTTP_PATH; ?>admin/user/adduser'" Value='<?php //echo $this->translate('Add New Visitor'); ?>' name='addNew' class="btn ml10" /> --></h1>


          	<div class="clear"></div>
          <p class="text-right"><a href="<?php echo HTTP_PATH ?>admin/visitor/importvisitorlist"><?php echo $this->translate('Import List'); ?></a></p>
          <div class="mainpage-content-colorbox">

                <form class="form-search" name="searchForm" id="searchForm">
                    <div class="fl">

                         <input type="hidden" id='searchVisitor' name='searchVisitor' placeholder="Search Visitor.." style="width:200px;">
                     </div>

                     <div class="fl ml15">
                         <input type="hidden" id='searchEmail' name='searchEmail' placeholder="Search Email.." style="width:300px;">
					</div>
					<div class="mainpage-content-searchbart">
                        <div class="mainpage-content-right-searchbar">

                        	<button class="btn btn-primary" type="button" id="searchButton"><?php echo $this->translate('Search');?></button>
                        	<!--<button onclick="javascript:getUserList(search.value,'undefined')" class="btn btn-primary">Search</button> -->
                    	</div>
                    </div>

                </form>

            </div>

		<table id="visitorListTable" class="table table-bordered table-striped">
			<thead>
	            <tr>
	             	<th><?php echo $this->translate('Id'); ?></th>
	                <th><?php echo $this->translate('First Name'); ?></th>
	                <th><?php echo $this->translate('Last Name'); ?></th>
	                <th><?php echo $this->translate('Email'); ?></th>
	                <th><?php echo $this->translate('Opens'); ?></th>
	                <th><?php echo $this->translate('Clicks'); ?></th>
	                <th><?php echo $this->translate('Hard Bounces'); ?></th>
	                <th><?php echo $this->translate('Soft Bounces'); ?></th>
	               	<th width="155px"><?php echo $this->translate('Active'); ?></th>
	               	<th><?php echo $this->translate('weekly newsletter'); ?></th>
	               	<th><?php echo $this->translate('Date Of Registration'); ?></th>
	                <th><?php echo $this->translate('Delete'); ?></th>

	            </tr>
	        </thead>
	    </table>
</div><!-- End code of list users -->

