<?php $this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.dataTables.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/dataTableComman.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.ui.widget.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.iframe-transport.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.fileupload.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.fileupload-fp.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.fileupload-ui.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/media.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/jquery.textareaCounter.plugin.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/jquery-ui-1.8.16.custom.css" );
?>
<?php echo $this->headTitle()->append('Media List');?>
      <div style="overflow: hidden;" id="imbullbody-content">
        <div id="mediaList">
        <div class="wrap columns-2">
         
          <h1><?php echo $this->translate('Media library')?><button class="btn ml10" onClick="window.location.href='<?php echo HTTP_PATH.'admin/media/addmedia';?>'"><?php echo $this->translate('Add New');?></button></h1>
            <?php 
			 if($this->messageSuccess!='' || $this->messageError!='' ){?>
			
			<br><div class ="mainpage-content-colorbox success">
			
			<?php if($this->messageSuccess!=''){?>
			
			<span class="successserver"><?php echo $this->messageSuccess; ?>
			</span>
			<?php }?>
			
			<?php if($this->messageError!=''){?>
			
			<span class="errorserver"><?php echo $this->messageError; ?></span>
			<?php } ?>
			</div>
		<?php 
		}?>  	
            
            <table class="table table-bordered table-striped" id="mediaListTable">
                <colgroup>
                  <col class="span7">
                  <col class="span1">
                  <col class="span2">
                  <col class="span1">
                </colgroup>
                <thead>
                  <tr>
                   <th><?php echo $this->translate('Id');?></th>
                    <th><?php echo $this->translate('Name');?></th>
                    <th><?php echo $this->translate('Author')?></th>
                    <th><?php echo $this->translate('Alternate text')?></th>
                    <th><?php echo $this->translate('Date');?></th>
                    <th><?php echo $this->translate('Delete');?></th>
                  </tr>
                </thead>
            </table>
          </div>
          </div>
        
        <div class="clear"></div>
      </div>
    