<tr>
    <td bgcolor="#ffffff">
        <table width="100%" cellpadding="0" cellspacing="0">
            <tbody><tr>
                <td bgcolor="#ea973d" align="center" 
                    style="padding:12px 0 11px; font:18px/18px Arial, Helvetica, sans-serif; color:#373736;">
                    <a href="#" style="text-decoration:none; color:#ffffff;">New Code Alert!</a>
                </td>
            </tr>
            <tr>
                <td style="padding:28px 10px 30px 29px; border-bottom:1px solid #eaeaea;">
                    <table width="100%" cellpadding="0" cellspacing="0">
                        <tbody><tr>
                            <td valign="top" width="132" style="border:1px solid #dddddd; border-radius:5px;">
                                <table width="100%" cellpadding="0" cellspacing="0">
                                    <tbody><tr>
                                        <td height="70" align="center">
                                            <img src="img-02.png" style="vertical-align:top;" 
                                                width="102" height="70" alt="Davids Bridal">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td bgcolor="#ea973d" align="center" 
                                            style="border-radius:0 0 4px 4px;
                                            box-shadow:0 0 4px rgba(0,0,0,0.15);
                                            padding:6px 0 5px; 
                                            font:11px/17px Arial, Helvetica, sans-serif; 
                                            color:#fff;">
                                            <a href="#" style="text-decoration:none; color:#fff;">CODE</a>
                                        </td>
                                    </tr>
                                </tbody></table>
                            </td>
                            <td width="30"></td>
                            <td valign="top">
                                <table width="100%" cellpadding="0" cellspacing="0">
                                    <tbody><tr>
                                        <td>
                                            <table width="100%" cellpadding="0" cellspacing="0">
                                                <tbody><tr>
                                                    <td width="91" 
                                                        style="padding:0 0 2px; 
                                                        font:14px/17px Arial, Helvetica, sans-serif; 
                                                        color:#363636;">David's Bridal</td>
                                                    <td width="5"></td>
                                                    <td width="18" style="line-height:0;">
                                                        <img src="star.png" align="left" vspace="0" hspace="0" 
                                                        width="14" height="17" alt="">
                                                    </td>
                                                    <td width="281" 
                                                        style="font:bold 12px/17px Arial, Helvetica, sans-serif; 
                                                            color:#e89438;">Exclusive</td>
                                                </tr>
                                            </tbody></table>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td style="padding:0 0 15px; 
                                        font:16px/22px Arial, Helvetica, sans-serif; 
                                        color:#0077cc;"><a href="#" 
                                        style="text-decoration:underline; 
                                        color:#0077cc;">David's Bridal coupon code for $20 off regular<br>priced bridesmaid and party dresses</a></td>
                                    </tr>
                                    <tr>
                                        <td style="font:12px/17px Arial, Helvetica, sans-serif; 
                                        color:#32383e;">Added on November 4th 2013, Expires on Februari 31st 2014</td>
                                    </tr>
                                </tbody></table>
                            </td>
                        </tr>
                    </tbody></table>
                </td>
            </tr>
            <tr>
                <td bgcolor="#fafafa" align="center" style="padding:12px 0 11px; 
                font:bold 14px/17px Arial, Helvetica, sans-serif; color:#373736;">
                <a href="#" style="text-decoration:none; color:#373736;">Bekijk meer van onze top aanbiedingen &gt;</a>
                </td>
            </tr>
        </tbody></table>
    </td>
</tr>