<?php
$websiteName = FrontEnd_Helper_viewHelper::getWebsiteName();
$publicPath = HTTP_PATH.'public/images/front_end/';
$logo = FrontEnd_Helper_viewHelper::setEmailLogos(
    LOCALE,
    PUBLIC_PATH.'images/front_end/',
    $publicPath,
    'email-header-password.png'
);
?>
<table width="100%" align="center" cellpadding="0" cellspacing="0">
    <tr>
        <td bgcolor="#0077cc">
            <table width="600" align="center" bgcolor="#0077cc" cellpadding="0" cellspacing="0"
                style="background:url(<?php
            echo LOCALE != '' ? $publicPath.'emails/stamp_01.jpg' : $publicPath.'emails/stamp_01-kc.jpg';
            ?>) no-repeat right bottom;">
                <tr><td colspan="2" height="22"></td></tr>
                <tr>
                    <td width="205"></td>
                    <td width="431">
                        <a href="<?php echo HTTP_PATH_LOCALE; ?>"><img src="<?php echo $logo; ?>" border="0"
                            style="vertical-align:top;" width="237" height="47"
                            alt="Welcome to <?php echo $websiteName; ?>" /></a>
                    </td>
                </tr>
                <tr><td colspan="2" height="20"></td></tr>
            </table>
        </td>
    </tr>
    <tr>
        <td bgcolor="#ffffff" style="border:1px solid #e4e4e4; border-radius:5px;">
            <table width="100%" cellpadding="0" cellspacing="0">
                <tr>
                    <td style="padding:28px 10px 30px 29px; border-bottom:1px solid #eaeaea;">
                    <table width="100%" cellpadding="0" cellspacing="0">
                        <tbody><tr><td height="36"></td></tr>
                        <tr>
                            <td style="padding:0 0 21px; font:23px/27px Arial, Helvetica, sans-serif; color:#32383e;">
                                <?php echo FrontEnd_Helper_viewHelper::__email('email_Dear KC/ Flipit admin,'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:0 0 21px; font:23px/27px Arial, Helvetica, sans-serif; color:#32383e;">
                            <?php 
                                echo FrontEnd_Helper_viewHelper::__email(
                                'emial_The contact form is filled with the following data:'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:0 0 21px; font:23px/27px Arial, Helvetica, sans-serif; color:#32383e;">
                                <?php 
                                        echo FrontEnd_Helper_viewHelper::__email('email_Visitor Name:').' '.$this->name; 
                                ?>
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:0 0 21px; font:23px/27px Arial, Helvetica, sans-serif; color:#32383e;">
                                <?php 
                                    echo FrontEnd_Helper_viewHelper::__email('email_From email:').' '.$this->email; 
                                ?>
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:0 0 21px; font:23px/27px Arial, Helvetica, sans-serif; color:#32383e;">
                                <?php 
                                    echo FrontEnd_Helper_viewHelper::__email('email_Subject:').' '.$this->subject; 
                                ?>
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:0 0 21px; font:23px/27px Arial, Helvetica, sans-serif; color:#32383e;">
                                <?php 
                                    echo FrontEnd_Helper_viewHelper::__email('email_Message:').' '.$this->message; 
                                ?>
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:0 0 21px; font:23px/27px Arial, Helvetica, sans-serif; color:#32383e;">
                                <?php echo FrontEnd_Helper_viewHelper::__email('email_Have a great day,'); ?>
                            </td>
                        </tr>
                         <tr>
                            <td style="padding:0 0 21px; font:23px/27px Arial, Helvetica, sans-serif; color:#32383e;">
                                <?php echo FrontEnd_Helper_viewHelper::__email('email_Tech team!'); ?>
                            </td>
                        </tr>
                        <tr><td height="36"></td></tr>
                        </tbody>
                    </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>