<?php
$link = $this->httpPathLocale.FrontEnd_Helper_viewHelper::__link('link_top-20');
if($this->categoryInformation != null) {
    $categoryInformation = explode('|', $this->categoryInformation);
    $link = $this->httpPathLocale.FrontEnd_Helper_viewHelper::__link('link_categorieen').'/'.$categoryInformation[1];
    ?>
    <tr><td height="45"></td></tr>
    <tr>
        <td style="padding:0 0 25px 29px; font:24px/27px Arial, Helvetica, sans-serif; color:#32383e;">
            <?php echo FrontEnd_Helper_viewHelper::__email('Popular category:'). ' ' .$categoryInformation[0]; ?>
        </td>
    </tr>
    <?php 
    }
?>
<tr>
    <td bgcolor="#ffffff" style="border:1px solid #e4e4e4; border-radius:5px;">
        <table width="100%" cellpadding="0" cellspacing="0">
            <tbody>
                <?php
                    foreach ($this->topOffers as $topOffer) {
                        $topOffer = (object) $topOffer;
                        $offerPartial = new FrontEnd_Helper_OffersPartialFunctions();
                        $daysTillOfferExpires = $offerPartial->getDaysTillOfferExpires($topOffer->endDate);
                        $urlToShow = $offerPartial->getUrlToShow($topOffer, $this->httpPathLocale);
                 ?>
                <tr>
                    <td style="padding:28px 10px 30px 29px; border-bottom:1px solid #eaeaea;">
                        <table width="100%" cellpadding="0" cellspacing="0">
                            <tbody><tr>
                                <td width="132" style="border:1px solid #dddddd; border-radius:5px;">
                                    <table width="100%" cellpadding="0" cellspacing="0">
                                        <tbody><tr>
                                            <td height="66" align="center"><a href="<?php echo $this->httpPathLocale.$topOffer->shop['permalink']; ?>" style="text-decoration:none; color:#fff;"><img src="<?php echo $this->publicPathCdn.ltrim($topOffer->shop['logo']['path'],'/').'thum_big_'.$topOffer->shop['logo']['name']; ?>" style="vertical-align:top;" width="132" height="66" alt="<?php echo $topOffer->shop['name']; ?>"></a></td>
                                        </tr>
                                        <tr>
                                            <td bgcolor="#ea973d" align="center" style="border-radius:0 0 4px 4px; box-shadow:0 0 4px rgba(0,0,0,0.15); padding:6px 0 5px; font:11px/17px Arial, Helvetica, sans-serif; color:#fff;"><a href="<?php echo $this->httpPathLocale.$topOffer->shop['permalink']; ?>" style="text-decoration:none; color:#fff;"><?php echo FrontEnd_Helper_viewHelper::__email('CODE'); ?></a></td>
                                        </tr>
                                    </tbody></table>
                                </td>
                                <td width="30"></td>
                                <td valign="top">
                                    <table width="100%" cellpadding="0" cellspacing="0">
                                        <tbody><tr>
                                            <td style="padding:0 0 2px; font:14px/17px Arial, Helvetica, sans-serif; color:#363636;"><?php echo $topOffer->shop['name']; ?></td>
                                        </tr>
                                        <tr>
                                            <td style="padding:0 0 15px; font:16px/22px Arial, Helvetica, sans-serif; color:#0077cc;"><a href="<?php echo $this->httpPathLocale.$topOffer->shop['permalink']; ?>" style="text-decoration:underline; color:#0077cc;"><?php echo $topOffer->title; ?></a></td>
                                        </tr>
                                        <tr>
                                            <td style="font:12px/17px Arial, Helvetica, sans-serif; color:#32383e;"><?php echo BackEnd_Helper_MandrillHelper::getOfferDates($topOffer, $daysTillOfferExpires); ?></td>
                                        </tr>
                                    </tbody></table>
                                </td>
                            </tr>
                        </tbody></table>
                    </td>
                </tr>
                <?php } ?>
            <tr>
                <td bgcolor="#fafafa" align="center" style="border-radius:0 0 4px 4px; padding:12px 0 11px; font:bold 14px/17px Arial, Helvetica, sans-serif; color:#373736;"><a href="<?php echo $link; ?>" style="text-decoration:none; color:#373736;"><?php echo FrontEnd_Helper_viewHelper::__email('email_Bekijk meer van onze top aanbiedingen');?> &gt;</a></td>
            </tr>
        </tbody></table>
    </td>
</tr>