<tr>
    <td>
        <table width="600" align="center" cellpadding="0" cellspacing="0">
            <tbody>
            <?php 
            if ($this->newsLetterHeaderImage!='') {
                ?>
                <tr>
                    <td width="0"></td>
                    <td width="800">
                        <img width='728'
                            alt="<?php echo $this->newsLetterHeaderImage['name']; ?>" 
                            title="<?php echo $this->newsLetterHeaderImage['name']; ?>" 
                            src="<?php echo $this->publicPathCdn
                            .$this->newsLetterHeaderImage['path']
                            .$this->newsLetterHeaderImage['name'] ?>">
                    </td>
                </tr>
                <?php 
            } ?>
            </tbody>
        </table>
    </td>
</tr>