<?php
$locale = $this->locale != '' ? $this->locale.'/' : '';
$welcomelogo = FrontEnd_Helper_viewHelper::setEmailLogos(
    $locale,
    $this->publicLocalePath,
    $this->publicPath,
    'email-header-welcome.png'
);
$newsLetterlogo = FrontEnd_Helper_viewHelper::setEmailLogos(
    $locale,
    $this->publicLocalePath,
    $this->publicPath,
    'email-header-best.png'
);
$logo = $this->mailType == 'welcome'
    ? $welcomelogo : $newsLetterlogo;
?>
<tr>
    <td bgcolor="#0077cc">
        <table width="600" align="center" bgcolor="#0077cc" cellpadding="0" cellspacing="0"
            style="background:url(<?php
            echo $this->locale != '' ? $this->publicPath.'emails/stamp_01.jpg' : $this->publicPath.'emails/KC-stamp.png';
            ?>) no-repeat right bottom;">
            <tbody><tr><td colspan="2" height="22"></td></tr>
            <tr>
                <td width="<?php if ($this->locale != '') { echo '205'; } else { echo "120"; } ?>"></td>
                <td width="431">
                    <a href="<?php echo rtrim($this->httpPathLocale, '/'); ?>"><img src="<?php echo $logo; ?>" border="0" style="vertical-align:top;" alt="<?php echo $this->websiteName; ?>"></a>
                </td>
            </tr>
            <tr><td colspan="2" height="20"></td></tr>
        </tbody></table>
    </td>
</tr>