<table width="100%" align="center" cellpadding="0" cellspacing="0">
    <?php 
    if ($this->newsLetterFooterImage!='') {
        ?>
        <tr>
            <td align="center">
                <img width='728'
                    alt="<?php echo $this->newsLetterFooterImage['name']; ?>" 
                    title="<?php echo $this->newsLetterFooterImage['name']; ?>" 
                    src="<?php echo $this->publicPathCdn.$this->newsLetterFooterImage['path']
                    .$this->newsLetterFooterImage['name'] ?>">
            </td>
        </tr>
        <?php 
    } ?>
</table>