<?php
$locale = $this->locale != '' ? $this->locale.'/' : '';
$welcomelogo = FrontEnd_Helper_viewHelper::setEmailLogos(
    $locale,
    $this->publicLocalePath,
    $this->publicPath,
    'email-header-welcome'
);
$newsLetterlogo = FrontEnd_Helper_viewHelper::setEmailLogos(
    $locale,
    $this->publicLocalePath,
    $this->publicPath,
    'email-header-best'
);

$codeAlertLogo = FrontEnd_Helper_viewHelper::setEmailLogos(
    $locale,
    $this->publicLocalePath,
    $this->publicPath,
    'code-alert'
);
if($this->mailType == 'codeAlert') {
    $logo = $codeAlertLogo;
} else {
    $logo = $this->mailType == 'welcome' ? $welcomelogo : $newsLetterlogo;
}
?>
<tr>
    <td bgcolor="#0077cc">
        <table width="600" align="center" bgcolor="#0077cc" cellpadding="0" cellspacing="0"
            style="background:url(<?php
            echo $this->locale != '' ? $this->publicPath.'emails/stamp_01.jpg' : $this->publicPath.'emails/stamp_01-kc.jpg';
            ?>) no-repeat right bottom;">
            <tbody><tr><td colspan="2" height="22"></td></tr>
            <tr>
                <td width="205"></td>
                <td width="431">
                    <a href="<?php echo rtrim($this->httpPathLocale, '/'); ?>"><img src="<?php echo $logo; ?>" border="0" style="vertical-align:top;" alt="<?php echo $this->websiteName; ?>" title="<?php echo $this->websiteName; ?>"></a>
                </td>
            </tr>
            <?php 
            if ($this->newsLetterHeaderImage!='') {
                ?>
                <tr>
                    <td width="0"></td>
                    <td width="800">
                        <img width='728'
                            alt="<?php echo $this->newsLetterHeaderImage['name']; ?>" 
                            title="<?php echo $this->newsLetterHeaderImage['name']; ?>" 
                            src="<?php echo $this->publicPathCdn
                            .$this->newsLetterHeaderImage['path']
                            .$this->newsLetterHeaderImage['name'] ?>">
                    </td>
                </tr>
                <?php 
            } ?>
            <tr><td colspan="2" height="20"></td></tr>
        </tbody></table>
    </td>
</tr>