<table width="100%" align="center" cellpadding="0" cellspacing="0">
    <?php 
    if (isset($this->newsLetterFooterImage['path']) && !empty($this->newsLetterFooterImage['path'])) {
        ?>
        <tr>
            <td align="center">
                <?php 
                if (
                    isset($this->newsLetterFooterImage['footerurl']) 
                    && !empty($this->newsLetterFooterImage['footerurl'])) {
                    ?>
                    <a href="<?php echo $this->newsLetterFooterImage['footerurl']; ?>">
                    <?php 
                }
                ?>
                <img style="display: block; border-radius: 5px;" width='615'
                    alt="<?php echo $this->newsLetterFooterImage['name']; ?>" 
                    title="<?php echo $this->newsLetterFooterImage['name']; ?>" 
                    src="<?php echo $this->publicPathCdn.$this->newsLetterFooterImage['path']
                    .$this->newsLetterFooterImage['name'] ?>">
               <?php 
                if (
                    isset($this->newsLetterFooterImage['footerurl']) 
                    && !empty($this->newsLetterFooterImage['footerurl'])
                ) {
                    ?>
                    </a>
                    <?php 
                }
                ?>
            </td>
        </tr>
        <tr><td height="2"></td></tr>
        <?php 
    }
    ?>
</table>