<?php
$websiteName = FrontEnd_Helper_viewHelper::getWebsiteName($this->locale);
$publicPath = $this->httpPath.'public/images/';

if($this->locale == ''):
    $logo = $publicPath.'front_end/emails/email-footer-kc.png';
else :
    $logo = $publicPath.'logo-footer.png';
endif;
$emailFooterImage = '';
if ($this->newsLetterFooterImage!='') {
    $emailFooterImage = $this->partial(
        'emails/emailFooterImage.phtml',
        array(
            'newsLetterFooterImage' => $this->newsLetterFooterImage,
            'publicPathCdn' => $this->publicPathCdn
        )
    );
}
echo $emailFooterImage;
?>
<table width="100%" align="center" cellpadding="0" cellspacing="0">
    <tr><td height="46"></td></tr>
    <tr>
        <td align="center" style="padding:0 0 25px; font:12px/20px Arial, Helvetica, sans-serif; color:#878a8d;">
            <?php echo FrontEnd_Helper_viewHelper::__email('email_Je ontvangt deze nieuwsbrief omdat je ons toestemming hebt gegeven om je op de'); ?>
        <br>
            <?php echo FrontEnd_Helper_viewHelper::__email('email_hoogte te houden van onze laatste acties.'); ?> 
            <a href="<?php echo $this->siteUrl; ?>" style="text-decoration:none; color:#878a8d;"><?php echo $this->siteUrl; ?></a> <?php echo FrontEnd_Helper_viewHelper::__email('email_is een onderdeel van'); ?>
            <br>
            <?php echo FrontEnd_Helper_viewHelper::__email('email_Imbull. Weteringschans 120, 1017XT Amsterdam - KvK #34339618'); ?>
        </td>
    </tr>
    <tr>
        <td align="center" style="padding:0 0 37px; font:14px/17px Arial, Helvetica, sans-serif; color:#33383e;">
                <a href="*|loginLinkWithUnsubscribe|*" style="text-decoration:none; color:#33383e;"><?php echo FrontEnd_Helper_viewHelper::__email('email_Uitschrijven'); ?></a>
             | 
            <a href="*|loginLink|*" style="text-decoration:none; color:#33383e;"><?php echo FrontEnd_Helper_viewHelper::__email('email_Wijzigen profiel'); ?></a>
            | 
            <a href="<?php echo $this->httpPathLocale.FrontEnd_Helper_viewHelper::__link('link_info').'/'.FrontEnd_Helper_viewHelper::__link('link_contact'); ?>" style="text-decoration:none; color:#33383e;"><?php echo FrontEnd_Helper_viewHelper::__email('email_Contact'); ?></a>
        </td>
    </tr>
    <tr>
        <td align="center"><a href="<?php echo rtrim($this->httpPathLocale, '/'); ?>"><img src="<?php echo $logo; ?>" border="0" style="vertical-align:top;" alt="<?php echo $websiteName; ?>" title="<?php echo $websiteName; ?>"></a></td>
    </tr>
</table>