<?php
$websiteName = FrontEnd_Helper_viewHelper::getWebsiteName(LOCALE);
$publicPath = HTTP_PATH.'public/images/front_end/';
$locale = LOCALE != '' ? LOCALE.'/' : '';
$logo = FrontEnd_Helper_viewHelper::setEmailLogos(
    $locale,
    PUBLIC_PATH.'images/front_end/',
    $publicPath,
    'email-header-password'
);
?>
<table width="100%" align="center" cellpadding="0" cellspacing="0">
    <tr>
        <td bgcolor="#0077cc">
            <table width="600" align="center" bgcolor="#0077cc" cellpadding="0" cellspacing="0"
                style="background:url(<?php
            echo LOCALE != '' ? $publicPath.'emails/stamp_01.jpg' : $publicPath.'emails/stamp_01-kc.jpg';
            ?>) no-repeat right bottom;">
                <tr><td colspan="2" height="22"></td></tr>
                <tr>
                    <td width="205"></td>
                    <td width="431">
                        <a href="<?php echo rtrim(HTTP_PATH_LOCALE, '/'); ?>"><img src="<?php echo $logo; ?>" border="0"
                            style="vertical-align:top;"
                            alt="<?php echo $websiteName; ?>" /></a>
                    </td>
                </tr>
                <tr><td colspan="2" height="20"></td></tr>
            </table>
        </td>
    </tr>
    <tr>
        <td bgcolor="#ffffff" style="border:1px solid #e4e4e4; border-radius:5px;">
            <table width="100%" cellpadding="0" cellspacing="0">
                <tr>
                    <td style="padding:28px 10px 30px 29px; border-bottom:1px solid #eaeaea;">
                    <table width="100%" cellpadding="0" cellspacing="0">
                        <tbody><tr><td height="36"></td></tr>
                        <tr>
                            <td style="padding:0 0 21px; font:23px/27px Arial, Helvetica, sans-serif; color:#32383e;">
                            <?php echo FrontEnd_Helper_viewHelper::__email('email_Dear Flipit visitor'); ?></td>
                        </tr>
                        <tr>
                            <td style="padding:0 0 15px; font:14px/21px Arial, Helvetica, sans-serif; color:#373736;">
                            <?php echo FrontEnd_Helper_viewHelper::__email('email_We received a request to reset your account password.');?></td>
                        </tr>
                        <tr>
                            <td style="padding:0 0 30px; font:14px/17px Arial, Helvetica, sans-serif; color:#373736;">
                            <?php echo FrontEnd_Helper_viewHelper::__email('email_to reset click on the link below or copy and paste the URL into your browser'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:0 0 30px; font:14px/17px Arial, Helvetica, sans-serif; color:#373736;">
                                <a href="<?php echo $this->resetPasswordLink; ?>">
                                    <?php echo $this->resetPasswordLink; ?>
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:0 0 30px; font:14px/17px Arial, Helvetica, sans-serif; color:#373736;">
                                <?php echo FrontEnd_Helper_viewHelper::__email('email_Check out our support page for more information');?> <br>
                                <a href="<?php echo HTTP_PATH_LOCALE; ?>">
                                    <?php echo FrontEnd_Helper_viewHelper::__email('email_support page');?></a> 
                        </td>
                        </tr>
                        <tr>
                            <td style="padding:0 0 10px; font:14px/17px Arial, Helvetica, sans-serif; color:#373736;">
                            <?php echo FrontEnd_Helper_viewHelper::__email('email_Regards,'); ?></td>
                        </tr>
                        <tr>
                            <td style="font:14px/17px Arial, Helvetica, sans-serif; color:#373736;">
                                <?php echo FrontEnd_Helper_viewHelper::__email('email_Flipit team');?>
                            </td>
                        </tr>
                        <tr><td height="36"></td></tr>
                        </tbody>
                    </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>