<table width="100%" cellpadding="0" cellspacing="0">
<tbody>
    <tr>
        <td>
            <table width="100%" align="center" cellpadding="0" cellspacing="0">
                <tbody><tr>
                    <td bgcolor="#0077cc">
                        <table width="600" align="center" bgcolor="#0077cc" cellpadding="0" cellspacing="0" style="background:url(http://s1.postimg.org/8skrrjzkr/stamp_01.jpg) no-repeat right bottom;">
                            <tbody><tr><td colspan="2" height="22"></td></tr>
                            <tr>
                                <td width="205"></td>
                                <td width="431">
                                    <a href="http://www.flipit.com/"><img src="logo.png" border="0" style="vertical-align:top;" width="237" height="47" alt="Welcome to Flipit"></a>
                                </td>
                            </tr>
                            <tr><td colspan="2" height="20"></td></tr>
                        </tbody></table>
                    </td>
                </tr>
                <tr>
                    <td bgcolor="#ffffff" style="border:1px solid #e4e4e4;">
                        <table width="100%" cellpadding="0" cellspacing="0">
                            <tbody><tr>
                                <td width="28"></td>
                                <td width="227" valign="top">
                                    <table width="100%" cellpadding="0" cellspacing="0">
                                        <tbody><tr><td height="36"></td></tr>
                                        <tr>
                                            <td style="padding:0 0 21px; font:23px/27px Arial, Helvetica, sans-serif; color:#32383e;">Welkom to Flipit</td>
                                        </tr>
                                        <tr>
                                            <td style="padding:0 0 15px; font:14px/21px Arial, Helvetica, sans-serif; color:#373736;">Get ready to flip some great deals! We selected the top 10 offers in this email especially for you! Have some great time fliping deals!</td>
                                        </tr>
                                        <tr>
                                            <td style="padding:0 0 10px; font:14px/17px Arial, Helvetica, sans-serif; color:#373736;">Regards,</td>
                                        </tr>
                                        <tr>
                                            <td style="font:14px/17px Arial, Helvetica, sans-serif; color:#373736;">The Flipit Team</td>
                                        </tr>
                                    </tbody></table>
                                </td>
                                <td width="343" valign="top">
                                    <img src="img-01.png" style="vertical-align:top;" width="343" height="258" alt="">
                                </td>
                            </tr>
                        </tbody></table>
                    </td>
                </tr>
                <tr><td height="45"></td></tr>
                <tr>
                    <td style="padding:0 0 25px 29px; font:24px/27px Arial, Helvetica, sans-serif; color:#32383e;">Top 5 kortingscodes</td>
                </tr>
                <tr>
                    <td bgcolor="#ffffff" style="border:1px solid #e4e4e4; border-radius:5px;">
                        <table width="100%" cellpadding="0" cellspacing="0">
                            <tbody><tr>
                                <td style="padding:28px 10px 30px 29px; border-bottom:1px solid #eaeaea;">
                                    <table width="100%" cellpadding="0" cellspacing="0">
                                        <tbody><tr>
                                            <td width="132" style="border:1px solid #dddddd; border-radius:5px;">
                                                <table width="100%" cellpadding="0" cellspacing="0">
                                                    <tbody><tr>
                                                        <td height="70" align="center"><img src="img-02.png" style="vertical-align:top;" width="102" height="70" alt="Davids Bridal"></td>
                                                    </tr>
                                                    <tr>
                                                        <td bgcolor="#ea973d" align="center" style="border-radius:0 0 4px 4px; box-shadow:0 0 4px rgba(0,0,0,0.15); padding:6px 0 5px; font:11px/17px Arial, Helvetica, sans-serif; color:#fff;"><a href="#" style="text-decoration:none; color:#fff;">CODE</a></td>
                                                    </tr>
                                                </tbody></table>
                                            </td>
                                            <td width="30"></td>
                                            <td valign="top">
                                                <table width="100%" cellpadding="0" cellspacing="0">
                                                    <tbody><tr>
                                                        <td style="padding:0 0 2px; font:14px/17px Arial, Helvetica, sans-serif; color:#363636;">David's Bridal</td>
                                                    </tr>
                                                    <tr>
                                                        <td style="padding:0 0 15px; font:16px/22px Arial, Helvetica, sans-serif; color:#0077cc;"><a href="#" style="text-decoration:underline; color:#0077cc;">David's Bridal coupon code for $20 off regular<br>priced bridesmaid and party dresses</a></td>
                                                    </tr>
                                                    <tr>
                                                        <td style="font:12px/17px Arial, Helvetica, sans-serif; color:#32383e;">Added on November 4th 2013, Expires on Februari 31st 2014</td>
                                                    </tr>
                                                </tbody></table>
                                            </td>
                                        </tr>
                                    </tbody></table>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding:28px 10px 30px 29px; border-bottom:1px solid #eaeaea;">
                                    <table width="100%" cellpadding="0" cellspacing="0">
                                        <tbody><tr>
                                            <td width="132" style="border:1px solid #dddddd; border-radius:5px;">
                                                <table width="100%" cellpadding="0" cellspacing="0">
                                                    <tbody><tr>
                                                        <td height="70" align="center"><img src="img-02.png" style="vertical-align:top;" width="102" height="70" alt="Davids Bridal"></td>
                                                    </tr>
                                                    <tr>
                                                        <td bgcolor="#ea973d" align="center" style="border-radius:0 0 4px 4px; box-shadow:0 0 4px rgba(0,0,0,0.15); padding:6px 0 5px; font:11px/17px Arial, Helvetica, sans-serif; color:#fff;"><a href="#" style="text-decoration:none; color:#fff;">CODE</a></td>
                                                    </tr>
                                                </tbody></table>
                                            </td>
                                            <td width="30"></td>
                                            <td valign="top">
                                                <table width="100%" cellpadding="0" cellspacing="0">
                                                    <tbody><tr>
                                                        <td style="padding:0 0 2px; font:14px/17px Arial, Helvetica, sans-serif; color:#363636;">David's Bridal</td>
                                                    </tr>
                                                    <tr>
                                                        <td style="padding:0 0 15px; font:16px/22px Arial, Helvetica, sans-serif; color:#0077cc;"><a href="#" style="text-decoration:underline; color:#0077cc;">David's Bridal coupon code for $20 off regular<br>priced bridesmaid and party dresses</a></td>
                                                    </tr>
                                                    <tr>
                                                        <td style="font:12px/17px Arial, Helvetica, sans-serif; color:#32383e;">Added on November 4th 2013, Expires on Februari 31st 2014</td>
                                                    </tr>
                                                </tbody></table>
                                            </td>
                                        </tr>
                                    </tbody></table>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding:28px 10px 30px 29px; border-bottom:1px solid #eaeaea;">
                                    <table width="100%" cellpadding="0" cellspacing="0">
                                        <tbody><tr>
                                            <td width="132" style="border:1px solid #dddddd; border-radius:5px;">
                                                <table width="100%" cellpadding="0" cellspacing="0">
                                                    <tbody><tr>
                                                        <td height="70" align="center"><img src="img-02.png" style="vertical-align:top;" width="102" height="70" alt="Davids Bridal"></td>
                                                    </tr>
                                                    <tr>
                                                        <td bgcolor="#ea973d" align="center" style="border-radius:0 0 4px 4px; box-shadow:0 0 4px rgba(0,0,0,0.15); padding:6px 0 5px; font:11px/17px Arial, Helvetica, sans-serif; color:#fff;"><a href="#" style="text-decoration:none; color:#fff;">CODE</a></td>
                                                    </tr>
                                                </tbody></table>
                                            </td>
                                            <td width="30"></td>
                                            <td valign="top">
                                                <table width="100%" cellpadding="0" cellspacing="0">
                                                    <tbody><tr>
                                                        <td style="padding:0 0 2px; font:14px/17px Arial, Helvetica, sans-serif; color:#363636;">David's Bridal</td>
                                                    </tr>
                                                    <tr>
                                                        <td style="padding:0 0 15px; font:16px/22px Arial, Helvetica, sans-serif; color:#0077cc;"><a href="#" style="text-decoration:underline; color:#0077cc;">David's Bridal coupon code for $20 off regular<br>priced bridesmaid and party dresses</a></td>
                                                    </tr>
                                                    <tr>
                                                        <td style="font:12px/17px Arial, Helvetica, sans-serif; color:#32383e;">Added on November 4th 2013, Expires on Februari 31st 2014</td>
                                                    </tr>
                                                </tbody></table>
                                            </td>
                                        </tr>
                                    </tbody></table>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding:28px 10px 30px 29px; border-bottom:1px solid #eaeaea;">
                                    <table width="100%" cellpadding="0" cellspacing="0">
                                        <tbody><tr>
                                            <td width="132" style="border:1px solid #dddddd; border-radius:5px;">
                                                <table width="100%" cellpadding="0" cellspacing="0">
                                                    <tbody><tr>
                                                        <td height="70" align="center"><img src="img-02.png" style="vertical-align:top;" width="102" height="70" alt="Davids Bridal"></td>
                                                    </tr>
                                                    <tr>
                                                        <td bgcolor="#ea973d" align="center" style="border-radius:0 0 4px 4px; box-shadow:0 0 4px rgba(0,0,0,0.15); padding:6px 0 5px; font:11px/17px Arial, Helvetica, sans-serif; color:#fff;"><a href="#" style="text-decoration:none; color:#fff;">CODE</a></td>
                                                    </tr>
                                                </tbody></table>
                                            </td>
                                            <td width="30"></td>
                                            <td valign="top">
                                                <table width="100%" cellpadding="0" cellspacing="0">
                                                    <tbody><tr>
                                                        <td style="padding:0 0 2px; font:14px/17px Arial, Helvetica, sans-serif; color:#363636;">David's Bridal</td>
                                                    </tr>
                                                    <tr>
                                                        <td style="padding:0 0 15px; font:16px/22px Arial, Helvetica, sans-serif; color:#0077cc;"><a href="#" style="text-decoration:underline; color:#0077cc;">David's Bridal coupon code for $20 off regular<br>priced bridesmaid and party dresses</a></td>
                                                    </tr>
                                                    <tr>
                                                        <td style="font:12px/17px Arial, Helvetica, sans-serif; color:#32383e;">Added on November 4th 2013, Expires on Februari 31st 2014</td>
                                                    </tr>
                                                </tbody></table>
                                            </td>
                                        </tr>
                                    </tbody></table>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding:28px 10px 30px 29px; border-bottom:1px solid #eaeaea;">
                                    <table width="100%" cellpadding="0" cellspacing="0">
                                        <tbody><tr>
                                            <td width="132" style="border:1px solid #dddddd; border-radius:5px;">
                                                <table width="100%" cellpadding="0" cellspacing="0">
                                                    <tbody><tr>
                                                        <td height="70" align="center"><img src="img-02.png" style="vertical-align:top;" width="102" height="70" alt="Davids Bridal"></td>
                                                    </tr>
                                                    <tr>
                                                        <td bgcolor="#ea973d" align="center" style="border-radius:0 0 4px 4px; box-shadow:0 0 4px rgba(0,0,0,0.15); padding:6px 0 5px; font:11px/17px Arial, Helvetica, sans-serif; color:#fff;"><a href="#" style="text-decoration:none; color:#fff;">CODE</a></td>
                                                    </tr>
                                                </tbody></table>
                                            </td>
                                            <td width="30"></td>
                                            <td valign="top">
                                                <table width="100%" cellpadding="0" cellspacing="0">
                                                    <tbody><tr>
                                                        <td style="padding:0 0 2px; font:14px/17px Arial, Helvetica, sans-serif; color:#363636;">David's Bridal</td>
                                                    </tr>
                                                    <tr>
                                                        <td style="padding:0 0 15px; font:16px/22px Arial, Helvetica, sans-serif; color:#0077cc;"><a href="#" style="text-decoration:underline; color:#0077cc;">David's Bridal coupon code for $20 off regular<br>priced bridesmaid and party dresses</a></td>
                                                    </tr>
                                                    <tr>
                                                        <td style="font:12px/17px Arial, Helvetica, sans-serif; color:#32383e;">Added on November 4th 2013, Expires on Februari 31st 2014</td>
                                                    </tr>
                                                </tbody></table>
                                            </td>
                                        </tr>
                                    </tbody></table>
                                </td>
                            </tr>
                            <tr>
                                <td bgcolor="#fafafa" align="center" style="border-radius:0 0 4px 4px; padding:12px 0 11px; font:bold 14px/17px Arial, Helvetica, sans-serif; color:#373736;"><a href="#" style="text-decoration:none; color:#373736;">Bekijk meer van onze top aanbiedingen &gt;</a></td>
                            </tr>
                        </tbody></table>
                    </td>
                </tr>
            </tbody></table>
        </td>
    </tr>
</tbody>
</table>
