<tr>
    <td bgcolor="#ffffff" style="border:1px solid #e4e4e4;">
        <table width="100%" cellpadding="0" cellspacing="0">
            <tbody><tr>
                <td width="28"></td>
                <td width="227" valign="top">
                    <table width="100%" cellpadding="0" cellspacing="0">
                        <tbody><tr><td height="36"></td></tr>
                        <tr>
                            <td style="padding:0 0 21px; font:23px/27px Arial, Helvetica, sans-serif; color:#32383e;"><?php echo FrontEnd_Helper_viewHelper::__email('email_Welkom to').' '.$this->firstName.','; ?></td>
                        </tr>
                        <tr>
                            <td style="padding:0 0 15px; font:14px/21px Arial, Helvetica, sans-serif; color:#373736;"><?php echo FrontEnd_Helper_viewHelper::__email('email_Get ready to flip some great deals! We selected the top 10 offers in this email especially for you! Have some great time fliping deals!');?></td>
                        </tr>
                        <tr>
                            <td style="padding:0 0 10px; font:14px/17px Arial, Helvetica, sans-serif; color:#373736;"><?php echo FrontEnd_Helper_viewHelper::__email('email_Regards,');?></td>
                        </tr>
                        <tr>
                            <td style="font:14px/17px Arial, Helvetica, sans-serif; color:#373736;"><?php echo FrontEnd_Helper_viewHelper::__email('email_The Flipit Team'); ?></td>
                        </tr>
                    </tbody></table>
                </td>
                <td width="343" valign="top">
                    <img src="<?php echo $this->publicPath.'emails/img-01.png'; ?>" style="vertical-align:top;" width="343" height="258" alt="" title="Welcome Back">
                </td>
            </tr>
        </tbody></table>
    </td>
</tr>
<tr><td height="45"></td></tr>
<tr>
    <td style="padding:0 0 25px 29px; font:24px/27px Arial, Helvetica, sans-serif; color:#32383e;"><?php echo FrontEnd_Helper_viewHelper::__email('email_Top 5 kortingscodes'); ?></td>
</tr>