<?php

if (defined('HTTP_PATH')) {
    $httpPath = LOCALE != '' ? 'http://www.flipit.com/' : 'http://www.kortingscode.nl/';
    $locale = LOCALE;
    $httpPathLocale = LOCALE != '' ? 'http://www.flipit.com/'.LOCALE.'/' : 'http://www.kortingscode.nl/';
    $publicPathCdn = LOCALE != '' ? 'http://img.flipit.com/public/'.LOCALE.'/' : 'http://img.kortingscode.nl/public/';
} else {
    $httpPath = $this->pathConstants['httpPath'].'/';
    $locale = $this->pathConstants['locale'];
    $httpPathLocale = $this->pathConstants['httpPathLocale'];
    $publicPathCdn = $this->pathConstants['publicPathCdn'];
}

$websiteName = FrontEnd_Helper_viewHelper::getWebsiteName($locale);
$publicPath = $httpPath.'public/images/front_end/';

if($locale == ''):
    $logo = $publicPath.'emails/kortingscode-logo.png';
else :
    $logo = $publicPath.'emails/logo-forgotpassword.png';
endif;

$emailsViewPath = 'emails/';
$topOffers = '';
if(!empty($this->topOffers)) {
    $topOffers = $this->partial(
        $emailsViewPath. 'emailOffers.phtml',
        array(
            'topOffers' => $this->topOffers,
            'categoryName' => null,
            'httpPathLocale' => $httpPathLocale,
            'publicPathCdn' => $publicPathCdn
        )
    );
}

$topVouchercodes = '';
if(!empty($this->topVouchercodes)) {
    $topVouchercodes = $this->partial(
        $emailsViewPath. 'emailOffers.phtml',
        array(
            'topOffers' => $this->topVouchercodes,
            'categoryName' => null,
            'httpPathLocale' => $httpPathLocale,
            'publicPathCdn' => $publicPathCdn
        )
    );
}

$categoryVouchers = '';
if(!empty($this->categoryVouchers)) {
    $categoryVouchers = $this->partial(
        $emailsViewPath. 'emailOffers.phtml',
        array(
            'topOffers' => $this->categoryVouchers,
            'categoryName' => $this->categoryName,
            'httpPathLocale' => $httpPathLocale,
            'publicPathCdn' => $publicPathCdn
        )
    );
}  
?>
<table width="100%" cellpadding="0" cellspacing="0">
<tbody>
    <tr>
        <td>
            <table width="100%" align="center" cellpadding="0" cellspacing="0">
                <tbody><tr>
                    <td bgcolor="#0077cc">
                        <table width="600" align="center" bgcolor="#0077cc" cellpadding="0" cellspacing="0" style="background:url(<?php echo $publicPath.'emails/stamp_01.jpg'; ?>) no-repeat right bottom;">
                            <tbody><tr><td colspan="2" height="22"></td></tr>
                            <tr>
                                <td width="205"></td>
                                <td width="431">
                                    <a href="<?php echo $httpPathLocale; ?>"><img src="<?php echo $logo; ?>" border="0" style="vertical-align:top;" width="237" height="47" alt="Welcome to <?php echo $websiteName;?>"></a>
                                </td>
                            </tr>
                            <tr><td colspan="2" height="20"></td></tr>
                        </tbody></table>
                    </td>
                </tr>
                <?php if(!empty($this->topOffers)) { ?>
                <tr>
                    <td bgcolor="#ffffff" style="border:1px solid #e4e4e4;">
                        <table width="100%" cellpadding="0" cellspacing="0">
                            <tbody><tr>
                                <td width="28"></td>
                                <td width="227" valign="top">
                                    <table width="100%" cellpadding="0" cellspacing="0">
                                        <tbody><tr><td height="36"></td></tr>
                                        <tr>
                                            <td style="padding:0 0 21px; font:23px/27px Arial, Helvetica, sans-serif; color:#32383e;"><?php echo FrontEnd_Helper_viewHelper::__email('email_Welkom to '.$websiteName); ?></td>
                                        </tr>
                                        <tr>
                                            <td style="padding:0 0 15px; font:14px/21px Arial, Helvetica, sans-serif; color:#373736;"><?php echo FrontEnd_Helper_viewHelper::__email('email_Get ready to flip some great deals! We selected the top 10 offers in this email especially for you! Have some great time fliping deals');?>!</td>
                                        </tr>
                                        <tr>
                                            <td style="padding:0 0 10px; font:14px/17px Arial, Helvetica, sans-serif; color:#373736;"><?php echo FrontEnd_Helper_viewHelper::__email('email_Regards');?>,</td>
                                        </tr>
                                        <tr>
                                            <td style="font:14px/17px Arial, Helvetica, sans-serif; color:#373736;"><?php echo FrontEnd_Helper_viewHelper::__email('email_The '.$websiteName.' Team'); ?></td>
                                        </tr>
                                    </tbody></table>
                                </td>
                                <td width="343" valign="top">
                                    <img src="<?php echo $publicPath.'emails/img-01.png'; ?>" style="vertical-align:top;" width="343" height="258" alt="">
                                </td>
                            </tr>
                        </tbody></table>
                    </td>
                </tr>
                <tr><td height="45"></td></tr>
                <tr>
                    <td style="padding:0 0 25px 29px; font:24px/27px Arial, Helvetica, sans-serif; color:#32383e;"><?php echo FrontEnd_Helper_viewHelper::__email('email_Top 5 kortingscodes'); ?></td>
                </tr>
                <?php
                }
                echo $topOffers;
                echo $topVouchercodes;
                echo $categoryVouchers;
                ?>
            </tbody></table>
        </td>
    </tr>
</tbody>
</table>