<tr>
    <td bgcolor="#ffffff" style="border:1px solid #e4e4e4;">
        <table width="100%" cellpadding="0" cellspacing="0">
            <tbody><tr>
                <td width="28"></td>
                <td width="227" valign="top">
                    <table width="100%" cellpadding="0" cellspacing="0">
                        <tbody><tr><td height="36"></td></tr>
                        <tr>
                            <td style="padding:0 0 21px; font:23px/27px Arial, Helvetica, sans-serif; color:#32383e;"><?php echo FrontEnd_Helper_viewHelper::__email('email_Hoi').' '.$this->firstName.','; ?></td>
                        </tr>
                        <tr>
                            <td style="padding:0 0 15px; font:14px/21px Arial, Helvetica, sans-serif; color:#373736;"><?php echo FrontEnd_Helper_viewHelper::__email("email_You're all set to start receiving our newsletter with the best vouchercodes, next to that you can also receive code alerts of your favourite stores.")." ".FrontEnd_Helper_viewHelper::__email("email_Just optimize your")." "."<a href='*|loginLink|*' style='text-decoration:underline; color:#33383e;'>profile</a>"." ".FrontEnd_Helper_viewHelper::__email("email_and start saving.");?></td>
                        </tr>
                        <tr>
                            <td style="padding:0 0 10px; font:14px/17px Arial, Helvetica, sans-serif; color:#373736;"><?php echo FrontEnd_Helper_viewHelper::__email("email_To get you started already, find here today's hottest vourchercodes!");?></td>
                        </tr>
                    </tbody></table>
                </td>
                <td width="343" valign="top">
                    <img src="<?php echo $this->publicPath.'emails/img-01.png'; ?>" style="vertical-align:top;" width="343" height="258" alt="">
                </td>
            </tr>
        </tbody></table>
    </td>
</tr>
<tr><td height="45"></td></tr>
<tr>
    <td style="padding:0 0 25px 29px; font:24px/27px Arial, Helvetica, sans-serif; color:#32383e;"><?php echo FrontEnd_Helper_viewHelper::__email('email_Top 5 kortingscodes'); ?></td>
</tr>