<?php
$this->headTitle()->append('Account Settings');
$this->headMeta('keyword', 'Description');
$this->headLink()->appendStylesheet(PUBLIC_PATH . "css/datepicker.css");
$this->headLink()->appendStylesheet(PUBLIC_PATH . "css/timepicker.css");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/ckeditor/ckeditor.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/ckeditor/config.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/news-letter-images.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/accountsetting.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/accountsetting2.js");
$this->headScript()->appendFile(PUBLIC_PATH  . "js/back_end/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
$this->headLink()->appendStylesheet(PUBLIC_PATH . "css/jquery-ui-1.8.16.custom.css");
$this->headScript()->appendFile(PUBLIC_PATH . "js/bootstrap-datepicker.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/bootstrap-timepicker.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/select2.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/jquery.ui.widget.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/jquery.iframe-transport.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/jquery.fileupload.js");
?>

<script type="text/javascript">

var CKEDITOR_BASEPATH = "<?php echo PUBLIC_PATH . "js/ckeditor/" ; ?>" ;

</script>


       <div class="newsletter-setting-container wrap columns-2">
                 <div class='wrap columns-2'>
		<?php if($this->messageSuccess!='' || $this->messageError!='' ){?>
		<br><div class ="mainpage-content-colorbox success">
		<?php if($this->messageSuccess!=''){?>
		<span class="successserver"><?php echo $this->messageSuccess; ?></span>
		<?php }?>
		<?php if($this->messageError!=''){?>
		<span class="errorserver"><?php echo $this->messageError; ?></span>
		<?php } ?>
		</div>
		<?php
		}?>
		</div>
           <h1><?php echo $this->translate('Create account settings'); ?><!-- <button  onclick="cancelAccountSettings();" class="btn ml10"></button> --></h1>
            <div class="mainpage-content">
            	<form name="speacialForm" method="post" id="speacialForm" action="">
            	   <div class="mainpage-content-line mb10">
						<div class="mainpage-content-left">
							<label><strong><?php echo $this->translate('Sender Email Address'); ?></strong></label>
						</div>
						<div class="mainpage-content-right">

							<div class="mainpage-content-right-inner-left-other">
							<div class="mainpage-content-right-inner-right-other"></div>
								<div data-toggle="buttons-checkbox" class="mainpage-content-right-inner-left-other">
									<input type="text" value="<?php echo !empty($this->data[0]['emailperlocale']) ? $this->data[0]['emailperlocale'] : '';?>" placeholder=<?php echo $this->translate('Sender')?> name="senderEmail" id="senderEmail" onblur="saveSenderEmail(this)"
									class="span3">
								</div>
							</div>
						</div>
					</div>

		    		<div class="mainpage-content-line mb10">
						<div class="mainpage-content-left">
							<label><strong><?php echo $this->translate('Sender Name'); ?></strong></label>
						</div>
						<div class="mainpage-content-right">

							<div class="mainpage-content-right-inner-left-other">
							<div class="mainpage-content-right-inner-right-other"></div>
								<div data-toggle="buttons-checkbox" class="mainpage-content-right-inner-left-other">
									<input type="text" value="<?php echo !empty($this->data[0]['sendername']) ? $this->data[0]['sendername'] : '';?>" placeholder=<?php echo $this->translate('Name')?> name="senderName" id="senderName" onblur="saveSenderEmail(this)"
									class="span3">
								</div>
							</div>
						</div>
					</div>

					<div class="mainpage-content-line mb10">
						<div class="mainpage-content-left">
							<label><strong><?php echo $this->translate('Email Subject'); ?></strong></label>
						</div>
						<div class="mainpage-content-right">

							<div class="mainpage-content-right-inner-left-other">
							<div class="mainpage-content-right-inner-right-other"></div>
								<div data-toggle="buttons-checkbox" class="mainpage-content-right-inner-left-other">
									<input type="text" value="<?php echo !empty($this->data[0]['emailsubject']) ? $this->data[0]['emailsubject'] : '';?>" placeholder=<?php echo $this->translate("Subject")?> name="emailSubject" id="emailSubject" onblur="saveSenderEmail(this)"
									class="span3">
								</div>
							</div>
						</div>
					</div>

	              	<div class="mainpage-content-line mb10">
						<div class="mainpage-content-left">
							<label><strong><?php echo $this->translate('Email Header'); ?></strong></label>
						</div>
						<div class="mainpage-content-right">
							<div class="mainpage-content-line">
								<div class="mainpage-content-right-inner-left-other">
									<div class="">
										<textarea name="emailHeader"  id="emailHeader" class="" style="height:135px;"><?php echo !empty($this->data[0]['email_header']) ? $this->data[0]['email_header'] : '';?></textarea>
									</div>
								</div>
							</div>
						</div>
					</div>

                    <div class="mainpage-content-line mb10">
                        <div class="mainpage-content-left">
                            <label><strong><?php echo $this->translate('Newsletter Header Image'); ?></strong></label>
                        </div>
                        <div class="mainpage-content-right">
                            <div class="mainpage-content-line">
                                <div class="mainpage-content-right-inner-left-other">
                                    <div class="mainpage-content-line header-image-cont">
                                        <div class="mainpage-content-right-inner"></div>
                                        <div class="mainpage-content-right-inner">
                                            <div class='browse-container'>            
                                                <?php  
                                                if (!empty($this->newsletterHeaderImage['path'])) { 
                                                    ?>
                                                    <img class='image-container' 
                                                        src="<?php echo PUBLIC_PATH_CDN
                                                        .$this->newsletterHeaderImage['path']
                                                        .urldecode($this->newsletterHeaderImage['name']); ?>">
                                                    <?php 
                                                } ?>
                                            </div>
                                            <div class="mainpage-content-right-inner-left-other"></div>
                                            <div class="progress-file-detail hide">
                                                <div>
                                                    <img alt="uploadig" 
                                                        src="http://www.flipit.com/public/images/back_end/ajax-loader-tran.gif">
                                                    <span id="selected-filename"></span>
                                                </div>
                                                <div class="progress progress-success progress-striped" id="progress">
                                                    <div class="bar" style="width: 99%;"></div>
                                                </div>
                                            </div>
                                            <div class="mainpage-content-right-inner-right-other">
                                                <span class="message help-inline success margin-bottom-tenpx"></span>
                                            </div>
                                            <?php 
                                            if(empty($this->newsletterHeaderImage['path'])) {
                                                ?>
                                                <input type="file"  id="newsLetterHeaderImage" 
                                                    class="span3 margin-bottom-tenpx" 
                                                    name="newsLetterHeaderImage">
                                                <?php 
                                            } else {
                                                ?>
                                                <button class="btn btn-primary" type="button" 
                                                    alt = "<?php echo urldecode($this->newsletterHeaderImage['name']); ?>" 
                                                    id="delete-header-image-btn">
                                                    <?php echo $this->translate("Delete Image");?>
                                                </button>
                                                <?php 
                                            } 
                                            ?>  
                                            <button class="btn btn-primary hide" type="button" 
                                                alt = "<?php echo urldecode($this->newsletterHeaderImage['name']); ?>" 
                                                id="delete-header-image-btn">
                                                <?php echo $this->translate("Delete Image");?>
                                            </button>
                                            <button class="btn btn-primary hide" type="button" 
                                                id="update-header-image-btn">
                                                <?php echo $this->translate("Update Image");?>
                                            </button>
                                            <div class="margin-bottom-tenpx">
                                                <span class="help-inline" id="logo_file_message">
                                                    <?php echo $this->translate("Image Size: 615px x 162px (*.jpg or *.png file only)") . "&nbsp;" . $this->translate("Max filesize:") . "&nbsp;" . ini_get('upload_max_filesize'); ?>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="mainpage-content-line mb10">
                        <div class="mainpage-content-left">
                            <label><strong><?php echo $this->translate('Newsletter header image url'); ?></strong></label>
                        </div>
                        <div class="mainpage-content-right">
                            <div class="mainpage-content-right-inner-left-other">
                            <div class="mainpage-content-right-inner-right-other"></div>
                                <div data-toggle="buttons-checkbox" class="mainpage-content-right-inner-left-other">
                                    <input type="text" 
                                    value="<?php echo !empty($this->newsletterHeaderImageUrl['headerurl']) ? $this->newsletterHeaderImageUrl['headerurl'] : '';?>" 
                                    placeholder=<?php echo $this->translate("https://abc.com")?> 
                                    name="headerurl" id="headerurl" onblur="saveNewsletterBannerUrl(this)"
                                    class="span3">
                                </div>
                            </div>
                        </div>
                    </div>

		            <div class="mainpage-content-line mb10">
						<div class="mainpage-content-left">
							<label><strong><?php echo $this->translate('Email Footer'); ?></strong></label>
						</div>
						<div class="mainpage-content-right">
							<div class="mainpage-content-line">
								<div class="mainpage-content-right-inner-left-other">
									<div class="">
										<textarea name="emailFooter" id="emailFooter" class="" style="height:135px;"><?php echo !empty($this->data[0]['email_footer']) ? $this->data[0]['email_footer'] : '';?></textarea>
									</div>
								</div>
							</div>
						</div>
					</div>


					<div class="mainpage-content-line mb10">
                        <div class="mainpage-content-left">
                            <label><strong><?php echo $this->translate('Newsletter Footer Image'); ?></strong></label>
                        </div>
                        <div class="mainpage-content-right">
                            <div class="mainpage-content-line">
                                <div class="mainpage-content-right-inner-left-other">
                                    <div class="mainpage-content-line footer-image-cont">
                                        <div class="mainpage-content-right-inner"></div>
                                        <div class="mainpage-content-right-inner">
                                            <div class='browse-container'>            
                                                <?php  
                                                if (
                                                    isset($this->newsletterFooterImage['path'])
                                                    && !empty($this->newsletterFooterImage['path'])
                                                ) { 
                                                    ?>
                                                    <img class='image-container' 
                                                        src="<?php echo PUBLIC_PATH_CDN. $this->newsletterFooterImage['path']
                                                        .urldecode($this->newsletterFooterImage['name']); ?>">
                                                    <?php 
                                                } ?>
                                            </div>
                                            <div class="mainpage-content-right-inner-left-other"></div>
                                            <div class="progress-file-detail hide">
                                                <div>
                                                    <img alt="uploadig" src="http://www.flipit.com/public/images/back_end/ajax-loader-tran.gif">
                                                    <span id="selected-filename"></span>
                                                </div>
                                                <div class="progress progress-success progress-striped" id="progress">
                                                    <div class="bar" style="width: 99%;"></div>
                                                </div>
                                            </div>
                                            <div class="mainpage-content-right-inner-right-other">
                                                <span class="message help-inline success margin-bottom-tenpx"></span>
                                            </div>
                                            <?php 
                                            if (
                                                !isset($this->newsletterFooterImage['path'])
                                                || empty($this->newsletterFooterImage['path'])
                                            ) {
                                                ?>
                                                <input type="file"  id="newsLetterFooterImage" 
                                                    class="span3 margin-bottom-tenpx" 
                                                    name="newsLetterFooterImage">
                                                <?php 
                                            } else { 
                                                ?>
                                                <button class="btn btn-primary" type="button" 
                                                    alt = "<?php echo urldecode($this->newsletterFooterImage['name']); ?>" 
                                                    id="delete-footer-image-btn">
                                                    <?php echo $this->translate("Delete Image");?>
                                                </button>
                                                <?php 
                                            } 
                                            ?>  
                                            <button class="btn btn-primary hide" type="button" 
                                                alt = "<?php echo urldecode($this->newsletterFooterImage['name']); ?>" 
                                                id="delete-footer-image-btn">
                                                <?php echo $this->translate("Delete Image");?>
                                            </button>
                                            <button class="btn btn-primary hide" type="button" 
                                                id="update-footer-image-btn">
                                                <?php echo $this->translate("Update Image");?>
                                            </button>
                                            <div class="margin-bottom-tenpx">
                                                <span class="help-inline" id="logo_file_message">
                                                    <?php echo $this->translate("Image Size: 615px x 162px (*.jpg or *.png file only)") . "&nbsp;" . $this->translate("Max filesize:") . "&nbsp;" . ini_get('upload_max_filesize'); ?>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="mainpage-content-line mb10">
                        <div class="mainpage-content-left">
                            <label><strong><?php echo $this->translate('Newsletter footer image url'); ?></strong></label>
                        </div>
                        <div class="mainpage-content-right">
                            <div class="mainpage-content-right-inner-left-other">
                            <div class="mainpage-content-right-inner-right-other"></div>
                                <div data-toggle="buttons-checkbox" class="mainpage-content-right-inner-left-other">
                                    <input type="text" 
                                    value="<?php echo !empty($this->newsletterFooterImageUrl['footerurl']) ? $this->newsletterFooterImageUrl['footerurl'] : '';?>" 
                                    placeholder=<?php echo $this->translate("https://abc.com")?> 
                                    name="footerurl" id="footerurl" onblur="saveNewsletterBannerUrl(this)"
                                    class="span3">
                                </div>
                            </div>
                        </div>
                    </div>

                	<?php
        			$isScheduled = $this->data['0']['newletter_is_scheduled'];
        			$sendDate = $isScheduled ? $this->data['0']['newletter_scheduled_time']->format('Y-m-d') : date('Y-m-d');

					$sendTime = isset($this->data['0']['newletter_is_scheduled'])
						? $this->data['0']['newletter_scheduled_time']->format('H:i')
						: date('H:i:s');
                	?>
                	<?php if($this->rights['rights'] ==  1 ) : ?>
	       			<div class="mainpage-content-line mb10">
	                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate("Schedule Newsletter");?></strong></label></div>
	                    <div class="mainpage-content-right">

	                    	<div data-toggle="buttons-checkbox" class="btn-group">
	                            <button type="button" class="btn <?php echo $isScheduled ? 'btn-primary' : '' ;?>" onclick="scheduleNewsletter(this);"><?php echo $this->translate('Yes'); ?></button>
	                            <button type="button" class="btn <?php echo $isScheduled ? '' : 'btn-primary' ;?> default" onclick="unScheduleNewsletter(this);"><?php echo $this->translate('No'); ?></button>
	                         </div>
                            <input class="display-none" type="hidden" name="isScheduled" id="isScheduled" value="<?php echo $isScheduled ;?>" >
	                    </div>
                	</div>
	            	<div class="mainpage-content-line <?php echo $isScheduled ? '' : 'hide' ;?>" id="timestamp-feild-container">
						<div class="mainpage-content-line mb10">
							<div class="mainpage-content-left">
								<label><strong><?php echo $this->translate('Time Zone'); ?></strong></label>
							</div>
							<div class="mainpage-content-right">
								<div class="mainpage-content-right-inner-left-other">
									<div data-toggle="buttons-checkbox" class="btn-group timezone">
										<label>
											<strong>
											<?php
												# set current timezone for scheduled newsletter if available (in case if it is schediled)
												echo $currentTimezone = isset($this->localeSettings['0']['timezone']) ?
																$this->localeSettings['0']['timezone'] : "" ;
											?>
											</strong>
										</label>
									</div>
								</div>
							</div>
						</div>
	                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Send date time'); ?></strong></label></div>
	                    <div class="mainpage-content-right">
	                    	<div class="mainpage-content-right-inner-right-other dateValidationMessage1"></div>
		                        <div class="mainpage-content-right-inner-left-other" style="width: 269px ! important;">
		                        	<div data-date-format="yyyy-mm-dd" data-date="<?php echo $sendDate;?>" id="dp3" class="input-append date">
		                        		<input readonly="readonly" type="text"  style="width:120px !important;" value="<?php echo $sendDate; ?>"  placeholder="Sunday, April 1" class="span2 ignore2 date-time-cusor-style" id="offerStartDate" name="sendDate">
		                        		<span class="add-on"><i class="icon-th"></i></span>
									</div>
									<input type="hidden"  value="<?php echo $sendTime;?>" name="currentSendTime" id="currentSendTime" />
					                <div class="input-append bootstrap-timepicker-component" style="display: inline-block;">
					                    <input style='width: 120px!important;'   readonly="readonly" type="text" id="offerstartTime" name="sendTime" class="input-small timepicker-default ignore2 date-time-cusor-style"><span class="add-on" style="min-width: 16px;margin-left: 3px;"><i class="icon-time" style="background-position: -47px -24px;"></i></span>
								    </div>
		                        </div>
	                     </div>
	               </div>

	               <!-- code added by cbhopal for newsletter -->
	                <div class="mainpage-content-line mb10">
	                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate(''); ?></strong></label></div>
	                    <div class="mainpage-content-right">
	                        <div class="mainpage-content-right-inner-left-other help-inline">
	                            <div data-toggle="buttons-checkbox" class="btn-group fl">
	                                <a id="sendNewsletter-btn" class="btn btn-primary" href="javascript:;" onclick="sendNewsLetter(event)"><?php echo  $isScheduled ? $this->translate('Save Scheduling') : $this->translate('Send Newsletter'); ?></a>

	                            </div>
	                           <div data-toggle="buttons-checkbox" class="btn-group fl m5">
	                            	<a id="disableNewsletter-btn" href="javascript:;" onclick="disableNewsLetterSchedule(event)"><?php echo  $isScheduled ? $this->translate('disable Scheduling') : ''; ?></a>
	                            </div>
	                        </div>
	                    </div>
	                </div>
	                <?php endif;?>
	               <!-- end code added by cbhopal -->
  		   	</form>

            </div>

 
            <!-- /poststuff -->
         <div class="mainpage-content">
         	<div class="mainpage-content-line mb10">
						<div class="mainpage-content-left">
							<label><strong><?php echo $this->translate('Test Email Address'); ?></strong></label>
						</div>
						<div class="mainpage-content-right">
	                         <input type="hidden" id='testEmail' name='testEmail' placeholder="Search Email.." style="width:300px;">
						</div>
					</div>
         	<div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Send Test Newsletter'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-left-other">
                            <div data-toggle="buttons-checkbox" class="btn-group">
                                <a class="btn btn-primary" href="javascript:;" onclick="sendTestNewsLetter(event)"><?php echo $this->translate('Send Test Newsletter') ?></a>
                            </div>
                        </div>
                    </div>
                </div>
         </div>
       </div>
