<?php
	$this->headTitle()->append('Account Settings');
	$this->headMeta('keyword', 'Description');
	$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/ckeditor/ckeditor.js");
	$this->headScript ()->appendFile (PUBLIC_PATH . "js/back_end/ckeditor/config.js" );
	$this->headScript ()->appendFile ( PUBLIC_PATH . "js/back_end/accountsetting.js" );
	$this->headScript ()->appendFile ( PUBLIC_PATH . "js/back_end/accountsetting2.js" );
	$this->headScript()->appendFile(PUBLIC_PATH  . "js/back_end/jquery.validate.js");
	$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
	$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
	$this->headLink()->appendStylesheet(PUBLIC_PATH . "css/jquery-ui-1.8.16.custom.css");
	$this->headScript()->appendFile(PUBLIC_PATH . "js/bootstrap-datepicker.js");
	$this->headScript()->appendFile(PUBLIC_PATH . "js/bootstrap-timepicker.js");
	$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/select2.min.js");

?>
<script type="text/javascript">
	var CKEDITOR_BASEPATH = "<?php echo PUBLIC_PATH . "js/ckeditor/" ; ?>" ;
</script>
<div class="wrap columns-2">
		<div class='wrap columns-2'>
		<?php if($this->messageSuccess!='' || $this->messageError!='' ){?>
		<br><div class ="mainpage-content-colorbox success">
		<?php if($this->messageSuccess!=''){?>
		<span class="successserver"><?php echo $this->messageSuccess; ?></span>
		<?php }?>
		<?php if($this->messageError!=''){?>
		<span class="errorserver"><?php echo $this->messageError; ?></span>
		<?php } ?>
		</div>
		<?php
		}?>
		</div>
           <h1><?php echo $this->translate('Create account settings'); ?><!-- <button  onclick="cancelAccountSettings();" class="btn ml10"></button> --></h1>

            <div class="mainpage-content"><form name="speacialForm" method="post" id="speacialForm" action="">
                <!-- CODE ADDED BY KRAJ FOR EMAIL CONFIRMATION -->
                <div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Show Emial Confirmation'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-left-other">
                            <div data-toggle="buttons-checkbox" class="btn-group">
                                <!-- <input type="checkbox" checked="checked" class="display-none" name="status" value="<?php //echo $this->special['status'] ? 1 : 0 ; ?>">-->
                                <button type="button" id="btnEmailConfimationOn" name="Yes" onclick="confirmationChanged(1)" class="btn <?php if(@$this->maxacc_data[0]['email_confirmation']==1){ echo "btn-primary";}?>"><?php echo $this->translate('Yes'); ?></button>
                                <button type="button" id="btnEmailConfimationOff" name="No" onclick="confirmationChanged(0)" class="btn <?php if(@$this->maxacc_data[0]['email_confirmation']==0){ echo "btn-primary" ;} ?>"><?php echo $this->translate('No'); ?></button>
                            </div>
                        </div>
                    </div>
                </div>
               <!-- END CODE ADDED BY KRAJ -->


               <!--  login page testimonioals -->
<?php /*
				<div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Show Testimonials'); ?></strong></label></div>
                    <div class="mainpage-content-right">
                        <div class="mainpage-content-right-inner-left-other">
                            <div data-toggle="buttons-checkbox" class="btn-group">
                                <!-- <input type="checkbox" checked="checked" class="display-none" name="status" value="<?php //echo $this->special['status'] ? 1 : 0 ; ?>">-->
                                <button type="button" id="btnShowTestimonialsOn" name="Yes" onclick="displayTestimonials(1)" class="btn <?php if(@$this->maxacc_data[0]['showTestimonial']==1){ echo "btn-primary";}?>"><?php echo $this->translate('Yes'); ?></button>
                                <button type="button" id="btnShowTestimonialsOff" name="No" onclick="displayTestimonials(0)" class="btn <?php if(@$this->maxacc_data[0]['showTestimonial']==0){ echo "btn-primary" ;} ?>"><?php echo $this->translate('No'); ?></button>
                            </div>
                        </div>
                    </div>
                </div>
*/?>

                <div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Testimonial 1'); ?></strong></label></div>
					<div class="mainpage-content-right">
						<div class="mainpage-content-line">
							<div class="mainpage-content-right-inner-right-other"></div>
							<div class="mainpage-content-right-inner-left-other">
								<textarea name="testimonial1" id="testimonial1"><?php echo @$this->maxacc_data[0]['testimonial1'] ; ?></textarea>
							</div>
						</div>
					</div>
                </div>
                <div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Testimonial 2'); ?></strong></label></div>
					<div class="mainpage-content-right">
						<div class="mainpage-content-line">
							<div class="mainpage-content-right-inner-right-other"></div>
							<div class="mainpage-content-right-inner-left-other">
								<textarea name="testimonial2" id="testimonial2"><?php echo @$this->maxacc_data[0]['testimonial2'] ; ?></textarea>
							</div>
						</div>
					</div>
                </div>
                <div class="mainpage-content-line mb10">
                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Testimonial 3'); ?></strong></label></div>
					<div class="mainpage-content-right">
						<div class="mainpage-content-line">
							<div class="mainpage-content-right-inner-right-other"></div>
							<div class="mainpage-content-right-inner-left-other">
								<textarea name="testimonial3" id="testimonial3"><?php echo @$this->maxacc_data[0]['testimonial3'] ; ?></textarea>
							</div>
						</div>
					</div>
                </div>
                <!-- end login page testimonioals -->
  		   	</form>

            </div>
        </div>



