<?php
$messege = $this->message;
if ($messege == "Page not found" &&  (!ctype_digit($this->matches) || (ctype_digit($this->matches) && $this->matches< 10))) {
    echo $this->render('error/pageContent.phtml');
} else {
	$httpScheme = FrontEnd_Helper_viewHelper::getServerNameScheme();
    if (HTTP_PATH == 'http://'.$httpScheme.'.flipit.com/' && LOCALE == '') {
        $flipitPartialViewPath = FrontEnd_Helper_viewHelper::renderFlipitErrorPage();
        echo $flipitPartialViewPath->render('error/error.phtml');
    } else {
    	$sessionNamespace = new Zend_Session_Namespace('ErrorPage');
    	$sessionNamespace->ErrorPage = true;
        echo $this->render('error/pageNotFound.phtml');
    }
}
