<?php
$this->headTitle()->append($this->translate('Create Newsletter Campaign'));
$this->headLink()->appendStylesheet(PUBLIC_PATH . "css/datepicker.css");
$this->headLink()->appendStylesheet(PUBLIC_PATH . "css/timepicker.css");
$this->headScript()->appendFile(PUBLIC_PATH  . "js/back_end/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/jquery.ui.widget.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/select2.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/jquery.bootstrap.wizard.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/createNewsletterCampaign.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/jquery-ui-1.8.16.custom.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/newsletterCampaignOffers.js");
$this->headScript ()->appendFile ( PUBLIC_PATH . "js/jquery.dataTables.min.js" );
$this->headScript ()->appendFile ( PUBLIC_PATH . "js/dataTableComman.js" );
$this->headScript ()->appendFile ( PUBLIC_PATH . "js/jquery.dataTables.rowReordering.js" );
$this->headScript ()->appendFile ( PUBLIC_PATH . "js/back_end/date.js" );
$this->headScript ()->appendFile ( PUBLIC_PATH . "js/bootstrap-timepicker.js" );
$this->headScript ()->appendFile ( PUBLIC_PATH . "js/bootstrap-datepicker.js" );
?>

<!-- Div for campaign info  -->

<div class="wrap columns-2" id="newsletterCampaignListDiv">
    <div class='wrap columns-2'>
        <?php echo $this->flashMessages(); ?>
        <div class="error alert-error form-error mt10"></div>
    </div>
    <form id="NewsletterWizardform" method="post" action="" enctype="multipart/form-data">
        <h1 class="fl"><?php echo $this->translate('Create Newsletter Campaign');?>
            <img id="loader" src="<?php echo PUBLIC_PATH;?>images/loader.gif" style="display:none;">
            <input type="button" onclick="" href="#" id="saveNewsletterCampaign" class="btn ml10" value="<?php echo $this->translate('Save & Exit');?>"></button>
            <a type="button" href="<?php echo HTTP_PATH;?>admin/newslettercampaigns" id="cancel" class="btn ml10"><?php echo $this->translate('Cancel');?></a>

        </h1>
        <div class="clear"></div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <ul class="nav nav-tabs font-bold">
                    <li class="active ">
                        <a class=""  id="emailSetting" href="#step1" data-toggle="tab">
                            1. Email Settings
                        </a>
                    </li>
                    <li class="">
                        <a class=""  id="campaignOffers" href="#step2" data-toggle="tab">
                            2. Coupons
                        </a>
                    </li>
                    <li class="">
                        <a href="#step3" data-toggle="tab" class="" id="ScheduleCampaign">
                            3. Schedule
                        </a>
                    </li>
                </ul>
            </div>
            <div class="panel-body">
                <div class="tab-content">
                    <div class="tab-pane active" id="step1">
                        <div class="mainpage-content">
                            <div class="mainpage-content-line">
                                <div class="mainpage-content-left"><label><strong><?php echo $this->translate('E-mail title(internal use only)');?></strong></label></div>
                                <div class="mainpage-content-right">
                                    <div class="mainpage-content-right-inner-right-other"></div>
                                    <div class="mainpage-content-right-inner-left-other">
                                        <input type="text" class="span3" id="campaignName" name="campaignName" placeholder="<?php echo $this->translate('Campaign Name');?>"
                                               value="<?php echo isset($this->newsletterCampaign['campaignName']) ? trim($this->newsletterCampaign['campaignName']): ''; ?>">
                                    </div>
                                </div>
                            </div>
                            <div class="mainpage-content-line">
                                <div class="mainpage-content-left"><label><strong><?php echo $this->translate('E-mail');?></strong></label></div>
                                <div class="mainpage-content-right">
                                    <div class="mainpage-content-right-inner-right-other"></div>
                                    <div class="mainpage-content-right-inner-left-other">
                                        <input type="text" class="span3" id="senderEmail" name="senderEmail"
                                               value="<?php echo isset($this->newsletterCampaign['senderEmail']) ? trim($this->newsletterCampaign['senderEmail']): ''; ?>" placeholder="<?php echo $this->translate('E-mail');?>"></input>
                                    </div>
                                </div>
                            </div>
                            <div class="mainpage-content-line">
                                <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Sender Name');?></strong></label></div>
                                <div class="mainpage-content-right">
                                    <div class="mainpage-content-right-inner-right-other"></div>
                                    <div class="mainpage-content-right-inner-left-other">
                                        <input type="text" class="span3" id="senderName" name="senderName"
                                               value="<?php echo isset($this->newsletterCampaign['senderName']) ? trim($this->newsletterCampaign['senderName']): ''; ?>" placeholder="<?php echo $this->translate('Sender Name');?>"></input>
                                    </div>
                                </div>
                            </div>
                            <div class="mainpage-content-line">
                                <div class="mainpage-content-left"><label><strong><?php echo $this->translate('E-mail Subject');?></strong></label></div>
                                <div class="mainpage-content-right">
                                    <div class="mainpage-content-right-inner-right-other"></div>
                                    <div class="mainpage-content-right-inner-left-other">
                                        <input type="text" class="span3" id="campaignSubject" name="campaignSubject" placeholder="<?php echo $this->translate('E-mail Subject');?>"
                                            value="<?php echo isset($this->newsletterCampaign['campaignSubject']) ? trim($this->newsletterCampaign['campaignSubject']): ''; ?>">
                                    </div>
                                </div>
                            </div>
                            <div class="mainpage-content-line">
                                <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Header');?></strong></label></div>
                                <div class="mainpage-content-right">
                                    <div class="mainpage-content-right-inner-right-other"></div>
                                    <div class="mainpage-content-right-inner-left-other">
                                        <textarea class="span3" id="campaignHeader" style="height:135px;" name="campaignHeader" placeholder="<?php echo $this->translate('Header');?>"><?php echo isset($this->newsletterCampaign['campaignHeader']) ? trim($this->newsletterCampaign['campaignHeader']): '';?></textarea>
                                    </div>
                                </div>
                            </div>

                            <div class="mainpage-content-line">
                                <div class="mainpage-content-left">
                                    <label><strong>Header Banner</strong></label>
                                </div>
                                <div class="mainpage-content-right">
                                    <div class="mainpage-content-line">
                                        <div class="mainpage-content-right-inner-left-other">
                                            <div class="mainpage-content-line header-image-cont">
                                                <div class="mainpage-content-right-inner">
                                                    <div class="browse-container">
                                                        <?php if ( isset($this->newsletterCampaign['headerBanner'])) { ?>
                                                            <img class="image-container"
                                                                 src="<?php echo  PUBLIC_PATH_CDN . 'public/images/upload/newslettercampaigns/'.trim($this->newsletterCampaign['headerBanner']);?>">
                                                        <?php } ?>
                                                    </div>
                                                    <input type="file" id="headerBanner" class="span3 margin-bottom-tenpx" name="headerBanner">
                                                    <div class="margin-bottom-tenpx">
                                                        <span class="help-inline" id="logo_file_message">
                                                        Image Size:(*.jpeg, *.jpg or *.png file only)</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="mainpage-content-line">
                                <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Header Banner URL');?></strong></label></div>
                                <div class="mainpage-content-right">
                                    <div class="mainpage-content-right-inner-right-other"></div>
                                    <div class="mainpage-content-right-inner-left-other">
                                        <input type="text" class="span3"  id="headerBannerURL" name="headerBannerURL" placeholder="<?php echo $this->translate('Header Banner URL');?>"
                                               value="<?php echo isset($this->newsletterCampaign['headerBannerURL']) ? trim($this->newsletterCampaign['headerBannerURL']): '';?>">
                                    </div>
                                </div>
                            </div>
                            <div class="mainpage-content-line">
                                <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Footer');?></strong></label></div>
                                <div class="mainpage-content-right">
                                    <div class="mainpage-content-right-inner-right-other"></div>
                                    <div class="mainpage-content-right-inner-left-other">
                                        <textarea class="span3" id="campaignFooter" style="height:135px;" name="campaignFooter" placeholder="<?php echo $this->translate('Footer');?>"><?php echo isset($this->newsletterCampaign['campaignFooter']) ? trim($this->newsletterCampaign['campaignFooter']): ''; ?></textarea>
                                    </div>
                                </div>
                            </div>

                            <div class="mainpage-content-line">
                                <div class="mainpage-content-left">
                                    <label><strong>Footer Banner</strong></label>
                                </div>
                                <div class="mainpage-content-right">
                                    <div class="mainpage-content-line">
                                        <div class="mainpage-content-right-inner-left-other">
                                            <div class="mainpage-content-line header-image-cont">
                                                <div class="mainpage-content-right-inner">
                                                    <div class="browse-container">
                                                        <?php if ( isset($this->newsletterCampaign['footerBanner']) ) { ?>
                                                            <img class="image-container"
                                                                 src="<?php echo PUBLIC_PATH_CDN . 'public/images/upload/newslettercampaigns/'.trim($this->newsletterCampaign['footerBanner']); ?>">
                                                        <?php } ?>
                                                    </div>
                                                    <input type="file" id="footerBanner" class="span3 margin-bottom-tenpx" name="footerBanner">
                                                    <div class="margin-bottom-tenpx">
                                                        <span class="help-inline" id="logo_file_message">
                                                        Image Size:(*.jpeg, *.jpg or *.png file only) </span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="mainpage-content-line">
                                <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Footer Banner URL');?></strong></label></div>
                                <div class="mainpage-content-right">
                                    <div class="mainpage-content-right-inner-right-other"></div>
                                    <div class="mainpage-content-right-inner-left-other">
                                        <input type="text" class="span3" id="footerBannerURL" name="footerBannerURL" placeholder="<?php echo $this->translate('Footer Banner URL');?>"
                                               value="<?php echo isset($this->newsletterCampaign['footerBannerURL']) ? trim($this->newsletterCampaign['footerBannerURL']): '';?>">
                                    </div>
                                </div>
                            </div>
                            <div class="mainpage-content-line">&nbsp;</div>
                        </div>
                    </div>
                    <div class="tab-pane" id="step2">
                        <div class="mainpage-content">
                            <div class="wrap columns-2" id="campaignOffersOne">
                                <h1>
                                    <?php echo $this->translate('Offer part One'); ?>
                                </h1>
                                <?php echo $this->flashMessages(); ?>
                                <div  class="metabox-holder has-right-sidebar">
                                    <div id="side-info-column" class="inner-sidebar-coupon">
                                        <div id="side-sortables" class="meta-box-sortables ui-sortable">
                                            <div class="coupon-sidebar-outer">
                                                <div class="coupon-sidebar-heading">
                                                    <select  style="display: none; width : 389px;" class="combobox" name="PartOneOfferlist" id="PartOneOfferlist">
                                                        <option value=""></option>
                                                        <?php
                                                        foreach ($this->partOneSearchOffers as $offerDetail) {
                                                            if (trim ($offerDetail ['title'] ) != '') {
                                                                $offer = substr ($offerDetail ['title'], 0, 70 );
                                                                ?>
                                                                <option  value="<?php echo $offerDetail['id']; ?>"><?php echo $offer; ?></option>
                                                            <?php }} ?>
                                                    </select>
                                                    <input type="hidden" name="selctedOffer" id="selctedOffer" value="">
                                                    <input type="hidden" name="selctedOfferText" id="selctedOfferText" value="">
                                                    <!--<input placeholder="search offer" id='searchCouponTxt' type="text" class="input-medium search-query">-->
                                                    <input type='hidden' name="SearchedValueIds" id="SearchedValueIds" value="">
                                                </div>
                                                <div class="coupon-sidebar-content-box">
                                                    <a onClick='addNewOffer(this)' class="btn btn-primary addNewOffer" >ADD NEW OFFER</a>
                                                </div>
                                                <div class="mb10"></div>
                                            </div>
                                        </div>
                                    </div>
                                    <div id="post-body">
                                        <div id="post-body-content-coupon">
                                            <div class="top-coupon-list">
                                                <table class="table table-bordered table-striped"  cellpadding="0" cellspacing="0" id="partOneOffers">
                                                    <thead>
                                                    <tr>
                                                        <th>#</th>
                                                        <th><?php echo $this->translate('Offer Name'); ?></th>
                                                        <th><?php echo $this->translate('Action'); ?></th>
                                                    </tr>
                                                    </thead>
                                                    <?php if( !empty($this->partOneOffers)):
                                                        $row = 1;
                                                        foreach($this->partOneOffers as $offer): ?>
                                                            <tr id="row_<?php echo $offer['id']; ?>" data-position="<?php echo $row; ?>">
                                                                <td><?php echo $row; ?></td>
                                                                <td><input type="hidden" name="partOneOffers[]" value="<?php echo $offer['id']; ?>"><?php echo $offer['offer']; ?></td>
                                                                <td>
                                                                    <input type="button" class="btn ml10 mb10" type="button" onClick="deleteOne('row_<?php echo $offer['id']; ?>', 'campaignOffersOne')" value='Delete'>
                                                                </td>
                                                            </tr>
                                                            <?php $row++; endforeach; ?>
                                                    <?php endif; ?>
                                                </table>
                                                <label class="toplinks-outer" style="color: #3a87ad"><i>* <?php echo $this->translate('You can drag & drop the offers to reorder'); ?></i></label>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="clear"></div>

                            <div class="wrap columns-2" id="campaignOffersTwo">
                                <h1>
                                    <?php echo $this->translate('Offer part Two'); ?>
                                </h1>
                                <?php echo $this->flashMessages(); ?>
                                <div class="mainpage-content-line" style="width: 83.5%;">
                                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Offer Part Two Title');?></strong></label></div>
                                    <div class="mainpage-content-right">
                                        <div class="mainpage-content-right-inner-right-other"></div>
                                        <div class="mainpage-content-right-inner-left-other">
                                            <input type="text" class="span3" id="offerPartTwoTitle" name="offerPartTwoTitle" placeholder="<?php echo $this->translate('Offer Part Two Title');?>"
                                                   value="<?php echo isset($this->newsletterCampaign['offerPartTwoTitle']) ? trim($this->newsletterCampaign['offerPartTwoTitle']): '';?>">
                                        </div>
                                    </div>
                                </div>
                                <div  class="metabox-holder has-right-sidebar">
                                    <div id="side-info-column" class="inner-sidebar-coupon">
                                        <div id="side-sortables" class="meta-box-sortables ui-sortable">
                                            <div class="coupon-sidebar-outer">
                                                <div class="coupon-sidebar-heading">
                                                    <select  style="display: none; width : 389px;" class="combobox" name="PartTwoOfferlist" id="PartTwoOfferlist">
                                                        <option value=""></option>
                                                        <?php
                                                        foreach ($this->partOneSearchOffers as $offerDetail) {
                                                            if (trim ($offerDetail ['title'] ) != '') {
                                                                $offer = substr ($offerDetail ['title'], 0, 70 );
                                                                ?>
                                                                <option  value="<?php echo $offerDetail['id']; ?>"><?php echo $offer; ?></option>
                                                            <?php }} ?>
                                                    </select>
                                                    <input type="hidden" name="selctedOffer" id="selctedOffer" value="">
                                                    <input type="hidden" name="selctedOfferText" id="selctedOfferText" value="">
                                                    <input type='hidden' name="SearchedValueIds" id="SearchedValueIds" value="">
                                                </div>
                                                <div class="coupon-sidebar-content-box">
                                                    <a onClick='addNewOffer(this)' class="btn btn-primary addNewOffer" >ADD NEW OFFER</a>
                                                </div>
                                                <div class="mb10"></div>
                                            </div>
                                        </div>
                                    </div>
                                    <div id="post-body">
                                        <div id="post-body-content-coupon">
                                            <div class="top-coupon-list">
                                                <table class="table table-bordered table-striped"  cellpadding="0" cellspacing="0" id="partTwoOffers">
                                                    <thead>
                                                    <tr>
                                                        <th>#</th>
                                                        <th><?php echo $this->translate('Offer Name'); ?></th>
                                                        <th><?php echo $this->translate('Action'); ?></th>
                                                    </tr>
                                                    </thead>
                                                    <?php if( true == !empty($this->partTwoOffers)):
                                                        $row = 1;
                                                        foreach($this->partTwoOffers as $offer): ?>
                                                            <tr id="row_<?php echo $offer['id']; ?>" data-position="<?php echo $row; ?>">
                                                                <td><?php echo $row; ?></td>
                                                                <td><input type="hidden" name="partTwoOffers[]" value="<?php echo $offer['id']; ?>"><?php echo $offer['offer']; ?></td>
                                                                <td>
                                                                    <input type="button" class="btn ml10 mb10" type="button" onClick="deleteOne('row_<?php echo $offer['id']; ?>', 'campaignOffersTwo')"  value='Delete'>
                                                                </td>
                                                            </tr>
                                                            <?php $row++; endforeach; ?>
                                                    <?php endif; ?>
                                                </table>
                                                <label class="toplinks-outer" style="color: #3a87ad"><i>* <?php echo $this->translate('You can drag & drop the offers to reorder'); ?></i></label>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="clear"></div>
                        </div>
                    </div>

                    <div class="tab-pane" id="step3">
                        <div class="mainpage-content">
                            <div class="mainpage-content-line">
                                <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Recipients');?></strong></label></div>
                                <div class="mainpage-content-right">
                                    <div class="mainpage-content-right-inner-right-other"></div>
                                    <div class="mainpage-content-right-inner-left-other">
                                       <div class="mb20"><?php echo $this->recipientCount['recepients'] . $this->translate(' Recipients selected');?></div>
                                    </div>
                                </div>
                            </div>

                            <div class="mainpage-content-line mb10">
                                <div class="mainpage-content-left">
                                    <label><strong><?php echo $this->translate('Time Zone'); ?></strong></label>
                                </div>
                                <div class="mainpage-content-right">
                                    <div class="mainpage-content-right-inner-left-other">
                                        <div data-toggle="buttons-checkbox" class="btn-group timezone">
                                            <label>
                                                <strong>
                                                    <?php
                                                    # set current timezone for scheduled newsletter if available (in case if it is schediled)
                                                    echo $currentTimezone = isset($this->localeSettings['0']['timezone']) ?
                                                        $this->localeSettings['0']['timezone'] : "" ;
                                                    ?>
                                                </strong>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="mainpage-content-line">
                                <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Send Date/Time');?></strong></label></div>
                                <div class="mainpage-content-right">
                                    <div class="mainpage-content-right-inner-right-other dateValidationMessage"></div>
                                    <div class="mainpage-content-right-inner-left-other">
                                        <div>
                                            <div data-date-format="dd-mm-yyyy" data-date="" id="dp1" class="input-append date">
                                                <input readonly="readonly" type="text"  value="<?php echo date('d-m-Y'); ?>"
                                                       placeholder=""
                                                       class="span2 ignore2 date-time-cusor-style" id="scheduleDate"
                                                       name="scheduleDate">
                                                <span class="add-on"><i class="icon-th"></i></span>
                                            </div>
                                        </div>
                                        <div>
                                            <div class="input-append bootstrap-timepicker-component" style="display: inline-block;">
                                                <input readonly="readonly" type="text" name="scheduleTime" id="scheduleTime" class="input-small timepicker-default ignore2 date-time-cusor-style" value="12:00">
                                                <span class="add-on">
                                                    <i class="icon-time" style="background-position: -47px -24px;"></i>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <ul class="pager wizard m-b-sm">
                        <li class="next last" style="display:none;"><a href="#">Last</a></li>
                        <li class="next"><a href="#" class="">Next</a></li>
                        <?php
                        $sessionNamespace = new Zend_Session_Namespace();
                        if (in_array($sessionNamespace->settings['rights']['content']['rights'], array('1', '2'))) { ?>
                            <li class="btn-primary accessSave" style="display:none;" id="scheduleButton"><a href="#">Schedule</a></li>
                        <?php } else { ?>
                            <li class="btn-primary accessSave" style="display:none;" id="saveCampaign"><a href="#">Save and Exit</a></li>
                        <?php } ?>
                        <li class="previous first disabled" style="display:none;"><a href="#">First</a></li>
                        <li class="previous disabled"><a href="#">Previous</a></li>

                    </ul>
                </div>
            </div>
        </div>
    </form>
</div>