<?php
$this->headTitle()->append($this->translate('Cteate Newsletter Campaign'));

$this->headScript()->appendFile(PUBLIC_PATH  . "js/back_end/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/jquery.ui.widget.js");
$this->headScript ()->appendFile ( PUBLIC_PATH . "js/jquery.bootstrap.wizard.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/createNewsletterCampaign.js");
?>

<!-- Div for campaign list  -->

<div class="wrap columns-2" id="newsletterCampaignListDiv">
    <div class='wrap columns-2'>
        <?php echo $this->flashMessages(); ?>
    </div>
    <form id="wizardform" method="post" action="">
        <h1 class="fl"><?php echo $this->translate('Cteate Newsletter Campaign');?>
            <button type="button" onclick="" href="#" id="sendTestMail" class="btn ml10"><?php echo $this->translate('Send Test Email');?></button>
            <input type="submit" onclick="" href="#" id="saveNewsletterCampaign" class="btn ml10" value="<?php echo $this->translate('Save & Exit');?>"></button>
        </h1>
        <div class="clear"></div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <ul class="nav nav-tabs font-bold">
                    <li class="active "><a href="#step1" data-toggle="tab">1. Email Settings</a></li>
                    <li class=""><a href="#step2" data-toggle="tab">2. Coupons</a></li>
                    <li class=""><a href="#step3" data-toggle="tab">3. Schedule</a></li>
                </ul>
            </div>
            <div class="panel-body">
<!--                <div class="progress progress-xs m-t-md">-->
<!--                    <div class="progress-bar bg-success" style="width: 33.3333333333333%;"></div>-->
<!--                </div>-->
                <div class="tab-content">
                    <div class="tab-pane active" id="step1">
                        <div class="mainpage-content">
                            <div class="mainpage-content-line">
                                <div class="mainpage-content-left"><label><strong><?php echo $this->translate('E-mail title(internal use only)');?></strong></label></div>
                                <div class="mainpage-content-right">
                                    <div class="mainpage-content-right-inner-right-other"></div>
                                    <div class="mainpage-content-right-inner-left-other">
                                        <input type="text" class="span3" id="campaignName" name="campaignName" placeholder="<?php echo $this->translate('Campaign Name');?>"><?php echo trim($this->campaignName); ?></input>
                                    </div>
                                </div>
                            </div>
                            <div class="mainpage-content-line">
                                <div class="mainpage-content-left"><label><strong><?php echo $this->translate('E-mail');?></strong></label></div>
                                <div class="mainpage-content-right">
                                    <div class="mainpage-content-right-inner-right-other"></div>
                                    <div class="mainpage-content-right-inner-left-other">
                                        <input type="text" class="span3" id="senderEmail" name="senderEmail" value="<?php echo trim($this->senderEmail); ?>" placeholder="<?php echo $this->translate('E-mail');?>"></input>
                                    </div>
                                </div>
                            </div>
                            <div class="mainpage-content-line">
                                <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Sender Name');?></strong></label></div>
                                <div class="mainpage-content-right">
                                    <div class="mainpage-content-right-inner-right-other"></div>
                                    <div class="mainpage-content-right-inner-left-other">
                                        <input type="text" class="span3" id="senderName" name="senderName" value="<?php echo trim($this->senderName); ?>" placeholder="<?php echo $this->translate('Sender Name');?>"></input>
                                    </div>
                                </div>
                            </div>
                            <div class="mainpage-content-line">
                                <div class="mainpage-content-left"><label><strong><?php echo $this->translate('E-mail Subject');?></strong></label></div>
                                <div class="mainpage-content-right">
                                    <div class="mainpage-content-right-inner-right-other"></div>
                                    <div class="mainpage-content-right-inner-left-other">
                                        <input type="text" class="span3" id="campaignSubject" name="campaignSubject" placeholder="<?php echo $this->translate('E-mail Subject');?>"><?php echo trim($this->campaignSubject); ?></input>
                                    </div>
                                </div>
                            </div>
                            <div class="mainpage-content-line">
                                <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Header');?></strong></label></div>
                                <div class="mainpage-content-right">
                                    <div class="mainpage-content-right-inner-right-other"></div>
                                    <div class="mainpage-content-right-inner-left-other">
                                        <textarea class="span3" id="campaignHeader" name="campaignHeader" placeholder="<?php echo $this->translate('Header');?>"><?php echo trim($this->campaignHeader); ?></textarea>
                                    </div>
                                </div>
                            </div>

                            <div class="mainpage-content-line">
                                <div class="mainpage-content-left">
                                    <label><strong>Header Banner</strong></label>
                                </div>
                                <div class="mainpage-content-right">
                                    <div class="mainpage-content-line">
                                        <div class="mainpage-content-right-inner-left-other">
                                            <div class="mainpage-content-line header-image-cont">
                                                <div class="mainpage-content-right-inner"></div>
                                                <div class="mainpage-content-right-inner">
                                                    <div class="browse-container">
                                                        <img class="image-container" src="<?php echo trim($this->campaignHeaderBanner);?>">
                                                    </div>
                                                    <input type="file" id="headerBanner" class="span3 margin-bottom-tenpx" name="headerBanner">
                                                    <div class="margin-bottom-tenpx">
                                                        <span class="help-inline" id="logo_file_message">
                                                        Image Size:(*.jpeg, *.jpg or *.png file only)</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="mainpage-content-line">
                                <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Header Banner URL');?></strong></label></div>
                                <div class="mainpage-content-right">
                                    <div class="mainpage-content-right-inner-right-other"></div>
                                    <div class="mainpage-content-right-inner-left-other">
                                        <input type="text" class="span3" id="headerBannerURL" name="headerBannerURL" placeholder="<?php echo $this->translate('Header Banner URL');?>" value="<?php echo trim($this->headerBannerURL);?>">
                                    </div>
                                </div>
                            </div>
                            <div class="mainpage-content-line">
                                <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Footer');?></strong></label></div>
                                <div class="mainpage-content-right">
                                    <div class="mainpage-content-right-inner-right-other"></div>
                                    <div class="mainpage-content-right-inner-left-other">
                                        <textarea class="span3" id="campaignFooter" name="campaignFooter" placeholder="<?php echo $this->translate('Footer');?>"><?php echo trim($this->campaignFooter); ?></textarea>
                                    </div>
                                </div>
                            </div>

                            <div class="mainpage-content-line">
                                <div class="mainpage-content-left">
                                    <label><strong>Footer Banner</strong></label>
                                </div>
                                <div class="mainpage-content-right">
                                    <div class="mainpage-content-line">
                                        <div class="mainpage-content-right-inner-left-other">
                                            <div class="mainpage-content-line header-image-cont">
                                                <div class="mainpage-content-right-inner"></div>
                                                <div class="mainpage-content-right-inner">
                                                    <div class="browse-container">
                                                        <img class="image-container" src="<?php echo trim($this->campaignFooterBanner);?>">
                                                    </div>
                                                    <input type="file" id="footerBanner" class="span3 margin-bottom-tenpx" name="footerBanner">
                                                    <div class="margin-bottom-tenpx">
                                                        <span class="help-inline" id="logo_file_message">
                                                        Image Size:(*.jpeg, *.jpg or *.png file only) </span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="mainpage-content-line">
                                <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Footer Banner URL');?></strong></label></div>
                                <div class="mainpage-content-right">
                                    <div class="mainpage-content-right-inner-right-other"></div>
                                    <div class="mainpage-content-right-inner-left-other">
                                        <input type="text" class="span3" id="footerBannerURL" name="footerBannerURL" placeholder="<?php echo $this->translate('Footer Banner URL');?>" value="<?php echo trim($this->footerBannerURL); ?>">
                                    </div>
                                </div>
                            </div>
                            <div class="clear"></div>
                        </div>
                    </div>
                    <div class="tab-pane" id="step2">
                        step2
                    </div>
                    <div class="tab-pane" id="step3">This is step 3</div>
                    <ul class="pager wizard m-b-sm">
                        <li class="previous first disabled" style="display:none;"><a href="#">First</a></li>
                        <li class="previous disabled"><a href="#">Previous</a></li>
                        <li class="next last" style="display:none;"><a href="#">Last</a></li>
                        <li class="next"><a href="#">Next</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </form>
</div><!-- End code of list campaigns -->
