<?php
$this->headTitle()->append($this->translate('Newsletter Campaign offers'));
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
$this->headScript()
    ->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
$this->headLink()
    ->appendStylesheet(PUBLIC_PATH . "css/jquery-ui-1.8.16.custom.css");

$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/back_end/bootstrap-combobox.css" );

$this->headScript ()->appendFile ( PUBLIC_PATH . "js/back_end/bootstrap-typeahead.js" );
$this->headScript ()->appendFile ( PUBLIC_PATH . "js/back_end/select2.min.js" );

$this->headScript()
    ->appendFile(PUBLIC_PATH . "/js/back_end/newsletterCampaignOffers.js");
?>
<div class="wrap columns-2" id="campaignOffers_one">
    <h1>
        <?php echo $this->translate('Offer part 1'); ?>
    </h1>
    <div class="mt10 mb10 alert alert-success" style="visibility: hidden;" id="part_one_success_message">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <label class="successserver">offers in part 1 has been reordered successfully</label>
    </div>
    <div  class="metabox-holder has-right-sidebar">
        <!-- button div with searchbar -->
        <div id="side-info-column" class="inner-sidebar-coupon">
            <div id="side-sortables" class="meta-box-sortables ui-sortable">
                <div class="coupon-sidebar-outer">
                    <div class="coupon-sidebar-heading">
                        <select  style="display: none; width : 389px;" class="combobox" name="offerlist" id="offerlist">
                            <option value=""></option>
                            <?php
                            foreach ($this->offer as $o) {
                                if (trim ($o ['title'] ) != '') {
                                    $offer = substr ($o ['title'], 0, 70 );
                                    ?>
                                    <option  value="<?php echo $o['id']; ?>"><?php echo $offer; ?></option>
                                <?php }} ?>
                        </select>
                        <input type="hidden" name="selctedOffer" id="selctedOffer" value="">
                        <input type="hidden" name="selctedOfferText" id="selctedOfferText" value="">
                        <!--<input placeholder="search offer" id='searchCouponTxt' type="text" class="input-medium search-query">-->
                        <input type='hidden' name="SearchedValueIds" id="SearchedValueIds" value="">
                    </div>
                    <div class="coupon-sidebar-content-box">
                        <button id='addNewOffer' onClick='addNewOffer();' class="btn btn-primary">ADD NEW OFFER</button>
                    </div>
                    <div class="coupon-sidebar-content-box mb10 image-loading-icon">
                        <button id='deleteOne' onClick='deleteOne();' class="btn">DELETE</button>
                    </div>
                </div>
            </div>
        </div>
        <?php
        $data = $this->data;
        ?>
        <div id="post-body">
            <div id="post-body-content-coupon">
                <div class="top-coupon-list">
                    <ul id='mostPopularCode'>
                        <?php
                        if (!empty($this->partOneOffers)){
                            foreach ($this->partOneOffers as $offerDetail){
                                    $lockImage = HTTP_PATH."public/images/back_end/stock_lock.png";
                                    $image = "<img src=".$lockImage." height='20' style='float:right' width='20'>";
                                echo  "<li class='ui-state-default'  relpos='" . $offerDetail['position'] . "' reloffer='" . $offerDetail['id'] . "' id='" . $offerDetail['id'] . "' ><span>" . $offerDetail['title'] ."</span>" .$image."</li>";
                            }
                        } else {
                            echo  "<li id='0'>No record found !</li>";
                        } ?>
                    </ul>
                </div>
            </div>
        </div>
        <br class="clear">
    </div>
</div>
<div class="wrap columns-2" id="campaignOffers_two">
    <h1>
        <?php echo $this->translate('Offer part 2'); ?>
    </h1>
    <div class="mt10 mb10 alert alert-success" style="visibility: hidden;" id="part_two_success_message">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <label class="successserver">offers in part 2 has been reordered successfully</label>
    </div>
    <div class="metabox-holder has-right-sidebar">
        <div id="side-info-column" class="inner-sidebar-coupon">
            <div id="side-sortables" class="meta-box-sortables ui-sortable">
                <div class="coupon-sidebar-outer">
                    <div class="coupon-sidebar-heading">
                        <select  style="display: none; width : 389px;" class="combobox" name="offerlist" id="offerlist">
                            <option value=""></option>
                            <?php
                            foreach ($this->offer as $o) {
                                if (trim ($o ['title'] ) != '') {
                                    $offer = substr ($o ['title'], 0, 70 );
                                    ?>
                                    <option  value="<?php echo $o['id']; ?>"><?php echo $offer; ?></option>
                                <?php }} ?>
                        </select>
                        <input type="hidden" name="selctedOffer" id="selctedOffer" value="">
                        <input type="hidden" name="selctedOfferText" id="selctedOfferText" value="">
                        <input type='hidden' name="SearchedValueIds" id="SearchedValueIds" value="">
                    </div>
                    <div class="coupon-sidebar-content-box">
                        <button id='addNewOffer' onClick='addNewOffer();' class="btn btn-primary" >ADD NEW OFFER</button>
                    </div>
                    <div class="coupon-sidebar-content-box mb10 image-loading-icon">
                        <button id='deleteOne' onClick='deleteOne();' class="btn">DELETE</button>
                    </div>
                </div>
            </div>
        </div>
        <?php
        $data = $this->data;
        ?>
        <div id="post-body">
            <div id="post-body-content-coupon">
                <div class="top-coupon-list">
                    <ul id='mostPopularCode'>
                        <?php
                        if (!empty($this->partTwoOffers)){
                            foreach ($this->partTwoOffers as $offerDetail){
                                $lockImage = HTTP_PATH."public/images/back_end/stock_lock.png";
                                $image = "<img src=".$lockImage." height='20' style='float:right' width='20'>";
                                echo "<li class='ui-state-default'  relpos='" . $offerDetail['position'] . "' reloffer='" . $offerDetail['id'] . "' id='" . $offerDetail['id'] . "' ><span>" . $offerDetail['title'] ."</span>" .$image."</li>";
                            }
                        } else {
                            echo  "<li id='0'>No record found !</li>";
                        } ?>
                    </ul>
                </div>
            </div>
        </div>
        <br class="clear">
    </div>
</div>
