<script type="text/javascript" src="<?php echo PUBLIC_PATH ;?>js/back_end/select2.min.js"></script>
<script type="text/javascript" src="<?php echo PUBLIC_PATH;?>js/back_end/newsletterCampaignOffers.js"></script>
<script type="text/javascript" src="<?php echo PUBLIC_PATH;?>js/jquery-ui-1.8.16.custom.min.js"></script>
<div class="wrap columns-2" id="campaignOffersOne">
    <h1>
        <?php echo $this->translate('Offer part 1'); ?>
    </h1>
    <div class="mt10 mb10 alert alert-success" style="visibility: hidden;" id="part_one_success_message">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <label class="successserver">offers in part 1 has been reordered successfully</label>
    </div>
    <div  class="metabox-holder has-right-sidebar">
        <!-- button div with searchbar -->
        <div id="side-info-column" class="inner-sidebar-coupon">
            <div id="side-sortables" class="meta-box-sortables ui-sortable">
                <div class="coupon-sidebar-outer">
                    <div class="coupon-sidebar-heading">
                        <select  style="display: none; width : 389px;" class="combobox" name="PartOneOfferlist" id="PartOneOfferlist">
                            <option value=""></option>
                            <?php
                            foreach ($this->partOneSearchOffers as $offerDetail) {
                                if (trim ($offerDetail ['title'] ) != '') {
                                    $offer = substr ($offerDetail ['title'], 0, 70 );
                                    ?>
                                    <option  value="<?php echo $offerDetail['id']; ?>"><?php echo $offer; ?></option>
                                <?php }} ?>
                        </select>
                        <input type="hidden" name="selctedOffer" id="selctedOffer" value="">
                        <input type="hidden" name="selctedOfferText" id="selctedOfferText" value="">
                        <!--<input placeholder="search offer" id='searchCouponTxt' type="text" class="input-medium search-query">-->
                        <input type='hidden' name="SearchedValueIds" id="SearchedValueIds" value="">
                    </div>
                    <div class="coupon-sidebar-content-box">
                        <button  onClick='addNewOffer();' class="btn btn-primary addNewOffer">ADD NEW OFFER</button>
                    </div>
                    <div class="coupon-sidebar-content-box mb10 image-loading-icon">
                        <button onClick='deleteOne();' class="btn deleteOne">DELETE</button>
                    </div>
                </div>
            </div>
        </div>
        <?php
        $data = $this->data;
        ?>
        <div id="post-body">
            <div id="post-body-content-coupon">
                <div class="top-coupon-list">
                    <ul id='partOneCode'>
                        <?php
                        if (!empty($this->partOneOffers)){
                            foreach ($this->partOneOffers as $offerDetail){
                                    $lockImage = HTTP_PATH."public/images/back_end/stock_lock.png";
                                    $image = "<img src=".$lockImage." height='20' style='float:right' width='20'>";
                                echo  "<li class='ui-state-default'  relpos='" . $offerDetail['position'] . "' reloffer='" . $offerDetail['id'] . "' id='" . $offerDetail['id'] . "' ><span>" . $offerDetail['title'] ."</span>" .$image."</li>";
                            }
                        } else {
                            echo  "<li id='0'>No record found !</li>";
                        } ?>
                    </ul>
                </div>
            </div>
        </div>
        <br class="clear">
    </div>
</div>
<div class="wrap columns-2" id="campaignOffersTwo">
    <h1>
        <?php echo $this->translate('Offer part 2'); ?>
    </h1>
    <div class="mt10 mb10 alert alert-success" style="visibility: hidden;" id="part_two_success_message">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <label class="successserver">offers in part 2 has been reordered successfully</label>
    </div>
    <div class="metabox-holder has-right-sidebar">
        <div id="side-info-column" class="inner-sidebar-coupon">
            <div id="side-sortables" class="meta-box-sortables ui-sortable">
                <div class="coupon-sidebar-outer">
                    <div class="coupon-sidebar-heading">
                        <select  style="display: none; width : 389px;" class="combobox" name="PartTwoOfferlist" id="PartTwoOfferlist">
                            <option value=""></option>
                            <?php
                            foreach ($this->partTwoSearchOffers as $offerDetail) {
                                if (trim ($offerDetail ['title'] ) != '') {
                                    $offer = substr ($offerDetail ['title'], 0, 70 );
                                    ?>
                                    <option  value="<?php echo $offerDetail['id']; ?>"><?php echo $offer; ?></option>
                                <?php }} ?>
                        </select>
                        <input type="hidden" name="selctedOffer" id="selctedOffer" value="">
                        <input type="hidden" name="selctedOfferText" id="selctedOfferText" value="">
                        <input type='hidden' name="SearchedValueIds" id="SearchedValueIds" value="">
                    </div>
                    <div class="coupon-sidebar-content-box">
                        <button  onClick='addNewOffer();' class="btn btn-primary addNewOffer" >ADD NEW OFFER</button>
                    </div>
                    <div class="coupon-sidebar-content-box mb10 image-loading-icon">
                        <button onClick='deleteOne();' class="btn deleteOne">DELETE</button>
                    </div>
                </div>
            </div>
        </div>
        <?php
        $data = $this->data;
        ?>
        <div id="post-body">
            <div id="post-body-content-coupon">
                <div class="top-coupon-list">
                    <ul id='partTwoCode'>
                        <?php
                        if (!empty($this->partTwoOffers)){
                            foreach ($this->partTwoOffers as $offerDetail){
                                $lockImage = HTTP_PATH."public/images/back_end/stock_lock.png";
                                $image = "<img src=".$lockImage." height='20' style='float:right' width='20'>";
                                echo "<li class='ui-state-default'  relpos='" . $offerDetail['position'] . "' reloffer='" . $offerDetail['id'] . "' id='" . $offerDetail['id'] . "' ><span>" . $offerDetail['title'] ."</span>" .$image."</li>";
                            }
                        } else {
                            echo  "<li id='0'>No record found !</li>";
                        } ?>
                    </ul>
                </div>
            </div>
        </div>
        <br class="clear">
    </div>
</div>
