<?php

$this->headTitle()->append($this->translate('Campaign Template Settings'));
$this->headMeta('keyword', 'Description');
$this->headScript()->appendFile(PUBLIC_PATH  . "js/back_end/jquery.validate.js");
$this->headScript ()->appendFile ( PUBLIC_PATH . "js/back_end/newsletter-campaign-settings.js" );
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/locale.js");

?>
<div class="wrap columns-2">
    <div class='wrap columns-2'>
        <?php echo $this->flashMessages(); ?>
    </div>
    <h1><?php echo $this->translate('Campaign Template Settings');?></h1>

    <form id="campaignsettings" name="campaignsettingsform" enctype="multipart/form-data" method="POST"
          action="http://dev.flipit.com/admin/newslettercampaigns/settings" _lpchecked="1">

        <div class="mainpage-content">
            <div class="mainpage-content-line">
                <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Default Header');?></strong></label></div>
                <div class="mainpage-content-right">
                    <div class="mainpage-content-right-inner-right-other"></div>
                    <div class="mainpage-content-right-inner-left-other">
                        <textarea class="span3" id="campaign-header" name="campaign-header" placeholder="<?php echo $this->translate('Default Header');?>"><?php echo trim($this->campaign_header); ?></textarea>
                    </div>
                </div>
            </div>
            <div class="mainpage-content-line">
                <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Default Footer');?></strong></label></div>
                <div class="mainpage-content-right">
                    <div class="mainpage-content-right-inner-right-other"></div>
                    <div class="mainpage-content-right-inner-left-other">
                        <textarea class="span3" id="campaign-footer" name="campaign-footer" placeholder="<?php echo $this->translate('Default Footer');?>"><?php echo trim($this->campaign_footer); ?> </textarea>
                    </div>
                </div>
            </div>
        </div>
        <div class="mainpage-content-colorbox">
            <button id="saveSettings" type="submit" class="btn btn-large btn-primary fl"><?php echo $this->translate('Save Settings');?></button>
            <a class="fl m10" href="javascript:void(0);" onclick="window.location.href='http://dev.flipit.com/admin/newslettercampaigns/settings'"><strong>CANCEL</strong></a>
        </div>
    </form>
</div>