
<?php 
 $this->headTitle()->append($this->translate('Add Chain'));
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/jquery.validate.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/chain-management.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/select2.min.js");
 
?>

<div class="wrap columns-2" id="addNewKeyword">
   <h1><?php echo $this->translate('Add Chain'); ?><button class="btn ml10" type="button" onClick="window.location.href='<?php echo HTTP_PATH ;?>admin/chain/chain-item/chain/<?php echo $this->chainId; ?>'"><?php echo $this->translate('Cancel'); ?></button></h1>
            <form method="post" id="addShopForm" >
            <input type="hidden" value="<?php echo $this->chainId; ?>" name="chain"/>
			<div class="mainpage-content" style="margin-bottom:120px;">
				<div class="mainpage-content-line mb10">
					<div class="mainpage-content-left">
						<label><strong><?php echo $this->translate('Locale'); ?></strong></label>
					</div>
					<div class="mainpage-content-right oveflow-hidden">
						<div class="mainpage-content-right-inner-left-other fl oh">
							<?php 
								echo $this->locale['0']['locale'] ;
							?>
								<select name ="locale" id='locale' style='width:200px;' onchange="updateShops(this);" >
									<option selected="selected" disabled="disabled" value="0">Select Website</option>		
									<?php
										$websites = $this->websites ;
										if($websites) :
												foreach($websites as $website):
												 	echo "<option value=". $website['id'] .">". $website['name'] ."</option>";
												endforeach;
										endif;
								 	?>
								</select>
						</div>
						<div class="mainpage-content-right-inner-right-other focus error">
							<span for="locale" class="error help-inline"></span>
						</div>
					</div>
				</div>
				<div  class="mainpage-content-line mb10">
	                    <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Shops'); ?></strong></label></div>
	                    <div class="mainpage-content-right">
		                	<div class="fl">                   
	                        <input type='hidden' id="searchShops" value="" name="shopName" style="width:200px;"/>
	                        <input type='hidden' id="searchShopId" value="" name="searchShopId" />
							</div>  
							<div class="mainpage-content-right-inner-right-other focus error">
							<span for="shopName" class="error help-inline"></span>
						</div>
							<div class="clear"></div>
	                    </div>
	            </div>
	            <div class="clear"></div>
				<div class="mainpage-content-colorbox">
					<button id="updateseenIdButton" type="submit" class="btn btn-large btn-primary fl" value="chain" name="form"><?php echo $this->translate('SAVE CHAIN'); ?></button>
					<a class="fl m10" href="<?php echo HTTP_PATH ;?>admin/chain/chain-item/chain/<?php echo $this->chainId; ?>"><strong><?php echo $this->translate('CANCEL'); ?></strong></a>
				</div>
			</div>
	</form>	
</div>