<?php
$breadcrumb = "<a href='".HTTP_PATH_LOCALE."top-kortingscodes' style='color:#6a6a6a'>".$this->translate('Offer')."</a>";
$headerSearch = new FrontEnd_Helper_viewHelper();
echo $this->partial('partials/_headerSearch.phtml',array('breadcrumb'=>$breadcrumb));
?>
        <!-- Voucher Outer Starts -->
        <div class="new-outer">
        <div class="voucher-outer">

<!-- Voucher Outer Left Starts -->
<div class="voucher-outer-left">

<?php echo $this->partial('partials/_top_new_popular_header.phtml',array('active' => 'popular','pageTitle' => $this->pageTitle) ); ?>

<!-- Voucher Outer Left Col1 Ends -->

  <!-- Voucher Outer Left Col2 Starts -->
  <div class="voucher-outer-left-col2">
    <?php if(count($this->paginator)>0){
      echo $this->partialLoop('partials/offer.phtml', $this->paginator);
    } else {
    ?>
    <div style="text-align:center;font-size:14px;font-weight:bold;"><?php echo $this->translate('No record found'); ?></div>
    <?php }?>
  </div>
  <!-- Voucher Outer Left Col2 Ends -->

<!-- Voucher Paging Outer Starts -->
<div  class="voucher-paging-outer">
<div class="voucher-paging-inner">
<!--  <div class="paging-leftarrow">&nbsp;</div> -->
<?php echo $this->paginationControl($this->paginator,'Sliding', '/partials/_pagination.phtml'); ?>
</div>
</div>
<!-- Voucher Paging Outer Ends -->

</div>
<!-- Voucher Outer Left Ends -->

          <!-- Voucher Outer Right Starts -->

            <div class="voucher-outer-right" style="margin-top:72px;">
            	  <!-- Waardebon Starts -->
           	  <?php
           	   echo $this->widget;
           	  ?>


           </div>
              <!-- Voucher Outer Right Ends -->


        <input type="hidden" id="shopId" value="<?php echo $this->shopId; ?>" >

        <div class="clr"></div>
    <div class="separator mt20">&nbsp;</div>

	<!-- Popup Starts -->

          </div>
          </div>
        <!-- Voucher Outer Ends -->