  <?php 
		$class = '';
		if($this->partialCounter % 3 == 0){
			$class = 'mr-none';
		}
		$shopPicture = HTTP_PATH.'public/images/NoImage/homeShopLogo64_32.jpg';
		$shopPicture = HTTP_PATH. "public/thumb.php?src=".$shopPicture."&h=31&w=62&zc=0";
		if(isset( $this->offer['shop']['logo']['name'] ) && $this->offer['shop']['logo']['name'] != '' )
		{    
			   
		        	$shopPicture = PUBLIC_PATH_CDN .  $this->offer['shop']['logo']['path'] .'thum_big_'. $this->offer['shop']['logo']['name'] ;
		       	
		}
		$dType = '';
		if ($this->offer['discountvalueType']  == '1') :
		$dType = '&euro;';
		elseif ($this->offer['discountvalueType']  == '2') :
			$dType = '%';
		endif;
		?>
		<div class="popular-kortings-coupon <?php echo $class; ?>">
			<div class="popular-kortings-coupon-img extofferpop">
			<a href="<?php echo HTTP_PATH_LOCALE.$this->offer['shop']['permaLink'];?>"> <img alt="<?php echo $this->offer['shop']['name'];?>" class='radiusImg' src="<?php echo  $shopPicture;?>"/></a>
			</div> 
			<div class="popular-kortings-coupon-text-outer">
			<div class="popular-kortings-coupon-text">
				<h3>
					<a class="text-blue-link" href="<?php echo HTTP_PATH_LOCALE.$this->offer['shop']['permaLink'];?>" title="<?php echo $this->offer['shop']['name'];?>"><?php echo strlen($this->offer['shop']['name'])<= 20 ?  $this->offer['shop']['name'] : substr($this->offer['shop']['name'], 0,20).'...';?></a>
				</h3>
				<a class="text-black-link" href="<?php echo HTTP_PATH_LOCALE.$this->offer['shop']['permaLink'];?>"><span title="<?php echo $this->offer['title']?>" ><?php echo strlen($this->offer['title'])<= 34 ?  $this->offer['title'] : substr($this->offer['title'], 0,34). '...';?></span></a>
			</div>
			      <?php if($this->offer['exclusiveCode'] =='1'):
			        if($class == 'mr-none'){
		             ?>
		             <div class="popular-kortings-coupon-top-heading3">
		             
			             <?php 
							$view = new Zend_View();
							$view->setScriptPath(APPLICATION_PATH . '/views/scripts/');
							echo $view->render('partials/exclusive_small.phtml');
						?>
		             	
		             </div>
		             <?php }else{?>
		             <div class="popular-kortings-coupon-top-heading3" style="">
			             <?php 
							$view = new Zend_View();
							$view->setScriptPath(APPLICATION_PATH . '/views/scripts/');
							echo $view->render('partials/exclusive_small.phtml');
						?>
		             </div>
		             <?php }
		           endif;
		           ?>
			        </div>
		            </div>
			       