<?php 

$breadcrumb = "<a href='".HTTP_PATH_LOCALE."kortingen' style='color:#6a6a6a'>".$this->translate('Offer')."</a>";
$headerSearch = new FrontEnd_Helper_viewHelper();
echo $this->partial('partials/_headerSearch.phtml',array('breadcrumb'=>$breadcrumb));
$this->minifyHeadScript()->prependFile ("public/js/front_end/top-20.js" );
?>
<!-- Voucher Outer Starts -->
<div class="new-outer">
<div class="voucher-outer">
	<!-- Voucher Outer Left Starts -->
	<div class="voucher-outer-left">

		<?php echo $this->partial('partials/_top_new_popular_header.phtml',array('active' => 'top20','pageTitle' => $this->pageTitle) ); ?>

		<!-- Voucher Outer Left Col1 Ends -->

		<!-- Voucher Outer Left Col2 Starts -->
		
		<div class="voucher-outer-left-col2">
            <?php 
            if(count($this->topPopularOffers)>0){
	            $this->showMessageBar = false;
	            echo $this->partialLoop('store/_top-20-offers.phtml', 1,$this->topPopularOffers);
            }else{
                 ?>
              <div style="text-align:center;font-size:14px;font-weight:bold;"><?php echo $this->translate('No record found'); ?></div> 
            <?php } ?> 
		</div>


</div>
<!-- Voucher Outer Left Ends -->

<!-- Voucher Outer Right Starts -->

<div class="voucher-outer-right" style="margin-top:72px;">
	<!-- Waardebon Starts -->
           	  <?php  echo $this->widget; ?>
				
</div>
<!-- Voucher Outer Right Ends -->

<input type="hidden" id="shopId" value="<?php echo $this->shopId; ?>">

<div class="clr"></div>

<!-- Popup Starts -->

</div>
</div>
<!-- Voucher Outer Ends -->