<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?php echo $this->translate('404 error - Page does not exist');?></title>
        <?php
        echo $this->headLink()->appendStylesheet(HTTP_PATH."public/css/front_end/all.css")->appendStylesheet(HTTP_PATH."public/css/front_end/custom.css");
        ?>
    </head>
    <body class="page404">
        <div class="bg-stretch">
            <img src="<?php echo HTTP_PATH; ?>public/images/front_end/img-46.jpg" alt="" />
        </div>
        <div id="wrapper">
            <main role="main" id="main">
                <div class="container">
                    <div class="section404">
                        <strong class="logo flipit"><a href="http://www.flipit.com"><?php echo $this->translate('FlipIt'); ?></a></strong>
                        <div class="row-block">
                            <div class="text-block">
                                <h1><?php echo $this->translate('Sorry, that page doesn’t exist');?>!</h1>
                                <p><?php echo $this->translate('Whoops, looks like you’ve made a little mistake').'. '.$this->translate('No worries, return to our'); ?> <a href="http://www.flipit.com/"><?php echo $this->translate('home page');?></a> <?php echo $this->translate('or search for other discounts');?></p>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </body>
</html>