<!DOCTYPE html>
<html lang="en">

  <?php echo $this->render('partials/_head.phtml'); ?>

</head>
<body>
<header>
  <div class="top-header">
    <div class="container">
      <div class="top-text">
        Flipit.com - Next Generation 'Global' Couponing - Select your Country and use our Coupons!
      </div>
    </div>
  </div>
  <div class="container">
    <img src="<?php echo HTTP_PATH;?>public/images/front_end/flipit.png" alt="Flipit" />
  </div>
</header>
<nav>
  <div class="container">
    <h2 class="selecttext">404 ERRROR. PAGE NOT FOUND</h2>
    <h4 align="center" class="sub-title" >Please select one on the following countries bellow</h4>

    <?php echo $this->render('partials/_bottom_country_list.phtml'); ?>


  <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
  <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
  <script type="text/javascript" src="<?php echo HTTP_PATH;?>public/flipit/js/jMenu.js"></script>
  <script type="text/javascript" src="<?php echo HTTP_PATH;?>public/flipit/js/jquery.flippy.js"></script> 
  <script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
  <script type="text/javascript">stLight.options({publisher: "96dd1eba-e0de-4147-ae74-e2430944f8ef", doNotHash: true, doNotCopy: false, hashAddressBar: false});</script>
  <script>

      (function() {

        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
        po.src = 'https://apis.google.com/js/plusone.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
      })();

  var mapContent = $(".mapcontainer").clone();

  $(document).ready(function(){
      init();
  });
  function rotate(obj,dir)
  {
     var cont, btnClass,content="" ;

      btnClass = jQuery(obj).data('rel');
      content = jQuery("div." + btnClass + "container").clone();
     
      if(btnClass == 'map')
      {
        content = mapContent ;
      }
      var div =    $("<div />").html(content.removeClass('hide'));

      jQuery("div.slides").flippy({
              content: div ,
              direction: dir,
              duration:"750",
              color_target :"#ea5234",
              onFinish: function(){
                init();
              }
      });

      
   // e.preventDefault();
  }

  function init()
  {

    $("li").hover(
          function() { $(".submenu", this).show(); },
          function() { $(".submenu", this).hide(); }
      );
  }
  </script> 
  <script>
  /*jQuery(".slides .button").bind("click",function(e){
      e.preventDefault();
      
      var content = jQuery(this).parents(".mapcontainer").next(".thestory").html();
      
      jQuery(this).parents(".mapcontainer").flippy({
          content: content,
          direction:"left",
          duration:"750",
          color_target :"#ea5234",
      });
  });*/
  </script>
  <script>
    $(document).ready(function(){

        $('#location').click(function(){

          $("li.selected" , ".small-left-tabs").removeClass('selected');
          $(this).parent('li').addClass("selected");
          $('#jquery-tabs-slider').show();
          $('#press-box').hide();
          $('#thestory-small' , '.small-banner').hide();
                      
        });
        $('#story').click(function(){
          $("li.selected" , ".small-left-tabs").removeClass('selected');
          $(this).parent('li').addClass("selected");
          $('#jquery-tabs-slider').hide();
          $('#press-box').hide();
          $('#thestory-small' , '.small-banner').show();
        });
        $('#press').click(function(){

          $("li.selected" , ".small-left-tabs").removeClass('selected');
          $(this).parent('li').addClass("selected");

          $('#jquery-tabs-slider').hide();
          $('#press-box').show();
          $('#thestory-small' , '.small-banner').hide();
        });
        
    });
  </script>
</footer>
</body>
</html>
