<?php 
foreach ($this->favouriteShopsOffers as $favouriteShopsOffer) {
    $shopImage = 
        PUBLIC_PATH_CDN.ltrim($favouriteShopsOffer['shop']['logo']['path'], "/")
        . $favouriteShopsOffer['shop']['logo']['name'];
    $offerId = $favouriteShopsOffer['id'];
    $offerBounceRate = "/out/offer/".$favouriteShopsOffer['id'];
    ?>
    <article class="block col-sm-6">
        <div class="holder">
            <a href="<?php echo HTTP_PATH_LOCALE. $favouriteShopsOffer["shop"]["permaLink"];?>"  
            class="code code-2">
                <div class="center">
                    <div class="code-holder">
                        <img src="<?php echo $shopImage;?>" width="132"
                        alt="<?php echo $favouriteShopsOffer['shop']['name'];?>">
                    </div>
                </div>
                <footer class="bottom"><?php echo FrontEnd_Helper_viewHelper::__translate('code');?></footer>
            </a>
            <div class="box">
                <div class="text">
                    <a href="<?php echo HTTP_PATH_LOCALE. $favouriteShopsOffer["shop"]["permaLink"];?>"  
                    class="link">
                    <?php echo $favouriteShopsOffer['title'];?>
                    </a>
                    <p>
                        <?php 
                        echo FrontEnd_Helper_viewHelper::__translate('and'). "10". " " 
                        .FrontEnd_Helper_viewHelper::__translate('other active codes for');
                        ?>
                        <a href="<?php echo HTTP_PATH_LOCALE. $favouriteShopsOffer["shop"]["permaLink"];?>">
                        <?php echo $favouriteShopsOffer['shop']['name'];?>
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </article>
<?php
}
echo $this->paginationControl($this->favouriteShopsOffers, 'Sliding', '/partials/_pagination.phtml');