<?php echo $this->translate('Beste Kortingscode.nl bezoeker') ?>,<br><br>
 
<?php echo $this->translate('Je ontvang deze e-mail omdat je hebt aangeven om op de hoogte te blijven van de beste kortingscodes en acties van Kortingscode.nl.'); ?><br><br>

<?php echo $this->translate('Met de volgende stap bevestig je dat je deze e-mail hebt ontvangen, klik daarvoor op onderstaande link:')?><br>
<a href='<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('login').'/'.FrontEnd_Helper_viewHelper::__link('confirmemail').'/'. base64_encode($this->email);?>'><?php echo $this->translate('Klik hier om je e-mail adres te bevestigen')?></a><br><br>

<?php echo $this->translate('Alvast bedankt')?>,<br><br>

<?php echo $this->translate('Kortingscode.nl')?><br><br>

<span style='font-size: 9px;'><?php echo $this->translate('Kortingscode.nl is een onderdeel van Imbull, Weteringschans 120, 1017XT Amsterdam - KvK# 34339618'); ?></span>
