<?php
echo $this->minifyHeadLink()->prependStylesheet("/public/css/front_end/register.css");
echo $this->minifyHeadScript()->prependFile(HTTP_PATH."public/js/front_end/registration.js");
$form = $this->form;
// Remove <dt> from label generation
foreach ($form->getElements() as $element) {
    $element->getDecorator('label')->setOption('tag', null);
}
if($this->messageSuccess!='' || $this->messageError!='') : ?>
    <div id="messageDiv" class="yellow-box-error-box-code myprofile-messagebox">
       <strong><?php echo $this->messageSuccess!='' ? $this->messageSuccess : $this->messageError;?></strong>
    </div>
    <?php 
endif;
?>
<section class="register-box">
    <form id="registerForm" name="registerForm" method="POST" action="">
        <fieldset>
            <div class="row">
                <div class="col-md-6">
                    <div class="image">
                        <img width="462" height="263" alt="image description" 
                            src="<?php echo PUBLIC_PATH;?>images/img-36.png">
                        <div class="text">
                        <?php echo $this->translate('Flipit! Get ready to flip over a great deal!');?>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                            <?php echo $form->emailAddress->renderLabel(). $form->emailAddress->renderViewHelper();?>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                            <?php echo $form->password->renderLabel(). $form->password->renderViewHelper();?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                            <?php echo $form->firstName->renderLabel() . $form->firstName->renderViewHelper();?>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                            <?php echo $form->lastName->renderLabel(). $form->lastName->renderViewHelper();?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                            <?php echo $form->dateOfBirth->renderLabel();?>
                                <div class="row">
                                    <div class="col-xs-4">
                                    <?php echo $form->dateOfBirthDay->renderViewHelper();?>
                                    </div>
                                    
                                    <div class="col-xs-4">
                                     <?php echo $form->dateOfBirthMonth->renderViewHelper();?>
                                    </div>
                                    
                                    <div class="col-xs-4">
                                     <?php echo $form->dateOfBirthYear->renderViewHelper();?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-sm-6">
                            <div class="form-group">
                            <?php echo $form->gender->renderLabel(). $form->gender->renderViewHelper();?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                            <?php echo $form->postCode->renderLabel(). $form->postCode->renderViewHelper();?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group alt">
                         <?php 
                         echo $this->formSubmit(
                             'submit',
                             'Create account',
                             array('class'=>'btn blue btn-lg btn-primary', 'id'=>'register')
                         ) ?>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</section>