<?php
$this->minifyHeadScript()->prependFile(HTTP_PATH."public/js/front_end/profile.js");
$this->minifyHeadLink()->prependStylesheet("/public/css/front_end/profile.css");
$registerForm = $this->form;
// Remove <dt> from label generation
foreach ($registerForm->getElements() as $formElement) {
    $formElement->getDecorator('label')->setOption('tag', null);
}
if($this->messageSuccess!='' || $this->messageError!='') : ?>
    <div id="messageDiv" class="yellow-box-error-box-code myprofile-messagebox">
        <strong><?php echo $this->messageSuccess!='' ? $this->messageSuccess : $this->messageError;?></strong>
    </div>
    <?php 
endif;
?>
<section class="profile-box">
    <form id="profile" name="profile" method="POST" action="">
        <div class="title">
            <h1><?php echo $this->translate('Hi'). " " . $this->firstName .',' . " ". $this->translate('How are you?');?></h1>
            <?php echo $this->translate('Want to change you personal setting then your free to do so below. Change name, email address, password and more');?>
        </div>
        <div class="form-row">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-6">
                                <?php echo $registerForm->firstName->renderLabel() . $registerForm->firstName->renderViewHelper();?>
                            </div>
                            <div class="col-sm-6">
                                <?php echo $registerForm->lastName->renderLabel() . $registerForm->lastName->renderViewHelper();?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <?php echo $registerForm->emailAddress->renderLabel(). $registerForm->emailAddress->renderViewHelper();?>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-6">
                                <?php echo $registerForm->gender->renderLabel(). $registerForm->gender->renderViewHelper();?>
                            </div>
                            <div class="col-sm-6">
                                <?php echo $registerForm->dateOfBirth->renderLabel();?>
                                    <div class="row">
                                        <div class="col-sm-4">
                                        <?php echo $registerForm->dateOfBirthDay->renderViewHelper();?>
                                        </div>
                                        
                                        <div class="col-sm-4">
                                         <?php echo $registerForm->dateOfBirthMonth->renderViewHelper();?>
                                        </div>
                                        
                                        <div class="col-sm-4">
                                         <?php echo $registerForm->dateOfBirthYear->renderViewHelper();?>
                                        </div>
                                    </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-6">
                                <?php echo $registerForm->password->renderLabel(). $registerForm->password->renderViewHelper();?>
                            </div>
                            <div class="col-sm-6">
                                <?php echo $registerForm->confirmPassword->renderLabel(). $registerForm->confirmPassword->renderViewHelper();?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-6">
                                <?php echo $registerForm->postCode->renderLabel(). $registerForm->postCode->renderViewHelper();?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="note-box">
            <h2><?php echo $this->translate('E-mail & Nieuwsbrief instellingen') .':' ;?></h2>
            <div class="form-group">
                <?php echo $registerForm->weeklyNewsLetter->renderViewHelper();?>
                <label for="checkbox">
                    <strong><?php echo $this->translate('The Kortingscode.nl weekly newsletter');?></strong>
                    <?php echo $this->translate('The newsletter is Kortingscode.nl almost every week improved the next time. Our ultimate goal: The user can provide with only shops in which you are truly interested in a personal discount list.');?>
                </label>
            </div>
        </div>
        <?php 
        echo $this->formSubmit(
            'submit',
            $this->translate('update your settings'),
            array('class'=>'btn blue btn-lg btn-primary', 'id'=>'register')
        ) ?>
    </form>
</section>
