<section id="signup-lightbox">
    <div id="popup1" class="lightbox">
        <a class="glyphicon glyphicon-remove btn-close" onclick="customPopUpClose()"></a>
        <header class="head">
            <div class="icon">
                <img src="<?php echo $this->shopLogo;?>" width="176" height="89" alt="image description" title="image description">
            </div>
        </header>
        <div class='singup-heading'>
            <p class='first-p'>
            <?php
            echo FrontEnd_Helper_viewHelper::getLightBoxFirstTextText(
                $this->shopName,
                $this->shopLightBoxText['lightboxfirsttext']
            )
            ?>
            </p>
            <p class='second-p'>
            <?php 
            echo FrontEnd_Helper_viewHelper::getLightBoxSecondTextText(
                $this->shopName,
                $this->shopLightBoxText['lightboxsecondtext']
            )
            ?>
            </p>
        </div>
        <div class="block">
            <form id='singupFormInLightbox' name='singupFormInLightbox' role="form"
                class="form-signin newsletter" method="POST" 
                action='<?php echo HTTP_PATH_LOCALE
                .FrontEnd_Helper_viewHelper::__link("link_inschrijven") ."/"
                .FrontEnd_Helper_viewHelper::__link("link_signuplightboxsetsessions");?>'>
                <input id="shopId" type="hidden" value="" name="shopId">
                <input id="formName" type="hidden" value="singupFormInLightbox" name="formName">
                <input class="form-control" type="text" name='emailAddress' placeholder = 'E-mail' id='emailAddress'>
                <button 
                    onclick="setHiddenFieldValue(), signUpNewsLetterLightBox()"
                    type="submit" class="btn blue btn-lg btn-primary">
                    <?php echo FrontEnd_Helper_viewHelper::__form('form_Follow Sign up');?>
                </button>
            </form>
        </div>
        <footer class="bottom">
            <?php echo $this->translate('Already a member?');?>
            <a class='link' rel="nofollow" 
                href="<?php echo HTTP_PATH_LOCALE 
                .FrontEnd_Helper_viewHelper::__link("link_inschrijven") ."/"
                . FrontEnd_Helper_viewHelper::__link('link_setsession'). "/". $this->shopId; ?>">
                <?php echo $this->translate('Sign In'); ?>
            </a>
        </footer>
    </div>
</section>