<?php
$signupViewPath = "signup/";
$popularShops = '';
if(!empty($this->popularShops)) {
    $popularShops = $this->partial(
        $signupViewPath . '_popularStores.phtml',
        array('popularShops' => $this->popularShops)
    );
}
$favouriteShops = $this->partial(
    $signupViewPath . '_favouriteStores.phtml',
        array('favouriteShops' => $this->favouriteShops)
    );
?>
<div class="row">
    <div id="content" class="col-sm-8">
        <div class="section">
            <header class="heading">
            <?php echo $this->translate('Like your favourite shops');?>
            </header>
            <div class="row row-area">
            <?php echo $popularShops;?>
            </div>
        </div>
    </div>
    <aside id="sidebar" class="col-sm-4">
        <article class="block white">
            <header class="heading">
            <?php echo $this->translate('Your favorite shops');?>
            </header>
            <div class="box-area">
            <?php echo $favouriteShops; ?>
            </div>
        </article>
    </aside>
</div>