<ul id="alphabet" class="alphabet">
    <li class='<?php echo $this->selectedAlphabet=="09-e" ? "active-search-alphabet" : "";?>'>
        <a href="<?php echo HTTP_PATH_LOCALE. FrontEnd_Helper_viewHelper::__link('link_alle-winkels-09-e');?>">
        0-9 <span>-</span> A<span>-</span> B <span>-</span> C <span>-</span> D <span>-</span> E
        </a>
    </li>
    <li class='<?php echo $this->selectedAlphabet=="f-j" ? "active-search-alphabet" : "";?>'>
        <a href="<?php echo HTTP_PATH_LOCALE. FrontEnd_Helper_viewHelper::__link('link_alle-winkels-f-j');?>">
        F <span>-</span> G <span>-</span> H <span>-</span> I <span>-</span> J
        </a>
    </li>
    <li class='<?php echo $this->selectedAlphabet=="k-o" ? "active-search-alphabet" : "";?>'>
        <a href="<?php echo HTTP_PATH_LOCALE. FrontEnd_Helper_viewHelper::__link('link_alle-winkels-k-o');?>">
        K <span>-</span> L <span>-</span> M <span>-</span> N <span>-</span> O
        </a>
    </li>
    <li class='<?php echo $this->selectedAlphabet=="p-t" ? "active-search-alphabet" : "";?>'>
        <a href="<?php echo HTTP_PATH_LOCALE. FrontEnd_Helper_viewHelper::__link('link_alle-winkels-p-t');?>">
        P <span>-</span> Q <span>-</span> R <span>-</span> S <span>-</span> T
        </a>
    </li>
    <li class='<?php echo $this->selectedAlphabet=="u-z" ? "active-search-alphabet" : "";?>'>
        <a href="<?php echo HTTP_PATH_LOCALE. FrontEnd_Helper_viewHelper::__link('link_alle-winkels-u-z');?>">
        U <span>-</span> V <span>-</span> W <span>-</span> X <span>-</span> Y <span>-</span> Z
        </a>
    </li>
</ul>
