<?php
$storeClass = "<ul class='shop-name box col-md-4 col-sm-4'>";
foreach ($this->storesInformation as $storesKey => $stores) :
    if ($stores != null) :
        $alphabetName = $storesKey =="abc" ? "0-9" : $storesKey;
        echo '<div class="block" id="'.strtolower($alphabetName).'">'
            . '<h2>'. $alphabetName.'</h2>'
            . '<div class="row">';
        $totolStoredAsPerKey = (count($this->storesInformation[$storesKey]) / 3);
        $numberOfstores = array_chunk($this->storesInformation[$storesKey], $totolStoredAsPerKey + 1);
        foreach ($numberOfstores as $storesIndex => $storeForOneDiv):
               echo "<div class='box col-md-4 col-sm-4'>
                    <ul class='shop-name'>";
            foreach ($storeForOneDiv as $store):
                echo $storeName =
                    "<li>
                        <a href='".HTTP_PATH_LOCALE.$store['permaLink']."'>".$store['name']."</a>
                    </li>";
            endforeach;
            echo "</ul>";
            if(count($numberOfstores) == ($storesIndex + 1 )) :
                echo '<a href="#" class="btn-top">Back to top</a>';
            endif;
            echo "</div>";
           
        endforeach;
        echo "</div></div>";
    endif;
endforeach;
