<ul class="pagination">
    <li class='<?php echo $this->selectedAlphabet=="a-e" ? "active" : "";?>'>
        <a href="<?php echo HTTP_PATH_LOCALE. FrontEnd_Helper_viewHelper::__link('link_alle-winkels-a-e');?>">
            <?php echo FrontEnd_Helper_viewHelper::__translate('a to e');?>
        </a>
    </li>
    <li class='<?php echo $this->selectedAlphabet=="f-j" ? "active" : "";?>'>
        <a href="<?php echo HTTP_PATH_LOCALE. FrontEnd_Helper_viewHelper::__link('link_alle-winkels-f-j');?>">
            <?php echo FrontEnd_Helper_viewHelper::__translate('f to j');?>
        </a>
    </li>
    <li class='<?php echo $this->selectedAlphabet=="k-o" ? "active" : "";?>'>
        <a href="<?php echo HTTP_PATH_LOCALE. FrontEnd_Helper_viewHelper::__link('link_alle-winkels-k-o');?>">
            <?php echo FrontEnd_Helper_viewHelper::__translate('k to o');?>
        </a>
    </li>
    <li class='<?php echo $this->selectedAlphabet=="p-t" ? "active" : "";?>'>
        <a href="<?php echo HTTP_PATH_LOCALE. FrontEnd_Helper_viewHelper::__link('link_alle-winkels-p-t');?>">
            <?php echo FrontEnd_Helper_viewHelper::__translate('p to t');?>
        </a>
    </li>
    <li class='<?php echo $this->selectedAlphabet=="u-09" ? "active" : "";?>'>
        <a href="<?php echo HTTP_PATH_LOCALE. FrontEnd_Helper_viewHelper::__link('link_alle-winkels-u-09');?>">
            <?php echo FrontEnd_Helper_viewHelper::__translate('u to 09');?>
        </a>
    </li>
</ul>