<?php
if (isset($this->futureCodeCount) && $this->futureCodeCount != '') {
    ?>
    <div class="message">
        <div class="holder">
        <?php
        echo FrontEnd_Helper_viewHelper::__translate(
        'New Zalando codes! Within')
        . ' '
        . $this->futureCodeCount
        . ' ' 
        . FrontEnd_Helper_viewHelper::__translate('of new codes will be offered');
        ?>
        </div>
    </div>
    <?php
}
?>