<?php
$domainName = LOCALE == '' ? HTTP_PATH : HTTP_PATH_LOCALE;
$shopUrl = $domainName.'out/shop/'.$this->shop['id'];
?>
<ul class="add-info">
<?php
if($this->shop['howToUse']):
?>
    <li>
        <h4><?php echo $this->translate('How to use code'); ?></h4>
        <p>
            <?php 
            echo $this->translate('Read our full'); 
            ?> 
            <a href="<?php echo HTTP_PATH_LOCALE.$this->howToUseGuidePermalink; ?>#guide">
            <?php echo $this->shop['name'].' '.$this->translate('Promotional Code'); ?>
            </a>
            <?php echo $this->translate('help guide'); ?>.
        </p>
    </li>
<?php endif; ?>    
    <li class="web">
        <h4><?php echo $this->translate('Official website'); ?></h4>
        <a href="<?php echo $shopUrl; ?>" rel="nofollow" target="_blank"><?php echo $this->actualUrl;?></a>
    </li>
</ul>