<?php $this->partial('offer/_jsFileForOfferPartial.phtml'); ?>
<section class="section">
<?php
$offerCounter = '';
foreach ($this->offers as $offer) {
    $offerCounter++;
    $offer = (object) $offer;
    $offerBounceRate = "/out/offer/".$offer->id;
    $offerPartial = new FrontEnd_Helper_OffersPartialFunctions();
    $daysTillOfferExpires = $offerPartial->getDaysTillOfferExpires($offer->endDate);
    $urlToShow = $offerPartial->getUrlToShow($offer);
    $offerTitle = $offer->title;
    $termsAndConditions = $offerPartial->getOfferTermsAndCondition($offer);
    $userLoggedInOrNot = $offerPartial->getUserIsLoggedInOrNot();
    ?>
    <article class="block <?php echo $offer->exclusiveCode == '1' ? "orange-block" : "active"; ?>">
        <div class="holder">
            <?php echo $offerPartial->getCommonRedirectUrlForOffer($offer, $urlToShow, $offerBounceRate, $this->offersType , 'offerImage'); ?>
            <div class="box">
    <?php
    if ($offer->discountType == 'PR' || $offer->discountType == 'PA') {
                ?>
                <div class="img-code">
                    <img width="163" height="96" alt="image description" src="<?php echo $urlToShow; ?>">
                </div>
    <?php
    }
    ?>
                <div class="text">
                    <p> <?php echo $offerPartial->getOfferOptionAndOfferDates($offer, $daysTillOfferExpires)?></p>
                    <?php echo $offerPartial->getCommonRedirectUrlForOffer($offer, $urlToShow, $offerBounceRate, $offerTitle, 'offerTitle'); ?>
                </div>
                <div class="buttons" id="offerButton<?php echo $offer->id ;?>">
    <?php
    $permalink = $this->offersType=='categoryOffers' ? $this->categoryPermaLink : $offer->shop['permaLink']; 
    echo $offerPartial->getCommonRedirectUrlForOffer($offer, $urlToShow, $offerBounceRate, $permalink, 'mainOfferClickoutButton');
    echo $offerPartial->getSecondButtonforOffer($offer, $urlToShow, $offerBounceRate, $permalink);
    ?>
                </div>
                <div class="the-code" id="offerCodeDiv<?php echo $offer->id ;?>">
                    <span class="instruction"><strong><?php echo $this->translate('enter this code at checkout')?></strong></span>
                    <strong class="code-value"><?php echo $offer->couponCode;?></strong>
                </div>
    
                <ul class="view-list">
                    <li>
    <?php 
    if ($this->offersType!='expiredOffer') {
        echo $offerPartial->getTermAndConditionsLink($offer, $termsAndConditions);
        echo $offerPartial->getExtendedOfferLink($offer);
    } else {
        echo $offerPartial->getViewAllCodeLink($offer->shop['name']);
    }
    ?>
                    </li>
                </ul>
            </div>
        </div>
    <?php
    if ($this->offersType!='expiredOffer') {
            $style = '';
    } else {
            $style = 'style="display:block;"';
    }
    ?>
        <div class="offer-box" id="websiteOfferLink<?php echo $offer->id ;?>" <?php echo $style; ?>>
            <hr class="alt2">
            <div class="offer">
                <span><?php echo $this->translate('Grab this offer now:');?></span>
                <a target = "_blank" href="<?php echo $urlToShow;?>">
                <?php echo $this->translate('Open ');?>
                <?php echo $offer->shop['name']; ?>
                <?php echo $this->translate(' website');?>
                </a>
            </div>
        </div>
        <div  class="terms-block" id='termAndConditions<?php echo $offer->id ;?>'>
            <h2><?php echo $this->translate('Terms');?> &amp; <?php echo $this->translate('Conditions')?></h2>
            <ol class="num-list">
            <?php echo $termsAndConditions;?>
            </ol>
        </div>
    </article>
    <?php
    $shopLogoOrDefaultImage = $offerPartial->getShopLogoForSignUp($this->shop);

    if($offerCounter == 1) :
        if($this->offersType=='simple' || $this->offersType=='top20' || $this->offersType=='offerPage'):
            echo $this->partial(
                'store/signupwidget.phtml',
                array(
                   'zendForm' => $this->zendForm,
                   'SignupFormWidgetType'=> 'widgetWithinOffers',
                   'shopId'=>$this->shop['id'],
                   'shopLogoOrDefaultImage'=>$shopLogoOrDefaultImage
               )
            );
        endif;
    endif;
}
if ($this->offersType!='expiredOffer') {
    if ($this->offersType == 'newestOffer' || $this->offersType=='offerWithPagenation' || $this->offersType=='offerPage') {
        echo $this->paginationControl($this->offers, 'Sliding', '/partials/_pagination.phtml');
    }
    if (isset($this->pageType) && $this->pageType == 'howToGuide') {
        $domainName = LOCALE == '' ? HTTP_PATH : HTTP_PATH_LOCALE;
        echo '<a class="link-box" href="'.$domainName.$offer->shop['permalink'].'">
                <hr class="alt2">
                '.$this->translate('View all voucher codes from').' '.$offer->shop['name'].'
            </a>';
    }
    ?>
</section>
<?php }?>