<section class="section">
<?php
$offerCounter = '';
foreach ($this->offers as $offer) {
    $offerCounter++;
    $offer = (object) $offer;
    $offerBounceRate = "/out/offer/".$offer->id;
    $offerPartialClass = new FrontEnd_Helper_OffersPartialFunctions();
    $daysTillOfferExpires = $offerPartialClass->getDaysTillOfferExpires($offer->endDate);
    $urlToShow = $offerPartialClass->getUrlToShow($offer);
    $offerTitle = $offer->title;
    $termsAndConditions = $offerPartialClass->getOfferTermsAndCondition($offer);
    $userLoggedInOrNot = $offerPartialClass->getUserIsLoggedInOrNot();
    ?>
    <article class="block <?php echo $offer->exclusiveCode == '1' ? "orange-block" : "active"; ?>">
        <div class="holder">
            <a id="<?php echo $offer->id ;?>" class="<?php echo $offerPartialClass->getClassNameForOffer($offer, $this->offersType);?>" 
            href="<?php echo $urlToShow;?>" rel="nofollow"
            target="_blank"
            onClick="<?php echo $offer->discountType == "CD" ? 'showCodePopUp(this),' : '' ?> viewCounter('onclick', 'offer', <?php echo $offer->id; ?>), ga('send', 'event', 'aff','<?php echo $offerBounceRate; ?>');">
            <?php echo $offerPartialClass->getOfferImage($offer, $this->offersType);?>
            </a>
            <div class="box">
    <?php
    if ($offer->discountType == 'PR' || $offer->discountType == 'PA') {
                ?>
                <div class="img-code">
                    <img width="163" height="96" alt="image description" src="<?php echo $urlToShow; ?>">
                </div>
    <?php
    }
    ?>
                <div class="text">
                    <p> <?php echo $offerPartialClass->getOfferOptionAndOfferDates($offer, $daysTillOfferExpires)?></p>
                    <a id="<?php echo $offer->id ;?>"
                    href="<?php echo $urlToShow;?>"
                    rel="nofollow" class="link" target="_blank"
                    onClick="<?php echo $offer->discountType == "CD" ? 'showCodePopUp(this),' : '' ?> ga('send', 'event', 'aff','<?php echo $offerBounceRate; ?>');">
                    <?php echo $offerTitle;?>
                    </a>
                </div>
                <div class="buttons" id="offerButton<?php echo $offer->id ;?>">
    <?php
    echo $offerPartialClass->getMainButtonforOffer($offer, $urlToShow, $offerBounceRate);
    echo $offerPartialClass->getSecondButtonforOffer($offer, $urlToShow, $offerBounceRate);
    ?>
                </div>
                <div class="the-code" id="offerCodeDiv<?php echo $offer->id ;?>">
                    <span class="instruction"><strong><?php echo $this->translate('enter this code at checkout')?></strong></span>
                    <strong class="code-value"><?php echo $offer->couponCode;?></strong>
                </div>
    
                <ul class="view-list">
                    <li>
    <?php 
    if ($this->offersType!='expiredOffer') {
        echo $offerPartialClass->getTermAndConditionsLink($offer, $termsAndConditions);
        echo $offerPartialClass->getExtendedOfferLink($offer);
    } else {
        echo $offerPartialClass->getViewAllCodeLink($offer->shop['name']);
    }
    ?>
                    </li>
                </ul>
            </div>
        </div>
    <?php
    if ($this->offersType!='expiredOffer') {
            $style = '';
    } else {
            $style = 'style="display:block;"';
    }
    ?>
        <div class="offer-box" id="websiteOfferLink<?php echo $offer->id ;?>" <?php echo $style; ?>>
            <hr class="alt2">
            <div class="offer">
                <span><?php echo $this->translate('Grab this offer now:');?></span>
                <a target = "_blank" href="<?php echo $urlToShow;?>">
                <?php echo $this->translate('Open ');?>
                <?php echo $offer->shop['name']; ?>
                <?php echo $this->translate(' website');?>
                </a>
            </div>
        </div>
        <div  class="terms-block" id='termAndConditions<?php echo $offer->id ;?>'>
            <h2><?php echo $this->translate('Terms');?> &amp; <?php echo $this->translate('Conditions')?></h2>
            <ol class="num-list">
            <?php echo $termsAndConditions;?>
            </ol>
        </div>
    </article>
    <?php
    $shopLogoOrDefaultImage = $offerPartialClass->getShopLogoForSignUp($this->shop);
    if(($offerCounter == 1 && $this->offersType=='simple') || ($offerCounter == 1 && $this->offersType=='top20')):
        echo $this->partial(
            'store/signupwidget.phtml',
            array(
               'zendForm' => $this->zendForm,
               'flagForDivClass'=>false,
               'shopId'=>$this->shop['id'],
               'shopLogoOrDefaultImage'=>$shopLogoOrDefaultImage
           )
        );
    endif;
}
if ($this->offersType!='expiredOffer') { ?>
    </section>
<?php }?>
