<?php
echo FrontEnd_Helper_OfferPartialFunctions::getSectionHeader($this->shopName, $this->offersType);
?>
<section class="section">
<?php
$dummyPartialCounter = '';
foreach ($this->offers as $offer) {
    $dummyPartialCounter++;
    $offer = (object) $offer;
    $offerTitle = substr($offer->title, 0, 150);
    $termsAndConditions = FrontEnd_Helper_OfferPartialFunctions::getOfferTermsAndCondition($offer);
    $urlToShow = FrontEnd_Helper_OfferPartialFunctions::getUrlToShow($offer);
    $userLoginStatus = FrontEnd_Helper_OfferPartialFunctions::getUserIsLoginOrNot();
    $offerBounceRate = "/out/offer/".$offer->id;
    $dayDifference = FrontEnd_Helper_OfferPartialFunctions::getDaysDifference($offer->endDate);
    ?>
    <article class="block <?php echo $offer->exclusiveCode == '1' ? "orange-block" : "active"; ?>">
        <div class="holder">
            <a class="<?php echo FrontEnd_Helper_OfferPartialFunctions::getClassNameForOffer($offer);?>" href="<?php echo $urlToShow;?>" rel="nofollow"
            target="_blank"
            onClick="viewCounter('onclick', 'offer', <?php echo $offer->id; ?>), ga('send', 'event', 'aff','<?php echo $offerBounceRate; ?>');">
            <?php echo FrontEnd_Helper_OfferPartialFunctions::getOfferImage($offer, $this->offersType);?>
            </a>
            <div class="box">
                <div class="text">
                    <p> <?php echo FrontEnd_Helper_OfferPartialFunctions::dateStringFormat($offer, $dayDifference)?></p>
                    <a id="<?php echo $offer->id ;?>"
                    href="<?php echo $urlToShow;?>"
                    rel="nofollow" class="link" target="_blank"
                    onClick="<?php echo $offer->discountType == "CD" ? 'showCodePopUp(this),' : '' ?> ga('send', 'event', 'aff','<?php echo $offerBounceRate; ?>');">
                    <?php echo $offerTitle;?>
                    </a>
                </div>
                <div class="buttons" id="offerButton<?php echo $offer->id ;?>">
<?php   
echo FrontEnd_Helper_OfferPartialFunctions::getMainButtonforOffer($this,$urlToShow,$offerBounceRate);   
echo FrontEnd_Helper_OfferPartialFunctions::getSecondButtonforOffer($this,$urlToShow,$offerBounceRate);
?>
                </div>
                <div class="the-code" id="offerCodeDiv<?php echo $offer->id ;?>">
                    <span class="instruction"><strong><?php echo $this->translate('enter this code at checkout')?></strong></span>
                    <strong class="code-value"><?php echo $offer->couponCode;?></strong>
                </div>
    
                <ul class="view-list">
                    <li>
    <?php
    if ($offer->userGenerated ==0 &&  $termsAndConditions!='' && $termsAndConditions!=null) { ?>
                        <a id="termAndConditionLink<?php echo $offer->id ;?>" onclick="showTermAndConditions(<?php echo $offer->id; ?>)" class="terms"
                        href="javascript:void(0);"><?php echo $this->translate('Term'); ?> &amp;
                        <?php echo $this->translate('Conditions'); ?>
                        </a>
        <?php
        if ($termsAndConditions!='' && $termsAndConditions!=null && $offer->extendedOffer =='1') {?>
            &nbsp; | &nbsp;
            <?php
        }
    }?>
    <?php
    if ($offer->extendedOffer =='1'):?>
                        <a class="text-blue-link"
                        href="<?php echo HTTP_PATH_LOCALE .FrontEnd_Helper_OfferPartialFunctions::__link('deals').'/'. $offer->extendedUrl;?>">
                        <?php echo $this->translate('Meer over deze code'); ?>
                        </a>
        <?php
    endif;?>
                    </li>
                </ul>
            </div>
        </div>
        <div class="offer-box" id="websiteOfferLink<?php echo $offer->id ;?>">
            <hr class="alt2">
            <div class="offer">
                <span><?php echo $this->translate('Grab this offer now:');?></span>
                <a href="<?php echo $urlToShow;?>">
                <?php echo $this->translate('Open ');?>
                <?php echo $offer->shop['name']; ?>
                <?php echo $this->translate(' website');?>
                </a>
            </div>
        </div>
        <div  class="terms-block" id='termAndConditions<?php echo $offer->id ;?>'>
            <h2><?php echo $this->translate('Terms');?> &amp; <?php echo $this->translate('Conditions')?></h2>
            <ol class="num-list">
            <?php echo $termsAndConditions;?>
            </ol>
        </div>
    </article>
    
    <?php
    if(($dummyPartialCounter == 1 && $this->offersType=='simple')
        || ($dummyPartialCounter == 1 && $this->offersType=='top20')):?>
        <div class="block block-form <?php echo $this->shop=='' ? 'block-form-2' : ''?>">
            <div class="holder">
                 <div class="<?php echo $this->shop=='' ? 'ico-box' : 'icon'?>">
                    <?php echo FrontEnd_Helper_OfferPartialFunctions::getShopLogoForSignUp($this->shop);?>
                 </div>
                <?php 
                if (!Auth_VisitorAdapter::hasIdentity()) {?>
                    <div class="box">
                        <h2><?php echo $this->translate('Receive weekly updates of the best offers?');?><br> 
                        <?php echo $this->translate('Sign up for our newsletter!');?></h2>
                        <?php echo $this->zendForm;?>
                    </div>
                    <?php 
                }
               ?>
           </div>
        </div>
        <?php 
    endif;
}
?>
</section>
