<!-- NEW LETTER SIGNUP FORM -->
<div class="block block-form">
	<div class="holder">
		<div class="icon">
			<img width="176" height="89" alt="image description" src="<?php echo HTTP_PATH;?>public/images/ico-01.png">
		</div>
		<div class="box">
			<h2>Receive weekly updates of the best offers? <br> Sign up for our newsletter!</h2>
			<form class="form-signin newsletter" role="form">
				<input type="email" class="form-control">
				<button class="btn blue btn-lg btn-primary" type="submit">sign up</button>
			</form>
		</div>
	</div>
</div>