<div class="block">
    <h1 class = "popular-store-title"><?php echo $this->translate('Popular stores'); ?></h1>
        <ul class="shops">
<?php
$popularStoreIncrementCheck = 1;

foreach ($this->popularStores as $popularStore) :
    $popularStoreIncrementCheck++;
    if ($popularStoreIncrementCheck == 8) :
        break;
    endif;

    if (count($popularStore['shop']['logo']) > 0) :
        $popularStoreImage =
    		PUBLIC_PATH_CDN
    		.ltrim($popularStore['shop']['logo']['imgpath'], "/")
    		."thum_medium_".$popularStore['shop']['logo']['imgname'];
    else :
        $popularStoreImage = HTTP_PATH . "public/images/NoImage/storeLogo100_50.jpg";
    endif;

    echo '<li>
        <a href="'.HTTP_PATH_LOCALE.$popularStore['shop']['permaLink'].'">
            <img src="' . $popularStoreImage . '"  
            alt="' .$popularStore['shop']['name'] . '" width="92" height="47" />
        </a>
    </li>';
endforeach;
?>
        </ul>
</div>