<?php
$this->minifyHeadScript()->prependFile("/public/js/front_end/lightbox.js");
echo $this->shopEditor;
$frontendHelper = new FrontEnd_Helper_viewHelper();
echo $frontendHelper->socialMediaWidget($this->currentStoreInformation['affliateProgram'] =='' ? $this->currentStoreInformation['actualUrl'] : $this->currentStoreInformation['affliateProgram']);

if (count($this->latestShopUpdates) > 0):?>
    <?php echo $this->partial('store/_latestNews.phtml', array('latestShopUpdates' => $this->latestShopUpdates));
endif;

if ($this->shopChain):
    ?>
        <article class="block">
    <?php echo $this->shopChain; ?>
        </article>
    <?php
endif;
        
if(isset($this->popularStoresList)):
    echo $this->popularStoresList;
endif;

echo $this->signUpWidgetForm;