<header class="heading-box text-shop">
    <h2>
<?php 
echo $this->translate('Similar shops');
?>  
    </h2>
    <strong>
<?php 
echo $this->translate('Check out these similar shops for more discounts');
?>  
    </strong>
</header>
<section class="section">
    <div class="block">
       <div class="holder">
           <ul class="shops">
<?php
if (!empty($this->similarShopsAndSimilarCategoryShops)) {
    foreach ($this->similarShopsAndSimilarCategoryShops as $shop) {
        $shopLogoName = isset($shop['category']['logo']['name']) ? $shop['category']['logo']['name'] : '';
        $shopLogoPath = isset($shop['category']['logo']['path']) ? $shop['category']['logo']['path'] : '';
        printf(
            '<li><a href="%s"><img style="max-width: 84px;" alt="%s" src="%s"></a></li>',
            HTTP_PATH_LOCALE  . $shop['category']['permaLink'],
            $shop['category']['name'],
            PUBLIC_PATH_CDN . ltrim($shopLogoPath, "/") . 'thum_small_'. $shopLogoName
        );
  
    }
}
?>
           </ul>
       </div>
    </div>
</section>