<header class="heading-box text-shop">
    <h2>
<?php 
echo $this->translate('Similar shops');
?>  
    </h2>
    <strong>
<?php 
echo $this->translate('Check out these similar shops for more discounts');
?>  
    </strong>
</header>
<section class="section">
    <div class="block">
       <div class="holder">
           <ul class="shops">
<?php
if (!empty($this->similarShopsAndSimilarCategoryShops)) {
    foreach ($this->similarShopsAndSimilarCategoryShops as $shop) {
        if (!empty($shop)) {
            $shopName = isset($shop['name']) ? $shop['name'] : '';
            $shopPath = isset($shop['path']) ? $shop['path'] : '';
            $shopsPermalink = isset($shop['permaLink']) ? $shop['permaLink'] : '';
            $shopLogoName = isset($shop['category']['logo']['name']) ? $shop['category']['logo']['name'] : $shopName;
            $shopLogoPath = isset($shop['category']['logo']['path']) ? $shop['category']['logo']['path'] : $shopPath;
            $shopPermalink = isset($shop['category']['permaLink']) ? $shop['category']['permaLink'] : $shopsPermalink;
            $similarShopName = isset($shop['shopName']) ? $shop['shopName'] : '';
            $shopName = isset($shop['category']['name']) ? $shop['category']['name'] : $similarShopName;
            printf(
                '<li><a href="%s"><span class="similar-shops-images" data-src="%s">%s</span></a></li>',
                HTTP_PATH_LOCALE  . $shopPermalink,
                PUBLIC_PATH_CDN . ltrim($shopLogoPath, "/") . 'thum_medium_'. $shopLogoName,
                $shopName.' '.FrontEnd_Helper_viewHelper::__form('form_discount vouchers')
            );
        } 
    }
}
?>
           </ul>
       </div>
    </div>
</section>