 <section class="section six-reasons">
    <header class="heading-box">
        <h2>
            <?php echo $this->translate('6 reasons to Kiesen for') . " " .
            $this->shopName. " " . $this->translate('coupon code');
            ?>
        </h2>
    </header>
    <article class="block">
        <div class="row">
            <?php
             foreach($this->reasons  as $reason) {
                ?>
                <div class="col-md-6">
                    <div class='six-reason-image'>
                    </div>
                    <div class='six-reason-text'>
                        <h2><?php echo $reason[0];?></h2>
                        <h3><?php echo $reason[1];?></h3>
                    </div>
                    </ul>
                </div>
                <?php
            }
            ?>
        </div>
    </article>
</section>