<?php
$authorName = FrontEnd_Helper_AuthorPartialfunctions::
    getAuthorName($this->shopEditor['firstName'], $this->shopEditor['lastName']);
$EditorImageSlug = $this->shopEditor['slug'];
$shopHeader = $this->translate('All').' '.$this->shop['name'].' '.$this->translate('deals verified by');
$shopEditorPath =
	HTTP_PATH_CDN 
	.ltrim($this->shopEditor['profileimage']['path'], "/")
	.'thum_large_widget_' .$this->shopEditor['profileimage']['name'];
$shopAbout = $this->translate('About').' '.$this->shop['name'].' '.$this->translate('Vouchers').' '.date('Y');

$howToUse = '';
if($this->shop['howToUse']):
    $howToUse = $this->partial(
        'store/_howToUseGuide.phtml',
        array(
           'shop' => $this->shop,
           'howToUseGuidePermalink' => $this->howToUseGuidePermalink,
           'actualUrl'=>$this->actualUrl
        )
    );
endif;
?>
<article class="block">
    <div class="intro intro-2">
        <div class="deal">
            <div class="deal-holder">
                <span class="text"><?php echo $shopHeader; ?>
                    <span class="name"><?php echo $authorName; ?></span>
                </span>
                <div class="photo">
                    <span class="text-box"><?php echo $this->translate('Hello'); ?></span>
                    <img alt="<?php echo $authorName; ?>" class="" 
                    src="<?php echo $shopEditorPath; ?>" width="120" height="120"/>
                </div>
            </div>
        </div>
        <h1><?php echo $shopAbout; ?></h1>
        <?php echo $this->shop['shopText']; ?>
    </div>
<?php echo $howToUse; ?>
</article>