<?php
$authorName = FrontEnd_Helper_AuthorPartialFunctions::
    getAuthorName($this->shopEditor[0]['firstName'], $this->shopEditor[0]['lastName']);

$profileLink = HTTP_PATH_LOCALE.FrontEnd_Helper_viewHelper::__link("link_redactie")."/"
                    . $this->shopEditor[0]['slug'];
$shopHeader = $this->translate('All').' '.$this->shop['name'].' '.$this->translate('deals verified by');
$shopEditorPath =
	HTTP_PATH_CDN 
	.ltrim($this->shopEditor[0]['profileimage']['path'], "/")
	.'thum_large_widget_' .$this->shopEditor[0]['profileimage']['name'];
$shopAbout = $this->translate('About').' '.$this->shop['name'];


$howToUse = $this->partial(
    'store/_howToUseGuide.phtml',
    array(
       'shop' => $this->shop,
       'howToUseGuidePermalink' => $this->howToUseGuidePermalink,
       'actualUrl'=>$this->actualUrl
    )
);

?>
<article class="block">
    <div class="intro intro-2">
        <div class="deal">
            <div class="deal-holder">
                <span class="text"><?php echo $shopHeader; ?>
                    <span class="name"><?php echo $authorName; ?></span>
                </span>
                <div class="photo">
                <?php
                    $editorText = FrontEnd_Helper_viewHelper::getEditorText(
                        $this->shop['name'],
                        $this->shopEditor[0]['editorText'],
                        $this->shopEditor[1]
                    );
                    $i = 0;
                    if (is_array($editorText)) { ?>
                            <?php foreach ($editorText as $text) { ?>
                                    <span class = "text-box text-box-ballon" id="text-box-<?php echo $i;?>" style="display:none;"><?php echo $text; ?></span>
                            <?php 
                            $i++;
                            } ?>
                    <?php } else { ?>
                        <span id="text-box" class="text-box">
                            <?php echo $editorText;?>
                        </span>
                    <?php }  ?>
                    <span>
                        <img title="<?php echo $authorName; ?>" alt="<?php echo $authorName; ?>" class=""
                        src="<?php echo $shopEditorPath; ?>" width="120" height="120"/>
                    </span>    
                </div>
            </div>
        </div>
        <h2><?php echo $shopAbout; ?></h2>
        <?php 
        echo  preg_replace('/(<a\b[^><]*)>/i', '$1 style="color: #0077cc;text-decoration: underline;">',
        $this->shop['shopText']); ?>
    </div>
<?php echo $howToUse; ?>
</article>