<div class="voucher-col1 voucher-col1-new ">
		<form name="discount_code" id="discount_code" action="#" method="POST" novalidate="novalidate">
		<input id="offer_nameHidden"  name="offer_nameHidden" type="hidden"/>
     	<input id="shopId"  name="shopId" type="hidden"/>
			<div class="codeToe_img"><img src="<?php echo HTTP_PATH ?>public/images/front_end/codeToe_img.png" alt="" /></div>
	    	<div class="codeToe_rt">
		    	<div class="voucher-col1-top-heading-new ml-none">
						<h3>
							<?php echo $this->translate('Heb he enn kortingscode gevonden ? Voeg hen toe!'); ?>
						</h3>
				</div> 
				<div class="fl">  
			    	<div class="rt_input">
			        	<input type="text" name="offer_name" id="offer_name" placeHolder="<?php echo $this->translate('Voor welke shop?') ?>" />	    
			        </div>
			        <div class="rt_input">
			       	 	<input type="text" name="offer_code" id="offer_code" placeHolder="<?php echo $this->translate('Vul hier de kortingscode in') ?>" />
			        </div>
	        	</div>
		        <div class="rt_txtarea">
		        	<div class="rt_txtarea_txt">
		        		<textarea name="offer_desc" id="offer_desc" placeHolder="<?php echo $this->translate('Geef alle informatie die je hebt over dese code:wees volledig')?>" rows="4" cols="20"></textarea>
		        	</div>
		            <a onClick="sendiscountCoupon()" href="javascript:void(0);"> <?php echo $this->translate('Code toevoegen'); ?> </a>
		        </div>
	    	</div>
		</form>
	</div>
