<?php
$visitorId = Auth_VisitorAdapter::hasIdentity() ? Auth_VisitorAdapter::getIdentity()->id : 0;
$redirectUrl = HTTP_PATH_LOCALE. 'store/addtofavourite?permalink='. $this->permalink .'&shopId='
    . base64_encode($this->shopId);
$titleTextForLove = FrontEnd_Helper_viewHelper::__form('form_Remove from Favourite');
$emAndSpan = '<em>'.FrontEnd_Helper_viewHelper::__translate("I FOLLOW THIS").'</em>
    <strong>'.FrontEnd_Helper_viewHelper::__translate("REMOVE").'</strong>';
$aTagClasses = 'pop btn btn-sm btn-default remove-fovourite blue btn-holder';
if (KC\Repository\Visitor::getFavoriteShopsForUser($visitorId, $this->shopId)==false):
    $titleTextForLove = FrontEnd_Helper_viewHelper::__form("form_Add in Favourite");
    $emAndSpan = '<span class="glyphicon red-heart glyphicon-heart"></span>
        <span class = "follow-text">'.FrontEnd_Helper_viewHelper::__translate("FOLLOW").'</span>';
    $aTagClasses = 'pop btn btn-sm btn-default follow-button btn-holder';
endif;

$clickEvent = '';
if ($visitorId==0) {
    $redirectUrl = 'javascript:void(0)';
    $clickEvent = "onclick=showSignUpPopUp();";
}
echo  '<a title="'. $titleTextForLove .'" '.$clickEvent.' href="' . $redirectUrl .'" 
    class="'. $aTagClasses . '">'. $emAndSpan.
'</a>';
?>