<?php
$this->minifyHeadScript()->prependFile("public/js/front_end/socialmedia.js");

$storeViewPath = 'store/';
$popularStores = '';
if (count($this->popularStores)) :
     $popularStores = $this->partial(
         $storeViewPath.'_popular-stores.phtml',
         array('popularStores' => $this->popularStores)
     );
endif;

$storesInformation = '';
if ($this->storesInformation != '' && $this->storesInformation != null) :
    $storesInformation = $this->partial(
        $storeViewPath.'_all-stores-listing.phtml',
        array('storesInformation' => $this->storesInformation)
    );
endif;
?>
<div class="header-block">
    <div class="icon icon-small">
        <img src="<?php echo HTTP_PATH; ?>public/images/ico-02.png" width="89" height="89" alt="image description">
    </div>
    <div class="box">
        <h1><?php echo $this->translate('All stores'); ?></h1>
        <strong><?php echo $this->translate('All stores sorted out for you from A to Z'); ?></strong>
    </div>
</div>
<div class="row">
    <div id="content" class="col-md-8 col-sm-8">
        <div class="content-holder">            
<?php 
echo $this->storeSearchByAlphabet;
echo $popularStores;
echo $storesInformation;
?>
        </div>
    </div>
    <aside id="sidebar" class="col-md-4 col-sm-4 col-sm-4">
<?php
echo $this->esi($this->locale.$storeViewPath.'signupwidget');

$controllerName =  $this->controllerName;
$socialMediaTitle = "<h2>".$this->translate('Share')."</h2>
                    <span>".$this->translate('And receive cool discounts and useful actions through google+, twitter and Facebook')."</span>";

echo FrontEnd_Helper_viewHelper::socialmediaSmall('', $socialMediaTitle, $controllerName);
?>
    </aside>
</div>
</div>