<div class="news-box">
	<article class="box">
		<?php 
		$datetime = strtotime($this->startdate);
		$date = date('d', $datetime);
		$month = date('M', $datetime);
		$year = date('Y', $datetime);
		$httpStringPosition = 'http';
	 	?>
		<em class="date"><?php echo $date.' '.$month.' '.$year; ?></em>
		<h3>
		<?php if ($this->url!=null && $this->url!='') { ?>	
			<a href="
			<?php
				if (strpos($this->url,$httpStringPosition) !== false) {
					echo $this->url;
				} else {
					echo 'http://'.$this->url; 
				}?>" target="_blank"><?php echo $this->title;?></a>
		<?php } else { 
			echo $this->title;
		}?>
        </h3>
		<p>
		<?php 
		if ($this->content!=""): 
			$content = $this->content;
			echo $content;
		else: 
			echo "No desc found"; 
		endif;?>
		</p>
	</article>
</div>