<?php $articleImage = PUBLIC_PATH_CDN.ltrim($this->ArtIcon['path'], "/") . 'thum_article_medium_'. $this->ArtIcon['name']; ?>
<section class="tips-section">
    <article class="block">
        <a onClick="javascript:viewCounter('onclick', 'article', <?php echo $this->id ; ?>);" 
        href="<?php echo HTTP_PATH_LOCALE .FrontEnd_Helper_viewHelper::__link('bespaarwijzer').'/'.$this->permalink;?>"
        title='<?php echo $this->title;?>'>
            <div class="image">
                <img id="<?php echo $this->articles['id']; ?>" alt="<?php echo $this->title;?>" src="<?php echo $articleImage;?>" width="216" height="129">
            </div>
            <div class="box">
                <h2>
<?php 
if (strlen($this->title) > 35) {
    echo substr($this->title, 0, 35).'..';
} else {
    echo $this->title;
}
?>
                </h2>
                <p>
<?php 
if (isset($this->chapters[0])) {
    if ($this->chapters[0]['content']!=null || $this->chapters[0]['content']!='undefined' || $this->chapters[0]['content']!='') {
        $allowedTags = '<p>';
        $articleContent = $this->chapters[0]['content'];
        $articleContent = strip_tags($articleContent);
        if (strlen($articleContent) > 120) {
            echo substr($articleContent, 0, 120).'...';
        } else {
            echo $articleContent;
        }
    }
}
?>
                </p>
            </div>
        </a>
    </article>
</section>    