<?php
$signUpForm = $this->partial(
    'partials/_signupwidget.phtml',
    array(
        'flagForDivClass'=>$this->flagForDivClass,
        'zendForm'=>$this->zendForm,
    )
);

$id = 0;
if(Auth_VisitorAdapter::hasIdentity()):
    $id = Auth_VisitorAdapter::getIdentity()->id;
endif;
$shopId = $this->shopId=='' ? 0 : $this->shopId;
if (Visitor::getFavoriteShopForUser($id, $shopId)==false):
    if ($this->flagForDivClass==false) {?>
        <div class="block block-form <?php echo $this->shop=='' ? 'block-form-2' : ''?>">
            <div class="holder">
                <div class="<?php echo $this->shopId=='' ? 'ico-box' : 'icon'?>">
                <?php echo $this->shopLogoOrDefaultImage;?>
                </div>
            <?php echo $signUpForm;?>
            </div>
        </div>
        <?php 
    } else {
        echo $signUpForm;
    }
endif;
