<?php
if (!Auth_VisitorAdapter::hasIdentity()): ?>
    <div class="block block-2">
        <h2 class="form-signin-heading">
        <?php echo $this->translate('Sign up'); ?>
        <span>
        <?php echo $this->translate('and join over'); ?>
        <br>
        <?php echo $this->translate('10 million people'); ?>
        </span>
        </h2>
        <?php echo $this->zendForm;?>
    </div>
    <?php
endif;
