<div class="widget">
    <h3><?php echo $this->translate('Share Codes');?></h3>
    <strong class="sub-title"><?php echo $this->translate('Thank you for sharing your offer!');?></strong>
    <div class="sub-text">
        <p>
        <?php echo $this->translate('Thanks for sharing your coupon with the Flipit Community! Our team will check the details and publish the code');?>
        </p>
    </div>
    <a href="<?php echo HTTP_PATH_LOCALE; ?>/<?php echo FrontEnd_Helper_viewHelper::__link('link_all-shops');?>">
        <?php echo $this->translate('Share coupon codes for other shops');?>
    </a>
</div>