<script type="text/javascript">
    $(document).ready(function(){
    $('input#shopId').val($('input#currentShop').val())
    $("#sharecode").click(function(){
        saveSocialCode();
        return false;
    });
});

function saveSocialCode() {
    $.ajax({
        url : HOST_PATH_LOCALE + 'store/socialcode',
        method : "post",
        data: $('form#socialcodeForm').serialize(),       
        dataType : "json",
            type : "post",
            success : function(data) {
            if (data != null) {
                $('aside#sidebar .widget').remove();
                $('aside#sidebar').append(data);
            } else {
                alert(__("Problem in your data"));
            }
        }
    });
}
</script>
<?php
$socialcodeForm = $this->zendForm;
foreach ($socialcodeForm->getElements() as $formElement) {
    $formElement->getDecorator('label')->setOption('tag', null);
}
?>
<div class="widget">
    <form id="socialcodeForm" class="widget-form" name="socialcodeForm" method="POST" 
        action="">
        <h3><?php echo $this->translate('Social Code');?></h3>
        <p><?php echo $this->translate('Share a code with our users');?></p>
        <?php 
        echo $socialcodeForm->shops->renderViewHelper();
        echo $socialcodeForm->code->renderViewHelper();
        echo $socialcodeForm->offerDetails->renderViewHelper();
        echo $socialcodeForm->expireDate->renderViewHelper();
        echo $socialcodeForm->shopId->renderViewHelper();
        echo $this->formSubmit(
            'sharecode',
            FrontEnd_Helper_viewHelper::__form('form_share vouchercode'),
            array('class'=>'btn btn-primary', 'id'=>'sharecode')
        );
        $sharecodeLink = HTTP_PATH_LOCALE
            . FrontEnd_Helper_viewHelper::__link('link_sharesocialcode');
        ?>
        <a
        href="<?php echo $sharecodeLink; ?>">
        <?php echo $this->translate('Share coupon codes for other shops');?>
        </a>
    </form>
</div>