<?php
echo $this->minifyHeadScript()->appendFile(HTTP_PATH. "public/js/front_end/add-social-code.js");
$socialCodeForm = $this->zendForm;
foreach ($socialCodeForm->getElements() as $formElement) {
    $formElement->getDecorator('label')->setOption('tag', null);
}
?>
<div class="widget">
    <form id="socialCodeForm" class="widget-form" name="socialCodeForm" method="POST" action="">
        <h3><?php echo $this->translate('Social Code');?></h3>
        <p><?php echo $this->translate('Share a code with our users');?></p>
        <?php 
        echo $socialCodeForm->shops->renderViewHelper();
        echo $socialCodeForm->code->renderViewHelper();
        echo $socialCodeForm->offerDetails->renderViewHelper();
        echo $socialCodeForm->expireDate->renderViewHelper();
        echo $socialCodeForm->shopPermalink->renderViewHelper();
        echo $this->formSubmit(
            'shareCode',
            FrontEnd_Helper_viewHelper::__form('form_share vouchercode'),
            array('class'=>'btn btn-primary', 'id'=>'shareCode')
        );
        $shareCodeLink = HTTP_PATH_LOCALE
            . FrontEnd_Helper_viewHelper::__link('link_sharesocialcode');
        ?>
        <a href="<?php echo $shareCodeLink; ?>">
        <?php echo $this->translate('Share coupon codes for other shops');?>
        </a>
    </form>
</div>