<?php
$socialcodeForm = $this->zendForm;
foreach ($socialcodeForm->getElements() as $formElement) {
    $formElement->getDecorator('label')->setOption('tag', null);
}
?>
<div class="widget">
    <form id="socialcodeForm" class="widget-form" name="socialcodeForm" method="POST" action="">
        <h3><?php echo $this->translate('Share Codes');?></h3>
        <p><?php echo $this->translate('Share a code with our users');?></p>
        <?php echo $socialcodeForm->nickname->renderViewHelper();?>
        <?php echo $socialcodeForm->title->renderViewHelper();?>
        <?php echo $socialcodeForm->offerUrl->renderViewHelper();?>
        <div class="input-block">
            <?php echo $socialcodeForm->code->renderViewHelper();?>
            <?php echo $socialcodeForm->expireDate->renderViewHelper();?>
        </div>
        <?php echo $socialcodeForm->offerDetails->renderViewHelper();?>

        <?php echo $socialcodeForm->shopId->renderViewHelper();
        echo $this->formSubmit(
         'sharecode',
         FrontEnd_Helper_viewHelper::__form('form_share vouchercode'),
         array('class'=>'btn btn-primary', 'id'=>'sharecode')
        ) ?>
        <a  
        href="<?php echo HTTP_PATH_LOCALE; ?>/<?php echo FrontEnd_Helper_viewHelper::__link('link_all-shops'); ?>">
        <?php echo $this->translate('Share coupon codes for other shops');?></a>
    </form>
</div>