<?php
$this->minifyHeadScript()->prependFile("public/js/front_end/jquery.expander.min.js");
$this->minifyHeadScript()->prependFile("public/js/front_end/storeDetail.js");
$this->minifyHeadScript()->prependFile("public/js/front_end/signupnewsletter.js");
$this->minifyHeadScript()->prependFile("public/js/front_end/modalPopLite.min.js");
$this->minifyHeadScript()->prependFile("public/js/front_end/socialmedia.js");

$storeViewPartialPath = 'store/';
$offers = '';
if(count($this->offers) > 0):
    $offers = $this->partial(
        $storeViewPartialPath. '_offer.phtml',
        array(
            'offers' => $this->offers,
            'offersType'=>'simple',
            'shopName' => $this->currentStoreInformation[0]['name'],
            'shop' => $this->currentStoreInformation[0],
            'zendForm'=>$this->form
        )
    );
endif;

$offerPartialClass = new FrontEnd_Helper_OffersPartialFunctions();
$similarOffersHeader = '';
$similarOffers = '';
if(count($this->similarShopsAndSimilarCategoriesOffers) > 0):
    $similarOffersHeader = $offerPartialClass->getSimilarShopHeader($this->currentStoreInformation[0]['name'], 'similar');
    $similarOffers = $this->partial(
        $storeViewPartialPath.'_offer.phtml',
        array(
            'offers' => $this->similarShopsAndSimilarCategoriesOffers,
            'offersType' => 'similar',
            'shopName' => $this->currentStoreInformation[0]['name'],
            'shop' => $this->currentStoreInformation[0]
        )
    );
endif;

$noMoneyNocodeMessage = '';
if ($this->currentStoreInformation[0]['affliateProgram']!='1' && $offers=='') :
    $noMoneyNocodeMessage = $this->partial($storeViewPartialPath.'_noCodeNoMoneyMessage.phtml');
    $similarOffersHeader = '';
endif;

$similarShopsAndSimilarCategoriesShops ='';
if(!empty($this->similarShops)):
    $similarShopsAndSimilarCategoriesShops = $this->partial(
        $storeViewPartialPath.'_similar-and-category-related-shops.phtml',
        array('similarShopsAndSimilarCategoryShops' => $this->similarShops)
    );
endif;

$discussion = '';
$partialViewPath = 'partials/';
if($this->currentStoreInformation[0]['discussions'] == 1):
    $discussion = $this->partial(
        $partialViewPath.'_discussion.phtml',
        array('shopName' => $this->currentStoreInformation[0]['name'])
    );
endif;

$moneySavingGuide = '';
if(count($this->moneySavingGuideArticle) >0):
    $moneySavingGuide = $this->partialLoop($storeViewPartialPath.'_moneySavingGuideArticle.phtml', $this->moneySavingGuideArticle);
endif;

$expiredOffers ='';
if(count($this->expiredOffers) >0):
      $expiredOffers = $this->partial(
          $storeViewPartialPath.'_expiredOffer.phtml',
          array('expiredOffers'=>$this->expiredOffers,'shopName'=>$this->currentStoreInformation[0]['name'])
      );
endif;

if($this->profileImage['addtosearch'] == 1):
    if($this->profileImage['google']):
        $google = $this->profileImage['google'];
        echo $this->headLink(array( 'rel' => 'author','href' => $google));
    endif;
endif;

$getPermaLinkNewOffer = Page::getPageFromPageAttribute(6);
$howToUseGuidePermalink= "how-to/".$this->currentStoreInformation[0]['permaLink'];
$this->locale = LOCALE != 'en' ? LOCALE . '/' : '';
$offersCount = count($this->offers);

$actualUrlWithoutDoubleSlash = explode("//", $this->currentStoreInformation[0]['actualUrl']);
if (isset($actualUrlWithoutDoubleSlash[1])):
    $actualUrl = $actualUrlWithoutDoubleSlash[1];
else:
    $actualUrl = $this->currentStoreInformation[0]['actualUrl'];
endif;

$headerBlock = FrontEnd_Helper_viewHelper::getLoveRelatedVariables($this->currentStoreInformation[0], $message = 'storeDetail', $offerTitle = 'storeDetail');
$shopEditor = '';
if($this->shopEditor != null):
    $shopEditor = $this->partial(
        $storeViewPartialPath.'_storeEditor.phtml',
        array(
           'shopEditor' => $this->shopEditor,
           'shop' => $this->currentStoreInformation[0],
            'howToUsePermalink'=>$howToUseGuidePermalink,
            'actualUrl'=>$actualUrl
        )
    );
endif;
?>
<input type="hidden" name="currentShop" id="currentShop" value= "<?php echo base64_encode($this->currentStoreInformation[0]['id']);?>"/>
<?php echo $headerBlock; ?> 
<div class="row">
    <div id="content" class="col-md-8 col-sm-8">
    <?php 
    echo $noMoneyNocodeMessage;
    echo $offers;
    echo $similarOffersHeader;
    echo $similarOffers;
    echo $similarShopsAndSimilarCategoriesShops;
    echo $discussion;
    echo $moneySavingGuide;
    echo $expiredOffers;
    ?>
    </div>
    <aside id="sidebar" class="col-md-4 col-sm-4">
    <?php
    echo $shopEditor;
    echo FrontEnd_Helper_viewHelper::socialMediaWidget($this->currentStoreInformation[0]['affliateProgram'] =='' ? $this->currentStoreInformation[0]['actualUrl'] : $this->currentStoreInformation[0]['affliateProgram']);
if (count($this->latestShopUpdates) > 0):?>
    <?php echo $this->partial($storeViewPartialPath.'_latestNews.phtml', array('latestShopUpdates' => $this->latestShopUpdates));
endif;
?>

<?php
if ($this->shopChain):
    ?>
        <article class="block">
    <?php echo $this->shopChain; ?>
        </article>
    <?php
endif;
        
if(isset($this->popularStoresList)):
    ?>
        <div class="block">
            <?php echo $this->popularStoresList; ?>
        </div>
    <?php
endif;
        
if ($this->currentStoreInformation[0]['showSignupOption']) :
    echo $this->esi($this->locale.$storeViewPartialPath.'signupwidget');
endif;
?>
    </aside>
</div>
