<?php
####### REFATORED CODE #####
$similarShopsAndSimilarCategoriesShops ='';
if(!empty($this->similarShops)):
    $similarShopsAndSimilarCategoriesShops = $this->partial(
        'store/_similar-and-category-related-shops.phtml',
        array('similarShopsAndSimilarCategoryShops' => $this->similarShops)
    );
endif;

$discussion = '';

$partialViewPath = 'partials/';
if($this->currentStoreInformation[0]['discussions'] == 1):
    $discussion = $this->partial(
        $partialViewPath.'_discussion.phtml',
        array('shopName' => $this->currentStoreInformation[0]['name'])
    );
endif;

if($this->profileImage['addtosearch'] == 1):
    if($this->profileImage['google']):
        $google = $this->profileImage['google'];
        echo $this->headLink(array( 'rel' => 'author','href' => $google));
    endif;
endif;

$getPermaLinkNewOffer = Page::getPageFromPageAttr(6);
$bounceRate = "/out/shop/".@$this->currentStoreInformation[0]['id'];
$shopUrl = HTTP_PATH_LOCALE.'out/shop/'.@$this->currentStoreInformation[0]['id'];
$Link = '';
$howToUseGuidePermalink= "how-to/".$this->currentStoreInformation[0]['permaLink'];
$name =  strtoupper($this->currentStoreInformation[0]['name']);
$breadcrumb = "<a href='".HTTP_PATH_LOCALE."store/index/' style='color:#6a6a6a'>".$this->translate($name)."</a>";
$id = 0;

if(Auth_VisitorAdapter::hasIdentity()):
    $id = Auth_VisitorAdapter::getIdentity()->id;
endif;

$this->minifyHeadScript()->prependFile("public/js/front_end/jquery.expander.min.js" );
$this->minifyHeadScript()->prependFile("public/js/front_end/storeDetail.js");
$this->minifyHeadScript()->prependFile("public/js/front_end/socialmedia.js");

$offers = '';
$this->locale = LOCALE != 'en' ? LOCALE . '/' : '';
$offersCount = count($this->offers);

if(count($this->offers) > 0):
    $offers = $this->partial(
        'store/_offer.phtml',
        array(
            'offers' => $this->offers,
            'offersType'=>'simple',
            'shopName' => $this->currentStoreInformation[0]['name'],
            'shop' => $this->currentStoreInformation[0],
            'zendForm'=>$this->form
        )
    );
endif;

$similarOffers = '';
if(count($this->similarShopsAndSimilarCategoriesOffers) > 0):
    $similarOffers = $this->partial(
        'store/_offer.phtml',
        array(
            'offers' => $this->similarShopsAndSimilarCategoriesOffers,
            'offersType' => 'similar',
            'shopName' => $this->currentStoreInformation[0]['name'],
            'shop' => $this->currentStoreInformation[0]
        )
    );
endif;

?>
<input type="hidden" name="currentShop" id="currentShop" value= "<?php echo base64_encode($this->currentStoreInformation[0]['id']);?>"/>
<div class="header-block header-block-2">
    <div id="messageDiv" class="yellow-box-error-box-code" style="margin-top : 20px; display:none;"><strong></strong></div>
    <div class="icon">
<?php
$affliateProgramUrl = @$this->currentStoreInformation[0]['affliateProgram']['name']=='' ? $this->currentStoreInformation[0]['actualUrl'] : @$this->currentStoreInformation[0]['affliateProgram']['name'];
if ($this->currentStoreInformation[0]['affliateProgram']) :
    $affliateBounceRate = "ga('send', 'event', 'aff','$bounceRate');";
    $affliateUrl = $shopUrl;
    $affliateDisabled = '';
    $affliateClass = '';
else:
    $affliateBounceRate = '';
    $affliateUrl = '#';
    $affliateDisabled = 'disabled="disabled"';
    $affliateClass = 'btn-disabled';
endif;
?>
        <a target="_blank" rel="nofollow" class="text-blue-link store-header-link <?php echo $affliateClass; ?>" <?php echo $affliateDisabled; ?> onclick="<?php echo $affliateBounceRate; ?>" href="<?php echo $affliateUrl; ?>"><?php echo'<img class="radiusImg" src="'. $this->storeImage . '" alt="' . $this->currentStoreInformation[0]['name']  . '"  width="176" height="89" />'; ?></a>
    </div>
    <div class="box">
        <h1><?php echo $this->currentStoreInformation[0]['title'];?></h1>
        <strong><?php echo '' . $this->currentStoreInformation[0]['subTitle'];?></strong>
            <a target="_blank" rel="nofollow" class="btn text-blue-link fl store-header-link <?php echo $affliateClass; ?> pop btn btn-sm btn-default" <?php echo $affliateDisabled; ?> onclick="<?php echo $affliateBounceRate; ?>" href="<?php echo $affliateUrl; ?>">
<?php
$actualUrlWithoutDoubleSlash = explode("//", $this->currentStoreInformation[0]['actualUrl']);
if (isset($actualUrlWithoutDoubleSlash[1])):
     $actualUrl = $actualUrlWithoutDoubleSlash[1];
else:
     $actualUrl = $this->currentStoreInformation[0]['actualUrl'];
endif;
echo $actualUrl;
?>
            </a>
<?php
echo $this->esi($this->locale.'store/addfavoriteview?shopId='.$this->currentStoreInformation[0]['id'].'&shopName='.urlencode($this->currentStoreInformation[0]['name']));
?>        
    </div>
</div> 
<div class="row">
    <div id="content" class="col-md-8 col-sm-8">
    <?php echo $offers; ?>
    <?php echo $similarOffers; ?>
<?php
echo $similarShopsAndSimilarCategoriesShops;
echo $discussion;
      
if(count($this->moneySavingGuideArticle) >0):
    echo $this->partialLoop('store/_moneySavingGuideArticle.phtml', $this->moneySavingGuideArticle);
endif;

if(count($this->expiredOffers) >0):
    ?>
        
        <header class="heading-box text-expired">
            <h2><?php echo  $this->translate('Expired').' '.$this->currentStoreInformation[0]['name'].' '.$this->translate("vouchers and discounts"); ?></h2>
            <strong><?php echo  $this->translate('Unfortunately ... These discount codes from').' '.$this->currentStoreInformation[0]['name'].' '.$this->translate("you’ve missed");?>.</strong>
        </header>
        <section class="section-module">
            <?php  echo $this->partialLoop('store/_expiredOffer.phtml', $this->expiredOffers); ?>
        </section>

    <?php
endif;
?>
    </div>
    <aside id="sidebar" class="col-md-4 col-sm-4">
        <article class="block">
            <div class="intro intro-2">

<?php
if($this->shopEditor != null):
    ?>

                <div class="deal">
                    <div class="deal-holder">
    <?php
    $EditorFirstName = str_replace(' ', '', $this->shopEditor['firstName']);
    $EditorLastName = str_replace(' ', '', $this->shopEditor['lastName']);
    $EditorImageSlug = $this->shopEditor['slug'];
    ?>
                        <span class="text">
    <?php
    echo $this->translate('All').' '.$this->currentStoreInformation[0]['name'].' '.$this->translate('deals verified by');
    ?>
                            <span class="name"><?php echo $EditorFirstName; ?></span>
                        </span>
                        <div class="photo">
                            <span class="text-box"><?php echo $this->translate('Hello'); ?></span>
    <?php
    $shopEditorPath = HTTP_PATH_CDN . ltrim($this->shopEditor['profileimage']['path'], "/"). 'thum_large_widget_' .$this->shopEditor['profileimage']['name'];
    echo '<img alt="' .  $this->shopEditor['firstName'] . '" class="" src="'.  $shopEditorPath . '" width="120" height="120"/>';
    ?>
                      </div>
                    </div>
                </div>

    <?php
endif;
?>
                <h1><?php echo $this->translate('About').' '.$this->currentStoreInformation[0]['name'].' '.$this->translate('Vouchers').' '.date('Y'); ?></h1>
<?php
echo $this->currentStoreInformation[0]['shopText'];
?>
            </div>

<?php
if($this->currentStoreInformation[0]['howToUse']):
    ?>

            <ul class="add-info">
                <li>
                    <h2><?php echo $this->translate('How to use code');?></h2>
                    <p>
                        <a href="javascript:void(0);" id="clicker"><?php echo $this->translate('Show me'); ?></a> 
                        <?php echo $this->translate('where to enter my').' '.$this->currentStoreInformation[0]['name'].' '.$this->translate('code, or read our full'); ?> 
                        <a href="<?php echo HTTP_PATH_LOCALE.$howToUseGuidePermalink; ?>"><?php echo $this->currentStoreInformation[0]['name'].' '.$this->translate('Promotional Code'); ?></a>
                        <?php echo $this->translate('help guide'); ?>.
                    </p>
                </li>
                <li class="web">
                    <h2><?php echo $this->translate('Official website'); ?></h2>
                    <a href="<?php echo $this->currentStoreInformation[0]['actualUrl']; ?>"><?php echo $actualUrl; ?></a>
                </li>
            </ul>

    <?php
endif;
?>

        </article>
        <article class="block">

<?php
$controllerName =  $this->controllerName;
$socialMediaTitle = "<h2>".$this->translate('Share')."</h2>
                    <span>".$this->translate('And receive cool discounts and useful actions through google+, twitter and Facebook')."</span>";
echo FrontEnd_Helper_viewHelper::socialmediaSmall($affliateProgramUrl, $socialMediaTitle, $controllerName);
?>
        
        </article>

<?php
if (count($this->latestShopUpdates) > 0):?>

        <section class="block">
            <h2><?php echo $this->translate('Latest news about').' '.$this->currentStoreInformation[0]['name'];?></h2>
   <?php echo $this->partialLoop('store/_latestNews.phtml', $this->latestShopUpdates); ?>
        </section>

   <?php
endif;
?>

<?php
if ($this->shopChain):
    ?>

        <article class="block">
    <?php echo $this->shopChain; ?>
        </article>

    <?php
endif;
        
if(isset($this->popularStoresList)):
    ?>
        <div class="block">
            <?php echo $this->popularStoresList; ?>
        </div>
    <?php
endif;
        
if ($this->currentStoreInformation[0]['showSignupOption']) :
    ?>

            <div class="block white">
     <?php echo $this->esi($this->locale.'store/signupwidget'); ?>
            </div>

    <?php
endif;
?>
    </aside>
</div>
</div>