<?php
####### REFATORED CODE #####
$similarShopsAndSimilarCategoriesShops ='';
if(!empty($this->similarShops)):
    $similarShopsAndSimilarCategoriesShops = $this->partial(
        'store/_similar-and-category-related-shops.phtml',
        array('similarShopsAndSimilarCategoryShops' => $this->similarShops)
    );
endif;

	echo $this->doctype('XHTML1_RDFA');
	if($this->profileImage['addtosearch'] == 1):
		if($this->profileImage['google']):
			$google = $this->profileImage['google'];
			echo $this->headLink( array( 'rel' => 'author','href' => $google));
		endif;
	endif;

	$this->minifyHeadLink()->prependStylesheet("public/css/front_end/modalPopLite.css");
	$this->minifyHeadScript()->prependFile ("public/js/front_end/modalPopLite.min.js" );
	$this->minifyHeadScript()->prependFile ("public/js/front_end/jquery.expander.min.js" );
	$this->minifyHeadScript()->prependFile ("public/js/front_end/socialmedia.js" );
	$this->minifyHeadScript()->prependFile ("public/js/front_end/storeDetal.js" );
	$this->minifyHeadScript()->appendFile("public/js/back_end/bootbox.min.js");

	?>
<!-- Search Outer2 Starts -->
  <?php $getPermLinkNewOffer = Page::getPageFromPageAttr(6);
    $bounceRate = "/out/shop/".@$this->data[0]['id'];
    $shopUrl = HTTP_PATH_LOCALE.'out/shop/'.@$this->data[0]['id'];
    $Link = '';
    $howToUseGuidePermalink= "how-to/".$this->data[0]['permaLink'];
    $name =  strtoupper($this->data[0]['name']);
    $breadcrumb = "<a href='".HTTP_PATH_LOCALE."store/index/' style='color:#6a6a6a'>".$this->translate($name)."</a>";
    $id = 0;
    if(Auth_VisitorAdapter::hasIdentity()):
        $id = Auth_VisitorAdapter::getIdentity()->id;
    endif;

    $yellowBoxWarning  =
    '<div class="yellow-box2 mt20 clr">
    <div class="yellow-box2-img">
    <img src="' .HTTP_PATH  . "public/images/front_end/icon19.png" . '" width="32" height="32" alt="" /></div>
    <div class="yellow-box2-text text-black">'
    . $this->translate("Sorry") . " ". $this->data[0]['name']
    . " ".  $this->translate('offers right now!') . '<br />
    <p>' .  $this->translate("Check out the") ." "
    . '<a target="_blank" rel="nofollow" class="text-blue-link"'
    . ' onclick=\'ga("send","event", "aff","' . $bounceRate . '");\' href=" ' .$shopUrl. '">'
    . $this->data[0]["name"] . '</a>' .
    " " . $this->translate("website to see what direct offers are available. Our deal team are working hard to bring you more great discounts soon.") ." " . '</p><p>' .
    " " .$this->translate("However, you might also like these vouchercodes we have selected for you! Dont forget to have a look at or") . " "
    . '<a class="text-blue-link" href="' . HTTP_PATH_LOCALE . "categorieen" . '">' .
    " " .$this->translate("Categories") ." " . '</a>' . $this->translate('or')
    .'<a class="text-blue-link"  href="' .  HTTP_PATH_LOCALE . "alle-winkels" . '">'
    . " " . $this->translate("Stores overview") . '</a>'
    . '</p></div></div>';


    $offers = '';


    $this->locale = LOCALE != 'en' ? LOCALE . '/' : '';
    $offerCount = count($this->offers) ;
    if( $offerCount > 0):
        $k = 0;
        foreach ($this->offers as $offer):
            $this->offers[$k]['codeUploadShowOrNot'] = $this->data[0]['usergenratedcontent'];
            $this->offers[$k]['offerCount'] = $offerCount;
            $this->offers[$k]['locale'] = $this->locale;
            $k++;
        endforeach;

        $offers = $this->partialLoop('store/offer.phtml', $this->offers);
    endif;

    if(count($this->relatedshops) > 0):
        $relatedOffer = $this->partialLoop('store/relatedOffer.phtml', $this->relatedshops);
    endif;

    $headingOfSimilerOffer = '<div class="clr"><h2>'
    .$this->translate('Similar vouchercodes we think you will like!'). '</h2></div>';
    $headingOfSimilerOfferMt20 = '<div class="popular-kortings-heading text-white clr mt20"><span>'
    .  $this->translate('Similar vouchercodes we think you will like!'). '</span></div>';

    $discussion = '';
    if($this->data[0]['discussions'] == 1):
        $discussion ='<div class="voucher-col1-new">';
        $discussion .=$this->render('partials/discussion.phtml');
        $discussion .='</div>';
    endif;
    $speratorDiv = '<div class="separator"></div>';
# end common code
?>

<!-- Search Outer2 Ends -->
<!-- Separator Starts -->

<!-- Separator Ends -->
     <!-- Mark Spencer Top Starts -->
<div class="clr"></div>
<!--Refactored code-->
<div class="header-block header-block-2">
    <div id="messageDiv" class="yellow-box-error-box-code" style="margin-top : 20px; display:none;"><strong></strong></div>
    <div class="icon">
<?php
$affliateProgramUrl = @$this->data[0]['affliateProgram']['name']=='' ? $this->data[0]['actualUrl'] : @$this->data[0]['affliateProgram']['name'];
// create click out only on when a shop is money shop
if ($this->data[0]['affliateProgram']) :
    $affliateBounceRate = "ga('send', 'event', 'aff','$bounceRate');";
    $affliateUrl = $shopUrl;
    $affliateDisabled = '';
    $affliateClass = '';
else:
    $affliateBounceRate = '';
    $affliateUrl = '#';
    $affliateDisabled = 'disabled="disabled"';
    $affliateClass = 'btn-disabled';
endif;
?>
        <a target="_blank" rel="nofollow" class="text-blue-link store-header-link <?php echo $affliateClass; ?>" <?php echo $affliateDisabled; ?> onclick="<?php echo $affliateBounceRate; ?>" href="<?php echo $affliateUrl; ?>"><?php echo'<img class="radiusImg" src="'. $this->img . '" alt="' . $this->data[0]['name']  . '"  width="176" height="89" />'; ?></a>
    
    </div>
    <div class="box">
        <h1><?php echo $this->data[0]['title'];?></h1>
        <strong><?php echo '' . $this->data[0]['subTitle'];?></strong>
            <a target="_blank" rel="nofollow" class="btn text-blue-link fl store-header-link <?php echo $affliateClass; ?> pop btn btn-sm btn-default" <?php echo $affliateDisabled; ?> onclick="<?php echo $affliateBounceRate; ?>" href="<?php echo $affliateUrl; ?>">
<?php
$actualUrlWithoutDoubleSlash = explode("//", $this->data[0]['actualUrl']);
if (isset($actualUrlWithoutDoubleSlash[1])):
     $actualUrl = $actualUrlWithoutDoubleSlash[1];
else:
     $actualUrl = $this->data[0]['actualUrl'];
endif;
echo $actualUrl;
?>
            </a>
<?php
echo $this->esi($this->locale.'store/addfavoriteview?shopId='.$this->data[0]['id'].'&shopName='.urlencode($this->data[0]['name']));
?>
             
    </div>
</div> 
<!--Refactored code-->
<div class="separator">&nbsp;</div>

<div class="new-outer row">
<div id="content" class="col-md-8 col-sm-8">
<div class="mark-spencer-mid" >
<!-- Mark Spencer Mid Left Starts -->
<?php

	if($this->data[0]['usergenratedcontent']==1):

		# CHECK CONDITION
		if($this->data[0]['affliateProgram']==0):
			# NO MONEY NO CODE
			if(count($this->offers) <=0): ?>

				<?php
						# show top popular code when no money code is available
						if(! $this->topPopularOffers)
						{
							echo $yellowBoxWarning;
						} else 	{
							$offers =  $this->partialLoop('store/_popular-offers.phtml', $this->topPopularOffers);
						}

			            echo $speratorDiv; ?>
				<div class="mark-spencer-mid-left" style='width:660px!important;'>
				<?php echo $offers;
				if ($this->data[0]['showSignupOption']) :
					echo $this->esi($this->locale.'store/signup');
				endif;
				
				# show promotional similar codes
				if(count($this->relatedshops8) >0): ?>
					<div class="similar-promotionl-offer-cont">
						<h2><span><?php echo $this->translate("Compairable codes in store");?></span></h2>
					<?php	
						echo $this->partialLoop('store/_similar-promotional-codes.phtml', $this->relatedshops8); ?>	
					</div>
				<?php endif;
				
				
				echo $this->esi($this->locale.'store/discountcodewidget');
				echo $discussion;
				?>
				</div>
		<?php

		# NO MONEY WITH CODE
		elseif(count($this->offers) > 0): 
			 echo $speratorDiv; ?>

			<!-- code for  one code -->
			<div class="mark-spencer-mid-left" style='width:660px!important;'>
		    	<?php echo $offers;
		    	if ($this->data[0]['showSignupOption']) :
		    		echo $this->esi($this->locale.'store/signup');
		    	endif;
		    	# show promotional similar codes
		    	if(count($this->relatedshops8) >0): ?>
		    		<div class="similar-promotionl-offer-cont">
		    			<h2><span><?php echo $this->translate("Compairable codes in store");?></span></h2>
		    			<?php	
		    				echo $this->partialLoop('store/_similar-promotional-codes.phtml', $this->relatedshops8); ?>	
		    		</div>
				<?php endif;
		    					
		    	
		    	echo $discussion;   ?>
		 	</div>
		    <!-- Mark Spencer Mid Left Ends -->
	<!--end code for  one code -->

	<?php endif;
	else:

		# YES MONEY NO CODE
		 if(count($this->offers) <=0): ?>

		 	<?php echo $yellowBoxWarning;
			if(count($this->relatedshops) >0):?>
				<div class="merchants-outer">
					<?php echo $headingOfSimilerOfferMt20;?>
					<div class="merchants-bot"><?php echo $relatedOffer ?></div>
				</div>
			<?php  endif;
			echo $speratorDiv; ?>

			<div class="mark-spencer-mid-left" style='width:660px!important;'>
				<?php echo $offers;
					if ($this->data[0]['showSignupOption']) :
					echo $this->esi($this->locale.'store/signup');
				endif;
				# show promotional similar codes
		    	if(count($this->relatedshops8) >0): ?>
		    		<div class="similar-promotionl-offer-cont">
		    			<h2><span><?php echo $this->translate("Compairable codes in store");?></span></h2>
		    			<?php	
    					echo $this->partialLoop('store/_similar-promotional-codes.phtml', $this->relatedshops8); ?>	
	    		</div>
				<?php endif;
				
			
				echo $this->esi($this->locale.'store/discountcodewidget');
				echo $discussion; ?>
			</div>
			<!-- Mark Spencer Mid Left Ends -->
	<?php

	# YES MONEY WITH CODE
	elseif(count($this->offers) >0):  ?>

			<!-- code for  one code -->
			<div class="mark-spencer-mid-left" style='width:660px!important;'>
			<?php echo $offers;
				if ($this->data[0]['showSignupOption']) :
					echo $this->esi($this->locale.'store/signup');
				endif;	
			# show promotional similar codes
			if(count($this->relatedshops8) >0): ?>
				<div class="similar-promotionl-offer-cont">
					<h2><span><?php echo $this->translate("Compairable codes in store");?></span></h2>
				<?php	
					echo $this->partialLoop('store/_similar-promotional-codes.phtml', $this->relatedshops8); ?>	
				</div>
			<?php endif; 
			  
			
				echo $discussion;?>
			</div>
			<?php endif;
	endif;

	# not user generated code
	else:

		# CHECK MOENY CONDITION
		if($this->data[0]['affliateProgram']==0):
			# NO MONEY AND NO CODE
			if(count($this->offers) <=0):?>
				<?php
					# show top popular code when no money code is available
					if(! $this->topPopularOffers)
					{
						echo $yellowBoxWarning;
					} else 	{
						$offers =  $this->partialLoop('store/_popular-offers.phtml', $this->topPopularOffers);

					}
			echo $speratorDiv; ?>


			<div class="mark-spencer-mid-left" style='width:660px!important;'>
 		      	<?php echo $offers;
 		      		if ($this->data[0]['showSignupOption']) :
 		      		echo $this->esi($this->locale.'store/signup');
 		      	endif;
 		      	# show promotional similar codes
				if(count($this->relatedshops8) >0): ?>
 		      		<div class="similar-promotionl-offer-cont">
 		      			<h2><span><?php echo $this->translate("Compairable codes in store");?></span></h2>
 		      			<?php	
 		      				echo $this->partialLoop('store/_similar-promotional-codes.phtml', $this->relatedshops8); ?>	
 		      		</div>
 		      	<?php endif; 
 		      

 		      	echo $discussion; ?>
 		 	</div>
	<?php
		# NO MONEY AND WITH CODE
		elseif(count($this->offers) >0): ?>

			<?php /*if(count($this->relatedshops) >0):?>
				<div class="merchants-outer">
					<?php echo $headingOfSimilerOffer;?>
					<div class="merchants-bot"><?php echo $relatedOffer ?></div>
				</div>
			<?php  endif;  */
			echo $speratorDiv; ?>

			<div class="mark-spencer-mid-left" style='width:660px!important;'>
 		      	<?php echo $offers;
 		      		if ($this->data[0]['showSignupOption']) :
 		      		echo $this->esi($this->locale.'store/signup');
 		      	endif;
 		      	# show promotional similar codes
				if(count($this->relatedshops8) >0): ?>
 		      		<div class="similar-promotionl-offer-cont">
 		      			<h2><span><?php echo $this->translate("Compairable codes in store");?></span></h2>
 		      			<?php	
 		      				echo $this->partialLoop('store/_similar-promotional-codes.phtml', $this->relatedshops8); ?>	
 		      		</div>
 		      	<?php endif; 
 		      	 		      	
 		      

 		      	echo $discussion; ?>
 		 	</div>
 		      <!-- Mark Spencer Mid Left Ends -->
 		     <!-- end code for no money MORE THAN 0 code -->
		<?php endif;
		else:

			# YES MONEY AND NO CODE
			 if(count($this->offers) <=0): ?>

			 	<?php if(count($this->relatedshops) >0):?>
			 	<div class="merchants-outer">
					<?php echo $headingOfSimilerOffer;?>
					<div class="merchants-bot"><?php echo $relatedOffer ?></div>
				</div>
				<?php endif;?>

				<div class="mark-spencer-mid-left" style="width:660px!important;">
					<?php
					echo $yellowBoxWarning;
						if ($this->data[0]['showSignupOption']) :
						echo $this->esi($this->locale.'store/signup');
					endif;
					# show promotional similar codes
					if(count($this->relatedshops8) >0): ?>
						<div class="similar-promotionl-offer-cont">
							<h2><span><?php echo $this->translate("Compairable codes in store");?></span></h2>
						<?php	
							echo $this->partialLoop('store/_similar-promotional-codes.phtml', $this->relatedshops8); ?>	
						</div>
					<?php endif; 				
				

					echo $discussion; ?>

            <!-- display similar shops and shop under same category widget -->
                <?php echo $similarShopsAndSimilarCategoriesShops; ?>

				</div>
		 </div>
		<!-- Mark Spencer Mid Right Starts -->
		<?php

		# YES MONEY AND WITH CODE
		elseif(count($this->offers) > 0): ?>
			<div class="mark-spencer-mid-left" style='width:660px!important;'>
				<?php echo $offers;
				if ($this->data[0]['showSignupOption']) :
					echo $this->esi($this->locale.'store/signup');
				endif;
				# show promotional similar codes
				if(count($this->relatedshops8) >0): ?>
					<div class="similar-promotionl-offer-cont">
						<h2><span><?php echo $this->translate("Compairable codes in store");?></span></h2>
					<?php	
						echo $this->partialLoop('store/_similar-promotional-codes.phtml', $this->relatedshops8); ?>	
					</div>
				<?php endif;  	  
				    	
				

				echo $discussion;?>

            <!-- display similar shops and shop under same category widget -->
            <?php echo $similarShopsAndSimilarCategoriesShops; ?>
 		 	</div>
	       <?php endif;
		endif;
	endif;
	?>

</div>
<!-- Common side bar -->
<!--Refactored code-->
                <aside id="sidebar" class="col-md-4 col-sm-4">
                    <article class="block">
                        <div class="intro intro-2">

                            <?php if($this->shopEditor != null): ?>

                            <div class="deal">
                                <div class="deal-holder">
                                    <?php
                                    $EditorFirstName = str_replace(' ', '', $this->shopEditor['firstName']);
                                    $EditorLastName = str_replace(' ', '', $this->shopEditor['lastName']);
                                    $EditorImageSlug = $this->shopEditor['slug'];
                                    ?>
                                    <span class="text">
                                        <?php echo $this->translate('All').' '.$this->data[0]['name'].' '.$this->translate('deals verified by'); ?>
                                        <span class="name"><?php echo $EditorFirstName; ?></span>
                                    </span>
                                    <div class="photo">
                                        <span class="text-box"><?php echo $this->translate('Hello'); ?></span>
                                        <?php
                                        $shopEditorPath = HTTP_PATH_CDN . ltrim($this->shopEditor['profileimage']['path'], "/"). 'thum_large_widget_' .$this->shopEditor['profileimage']['name'];
                                        echo '<img alt="' .  $this->shopEditor['firstName'] . '" class="" src="'.  $shopEditorPath . '" width="120" height="120"/>';
                                        ?>
                                  </div>
                                </div>
                            </div>

                            <?php endif;
                            ?>

                            <h1><?php echo $this->translate('About').' '.$this->data[0]['name'].' '.$this->translate('Vouchers').' '.date('Y'); ?></h1>
                            <?php echo $this->data[0]['shopText']; ?>
                        </div>

                        <?php if($this->data[0]['howToUse']): ?>

                        <ul class="add-info">
                            <li>
                                <h2><?php echo $this->translate('How to use code');?></h2>
                                <p>
                                    <a href="javascript:void(0);" id="clicker"><?php echo $this->translate('Show me'); ?></a> 
                                    <?php echo $this->translate('where to enter my').' '.$this->data[0]['name'].' '.$this->translate('code, or read our full'); ?> 
                                    <a href="<?php echo HTTP_PATH_LOCALE.$howToUseGuidePermalink; ?>"><?php echo $this->data[0]['name'].' '.$this->translate('Promotional Code'); ?></a>
                                    <?php echo $this->translate('help guide'); ?>.
                                </p>
                            </li>
                            <li class="web">
                                <h2><?php echo $this->translate('Official website'); ?></h2>
                                <a href="<?php echo $this->data[0]['actualUrl']; ?>"><?php echo $actualUrl; ?></a>
                            </li>
                        </ul>

                        <?php endif;
                        ?>

                    </article>
                    <article class="block">

                    <?php
                        $controllerName =  $this->controllerName;
                        $socialMediaTitle = "<h2>".$this->translate('Share')."</h2>
                                <span>".$this->translate('And receive cool discounts and useful actions through google+, twitter and Facebook')."</span>";
                        echo FrontEnd_Helper_viewHelper::socialmediaSmall($affliateProgramUrl, $socialMediaTitle, $controllerName);
                    ?>
                    
                    </article>

                    <?php if (count($this->latestShopUpdates) > 0):?>

                    <section class="block">
                        <h2><?php echo $this->translate('Latest news about').' '.$this->data[0]['name'];?></h2>
                        <?php echo $this->partialLoop('store/latestNews.phtml', $this->latestShopUpdates); ?>
                    </section>

                    <?php endif;
                    ?>

                    <?php if ($this->chain):  ?>

                    <article class="block">
                    <?php echo $this->chain; ?>
                    </article>

                    <?php endif;
                    
                    if(isset($this->popularStoresList)): ?> 
                    <div class="block">
                        <?php echo $this->popularStoresList; ?>
                    </div>
                    <?php endif;
                    
                    if ($this->data[0]['showSignupOption']) : ?>

                        <div class="block white">
                        <?php echo $this->esi($this->locale.'store/signupwidget'); ?>
                        </div>

                    <?php endif;
                    ?>
                </aside>
            </div>
        </div>
<!--Refactored code-->
<!-- end of common side bar -->


  <!-- end simlir shop widget -->
<!-- end display conditionality code  by kraj -->

        <!-- Separator Starts -->
            <div style="clear:both;"></div>
            <div class="separator mt20"></div>
        <!-- Separator Ends -->

			<?php  if(count($this->moneySavingGuideArticle) >0): ?>

			<header class="heading-box text-advice">
				<h2><?php echo $this->translate("General money saving advice &amp; tricks for shopping at"). " " . $this->data[0]['name']; ?></h2>
			</header>

			<?php echo $this->partialLoop('store/moneySavingGuideArticle.phtml', $this->moneySavingGuideArticle); ?>

         <!-- Separator Starts -->
        <div class="separator">&nbsp;</div>
        <!-- Separator Ends -->

      <?php endif; ?>
      
        <!-- Refactored code -->
        <?php if(count($this->expiredOffers) >0):?>
			
			<header class="heading-box text-expired">
            	<h2><?php echo  $this->translate('Expired').' '.$this->data[0]['name'].' '.$this->translate("vouchers and discounts"); ?></h2>
            	<strong><?php echo  $this->translate('Unfortunately ... These discount codes from').' '.$this->data[0]['name'].' '.$this->translate("you’ve missed");?>.</strong>
			</header>
			<section class="section-module">
				<?php  echo $this->partialLoop('store/expiredOffer.phtml', $this->expiredOffers); ?>
			</section>

        <?php endif;?>
        <!-- END Refactored code -->

<?php if($this->data[0]['howToUse'] == 1){
        if(LOCALE==''):
            $imagePop = HTTP_PATH ."public/images/front_end/logo-popup.png";
       else:
            $imagePop = HTTP_PATH ."public/images/front_end/flip-logo.png";
       endif;?>
<!-- popup div -->

<div id="popup-wrapper" class="maindiv popup-outer">
    <div class="popup-header">
        <div class="popup-logo"><img src="<?php echo $imagePop; ?>" alt="Logo" /></div>
        <div class="popup-cross" id="close-btn" onClick="custompopupClose()"><img src="<?php echo HTTP_PATH; ?>public/images/front_end/cross-white.png" width="10" height="10" alt="cross-white" /></div>
    </div>
    <div class="middlediv"><h4><b><?php echo $this->translate("Zo gebruik je de") ." ". $this->data[0]['name'] ." ". $this->translate("kortingscodes:")?></b></h4>
        <div class="pop-list-outer" id="list"><ol>
              <li><p><?php echo $this->translate("Click the green button to reveal the  code and open the retailer website in either a new tab or window, depending on your browser settings.")?></p></li>
              <li><p><?php echo $this->translate("Buy something nice. Check you've met any terms and conditions then head to the checkout.")?></p></li>
              <li><p><?php echo $this->translate('Copy the code from our site.')?></p></li>
           </ol>
        </div>
        <div style="float:right;margin-right:0;width:280px;">
             <div class="greybox-popup">
                <?php if(!empty($this->data[0]['bigimage'])){ ?>
                    <img src="<?php echo PUBLIC_PATH_CDN.$this->data[0]['bigimage']['path']."thum_bigLogoFile_".$this->data[0]['bigimage']['name'];?>" width="280" height="197" alt="noimage"  />
                    <?php  } else{ ?>
                    <img src="<?php echo HTTP_PATH; ?>public/images/NoImage/280x100.jpg" width="280" height="197" alt="noimage"  />
                    <?php    }?>

             </div>
             <div class="popup-col1-right-col1 mt10" style="margin-bottom:10px"><img src="<?php echo HTTP_PATH; ?>public/images/front_end/shape1.png" width="14" height="43" alt="noimage" /></div>

            <div class="greybox-popup">
                <?php if(!empty($this->data[0]['smallimage'])){ ?>

                    <img src="<?php echo PUBLIC_PATH_CDN.ltrim($this->data[0]['smallimage']['path'],"/")."thum_smallLogoFile_".$this->data[0]['smallimage']['name'];?>" width="280" height="100" alt="noimage" />

                    <?php  } else{ ?>

                    <img src="<?php echo HTTP_PATH; ?>public/images/NoImage/280x197.jpg" width="280" height="100" alt="noimage" />

                    <?php   }?>
            </div>

            </div>
          </div>
    </div>
<?php } ?>
</div>


