<div class="container">
    <div class="section tab-section">
        <ul class="tabset">
<?php
foreach ($this->aboutTabs as $aboutTabIndex => $aboutTab):
    $elementId =  (!empty($aboutTab['permalink'])) ? $aboutTab['permalink'] : $aboutTabIndex;
    ?>
            <li class="<?php echo $aboutTabIndex=='0' ? 'active' : ''; ?>" id="<?php echo $elementId; ?>">
                <a id="tab_<?php echo $elementId;?>"
                onclick="showTab('<?php echo $elementId;?>');" href="javascript:void(0)">
                <?php echo $aboutTab['title']; ?>
                </a>
            </li>
    <?php 
endforeach;
?>
        </ul>
        <div class="tab-content">
<?php 
foreach ($this->aboutTabs as $aboutTabIndex => $aboutTab):
    $elementId =  (!empty($aboutTab['permalink'])) ? $aboutTab['permalink'] : $aboutTabIndex;
?>
            <div id="services_<?php echo $elementId; ?>">
                <?php echo $aboutTab['content']; ?>
            </div>
<?php 
endforeach;
?>
        </div>
    </div>
</div>