<div class="text-block">
    <div class="container">
        <form 
        action="<?php echo HTTP_PATH_LOCALE. FrontEnd_Helper_viewHelper::__link('link_zoeken'); ?>" role="form" 
        class="email-form form-inline" id="search-form">
            <fieldset>
                <h1><?php echo FrontEnd_Helper_viewHelper::replaceStringVariable($this->translate('Searching for Coupons?'));?></h1>
                <h1 class='home-header-second-header'>
                	<?php echo FrontEnd_Helper_viewHelper::replaceStringVariable($this->translate("We&#39;ve got a lot of them :)"));?>
                </h1>
                <div class="holder search-outer">
                    <div class="form-group">
                         <input type="search" 
                         placeholder="<?php echo FrontEnd_Helper_viewHelper::__form('form_What deal are you looking for?');?>"
                         id='searchFieldHeader'
                         name='searchFieldHeader'
                         label='searchField' type="search"  class="form-control" />
                         <input type='hidden' name='searchedKeyword' label='searchHidden' id='searchedKeyword' />
                    </div>
                    <a href="javascript:void(0);" id='searchbuttonHeader'>
                        <button id='searchbuttonHP' class="orange btn btn-default searchbutton">
                        <span class="glyphicon glyphicon-search"></span>
                        <?php echo FrontEnd_Helper_viewHelper::__form('form_Find');?>
                        </button>
                    </a>
                </div>
            </fieldset>
        </form>
    </div>
</div>
