<header class="heading-box text-ask">
    <h2>
<?php
$headerName  = isset($this->shopName) ? $this->shopName : $this->authorName;
echo $this->shopName!= '' 
    ?  $this->translate('Ask a question about'). ' ' . $headerName 
    :  $this->translate('Ask a question');
?>
    </h2>
    <strong>
<?php
echo $this->shopName!= '' 
    ? $this->translate('Ask us anything about'). ' '. $headerName.' '. $this->translate('and their discounts') 
    : $this->translate('Ask us anything about discounts');
?>
    </strong>
</header>
<section id="disqus_thread" class="section section-comments" style="display: none;"></section>
<script type="text/javascript">
    var disqus_shortname = '<?php echo FrontEnd_Helper_viewHelper::__form("form_disqus_shortname");?>';
    <?php if (isset($this->discussionUrl) && $this->discussionUrl != '') { ?>
        var disqus_url = '<?php echo HTTP_PATH_LOCALE.$this->discussionUrl; ?>';
    <?php } ?>
</script>
<?php
$this->minifyHeadScript()->appendFile("/public/js/front_end/disqusComments.js");
?>
<div id="disqusComments" style="background:#fff;">
    <section class="section tips-section tips-section-2">
        <?php
        if (!empty($this->discussionComments)) {
            foreach ($this->discussionComments as $discussionCommentArray) {
                foreach ($discussionCommentArray['disqusComments'] as $discussionComment) {
                ?>
                    <article class= "block">
                        <h5><b><?php echo $discussionComment['author_name'];?></b></h5>
                        <b><?php echo gmdate("Y-m-d", $discussionComment['created']);?></b>
                        <div class="box"><?php echo $discussionComment['comment'];?></div>
                    </article>
                <?php 
                }    
            }
        }
        ?>
    </section>
</div>

