<?php
$signUpUrl= HTTP_PATH_LOCALE. FrontEnd_Helper_viewHelper::__link('link_inschrijven');
$footer = FrontEnd_Helper_viewHelper::getFooterData();
?>
<footer id="footer">
<?php 
if(zend_Controller_Front::getInstance()->getRequest()->getControllerName()!='login'
    && zend_Controller_Front::getInstance()->getRequest()->getControllerName()!='signup'
):
?>
    <div class="bottom-panel">
        <div class="container" id="footer-signup-button">
            <?php
            if (!isset($_COOKIE['registered_user'])) :
                ?>
                <div class="text-center">
                    <h4><?php echo FrontEnd_Helper_viewHelper::__translate('Sign up for the newsletter and keep up to date about all voucher codes.'); ?></h4>
                    <a href="<?php echo $signUpUrl; ?>" class="btn btn-primary sign-up-button"><?php echo FrontEnd_Helper_viewHelper::__form('form_Sign up'); ?></a>
                </div>
                <?php
            endif;
            ?>
        </div>
    </div>
<?php
endif;
?>
    <div class="container bottom-nav">
        <div class="row">
            <?php echo $footer['middleColumn1'];?>
            <?php echo FrontEnd_Helper_viewHelper::replaceStringVariable($footer['middleColumn2']);?>
            <?php echo $footer['middleColumn3'];?>
        </div>
    </div>

    <div class="container add-block">
    <?php echo $footer['middleColumn4'];?>
    <?php echo $footer['bottomFooter'];?>
    </div>
<?php
if (APPLICATION_ENV == 'development') {
    $headScript =  $this->HeadScript();
} else {
    $headScript = $this->minifyHeadScript();
}
echo $headScript;
?>
</footer>
<?php if (!isset($_COOKIE['cookie_agreement']) || empty($_COOKIE['cookie_agreement'])) { ?>
<div id="footer-cookie-info">
    <?php echo FrontEnd_Helper_viewHelper::__translate('This site uses cookies ');?><a class="btn btn-primary btn-xs" onclick="createCookieAgreement();"><strong><?php echo FrontEnd_Helper_viewHelper::__translate('Okay, thanks');?></strong></a>
    <a class="txt-underline" href="<?php echo HTTP_PATH_LOCALE; ?>info/<?php echo FrontEnd_Helper_viewHelper::__link('link_privacy-cookies'); ?>"><?php echo FrontEnd_Helper_viewHelper::__translate('Find out more');?></a>
</div>
<?php } ?>