<div class="panel panel-default">
    <div class="panel-body">
    <form action="" class="" name="sign_up_form" id="sign_up_form" method="post">
        <fieldset>
            <h2><?php echo FrontEnd_Helper_viewHelper::__translate('Keep up to date about all MyTeksi voucher codes with our code alert.'); ?></h2>
            <div class="">
                <div class="input-group input-group-lg">
                    <input type="email" class="form-control" placeholder="<?php echo FrontEnd_Helper_viewHelper::__form('Email Address');?>" name="emailAddress" id="emailAddress">
                    <span class="input-group-btn">
                        <button class="btn btn-primary" type="submit" id="sign_up_button" name="sign_up_button"><?php echo FrontEnd_Helper_viewHelper::__form('Sign up'); ?></button>
                    </span>
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="privacyPolicy" id="privacyPolicy" value="accepated">
                        <label for="privacyPolicy" class="privacyPolicy-label"><?php echo FrontEnd_Helper_viewHelper::__translate('Ik ga akkoord met onze');?> <a href="<?php echo HTTP_PATH_LOCALE; ?>info/<?php echo FrontEnd_Helper_viewHelper::__link('link_privacy-cookies'); ?>" target="_blank"><?php echo FrontEnd_Helper_viewHelper::__translate('privacy policy'); ?></a> <?php echo FrontEnd_Helper_viewHelper::__translate('en'); ?> <a href="<?php echo HTTP_PATH_LOCALE; ?>info/<?php echo FrontEnd_Helper_viewHelper::__link('link_terms'); ?>" target="_blank"><?php echo FrontEnd_Helper_viewHelper::__translate('voorwaarden'); ?></a>.</label>
                    </label>
                </div>
            </div>
        </fieldset>
    </form>
    </div>
</div>