<form action="" class="newsletter-form text-center" name="sign_up_form" id="sign_up_form" method="post">
    <fieldset>
        <h2>Keep up to date about all MyTeksi voucher codes with our code alert.</h2>
        <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3 text-left">
            <div class="input-group input-group-lg">
                <input type="email" class="form-control" placeholder="Email Address" name="emailAddress" id="emailAddress">
                <span class="input-group-btn">
                    <button class="btn btn-primary" type="submit" id="sign_up_button" name="sign_up_button">Sign Up</button>
                </span>
            </div>
            <div></div>
            <div class="checkbox">
                <label>
                    <input type="checkbox" name="privacyPolicy" id="privacyPolicy" value="accepated"> <label for="privacyPolicy">Ik ga akkoord met onze <a href="#">privacy policy</a> en <a href="#">voorwaarden</a>.</label>
                </label>
            </div>
        </div>
    </fieldset>
</form>
