<form action="#" class="newsletter-form text-center">
    <fieldset>
        <h2>Keep up to date about all MyTeksi voucher codes with our code alert.</h2>
        <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3 text-left">
            <div class="input-group input-group-lg">
                <input type="email" class="form-control" placeholder="Email Address">
                <span class="input-group-btn">
                    <button class="btn btn-primary" type="button">Sign Up</button>
                </span>
            </div>
            <div class="checkbox">
                <label>
                    <input type="checkbox"> Ik ga akkoord met onze <a href="#">privacy policy</a> en <a href="#">voorwaarden</a>.
                </label>
            </div>
        </div>
    </fieldset>
</form>