<nav class="account-box">
    <ul>
        <li class="home">
            <a href="<?php echo HTTP_PATH_LOCALE; ?>" rel="nofollow"><?php 
            echo FrontEnd_Helper_viewHelper::__form('form_home'); ?></a>
        </li>
        <li>
            <a rel="nofollow" 
            href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('link_login') ?>">
            <?php echo FrontEnd_Helper_viewHelper::__form('form_Sign In'); ?>
            </a>
        </li>
        <li class="">
            <a rel="nofollow" 
            href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('link_inschrijven') ?>">
            <?php echo FrontEnd_Helper_viewHelper::__form('form_Sign up'); ?>
            </a>
        </li>
    </ul>
</nav>
