<?php 
$visitorInformation = \KC\Repository\Visitor::getUserDetails(Auth_VisitorAdapter::getIdentity()->id);
?>
<nav class="account-box">
    <ul class=''>
        <li class="dropdown">
            <a id="welcomeText" class="dropdown-toggle" onclick="showErrow();" data-toggle="dropdown" href="#">
                <?php echo FrontEnd_Helper_viewHelper::__form('form_Welcome') . " ";?>
                <b class="arrow-menu-up"></b>
            </a>
        <ul class="dropdown-menu pull-right" role="menu" aria-labelledby="dLabel">
            <li class='arrow-up'></li>
            <li class="full-width-li border-bottom">
                <a href="<?php echo HTTP_PATH_LOCALE 
                    . FrontEnd_Helper_viewHelper::__link('link_mijn-favorieten') . "/" 
                    . FrontEnd_Helper_viewHelper::__link('link_memberonlycodes');?>">
                    <?php echo FrontEnd_Helper_viewHelper::__form('form_Your offers');?>
                </a>
            </li>
            <li class="full-width-li border-bottom">
                <a href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('link_mijn-favorieten');?>">
                    <?php echo FrontEnd_Helper_viewHelper::__form('form_Your brands');?>
                </a>
            </li>
            <li class="full-width-li border-bottom">
                <a href="<?php echo HTTP_PATH_LOCALE 
                    . FrontEnd_Helper_viewHelper::__link('link_inschrijven') . "/" 
                    . FrontEnd_Helper_viewHelper::__link('link_profiel');?>">
                    <?php echo FrontEnd_Helper_viewHelper::__form('form_Account Settings');?>
                </a>
            </li>
            <li class="full-width-li">
                <a href=" <?php echo HTTP_PATH_LOCALE 
                    . FrontEnd_Helper_viewHelper::__link('link_login') .'/'
                    . FrontEnd_Helper_viewHelper::__link('link_logout'); ?>">
                    <?php echo FrontEnd_Helper_viewHelper::__form('form_Sign Out');?>
                </a>
            </li>
        </ul>
        </li>
    </ul>
</nav>