<?php

$new_categories = array(
    "Mode",
    "Schoenen",
    "Baby & Kind",
    "Reizen & Vakantie",
    "Huis & Tuin",
    "Boeken, Films & Muziek",
    "Eten & Drinken",
    "Dagje uit",
    "TV, Audio & Camera",
    "Computer ",
    "Printen & Canvas",
    "Telefonie & Internet",
    "Gezondheid & Verzorging",
    "Sport & Outdoor",
    "Zakelijk",
    "Opleiding & Cursus",
    "Bloemen & Geschenken",
    "Dieren",
    "Speelgoed",
    "Kansspelen & Loterij",
    "Verzekeringen & Financien",
    "Dating & Erotiek"
);

$old_2_new = array(
    "Audio & Beeld" => "TV, Audio & Camera",
    "Audio Apparatuur" => "TV, Audio & Camera",
    "CD & Mp3" => "TV, Audio & Camera",
    "DVD & Video" => "TV, Audio & Camera",
    "Overig" => "TV, Audio & Camera",
    "Video Apparatuur" => "TV, Audio & Camera",
    "Boeken & Tijdschriften" => "Boeken, Films & Muziek",
    "Boeken" => "Boeken, Films & Muziek",
    "Kranten" => "Boeken, Films & Muziek",
    "Overig" => "Boeken, Films & Muziek",
    "Proefabonnementen" => "Boeken, Films & Muziek",
    "Tijdschiften" => "Boeken, Films & Muziek",
    "Cadeaus & Gadgets" => "Bloemen & Geschenken",
    "Bloemen" => "Bloemen & Geschenken",
    "Cadeaus" => "Bloemen & Geschenken",
    "Feestartikelen" => "Bloemen & Geschenken",
    "Gadgets" => "Bloemen & Geschenken",
    "Overig" => "Bloemen & Geschenken",
    "Relatiegeschenken" => "Bloemen & Geschenken",
    "Casino & Gokken" => "Wedden & Loterij",
    "Loterijen" => "Wedden & Loterij",
    "Poker" => "Wedden & Loterij",
    "Wedden" => "Wedden & Loterij",
    "Computers & Toebehoren" => "Computer & Printer",
    "Desktop" => "Computer & Printer",
    "Diensten" => "Computer & Printer",
    "Games" => "Computer & Printer",
    "Hardware" => "Computer & Printer",
    "Internet" => "Computer & Printer",
    "Laptop" => "Computer & Printer",
    "Overig" => "Computer & Printer",
    "Software" => "Computer & Printer",
    "Dating & Erotiek" => "Dating & Erotiek",
    "Dating" => "Dating & Erotiek",
    "Erotiek" => "Dating & Erotiek",
    "Lingerie" => "Dating & Erotiek",
    "Overig" => "Dating & Erotiek",
    "Dieren & Toebehoren" => "Dieren",
    "Diensten" => "Dieren",
    "Dieren" => "Dieren",
    "Dieren Accessoires" => "Dieren",
    "Overig" => "Dieren",
    "Diversen" => "X",
    "Dagaanbiedingen" => "X",
    "Enquêtes" => "X",
    "Evenementen" => "X",
    "Goede Doelen" => "X",
    "Gratis" => "X",
    "Overig" => "X",
    "Prijsvragen" => "X",
    "Warenhuizen" => "X",
    "Elektronica & Witgoed" => "",
    "Audio & Video" => "TV, Audio & Camera",
    "Eten & Drinken" => "Eten & Drinken",
    "Navigatie" => "X",
    "Overig" => "Bloemen & Geschenken",
    "Schoonmaken & Wassen" => "Huis & Tuin",
    "Televisie" => "Audio & TV",
    "Eten & Drinken" => "Eten & Drinken",
    "Bestellen" => "Eten & Drinken",
    "Drank" => "Eten & Drinken",
    "Levensmiddelen" => "Eten & Drinken",
    "Overig" => "Eten & Drinken",
    "Restaurants" => "Eten & Drinken",
    "Uitgaan" => "Eten & Drinken",
    "Financieel" => "Verzekeringen & Financien",
    "Banken" => "Verzekeringen & Financien",
    "Beleggen" => "Verzekeringen & Financien",
    "Hypotheken" => "Verzekeringen & Financien",
    "Lenen" => "Verzekeringen & Financien",
    "Overig" => "Verzekeringen & Financien",
    "Sparen" => "Verzekeringen & Financien",
    "Verzekeringen" => "Verzekeringen & Financien",
    "Fotografie & Printen" => "Printen & Canvas",
    "Afdrukken" => "Printen & Canvas",
    "Camera's" => "TV, Audio & Camera",
    "Foto's" => "Printen & Canvas",
    "Kaartje Sturen" => "Bloemen & Geschenken",
    "Overig" => "Printen & Canvas",
    "Huis & Interieur" => "Huis & Tuin",
    "Accessoires" => "Huis & Tuin",
    "Badkamer" => "Huis & Tuin",
    "Energie" => "Huis & Tuin",
    "Keuken" => "Huis & Tuin",
    "Meubels" => "Huis & Tuin",
    "Overig" => "Huis & Tuin",
    "Slaapkamer" => "Huis & Tuin",
    "Woonkamer" => "Huis & Tuin",
    "Kinderen & Baby's" => "Baby & Kind",
    "Baby & Kinderartikelen" => "Baby & Kind",
    "Babykleding" => "Baby & Kind",
    "Kinderkleding" => "Baby & Kind",
    "Overig" => "Baby & Kind",
    "Speelgoed" => "Speelgoed",
    "Mode & Fashion" => "Mode",
    "Accessoires" => "Mode",
    "Dameskleding" => "Mode",
    "Kinderkleding" => "Mode",
    "Kleding" => "Mode",
    "Mannenkleding" => "Mode",
    "Overig" => "Mode",
    "Schoenen" => "Schoenen",
    "Sieraden" => "Mode",
    "Sportkleding" => "Mode",
    "Tassen" => "Mode",
    "Speciale Thema`s" => "X",
    "Kerst" => "X",
    "Nieuwjaar" => "X",
    "Pasen" => "X",
    "Sinterklaas" => "X",
    "Valentijnsdag" => "X",
    "Sport & Hobby's" => "Sport & Outdoor",
    "Cursussen" => "Opleiding & Cursus",
    "Fietsen" => "Sport & Outdoor",
    "Games" => "Computer & Printer",
    "Muziek" => "Boeken, Films & Muziek",
    "Overig" => "Sport & Outdoor",
    "Sport & Fitness" => "Sport & Outdoor",
    "Sportkleding" => "Sport & Outdoor",
    "Voetbal" => "Sport & Outdoor",
    "Telefonie" => "Telefonie & Internet",
    "Abonnementen" => "Telefonie & Internet",
    "GSM" => "Telefonie & Internet",
    "GSM Accessoires" => "Telefonie & Internet",
    "Tickets & Kaartjes" => "Dagje uit",
    "Tuin & Klussen" => "Huis & Tuin",
    "Bouwmateriaal" => "Huis & Tuin",
    "Gereedschap" => "Huis & Tuin",
    "Overig" => "Huis & Tuin",
    "Planten" => "Huis & Tuin",
    "Tuin Accessoires" => "Huis & Tuin",
    "Tuinmeubelen" => "Huis & Tuin",
    "Vakantie & Toerisme" => "Reizen & Vakantie",
    "Bungalow Parken" => "Reizen & Vakantie",
    "Campings" => "Reizen & Vakantie",
    "Hotels" => "Reizen & Vakantie",
    "Huren" => "Reizen & Vakantie",
    "Last Minute" => "Reizen & Vakantie",
    "Musea" => "Dagje uit",
    "Overig" => "Reizen & Vakantie",
    "Pretparken & Dierentuinen" => "Dagje uit",
    "Vakanties" => "Reizen & Vakantie",
    "Vliegreizen" => "Reizen & Vakantie",
    "Weekend" => "Reizen & Vakantie",
    "Wintersport" => "Reizen & Vakantie",
    "Vervoer" => "X",
    "Auto's & Motoren" => "X",
    "Fietsen & Brommers" => "X",
    "Overig" => "X",
    "Verzorging & Gezondheid" => "Gezondheid & Verzorging",
    "Apparatuur" => "Gezondheid & Verzorging",
    "Dieet" => "Gezondheid & Verzorging",
    "Diensten" => "Gezondheid & Verzorging",
    "Overig" => "Gezondheid & Verzorging",
    "Parfum" => "Gezondheid & Verzorging",
    "Uiterlijke Verzorging" => "Gezondheid & Verzorging",
    "Zaken & Transacties" => "Zakelijk",
    "Dienstverlening" => "Zakelijk",
    "Hosting" => "Telefonie & Internet",
    "Kantoorartikelen" => "Zakelijk",
    "Overig" => "Zakelijk"
);
