<?php 
 $this->headTitle()->append($this->translate('Edit Redirect'));
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/jquery.validate.js");
 
 //$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.dataTables.min.js");
 //$this->headScript()->appendFile(PUBLIC_PATH . "/js/dataTableComman.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
 $this->headLink ()->appendStylesheet ( PUBLIC_PATH . "/css/jquery-ui-1.8.16.custom.css" );
 $this->headScript()->appendFile  ( PUBLIC_PATH . "/js/back_end/redirect.js");
?>

<div class="wrap columns-2" id="editRedirect">
   <h1><?php echo $this->translate('Edit Redirect'); ?><button class="btn ml10" type="button" onClick="window.location.href='<?php echo HTTP_PATH ;?>admin/redirect<?php echo '#'.$this->qstring; ?>'"><?php echo $this->translate('Cancel'); ?></button></h1>
        <form method="POST" enctype=multipart/form-data name="editRedirectForm" id="editRedirectForm">
        <input type="hidden" name='selectedShopId' id='selectedShopId' value="" />
        <input type="hidden" value="<?php echo $this->editRedirect[0]['id'];?>" name='id' id='id' />
        <input type="hidden" name='qString' id='qString' value='<?php echo $this->qstring; ?>' />
          <div id="poststuff" class="metabox-holder has-right-sidebar">
              <div id="post-body">
              <div>
               <div class="mainpage-content">
               <div class="mainpage-content-line">
                   <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Original URL'); ?></strong></label></div>
                       <div class="mainpage-content-right">
                         <div class="mainpage-content-right-inner-right-other" style="width:250px;"></div>
                          <div class="mainpage-content-right-inner-left-other">
                          <input type="text" class="span3" placeholder="<?php echo $this->translate('Original URL'); ?>"  name="orignalurl" id="orignalurl" value="<?php echo $this->editRedirect[0]['orignalurl']?>"></div>
                          </div>
                        </div>
                       
                        <div class="mainpage-content-line mt10">
                          <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Redirect To'); ?></strong></label></div>
                            <div class="mainpage-content-right">
                                <div class="mainpage-content-right-inner-right-other" style="width:250px;"></div>
                                <div class="mainpage-content-right-inner-left-other">
                               	<input type="text" placeholder="<?php echo $this->translate('Redirect to'); ?>"  name="redirectto" id="redirectto" value="<?php echo $this->editRedirect[0]['redirectto']?>">
                                </div>
                            </div>
                        </div>
                        <!-- hide show div  -->
                         </div>
                        </div>
                      </div>
                    <br class="clear">
               </div>    
               <div class="mainpage-content-colorbox">
               <button type="submit" id="editKeyword" class="btn btn-large btn-primary fl"><?php echo $this->translate('SAVE CHANGES'); ?>
            	</button>
                <a href="javascript:void(0);" onclick="window.location.href='<?php echo HTTP_PATH ;?>admin/redirect<?php echo '#'.$this->qstring; ?>'" class="fl m10" ><strong><?php echo $this->translate('CANCEL'); ?></strong>
                </a>
                <a id="deleteButton" class="fl red mt10" href="javascript:void(0);"  onclick="deleteRedirectByEdit();"><strong>
                <?php echo $this->translate('DELETE'); ?></strong>
                </a>
            </div>
            <!-- /poststuff -->
            </form>
</div>