<?php
$this->headTitle()->append($this->translate('Locale Settings'));
$this->headMeta('keyword', 'Description');
$this->headScript()->appendFile(PUBLIC_PATH  . "js/back_end/jquery.validate.js");
$this->headScript ()->appendFile ( PUBLIC_PATH . "js/back_end/locale-settings.js" );
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/select2.min.js");
?>
<div class="wrap columns-2">
    <div class='wrap columns-2'>
        <?php echo $this->flashMessages(); ?>
    </div>
    <h1><?php echo $this->translate('Locale Settings'); ?></h1>
    <div class="mainpage-content">
        <div class="mainpage-content-line mb10">
            <div class="mainpage-content-left">
                <label><strong><?php echo $this->translate('Locale'); ?></strong></label>
            </div>
            <div class="mainpage-content-right">
                <div class="mainpage-content-right-inner-left-other">
                    <div data-toggle="buttons-checkbox" class="btn-group">
                        <select id='locale' style='width:200px;'>
                            <option value=""></option>
                            <?php
                                $seletced = '';
                                $locale = Zend_Locale::getLocaleList();
                                foreach ($locale as $localeKey => $localeValue):
                                    if ($this->localeSettings['0']['locale'] == $localeKey) {
                                        $seletced = 'selected="selected"';
                                    }
                                    echo "<option $seletced value=". $localeKey .">". $localeKey ."</option>";
                                endforeach;
                            ?>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="mainpage-content">
        <div class="mainpage-content-line mb10">
            <div class="mainpage-content-left">
                <label><strong><?php echo $this->translate('Locale Status'); ?></strong></label>
            </div>
            <div class="mainpage-content-right">
                <div class="btn-group" data-toggle="buttons-checkbox">
                    <?php
                    $backEndViewHelper = new BackEnd_Helper_viewHelper();
                    echo $this->localeStatus['status'] == 'online' ?
                        $backEndViewHelper->getLocaleStatusButtons('online') :
                        $backEndViewHelper->getLocaleStatusButtons('offline');
                    ?>
                </div>
            </div>
        </div>
    </div>
    <div class="mainpage-content">
        <div class="mainpage-content-line mb10">
            <div class="mainpage-content-left">
                <label><strong><?php echo $this->translate('Time Zone'); ?></strong></label>
            </div>
            <div class="mainpage-content-right">
                <div class="mainpage-content-right-inner-left-other">
                    <div data-toggle="buttons-checkbox" class="btn-group timezone">
                        <select id='timezone' style='width:300px;' name="timezone">
                            <option value=""></option>
                            <?php
                                $timezonesList = $this->timezones_list;
                                foreach($timezonesList as $timezoneskey => $timezonesName):
                                    $seletcedTimeZone = '';

                                    if ($this->localeSettings['0']['timezone'] == $timezoneskey) {
                                        $seletcedTimeZone = 'selected="selected"';
                                    }

                                    echo "<option $seletcedTimeZone value=". $timezoneskey .">".
                                        $timezonesName ."</option>";
                                endforeach;
                            ?>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="mainpage-content">
        <form name="localeChain" method="post" id="localeChain">
            <div class="mainpage-content-line mb10">
                <div class="mainpage-content-left">
                    <label>
                        <strong><?php echo $this->translate('Chain hreflang'); ?></strong>
                    </label>
                </div>
                <div class="mainpage-content-right">
                    <div class="mainpage-content-right-inner-left-other">
                        <div class="mainpage-content-right-inner-right-other"></div>
                        <div data-toggle="buttons-checkbox" class="mainpage-content-right-inner-left-other">
                            <input type="text"
                            value="<?php echo isset($this->chainHrefLang[0]['chain']) ?
                                $this->chainHrefLang[0]['chain'] : '';?>"
                            placeholder=<?php echo $this->translate('Chain hreflang')?>
                            name="chain" id="chain" class="span3">
                        </div>
                    </div>
                </div>
            </div>
            <?php foreach ($this->settings as $setting) : ?>
                    <div class="mainpage-content-line mb10">
                        <div class="mainpage-content-left">
                            <label>
                                <strong><?php echo $this->translate($setting->getLabel()); ?></strong>
                            </label>
                        </div>
                        <div class="mainpage-content-right">
                            <div data-toggle="buttons-checkbox" class="btn-group">
                            <?php if($setting->getName() == 'SHOW_FLOATING_COUPON') : ?>
                                <button type="button" data-option="1" class="btn <?php echo 1 ==  $setting->getValue() ? 'btn-primary' : ''; ?>" onclick="localeSettingToggle(this, '<?php echo $setting->getName(); ?>');"><?php echo $this->translate('Yes'); ?></button>
                                <button type="button" data-option="0" class="btn <?php echo 1 ==  $setting->getValue() ? '' : 'btn-primary'; ?>" style="border-radius: 0 4px 4px 0;" onclick="localeSettingToggle(this, '<?php echo $setting->getName(); ?>');"><?php echo $this->translate('No'); ?></button>
                                <input type="hidden" value="<?php echo $setting->getValue(); ?>" name="settings[<?php echo $setting->getName(); ?>]" id="<?php echo $setting->getName(); ?>" class="span3">
                            <?php else: ?>
                                <input type="text" value="<?php echo $setting->getValue(); ?>" name="settings[<?php echo $setting->getName(); ?>]" class="span3">
                            <?php endif; ?>
                            </div>
                        </div>
                    </div>
            <?php endforeach; ?>
            <div class="mainpage-content-line mb10">
                <div class="mainpage-content-left"><label></label></div>
                <div class="mainpage-content-right">
                    <div class="mainpage-content-right-inner-left-other">
                    <div class="btn-group" data-toggle="buttons-checkbox">
                        <button class="btn btn-primary" type="submit">
                            <?php echo $this->translate('Submit'); ?>
                        </button>
                    </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>