 <?php
  $this->headTitle()->append($this->translate('Article Category'));
  $this->headScript ()->appendFile ( PUBLIC_PATH . "/js/back_end/jquery.validate.js" );
  $this->headScript ()->appendFile ( PUBLIC_PATH . "/js/back_end/addArticleCategory.js" );
  $this->headScript ()->appendFile ( PUBLIC_PATH . "/js/back_end/jquery.textareaCounter.plugin.js");
  $this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/bootbox.min.js");
  $this->headScript ()->appendFile ( PUBLIC_PATH . "/js/jquery.NobleCount.js");
  
?>
<div class="wrap columns-2" id="createCategory">
    <form action="<?php echo HTTP_PATH ;?>admin/articlecategory/editcategory/id/<?php echo $this->data['id']?>" method="POST" id="saveCategoryForm" name="saveCategoryForm" enctype="multipart/form-data">
      
        <h1><?php echo $this->translate('Edit Article Category'); ?><input type="button"  Value='<?php echo $this->translate('Cancel'); ?>' class="btn ml10" onClick="window.location.href='<?php echo HTTP_PATH; ?>admin/articlecategory'" /></h1>
       
        <input type="hidden" value="<?php echo $this->role; ?>" name='role' id='role' />
        <input type="hidden" name='qString' id='qString' value='<?php echo $this->qstring; ?>' />
        <div id="poststuff" class="metabox-holder has-right-sidebar">
            <div id="post-body">
                <div>
                    <div class="mainpage-content">
                        <input type='hidden' name="artCatId" id="artCatId" value="<?php echo $this->data['id']?>">
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left">
                                <label><strong><?php echo $this->translate('Title'); ?></strong></label>
                            </div>
                            <div class="mainpage-content-right">
                                <div class="mainpage-content-right-inner-right-other"></div>
                                <div class="mainpage-content-right-inner-left-other">
                                    <input type="text" name="categoryName" value="<?php echo $this->data['name']?>"
                                        placeholder="<?php echo $this->translate('Title');?>"
                                        class="span3" />
                                </div>
                            </div>
                        </div>
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left">
                                <label><strong><?php echo $this->translate('Permalink'); ?></strong></label>
                            </div>
                            <div class="mainpage-content-right">
                                <div class="mainpage-content-right-inner-left">
                                    <label><?php echo $this->translate('http://www.kortingscode.nl/'); ?></label>
                                </div>
                                <div class="mainpage-content-right-inner-right-other"></div>
                                <div class="mainpage-content-right-inner-right-full">
                                    <input <?php echo ($this->role == '3' || $this->role == '4') ? "disabled=disabled" : "" ;  ?> type="text" name="permaLink" id="permaLink" placeholder="centerparks" class="span3" value="<?php echo $this->data['permalink']?>">
                                    <?php if($this->role == '3' || $this->role == '4'):?><input value="<?php echo $this->data['permalink']?>" type="hidden" name="permaLink" id="permaLink"></div> <?php endif;?>
                                </div>
                            </div>
                        </div>
                        
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left">
                                <label><strong><?php echo $this->translate('Meta Title'); ?></strong></label>
                            </div>
                            <div class="mainpage-content-right">
                                <div class="mainpage-content-right-inner-right-other"></div>
                                <div class="mainpage-content-right-inner-left-other">
                                
                                <input class="input-xlarge mbot bbot ignore" type="text" name="metaTitle" id="metaTitle" value="<?php echo $this->data['metatitle']?>" placeholder="<?php echo $this->translate('Meta title');?>" class="span3">
                                <span id="metaTextLeft" class="nobel"></span>
                                
                                <!--<input type="text" name="metaTitle" value="<?php //echo $this->data['metatitle']?>"
                                        placeholder="<?php //echo $this->translate('Meta Title');?>"
                                        class="span3" maxlength="50"/>-->
                                </div>
                            </div>
                        </div>
                        
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left">
                                <label> <strong>
                                    <?php echo $this->translate ( 'Meta Description' );?>
                                </strong></label>
                            </div>
                            <div class="mainpage-content-right">
                                <div class="mainpage-content-right-inner-right-other"></div>
                                <div class="mainpage-content-right-inner-left-other">
                                
                                <textarea class="input-xlarge mbot bbot ignore" id="metaDescription" name="metaDescription" placeholder="<?php echo $this->translate ( 'Meta Description' );?>" rows="3"><?php echo $this->data['metadescription']; ?></textarea>
                                <span id="metaTextLeft1" class="nobel"></span>
                                
                             <!--<textarea class="input-xlarge mbot bbot ignore" name="metaDescription" id="metaDescription" placeholder="<?php //echo $this->translate ( 'Meta Description' );?>" rows="3"><?php //echo $this->data['metadescription']?></textarea>
                                <input type="text" class="input-xlarge disabled btop word-count"  id="metaTextLeft" value = "Characters Left: <?php //echo 160 - strlen( $this->data['metadescription'] )?>" placeholder="Word Count: 28" disabled="disabled">-->
                                </div>
                            </div>
                        </div>
                        
                        <div class="mainpage-content-line mb10">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Related Categories'); ?></strong></label></div>
                            
                            <div class="mainpage-content-right">
                              <div class="category-error"></div>
                              <div class="categories" style="position:relative;">
                              <?php 
                              $arr = array();
                              foreach ($this->data['refArticlecategoryRelatedcategory'] as $related) {
                                $arr[] = $related['category']['id'];
                              }
                              
                              for($i = 0; $i < count($this->categoryList) ; $i++) { ?>
                              
                               <?php 
                              
                                    if(@in_array($this->categoryList[$i]['id'], $arr) )
                                    {
                                        //echo "true";
                                        $checked = 'checked="checked"' ;
                                    
                                    } else {
                                        
                                        $checked = '' ;
                                    }
                                ?>
                                <input type="checkbox" <?php echo $checked ;?> value="<?php echo $this->categoryList[$i]['id']; ?>" class="" name="selectedCategoryies[]" id="category-<?php echo $this->categoryList[$i]['id']; ?>" />
                            <?php
                            
                           
                               if(trim($this->categoryList[$i]['name'])!=''){ 
                            ?>
                            <button type="button" title="<?php echo $this->categoryList[$i]['name'];?>" class="btn square-btn <?php echo  @in_array( $this->categoryList[$i]['id'] , $arr )  ? "btn-primary" : "" ?>" id="categoryBtn-<?php echo $this->categoryList[$i]['id'];?>" onClick="addCategory(event,'<?php echo $this->categoryList[$i]['id']; ?>')"><?php echo strlen($this->categoryList[$i]['name']) < 20 ? $this->categoryList[$i]['name'] : substr($this->categoryList[$i]['name'],0,20).'..'; ?></button>
                            <?php }
                              
                              } ?>
                            
                            
                              </div>
                          </div>
                  
                    </div>
                        
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left">
                                <label><strong><?php echo $this->translate('Category Icon'); ?></strong></label>
                            </div>
                            <div class="mainpage-content-right control-group">
                                
                                <?php       
                    
                                            $ArticleCategoryPicture = PUBLIC_PATH.'images/upload/no.jpg';
                                                     
                                            if(isset( $this->data['ArtCatIcon']['name'] ) && $this->data['ArtCatIcon']['name'] != '' ) {
                                          
                                                 if( file_exists ( ROOT_PATH .  $this->data['ArtCatIcon']['path'] . $this->data['ArtCatIcon']['name'] )) {
                                                    
                                                    $ArticleCategoryPicture = PUBLIC_PATH_LOCALE .  $this->data['ArtCatIcon']['path']  .'thum_'. $this->data['ArtCatIcon']['name'] ;
                                             
                                                }
                                            }   
                                          
                                      ?>
                                      <img alt="<?php echo $this->translate('Article Category logo'); ?>" src="<?php echo $ArticleCategoryPicture ; ?>">
                                
                                <div class="mainpage-content-right-inner-left-other">
                                     <br>
                                    <input class="span3 ignore" data-max-size="2097152" onchange="checkFileType(event)" type="file" name="categoryIconNameHidden">
                                    <span class="ml15 help-inline" style="display: inline-block; padding-bottom: 5px;"><?php echo $this->translate('Upload .jpg or .png file only (Maximum file size: 2MB)') ?></span>
                                </div>
                            </div>
                        </div>
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left">
                                <label><strong><?php echo $this->translate('Description')?></strong></label>
                            </div>
                            <div class="mainpage-content-right">
                                <div class="mainpage-content-right-inner-right-other"></div>
                                <div class="mainpage-content-right-inner-left-other">
                                
                                <textarea class="input-xlarge mbot bbot ignore word_count" id="description" placeholder="<?php echo $this->translate('Description');?>" rows="3" name="description"><?php echo $this->data['description']?></textarea>
                                <input type="text" class="input-xlarge disabled btop word-count"  id="description_count" disabled="disabled">
                                <!--<textarea rows="3" name="description"
                                        placeholder="<?php //echo $this->translate('Description')?>"
                                        id="description" class="input-xlarge mbot bbot ignore"><?php //echo $this->data['description']?></textarea>
                                        <input maxlength="500" type="text" class="input-xlarge disabled btop word-count"  id="descriptionLeft" value = "Characters Left: <?php //echo 500 - strlen( $this->data['description'] )?>" placeholder="Word Count: 28" disabled="disabled">-->
                                </div>
                            </div>
                        </div>
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left">
                                <label>
                                    <strong>
                                        <?php echo $this->translate ('Category Title Color');?>
                                    </strong>
                                </label>
                            </div>
                            <div class="mainpage-content-right">
                                <div class="mainpage-content-right-inner-right-other"></div>
                                <div class="mainpage-content-right-inner-left-other">
                                    <?php 
                                        $borderClass = $this->data['categorytitlecolor'] == 'e69342'
                                        ? 'color-box-selected-border' : '';
                                    ?>
                                    <div id = "e69342" class = "color-box <?php echo $borderClass;?>"
                                        onclick = "selectedColor('e69342')" style="background-color: #e69342;">
                                    </div>
                                    <?php 
                                        $borderClass = $this->data['categorytitlecolor'] == 'f03580'
                                        ? 'color-box-selected-border' : '';
                                    ?>
                                    <div id = "f03580" class = "color-box <?php echo $borderClass;?>"
                                        onclick = "selectedColor('f03580')" style="background-color: #f03580;">
                                    </div>
                                    <?php 
                                        $borderClass = $this->data['categorytitlecolor'] == '0077cc'
                                        ? 'color-box-selected-border' : '';
                                    ?>
                                    <div id = "0077cc" class = "color-box <?php echo $borderClass;?>"
                                        onclick = "selectedColor('0077cc')" style="background-color: #0077cc;">
                                    </div>
                                    <?php 
                                        $borderClass = $this->data['categorytitlecolor'] == 'e6050f'
                                        ? 'color-box-selected-border' : '';
                                    ?>
                                    <div id = "e6050f" class = "color-box <?php echo $borderClass;?>"
                                        onclick = "selectedColor('e6050f')" style="background-color: #e6050f;">
                                    </div>
                                    <?php 
                                        $borderClass = $this->data['categorytitlecolor'] == '47e64b'
                                        ? 'color-box-selected-border' : '';
                                    ?>
                                    <div id = "47e64b" class = "color-box <?php echo $borderClass;?>"
                                        onclick = "selectedColor('47e64b')" style="background-color: #47e64b;">
                                    </div>
                                    <input type = "hidden" id = "titlecolor"
                                        value = "<?php echo $this->data['categorytitlecolor'];?>" name = "titlecolor">          
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <br class="clear">
        </div>
        <div class="mainpage-content-colorbox">
            <button id='editCategory' type="submit" class="btn btn-large btn-primary fl">
                    <?php echo $this->translate('SAVE CHANGES')?>
                </button>
            <a href="<?php echo HTTP_PATH; ?>admin/articlecategory/" class="fl m10"
                id="cancelCategory"> <strong><?php echo $this->translate('CANCEL')?></strong></a>
                
            <a href="javascript:void(0);" onclick="deleteShop(<?php echo $this->data['id']?>)" class="fl m10 red"
                id="cancelCategory"> <strong><?php echo $this->translate('DELETE')?></strong></a>
        </div>
        <!-- /poststuff -->
    </form>
</div>