<?php
$frontShopHeaderHelper = new FrontEnd_Helper_ShopHeaderPartialFunctions();

$headerBlock =
    $frontShopHeaderHelper->getShopHeader(
        $this->currentStoreInformation[0],
        $message = 'storeHowTo',
        $offerTitle = 'storeHowTo'
    );
$storeViewPartialPath = 'store/';
$partialViewPath = 'partials/';

$howToGuides = '';
if ($this->currentStoreInformation[0]['howToUse'] != '') :
    $howToGuides = $this->partial(
        $storeViewPartialPath.'_how-to-guide-chapters.phtml',
        array(
           'howToGuides' => $this->howToGuides,
           'shopName' => $this->currentStoreInformation[0]['name']
        )
    );
endif;
 
echo $headerBlock;
?>
</div></div></div>
<div class="row">
    <div id="content" class="col-md-8 col-sm-8">
    <?php
    $offers = $this->offers;
    if(!empty($offers)) {
        for ($i = 0; $i<count($offers); $i++) {
            $signUpForm = '';
            if ($i == 0) {
                $signUpForm = $this->form; 
            }
            $storeFilteredOffers = $this->partial(
                   $partialViewPath .'_offer.phtml',
                    array(
                        'offers' => $offers[$i],
                        'offersType'=>'simple',
                        'shopName' => $this->currentStoreInformation[0]['name'],
                        'shop' => $this->currentStoreInformation[0],
                        'zendForm'=> $signUpForm,
                        'pageType' => 'howToGuide'
                    )
                ); 
            if ($i == 0) {
            echo  $storeFilteredOffers.$howToGuides;
            } else {
                echo '<header class="heading-box text-star">
                        <h2>'.$this->translate('Most valuable codes from').' '
                        . $this->currentStoreInformation[0]['name'].'</h2>
                    </header>'.$storeFilteredOffers;
            }
        }
    } else {
        echo  $howToGuides;
    }
    ?>
    </div>
    <aside id="sidebar" class="col-md-4 col-sm-4">
    <?php
    echo $this->partial(
            $storeViewPartialPath. '_shop-sidebar.phtml',
            array(
                'shopEditor' => '',
                'latestShopUpdates'=> array(),
                'shopChain' => $this->shopChain,
                'shop' => $this->currentStoreInformation[0],
                'popularStoresList'=> $this->popularStoresList
            )
        );
    if ($this->currentStoreInformation[0]['showSignupOption']) :
        $this->locale = LOCALE != 'en' ? LOCALE . '/' : '';
        echo $this->esi($this->locale.'signup/signupwidget?shopId='.$this->currentStoreInformation[0]['id']
        .'&signupFormWidgetType=sidebarWidget&shopLogoOrDefaultImage=');
    endif;
    $frontendSidebarHelper = new FrontEnd_Helper_SidebarWidgetFunctions();
    echo $frontendSidebarHelper->popularCategoryWidget();
    echo $this->partial('socialcode/social-code.phtml', array('zendForm' => $this->zendForm));
    ?>
    </aside>
</div>
     