<?php 
$this->minifyHeadScript()->prependFile ( HTTP_PATH."public/js/front_end/resetpassword.js");
$this->minifyHeadLink()->prependStylesheet("/public/css/front_end/login.css");
$resetPasswordForm = $this->form;
// Remove <dt> from label generation
foreach ($resetPasswordForm->getElements() as $formElement) {
    $formElement->getDecorator('label')->setOption('tag', null);
}

$message =  $this->successMessage!='' ? $this->successMessage : $this->errorMessage;
$message = $message!='' && $this->linkAlreadyUsed==true ? $message : $this->resetLinkMessage;

if ($message!='') : ?>
    <div id="messageDiv" class="yellow-box-error-box-code myprofile-messagebox">
        <span class='glyphicon glyphicon-warning-sign'></span>
        <strong><?php echo $message;?></strong>
    </div>
    <?php 
endif;
if($this->linkAlreadyUsed):
    ?>
    <section class="login-box">
        <h1><?php echo $this->translate('Please reset your new password!');?></h1>
        <form action="" method="post" class="login-form" name="resetPassword" id="resetPassword">
            <fieldset>
                <div class="form-group">
                <?php 
                echo $resetPasswordForm->password->renderLabel()
                . $resetPasswordForm->password->renderViewHelper();
                ?>
                </div>
                <div class="form-group">
                <?php 
                echo $resetPasswordForm->confirmPassword->renderLabel()
                . $resetPasswordForm->confirmPassword->renderViewHelper();
                ?>
                </div>
                <div class="form-group">
                <?php 
                echo $this->formSubmit(
                    'submit',
                    FrontEnd_Helper_viewHelper::__form('form_Change Password'),
                    array('class'=>'btn blue btn-lg btn-primary', 'id'=>'Reset Password')
                )
                ?>
                </div>
            </fieldset>
        </form>
    </section>
    <?php 
endif;