<?php 
	echo $this->partial('partials/_headerSearch.phtml',array('breadcrumb' => null));
?>
<div class="new-outer">
	<div class='unsubscribe-wrapper fl'>
		<h1><?php echo $this->translate('Succesvol uitgeschreven');?></h1>
		<p><?php echo $this->translate('Je bent succesvol uitgeschreven voor de wekelijkse nieuwsbrief van Kortingscode.nl');?></p>
		<p><?php echo $this->translate('Jammer dat je niet meer per e-mail op de hoogte wil vorden gehouden van de nieuwste en leukste actiecodes');?></p>
	</div>
	
	<div class='newsletter-signup fl'>
		<p><?php echo $this->translate('Mocht je je willen aanmelden met een ander e-mailadres, klik dan op onderstaande link:');?></p>
		<div class='newsletter-btn fl'>Aanmelden Nieuwsbrief</div>
	</div>
	
</div>
