<script>
	$(document).ready(showDummyPage);
</script>
<!-- Search Outer2 Ends -->
<div class='new-outer'>    
    <div class="fav_img_outer">
		<div id='showHide' class="user-pic pos_relative">
			<img  class='mt24' src="<?php echo HTTP_PATH .'public/images/front_end/per_icon.png'?>" alt="User Image" />
		</div>
        <div class="user-profile-txt">
        	<h2><?php echo $this->translate('Hein');?></h2>
            <?php echo $this->translate(utf8_encode('Welkom terug&#33; Voeg een aantal van je favoriete winkels toe zodat je altijd op de hoogte blijft van de beste acties &#38; kortingscodes&#33;'))?>
        </div>
	</div>
    
     <div class="new-signup-outer-round mt40">
     <!--Favourite Txt Bg-->
        <!--Favourite Txt Bg-->
        <div class="fav_txt_bg">
        	<!--Lt Side-->
        	<div class="fav_txt_lt">
            	<ul>
                	<li class="p-deals"><a href="javascript:void(0);"><?php echo $this->translate('Persoonlijke deals');?></a></li>
                    <li class="m-codes"><a class="sltd" href="javascript:void(0);"><?php echo $this->translate('Members only codes');?></a></li>
                    <li class="my-profile"> <a href="javascript:;"><?php echo $this->translate('Mijn profiel');?></a></li>
                </ul>
            </div>
            <!--//Lt Side-->
            
            <!--Rt Side-->
        	<div class="fav_txt_rt">
            	<h3 class="text-blue"><?php echo $this->translate('Member-Only');?></h3>
                <div class="sub_hdr mb20">
    				<img src="<?php echo HTTP_PATH; ?>public/images/front_end/fav_icon.png" alt="" />
    					<?php echo $this->translate('Jouw favorieten codes');?>
   				 </div>
                
                 <div class="shops_fav">
                   <div class="shops_fav_codes mr15 mb20">
                     <div class="percentage"><?php echo $this->translate('15% korting op B.Loved Collectie bij Selected Labels');?></div>
                     <div class="percentage_logo"><img src="<?php echo HTTP_PATH; ?>public/images/front_end/prcent_logo_03.jpg" alt="" /></div>
                     <div class="percentage_code"><img src="<?php echo HTTP_PATH; ?>public/images/front_end/coupon_03.png" alt="" /> </div>
                     <div class="codetxt"><?php echo $this->translate('Alle')?><a href="#"><?php echo $this->translate('Babywalz Kortingscode');?></a><br /> 
                     <?php echo $this->translate('Verloopt op: 31 March 2013');?></div>
                   </div>
                   
                   <div class="shops_fav_codes mr15 mb20">
                     <div class="percentage"><?php echo $this->translate('15% korting op B.Loved Collectie bij Selected Labels');?></div>
                     <div class="percentage_logo"><img src="<?php echo HTTP_PATH; ?>public/images/front_end/prcent_logo_06.jpg" alt="" /></div>
                     <div class="percentage_code"><img src="<?php echo HTTP_PATH; ?>public/images/front_end/coupon_03.png" alt="" /> </div>
                     <div class="codetxt"><?php echo $this->translate('Alle')?><a href="#"><?php echo $this->translate('Babywalz Kortingscode');?></a><br /> 
                     <?php echo $this->translate('Verloopt op: 31 March 2013');?></div>
                   </div>
                   
                   <div class="shops_fav_codes mb20">
                      <div class="percentage"><?php echo $this->translate('15% korting op B.Loved Collectie bij Selected Labels');?></div>
                     <div class="percentage_logo"><img src="<?php echo HTTP_PATH; ?>public/images/front_end/prcent_logo_03.jpg" alt="" /></div>
                     <div class="percentage_code"><img src="<?php echo HTTP_PATH; ?>public/images/front_end/coupon_03.png" alt="" /> </div>
                     <div class="codetxt"><?php echo $this->translate('Alle')?><a href="#"><?php echo $this->translate('Babywalz Kortingscode');?></a><br /> 
                     <?php echo $this->translate('Verloopt op: 31 March 2013');?></div>
                   </div>
                   
                   <div class="shops_fav_codes mr15 mb20">
                      <div class="percentage"><?php echo $this->translate('15% korting op B.Loved Collectie bij Selected Labels');?></div>
                     <div class="percentage_logo"><img src="<?php echo HTTP_PATH; ?>public/images/front_end/prcent_logo_11.jpg" alt="" /></div>
                     <div class="percentage_code"><img src="<?php echo HTTP_PATH; ?>public/images/front_end/coupon_03.png" alt="" /> </div>
                     <div class="codetxt"><?php echo $this->translate('Alle')?><a href="#"><?php echo $this->translate('Babywalz Kortingscode');?></a><br /> 
                    <?php echo $this->translate('Verloopt op: 31 March 2013');?></div>
                   </div>
                   
                   <div class="shops_fav_codes mr15 mb20">
                     <div class="percentage"><?php echo $this->translate('15% korting op B.Loved Collectie bij Selected Labels');?></div>
                     <div class="percentage_logo"><img src="<?php echo HTTP_PATH; ?>public/images/front_end/prcent_logo_06.jpg" alt="" /></div>
                     <div class="percentage_code"><img src="<?php echo HTTP_PATH; ?>public/images/front_end/coupon_03.png" alt="" /> </div>
                     <div class="codetxt"><?php echo $this->translate('Alle')?><a href="#"><?php echo $this->translate('Babywalz Kortingscode');?></a><br /> 
                     <?php echo $this->translate('Verloopt op: 31 March 2013');?></div>
                   </div>
                   
                   <div class="shops_fav_codes mb20">
                      <div class="percentage"><?php echo $this->translate('15% korting op B.Loved Collectie bij Selected Labels');?></div>
                     <div class="percentage_logo"><img src="<?php echo HTTP_PATH; ?>public/images/front_end/prcent_logo_03.jpg" alt="" /></div>
                     <div class="percentage_code"><img src="<?php echo HTTP_PATH; ?>public/images/front_end/coupon_03.png" alt="" /> </div>
                     <div class="codetxt"><?php echo $this->translate('Alle')?><a href="#"><?php echo $this->translate('Babywalz Kortingscode');?></a><br /> 
                    <?php echo $this->translate('Verloopt op: 31 March 2013');?></div>
                   </div>
                   
                   <div class="shops_fav_codes mr15 mb20">
                     <div class="percentage"><?php echo $this->translate('15% korting op B.Loved Collectie bij Selected Labels');?></div>
                     <div class="percentage_logo"><img src="<?php echo HTTP_PATH; ?>public/images/front_end/prcent_logo_06.jpg" alt="" /></div>
                     <div class="percentage_code"><img src="<?php echo HTTP_PATH; ?>public/images/front_end/coupon_03.png" alt="" /> </div>
                     <div class="codetxt"><?php echo $this->translate('Alle')?><a href="#"><?php echo $this->translate('Babywalz Kortingscode');?></a><br /> 
                     <?php echo $this->translate('Verloopt op: 31 March 2013');?></div>
                   </div>
                   
                   <div class="shops_fav_codes mr15 mb20">
                    <div class="percentage"><?php echo $this->translate('15% korting op B.Loved Collectie bij Selected Labels');?></div>
                     <div class="percentage_logo"><img src="<?php echo HTTP_PATH; ?>public/images/front_end/prcent_logo_03.jpg" alt="" /></div>
                     <div class="percentage_code"><img src="<?php echo HTTP_PATH; ?>public/images/front_end/coupon_03.png" alt="" /> </div>
                     <div class="codetxt"><?php echo $this->translate('Alle')?><a href="#"><?php echo $this->translate('Babywalz Kortingscode');?></a><br /> 
                    <?php echo $this->translate('Verloopt op: 31 March 2013');?></div>
                   </div>
                   
                   <div class="shops_fav_codes mb20">
                      <div class="percentage"><?php echo $this->translate('15% korting op B.Loved Collectie bij Selected Labels');?></div>
                     <div class="percentage_logo"><img src="<?php echo HTTP_PATH; ?>public/images/front_end/prcent_logo_11.jpg" alt="" /></div>
                     <div class="percentage_code"><img src="<?php echo HTTP_PATH; ?>public/images/front_end/coupon_03.png" alt="" /> </div>
                     <div class="codetxt"><?php echo $this->translate('Alle')?><a href="#"><?php echo $this->translate('Babywalz Kortingscode');?></a><br /> 
                     <?php echo $this->translate('Verloopt op: 31 March 2013');?></div>
                   </div>
                 </div>
                
            </div>
            <!--//Rt Side-->
            
        </div>
        <!--//Favourite Txt Bg-->
        <!--//Favourite Txt Bg-->
    </div>
</div>  