<?php
$this->minifyHeadScript()->prependFile(HTTP_PATH."public/js/front_end/forgotpassword.js");
$this->minifyHeadLink()->prependStylesheet("/public/css/front_end/login.css");
$forgotPasswordForm = $this->form;
// Remove <dt> from label generation
foreach ($forgotPasswordForm->getElements() as $formElement) {
    $formElement->getDecorator('label')->setOption('tag', null);
}
if ($this->successMessage!='' || $this->errorMessage!='') : ?>
    <div id="messageDiv" class="yellow-box-error-box-code myprofile-messagebox">
        <strong><?php echo $this->successMessage!='' ? $this->successMessage : $this->errorMessage;?></strong>
    </div>
    <?php 
endif;
?>
<section class="login-box">
    <h1><?php echo $this->translate('Please enter the registered email address!');?></h1>
    <form action="" method="post" class="login-form" name="forgotPassword" id="forgotPassword">
        <fieldset>
            <div class="form-group">
            <?php 
            echo $this->translate($forgotPasswordForm->emailAddress->renderLabel())
            . $forgotPasswordForm->emailAddress->renderViewHelper();
            ?>
            </div>
            <div class="form-group">
            <?php 
            echo $this->formSubmit(
                'submit',
                $this->translate('Forgot Password'),
                array('class'=>'btn blue btn-lg btn-primary', 'id'=>'forgotpassword')
            )
            ?>
            </div>
        </fieldset>
    </form>
</section>