<?php
	 $this->minifyHeadScript()->prependFile (HTTP_PATH."public/js/front_end/jquery.placeholder.js");
	 $this->minifyHeadScript()->prependFile (HTTP_PATH."public/js/front_end/forgotpwd.js");
?>
 <script>
   $(function() {
    // Invoke the plugin
    $('input, textarea').placeholder();
   
   });
</script>
 <div class='new-outer'>
	 <div class="new-signup-outer-round mt40">
	 <div class='forgot-pwd-warning'>
	 	<div style="" id="notfound" class="yellow-box-error-box-code no-margin"><strong><?php echo $this->translate("E-mail adres niet gevonden :(")?></strong></div>
	 	<div style="" id="emailsent" class="yellow-box-error-box-code no-margin"><strong><?php echo $this->translate("An Email has been sent to you please check and click on link recieved to reset the password .!")?></strong></div>
	</div>
	 <h2 class="mb20">
	 <?php echo $this->translate('Wachtwoord vergeten?') ?></h2>
	 <p class="forgot-password-text">
	 	<?php echo $this->translate('Vul hieronder het emailadres in waarmee je geregistreerd staat, je ontvangt dan automatisch een e-mail met daarin om een nieuw wachtwoord in te stellen.') ?>
	  </p>
	 
	 <form name="forgotpwd" id="forgotpwd" method="post" action="" autocomplete="off">
		 <div class="login-form">
		 	<div class="error-msg"></div>
		 
		 <div class="login-form-row">
		 	<input class="textLine" tabindex="1"  type="text" name="email" id="email" value="" placeholder="<?php echo FrontEnd_Helper_viewHelper::__form('Uw e-mailadres');?>"/>
		 	<label class="lblerrcls" style="margin:0;padding:0;"></label>
		 </div>
		  <div class="clr"></div>
		 <div id='changeWhenLogin' class="blue_btn">
		 	<a tabindex="2" onclick="sendMailUser();" href="javascript:void(0);"><?php echo FrontEnd_Helper_viewHelper::__form('verstuur') ?></a>
		 </div>
		  
		 <div class="clr"></div>
		 </div>
		 </form>
	 </div>
<!--     <?php echo $this->render('login/login_footer_member.phtml')?>-->  
</div>
