<?php
$this->minifyHeadScript()->prependFile ( HTTP_PATH."public/js/front_end/jquery.placeholder.js");
$this->minifyHeadScript()->prependFile ( HTTP_PATH."public/js/front_end/login.js" );
?>
<script>
   $(function() {
    	// Invoke the plugin
	    $('input, textarea').placeholder();
   });
</script>

	<div class='new-outer'>
	<div class="new-signup-outer-round mt40">
	<div class='forgot-pwd-warning'>
	 	<div style="display: none" id="errorPop" class="yellow-box-error-box-code mt10 no-margin"><strong><?php echo $this->translate("Weet je het zeker? Deze inloggegevens staan niet in ons systeem! Probeer het alsjeblieft opnieuw..")?></strong></div>
	 </div>
   		<h2>
        	<?php echo $this->translate("Log snel in want er worden dagelijks nieuwe Members-Only codes toegevoegd!"); ?>
        </h2>
       <form name="login" id="login" method="post" action="" autocomplete="off"> 
        <div class="login-form">
       		<div class="error-msg"></div>
            <div class="login-form-row clearfix">
            	<input type="text" name="uname" id="uname" value="" tabindex="1" placeholder="<?php echo $this->translate("e-mailaddress");?>" /><label class="lblerrcls"></label>
            </div>
            <div class="login-form-row clearfix">
            	<input type="password" name="pwd" id="pwd" value=""  tabindex="2"  type="text" placeholder="<?php echo $this->translate("password") ?>"/><label class="lblerrcls"></label>
                
            </div>
            
            	<a href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('login').'/'.FrontEnd_Helper_viewHelper::__link('forgotpassword')?>" class="forgot-password-login"><?php echo $this->translate("Vergeten?");?></a>
            <div class="clr"></div>
            <div id='changeWhenLogin' class="blue_btn">
            	<a href="javascript:void(0);"  tabindex="3" onclick="checkLogin();"><?php echo $this->translate('aanmelden');?></a>
            </div>
            <div class="already-ac">
            	<?php echo $this->translate("Heb je nog geen account? ") ; ?> <a href="<?php echo HTTP_PATH_LOCALE. FrontEnd_Helper_viewHelper::__link('inschrijven').'/'.FrontEnd_Helper_viewHelper::__link('stap1')?>"><?php echo $this->translate("Klik hier om je te registreren") ;?></a>
            </div>
       
       <div class="clr"></div>
       </div> 
       </form>
    </div>
    <!--     <?php echo $this->render('login/login_footer_member.phtml')?> -->
</div>