<?php
$this->minifyHeadScript()->prependFile(HTTP_PATH. "public/js/front_end/login.js");
$this->minifyHeadLink()->prependStylesheet("/public/css/front_end/login.css");
$loginFrom = $this->form;
// Remove <dt> from label generation
foreach ($loginFrom->getElements() as $formElement) {
    $formElement->getDecorator('label')->setOption('tag', null);
}
if($this->messageSuccess!='' || $this->messageError!='') : ?>
    <div id="messageDiv" class="yellow-box-error-box-code myprofile-messagebox">
       <strong><?php echo $this->messageSuccess!='' ? $this->messageSuccess : $this->messageError;?></strong>
    </div>
    <?php 
endif;
$forgotPasswordLink =
    HTTP_PATH_LOCALE .
    FrontEnd_Helper_viewHelper::__link('login').'/'
    .FrontEnd_Helper_viewHelper::__link('forgotpassword');
?>
<section class="login-box">
    <h1><?php echo $this->translate('Welkom back, nice to see you again!');?></h1>
    <form action="" method="post" class="login-form" name="login" id='login'>
        <fieldset>
            <div class="form-group">
            <?php echo $loginFrom->emailAddress->renderLabel(). $loginFrom->emailAddress->renderViewHelper();?>
            </div>
            <div class="form-group">
                <div class="link">
                    <?php echo $loginFrom->password->renderLabel();?>
                    <a href="<?php echo $forgotPasswordLink;?>"
                        class="right">
                        <?php echo $this->translate('Forgot password?');?>
                    </a>
                </div>
                <?php echo $loginFrom->password->renderViewHelper();?>
            </div>
            <div class="form-group">
            <?php 
            echo $this->formSubmit(
                'submit',
                $this->translate('sign in'),
                array('class'=>'btn blue btn-lg btn-primary', 'id'=>'login')
            )
            ?>
                <div class="text"><?php echo $this->translate('No Account yet?');?>
                    <a href="<?php echo HTTP_PATH_LOCALE. FrontEnd_Helper_viewHelper::__link('inschrijven');?>">
                        <?php echo $this->translate('Click here to register');?>
                    </a>
                </div>
            </div>
        </fieldset>
    </form>
</section>
