<div onclick="custompopupClose()" class="crose-button-addtofavorite"><img width="10" height="10" src="<?php echo HTTP_PATH;?>public/images/front_end/cross-black.png"></div>  
 
<div class="new-signup-form new-signup-form-new">
   <h2 class="text-center mt40"><strong>
       <?php
         echo $this->translate('Doe mee met kortingscode.nl'); 
       ?></strong>
    </h2>

    <p class="mb20">
       <?php 
          echo $this->translate('Krijg gratis toegang to exclusive Members-Only codes an kortingen!'); 
       ?>
    </p>
	
  	<a rel="nofollow" class="mt20" href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link ('inschrijven'). '/' .  FrontEnd_Helper_viewHelper::__link('stap1');?>">
  		<button  class="directSignupButton" value="<?php echo  FrontEnd_Helper_viewHelper::__link('DIRECT ACCOUNT AANMAKEN') ?>"><?php echo  FrontEnd_Helper_viewHelper::__link('DIRECT ACCOUNT AANMAKEN') ?></button>
  	</a>
  
    <div class="already-ac">
	    <?php echo $this->translate('Al een member?'); ?>
	    <a href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('login') ?>">
	    <?php echo $this->translate('Login'); ?>
	    </a>
	 </div>
</div>