<?php 

$domain = $_SERVER['HTTP_HOST'];
if(isset($this->fbtitle)){

	$this->headMeta()->setProperty('og:title', @$this->fbtitle);
}
$this->headMeta()->setProperty('og:type', 'website');
if(isset($this->fbshareUrl)){

	$this->headMeta()->setProperty('og:url', @$this->fbshareUrl);
}

if(isset($this->fbImg)){
	
	$this->headMeta()->setProperty('og:image', @$this->fbImg);
}

if($domain == "kortingscode.nl" || $domain == "www.kortingscode.nl"):
	$this->headMeta()->setProperty('og:site_name', "Kortingscode.nl");
else:
	$this->headMeta()->setProperty('og:site_name', "Flipit.com");
	
endif;
?>