<link href='http://fonts.googleapis.com/css?family=Cookie' rel='stylesheet' type='text/css'>
<?php
	if (APPLICATION_ENV == 'development') {
		$lessCssPath = "/public/css/front_end/";
?>
<link rel="stylesheet/less" type="text/css" href="<?php echo $lessCssPath;?>all-stores.less"/>
<link rel="stylesheet/less" type="text/css" href="<?php echo $lessCssPath;?>contact.less"/>
<link rel="stylesheet/less" type="text/css" href="<?php echo $lessCssPath;?>faq.less"/>
<link rel="stylesheet/less" type="text/css" href="<?php echo $lessCssPath;?>flipit-expired.less"/>
<link rel="stylesheet/less" type="text/css" href="<?php echo $lessCssPath;?>login.less"/>
<link rel="stylesheet/less" type="text/css" href="<?php echo $lessCssPath;?>profile.less"/>
<link rel="stylesheet/less" type="text/css" href="<?php echo $lessCssPath;?>register.less"/>
<link rel="stylesheet/less" type="text/css" href="<?php echo $lessCssPath;?>splash-page.less"/>
<link rel="stylesheet/less" type="text/css" href="<?php echo $lessCssPath;?>404.less"/>
<link rel="stylesheet/less" type="text/css" href="<?php echo $lessCssPath;?>all-categoties-alt.less"/>
<link rel="stylesheet/less" type="text/css" href="<?php echo $lessCssPath;?>in-savings.less"/>
<link rel="stylesheet/less" type="text/css" href="<?php echo $lessCssPath;?>home.less"/>
<link rel="stylesheet/less" type="text/css" href="<?php echo $lessCssPath;?>saving.less"/>
<link rel="stylesheet/less" type="text/css" href="<?php echo $lessCssPath;?>all.less"/>
<link rel="stylesheet/less" type="text/css" href="<?php echo $lessCssPath;?>custom.less"/>
<link rel="stylesheet/less" type="text/css" href="<?php echo $lessCssPath;?>author.less"/>
<link rel="stylesheet/less" type="text/css" href="<?php echo $lessCssPath;?>authors.less"/>
<link rel="stylesheet/less" type="text/css" href="<?php echo $lessCssPath;?>ie.less"/>
<?php
	} else {
   		echo $this->minifyHeadLink()->prependStylesheet("/public/css/front_end/all.css");
	}



