<link href='http://fonts.googleapis.com/css?family=Cookie' rel='stylesheet' type='text/css'>
<?php
	if (APPLICATION_ENV == 'development') {
		$lessCssPath = "/public/css/front_end/";
?>
<link rel="stylesheet/less" type="text/css" href="<?php echo $lessCssPath;?>all.less"/>
<link rel="stylesheet/less" type="text/css" href="<?php echo $lessCssPath;?>ie.less"/>
<?php
	} else {
   		echo $this->minifyHeadLink()->prependStylesheet("/public/css/front_end/all.css");
	}



