<?php
$this->minifyHeadScript()->prependFile("public/js/common.js")
    ->prependFile("public/js/front_end/jquery-bigtext.js");

if(LOCALE !='') :
    $this->minifyHeadScript()->prependFile("public/" . LOCALE ."/js/front_end/json/translation.js")
        ->prependFile("public/" . LOCALE ."/js/front_end/json/shops.js");

else:
   $this->minifyHeadScript()->prependFile("public/js/front_end/json/translation.js")
       ->prependFile("public/js/front_end/json/shops.js");
endif;

  echo $this->minifyHeadScript()->prependFile("public/js/front_end/layout.js")
      ->prependFile("public/js/Gettext.js")
      ->prependFile("public/js/jquery-ui-1.8.16.custom.min.js")
      ->prependFile("public/js/back_end/jquery.validate.js")
      ->prependFile("public/js/bootstrap.js")
      ->prependFile("public/js/jquery-1.7.2.min.js" )
      ->prependScript('var HOST_PATH = "'.  HTTP_PATH .'";')
      ->prependScript('var HOST_PATH_LOCALE = "'.  HTTP_PATH_LOCALE .'";')
      ->prependScript('var HOST_PATH_PUBLIC = "'.  PUBLIC_PATH .'";');
