<?php
# render flipit.com home page when url www.flipit.com, http://www.flipit.com, flipit.com 
$flipitHomePage = FrontEnd_Helper_LayoutContent::loadFlipitHomePage($this->serverUrl());
echo $flipitHomePage!='' ?  $flipitHomePage['obj']->render($flipitHomePage['path']) : '';
echo $flipitHomePage['path']!='' ? die : ''; 
echo $this->doctype("XHTML1_RDFA");

# manage the kc_session_active by checking the front_login session, we need this cookie for Varnish
$localeName = Signupmaxaccount::getLocaleName();
$countryLocale = !empty($localeName['locale']) ? $localeName['locale'] : 'nl_NL';
$locale = explode('_', $countryLocale);
$language = $locale[0];
?>
<html lang="<?php echo $language; ?>" xml:lang="<?php echo $language; ?>" xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php
$this->headLink(FrontEnd_Helper_LayoutContent::loadCanonical($this->canonical));
$this->headMeta()->appendName('robots', 
		FrontEnd_Helper_LayoutContent::loadRobots(
				$this->param, $this->layout()->robotKeywords
				)
		);

echo $this->headTitle();
echo $this->layout()->customHeader ;
echo $this->headLink( array( 'rel' => 'shortcut icon',
						'href' => HTTP_PATH . 'public/images/favicon.ico',
						'type' => 'image/x-icon'
					   )
			   		);

echo $this->render('fbmeta.phtml');
echo $this->headMeta();
echo $this->minifyHeadLink()->prependStylesheet("public/css/placeholder_polyfill.css")
							->prependStylesheet("public/css/bootstrap.min.css")
							->prependStylesheet("public/css/bootstrap.css")
							->prependStylesheet("public/css/front_end/style.css");

echo $this->headStyle();
echo $this->minifyHeadScript()->prependFile ("public/js/common.js" )
							  ->prependFile ("public/js/front_end/jquery-bigtext.js" )
 							  ->prependFile ("public/js/front_end/json/translation.js" )
 							  ->prependFile ("public/js/front_end/json/shops.js" )
							  ->prependFile ("public/js/front_end/layout.js" )
							  ->prependFile ("public/js/Gettext.js" )
							  ->prependFile ("public/js/jquery-ui-1.8.16.custom.min.js" )
							  ->prependFile ("public/js/back_end/jquery.validate.js" )
							  ->prependFile ("public/js/bootstrap.js" )
							  ->prependFile ("public/js/jquery-1.7.2.min.js" )
							  ->prependScript(  'var HOST_PATH = "'.  HTTP_PATH .'";'  )
							  ->prependScript(  'var HOST_PATH_LOCALE = "'.  HTTP_PATH_LOCALE .'";'  )
 							  ->prependScript( 'var HOST_PATH_PUBLIC = "'.  PUBLIC_PATH .'";'  );

echo FrontEnd_Helper_LayoutContent::loadGoogleAnalyticsCode();
?>
</head>
<body>
    <div class="outerwrapper">
		<!-- hidden field for apply selected class on menu -->
	    <input type="hidden" name='cName' id='cName' value='<?php echo strtolower($this->controllerName);?>'/>
	    <input type="hidden" name='aName' id='aName' value='<?php echo strtolower($this->action);?>'/>
	    <div class="nav-bg"></div>
	    <div class="innerwrapper">
		     <?php echo $this->render('partials/_header.phtml'); ?>
			 <div class="content-section">
                <?php echo $this->render('partials/_top_nav.phtml'); ?>
			    <?php echo $this->layout()->content;?>
			</div>
		    <?php echo $this->render('partials/_footer.phtml');  ?>
		</div>
    </div>
	<?php echo $this->render('partials/_pop_up.phtml'); ?>
</body>
</html>

