<?php
if(LOCALE=='') :
    # render flipit.com home page when url www.flipit.com, http://www.flipit.com, flipit.com
    $flipitHomePage =
        FrontEnd_Helper_LayoutContent::loadFlipitHomePage($this->serverUrl());
    echo $flipitHomePage!='' ?
        $flipitHomePage['viewObject']->render($flipitHomePage['htmlPath']) : '';
    echo $flipitHomePage['htmlPath']!='' ? die : '';
endif;

echo $this->doctype("XHTML1_RDFA");

# manage the kc_session_active by checking the front_login session, we need this cookie for Varnish
$localeName = Signupmaxaccount::getLocaleName();
$countryLocale = !empty($localeName['locale']) ?
    $localeName['locale'] : 'nl_NL';
$locale = explode('_', $countryLocale);
$language = $locale[0];
?>

<html lang="<?php echo $language; ?>" xml:lang="<?php echo $language;?>" xmlns="http://www.w3.org/1999/xhtml">
<head>

<?php
if(isset($this->canonical)):
    $this->headLink(
        FrontEnd_Helper_LayoutContent::loadCanonical($this->canonical)
    );
endif;

if($this->serverUrl() == 'http://admin.kortingscode.nl') :
    $this->headMeta()->appendName('robots', 'noindex, nofollow');
    header("Location: http://admin.kortingscode.nl/admin");
else :
    $this->headMeta()->appendName(
        'robots',
        FrontEnd_Helper_LayoutContent::loadRobots(
            $this->param,
            $this->layout()->robotKeywords
        )
    );
endif;

echo $this->headTitle();
echo $this->layout()->customHeader ;
echo $this->headLink(FrontEnd_Helper_LayoutContent::loadFavicon());

# if not kortingscode.nl website then render simple meta phtml file else render for each locale by custom
if(LOCALE=='') :
    echo $this->render('fbmeta.phtml');
else:
    echo $this->render(
        FrontEnd_Helper_LayoutContent::loadFbMeta(
            $this->fbtitle,
            $this->fbshareUrl,
            $this->fbImg
        )
    );
endif;

echo $this->headMeta();
echo $this->render('layout_css.phtml');
echo $this->render('layout_js.phtml');

echo FrontEnd_Helper_LayoutContent::loadGoogleAnalyticsCode();
?>

</head>
<body>
    <div class="outerwrapper">
	    <!-- hidden field for apply selected class on menu -->
	    <input type="hidden" name='cName' id='cName' value='<?php echo strtolower($this->controllerName);?>'/>
	    <input type="hidden" name='aName' id='aName' value='<?php echo strtolower($this->action);?>'/>
	    <div class="nav-bg"></div>
	    <div class="innerwrapper">
<?php
$localePartialPath = APPLICATION_PATH . '/modules/'. LOCALE .'/views/' ;

$basePartialViewPath = new Zend_View();
$basePartialViewPath->setBasePath(APPLICATION_PATH . '/views/');

$localePartialViewPath = new Zend_View();
$localePartialViewPath->setBasePath($localePartialPath);

if(file_exists($localePartialPath .  'partials/_header.phtml')) :
    echo $localePartialViewPath->render('partials/_header.phtml');
else:
    echo $basePartialViewPath->render('partials/_header.phtml');
endif;
?>

        <div id="main" class="container">   

 <?php

if(file_exists($localePartialPath .  'partials/_top_nav.phtml')):
    echo $localePartialViewPath->render('partials/_top_nav.phtml');
else :
    echo $basePartialViewPath->render('partials/_top_nav.phtml');
endif;

echo $this->layout()->content;
?>
         </div>
<?php
if(file_exists($localePartialPath .  'partials/_footer.phtml')):
    echo $localePartialViewPath->render('partials/_footer.phtml');
else:
    echo $basePartialViewPath->render('partials/_footer.phtml');
endif;
?>
        </div>
    </div>
<?php
if(file_exists($localePartialPath . 'partials/_pop_up.phtml')):
    echo $localePartialViewPath->render('partials/_pop_up.phtml');
else :
    echo $basePartialViewPath->render('partials/_pop_up.phtml');
endif;
?>
	    
</body>
</html>
