<script type="text/javascript" src="/public/js/jquery-1.7.2.min.js"></script>
<?php
if (APPLICATION_ENV == 'development') {
    $headScript =  $this->HeadScript();
    $headScript->prependFile("/public/js/front_end/less/dist/less-1.7.0.js");
} else {
    $headScript = $this->minifyHeadScript();
}
$this->minifyHeadScript()
    ->prependFile("/public/js/common.js")
    ->prependFile("/public/js/front_end/jquery-bigtext.js");
if(LOCALE !='') :
    $this->minifyHeadScript()
        ->prependFile("/public/" . LOCALE ."/js/front_end/json/translation.js")
        ->prependFile("/public/" . LOCALE ."/js/front_end/json/shops.js");
else:
    $this->minifyHeadScript()
        ->prependFile("public/js/front_end/json/translation.js")
        ->prependFile("/public/js/front_end/json/shops.js");
endif;

    $headScript
    ->prependFile("/public/js/front_end/jquery.mmenu.min.js")
    ->prependFile("/public/js/front_end/jquery.main.js")
    ->prependFile("/public/js/front_end/layout.js")
    ->prependFile("/public/js/Gettext.js")
    ->prependFile("/public/js/jquery-ui-1.8.16.custom.min.js")
    ->prependFile("/public/js/front_end/jquery.validate.js")
    ->prependFile("/public/js/bootstrap.js")
    ->prependScript('var HOST_PATH_LOCALE = "'.  HTTP_PATH_LOCALE .'";');
