<?php
/*if(LOCALE !='') :
    $this->minifyHeadLink()->prependStylesheet("public/" .  LOCALE . "/css/style.css");
endif;

$this->minifyHeadLink()->prependStylesheet("public/css/placeholder_polyfill.css")
    ->prependStylesheet("public/css/bootstrap.min.css")
    ->prependStylesheet("public/css/bootstrap.css");
    
if(LOCALE !='') :
    $this->minifyHeadLink()->prependStylesheet("public/flipit/css/general_style.css");
endif;

echo $this->minifyHeadLink()->prependStylesheet("public/css/front_end/style.css");*/

?>

<link href='http://fonts.googleapis.com/css?family=Cookie' rel='stylesheet' type='text/css'>
<?php
if (APPLICATION_ENV == 'development') {
   $headLink =  $this->headLink();
} else {
   $headLink = $this->minifyHeadLink();
}
echo $this->headLink()->prependStylesheet("/public/css/front_end/all.css")
        ->prependStylesheet("/public/css/front_end/custom.css");


