<nav class="nav-mobile">
    <ul>
        <li>
            <strong class="title"><?php echo $this->translate('Discount suits'); ?></strong>
            <?php echo FrontEnd_Helper_layoutContent::generateMobileMenu('mobile'); ?>
        </li>
        <li>
            <strong class="title"><?php echo $this->translate('Account') ;?></strong>
            <?php
            if(Auth_VisitorAdapter::hasIdentity()) :
                echo $this->render('partials/_user_nav_logged_in.phtml');
            else :
                echo $this->render('partials/_user_nav.phtml');
            endif;
            ?>
        </li>
    </ul>
</nav>