<nav class="nav-mobile">
    <ul>
        <li>
            <strong class="title"><?php echo $this->translate('Discount suits'); ?></strong>
            <?php echo FrontEnd_Helper_layoutContent::generateMobileMenu(); ?>
        </li>
        <li>
            <strong class="title"><?php echo $this->translate('Account') ;?></strong>
            <?php echo $this->render('partials/_user_nav.phtml'); ?>
        </li>
    </ul>
</nav>