<!DOCTYPE html>
<html>
<?php echo $this->render('partials/_head.phtml'); ?>
<script type="text/javascript" src="/public/js/jquery-1.7.2.min.js"></script>
</head>
<body class="splash-page">
<?php
echo FrontEnd_Helper_LayoutContent::loadGoogleTagManager();
$serverNameScheme = FrontEnd_Helper_viewHelper::getServerNameScheme();
$mostPopularCoupon = FrontEnd_Helper_layoutContent::getMostPopularCouponOnEarth();
if (!empty($mostPopularCoupon['locale']) && !empty($mostPopularCoupon['mostPopularCoupon'])) {
    $countryName = FrontEnd_Helper_viewHelper::getCountryNameByLocale($mostPopularCoupon['locale']);
    $localeName =
        $mostPopularCoupon['locale'] == 'en'
            ? ''
            : $mostPopularCoupon['locale'].'/';
    $domainName =
        $mostPopularCoupon['locale'] == 'en'
            ? 'http://'.$serverNameScheme.'.kortingscode.nl/'
            : 'http://'.$serverNameScheme.'.flipit.com/'.$localeName;
    $offerPartial = new FrontEnd_Helper_OffersPartialFunctions();
    $daysTillOfferExpires =
        $offerPartial->getDaysTillOfferExpires($mostPopularCoupon['mostPopularCoupon'][0]['endDate']);
    $offerExpiryDate =
        $offerPartial->getOfferDates((object) $mostPopularCoupon['mostPopularCoupon'][0], $daysTillOfferExpires);
}
?>
<div id="wrapper">
    <div class="container">
        <div class="panel-box win-min-height">
            <strong class="logo-panel"><a href="http://<?php echo $serverNameScheme; ?>.flipit.com/"><h1>Changing the way we save</h1></a></strong>
            <span class="alt-text">CHoose RegioN:</span>
            <div id="selectedByIP" style="display:none;" class="region-box"></div>
            <div class="links-cols">
                <div class="row">
                    <div class="col-xs-6">
                        <strong class="title">ASIA</strong>
                        <ul>
                            <li><a href="http://www.flipit.com/in">India</a></li>
                            <li><a href="http://www.flipit.com/id">Indonesia</a></li>
                            <li><a href="http://www.flipit.com/my">Malaysia | Malasja</a></li>
                            <li><a href="http://www.flipit.com/sg">Singapore</a></li>
                        </ul>
                        <strong class="title">australia</strong>
                        <ul>
                            <li><a href="http://www.flipit.com/au">Australia</a></li>
                            <li><a href="http://www.flipit.com/nz">New Zealand</a></li>
                        </ul>
                        <strong class="title">NORTH AND SOUTH AMERICA</strong>
                        <ul>
                            <li><a href="http://www.flipit.com/br">Brazil | Brasil</a></li>
                            <li><a href="http://www.flipit.com/us">United States</a></li>
                        </ul>
                    </div>
                    <div class="col-xs-6">
                        <strong class="title">EUROPE</strong>
                        <ul>
                            <li><a href="http://www.flipit.com/be">Belgium | België</a></li>
                            <li><a href="http://www.flipit.com/dk">Denmark | Danmark</a></li>
                            <li><a href="http://www.flipit.com/fr">France</a></li>
                            <li><a href="http://www.flipit.com/de">Germany | Deutschland</a></li>
                            <li><a href="http://www.flipit.com/it">Italy | Italia</a></li>
                            <li><a href="http://www.kortingscode.nl">Netherlands | Nederland</a></li>
                            <li><a href="http://www.flipit.com/pl">Poland | Polska</a></li>
                            <li><a href="http://www.flipit.com/pt">Portugal</a></li>
                            <li><a href="http://www.flipit.com/es">Spain | España</a></li>
                            <li><a href="http://www.flipit.com/se">Sweden | Sverige</a></li>
                            <li><a href="http://www.flipit.com/ch">Switzerland | Schweiz</a></li>
                            <li><a href="http://www.flipit.com/no">Norway | Norge</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <?php
            if (!empty($mostPopularCoupon['locale']) && !empty($mostPopularCoupon['mostPopularCoupon'])) {
                ?>
                <span class="alt-text">Most Popular Coupon ON EARTH</span>
                <div class="sponsor-box">
                    <span class="image">
                        <a href="<?php echo $domainName.$mostPopularCoupon['mostPopularCoupon'][1]['permaLink']; ?>">
                            <img src="<?php echo PUBLIC_PATH_CDN.$localeName
                                .ltrim($mostPopularCoupon['mostPopularCoupon'][2]['path'], '/')
                                .'thum_medium_'
                                .$mostPopularCoupon['mostPopularCoupon'][2]['name']; ?>"
                                 alt="<?php echo $mostPopularCoupon['mostPopularCoupon'][2]['name'];?>"
                                 width="86" height="44" />
                        </a>
                    </span>
                    <div class="text-box">
                        <a href="<?php echo $domainName.$mostPopularCoupon['mostPopularCoupon'][1]['permaLink']; ?>">
                            <strong>Flipit
                                <?php echo $countryName; ?> -
                                <?php echo $mostPopularCoupon['mostPopularCoupon'][1]['name']; ?>
                            </strong>
                        </a>
                        <p><span class="mark"><?php echo 'Added: '.
                                    $mostPopularCoupon['mostPopularCoupon'][0]['startDate']->format('M d, Y').
                                    ', Expires on: '.
                                    $mostPopularCoupon['mostPopularCoupon'][0]['endDate']->format('M d, Y'); ?></span>
                            <?php echo $mostPopularCoupon['mostPopularCoupon'][0]['exclusiveCode'] != '' ?
                                '<span class="mark2">Exclusive</span>' : '' ; ?></p>
                        <a href="<?php echo $domainName.$mostPopularCoupon['mostPopularCoupon'][1]['permaLink']; ?>">
                            <?php echo $mostPopularCoupon['mostPopularCoupon'][0]['title']; ?></a>
                    </div>
                </div>
            <?php
            }
            ?>
        </div>
        <div class="bg-stretch">
            <img src="<?php echo PUBLIC_PATH;?>images/front_end/img-33.jpg" alt="img-33" />
        </div>
    </div>
</div>
<script type="text/javascript">

    $(function(){
        var availableLanguages = <?php echo json_encode(
                FrontEnd_Helper_viewHelper::getAllCountriesByLocaleNames('true')); ?>;

        $.get("http://ipinfo.io", function(response) {
            if(response.country.toLowerCase() in availableLanguages){

                var countryCode = response.country.toLowerCase(),
                    countryName = availableLanguages[countryCode];

                var countryUrl = '/'+countryCode;
                if(countryName == 'Netherlands') {
                    countryUrl = 'http://www.kortingscode.nl';
                }
                var htmlContent = '<span class="flag"><span class="country-flags '+ countryCode +'"></span></span>';
                htmlContent+= '<span class="text">Country Detected:  <a href="'+countryUrl+'">'+ countryName
                +'</a></span>';

                $('#selectedByIP').html(htmlContent).show();
            }

        }, "jsonp");

    });
</script>
<?php
if (APPLICATION_ENV == 'development') {
    $headScript =  $this->HeadScript();
    $headScript->prependFile("/public/js/front_end/less/dist/less-1.7.0.js");
} else {
    $headScript = $this->HeadScript();
}

echo $headScript
    ->prependFile("/public/js/front_end/jquery.main.js")
    ->prependFile("/public/js/bootstrap.js")
    ->prependScript('var HOST_PATH_LOCALE = "'.  HTTP_PATH_LOCALE .'";');
?>
</body>
</html>
