<!DOCTYPE html>
<html>
<?php echo $this->render('partials/_head.phtml'); ?>
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,600' rel='stylesheet' type='text/css'/>
<link type="text/css" media="all" rel="stylesheet" href="<?php echo HTTP_PATH;?>public/css/front_end/splash_page.css">
<script type="text/javascript" src="/public/js/jquery-1.7.2.min.js"></script>
</head>

<body class="inner">
<div id="wrapper">
<header id="header" class="header">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-5">
                <div class="logo"><a href="#"><img src="<?php echo PUBLIC_PATH;?>images/logo2.png" alt="Flipit Your online couponing portal" width="199" height="50"></a></div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-7 text-right">
                <span class="h-text"><a id="current-local" href=""></a></span>
            </div>
        </div>
    </div>
</header>
<main id="main" role="main">
<div class="banner" style="background-image:url(<?php echo PUBLIC_PATH;?>images/front_end/banner.jpg)">
    <div class="caption">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <form  action="" class="select-form">
                        <fieldset>
                            <label for="coutry">Select country! <span>We have 24.365 codes available in</span></label>
                            <div class="input-group">
                                <select class="present" data-jcf='{"wrapNative": false, "wrapNativeOnMobile": false}'>
                                    <option class="hideme">Select your country</option>
                                    <?php
                                    $languages = FrontEnd_Helper_viewHelper::getAllCountriesByLocaleNames('true');
                                    foreach ($languages as $lang_code => $lang_val) {
                                        echo '<option data-image-class="country-flags '.$lang_code.'" value="'.$lang_code.'">'.$lang_val.'</option>';
                                    }
                                    ?>
                                </select>
                                    <span class="input-group-btn">
                                        <button class="btn country-btn" type="submit">WEITERGEHEN</button>
                                    </span>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<section class="carousel container">
    <div class="row">
        <header class="col-xs-12">
            <h1>Our global trending coupons</h1>
        </header>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="mask">
                <div class="slideset">
                    <?php ?>
                    <div class="slide">
                        <img src="<?php echo PUBLIC_PATH;?>images/front_end/trading_coupon/slide-img1.jpg" alt="image description">
                        <div class="caption">
                            <div class="img-holder">
                                <a href="#"><img src="http://img.kortingscode.nl/public/images/upload/shop/thum_medium_1365695043_hema.png" alt="V & D"></a>
                            </div>
                            <div class="text-holder">
                                <p><strong class="persent"><a href="#">12% korting op jouw aankopen</a></strong></p>
                                <span class="flag">
                                    <a href="#">
                                        <img src="<?php echo PUBLIC_PATH;?>images/front_end/flags/flag_FR.jpg" alt="french-flag">
                                        <span class="country">Zalando</span>
                                    </a>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="slide">
                        <img src="<?php echo PUBLIC_PATH;?>images/front_end/trading_coupon/slide-img2.jpg" alt="image description">
                        <div class="caption">
                            <div class="img-holder">
                                <a href="#"><img src="http://img.kortingscode.nl/public/images/upload/shop/thum_medium_1365695043_hema.png" alt="V & D"></a>
                            </div>
                            <div class="text-holder">
                                <p><strong class="persent"><a href="#">12% korting op jouw aankopen</a></strong></p>
                                <span class="flag">
                                    <a href="#">
                                        <img src="<?php echo PUBLIC_PATH;?>images/front_end/flags/flag_FR.jpg" alt="french-flag">
                                        <span class="country">Zalando</span>
                                    </a>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="slide">
                        <img src="<?php echo PUBLIC_PATH;?>images/front_end/trading_coupon/slide-img3.jpg" alt="image description">
                        <div class="caption">
                            <div class="img-holder">
                                <a href="#"><img src="http://img.kortingscode.nl/public/images/upload/shop/thum_medium_1365695043_hema.png" alt="V & D"></a>
                            </div>
                            <div class="text-holder">
                                <p><strong class="persent"><a href="#">12% korting op jouw aankopen</a></strong></p>
                                <span class="flag">
                                    <a href="#">
                                        <img src="<?php echo PUBLIC_PATH;?>images/front_end/flags/flag_FR.jpg" alt="french-flag">
                                        <span class="country">Zalando</span>
                                    </a>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="slide">
                        <img src="<?php echo PUBLIC_PATH;?>images/front_end/trading_coupon/slide-img1.jpg" alt="image description">
                        <div class="caption">
                            <div class="img-holder">
                                <a href="#"><img src="http://img.kortingscode.nl/public/images/upload/shop/thum_medium_1365695043_hema.png" alt="V & D"></a>
                            </div>
                            <div class="text-holder">
                                <p><strong class="persent"><a href="#">12% korting op jouw aankopen</a></strong></p>
                                <span class="flag">
                                    <a href="#">
                                        <img src="<?php echo PUBLIC_PATH;?>images/front_end/flags/flag_FR.jpg" alt="french-flag">
                                        <span class="country">Zalando</span>
                                    </a>
                                </span>
                            </div>
                        </div>
                    </div>
                    <?php ?>
                </div>
            </div>
            <ul class="pagination">
            </ul>
            <a class="btn-prev" href="#"><span class="icon-chevron-small-left"></span></a>
            <a class="btn-next" href="#"><span class="icon-chevron-small-right"></span></a>
        </div>
    </div>
</section>
<article class="information-sec same-height">
    <div class="alignleft common-height">
        <div class="text-wrp">
            <h2>Flipit.com — your online couponing portal</h2>
            <p>Flipit is your tool of choice for saving money on your online shopping. We work closely with leading brands worldwide to bring you the best deals and discount codes available on the web.</p>
            <p>Now you’re here, you’re just a few clicks away from knocking a percentage or amount off your online order! It won’t cost you a thing and you don’t even need to register with us to take advantage of our great discounts. We check, verify and publish brand new voucher codes each and every day, so you can find a way to save money on your online purchase all year round.</p>
            <p>Simply select your country, search for your favourite brand, then click on your favourite deal to reveal your desired coupon code. When you’re ready, proceed to checkout and copy the voucher code from Flipit.com into the designated box, and enjoy your discount! Saving online really is that easy</p>
            <p>We hope you enjoy saving money with us!</p>
        </div>
    </div>
    <div class="img-block common-height" style="background-image:url(<?php echo PUBLIC_PATH;?>images/front_end/img.jpg)"></div>
</article>
<section class="popular-sec">
    <div class="container">
        <div class="row">
            <div class="col-xs-12"><h2>What’s  popular on Flipit.com?</h2></div>
        </div>
        <div class="row">
            <div class="col-xs-6 col-sm-4 col-md-2 col-lg-2">
                <h3>Singapore</h3>
                <ul class="list-unstyled">
                    <li><a href="<?php echo HTTP_PATH;?>sg/zalora">Zalora</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>sg/lazada-singapore">Lazada</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>sg/redmart">RedMart</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>sg/foodpanda">Foodpanda</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>sg/hotels-com">Hotels.com</a></li>
                </ul>

                <h3>Australia</h3>
                <ul class="list-unstyled">
                    <li><a href="<?php echo HTTP_PATH;?>au/groupon">Groupon</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>au/crazy-sales">CrazySales</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>au/get-glasses">Get Glasses</a></li>
                </ul>


            </div>
            <div class="col-xs-6 col-sm-4 col-md-2 col-lg-2">
                <h3>France</h3>
                <ul class="list-unstyled">
                    <li><a href="<?php echo HTTP_PATH;?>fr/aliexpress">Aliexpress</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>fr/kiabi">Kiabi</a></li>
                    <li><a href=<?php echo HTTP_PATH;?>fr/ms-mode">MS mode</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>fr/hema">HEMA</a></li>
                </ul>

                <h3>Indonesie</h3>
                <ul class="list-unstyled">
                    <li><a href="<?php echo HTTP_PATH;?>id/lazada">Lazada</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>id/bilna">Bilna</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>/id/blibli">Blibli</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>id/zalora">Zalora</a></li>
                </ul>
            </div>

            <div class="col-xs-6 col-sm-4 col-md-2 col-lg-2">
                <h3>Spain</h3>
                <ul class="list-unstyled">
                    <li><a href="<?php echo HTTP_PATH;?>es/kiabi">Kiabi.es</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>es/pc-componentes">PcComponentes</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>es/sportium">Sportium</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>es/casa-del-libro">Casa del Libro</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>es/vueling">Vueling</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>es/groupalia">Groupalia</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>es/rakuten-es">Rakuten</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>es/letsbonus">LetsBonus</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>es/descuentos-perfumes">PerfumesClub</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>es/promociones-farma">Promofarma</a></li>
                </ul>
            </div>
            <div class="col-xs-6 col-sm-4 col-md-2 col-lg-2">
                <h3>Denmark</h3>
                <ul class="list-unstyled">
                    <li><a href="<?php echo HTTP_PATH;?>dk/stylepit">Stylepit</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>dk/asos">ASOS</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>/dk/hotels-com">Hotels.com</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>dk/pixizoo">PixiZoo</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>dk/bona-parte">BON'A PARTE</a></li>
                </ul>
                <h3>Sweden</h3>
                <ul class="list-unstyled">
                    <li><a href="<?php echo HTTP_PATH;?>se/adidas">Adidas</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>se/miinto">Miinto</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>se/zoovillage">Zoovillage</a></li>
                </ul>
            </div>
            <div class="col-xs-6 col-sm-4 col-md-2 col-lg-2">
                <h3>Belgie</h3>
                <ul class="list-unstyled">
                    <li><a href="<?php echo HTTP_PATH;?>be/zalando">Zalando</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>be/bol-com">bol.com</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>be/collishop">ColliShop</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>be/albelli">Albelli</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>be/smartphoto">Smartphoto</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>be/hema">HEMA</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>be/sarenza">Sarenza</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>be/lensonline">LensOnline</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>be/center-parcs">Center Parcs</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>be/hellofresh">HelloFresh</a></li>
                </ul>
            </div>
            <div class="col-xs-6 col-sm-4 col-md-2 col-lg-2">
                <h3>New Zealand</h3>
                <ul class="list-unstyled">
                    <li><a href="<?php echo HTTP_PATH;?>nz/value-basket">Value Basket</a></li>
                    <li><a href="<?php echo HTTP_PATH;?>nz/mighty-ape">Mighty Ape</a></li>
                </ul>
                <h3>Netherlands</h3>
                <ul class="list-unstyled">
                    <li><a href="#">Forever 21</a></li>
                    <li><a href="#">Lane Bryant</a></li>
                    <li><a href="#">Venus</a></li>
                    <li><a href="#">Forever 21</a></li>
                    <li><a href="#">Lane Bryant</a></li>
                    <li><a href="#">Venus</a></li>
                </ul>
                <h3>Poland</h3>
                <ul class="list-unstyled">
                    <li><a href="#">Forever 21</a></li>
                    <li><a href="#">Lane Bryant</a></li>
                    <li><a href="#">Venus</a></li>
                </ul>
            </div>
        </div>
    </div>
</section>
<aside class="aside">
    <div class="container">
        <div class="row">
            <div class="col-xs-6 col-sm-3 col-md-3 col-lg-3 block">
                <span class="count">22</span>
                <p>countries</p>
            </div>
            <div class="col-xs-6 col-sm-3 col-md-3 col-lg-3 block">
                <span class="count">30 Million+</span>
                <p>vistors per year</p>
            </div>
            <div class="col-xs-6 col-sm-3 col-md-3 col-lg-3 block">
                <span class="count">40.000</span>
                <p>codes online</p>
            </div>
            <div class="col-xs-6 col-sm-3 col-md-3 col-lg-3 block">
                <span class="count">4</span>
                <p>continents</p>
            </div>
        </div>
    </div>
</aside>
</main>
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="qshopes-logo"><a href="#"><img src="<?php echo PUBLIC_PATH;?>images/logo-qshops.jpg" alt="Q shope keurmerk"></a></div>
                <nav class="add-nav">
                    <ul>
                        <li class="copy-right">&copy; 2009-<?php echo date('Y', time());?>  <a href="#">Flipit.com  -  Imbull.com, Inc</a>. All rights reserved</li>

                    </ul>
                </nav>
                <?php if (!isset($_COOKIE['cookie_agreement']) || empty($_COOKIE['cookie_agreement'])) { ?>
                    <div class="f-panel" id="footer-cookie-bar">
                        <?php echo FrontEnd_Helper_viewHelper::__translate('This site uses cookies ');?>
                        <a class="btn thanks-btn">
                            <strong><?php echo FrontEnd_Helper_viewHelper::__translate('Okay, thanks');?></strong>
                        </a>
                        <a class="txt-underline" href="sg/info/<?php echo FrontEnd_Helper_viewHelper::__link('link_privacy-cookies'); ?>"><?php echo FrontEnd_Helper_viewHelper::__translate('Find out more');?></a>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</footer>
</div>

<?php
if (APPLICATION_ENV == 'development') {
    $headScript =  $this->HeadScript();
    $headScript->prependFile("/public/js/front_end/less/dist/less-1.7.0.js");
} else {
    $headScript = $this->HeadScript();
}

echo $headScript
    ->prependFile("/public/js/bootstrap.js")
    ->prependFile("/public/js/coustom-select.js")
    ->prependFile("/public/js/carousel-slider.js")
    ->prependFile("/public/js/front_end/jquery.main.js")
    ->prependScript('var HOST_PATH_LOCALE = "'.  HTTP_PATH_LOCALE .'";');
?>

<script type="text/javascript">
    $(function(){
        var availableLanguages = <?php echo json_encode(
                FrontEnd_Helper_viewHelper::getAllCountriesByLocaleNames('true')); ?>;

        $.get("http://ipinfo.io", function(response) {
            if(response.country.toLowerCase() in availableLanguages){
                var countryCode = response.country.toLowerCase();
                var countryUrl = '/'+countryCode;
                if(countryCode == 'nl') {
                    countryUrl = 'http://www.kortingscode.nl';
                }
                var countryName = availableLanguages[countryCode];
                $("#current-local").attr('href', countryUrl).html("To Flipit.com "+ countryName);
                $('select.present').val(countryCode);
                jcf.refreshAll();
            }
        }, "jsonp");

        $('form.select-form').submit(function(e){
            e.preventDefault();
            countryCode = $('select.present').val();
            if (countryCode != '') {
                var countryUrl = '/'+countryCode;
                if(countryCode == 'nl') {
                    countryUrl = 'http://www.kortingscode.nl';
                }
                window.location.href = countryUrl;
            }
        });

        $(".thanks-btn").on("click", function() {
            var expiry = new Date();
            expiry.setFullYear(expiry.getFullYear() + 10);
            document.cookie = "cookie_agreement=1; expires=" + expiry.toGMTString();
            $('#footer-cookie-bar').remove();
        });
    });
</script>
</body>
</html>


