<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?php echo $this->translate('Kortingscode.nl');?></title>
        <link href="<?php echo PUBLIC_PATH ?>css/feeds/style.css" rel="stylesheet" type="text/css" />
    </head>
<body>
<div id="wrapper">
    <h1><?php echo $this->translate('Top 5 coupons'); ?></h1>
    <ul class="coupon">
<?php
$topPopularCouponCode = $this->topPopularCoupons;
$offerNumber = 1;
for ($couponCounter = 0; $couponCounter<count($topPopularCouponCode); $couponCounter++):
    $couponImage = PUBLIC_PATH_CDN.ltrim($topPopularCouponCode[$couponCounter]['path'], "/") .'thum_small_'. $topPopularCouponCode[$couponCounter]['name'];

    if ($topPopularCouponCode[$couponCounter]['shopName'] != '') :
        $couponTitle = $topPopularCouponCode[$couponCounter]['shopName'];

        if (mb_strlen($topPopularCouponCode[$couponCounter]['shopName'], 'UTF-8') > 15) :
            $couponTitle = mb_substr($topPopularCouponCode[$couponCounter]['shopName'], 0,15,  'UTF-8')."...";
        endif;
    endif;

    $couponContent = $topPopularCouponCode[$couponCounter]['title'];

    if(mb_strlen($topPopularCouponCode[$couponCounter]['title'], 'UTF-8') > 45):
        $couponContent = mb_substr($topPopularCouponCode[$couponCounter]['title'], 0, 45, 'UTF-8').'...';
    endif;
    ?>
    <li>
        <a href="<?php echo HTTP_PATH_LOCALE.$topPopularCouponCode[$couponCounter]['permaLink'];  ?>" class="coupon-image" target="_blank">
            <img  src="<?php  echo $couponImage; ?>" alt="<?php echo $topPopularCouponCode[$couponCounter]['shopName'];?>" width="70" height="36" title="<?php echo $topPopularCouponCode[$couponCounter]['shopName'];?>" >
        </a>
        <div class="coupon-content">
        <h1 class="title">
        <a class="text-blue-link" target="_blank" href="<?php echo HTTP_PATH_LOCALE.$topPopularCouponCode[$couponCounter]['permaLink'];  ?>">
        <span class="coupon-number">
        <p>
    <?php
    echo $offerNumber;
    ?>
        </p>
        </span> 
    <?php
    echo $couponTitle;
    ?>
    <?php
    if($topPopularCouponCode[$couponCounter]['exclusivecode'] == 1):
        ?>   
        <span class="exclusive"><?php echo $this->translate('Exclusive'); ?></span>
        <?php
    endif;
    ?>
        </a>
        </h1>
        <p class="content">
            <a href="<?php echo HTTP_PATH_LOCALE.$topPopularCouponCode[$couponCounter]['permaLink'];  ?>" target="_blank">
    <?php
    echo $couponContent;
    ?>
            </a>
        </p>
        </div>
    </li> 
    <?php
    $offerNumber++;
endfor;
?>
    </ul>
</div>
</body>
</html>