<?php

/**
 * AboutTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AboutTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AboutTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('About');
    }
}
