<?php
/**
 * Chain
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##Er.kundal## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Chain extends BaseChain
{
    ######### refactored code #################
    public static function updateChainItemLocale($newLocale, $oldLocale)
    {
        Doctrine_Query::create()
            ->update('ChainItem')
            ->set("locale", '"'.$newLocale.'"')
            ->where("locale = "."'".$oldLocale."'")
            ->execute();
        return true;
    }
    ######### end refactored code #################
     /**
      *  saveChain
      *
      *  save a new chain into data base
      *  @param object $request requets object
      *  @author sp singh
      */
      public function saveChain($request)
      {
            $name = $request->getParam('name' , false);
            $website = $request->getParam('locale' , false);

            if($name) {
                try {

                    $this->name = $name ;
                    $this->save();
                    return true ;

                } catch (Exception $e) {

                    return  false ;
                }
            } else {
                return false ;
            }
      }

    /**
    * returnChainList
    *
    * return  all chains from data base
    *
    * @return array chain list for dattable.js date feed
    */
    public static function returnChainList($params)
    {

        $srh =  @$params["searchText"] != 'undefined' ? @$params["searchText"] : '';

        $chainList = Doctrine_Query::create ()
        ->select ("c.name")
        ->from ( "Chain c")
        ->addSelect("(SELECT count(ci.id) FROM ChainItem ci WHERE ci.chainId = c.id ) as totalShops")
        ->where("c.name LIKE ?", "$srh%");


        $list = DataTable_Helper::generateDataTableResponse($chainList,
        $params,array("__identifier" => 'c.id', 'name', 'totalShops'),
        array(),array());

        return $list;
    }


    /**
     * deleteChain
     *
     * delete chain and chains items
     * @param integer $id chain id
     * @return boolean true on delete otherwise false
     */
    public static function deleteChain($id)
    {
        try {

            $chain = Doctrine_Core::getTable("Chain")->find($id);
            $chain->delete();

            return true ;
        } catch (Exception $e) {

            return false;
        }

    }

    /**
     * execute before deletion of a chain and
     * will update varnish for this particular chain items
     *
     * @see Doctrine_Record::preDelete()
     */
    public function preDelete($event)
    {
        $chainItem = new ChainItem();
        $chainItem->updateVarnish($this->id);
        $chainItem->free(true);
    }


    /**
     * returnChainDetail
     *
     * @param integer $id chain id
     * @return array return chain detail
     */
    public static function returnChainDetail($id)
    {
        try {
            return Doctrine_Core::getTable("Chain")->find($id)->toArray();
        } catch (Exception $e) {

            return false;
        }

    }


    /**
    * returnChainData
    *
    * return  all chains items data for shop page
    *
    * @param integer $id chain id to retrieve all chain item
    * @param integer $shopId shop if on which chain is being rendered
    * @return array
    */
    public static function returnChainData($chainItemId,$shopId)
    {


        $pattern = "~((?:.+://|)(?:www.|))(flipit.com/[a-z]{2}|kortingscode.nl)~";

        $subject = trim(HTTP_PATH_LOCALE,'/');

        $replacement = '$2';
        $curSite = preg_replace($pattern, $replacement, $subject);


         $chainData = Doctrine_Query::create ()
            ->select("c.name,ci.shopName,ci.permalink,w.name,w.url,ci.locale as locale,ci.shopId as shopId")
            ->from ( "Chain c")
            ->leftJoin("c.chainItem ci")
            ->leftJoin("ci.website w")
            ->where("c.id = (SELECT cii.chainId FROM ChainItem cii where cii.id = ?)", $chainItemId)
            ->andWhere("ci.status = 1")
            ->orderBy("w.name ASC")
            ->fetchArray();

        $chain = array();

        if(! @ $chainData[0]) {
            return false ;
        }


        $chainData = $chainData[0];

        foreach ($chainData['chainItem'] as $value) {

            # fetch chain detail

            $locale = explode('_' , $value['locale']);
            $locale = isset($locale[1]) ? $locale[1] : 'nl';


             $hrefLocale = isset($value['locale']) ? $value['locale'] : 'nl_NL';

             $hrefLang = preg_replace( '~_~' , '-' ,$hrefLocale ) ;

            $url  = $value['website']['url'] . '/' . $value['permalink'] ;

            $headLink = sprintf('<link rel="alternate" hreflang="%s" href="%s"/>',
                                    $hrefLang, $url );

            $shop = array();

            # remove current site from chain list
            if($value['website']['name'] != $curSite || $shopId != $value['shopId']) {

                $shop = array( 'name' => $chainData['name'],
                                'shop' => $value['shopName'],
                                'locale' => strtoupper( $locale) ,
                                'url' => $url);
            }


            $chain[] = array( 'shops' => $shop,'headLink' => $headLink );
        }

        return $chain;
    }


    /**
    * get top five chains
    * @param string $keyword
    * @return array $data
    *
    */
    public static function searchChain($keyword)
    {
        $data = Doctrine_Query::create()->select('c.name as name')
                                        ->from("Chain as c")
                                        ->andWhere("c.name LIKE ?", "$keyword%")
                                        ->orderBy("c.name ASC")
                                        ->limit(5)->fetchArray();
            return $data;
    }

}
