<?php

/**
 * DefaultPageTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DefaultPageTable extends PageTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DefaultPageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DefaultPage');
    }
}
