<?php

/**
 * SpecialListTable
 * author Amit Sharma
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmailSettingsTable extends Doctrine_Table
{
    /**
     * get all data of table
     * @version 1.0
     * @return array $data
     * @author asharma
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('emailsettings');
    }
}
