<?php

/**
 * Email subscriber...
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Emailsubscribe extends BaseEmailsubscribe
{
    public static function add_emailsubscriber($email)
    {
        $data = new Emailsubscribe();
        $data->email=$email;
        $data->send=0;
        $data->save();
    }
}
