<?php

/**
 * Footer
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Footer extends BaseFooter
{


    /**
     *  @return mixed footer content array or false if doesn't exists!
     */
    public static function getFooterContent()
    {

        $retVal = self::checkFooterContent() ;

        if($retVal) {
            # create object of previous data

            $footer = Doctrine_Core::getTable("Footer")
                    ->findOneBy( "id" , $retVal)->toArray() ;

            return $footer ;
        }

        return false ;

    }

    /**
    *
    * @param array request array  saving footer
    * @return integer id
    */
    public static function update($params)
    {


        $retVal = self::checkFooterContent() ;


        # check if it has integer id of footer

        $footer = Doctrine_Core::getTable("Footer")->find($retVal) ;
        if(!$retVal) {

            $footer = new Footer();
            $footer->id = 2;
        }


        $footer->topFooter = BackEnd_Helper_viewHelper::removeScriptTag($params['topFooter']);
        $footer->middleColumn1 = BackEnd_Helper_viewHelper::removeScriptTag($params['column1']);
        $footer->middleColumn2 = BackEnd_Helper_viewHelper::removeScriptTag($params['column2']);
        $footer->middleColumn3 = BackEnd_Helper_viewHelper::removeScriptTag($params['column3']);
        $footer->middleColumn4 = BackEnd_Helper_viewHelper::removeScriptTag($params['column4']);
        $footer->bottomFooter = BackEnd_Helper_viewHelper::removeScriptTag($params['bottomFooter']);
        $footer->save();

        //self::checkFooterContent();

        //call cache function
        FrontEnd_Helper_viewHelper::clearCacheByKeyOrAll('all_footer_page');
        return $footer->id ;

    }

    /**
    * check footer is exist or not
    * by geetings its setting value
    * @return mixed setting value or false
    */
    public static function checkFooterContent()
    {
        $id = Settings::getSettings(Settings::FOOTER );
        if($id!=2) {
            self::newFooterSetting(2);
            return 2;
        } else {

            return $id;
        }

    }
    /**
    *  save new footer settings
    *  @param $id integer footer id
    */
    public static function newFooterSetting($id)
    {

        $settings =  new Settings();
        $settings->name =  Settings::FOOTER ;
        $settings->value = $id ;
        $settings->save();
        //call cache function
        FrontEnd_Helper_viewHelper::clearCacheByKeyOrAll('all_footer_page');
    }

    /**
     *  Author Raman
     *  Get footer content
     *	Version: 1.0
     */
    public static function getFooter()
    {
        $data = Doctrine_Query::create()
        ->select('f.id,f.topfooter,f.middleColumn1,f.middleColumn2, f.middleColumn3, f.middleColumn4, f.bottomFooter')
        ->from('Footer f')
        ->where('f.deleted=0' )
        ->limit(1)->fetchArray();
        return $data;
    }

}
