<?php

/**
 * GlobalExportPasswordTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GlobalExportPasswordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GlobalExportPasswordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GlobalExportPassword');
    }
}
