<?php

/**
 * Logo
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Logo extends BaseLogo
{
    #################################################
    ########### REFACTORED CODE #####################
    #################################################
    public static function getPageLogo($logoId)
    {
        $pageLogo = Doctrine_Query::create()->select()
        ->from('logo l')
        ->where("l.id = ?", $logoId)
        ->fetchArray();
        return $pageLogo;
    }
    #################################################
    ########### END REFACTORED CODE #################
    #################################################
}
