<?php

/**
 * PageAttribute
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class PageAttribute extends BasePageAttribute
{

	
	public function __contruct($connName = false)
	{
		if(! $connName)
		{
			$connName = "doctrine_site" ;
		}
	
		Doctrine_Manager::getInstance()->bindComponent($connName, $connName);
	
	}
	
	
	function getPageAttributes(){
		$attrList = Doctrine_Query::create()
		            ->select()->from('pageAttribute')->fetchArray();
		return  $attrList;
	}
}