<?php

/**
 * ProfileImageTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileImage');
    }
}
