<?php

/**
 * refUserWebsiteTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class refUserWebsiteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object refUserWebsiteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('refUserWebsite');
    }
}
