<?php

/**
 * ShopTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShopTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Shop');
    }
}
