<?php

/**
 * Signupfavoriteshop
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Signupfavoriteshop extends BaseSignupfavoriteshop
{
    /**
     * Search favorite shops and store data required from shop
     * @param string $keyword
     * @param boolean $flag
     * @version 1.0
     * @return array $data
     * @author sunny patial
     */

    public static function getalladdstore()
    {
        $data = Doctrine_Query::create()
        ->select('p.id,p.entered_uid,p.store_id,p.created_at,s.name,s.id,l.path,l.name as image')
        ->from("Signupfavoriteshop p")
        ->leftJoin('p.shop s')
        ->leftJoin('s.logo l')
        ->where("p.store_id=s.id")
        ->andwhere('s.deleted=0')
        ->andwhere('s.status=1')
        ->orderBy("s.name ASC")->fetchArray();
        return $data;

        /*
            $data = Doctrine_Query::create()
        ->select('p.id,p.entered_uid,p.store_id,p.created_at')
        ->from('Signupfavoriteshop p')
        ->orderBy('p.store_id ASC')->fetchArray();
        return $data;*/
    }
    public static function deletestorebyid($id)
    {
        if($id){
            //delete particular code from list
            $pc = Doctrine_Query::create()->delete('Signupfavoriteshop')
            ->where('id=' . $id)->execute();
            //call cache function
            FrontEnd_Helper_viewHelper::clearCacheByKeyOrAll('all_signupfavoriteshop_list');
        }
    }
    public static function addcode($codetext)
    {
        if($codetext){
            $code = new AccountsettingCode(); // A Doctrine Model with timestampable behavior enabled
            $code->entered_uid = 2;
            $code->code = "$codetext";
            $code->save();
            //call cache function
            FrontEnd_Helper_viewHelper::clearCacheByKeyOrAll('all_signupfavoriteshop_list');
        }
    }
    public static function addshop($name,$userid,$shopid)
    {
        $pc = new Signupfavoriteshop();
        $pc->entered_uid =$userid;
        $pc->store_id = $shopid;
        if($pc->save()) {
            $flag = $pc->toArray();
        } else{
            return false;
        }
        //call cache function
        FrontEnd_Helper_viewHelper::clearCacheByKeyOrAll('all_signupfavoriteshop_list');
    /*	$Shop = Doctrine_query::create()->from('Shop')
        ->where('name=' . "'$name'")->limit(1)->fetchArray();
        if($Shop[0]['id']>0) {
            $pc = new Signupfavoriteshop();
            $pc->entered_uid =$userid;
            $pc->store_id = $Shop[0]['id'];
            if($pc->save()) {
            $flag = $pc->toArray();
            } else{
                return false;
            }
        }
    */
    }
    public static function searchTopTenShops($keyword, $flag)
    {
        $lastdata=Signupfavoriteshop::getalladdstore();
        if(sizeof($lastdata)>0){
        for($i=0;$i<sizeof($lastdata);$i++){
            $shopdata[$i]=$lastdata[$i]['store_id'];
        }
        $shopvalues=implode(",", $shopdata);
        $data = Doctrine_Query::create()->select('s.name as name,s.id as id')
        ->from("Shop s")->where('s.deleted= ?' , $flag )->andWhere("s.status= ?",1)
        ->andWhere("s.name LIKE ?", "$keyword%")->andWhere("s.id NOT IN ($shopvalues)")->orderBy("s.name ASC")
        ->limit(10)->fetchArray();
        } else{
            $data = Doctrine_Query::create()->select('s.name as name,s.id as id')
            ->from("Shop s")->where('s.deleted= ?' , $flag )->andWhere("s.status= ?",1)
            ->andWhere("s.name LIKE ?", "$keyword%")->orderBy("s.name ASC")
            ->limit(10)->fetchArray();
        }
        return $data;

    }
}
