<?php

/**
 * TermAndConditionTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TermAndConditionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TermAndConditionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TermAndCondition');
    }
}
