<?php

/**
 * ViewCountTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ViewCountTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ViewCountTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ViewCount');
    }
}
