<?php

/**
 * Website
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Website extends BaseWebsite
{
	
	
	/**
	 * getAllwebSites
	 * 
	 * returns all running websites for chain
	 * @return array
	 * @author sp singh
	 */
	public static function getAllwebSites()
	{
		$websites = Doctrine_Query::create()->select("id,name")
					->from("Website")
					->where("deleted=0")
					->fetchArray();
		return BackEnd_Helper_viewHelper::msort($websites,"name",array("kortingscode.nl") );
	} 
	
	/**
	 * getWebsiteDetail
	 * 
	 * return website detail
	 * @param integer  $id website id
	 * @param string $name website name
	 */
	public static function getWebsiteDetail($id = null,$name = null)
	{
		$id =  FrontEnd_Helper_viewHelper::sanitize($id);
		
		$websites = Doctrine_Query::create()->select("id,name,url")
						->from("Website")
						->where("deleted=0");
		
		if($name)
		{
			$websites->andWhere("name = ? ", $name);
		}else{
			
			$websites->andWhere("id = ? ", $id);
		}
		
		return  $websites->fetchOne(null,Doctrine::HYDRATE_ARRAY);
		
	} 
	

	 
	
}