<?php
$backEndHelper = new BackEnd_Helper_viewHelper();
$widgetLocations  = $backEndHelper->getWidgetLocationsByPageType($this->pageType, $this->relatedId);
$widgetLocation = 'global';
if (!empty($this->relatedId)) {
    $widgetLocation = 'individual';
}
$widgetPosition = \KC\Repository\WidgetLocation::getWidgetPosition($this->pageType, $widgetLocation, $this->relatedId);
?>
<div class="modal display-none popup-width" id="modalForWidgetLocation" tabindex="1" role="dialog" aria-labelledby="myModalLabel" 
    aria-hidden="true">
    <div class="wrap columns-2">
        <form name="widgetlocationForm" id="widgetlocationForm" method="post" 
            action="<?php echo HTTP_PATH ?>admin/widgetlocation/save-widget-location">
            <div class="m-item-popup-hdr">
                <?php echo $this->translate('backend_News letter Subscribe widget location');?>
            </div>
            <div id="poststuff" class="metabox-holder has-right-sidebar">
                <div class="" id='message-display'></div>
                <input type="hidden" name="relatedId" id="relatedId" value="<?php echo $this->relatedId;?>"/>
                <input type="hidden" name="pageType" id="pageType" value="<?php echo $this->pageType;?>"/>
                <div id="post-body">
                    <div class="mainpage-content-line">
                        <div class="mainpage-content-left">
                            <label>
                                <strong><?php echo $this->translate('backend_Widget Location');?></strong>
                            </label>
                        </div>
                        <div class="mainpage-content-right-inner-right-other display-none"></div>
                        <div class="mainpage-content-right">
                            <select onchange="showWidgetPosition()" name='widgetLocation' id='widgetlocation'>
                                <?php 
                                foreach ($widgetLocations as $widgetLocationIndex => $widgetLocation) {
                                   echo "<option value='". $widgetLocationIndex ."'>". $widgetLocation. "</option>";
                                }?>
                            </select>
                        </div>
                    </div> 
                    <div class="mainpage-content-line">
                        <div class="mainpage-content-left">
                            <label>
                                <strong><?php echo $this->translate('backend_Widget Position');?></strong>
                            </label>
                        </div>
                        <div class="mainpage-content-right-inner-right-other display-none"></div>
                        <div class="mainpage-content-right">
                            <input type="text" 
                                placeholder="<?php echo $this->translate('backend_Widget Position');?>" 
                                class="span3" name="widgetPostion" id="widgetPostion" 
                                value='<?php echo $widgetPosition;?>'>
                        </div>
                    </div> 
                </div>
                <br class="clear">
            </div>
            <div class="m-item-popup-btm">
                <button id="submitButton" class="btn btn-large btn-primary fl export-submit-btn" type="submit">
                    <?php echo $this->translate('backend_Submit');?>
                </button> 
                <button type='button' class="btn ml10 m5" onclick="hideModel();">
                    <?php echo $this->translate('backend_Cancel');?>
                </button>
            </div>
        </form>
    </div>
</div>