<body>
<p><?php 
	echo FrontEnd_Helper_viewHelper::__email('Hi') .' ' .$this->name; ?>,</p>
<p><?php echo FrontEnd_Helper_viewHelper::__email('Your password has been reset as per your request on our website');?><?php echo $this->host; ?></p>
<p><?php echo FrontEnd_Helper_viewHelper::__email('Your new password is:');?><strong><?php echo $this->pwd; ?></strong> </p>
<br/>
<p><?php echo FrontEnd_Helper_viewHelper::__email('Regards');?>,<br/><?php echo FrontEnd_Helper_viewHelper::__email('Kortingscode Team')?></p>

</body>
