<div class="wrap columns-2">
    <form name="splashImageForm" id="splashImageForm" enctype="multipart/form-data" method="post">
        <div class="m-item-popup-hdr">Upload Featured Image</div>
        <div class="metabox-holder has-right-sidebar" id="poststuff">
            <div id="post-body">
                <div class="mainpage-content-line">
                    <div class="mainpage-content-left"><label><strong>Select Image</strong></label></div>
                    <div class="mainpage-content-right-inner-right-other display-none"></div>
                    <div class="mainpage-content-right">
                        <input type="file" id="featuredImage" class="span3 margin-bottom-tenpx" name="featuredImage">
                    </div>
                </div>
            </div>
            <br class="clear">
        </div>

        <div class="m-item-popup-btm">
            <button type="submit" class="btn btn-large btn-primary fl" id="submitUploadBtn" value="">Upload</button>
            <button data-dismiss="modal" class="btn ml10 m5" value="">Cancel</button>
        </div>
    </form>
</div>