<?php 
$this->headTitle()->append($this->translate('Add Offer'));
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/splash-management.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/select2.min.js");
?>
<div class="wrap columns-2" id="addNewKeyword">
    <h1><?php echo $this->translate('Add Offer'); ?>
        <button class="btn ml10" type="button" onClick="window.location.href='<?php echo HTTP_PATH ;?>admin/splash'"><?php echo $this->translate('Cancel'); ?>
        </button>
    </h1>
    <form method="post" id="addOfferForm" >
        <div class="mainpage-content mb300">
            <div class="mainpage-content-line mb10">
                <div class="mainpage-content-left">
                    <label><strong><?php echo $this->translate('Locale'); ?></strong></label>
                </div>
                <div class="mainpage-content-right oveflow-hidden">
                    <div class="mainpage-content-right-inner-left-other fl oh">
                        <?php 
                            echo $this->locale['0']['locale'] ;
                        ?>
                        <select name ="locale" id='locale' class='select-width' onchange="updateShops(this);" >
                            <option selected="selected" disabled="disabled" value="0"><?php echo $this->translate('Select website');?>
                            </option>       
                                <?php
                                    $websites = $this->websites ;
                                    if($websites) :
                                            foreach($websites as $website):
                                                echo "<option value=". $website['id'] .">". $website['name'] ."</option>";
                                            endforeach;
                                    endif;
                                ?>
                        </select>
                    </div>
                    <div class="mainpage-content-right-inner-right-other focus error">
                        <span for="locale" class="error help-inline"></span>
                    </div>
                </div>
            </div>
            <div  class="mainpage-content-line mb10">
                <div class="mainpage-content-left">
                    <label>
                        <strong><?php echo $this->translate('Shop'); ?></strong>
                    </label>
                </div>
                <div class="mainpage-content-right">
                    <div class="fl">
                        <input type='hidden' id="searchShops" value="" name="searchShops" class='select-width'/>
                        <input type='hidden' id="searchShopsId" value="" name="searchShopsId"/>
                    </div>
                    <div class="mainpage-content-right-inner-right-other focus error">
                        <span for="offerName" class="error help-inline"></span>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="mainpage-content-right-inner-right-other focus error">
                    <span for="searchShopsId" class="error help-inline"></span>
                </div>
            </div>
            <div  class="mainpage-content-line mb10">
                <div class="mainpage-content-left">
                    <label>
                        <strong><?php echo $this->translate('Offers'); ?></strong>
                    </label>
                </div>
                <div class="mainpage-content-right">
                    <div class="fl">                   
                        <input type='hidden' id="searchOffers" value="" name="offerName" class='select-width' />
                        <input type='hidden' id="searchOfferId" value="" name="searchOfferId" />
                    </div>  
                    <div class="mainpage-content-right-inner-right-other focus error">
                        <span for="offerName" class="error help-inline"></span>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="mainpage-content-right-inner-right-other focus error">
                    <span for="offerName" class="error help-inline"></span>
                </div>
            </div>
            <div class="clear"></div>
            <div class="mainpage-content-colorbox">
                <button id="updateseenIdButton" type="submit" class="btn btn-large btn-primary fl" value="chain" name="form"><?php echo $this->translate('SAVE Offer'); ?>
                </button>
                <a class="fl m10" href="<?php echo HTTP_PATH ;?>admin/splash">
                    <strong><?php echo $this->translate('CANCEL'); ?></strong>
                </a>
            </div>
        </div>
    </form> 
</div>