<?php 
 $this->headMeta('keyword', 'Description');
 $this->headTitle()->append($this->translate('Splash Images'));
 $this->headScript ()->appendFile ( PUBLIC_PATH . "js/jquery.dataTables.min.js" );
 $this->headScript ()->appendFile ( PUBLIC_PATH . "js/dataTableComman.js" );
 $this->headScript ()->appendFile ( PUBLIC_PATH . "js/jquery.dataTables.rowReordering.js" );
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/splashImages.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
 $this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/jquery-ui-1.8.16.custom.css" );
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
?>
<form method="post" action="<?php echo HTTP_PATH ;?>admin/splash/image-reorder">
<div id="chainList">
    <div class="top_navigation">
        <ul>
            <li><a href="/admin/splash/page">Splash Page</a></li>
            <li><a href="/admin/splash">Splash Offers </a></li>
            <li><a href="/admin/splash/images" class="selected_nav">Featured Images </a></li>
        </ul>
    </div>
    <div class="clear"></div>
    <div class="wrap columns-2">
        <?php echo $this->flashMessages(); ?>
        <h1 class="fl"><?php echo $this->translate('Featured Images'); ?>
            <button class="btn ml10 btn-primary" type="button" onClick="window.location.href='<?php echo HTTP_PATH ?>admin/splash/upload-featured-image'"><?php echo $this->translate('Upload New Image'); ?></button>
        </h1>
        <div class="clear"></div>
        <table class="table table-bordered table-striped"  cellpadding="0" cellspacing="0" id="splash-image-table">
            <thead>
                <tr>
                    <th>#</th>
                    <th><?php echo $this->translate('Image'); ?></th>
                    <th><?php echo $this->translate('Action'); ?></th>
                </tr>
            </thead>
            <?php if( true == !empty($this->splashImages)):
                $row = 1;
                foreach($this->splashImages as $splashImage): ?>
                    <tr id="row_<?php echo $splashImage->getId(); ?>" data-position="<?php echo $row; ?>">
                        <td><?php echo $row; ?></td>
                        <td><input type="hidden" name="splashOffers[]" value="<?php echo $splashImage->getId(); ?>">
                            <img class='image-container mb10' src="<?php echo PUBLIC_PATH . 'images/front_end/trading_coupon/' . $splashImage->getImage(); ?>" height="90" width="100">
                        </td>
                        <td><button class="btn ml10" type="button" onClick="window.location.href='<?php echo HTTP_PATH ?>admin/splash/delete-image/id/<?php echo $splashImage->getId(); ?>'"><?php echo $this->translate('Delete'); ?></button></td>
                    </tr>
                <?php $row++; endforeach; ?>
            <?php endif; ?>
        </table>
    </div>
</div>
<div class="clear"></div><br>
<div id="save-order-section" style="display:none;">
    <button class="btn btn-large btn-primary fl" type="submit">SAVE ORDER</button>
    <a onclick="window.location.href='<?php echo HTTP_PATH ;?>admin/splash/images'" href="javascript:void(0);" class="fl m10"><strong>CANCEL</strong></a>
</div>
</form>