<?php 
 $this->headMeta('keyword', 'Description');
 $this->headTitle()->append($this->translate('Splash Offer management'));
 $this->headScript ()->appendFile ( PUBLIC_PATH . "js/jquery.dataTables.min.js" );
 $this->headScript ()->appendFile ( PUBLIC_PATH . "js/dataTableComman.js" );
 $this->headScript ()->appendFile ( PUBLIC_PATH . "js/jquery.dataTables.rowReordering.js" );
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/splash-management.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
 $this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/jquery-ui-1.8.16.custom.css" );
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
?>
<form method="post" action="<?php echo HTTP_PATH ;?>admin/splash/reorder">
<div id="chainList">
    <div class="top_navigation">
        <ul>
            <li><a href="/admin/splash/page">Splash Page</a></li>
            <li><a href="/admin/splash">Splash Offers </a></li>
            <li><a href="/admin/splash/images" class="selected_nav">Featured Images </a></li>
        </ul>
    </div>
    <div class="clear"></div>
    <div class="wrap columns-2">
        <?php echo $this->flashMessages(); ?>
        <h1 class="fl"><?php echo $this->translate('Splash Offers'); ?>
            <button class="btn ml10 btn-primary" type="button" onClick="window.location.href='<?php echo HTTP_PATH ?>admin/splash/upload-featured-image'"><?php echo $this->translate('Upload New Image'); ?></button>
        </h1>
        <div class="clear"></div>
        <table class="table table-bordered table-striped"  cellpadding="0" cellspacing="0" id="splash-offer-table">
            <thead>
                <tr>
                    <th>#</th>
                    <th><?php echo $this->translate('Image'); ?></th>
                    <th><?php echo $this->translate('Action'); ?></th>
                </tr>
            </thead>
            <?php if( true == !empty($this->splashOffersData)):
                $row = 1;
                foreach($this->splashOffersData as $splashOffer): ?>
                    <tr id="row_<?php echo $splashOffer['id']; ?>" data-position="<?php echo $row; ?>">
                        <td><?php echo $row; ?></td>
                        <td><input type="hidden" name="splashOffers[]" value="<?php echo $splashOffer['id']; ?>"><?php echo $splashOffer['offer']; ?></td>
                        <td><button class="btn ml10" type="button" onClick="window.location.href='<?php echo HTTP_PATH ?>admin/splash/delete-offer/id/<?php echo $splashOffer['id']; ?>'"><?php echo $this->translate('Delete'); ?></button></td>
                    </tr>
                <?php $row++; endforeach; ?>
            <?php endif; ?>
        </table>
    </div>
</div>
<div class="clear"></div><br>
<div id="save-order-section" style="display:none;">
    <button class="btn btn-large btn-primary fl" type="submit" id="publishShopButton">SAVE ORDER</button>
    <a onclick="window.location.href='<?php echo HTTP_PATH ;?>admin/splash'" href="javascript:void(0);" class="fl m10"><strong>CANCEL</strong></a>
</div>
</form>