<?php 
 $this->headMeta('keyword', 'Description');
 $this->headTitle()->append($this->translate('Splash Offer management'));
 $this->headScript ()->appendFile ( PUBLIC_PATH . "js/jquery.dataTables.min.js" );
 $this->headScript ()->appendFile ( PUBLIC_PATH . "js/dataTableComman.js" );
 $this->headScript ()->appendFile ( PUBLIC_PATH . "js/jquery.dataTables.rowReordering.js" );
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/splash-management.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
 $this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/jquery-ui-1.8.16.custom.css" );
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
?>
<form method="post" action="<?php echo HTTP_PATH ;?>admin/splash/reorder">
<div id="chainList">
    <div class="wrap columns-2">
        <?php echo $this->flashMessages(); ?>
        <?php if(count($this->splashOffersData)>8): ?>
        <div style="margin-top:14px; padding-top: 5px; padding-bottom: 5px; text-align: center;" class="alert alert-info"><label class="successserver">Maximum splash page offer limit reached, you cannot add more offers to splash page.</label></div>
            <h1 class="fl"><?php echo $this->translate('Splash Offers'); ?></h1>
        <?php else: ?>
        <h1 class="fl"><?php echo $this->translate('Splash Offers'); ?>
            <button class="btn ml10 btn-primary" type="button" onClick="window.location.href='<?php echo HTTP_PATH ?>admin/splash/add-offer'"><?php echo $this->translate('Add New Offer'); ?>
            </button>
        </h1>
        <?php endif; ?>
        <div class="clear"></div>
        <div class="top_navigation">
            <ul>
                <li><a href="/admin/splash/page">Splash Page</a></li>
                <li><a href="/admin/splash" class="selected_nav">Splash Offers </a></li>
                <li><a href="/admin/splash/images">Featured Images </a></li>
            </ul>
        </div>
        <div class="clear"></div>
        <table class="table table-bordered table-striped"  cellpadding="0" cellspacing="0" id="splash-offer-table">
            <thead>
                <tr>
                    <th>#</th>
                    <th><?php echo $this->translate('Offer Name'); ?></th>
                    <th><?php echo $this->translate('Shop Name'); ?></th>
                    <th><?php echo $this->translate('Locale'); ?></th>
                    <th><?php echo $this->translate('Action'); ?></th>
                </tr>
            </thead>
            <?php if( true == !empty($this->splashOffersData)):
                $row = 1;
                foreach($this->splashOffersData as $splashOffer): ?>
                    <tr id="row_<?php echo $splashOffer['id']; ?>" data-position="<?php echo $row; ?>">
                        <td><?php echo $row; ?></td>
                        <td><input type="hidden" name="splashOffers[]" value="<?php echo $splashOffer['id']; ?>"><?php echo $splashOffer['offer']; ?></td>
                        <td><?php echo $splashOffer['shop']; ?></td>
                        <td><?php echo $splashOffer['locale']; ?></td>
                        <td>
                            <button class="btn ml10 mb10" type="button" onClick="window.location.href='<?php echo HTTP_PATH ?>admin/splash/delete-offer/id/<?php echo $splashOffer['id']; ?>'"><?php echo $this->translate('Delete'); ?>
                            </button>
                        </td>
                    </tr>
                <?php $row++; endforeach; ?>
            <?php endif; ?>
        </table>
        <label class="toplinks-outer" style="color: #3a87ad"><i>* <?php echo $this->translate('You can drag & drop the offers to reorder'); ?></i></label>
    </div>
</div>
<div class="clear"></div><br>
<div id="save-order-section" style="display:none;">
    <button class="btn btn-large btn-primary fl" type="submit" id="publishShopButton">SAVE ORDER</button>
    <a onclick="window.location.href='<?php echo HTTP_PATH ;?>admin/splash'" href="javascript:void(0);" class="fl m10"><strong>CANCEL</strong></a>
</div>
</form>