<?php
$this->headScript()->appendFile(PUBLIC_PATH  . "js/back_end/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.dataTables.min.js");
$this->headScript ()->appendFile ( PUBLIC_PATH . "js/back_end/ckeditor/ckeditor.js" );
$this->headScript ()->appendFile ( PUBLIC_PATH . "js/back_end/ckeditor/config.js" );
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/splashPage.js");
$this->headTitle()->append('Splash Page');
?>
<script type="text/javascript">
    var CKEDITOR_BASEPATH = "<?php echo PUBLIC_PATH . "js/back_end/ckeditor/" ; ?>" ;
</script>

<div id="imbullbody">
    <div style="overflow: hidden;" id="imbullbody-content">
        <div class="wrap columns-2">
            <?php echo $this->flashMessages(); ?>
            <h1><?php echo $this->translate('Splash Page');?></h1>
            <div class="clear"></div>
            <div class="top_navigation margin-b0">
                <ul>
                    <li><a href="/admin/splash/page" class="selected_nav">Splash Page </a></li>
                    <li><a href="/admin/splash" id="subMenu">Splash Offers </a></li>
                    <li><a href="/admin/splash/images" id="subMenu">Featured Images </a></li>
                </ul>
            </div>
            <form name="splashPage" id="splashPage" enctype="multipart/form-data" method="post">
                <div id="poststuff" class="metabox-holder has-right-sidebar">
                    <div id="post-body">
                        <div>
                            <div class="mainpage-content" style="border-top: none;">
                                <br>
                                <div class="mainpage-content-line mb10">
                                    <div class="mainpage-content-left">
                                        <label><strong><?php echo $this->translate('Banner Image'); ?></strong></label>
                                    </div>
                                    <div class="mainpage-content-right">
                                        <div class="mainpage-content-line">
                                            <div class="mainpage-content-right-inner-left-other">
                                                <div class="mainpage-content-line header-image-cont">
                                                    <div class="mainpage-content-right-inner"></div>
                                                    <div class="mainpage-content-right-inner">
                                                        <div class='browse-container'>
                                                            <?php if (!empty($this->splashPage->getImage())) : ?>
                                                                <img class='image-container' src="<?php echo PUBLIC_PATH . 'images/upload/splash/' . $this->splashPage->getImage(); ?>">
                                                            <?php endif; ?>
                                                        </div>
                                                        <input type="file"  id="splashPageImage" class="span3 margin-bottom-tenpx" name="splashImage">
                                                        <div class="margin-bottom-tenpx">
                                                            <span class="help-inline" id="logo_file_message">
                                                                <?php echo $this->translate("Image Size: 1400px x 600px (*.jpeg, *.jpg or *.png file only)"); ?>
                                                            </span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="mainpage-content-line">
                                    <div class="mainpage-content-left">
                                        <label><strong><?php echo $this->translate('About Flipit'); ?></strong></label>
                                    </div>
                                    <div class="mainpage-content-right">
                                        <div class="mainpage-content-right-inner-right-other"></div>
                                        <div class="mainpage-content-right-inner-left-other">
                                            <textarea name="splashPage[content]"  id="splashPageContent"><?php echo  $this->splashPage ? $this->splashPage->getContent() : ""; ?></textarea>
                                        </div>
                                    </div>
                                </div>

                                <div class="mainpage-content-line mb10">
                                    <div class="mainpage-content-left">
                                        <label><strong><?php echo $this->translate('Info Image'); ?></strong></label>
                                    </div>
                                    <div class="mainpage-content-right">
                                        <div class="mainpage-content-line">
                                            <div class="mainpage-content-right-inner-left-other">
                                                <div class="mainpage-content-line header-image-cont">
                                                    <div class="mainpage-content-right-inner"></div>
                                                    <div class="mainpage-content-right-inner">
                                                        <div class='browse-container'>
                                                            <?php if (!empty($this->splashPage->getInfoImage())) : ?>
                                                                <img class='image-container' src="<?php echo PUBLIC_PATH . 'images/upload/splash/' . $this->splashPage->getInfoImage(); ?>">
                                                            <?php endif; ?>
                                                        </div>
                                                        <input type="file"  id="splashPageInfoImage" class="span3 margin-bottom-tenpx" name="splashInfoImage">
                                                        <div class="margin-bottom-tenpx">
                                                            <span class="help-inline" id="logo_file_message">
                                                                <?php echo $this->translate("Image Size: 1400px x 600px (*.jpeg, *.jpg or *.png file only)"); ?>
                                                            </span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="mainpage-content-line">
                                    <div class="mainpage-content-left">
                                        <label><strong><?php echo $this->translate('Popular Shops'); ?></strong></label>
                                    </div>
                                    <div class="mainpage-content-right">
                                        <div class="mainpage-content-right-inner-right-other"></div>
                                        <div class="mainpage-content-right-inner-left-other">
                                            <textarea name="splashPage[popularShops]"  id="splashPagePopularShops"><?php echo  $this->splashPage ? $this->splashPage->getPopularShops() : ""; ?></textarea>
                                        </div>
                                    </div>
                                </div>

                                <div class="mainpage-content-line">
                                    <div class="mainpage-content-left">
                                        <label><strong><?php echo $this->translate('Statistics'); ?></strong></label>
                                    </div>
                                    <div class="mainpage-content-right">
                                        <div class="mainpage-content-right-inner-right-other"></div>
                                        <div class="mainpage-content-right-inner-left-other">
                                            <textarea name="splashPage[statistics]"  id="splashPageStatistics"><?php echo  $this->splashPage ? $this->splashPage->getStatistics() : ""; ?></textarea>
                                        </div>
                                    </div>
                                </div>

                                <div class="mainpage-content-line">
                                    <div class="mainpage-content-left">
                                        <label><strong><?php echo $this->translate('Footer Content'); ?></strong></label>
                                    </div>
                                    <div class="mainpage-content-right">
                                        <div class="mainpage-content-right-inner-right-other"></div>
                                        <div class="mainpage-content-right-inner-left-other">
                                            <textarea name="splashPage[footer]"  id="splashPageFooter"><?php echo  $this->splashPage ? $this->splashPage->getFooter() : ""; ?></textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br class="clear">
                </div>
                <div class="mainpage-content-colorbox">
                    <button id="updateFooterButton" class="btn btn-large btn-primary fl"><?php echo $this->translate('EDIT SPLASH PAGE'); ?></button>
                    <a href="/admin/splash/page" class="fl m10"><strong><?php echo $this->translate('CANCEL'); ?></strong></a>
                </div>
            </form>

        </div>
        <div class="clear"></div>
    </div>
</div>


