<?php
$this->headTitle()->append($this->translate('Locale Settings'));
$this->headMeta('keyword', 'Description');
$this->headScript ()->appendFile ( PUBLIC_PATH . "js/back_end/locale-settings.js" );
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/select2.min.js");
?>
<div class="wrap columns-2">
    <div class='wrap columns-2'>
        <?php if($this->messageSuccess!='' || $this->messageError!='' ){ ?>
        <br>
        <div class="mainpage-content-colorbox success">
        <?php if($this->messageSuccess!=''){ ?>
        <span class="successserver"><?php echo $this->messageSuccess; ?></span>
        <?php }?>
        <?php if($this->messageError!=''){?>
        <span class="errorserver"><?php echo $this->messageError; ?></span>
        <?php } ?>
        </div>
        <?php
        }?>
    </div>
    <h1><?php echo $this->translate('Locale Settings'); ?></h1>
    <div class="mainpage-content">
        <div class="mainpage-content-line mb10">
            <div class="mainpage-content-left">
                <label><strong><?php echo $this->translate('Locale'); ?></strong></label>
            </div>
            <div class="mainpage-content-right">
                <div class="mainpage-content-right-inner-left-other">
                    <div data-toggle="buttons-checkbox" class="btn-group">
                        <select id='locale' style='width:200px;'>
                            <option value=""></option>
                            <?php
                            $seletced = '';
                                $locale = Zend_Locale::getLocaleList();
                                foreach($locale as $key => $loc):
                                    if ($this->localeSettings['0']['locale'] == $key) {
                                        $seletced = 'selected="selected"';
                                    }
                                    echo "<option $seletced value=". $key .">". $key ."</option>";
                                endforeach;
                            ?>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="mainpage-content">
        <div class="mainpage-content-line mb10">
            <div class="mainpage-content-left">
                <label><strong><?php echo $this->translate('Locale Status'); ?></strong></label>
            </div>
            <div class="mainpage-content-right">
                <div class="btn-group" data-toggle="buttons-checkbox">
                    <?php
                    $backEndViewHelper = new BackEnd_Helper_viewHelper();
                    echo $this->localeStatus['status'] == 'online' ?
                        $backEndViewHelper->getLocaleStatusButtons('online') :
                        $backEndViewHelper->getLocaleStatusButtons('offline');
                    ?>
                </div>
            </div>
        </div>
    </div>
    <div class="mainpage-content">
        <div class="mainpage-content-line mb10">
            <div class="mainpage-content-left">
                <label><strong><?php echo $this->translate('Time Zone'); ?></strong></label>
            </div>
            <div class="mainpage-content-right">
                <div class="mainpage-content-right-inner-left-other">
                    <div data-toggle="buttons-checkbox" class="btn-group timezone">
                        <select id='timezone' style='width:300px;' name="timezone">
                            <option value=""></option>
                            <?php
                                $timezones_list = $this->timezones_list;
                                foreach($timezones_list as $key => $name):
                                    $seletcedTimeZone = '';
                                    if ($this->localeSettings['0']['timezone'] == $key) {
                                        $seletcedTimeZone = 'selected="selected"';
                                    }
                                    echo "<option $seletcedTimeZone value=". $key .">". $name ."</option>";
                                endforeach;
                            ?>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>