<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?php echo $this->translate('Kortingscode.nl');?></title>
        <link href="<?php echo PUBLIC_PATH ?>css/feeds/style.css" rel="stylesheet" type="text/css" />
    </head>
<body>
<div id="wrapper">
    <h1 class="title"><?php echo $this->translate('Popular Coupon Codes'); ?>&nbsp;<i><?php echo $this->translate('Powered by Flipit.com'); ?></i></h1>
    <ul class="coupon">
<?php
$topPopularCouponCode = $this->topPopularCoupons;
$offerNumber = 1;
for ($couponCounter = 0; $couponCounter<count($topPopularCouponCode); $couponCounter++):
    $couponContent = $topPopularCouponCode[$couponCounter]['title'];

    if(mb_strlen($topPopularCouponCode[$couponCounter]['title'], 'UTF-8') > 35):
        $couponContent = mb_substr($topPopularCouponCode[$couponCounter]['title'], 0, 35, 'UTF-8').'...';
    endif;
    ?>
    <li>
        <div class="coupon-content">
        <span class="content">
            <a href="<?php echo HTTP_PATH_LOCALE.$topPopularCouponCode[$couponCounter]['permaLink'];  ?>" target="_blank">
    <?php
    echo '<p class="number">'.$offerNumber.'</p>. '.$couponContent;
    ?>
            </a>
        </span>
        </div>
    </li> 
    <?php 
    if($offerNumber % 3 == 0):
        echo "</ul><ul class='coupon'>";
    endif;
    $offerNumber++;
endfor;
?>
</div>
</body>
</html>