<?php $session = new Zend_Session_Namespace('Branding'); ?>
<?php
if (
    $session->brandingActivated == true
    && Zend_Controller_Front::getInstance()->getRequest()->getActionName() == 'storedetail'
): 
    $this->minifyHeadScript()->appendFile(HTTP_PATH."public/js/front_end/branding.js");
    ?>
    <?php echo $this->headStyle()->appendStyle($this->shop()->brandingCss($session->data)); ?>
    <?php echo $this->headScript()->appendScript($this->shop()->brandingJs($session->data)); ?>
    <div id="show_branding"><a href="javascript:void(0);">Branding panel ></a></div>
    <div id="branding_panel">
        <form id="branding" action="<?php echo $session->saveUrl; ?>branding/save" method="post" enctype="multipart/form-data">
            <div class="toolbar top">
                <h2>Shop Branding</h2>
                <div id="close_branding"><a href="javascript:void(0);">X</a></div>
            </div>
            <div style="clear:both;"></div>
            <br />
            <hr>
            <div class="branding_section">
                
                <input type="hidden" name="preview" id="preview" value="0" />
                <input type="hidden" name="reset" id="reset" value="0" />
                <input type="hidden" name="shop_id" id="shop_id" value="<?php echo $this->currentStoreInformation[0]['id']; ?>" />
                <h3>Colors</h3>
                <table>
                    <?php $item = 'link_color'; ?>
                    <tr>
                        <td><label for="<?php echo $item; ?>">Links</label></td>
                        <td class="color_select"><input type="color" name="<?php echo $item; ?>" value="<?php echo isset($session->data[$item]['value']) ? $session->data[$item]['value'] : ''; ?>" data-css-selector="<?php echo isset($session->data[$item]['css-selector']) ? $session->data[$item]['css-selector'] : ''; ?>" data-css-property="<?php echo isset($session->data[$item]['css-property']) ? $session->data[$item]['css-property'] : ''; ?>" /></td>
                    </tr>
                    <?php $item = 'store_title'; ?>
                    <tr>
                        <td><label for="<?php echo $item; ?>">Store title</label></td>
                        <td class="color_select"><input type="color" name="<?php echo $item; ?>" value="<?php echo isset($session->data[$item]['value']) ? $session->data[$item]['value'] : ''; ?>" data-css-selector="<?php echo isset($session->data[$item]['css-selector']) ? $session->data[$item]['css-selector'] : ''; ?>" data-css-property="<?php echo isset($session->data[$item]['css-property']) ? $session->data[$item]['css-property'] : ''; ?>" /></td>
                    </tr>
                    <?php $item = 'store_sub_title'; ?>
                    <tr>
                        <td><label for="<?php echo $item; ?>">Store sub title</label></td>
                        <td class="color_select"><input type="color" name="<?php echo $item; ?>" value="<?php echo isset($session->data[$item]['value']) ? $session->data[$item]['value'] : ''; ?>" data-css-selector="<?php echo isset($session->data[$item]['css-selector']) ? $session->data[$item]['css-selector'] : ''; ?>" data-css-property="<?php echo isset($session->data[$item]['css-property']) ? $session->data[$item]['css-property'] : ''; ?>" /></td>
                    </tr>
                    <?php $item = 'store_coupons_used'; ?>
                    <tr>
                        <td><label for="<?php echo $item; ?>">Store Coupons Used</label></td>
                        <td class="color_select"><input type="color" name="<?php echo $item; ?>" value="<?php echo isset($session->data[$item]['value']) ? $session->data[$item]['value'] : ''; ?>" data-css-selector="<?php echo isset($session->data[$item]['css-selector']) ? $session->data[$item]['css-selector'] : ''; ?>" data-css-property="<?php echo isset($session->data[$item]['css-property']) ? $session->data[$item]['css-property'] : ''; ?>" /></td>
                    </tr>
                    <?php $item = 'store_total_coupons'; ?>
                    <tr>
                        <td><label for="<?php echo $item; ?>">Store Total Coupons</label></td>
                        <td class="color_select"><input type="color" name="<?php echo $item; ?>" value="<?php echo isset($session->data[$item]['value']) ? $session->data[$item]['value'] : ''; ?>" data-css-selector="<?php echo isset($session->data[$item]['css-selector']) ? $session->data[$item]['css-selector'] : ''; ?>" data-css-property="<?php echo isset($session->data[$item]['css-property']) ? $session->data[$item]['css-property'] : ''; ?>" /></td>
                    </tr>
                    <?php $item = 'newsletter_background_color'; ?>
                    <tr>
                        <td><label for="<?php echo $item; ?>">Newsletter background</label></td>
                        <td class="color_select"><input type="color" name="<?php echo $item; ?>" value="<?php echo isset($session->data[$item]['value']) ? $session->data[$item]['value'] : ''; ?>" data-css-selector="<?php echo isset($session->data[$item]['css-selector']) ? $session->data[$item]['css-selector'] : ''; ?>" data-css-property="<?php echo isset($session->data[$item]['css-property']) ? $session->data[$item]['css-property'] : ''; ?>" /></td>
                    </tr>
                    <?php $item = 'newsletter_title_color'; ?>
                    <tr>
                        <td><label for="<?php echo $item; ?>">Newsletter title color</label></td>
                        <td class="color_select"><input type="color" name="<?php echo $item; ?>" value="<?php echo isset($session->data[$item]['value']) ? $session->data[$item]['value'] : ''; ?>" data-css-selector="<?php echo isset($session->data[$item]['css-selector']) ? $session->data[$item]['css-selector'] : ''; ?>" data-css-property="<?php echo isset($session->data[$item]['css-property']) ? $session->data[$item]['css-property'] : ''; ?>" /></td>
                    </tr>
                </table>
            </div>
            <hr>
            <div class="branding_section">
                <h3>Images</h3>
                <?php $item = 'newsletter_store_logo'; ?>
                <p>
                    <label for="<?php echo $item; ?>">Newsletter store logo</label>
                    <input type="file" name="<?php echo $item; ?>" accept="image/x-png, image/gif, image/jpeg, image/jpg" />
                </p>
                <p>                    
                    <?php if(!empty($session->data[$item]['img'])): ?>   
                        <p>
                            <img src="<?php echo PUBLIC_PATH.$session->data[$item]['img'] ?>" title="image">
                            <input type="checkbox" name="delete[]" value="<?php echo $item; ?>"> Delete?
                        </p>
                    <?php endif; ?>      
                </p>
                <p>
                    <?php $item = 'header_background'; ?>
                    <label for="<?php echo $item; ?>">Header Background</label>
                    <input type="file" name="<?php echo $item; ?>" accept="image/x-png, image/gif, image/jpeg, image/jpg" />  
                    <?php if(!empty($session->data[$item]['img'])): ?>
                        <p>
                            <img src="<?php echo PUBLIC_PATH.$session->data[$item]['img'] ?>" title="image">
                            <input type="checkbox" name="delete[]" value="<?php echo $item; ?>"> Delete?
                        </p>
                    <?php endif; ?>         
                </p>
            </div>
            <hr>
            <div class="branding_section">
                <p>
                    <?php $item = 'overwrite'; ?>
                    <label for="<?php echo $item; ?>">Overwrite css</label>
                    <textarea name="<?php echo $item; ?>" id="<?php echo $item; ?>"><?php echo isset($session->data[$item]['value']) ? $session->data[$item]['value'] : ''; ?></textarea>
                </p>
            </div>
            <hr>
            <div class="toolbar bottom">
                <button id="save_form" type="submit" class="btn btn-sm blue btn-primary">Save</button>
                <button id="preview_submit" class="btn btn-sm btn-default preview">Preview</button>
                <div style="clear:both;"></div>
                <br />
                <p><button id="reset_submit" >Reset to defaults</button> </p>
                <br />
            </div>
        </form>
    </div>
<?php endif; ?>