
<?php
if (APPLICATION_ENV == 'development') {
    $headScript =  $this->HeadScript();
    $headScript->prependFile("/public/js/front_end/less/dist/less-1.7.0.js");
} else {
    $headScript = $this->minifyHeadScript();
}
$this->minifyHeadScript()
    ->prependFile("/public/js/common.js")
    ->prependFile("/public/js/front_end/popupShow.js")
    ->prependFile("/public/js/front_end/bigtext.js");
if(LOCALE !='') :
    $this->minifyHeadScript()
        ->prependFile("/public/" . LOCALE ."/js/front_end/json/translation.js")
        ->prependFile("/public/" . LOCALE ."/js/front_end/json/shops.js");
else:
    $this->minifyHeadScript()
        ->prependFile("public/js/front_end/json/translation.js")
        ->prependFile("/public/js/front_end/json/shops.js")
        ->prependScript("(function(h,o,t,j,a,r){
                h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
                h._hjSettings={hjid:61629,hjsv:5};
                a=o.getElementsByTagName('head')[0];
                r=o.createElement('script');r.async=1;
                r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
                a.appendChild(r);
            })(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');");
endif;

if (FrontEnd_Helper_LayoutContent::loadPicreelScript() === true) :
    $headScript->prependFile("//assets.pcrl.co/js/jstracker.min.js");
endif;

    $headScript
        ->prependFile("/public/js/front_end/jquery.menu.js")
        ->prependFile("/public/js/front_end/social-code.js")
        ->prependFile("/public/js/front_end/signupnewsletter.js")
        ->prependFile("/public/js/front_end/jquery.inputmask.min.js")
        ->prependFile("/public/js/front_end/jquery.validate.js")
        ->prependFile("/public/js/front_end/jquery.main.js")
        ->prependFile("/public/js/front_end/layout.js")
        ->prependFile("/public/js/Gettext.js")
        ->prependFile("/public/js/jquery-ui-1.8.16.custom.min.js")
        ->prependFile("/public/js/bootstrap.min.js")
        ->prependFile("/public/js/jquery-1.7.2.min.js")
        ->prependScript('var HOST_PATH_LOCALE = "'.  HTTP_PATH_LOCALE .'";')
        ->prependScript('var LOCALE = "'. LOCALE .'";');
