<?php
    $this->headTitle()->append($this->translate('Special pages'));
    $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
    $this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
    $this->headLink()->appendStylesheet(PUBLIC_PATH . "css/jquery-ui-1.8.16.custom.css");
    $this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/back_end/bootstrap-combobox.css" );
    $this->headScript ()->appendFile ( PUBLIC_PATH . "js/back_end/select2.min.js" );
    $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/special_pages.js");
?>
<div class="wrap columns-2">
    <h1>
        <?php echo $this->translate('Special pages'); ?>
    </h1>
    <div class='mb10'> 
        <select  style="display: none; width : 389px;" class="combobox" name="specialPagelist" id="specialPagelist">
        <?php
        foreach ($this->specialPages as $specialPage) { 
            if($specialPage['id'] == $this->pageId) {
                ?>
                <option  selected='selected' 
                value="<?php echo $specialPage['id']; ?>"><?php echo $specialPage['pageTitle']; ?>
                </option>
                <?php
            } else {
                ?>
                <option  value="<?php echo $specialPage['id']; ?>"><?php echo $specialPage['pageTitle']; ?></option>
                <?php
            }
         }?>
        </select>
    </div>
    <input type="hidden" name="selctedPageId" id="selctedPageId" value="<?php echo $this->pageId; ?>">
    <div id="poststuff" class="metabox-holder has-right-sidebar">
        <div id="side-info-column" class="inner-sidebar-coupon">
            <div id="side-sortables" class="meta-box-sortables ui-sortable">
                <div class="coupon-sidebar-outer">
                    <div class="coupon-sidebar-heading">
                        <select  style="display: none; width : 389px;" class="combobox" name="offerlist" id="offerlist">
                            <option value=""></option>
                            <?php
                            foreach ($this->offer as $o) { 
                                if (trim ($o ['title'] ) != '') {
                                    $offer = substr ($o ['title'], 0, 70 );
                                    ?>
                                    <option  value="<?php echo $o['id']; ?>"><?php echo $offer; ?></option>
                                    <?php 
                                }
                            }
                            ?>
                        </select> 
                        <input type="hidden" name="selctedOffer" id="selctedOffer" value="">
                        <input type="hidden" name="selctedOfferText" id="selctedOfferText" value="">
                        <input type='hidden' name="SearchedValueIds" id="SearchedValueIds" value="">
                    </div>
                    <div class="coupon-sidebar-content-box">
                        <button id='addNewOffer' onClick='addNewOffer();'class="btn">
                        <?php echo $this->translate('ADD NEW OFFER');?>
                        </button>
                    </div>
                    <div class="coupon-sidebar-content-box mb10 image-loading-icon">
                        <button id='deleteOne' onClick='deleteOne();' class="btn">
                        <?php echo $this->translate("DELETE");?>
                        </button>
                    </div>                    
                </div>
            </div>
        </div>
        <div id="post-body">
            <div id="post-body-content-coupon">
                <div class="top-coupon-list">
                    <ul id='specialPages'>
                    <?php 
                    if (!empty($this->specialPageOffers)) {
                        $date = new DateTime();
                        foreach ($this->specialPageOffers as $specialPageOffers) {
                            $expired = '';
                            if($date > $specialPageOffers['offers']['endDate']) {
                                $expired = "<i class='pull-right icon icon-time'></i></li>";
                            }
                            echo  "<li class='ui-state-default'  id='".$specialPageOffers['id']."' 
                            reloffer='".$specialPageOffers['offers']['id']."'
                            relpos='".$specialPageOffers['position']."'
                            relpageId='".$specialPageOffers['pages']['id']."'>
                            <span>".$specialPageOffers['offers']['title']."</span>".$expired;
                        }
                    } else {             
                        echo  "<li id='0'>". $this->translate('No record found !') ."</li>";
                    } ?>
                    </ul>
                </div>
            </div>
        </div>
        <br class="clear">
    </div>
</div>
