<?php  
     $this->minifyHeadScript()->prependFile ( HTTP_PATH ."public/js/front_end/socialmedia.js" );
	 $headerSearch = new FrontEnd_Helper_viewHelper(); 
     $page = $this->page;
     $pageDetail = $this->pageDetail;
     
     $breadcrumb = "<a href='".HTTP_PATH_LOCALE."bespaarwijzer' style='color:#6a6a6a'>".$this->translate('Bespaar Wijzer')."</a>";
	 echo $this->partial('partials/_headerSearch.phtml',array('breadcrumb' => $breadcrumb));
	 $category = $this->category;
?>
     <!-- Separator Starts -->
        <div class="separator">&nbsp;</div>
     <!-- Separator Ends -->
<?php 
	 if(!empty($category)){
	 	$namebespaar = $category[0]['name'];
	 ?> 
        <!-- Bespaarwijzer Starts -->
        <div class="new-outer">
        <div class="bespaarwijzer-outer">
        
        <!-- Bespaarwijzer Left Starts -->
        	<div class="bespaarwijzer-left">
            	<div class="bespaarwijzer-left-heading">
            	  <h1><?php echo $namebespaar; ?></h1>
            	</div>
            	<div class="bespaarwijzer-left-category">
					<?php echo $category[0]['description']; ?>                  
                </div>
            </div>
            <!-- Bespaarwijzer Left Ends -->
                   <?php  	
						 if(file_exists(ROOT_PATH.$category[0]['ArtCatIcon']['path']."thum_articleCategory_big_".$category[0]['ArtCatIcon']['name']) && $category[0]['ArtCatIcon']['name']!=''){
						  	$img = PUBLIC_PATH.$category[0]['ArtCatIcon']['path']."thum_articleCategory_big_".$category[0]['ArtCatIcon']['name'];
						 }else{
						  	$img = HTTP_PATH."public/images/NoImage/NoImage_250_250.jpg";
						  	
						 }	
                   ?>
            
            <div class="financieel-right crop">
            	<img class='radiusImg' src="<?php  echo $img;?>" alt="<?php echo $namebespaar; ?>"/>
            </div>
        </div>
        </div>
        <!-- Bespaarwijzer Ends -->
        
        <!-- Separator Starts -->
        <div class="separator">&nbsp;</div>
        <!-- Separator Ends -->
        
         <!-- Social Likes Starts -->
        <div class="white-bg">
        <div class="new-outer">
        <div class="small-social-likes"> 
         <?php
            $url = "http://www.kortingscode.nl"; 
            $title = $this->translate("Share Kortingscode.nl en maak kans op een waardebon t.w.v. &euro; 50!");
            $socialMedia = new FrontEnd_Helper_viewHelper();
         	echo $socialMedia->socialmedia($url, $title,'moneysavingguide');
         ?>
         </div>
         </div>
         </div>
         <!-- Social Likes Ends -->
        
         <!-- Separator Starts -->
        <div class="separator">&nbsp;</div>
        <!-- Separator Ends -->
        
        <!-- Merchants Outer Starts -->
        <div class="new-outer">
            <div class="common-div mt20">

             <h2><?php echo $this->translate('MOST READ MONEY SAVING GUIDES IN'); echo ' '.$namebespaar; ?></h2>
            	<div class="common-div">
            		<?php
            		if(!empty($this->mostReadArtOfcategory)) { 
            			echo $this->partialLoop('partials/mostReadAcls.phtml',$this->mostReadArtOfcategory);
            		} else {
            			echo $this->translate("No Records Found");
            		}
            		?>
                </div>
            </div>
        </div>
     
         <!-- Merchants Outer Ends -->
   
         <!-- Separator Starts -->
        <div class="separator mt20">&nbsp;</div>
        <!-- Separator Ends -->
         <div class="white-bg"> 
         <!-- Common Div Starts -->
         <div class="new-outer">
         <div class="common-div mt20">
         	<h2><?php echo $this->translate('RELENVABTE KORTINGSCODE CATEGORIEEN'); ?></h2>
         	<?php 
          if(!empty($this->relatedCategory)) { 
          	$relCategory =  array();
         	$relatedCategory = $this->relatedCategory;
         	$relCategory = $relatedCategory[0]['relatedcategory'];
         	?>
            <div class="common-div">
            <?php $ret1 = 1; ?>   
            <?php  
            foreach($relCategory as $relCat){
            	if(file_exists(ROOT_PATH.$relCat['categoryicon']['path']."thum_medium_".$relCat['categoryicon']['name']) && $relCat['categoryicon']['name']!=''){
            		$img1 = PUBLIC_PATH.$relCat['categoryicon']['path']."thum_medium_".$relCat['categoryicon']['name'];
            	}else{
            		//$img = HTTP_PATH."public/images/upload/no.jpg";
            		//$img1 = HTTP_PATH. "public/thumb.php?src=". $img . "&h=50&w=50&zc=0";
            		$img1 = HTTP_PATH."public/images/NoImage/NoImage50x50.jpg";
            	}
            	$catLink = HTTP_PATH_LOCALE.FrontEnd_Helper_viewHelper::__link("categorieen")."/".$relCat['permaLink'];
            	?>
              <!-- Icon Description Outer Starts -->
       	      <div class="image-description-outer">
             	<a href="<?php echo $catLink; ?>">
                  <div class="image-description-img">
                    <img src="<?php echo $img1; ?>" alt="<?php echo $relCat['name'] ?>"/>
                  </div>
                  <div class="image-description-text">
                       <span class="text-black-link">
                          <?php echo $relCat['name'] ?>
    	               </span>
	               </div>
               	</a>   		
              </div>
              <!-- Icon Description Outer Ends -->
            	  <?php if($ret1%8 == 0){ ?><br>
        			<!-- Separator Starts -->
        			<div class="autosep">&nbsp;</div>
        			<!-- Separator Ends --> 
             		<?php }
              		$ret1++;
            }
          } else {
          	
          	echo $this->translate("No Records Found");
          	
          }
            ?>
        </div>

         </div>
         </div>
         <!-- Common Div Ends -->
        </div>
         <!-- Separator Starts -->
        <div class="separator">&nbsp;</div>
        <!-- Separator Ends -->

		<!-- Common Div Starts -->
         <div class="new-outer">
	      <div class="common-div mt20">
	        <h2>
	        <?php echo $this->translate('Alle') ." ".strtolower($namebespaar)." ". $this->translate('BESPAAR WIJZERS'); ?></h2>
	    		<div class="common-div">
	    		<?php
	    		 if(!empty($this->allMoneySavingArticles)) { 
	    		 	
	    		 	echo $this->partialLoop('bespaarwijzer/readMoreCategory.phtml',$this->allMoneySavingArticles);
	    		 	
	    		 } else {
	    		 	echo $this->translate("No Records Found");
	    		 }
	 			 ?>
	        	</div>
	        </div>
        </div>
        <!-- Common Div Ends -->

	<?php } else {
		echo $this->translate("No Records Found");
	 } ?>
