<?php  
$articleview = $this->articleview;
$userview = $this->udetails;

if(!empty($articleview)) :
    
    
?> 
</style>

        <!-- Guide Outer Starts -->
        <div class="new-outer">
        <div class="guide-outer-new">
        
          <!-- Bespaarwijzer Left Starts -->
            <div>
            <div class="bespaarwijzer-left-heading">
                  <h1><?php echo $articleview['title'];?></strong></h1>
                  <div class="guide-detail">
                  <?php 
                     $fname = str_replace(' ', '', $userview['firstName']);
                     $lname = str_replace(' ', '', $userview['lastName']);
                     $link_url = $userview['slug'];
                     $profileLink = HTTP_PATH_LOCALE.FrontEnd_Helper_viewHelper::__link("redactie")."/".$link_url;
                  ?>
                  <span class="guide-text"><a class="text-blue-link" href="<?php echo $profileLink; ?>"><?php echo @$userview['firstName'] . " " . $userview['lastName'];?></a></span>
                   <?php 
                              $img = HTTP_PATH ."public/images/front_end/guide-cal.png";
                              $update = strtotime($articleview['updated_at']);
                              $udate = date('d M Y', $update);
                              $date = $udate;
                              $catString = '';
                              $pLink = '';
                              $i = 0;
                              $count = count($articleview['relatedcategory']);
                              if($count > 0):
                              $date = $date .'';
                              $aTag = '';
                              '<br>'.$this->translate('category :') . ' ';
                              foreach ($articleview['relatedcategory'] as $category):
                                     if(++$i === $count):
                                         $aTag .= "<a href='" . HTTP_PATH_LOCALE .FrontEnd_Helper_viewHelper::__link('bespaarwijzercat').'/'.$category['articlecategory']['permalink'] . "'>" .  $category['articlecategory']['name'] ."</a>";
                                     else:
                                         $aTag .= "<a href='" . HTTP_PATH_LOCALE .FrontEnd_Helper_viewHelper::__link('bespaarwijzercat').'/'.$category['articlecategory']['permalink'] . "'>" .  $category['articlecategory']['name'] ."</a> ,";
                                    endif;
                                endforeach;
                              endif;
                              $allCatLink = "<span style='margin:0 15px;'>|</span>" .  $this->translate('Categorie:') . " " . $aTag;
                              echo " - ".$date;
                    ?>
                    <span style="margin:0 15px;">|</span><img src="/public/images/front_end/1361286131_coins.png"><?php echo $this->translate('Alle'); ?> <a class="text-blue-link bespaarwijzer" href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('bespaarwijzer')?>"><?php echo $this->translate('Bespaarwijzers');?></a>
                    <?php echo $allCatLink;?>
                    
                    </div>
                   </div>
                  <div>
                          <?php
                        $url = "http://www.kortingscode.nl/"; 
                        $title = "";
                        $socialMedia = new FrontEnd_Helper_viewHelper();
                        echo $socialMedia->socialMediaWidget($url, $title,'moneysavingguide');
                  ?>
                </div>
               <!-- Separator Starts -->
                <div class="separator mt10">&nbsp;</div>
                <!-- Separator Ends -->
                
            <!-- Quick Outer Starts -->
             <div class="guide-chantal-left" style="margin-top:15px;">
                    <?php   
                            $img = PUBLIC_PATH_CDN.$articleview['ArtIcon']['path'].$articleview['ArtIcon']['name'];
                            
                   ?>
                        <img src="<?php echo $img; ?>" alt="<?php echo $articleview['title'];?>" class="img-radius" width='960px' height='340px'/>
                    
              </div>
            
            
            
          <!-- Quick Outer Ends -->  
          
            
            
          </div>
          <!-- Bespaarwijzer Left Ends -->
          <div class="ct-content-outer">
            <div class="guide-content-new">
                <div class="guide-chantal-right-bot">
                    <?php  
                    foreach ($this->articleview['chapters'] as $chapters) :

                        $pattern = array ('/\s/','/[\,+@#?$%^:&*!.();]+/', '/(\')/');

                        
                        $replace = array ("-","-","-");
                        $title = preg_replace ( $pattern, $replace, $chapters['title'] );
                        
                        $title = strtolower($title);
                        echo '<h2 id="'.$title.'">'.$chapters['title'].'</h2>';
                        echo $chapters['content']; 
                    endforeach;
                    ?> 
                </div>
            
            </div>
            <div class="guide-content-new-right-scroll" id='floatDiv'>
                <h4><?php echo $this->translate('Go To Chapter')?></h4>
                <ul>
                    <?php 
                        foreach ($this->articleview['chapters'] as $key => $chapters) : 

                        $pattern = array ('/\s/','/[\,+@#?$%^:&*!.();]+/' , '/(\')/');

                         
                        $replace = array ("-","-","-");
                        $title = preg_replace ( $pattern, $replace, $chapters['title'] );
                         
                        $title = strtolower($title);
                    ?>
                        <li><a href="javascript:void(0);" rel = "<?php echo $title; ?>" onclick="scrollbyChapter(this)"><?php echo $chapters['title']; ?></a></li>
                    <?php endforeach;?>
                </ul>
                <div class="side-cor"></div>
            </div>
          </div> 
          
          <div class="clr"></div>
          
          
           
           <div class="guide-bottom-social">
            <p><?php echo $this->translate('Deel deze Bespaarwijzer met vrienden!'); ?></p>
            <?php
              $url = "http://www.kortingscode.nl/"; 
              $title = "";
              $socialMedia = new FrontEnd_Helper_viewHelper();
              echo $socialMedia->socialMediaWidget($url, $title,'moneysavingguide');
            ?>
           </div>
           
           <!-- Next/Previous div starts here -->
           <div class="guide-next-prev-outer">
                <?php 
                 /*   $this->headLink( array( //'rel' => 'prev',
                                            'href' => HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('bespaarwijzer').'/'.$this->prevLink
                                          )
                                   ); */
                ?>
                <a class="left" href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('bespaarwijzer').'/'.$this->prevLink; ?>">
                  <?php if($this->prevLink !=""){?>
                    <img class="arrow-left" src="<?php echo HTTP_PATH; ?>public/images/front_end/guide-arrows-prev.png" border="0">
                  <?php } ?>
                  <div class="guide-prev-img">
                    <?php if($this->prevImage !=""){?>
                      <img src="<?php echo $this->prevImage;?>" alt="<?php echo $this->prevTitle;?>">
                    <?php } ?>
                  </div>
                  <div class="guide-prev-row-left">
                    <?php if($this->prevLink !=""){?>
                      <h4><?php echo (strlen($this->prevTitle) > 38 ) ? trim(substr($this->prevTitle, 0, 38)).'...' : $this->prevTitle;?></h4>
                    <?php } ?>
                    <?php if($this->prevDesc !=""){?>
                      <span><?php echo (strlen($this->prevDesc) > 125) ? strip_tags(trim(substr($this->prevDesc, 0, 125))).'...' : strip_tags($this->prevDesc);?></span>
                    <?php }?>
                  </div>
                </a>
                <?php 
                /*    $this->headLink( array( //'rel' => 'next',
                                            'href' => HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('bespaarwijzer').'/'.$this->nextLink
                                          )
                                   );*/
                ?>
                <a class="right" href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('bespaarwijzer').'/'. $this->nextLink; ?>">
                <img class="arrow-right" src="<?php echo  HTTP_PATH; ?>public/images/front_end/guide-arrows-next.png" border="0">
                        <div class="guide-next-img">
                           <?php if($this->nextImage !=""){?>
                           <img src="<?php echo $this->nextImage;?>" alt="<?php echo $this->nextTitle;?>">
                           <?php }?>
                      </div>
                        <div class="guide-prev-row-right">
                      <?php if($this->nextLink !=""){?>
                       <h4><?php echo (strlen($this->nextTitle) > 38 ) ? trim(substr($this->nextTitle, 0, 38)).'...' : $this->nextTitle;?></h4>
                       <?php } ?>
                       
                       <?php if($this->nextDesc !=""){?>
                      <span><?php echo (strlen($this->nextDesc) > 125) ? strip_tags(trim(substr($this->nextDesc, 0, 125))).'...' : strip_tags($this->nextDesc);?></span>
                      <?php }?>
                      </div>
                </a>
            </div>
            <!-- Next/Previous div ends here -->
        
        </div>

        <!-- Disqus -->
        <div class="guide-outer-new">
            <div id="disqus_thread"></div>
            <script type="text/javascript">
                /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
                var disqus_shortname = '<?php echo $this->translate('disqus_shortname');?>'; // required: replace example with your forum shortname

                /* * * DON'T EDIT BELOW THIS LINE * * */
                (function() {
                    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                })();
            </script>
            <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
            <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
        </div>
        <!-- End disqus -->
      <!-- Guide Outer Ends -->
      </div>
        
<?php else:?>
          
<center>
    <div style='border:solid 1px gray'>
        <h2>
            <?php //echo $this->message 
             echo  $this->translate(' Oops This Page Does Not Exist');
             ?>
        </h2>
    </div>
</center>
    
<?php endif;?>

