<?php 
$this->minifyHeadScript()->prependFile ( HTTP_PATH."public/js/front_end/socialmedia.js" ); 
     $page = $this->page;
     echo $this->partial('partials/_headerSearch.phtml',array('breadcrumb' => null)); 
	 $permaLink = $this->permaLink;
     if(!empty($page)){
       ?>
        <!-- Bespaarwijzer Starts -->
        <div class="white-bg">
          <div class="new-outer">
            <div class="bespaarwijzer-outer">
              <div class="bespaarwijzer-left">
              	<div class="bespaarwijzer-left-heading">
              	  <h1><?php  echo $page[0]['pageTitle']; ?></h1>
              	</div>
                <div class="bespaarwijzer-left-col1">
                  <?php  
                    
                   	$pagelogo = PUBLIC_PATH_CDN.$page[0]['logo']['path'].'thum_extra_large_'.$page[0]['logo']['name'];
                 	
                       ?>
                  <div>
                    <?php echo $page[0]['content']; ?>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- Bespaarwijzer Ends -->
         
         <!-- Blue Listing Outer Starts -->
          <div class="white-bg">
            <div class="new-outer">
              <div class="blue-listing-outer">
                <div class="popular-kortings-heading mt20 clr">
                  <h2><?php echo $this->translate('CAT');?></h2>
                </div>
                 <?php 
                    if(!empty($this->allMoneySavingArticles)){
                  ?>
                  <?php 
                    $ms =  array();
                    $ms = $this->allMoneySavingArticles[0]['moneysaving'];
                    $ret = 1;
                    for($i=0;$i < count($ms);$i++) {
                  ?>
                <!-- Blue Listing Inner Starts -->
                <div class="blue-listing-inner">
                  <div class="blue-listing-heading">
                    <?php $link = HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('bespaarwijzercat').'/'. $ms[$i]['articlecategory'][0]['permalink']; ?>
                    <h3>
                      <?php echo $ms[$i]['articlecategory'][0]['name']; ?>
                    </h3>
                  </div>
                  <div class="blue-listing">
                    <ul>
                    <?php 

                    for($j=0;$j < count($ms[$i]['refarticlecategory']);$j++) {
                    	
                    	$artId = $ms[$i]['refarticlecategory'][$j]['articles']['id'];
                    	$alink = HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('bespaarwijzer').'/'. $ms[$i]['refarticlecategory'][$j]['articles']['permalink'];
                    ?>
                      <li>
                        <h3>
                          <a href="<?php echo $alink; ?>" onClick="javascript:viewCounter('onclick', 'article', <?php echo $artId; ?>);"><?php echo $ms[$i]['refarticlecategory'][$j]['articles']['title']; ?>
                          </a>
                        </h3>
                      </li>
                    	<?php 
                        }
                    	?>
                    </ul>
                    </div>
                  </div>
                  <?php if($ret%4 == 0){
                  		?>
                  		<br>
                  <!-- Separator Starts -->
                  	<div class="autosep">&nbsp;</div>
                  <!-- Separator Ends --> 
                  		<?php
                  		}	
                  ?>
                  <!-- Blue Listing Inner Ends -->

                  <?php $ret++; }
                  } else {
                  echo $this->translate("No Records Found");
                  }
                  ?>                
              </div>
            </div>
            
            <!-- Separator Starts -->
            <div class="separator mt20">&nbsp;</div>
            <!-- Separator Ends --> 

          <!-- white bg ends--> 
          </div> 

	       <!-- Common Div Starts -->
          <div class="new-outer">
            <div class="common-div">
              <div class="popular-kortings-heading mt20 clr">
                <h2><?php echo $this->translate('MEEST GELEZEN BESPAAR WIJZERS');?></h2>
              </div>
              <div class="common-div">
              <?php 
              if(!empty($this->mostRead)){
              	echo $this->partialLoop('partials/mostReadAcls.phtml',$this->mostRead); 
                } else {
              	echo $this->translate("No Records Found");
                }
              ?>
              </div>
            </div>
          </div>
     <!-- Common Div Ends -->
     <?php } ?>