<?php 
$this->minifyHeadLink()->prependStylesheet("/public/css/front_end/saving.css");
$this->minifyHeadScript()->prependFile("public/js/front_end/socialMedia.js");
$pageDetails = $this->pageDetails;
$recentlyAddedArticles = $this->recentlyAddedArticles;
$categoryWiseArticles = $this->categoryWiseArticles;
?>
<div class="banner-block">
    <?php $pageImage = PUBLIC_PATH_CDN.$pageDetails[0]['logo']['path'].'thum_extra_large_'.$pageDetails[0]['logo']['name']; ?>
    <img class="image" src="/public/images/banner-06.jpg" alt="image description">
    <!--<img class='image' src="<?php  echo $pageImage;?>" alt="<?php echo $pageDetails[0]['pageTitle']; ?>"/>-->
    <div class="frame-image">
        <div class="container">
            <h1 class="flipit-text"><?php $this->translate('Flipit plus');?></h1>
        </div>
    </div>
    <div class="container">
        <div class="text-box">
            <p>
            <?php echo  $this->translate('Flipit.com Plus is our magazine in which we want to do one thing only: help out all the consumers out there in every way possible');?>
            </p>
        </div>
        <div class="block">
            <div class="caption"><span><?php echo $this->translate('Featured savings');?></span></div>
            <div class="carousel">
                <div class="holder">
                    <div class="mask">
                        <div class="slideset">
                            <div class="slide active" id="first">
                                <img class="aligncenter"  src="<?php echo PUBLIC_PATH_CDN.$this->mostReadArticles[0]['articles']['thumbnail']['path'].$this->mostReadArticles[0]['articles']['thumbnail']['name']; ?>" alt="<?php echo $this->mostReadArticles[0]['articles']['title'];  ?>">
                                <h1><?php echo $this->mostReadArticles[0]['articles']['title']; ?></h1>
                                <p>
                                   <?php echo $this->mostReadArticles[0]['articles']['metadescription']; ?>
                                </p>
                            </div>
                            <div class="slide"  id="second">
                                <img class="aligncenter" src="<?php echo PUBLIC_PATH_CDN.$this->mostReadArticles[1]['articles']['thumbnail']['path'].$this->mostReadArticles[1]['articles']['thumbnail']['name']; ?>" alt="<?php echo $this->mostReadArticles[1]['articles']['title'];  ?>">
                                <h1><?php echo $this->mostReadArticles[1]['articles']['title']; ?></h1>
                                <p>
                                    <?php echo $this->mostReadArticles[1]['articles']['metadescription']; ?>
                                </p>
                            </div>
                            <div class="slide" id="third">
                                <img class="aligncenter" src="<?php echo PUBLIC_PATH_CDN.$this->mostReadArticles[2]['articles']['thumbnail']['path'].$this->mostReadArticles[2]['articles']['thumbnail']['name']; ?>" alt="<?php echo $this->mostReadArticles[2]['articles']['title'];  ?>">
                                <h1><?php echo $this->mostReadArticles[2]['articles']['title'];?></h1>
                                <p>
                                    <?php echo $this->mostReadArticles[2]['articles']['metadescription']; ?>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <ul class="switcher">
                <?php
                   if (!empty($this->mostReadArticles)) {
                        echo $this->partial('partials/_mostReadArticles.phtml',array('articles'=>$this->mostReadArticles)); 
                    } else {
                    echo $this->translate("No Records Found");
                    } 
                ?>
                </ul>
            </div>
        </div>
    </div>
</div>
<main role="main" id="main">
    <div class="container content-box">
        <header class="heading-bar">
            <h2><?php echo $this->translate('Recently added');?></h2>
        </header>
        <div class="item-block">
            <div class="holder">
                 <?php foreach($recentlyAddedArticles as $recentlyAddedArticle) { ?>
                <div class="item">
                    <img src="<?php echo PUBLIC_PATH_CDN.$recentlyAddedArticle['ArtIcon']['path'].$recentlyAddedArticle['ArtIcon']['name'];?>" alt="<?php echo $recentlyAddedArticle['title'];?>">
                    <div class="box">
                        <div class="caption-area">
                            <span class="caption">
                            <?php echo $recentlyAddedArticle['title'];?>
                            </span>
                        </div>
                        <a href="javascript:void(0);" onclick = "viewCounter('onclick', 'article', <?php echo $recentlyAddedArticle['id']; ?>);" class="link"><?php echo $this->translate('more');?> &#8250;</a>
                    </div>
                </div>
                <?php } ?>          
            </div>
        </div>
        <header class="heading-bar">
            <h2><?php echo $this->translate('From the blog');?></h2>
        </header>
        <div class="item-block">
            <div class="holder">
                <?php foreach($categoryWiseArticles['blog'] as $categoryWiseArticle) { ?>
                <div class="item">
                     <img src="<?php echo PUBLIC_PATH_CDN.$categoryWiseArticle['ArtIcon']['path'].$categoryWiseArticle['ArtIcon']['name'];?>" alt="<?php echo $categoryWiseArticle['title'];?>">
                    <div class="box">
                        <div class="caption-area">
                            <span class="caption">
                              <?php echo $categoryWiseArticle['title'];?>
                            </span>
                        </div>
                        <a href="javascript:void(0);" onclick = "viewCounter('onclick', 'article', <?php echo $categoryWiseArticle['id']; ?>);" class="link"><?php echo $this->translate('More');?> &#8250;</a>
                    </div>
                </div>
                <?php } ?>
            </div>
        </div>
        <header class="heading-bar">
            <h2><?php echo  $this->translate('Saving tips');?></h2>
        </header>
        <div class="item-block">
            <div class="holder">
                <?php foreach($categoryWiseArticles['savingtip'] as $categoryWiseArticle) { ?>
                <div class="item">
                    <img src="<?php echo PUBLIC_PATH_CDN.$categoryWiseArticle['ArtIcon']['path'].$categoryWiseArticle['ArtIcon']['name'];?>" alt="<?php echo $categoryWiseArticle['title'];?>">
                    <div class="box">
                        <div class="caption-area">
                            <span class="caption">
                             <?php echo $categoryWiseArticle['title'];?>
                            </span>
                        </div>
                        <a href="javascript:void(0);" onclick = "viewCounter('onclick', 'article', <?php echo $categoryWiseArticle['id']; ?>);" class="link"><?php echo $this->translate('More');?> &#8250;</a>
                    </div>
                </div>
                 <?php } ?>
            </div>
        </div>
    </div>
</main>
<footer class="bottom-panel">
    <div class="container">
        <div class="holder">
            <span class="text"><?php echo  $this->translate('Satisfied with the new Kortingscode.nl? Like us and win great prizes');?>
            </span>
            <ul class="share-list">
                <?php
               echo FrontEnd_Helper_viewHelper::socialMediaWidget('','article');
               ?>
            </ul>
        </div>
    </div>
</footer>




