<?php 
	if(count($this->partialCounter >0)){
		$cls = 'iphone-col1-none';
		if($this->partialCounter > 3){
			
			$cls = 'iphone-col1-top';
		}
	}
?>
<div class="<?php echo $cls;?>">
    <div class="<?php echo $cls;?>-left">
    	<div class="<?php echo $cls;?>-left-img">
        <?php  	
 			$img = PUBLIC_PATH_CDN.$this->thumbnail['path'].'thum_article_samll_'.$this->thumbnail['name'];
		
		$mlink = HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('bespaarwijzer').'/'. $this->permalink;
		$nameArr = explode(' ', $this->authorname);
		$profileLink = HTTP_PATH_LOCALE."about/profile/id/".$this->authorid;
		$name = substr($nameArr[0],0, 5);
		$martId = $this->id;
        ?>
        <a href="<?php echo $mlink; ?>" onClick="javascript:viewCounter('onclick', 'article', <?php echo $martId; ?>);">
	        <img src="<?php echo $img; ?>" alt="<?php echo $this->title; ?>"/>
	   </a>
        </div>
        
      </div>
    <div class="<?php echo $cls;?>-right">
    	<div class="<?php echo $cls; ?>-right-text1 text-blue">
        	<h3>	
                <a title='<?php echo $this->title; ?>' class="text-blue-link" href="<?php echo $mlink; ?>" onClick="javascript:viewCounter('onclick', 'article', <?php echo $martId; ?>);">
        		<?php 
            		if(strlen($this->title) > 35):
            		
            			echo substr($this->title, 0,35).'..';
            		
            			else: 
            			
            			echo $this->title;
            			
            		endif;
            		?>
        		</a>
            </h3>
         </div>
        <div class="iphone-col1-right-text2">
			<?php 
			
			if(isset($this->chapters[0])){
					
				if($this->chapters[0]['content']!=null || $this->chapters[0]['content']!='undefined' || $this->chapters[0]['content']!=''){
					$allowed_tags = '<p>'; 
					$description = $this->chapters[0]['content']; 
					$only = strip_tags($description);
					
					if(strlen($only) > 70) { 
						echo substr($only, 0,70).'...';
					} else {
						
						echo $only;
					} 
				}
			}else{
			
			}
			?>
      	</div>
     </div>
</div> 
