<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>
<?php echo $this->translate('404 error - Page does not exist');?></title>
<?php echo $this->headLink ()->appendStylesheet ( HTTP_PATH . "public/css/front_end/404.css" );?>
<!--[if lte IE 7]>
<?php echo $this->headLink ()->appendStylesheet ( HTTP_PATH . "public/css/front_end/ie.css" );?>
<![endif]-->
<!--[if IE 8]>
<?php echo $this->headLink ()->appendStylesheet ( HTTP_PATH . "public/css/front_end/ie8.css" );?>
<![endif]-->

<!--[if IE]>
<?php echo $this->headScript()->appendFile(HTTP_PATH . "public/js/front_end/DD_belatedPNG_0.0.7a.js");?>
<?php echo $this->headScript()->appendFile(HTTP_PATH . "public/js/front_end/png_fix_elements.js");?>
<![endif]-->
</head>
<body>
    <div id="screen-404">
        <h2><?php echo $this->translate('Sorry - De opgevraagde pagina bestaat helaas niet');?></h2>
      <p><?php echo $this->translate('Wellicht helpt een van onderstaande links je verder:');?></p>
      <ul>
        <li><a href="javascript: history.go(-1)"><?php echo $this->translate('Terug naar de vorige pagina');?></a></li>
        <li><a href="/"><?php echo $this->translate('Naar de homepage');?></a></li>
        <li><a href="<?php echo  HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('veelgestelde-vragen')?>"><?php echo $this->translate('Naar veelgestelde vragen');?></a></li>
      </ul>
      <p><?php echo $this->translate('Populair');?></p>
      <ul>
        <li><a href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('alle-winkels'); ?>"><?php echo $this->translate('Alle winkels');?></a></li>
        <li><a href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('populair');?>"><?php echo $this->translate('Populaire Codes');?></a></li>
        <li><a href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('nieuw');?>"><?php echo $this->translate('Nieuwe Codes');?></a></li>
        <li><a href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('plus');?>"><?php echo $this->translate('plus');?></a></li>
        <li><a href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('categorieen');?>"><?php echo $this->translate('Categorie&euml;n');?></a></li>
      </ul>
    </div>
</body>
</html>