<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>
<?php echo $this->translate('404 error - Page does not exist');?></title>
<?php echo $this->headLink ()->appendStylesheet ( HTTP_PATH . "public/css/front_end/all.css" );?>
</head>
<body class="page404">
  <div class="bg-stretch">
    <img src="<?php echo HTTP_PATH; ?>public/images/front_end/img-46.jpg" alt="" />
  </div>
  <div id="wrapper">
    <main role="main" id="main">
      <div class="container">
        <div class="section404">
          <strong class="logo"><a href="#"><?php echo $this->translate('FlipIt'); ?></a></strong>
          <div class="row-block">
            <div class="text-block">
              <h1><?php echo $this->translate('Sorry, that page doesn’t exist');?>!</h1>
              <p><?php echo $this->translate('Whoops, looks like you’ve made a little mistake').'. '.$this->translate('No worries, return to our'); ?><a href="#"><?php echo $this->translate('home page');?></a> <?php echo $this->translate('or search for other discounts');?></p>
              <div class="search-box">
                <form class="search-form" role="form">
                  <input type="text" class="form-control" placeholder="Type in a Store e.g.  Avis">
                  <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
                </form>
              </div>
            </div>
            <div class="sponsors-block">
              <h2><?php echo $this->translate('Flipit! Get ready to flip over a great deal');?>!</h2>
              <ul>
                <li><a href="#"><img width="90" height="45" alt="nike" src="images/logo-04.png"></a></li>
                <li><a href="#"><img width="90" height="45" alt="adidas" src="images/logo-05.png"></a></li>
                <li><a href="#"><img width="90" height="45" alt="voetbalshop.nl" src="images/logo-06.png"></a></li>
                <li><a href="#"><img width="90" height="45" alt="nike" src="images/logo-04.png"></a></li>
                <li><a href="#"><img width="90" height="45" alt="decathlon" src="images/logo-09.png"></a></li>
                <li><a href="#"><img width="90" height="45" alt="perry" src="images/logo-07.png"></a></li>
                <li><a href="#"><img width="90" height="45" alt="bever" src="images/logo-08.png"></a></li>
                <li><a href="#"><img width="90" height="45" alt="adidas" src="images/logo-05.png"></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </main>
    <footer id="footer">
      <div class="container add-block">
        <ul class="language">
          <li><a href="#">german</a></li>
          <li><a href="#" class="ico-2"></a></li>
          <li><a href="#" class="ico-3"></a></li>
          <li><a href="#" class="ico-4"></a></li>
          <li><a href="#" class="ico-5"></a></li>
          <li><a href="#" class="ico-6"></a></li>
          <li><a href="#" class="ico-7"></a></li>
          <li><a href="#" class="ico-8"></a></li>
        </ul>
        <strong class="logo"><a href="#"><?php echo $this->translate('FlipIt'); ?></a></strong>
        <span class="copy"><?php echo $this->translate('Copyright &copy; 2009-2014 Imbull BV'); ?>.</span>
      </div>
    </footer>
  </div>
</body>
</html>