<?php 
$this->headTitle()->append($this->translate('Import Excel for Offers'));
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/importoffers.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
$this->headLink()->appendStylesheet(PUBLIC_PATH . "css/jquery-ui-1.8.16.custom.css");
?>
<div class='wrap columns-2'>
<?php 
    if( $this->messageError !='') { ?>
        <br>
        <div class ="mainpage-content-colorbox success">
            <span class="errorserver"><?php echo $this->messageError; ?></span>
        </div>
<?php } ?>
</div>        
<div class="wrap columns-2" id="addNewKeyword">
    <h1>
        <?php echo $this->translate('Import Excel for Offers'); ?>
        <button class="btn ml10" type="button" onClick="window.location.href='<?php echo HTTP_PATH ;?>admin/offer'"><?php echo $this->translate('Cancel'); ?></button>
    </h1>
    <form method="POST" enctype="multipart/form-data" name="addOffersForm" id="addOffersForm">
        <div id="poststuff" class="metabox-holder has-right-sidebar">
            <div id="post-body">
               <div>
                    <div class="mainpage-content">
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left"><span><strong><?php echo $this->translate('Upload Excel file for import'); ?></strong></span>
                            </div>
                            <div class="mainpage-content-right">
                                <input type="file" onchange="checkFileType(event)" class=" width-204 ignore" name="excelFile" id="excelFile">
                                <span><?php echo $this->translate('.xlsx file upto 2MB of Size only'); ?></span>
                            </div>
                            <div class="mainpage-content-left offer-import-customized" id="imagerrorDiv"></div>
                        </div>
                    </div>
                </div>
            </div>
            <br class="clear">
        </div>
        <div class="mainpage-content-colorbox">
            <button type="button" id="importOffers" class="btn btn-large btn-primary fl"><?php echo $this->translate('IMPORT'); ?></button>
            <a href="javascript:void(0);" onclick="window.location.href='<?php echo HTTP_PATH ;?>admin/offer'" class="fl m10" ><strong><?php echo $this->translate('CANCEL'); ?></strong></a>
            <a href="<?php echo HTTP_PATH ;?>admin/offer/empty-offer-xlx" class="fl m10" ><strong><?php echo $this->translate('Download empty xlsx'); ?></strong></a>
        </div>
    </form>
</div>