<?php 
 $this->headMeta('keyword', 'Description');
 $this->headTitle()->append($this->translate('Reports'));
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
 $this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/jquery-ui-1.8.16.custom.css" );
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/Highcharts-4.2.1/js/highcharts.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/Highcharts-4.2.1/js/highcharts-3d.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/Highcharts-4.2.1/js/modules/exporting.js");
?>

<div id="chainList">
    <div class="wrap columns-2">
        <h1 class="fl"><?php echo $this->translate('Reports'); ?></h1>
        <div class="clear"></div>
        <div class="top_navigation">
            <ul>
                <li><a href="/admin/reports" class="selected_nav">Offers</a></li>
                <li><a href="/admin/reports/shops">Shops</a></li>
                <li><a href="/admin/reports/visitors">Visitors</a></li>
                <li><a href="/admin/reports/emails">Emails</a></li>
                <li><a href="/admin/reports/traffic">Traffic</a></li>
                <li><a href="/admin/reports/global">Global</a></li>
            </ul>
        </div>
        <div class="mainpage-content">
            <div class="clear"></div>
            <div id="onlineOfferContainer" style="height: 30%; width:49%; float:left;"></div>
            <div id="totalCouponsInYearContainer" style="height: 30%; width:49%;"></div>
            <div class="clear"></div>
            <br><br><br><br>
            <div id="monthlyOfferContainer" style="height: 500px"></div>
        </div>

    </div>
</div>

<script type="text/javascript">
$(function () {
    $('#onlineOfferContainer').highcharts({
        chart: {
            type: 'pie',
            options3d: {
                enabled: true,
                alpha: 45
            }
        },
        credits: {
            enabled: false
        },
        title: {
            text: 'Total Online Offers'
        },
        subtitle: {
            text: 'Current Online offers'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                depth: 45,
                innerSize: 120,
                dataLabels: {
                    enabled: true,
                    format: '{point.name}: {point.y}'
                }
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
            pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y}</b><br/>'
        },
        series: [{
            name: 'Online Count',
            data: [
                ['Coupons', 1200],
                ['Sales', 700],
                ['Printable Offers', 100],
                ['Exclusive', 200]
            ]
        }]
    });

    $('#totalCouponsInYearContainer').highcharts({
        chart: {
            type: 'pie',
            options3d: {
                enabled: true,
                alpha: 45
            }
        },
        credits: {
            enabled: false
        },
        title: {
            text: 'Total Offers Added'
        },
        subtitle: {
            text: 'In last 12 Months'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                depth: 45,
                innerSize: 120,
                dataLabels: {
                    enabled: true,
                    format: '{point.name}: {point.y}'
                }
            },
            series: {
                dataLabels: {
                    enabled: true,
                    format: '{point.name}: {point.y}'
                }
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
            pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y}</b><br/>'
        },
        series: [{
            name: 'Delivered amount',
            data: [
                ['Coupons', 2880],
                ['Sales', 700],
                ['Printable Coupons', 140],
                ['Exclusive', 410]
            ]
        }]
    });

    $('#monthlyOfferContainer').highcharts({
        chart: {
            type: 'column',
            options3d: {
                enabled: true,
                alpha: 0,
                beta: 0,
                viewDistance: 25,
                depth: 40
            },
            marginTop: 80,
            marginRight: 0
        },
        title: {
            text: 'Offers transaction in last 6 months'
        },
        xAxis: {
            categories: ['January', 'Feb', 'March', 'April', 'May', 'June']
        },
        yAxis: {
            allowDecimals: false,
            min: 0,
            title: {
                text: 'Number of offers added/expired '
            }
        },
        credits: {
            enabled: false
        },
        tooltip: {
            headerFormat: '<b>{point.key}</b><br>',
            pointFormat: '<span style="color:{series.color}">\u25CF</span> {series.name}: {point.y} / {point.stackTotal}'
        },
        plotOptions: {
            column: {
                stacking: 'normal',
                depth: 20
            }
        },
        series: [{
            name: 'Coupons Added',
            data: [235, 352, 401, 730, 292, 309],
            stack: 'added',
            color: Highcharts.getOptions().colors[0]
        }, {
            name: 'Sales Added',
            data: [332, 254, 214, 132, 155, 117],
            stack: 'added',
            color: Highcharts.getOptions().colors[3]
        }, {
            name: 'Printable Added',
            data: [112, 59, 69, 82, 71, 101],
            stack: 'added',
            color: Highcharts.getOptions().colors[2]
        }, {
            name: 'Offers Expired',
            data: [92, 45, 49, 31, 67, 21],
            stack: 'expired',
            color: Highcharts.getOptions().colors[4]
        }, {
            name: 'Sales Expired',
            data: [92, 31, 69, 51, 52, 31],
            stack: 'expired',
            color: Highcharts.getOptions().colors[7]
        }, {
            name: 'Printable Expired',
            data: [92, 71, 89, 85, 39, 19],
            stack: 'expired',
            color: Highcharts.getOptions().colors[6]
        }]
    });
});


</script>