<?php 
$articleDetails = $this->artcileDetails;
$userDetails = $this->userDetails;
$profileLink = $this->profileLink;
$authorName = FrontEnd_Helper_AuthorPartialFunctions::getAuthorName($this->firstName, $this->lastName);
$articleUpdatedAtDate = $this->articleUpdatedAtDate;
$byAuthorName[0] = '';
$byAuthorName[1] = '';
if (!$authorName == '') {
    $byAuthorName[0] = $this->translate('By');
    $byAuthorName[1] = $authorName;
}
?>
<section class="post-box">
    <header class="meta">
        <h1><?php echo $articleDetails['title'];?></h1>
        <p>
            <?php echo $byAuthorName[0]; ?>
            <a href="<?php echo $profileLink; ?>">
                <?php echo $byAuthorName[1];?></a> <?php echo empty($byAuthorName[1]) ? '' : '-'; 
                echo $articleUpdatedAtDate; ?> &nbsp; | &nbsp;   
            <a href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('link_plus')?>">
                <?php echo $this->translate('All Plus');?></a>
        </p>
    </header>
<?php  
    if (!empty($articleDetails['chapters'])) {
        foreach ($articleDetails['chapters'] as $articleChapter) :                    
            echo '<h2 id="'.$articleChapter['id'].'">'.$articleChapter['title'].'</h2>';
            echo $articleChapter['content'];
        endforeach;
    }
?> 
</section>