 <span class='share-buttons'>
    <a target="_blank" 
        href="<?php echo "http://www.facebook.com/sharer.php?u=".$this->shareUrl;?>">
        <img alt="Facebook" title="Facebook"
            src="<?php echo HTTP_PATH.'public/images/front_end/facebookblack.png';?>">
    </a>
    <a target="_blank" 
        href="<?php echo "http://twitter.com/share?url=".$this->shareUrl;?>">
        <img alt="Twitter" title="Twitter"
            src="<?php echo HTTP_PATH.'public/images/front_end/twitter-icon.jpg';?>">
    </a>
</span>