<?php 
$articleDetails = $this->artcileDetails;
$userDetails = $this->userDetails;
$profileLink = $this->profileLink;
$firstName = $this->firstName;
$lastName = $this->lastName;
$articleUpdatedAtDate = $this->articleUpdatedAtDate;
if(empty($firstName) || empty($lastName)) {
    $byAuthorName = '';
} else {
    $byAuthorName = $this->translate('By') . ' ' . $firstName . ' ' . $lastName;
}
?>
<section class="post-box">
    <header class="meta">
        <input type = "hidden" id = "" value = "<?php echo $articleDetails['id']; ?>"/>
        <h1><?php echo $articleDetails['title'];?></h1>
        <p>
            <a href="<?php echo $profileLink; ?>">
                <?php echo $byAuthorName;?></a> <?php echo empty($byAuthorName) ? '' : '- '; 
                echo $articleUpdatedAtDate; ?> &nbsp; | &nbsp;   
            <a href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('plus')?>">
                <?php echo $this->translate('All Plus');?></a>
        </p>
    </header>
<?php  
    if (!empty($articleDetails['chapters'])) {
        foreach ($articleDetails['chapters'] as $articleChapter) :                    
            echo '<h2 id="'.$articleChapter['id'].'">'.$articleChapter['title'].'</h2>';
            echo $articleChapter['content'];
        endforeach;
    }
?> 
</section>