<?php 
$articleDetails = $this->artcileDetails;
$userDetails = $this->userDetails;
$profileLink = $this->profileLink;
$authorName = FrontEnd_Helper_AuthorPartialFunctions::getAuthorName($this->firstName, $this->lastName);
$articleUpdatedAtDate = $this->articleUpdatedAtDate;
$byAuthorName[0] = '';
$byAuthorName[1] = '';
if (!$authorName == '') {
    $byAuthorName[0] = $this->translate('By');
    $byAuthorName[1] = $authorName;
}
$websiteName = FrontEnd_Helper_viewHelper::getWebsiteName(LOCALE);
$articleShareButtons = '';
if (!empty($articleDetails['permalink'])) {
    $articleShareUrl = HTTP_PATH_LOCALE 
        . FrontEnd_Helper_viewHelper::__link('link_plus'). '/'.$articleDetails['permalink'];
    $articleShareButtons = $this->partial(
        'plus/_articleShareButtons.phtml',
        array(
            'shareUrl' => $articleShareUrl,
            'title' => mb_substr($articleDetails['title'], 0, 50)
        )
    );
}
?>
<section class="post-box">
    <header class="meta meta-parding">
        <h1><?php echo $articleDetails['title'];?></h1>
    </header>
    <header class="meta">
        <div class="btn-area">
            <?php echo $articleShareButtons;?>
        </div>
        <p class="article-detail">
            <?php echo $byAuthorName[0]; ?>
            <a class='black-link-bold' href="<?php echo $profileLink; ?>"><?php echo $byAuthorName[1];?></a>
            <?php echo empty($byAuthorName[1]) ? '' : '&nbsp;'; ?>
            <span class='date'><?php echo '&nbsp;&nbsp;'.$articleUpdatedAtDate; ?></span>
            <?php echo '&nbsp; | &nbsp;'. $this->translate('back to') . " ";?>   
            <a href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('link_plus')?>">
            <?php echo $websiteName . " ". $this->translate('plus');?></a>
        </p>
    </header>
<?php  
    if (!empty($articleDetails['articleChapter'])) {
        foreach ($articleDetails['articleChapter'] as $articleChapter) :                    
            echo '<h2 id="'.$articleChapter['id'].'">'.$articleChapter['title'].'</h2>';
            $chapters = preg_replace('/(<a\b[^><]*)>/i', '$1 style="color: #0077cc;text-decoration: underline;">', $articleChapter['content']);
            echo $chapters;
        endforeach;
    }
?> 
    <div class="btn-area add">
        <?php echo $articleShareButtons;?>
    </div>
</section>