<div class="carousel-area">
	<div class="container">
		<div class="flexslider carousel">
			<div class="mask">
				<div class="slideset">
				<?php
					foreach ($this->popularStores as $popularStore) { 
						$popularStoreImage =
                			PUBLIC_PATH_CDN.ltrim($popularStore['shop']['logo']['imgpath'], '/')
                			."thum_medium_".$popularStore['shop']['logo']['imgname'];  
        		?>
	        			<div class="slide">
							<a href="<?php echo HTTP_PATH_LOCALE.$popularStore['shop']['permaLink'];?>">
								<img src="<?php echo $popularStoreImage; ?>" width="132" height="75"
								alt="<?php echo $popularStore['shop']['name']; ?>">
							</a>
						</div>
				<?php
					}
				?>		
				</div>
			</div>
		</div>
	</div>
</div>