<?php
$userDetails = $this->userDetails;
$profileLink = $this->profileLink;
$firstName = $this->firstName;
$lastName = $this->lastName;
$articleUpdatedAtDate = $this->articleUpdatedAtDate;
?>
<section class="news-block">
    <?php 
        if(!empty($this->recentlyAddedArticles)) {
            foreach($this->recentlyAddedArticles as $recentlyAddedArticle) :
    ?>            
    <article class="box">
        <span class="image">
            <img src="<?php echo PUBLIC_PATH_CDN.$recentlyAddedArticle['ArtIcon']['path'].$recentlyAddedArticle['ArtIcon']['name'];?>" alt="<?php echo $recentlyAddedArticle['title'];?>" width="118" height="118" />
        </span>
        <div class="text-box">
            <h1>
                <a href="<?php echo $recentlyAddedArticle['title'];?>"><?php echo $recentlyAddedArticle['title'];?></a>
            </h1>
            <p>
                <em><?php echo $this->translate('by ');?>
                    <a href="<?php echo $profileLink; ?>"><?php echo $firstName . " " . $lastName;?></a>, <?php echo $articleUpdatedAtDate; ?>
                </em>
            </p>
            <a href="<?php echo $recentlyAddedArticle['title'];?>" class="more">
                <span><?php echo $this->translate('Read More');?></span>
            </a>
        </div>
    </article>
    <?php    
            endforeach;
        }
    ?>  
</section>