<section class="news-block">
    <?php 
        if(!empty($this->recentlyAddedArticles)) {
            foreach($this->recentlyAddedArticles as $recentlyAddedArticle) :
                $userInformationObject = new User();
                $userDetails =  $userInformationObject->getUserDetails($recentlyAddedArticle['authorid']);
                $profileLink = HTTP_PATH_LOCALE.FrontEnd_Helper_viewHelper::__link("link_redactie")."/". $userDetails['slug'];
                $articleUpdatedAtDate = new Zend_Date($recentlyAddedArticle['updated_at']);
                $articleUpdatedAtDate = $articleUpdatedAtDate->get(Zend_Date::DATE_LONG);
    ?>            
    <article class="box">
        <span class="image">
            <a href="<?php echo HTTP_PATH_LOCALE.'plus/'.$recentlyAddedArticle['permalink'];?>">
                <div class="latest-article-thumbnail"><img src="<?php echo PUBLIC_PATH_CDN.$recentlyAddedArticle['thumbnail']['path'].
                $recentlyAddedArticle['thumbnail']['name'];?>" alt="<?php echo $recentlyAddedArticle['title'];?>" 
                height="118" /></div>
            </a>    
        </span>
        <div class="text-box">
                    
            <h1>
                <a href="<?php echo HTTP_PATH_LOCALE.'plus/'.$recentlyAddedArticle['permalink'];?>">
                    <?php echo $recentlyAddedArticle['title'];?>
                </a>
            </h1>
            <p>
                <?php
                    if(empty($recentlyAddedArticle['authorname'])) {
                        $byAuthorName = '';
                        $authorRedirectLink =  '';
                    } else {
                        $byAuthorName = $recentlyAddedArticle['authorname'];
                        $authorRedirectLink =  '<a href="'.$profileLink.'">
                        '.$recentlyAddedArticle['authorname'].'</a>, ';
                    }
                ?>
                <em>
                    <?php 
                        echo empty($byAuthorName) ? '' : $this->translate('by ');
                        echo $authorRedirectLink;
                        echo $articleUpdatedAtDate; 
                    ?>
                </em>
            </p>
            <a href="<?php echo  HTTP_PATH_LOCALE.'plus/'.$recentlyAddedArticle['permalink'];?>" class="more">
                <span><?php echo FrontEnd_Helper_viewHelper::__translate('Read More');?></span>
            </a>
        </div>
    </article>
    <?php    
            endforeach;
        }
    ?>  
</section>