<ol class="alt-list clear-both">
    <?php
        if(!empty($this->topPopularOffers)) {
            foreach($this->topPopularOffers as $topPopularOffer) :
                $offerType =
                    $topPopularOffer['exclusiveCode'] == 1 ? '<mark>'. $this->translate('Exclusive').'</mark>' : '';
                    $redirectUrlToStore = LOCALE != '' ? HTTP_PATH_LOCALE : HTTP_PATH;  
    ?> 
    <li>
        <?php
            echo $offerShopPermalinkAnchor = FrontEnd_Helper_viewHelper::getOfferPopupLink($topPopularOffer);
        ?>    
            <strong class="title"><?php echo $topPopularOffer['shopOffers']['name'].' '.$offerType; ?></strong>
            <?php echo $topPopularOffer['title'];?>
        </a>    
     </li>
    <?php    
            endforeach;
        }
    ?>  
</ol>