<?php 
$this->minifyHeadScript()->prependFile("public/js/front_end/socialmedia.js");
$this->minifyHeadScript()->prependFile("public/js/front_end/moneySaving.js");
$this->minifyHeadScript()->prependFile("public/js/front_end/stickyfloat.js");
$articleDetails = $this->articleDetails;
$userDetails = $this->userDetails;
$profileLink = HTTP_PATH_LOCALE.FrontEnd_Helper_viewHelper::__link("redactie")."/". $userDetails['slug'];
$firstName = str_replace(' ', '', $userDetails['firstName']);
$lastName = str_replace(' ', '', $userDetails['lastName']);
$articleUpdatedAtDate = date('d M Y', strtotime($articleDetails['updated_at']));
$plusViewPath = 'plus/';
$discussion = $this->partial(
    'partials/_discussion.phtml',
    array('shopName' =>'')
);
$articleInformation = $this->partial(
    $plusViewPath.'_articleInformation.phtml',
        array(
           'artcileDetails' => $articleDetails,
           'userDetails' => $userDetails,
           'profileLink' => $profileLink,
           'firstName' => $firstName,
           'lastName' => $lastName,
           'articleUpdatedAtDate'=> $articleUpdatedAtDate
        )
);
$authorDetails = $this->partial(
    $plusViewPath.'_authorDetails.phtml',
        array(
            'userDetails' => $userDetails,
            'profileLink' => $profileLink
        )
);
$savingGuides = $this->partial(
    $plusViewPath.'_savingGuides.phtml',
        array(
            'articlesRelatedToCurrentCategory' => $this->articlesRelatedToCurrentCategory
        )
);
$recentlyAddedArticles = $this->partial(
    $plusViewPath.'_recentlyAddedArticles.phtml',
        array(
            'recentlyAddedArticles' => $this->recentlyAddedArticles
        )
);
$topPopularOffers = $this->partial(
    $plusViewPath.'_topPopularOffers.phtml',
        array(
            'topPopularOffers' => $this->topPopularOffers,
        )
);
$directChapterLinks = $this->partial(
    $plusViewPath.'_directChapterLinks.phtml',
        array(
            'firstName' => $firstName,
            'lastName' => $lastName,
            'artcileDetails' => $articleDetails
        )
);
$sidebarHtml = '<aside id="sidebar" class="col-md-4 col-sm-4">' . $recentlyAddedArticles . $topPopularOffers . $directChapterLinks 
."</aside>";
$articleImage = PUBLIC_PATH_CDN.$articleDetails['articleImage']['path'].$articleDetails['articleImage']['name'];
?>
<main role="main" id="main" class="container">
    <div class="banner-block">
        <img class="image" src="<?php echo $articleImage; ?>" alt="<?php echo $articleDetails['title'];?>">
    </div>
    <div class="row">
        <div id="content" class="col-md-8 col-sm-8">
            <?php echo $articleInformation; ?>
            <div class="share-box">
                <span class="txt"><?php echo $this->translate('Share this tip');?></span>
                <?php echo FrontEnd_Helper_viewHelper::socialMediaWidget('', 'article');?>            
            </div>
            <?php echo $authorDetails. $savingGuides. $discussion;?>
        </div>
        <?php echo $sidebarHtml; ?>
    </div>
</main>