<?php 
$this->minifyHeadLink()->prependStylesheet("/public/css/front_end/in-savings.css");
$articleview = $this->currentArticle;
//echo "<pre>";print_r($articleview);die;
$userview = $this->userDetails;
$partialViewPath = 'partials/';
$discussion = $this->partial(
    $partialViewPath.'_discussion.phtml',
    array('shopName' =>'')
);

if(!empty($articleview)) :
?>
<main role="main" id="main" class="container">
    <div class="banner-block">
        <?php
            $articleImage = PUBLIC_PATH_CDN.$articleview['ArtIcon']['path'].$articleview['ArtIcon']['name'];
        ?>
        <img class="image" src="<?php echo $articleImage; ?>" alt="<?php echo $articleview['title'];?>">
    </div>
    <div class="row">
        <div id="content" class="col-md-8 col-sm-8">
            <section class="post-box">
                <header class="meta">
                    <h1><?php echo $articleview['title'];?></h1>
                    <?php 
                        $firstName = str_replace(' ', '', $userview['firstName']);
                        $lastName = str_replace(' ', '', $userview['lastName']);
                        $link_url = $userview['slug'];
                        $profileLink = HTTP_PATH_LOCALE.FrontEnd_Helper_viewHelper::__link("redactie")."/".$link_url;
                        $articleUpdatedAt = date('d M Y', strtotime($articleview['updated_at']));
                    ?>
                    <p>By <a href="<?php echo $profileLink; ?>"><?php echo $firstName . " " . $lastName;?></a> - <?php echo $articleUpdatedAt; ?> &nbsp;   | &nbsp;   <a href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('plus')?>"><?php echo $this->translate('Alle Plus');?></a></p>
                </header>
                <?php  
                    if (!empty($this->articleview['chapters'])) {
                        foreach ($this->articleview['chapters'] as $chapter) :
                            $pattern = array('/\s/','/[\,+@#?$%^:&*!.();]+/', '/(\')/');                     
                            $replace = array("-","-","-");
                            $chapterTitle = preg_replace($pattern, $replace, $chapter['title']);
                            $chapterTitle = strtolower($chapterTitle);
                            echo $chapter['content'];
                        endforeach;
                    }
                ?> 
        </section>
        <div class="share-box">
            <span class="txt">Share this tip</span>
            <ul class="social-box">
                <li><img src="<?php echo HTTP_PATH; ?>public/images/img-42.png" alt="image description" width="129" height="20" /></li>
                <li><img src="<?php echo HTTP_PATH; ?>public/images/img-43.png" alt="image description" width="81" height="20" /></li>
                <li><img src="<?php echo HTTP_PATH; ?>public/images/img-45.png" alt="image description" width="238" height="24" /></li>
                <li><img src="<?php echo HTTP_PATH; ?>public/images/img-44.png" alt="image description" width="81" height="21" /></li>
            </ul>
        </div>
        <section class="about-box">
            <div class="photo">
                <span class="name"><?php echo $firstName; ?></span>
                <?php
                    $autorImage = PUBLIC_PATH_CDN.$userview['profileimage']['path'] .'thum_medium_'. $userview['profileimage']['name'];
                ?>
                <img width="120" height="120" alt="<?php echo $firstName; ?>" src="<?php echo $autorImage; ?>">
            </div>
            <div class="text-box">
                <p><strong>About <?php echo $firstName; ?></strong>, <?php $userview['mainText'];?></p>
                <p><a href="<?php echo $profileLink; ?>">Read more about <?php echo $firstName; ?></a></p>
            </div>
        </section>
        <header class="heading-box text-advice">
            <h2>Saving guides</h2>
        </header>
        <section class="tips-section">
            <?php 
                if (!empty($this->articlesRelatedToCurrentCategory)) {
                    foreach($this->articlesRelatedToCurrentCategory as $articleRelatedToCurrentCategory) :
            ?>        
            <article class="block">
                <a href="<?php echo $articleRelatedToCurrentCategory['title'];?>">
                    <div class="image">
                        <img width="216" height="129" alt="<?php echo $articleRelatedToCurrentCategory['title'];?>" src="<?php echo PUBLIC_PATH_CDN.$articleRelatedToCurrentCategory['ArtIcon']['path'].$articleRelatedToCurrentCategory['ArtIcon']['name'];?>" >
                    </div>
                    <div class="box">
                        <h2><?php echo $articleRelatedToCurrentCategory['title'];?></h2>
                        <p><?php echo $articleRelatedToCurrentCategory['content'];?></p>
                    </div>
                </a>
            </article>
            <?php    
                    endforeach;
                }
            ?> 
        </section>
        <?php echo $discussion;?>
    </div>
    <aside id="sidebar" class="col-md-4 col-sm-4">
        <section class="news-block">
            <?php 
                if(!empty($this->recentlyAddedArticles)) {
            <article class="box">
                <span class="image"><img src="<?php echo HTTP_PATH; ?>public/images/img-38.jpg" alt="image description" width="118" height="118" /></span>
                <div class="text-box">
                    <h1><a href="#">Wonderhandelen - tover de prijs omlaag</a></h1>
                    <p><em>by <a href="#">Kim Pelikaan</a>, posted Today</em></p>
                    <a href="#" class="more"><span>Read More</span></a>
                </div>
            </article>
            
        </section>
            <ol class="alt-list">
                <li>
                    <a href="#">
                        <strong class="title">Zalando <mark>Exclusief</mark></strong>
                        Zalando kortingscode voor 10% korting
                    </a>
                </li>
                <li>
                    <a href="#">
                        <strong class="title">Kwik-fit <mark>Exclusief</mark></strong>
                        Kwik-fit kortingscode voor 30% korting op onderhoud
                    </a>
                </li>
                <li>
                    <a href="#">
                        <strong class="title">Center Parcs</strong>
                        €25 kortingscode bij Center Parcs <br />(in de schoolvakanties)
                    </a>
                </li>
                <li>
                    <a href="#">
                        <strong class="title">Hunkemöller <mark>Exclusief</mark></strong>
                        Hunkemöller kortingscode: 20% korting op alle geselecteerde items
                    </a>
                </li>
                <li>
                    <a href="#">
                        <strong class="title">Schuurman Schoenen <mark>Exclusief</mark></strong>
                        Schuurman Schoenen kortingscode: ontvang €10 korting op schoenen
                    </a>
                </li>
            </ol>
            <section class="list-box">
                <h1>Read This List</h1>
                <ol>
                    <li>
                        <a href="#">
                            <strong class="title">Uren bellen met tante Truus, dat kan goedkoop</strong>
                            <p><em>by <mark>Kim Pelikaan</mark></em></p>
                        </a>
                    </li>           
                </ol>
            </section>
        </aside>
    </div>
</main>
<?php else:?>        
<center>
    <div style='border:solid 1px gray'>
        <h2>
            <?php echo  $this->translate('Oops This Page Does Not Exist');?>
        </h2>
    </div>
</center>
    
<?php endif;?>