<?php 
$this->minifyHeadScript()->appendFile("/public/js/front_end/socialMedia.js");
$this->minifyHeadScript()->appendFile("/public/js/front_end/savingguides.js");

$mostReadArticles = '';
if (!empty($this->mostReadArticles)) {
    $mostReadArticles =
        $this->partial(
            'partials/_mostReadArticles.phtml',
            array('mostReadArticles'=>$this->mostReadArticles)
        );
} else {
    $mostReadArticles = $this->translate("No Records Found");
}

usort(
    $this->allArticles,
    "FrontEnd_Helper_MoneySavingGuidesPartialFunctions::getArticlesAccordingToDescendingOrderFunction"
);
$articlesInformation = array_chunk($this->allArticles, 8);

$plusViewPath = 'plus/';
$popularStores = '';
if (!empty($this->popularStores)) :
     $popularStores = $this->partial(
         $plusViewPath.'_popularShopLogos.phtml',
         array(
            'popularStores' => $this->popularStores,
            'headerText' => $this->translate('Popular Stores')
        )
     );
endif;

$pageHeader = new FrontEnd_Helper_PageHeaderPartialFunctions();
$pageHeaderImage = $pageHeader->getCategoryOrPageHeaderImage($this->pageHeaderImage);
LOCALE == '' ? $logoCssClass = 'kortingscode' : $logoCssClass = '';
?>
<div class="banner-block">
    <img class='image' src="<?php echo $pageHeaderImage;?>" alt="<?php echo $this->pageTitle;?>"/>
    <div class="frame-image">
        <div class="container">
            <h1 class="flipit-text <?php echo $logoCssClass; ?>"><?php $this->translate('Flipit plus');?></h1>
        </div>
    </div>
    <?php echo $mostReadArticles;?>
</div>
<main role="main" id="main">
<?php
for ($articleCounter =0; $articleCounter < count($articlesInformation) ; $articleCounter++) { 
    if ($articleCounter == 0) {?>
        <div class="container">
            <?php  
            FrontEnd_Helper_MoneySavingGuidesPartialFunctions::
                getArticles($articlesInformation[$articleCounter]);
            echo '</div>'.$popularStores; ?>
        </div>
        <?php 
    } else {
        ?>
        <div class="container">
        <?php 
            FrontEnd_Helper_MoneySavingGuidesPartialFunctions::
                getArticles($articlesInformation[$articleCounter]);
        ?>
        </div>
        <?php 
    }
}
?>   
</main>
