<?php 
$this->minifyHeadLink()->prependStylesheet("/public/css/front_end/saving.css");
$this->minifyHeadScript()->prependFile("public/js/front_end/socialMedia.js");
$pageDetails = $this->pageDetails;
$recentlyAddedArticles = $this->recentlyAddedArticles;
$categoryWiseArticles = $this->categoryWiseArticles;
?>
<div class="banner-block">
    <?php $pageImage = PUBLIC_PATH_CDN.$pageDetails[0]['logo']['path'].'thum_extra_large_'.$pageDetails[0]['logo']['name']; ?>
    <img class='image' src="<?php  echo $pageImage;?>" alt="<?php echo $pageDetails[0]['pageTitle']; ?>"/>
    <div class="frame-image">
        <div class="container">
            <h1 class="flipit-text"><?php $this->translate('Flipit plus');?></h1>
        </div>
    </div>
    <div class="container">
        <div class="text-box">
            <p>
            <?php echo  $this->translate('Flipit.com Plus is our magazine in which we want to do one thing only: help out all the consumers out there in every way possible');?>
            </p>
        </div>
        <div class="block">
            <div class="caption"><span><?php echo $this->translate('Featured savings');?></span></div>
            <div class="carousel">
                <div class="holder">
                    <div class="mask">
                        <div class="slideset">
                            <?php 
                            $frontEndViewHelper = new FrontEnd_Helper_viewHelper();
                            echo $mostReadArticles = $frontEndViewHelper->getMostReadArticles($this->mostReadArticles);
                            ?>
                        </div>
                    </div>
                </div>
                <ul class="switcher">
                <?php
                   if (!empty($this->mostReadArticles)) {
                        echo $this->partial('partials/_mostReadArticles.phtml',array('articles'=>$this->mostReadArticles)); 
                    } else {
                    echo $this->translate("No Records Found");
                    } 
                ?>
                </ul>
            </div>
        </div>
    </div>
</div>
<main role="main" id="main">
    <div class="container content-box">
        <?php 
            echo $recentlyAddedArticles = $frontEndViewHelper->getArticles('Recently added', $recentlyAddedArticles);
            if (!empty($categoryWiseArticles['blog'])) {
                echo $blogWiseArticles = $frontEndViewHelper->getArticles('From Blog',$categoryWiseArticles['blog']);
            }
            if (!empty($categoryWiseArticles['savingtip'])) {    
                echo $savingTipWiseArticles = $frontEndViewHelper->getArticles('Saving Tip',$categoryWiseArticles['savingtip']);
            }
        ?>  
    </div>
</main>
<footer class="bottom-panel">
    <div class="container">
        <div class="holder">
            <span class="text"><?php echo  $this->translate('Satisfied with the new Kortingscode.nl? Like us and win great prizes');?>
            </span>
            <ul class="share-list">
                <?php
               echo FrontEnd_Helper_viewHelper::socialMediaWidget('','article');
               ?>
            </ul>
        </div>
    </div>
</footer>




