<!-- Popup Content Start -->
	<div id="element_to_pop_up" class="popup_block" style="display:none;height:670px;width:724px;">
	
	
   </div>
<!-- Popup Content Ends -->
       
<!-- Light box for addtofavite if use not login Content Start -->       
	<div class="new-signin-outer-new popup_block_signup" id="addStoreToFavorite" style="display:none;">
	
	</div>
<!-- Light box for addtofavite if use not login Content End -->
	
<!-- Light box for dummy if user not login Content Start -->       
	<div class="new-signin-outer-new popup_block_signup" id="dummypage" style="display:none;">
	</div>
<!-- Light box for dummy if user not login Content End -->