<?php
    $this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/datepicker.css" );
	$this->headScript ()->appendFile ( PUBLIC_PATH . "js/back_end/ckeditor/ckeditor.js" );
	$this->headScript ()->appendFile ( PUBLIC_PATH . "js/back_end/ckeditor/config.js" );
	$this->headScript()->appendFile(PUBLIC_PATH  . "js/back_end/jquery.validate.js");
	$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/bootbox.min.js");
    $this->headScript()->appendFile(PUBLIC_PATH . "js/bootstrap-datepicker.js");
	$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/addwidget.js");
?>
<?php echo $this->headTitle()->append('Create Widget');?>
<script type="text/javascript">
	var CKEDITOR_BASEPATH = "<?php echo PUBLIC_PATH . "js/back_end/ckeditor" ; ?>" ;
</script>
<!-- addwidget div starts -->
<div class="wrap columns-2">
    <div id="addNewWidgetDiv" class="wrap columns-2">
        <?php echo $this->flashMessages(); ?>
        <h1><span id="create"><?php echo $this->translate('Create Widget');?></span><button class="btn ml10" type="button" onClick="window.location.href='<?php echo HTTP_PATH ;?>admin/widget'"><?php echo $this->translate('Cancel'); ?></button></h1>
        <form name="createWidget" id="createWidget" enctype="multipart/form-data" method="post">
            <input type="hidden" name='editedWidgetId' id='editedWidgetId' value="" />
            <input type="hidden" name='loggedInUser' id='loggedInUser' value="<?php echo $this->id; ?>" />
            <input type="hidden" name='textValue' id='textValue'/>
            <div id="poststuff" class="metabox-holder has-right-sidebar">
                <div id="post-body">
                    <div>
                        <div class="mainpage-content margin_widget_editor">
                            <div class="row-fluid">
                                <div class="span2 mb10"><label><strong><?php echo $this->translate('Title');?> </strong>*</label></div>
                                <div class="span10">
                                    <input type="text" value="<?php echo isset($this->widget['title']) ? $this->widget['title'] : ''; ?>" name="title" id="title" class="span3">
                                </div>
                            </div>
                        </div>
                        <div class="mainpage-content margin_widget_editor">
                            <div class="row-fluid" id="visibiliyDiv">
                                <div class="span2 mb10">
                                    <label><strong><?php echo $this->translate('Is Dated'); ?></strong></label>
                                </div>
                                <div class="span10">
                                    <div data-toggle="buttons-checkbox" class="btn-group">
                                        <button type="button" class="btn btn-primary"  id="id_dated_yes" onClick="selectIsDated('id_dated_yes')">
                                            <?php echo $this->translate('Yes'); ?>
                                        </button>
                                        <button type="button" class="btn" style="border-radius: 0 4px 4px 0;"
                                                id="id_dated_no" onClick="selectIsDated('id_dated_no')">
                                            <?php echo $this->translate('No'); ?>
                                        </button>
                                    </div>
                                </div>
                            </div>

                            <div id="date_selectors_div">
                                <div class="row-fluid">
                                    <div class="span2">
                                        <label><strong><?php echo $this->translate('Start Date'); ?></strong></label>
                                    </div>
                                    <div class="span2">
                                        <div data-date-format="dd-mm-yyyy" data-date="<?php echo date('d-m-Y');?>" id="widgetStartDate_div"
                                             class="input-append date">
                                            <input readonly="readonly" type="text"  value="<?php echo isset($this->widget['startDate']) ? $this->widget['startDate'] : ''; ?>" class="span2 ignore2 date-time-cusor-style" id="widgetStartDate" name="startDate">
                                            <span class="add-on"><i class="icon-th"></i></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row-fluid">
                                    <div class="span2">
                                        <label><strong><?php echo $this->translate('End Date'); ?></strong></label>
                                    </div>
                                    <div class="span2">
                                        <div data-date-format="dd-mm-yyyy" data-date="" id="widgetEndDate_div"
                                             class="input-append date">
                                            <input readonly="readonly"  type="text" value="<?php echo isset($this->widget['endDate']) ? $this->widget['endDate'] : ''; ?>" name="endDate" id="widgetEndDate" class="span2 ignore2 date-time-cusor-style">
                                            <span class="add-on"><i class="icon-th"></i></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <textarea name="content" id="content"><?php echo isset($this->widget['content']) ? $this->widget['content'] : ''; ?></textarea>
                    </div>
                </div>
                <br class="clear">
            </div>
            <br>
            <div class="mainpage-content-colorbox margin_widget_content">
                <button class="btn btn-large btn-primary fl" type="submit" id="widgetSubmit"><span id="save"><?php echo $this->translate('CREATE WIDGET');?></span></button>
                <a href="<?php echo HTTP_PATH.'admin/widget';?>" class="fl m10"><strong><?php echo $this->translate('CANCEL');?></strong></a>
            </div>
        <!-- /poststuff -->
        </form>
    </div>
</div>
<script type="text/javascript">
    <?php if( ( !isset($this->widget['startDate']) || is_null($this->widget['startDate']) ) && ( !isset($this->widget['endDate']) || is_null($this->widget['endDate']))) : ?>
    $('#id_dated_no').click();
    <?php endif; ?>
</script>