<?php
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/datepicker.css" );
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/addwidget.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/ckeditor/ckeditor.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/ckeditor/config.js");
$this->headScript()->appendFile(PUBLIC_PATH  . "js/back_end/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/bootstrap-datepicker.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/bootbox.min.js");
?>
<?php echo $this->headTitle()->append('Edit Widget');?>
<script type="text/javascript">
  var CKEDITOR_BASEPATH = "<?php echo PUBLIC_PATH . "js/back_end/ckeditor" ; ?>" ;
</script>
<div class="wrap columns-2">
    <?php echo $this->flashMessages(); ?>
    <div id="editWidgetDiv" class="wrap columns-2">
    <h1>
        <span id="create"><?php echo $this->translate('Edit Widget');?></span>
        <button class="btn ml10" 
            type="button" 
            onClick="window.location.href='<?php echo HTTP_PATH ;?>admin/widget<?php echo '#'.$this->qstring; ?>'">
            <?php echo $this->translate('Cancel');?>
        </button>
    </h1>
        <form name="createWidget" id="createWidget" method="post">
            <input type="hidden" name='editedWidgetId' id='editedWidgetId' value="<?php echo $this->id;?>" />
            <input type="hidden" name='qString' id='qString' value='<?php echo $this->qstring; ?>' />
            <div id="poststuff" class="metabox-holder has-right-sidebar">
                <div id="post-body">
                    <div>
                        <div class="mainpage-content margin_widget_editor">
                            <div class="row-fluid">
                                <div class="span2 mb10">
                                    <label><strong><?php echo $this->translate('Title');?></strong> *</label>
                                </div>
                                <div class="span10">
                                    <input type="text" value="<?php echo $this->widgetInformation['title'];?>" placeholder="" name="title" id="title" class="span3">
                                </div>
                            </div>
                        </div>
                        <div class="mainpage-content margin_widget_editor">
                            <div class="row-fluid" id="visibiliyDiv">
                                <div class="span2 mb10">
                                    <label><strong><?php echo $this->translate('Is Dated'); ?></strong></label>
                                </div>
                                <div class="span10">
                                    <div data-toggle="buttons-checkbox" class="btn-group">
                                        <button type="button" class="btn btn-primary"  id="id_dated_yes" onClick="selectIsDated('id_dated_yes')">
                                            <?php echo $this->translate('Yes'); ?>
                                        </button>
                                        <button type="button" class="btn" style="border-radius: 0 4px 4px 0;"
                                                id="id_dated_no" onClick="selectIsDated('id_dated_no')">
                                            <?php echo $this->translate('No'); ?>
                                        </button>
                                    </div>
                                </div>
                            </div>

                            <div id="date_selectors_div">
                                <div class="row-fluid">
                                    <div class="span2">
                                        <label><strong><?php echo $this->translate('Start Date'); ?></strong></label>
                                    </div>
                                    <div class="span2">
                                        <div data-date-format="dd-mm-yyyy" data-date="<?php echo date('d-m-Y');?>" id="widgetStartDate_div"
                                             class="input-append date">
                                            <input readonly="readonly" type="text"  value="<?php echo ( isset($this->widgetInformation['startDate']) && is_object($this->widgetInformation['startDate']) ) ? $this->widgetInformation['startDate']->format('d-m-Y') : ''; ?>" class="span2 ignore2 date-time-cusor-style" id="widgetStartDate" name="startDate">
                                            <span class="add-on"><i class="icon-th"></i></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row-fluid">
                                    <div class="span2">
                                        <label><strong><?php echo $this->translate('End Date'); ?></strong></label>
                                    </div>
                                    <div class="span2">
                                        <div data-date-format="dd-mm-yyyy" data-date="" id="widgetEndDate_div"
                                             class="input-append date">
                                            <input readonly="readonly"  type="text" value="<?php echo ( isset($this->widgetInformation['endDate']) && is_object($this->widgetInformation['endDate']) ) ? $this->widgetInformation['endDate']->format('d-m-Y') : ''; ?>" name="endDate" id="widgetEndDate" class="span2 ignore2 date-time-cusor-style">
                                            <span class="add-on"><i class="icon-th"></i></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                            <?php if ($this->widgetInformation['content']) :?>
                            <textarea name="content" id="content" ><?php echo $this->widgetInformation['content'];?></textarea>
                            <?php endif;?>
                    </div>
                </div>
                <br class="clear">
            </div>
            <?php 
            if ($this->widgetInformation['content']):
                ?>
               <br>
                <?php 
            endif;
            ?>
            <div class="mainpage-content-colorbox margin_widget_content" >
                <button class="btn btn-large btn-primary fl" type="submit" id="widgetSubmit">
                    <span id="save"><?php echo $this->translate('SAVE CHANGES');?></span>
                </button>
                <a href="<?php echo HTTP_PATH.'admin/widget#'.$this->qstring; ?>" class="fl m10" >
                    <strong><?php echo $this->translate('CANCEL');?></strong>
                </a>
                <a href="#" onClick="javascript:callToPermanentDelete();" class="red fl mt10">
                    <strong>
                        <span id="delete"><?php echo $this->translate('backend_DELETE');?></span>
                    </strong>
                </a>
            </div>
        </form>
    </div> 
</div>
<script type="text/javascript">
    <?php if( ( !isset($this->widgetInformation['startDate']) || !is_object($this->widgetInformation['startDate']) ) && ( !isset($this->widgetInformation['endDate']) || !is_object($this->widgetInformation['endDate']))) : ?>
    $('#id_dated_no').click();
    <?php endif; ?>
</script>