<?php 
 $this->headTitle()->append($this->translate('API Key Listing'));
 $this->headScript()->appendFile(PUBLIC_PATH . "js/jquery.dataTables.min.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "js/dataTableComman.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/apikeys.js");
?>
<div id="searchbarlist">
   <div class="wrap columns-2">
    <?php 
    if($this->messageSuccess!='' || $this->messageError!='' ) {?>
        <br>
        <div class ="mainpage-content-colorbox success">
            <?php if($this->messageSuccess!='') {?>
                <span class="success"><?php echo $this->messageSuccess; ?></span>
                <?php 
            }?>
            <?php if($this->messageError!='') 
                {?>
                <span class="error"><?php echo $this->messageError; ?></span>
                <?php 
            } ?>
        </div>
        <?php 
    }?>
    
        <h1 class="fl"><?php echo $this->translate('API Keys'); ?>
            <button class="btn ml10" type="button" onClick="window.location.href='<?php echo HTTP_PATH ?>admin/apikeys/addapikeys'">
            <?php echo $this->translate('Add new API Key'); ?>
            </button>
        </h1>
        <div class="clear"></div>
        <table class="table table-bordered table-striped" id="ApiKeysListTbl" cellpadding="0" cellspacing="0">
            <thead>
                <tr>
                    <th><?php echo $this->translate('id');?></th>
                    <th><?php echo $this->translate('API Key'); ?></th>
                    <th><?php echo $this->translate('Created'); ?></th>
                    <th><?php echo $this->translate('Delete'); ?></th>
                </tr>
            </thead>
        </table> 
  </div>
 </div>
        