<?php
    $this->headTitle()->append($this->translate('Special pages'));
    $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
    $this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
    $this->headLink()->appendStylesheet(PUBLIC_PATH . "css/jquery-ui-1.8.16.custom.css");
    $this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/back_end/bootstrap-combobox.css" );
    $this->headScript ()->appendFile ( PUBLIC_PATH . "js/back_end/select2.min.js" );
    $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/special_pages.js");
?>
<div class="wrap columns-2">
    <h1>
        <?php echo $this->translate('Special pages'); ?>
    </h1>            
    <div id="poststuff" class="metabox-holder has-right-sidebar">
        <div id="side-info-column" class="inner-sidebar-coupon">
            <div id="side-sortables" class="meta-box-sortables ui-sortable">
              <div class="coupon-sidebar-outer">
              
                <!-- searchbar div -->
                <div class="coupon-sidebar-heading">
                    <select  style="display: none; width : 389px;" class="combobox" name="offerlist" id="offerlist">
                            <option value=""></option>
                            <?php
                            foreach ($this->offer as $o) { 
                                
                            if (trim ($o ['title'] ) != '') {
                                $offer = substr ($o ['title'], 0, 70 );
                            ?>
                                <option  value="<?php echo $o['id']; ?>"><?php echo $offer; ?></option>
                            
                                
                            <?php }} ?>
                    </select> 
                    <input type="hidden" name="selctedOffer" id="selctedOffer" value="">
                    <input type="hidden" name="selctedOfferText" id="selctedOfferText" value="">
                    <!--<input placeholder="search offer" id='searchCouponTxt' type="text" class="input-medium search-query">-->
                    <input type='hidden' name="SearchedValueIds" id="SearchedValueIds" value="">
                </div>
                
                <!-- coupon code move up -->
                <div class="coupon-sidebar-content-box">
                    <button id='addNewOffer' onClick='addNewOffer();'class="btn">ADD NEW OFFER</button>
                </div>
                <!-- coupon code move down -->
                <div class="coupon-sidebar-content-box mb10 image-loading-icon">
                    <button id='deleteOne' onClick='deleteOne();' class="btn">DELETE</button>
                </div>                    
              </div>
              
            </div>
          </div>
        <div id="post-body">
            <div id="post-body-content-coupon">
                <div class="top-coupon-list">
                    <ul id='specialPages'>
                    <?php 
                    if (!empty($this->articles)) { 
                        foreach ($this->articles as $articles) {
                        echo  "<li class='ui-state-default' id='".$articles['articles']['id']."'>
                            <span>".$articles['articles']['title']."</span></li>";
                        }
                    } else {             
                        echo  "<li id='0'>". $this->translate('No record found !') ."</li>";
                    } ?>
                    </ul>
                </div>
            </div>
        </div>
        <br class="clear">
    </div>
</div>
