<?php
$auhtorProfileImage = HTTP_PATH_CDN. ltrim($this->autherDetails['profileimage']['path'], "/")."thum_large_widget_".$this->autherDetails['profileimage']['name'];
$authorFullName = $this->autherDetails['firstName']. " " .$this->autherDetails['lastName'];
$partialFunctions = new FrontEnd_Helper_AuthorPartialFunctions();
$authorFavouriteShops = '';
if (!empty($this->authorFavouriteShops)):
$authorFavouriteShops = $this->partial(
    'partials/_authorFavouriteShops.phtml',
    array(
       "authorFavouriteShops"=>$this->authorFavouriteShops,
       "authorFirstName"=>$this->autherDetails['firstName']
    )
);
endif;
?>
<article class="section section-author">
    <header class="heading">
        <div class="icon">
            <img width="87" height="87" src="<?php echo $auhtorProfileImage;?>" alt="<?php echo $this->autherDetails['firstName'];?>">
        </div>
        <div class="box">
            <h1><span><?php echo $authorFullName;?></span> <span class="status"><?php echo $this->translate('deal guru');?></span></h1>
            <ul class="author-details">
               <?php 
               echo $partialFunctions->getAuthorCountryFlagWithCountryName($this->autherDetails['countryLocale']);
               echo $partialFunctions->authorSocialMediaLinks($this->autherDetails);?>
            </ul>
        </div>
    </header>
    <div class="text-block">
    <?php echo $this->autherDetails['mainText'];?>
    </div>
    <div class="box-statistics">
        <div class="col">
            <span><?php echo $this->translate('Coupons placed');?></span>
            <span class="add"><strong class="quantity"><?php echo $this->autherDetails['popularKortingscode'];?></strong><span><?php echo $this->translate('Popular codes');?></span></span>
        </div>
        <div class="col">
            <span><?php echo $this->translate('Editor since');?></span>
            <span class="add"><strong class="quantity"><?php echo $this->autherDetails['sinceDays'];?></strong> <span><?php echo $this->translate('days editor')?></span></span>
        </div>
    </div>
    <?php echo $authorFavouriteShops;?>
</article>