<?php
$auhtorProfileImage =
    HTTP_PATH_CDN
    .ltrim($this->authorDetails['path'], "/")
    ."thum_large_widget_". $this->authorDetails['name'];
$partialFunctions = new FrontEnd_Helper_AuthorPartialFunctions();
$authorName = $partialFunctions->getAuthorName($this->authorDetails[0]['firstName'], $this->authorDetails[0]['lastName']);
$authorFavouriteShops = '';
if (!empty($this->authorFavouriteShops)):
$authorFavouriteShops = $this->partial(
    'partials/_authorFavouriteShops.phtml',
    array(
       "authorFavouriteShops"=>$this->authorFavouriteShops,
       "authorFirstName"=>$this->authorDetails[0]['firstName']
    )
);
endif;
?>
<article class="section section-author">
    <header class="heading">
        <div class="icon">
            <img width="87" height="87" src="<?php echo $auhtorProfileImage;?>" 
            alt="<?php echo $authorName;?>" title="<?php echo $authorName;?>">
        </div>
        <div class="box">
            <h1>
                <span><?php echo $authorName;?></span>
                <span class="status"><?php echo $this->translate('deal guru');?></span>
            </h1>
            <ul class="author-details">
               <?php 
               echo $partialFunctions->getAuthorCountryFlagWithCountryName($this->authorDetails[0]['countryLocale']);
               echo $partialFunctions->authorSocialMediaLinks($this->authorDetails[0]);?>
            </ul>
        </div>
    </header>
    <div class="text-block">
        <p>
        <?php echo $this->authorDetails[0]['mainText'];?>
        </p>
    </div>
    <div class="box-statistics">
        <div class="col">
            <span><?php echo $this->translate('Coupons placed');?></span>
            <span class="add">
                <strong class="quantity"><?php echo $this->authorDetails[0]['popularKortingscode'];?></strong>
                <span><?php echo $this->translate('Popular codes');?></span>
            </span>
        </div>
        <div class="col">
            <span><?php echo $this->translate('Editor since');?></span>
            <span class="add">
                <strong class="quantity"><?php echo $this->authorDetails['sinceDays'];?></strong>
                <span><?php echo $this->translate('days editor')?></span>
            </span>
        </div>
    </div>
    <?php echo $authorFavouriteShops;?>
</article>