<?php
$this->minifyHeadLink()->prependStylesheet("/public/css/front_end/authors.css");
$this->minifyHeadScript()->prependFile("public/js/front_end/socialmedia.js");
$this->minifyHeadScript()->prependFile("public/js/front_end/signupnewsletter.js");

$pageImage = PUBLIC_PATH_CDN.$this->pageDetails['logo']['path'].$this->pageDetails['logo']['name'];
$pageHeader = new FrontEnd_Helper_PageHeaderPartialFunctions();
echo $pageHeader->getCategoryOrPageHeader($this->pageDetails['pageTitle'], $pageImage);

$partialViewPath = 'partials/';
$authorsList = '';
if (!empty($this->authorsWithPagination)) {
    $authorsList = $this->partial(
        $partialViewPath.'_authorsList.phtml',
        array(
           'authors' =>$this->authorsWithPagination,
        )
    );
} else {
    $authorsList = $this->translate('No Records Found');
}
$signUpWidgetForm = '';
$signUpWidgetForm = $this->partial(
    $partialViewPath.'_signupForm.phtml',
    array(
       'zendForm' => $this->sidebarWidgetForm,
       'signupFormWidgetType'=> 'sidebarWidget',
       'shopId'=>'',
       'shopLogoOrDefaultImage'=>''
    )
);
?>
<div class="row">
    <?php echo $authorsList;?>
    <aside class="col-md-4 col-sm-4" id="sidebar">
    <?php 
    $frontendSidebarHelper = new FrontEnd_Helper_SidebarWidgetFunctions();
    echo $frontendSidebarHelper->popularCategoryWidget();
    echo $frontendSidebarHelper->popularShopWidget();
    echo $frontendSidebarHelper->browseByStoreWidget();
    echo $frontendSidebarHelper->socialMediaWidget();
    echo $signUpWidgetForm;
    ?>
    </aside>
</div>
