<?php 
$this->minifyHeadLink()->prependStylesheet("/public/css/front_end/author.css");
$this->minifyHeadScript()->prependFile("public/js/front_end/socialmedia.js");
$this->minifyHeadScript()->prependFile("public/js/front_end/signupnewsletter.js");

$autherDetail  = '';
if(!empty($this->authorDetails)):
$autherDetail = $this->partial(
        'about/_authorTopContent.phtml',
        array(
            "authorFavouriteShops"=>$this->authorFavouriteShops,
            "autherDetail"=>$this->authorDetails,
        )
);
endif;

$partialViewPath = 'partials/';
$authorMostReadArticle = '';
if(!empty($this->authorMostReadArticles)):
    $authorMostReadArticle = $this->partial(
        $partialViewPath.'_authorMostReadArticle.phtml', 
        array(
            "authorMostReadArticles"=>$this->authorMostReadArticles,
            "authorName"=>$this->authorDetails['firstName']
        )
    );
endif;

$discussion = $this->partial(
        $partialViewPath.'_discussion.phtml',
        array('shopName' => $this->authorDetails['firstName'])
);

$signUpWidgetForm = '';
$signUpWidgetForm = $this->partial(
        $partialViewPath.'_signupForm.phtml',
        array(
                'zendForm' => $this->sidebarWidgetForm,
                'SignupFormWidgetType'=> 'sidebarWidget',
                'shopId'=>'',
                'shopLogoOrDefaultImage'=>''
        )
);
?>
<div class="row">
    <div id="content" class="col-md-8 col-sm-8">
        <?php echo $autherDetail;?>
        <?php echo $authorMostReadArticle.$discussion;?>
    </div>
    <aside class="col-md-4 col-sm-4" id="sidebar">
    <?php 
    $frontendViewHelper = new FrontEnd_Helper_viewHelper();
    echo $frontendViewHelper->popularCategoryWidget();
    echo FrontEnd_Helper_viewHelper::socialMediaWidget();
    echo FrontEnd_Helper_viewHelper::popularShopWidget();
    echo $frontendViewHelper->browseByStoreWidget();
    echo $signUpWidgetForm;
    ?>
    </aside>
</div>
