<?php 
$this->minifyHeadScript()->appendFile("public/js/front_end/socialmedia.js");
$authorName = FrontEnd_Helper_AuthorPartialFunctions::
    getAuthorName($this->authorDetails['firstName'], $this->authorDetails['lastName']);
$authorDetails  = '';
if(!empty($this->authorDetails)):
$authorDetails = $this->partial(
        'about/_authorTopContent.phtml',
        array(
            "authorFavouriteShops"=>$this->authorFavouriteShops,
            "authorDetails"=>$this->authorDetails,
        )
);
endif;

$partialViewPath = 'partials/';
$authorMostReadArticles = '';
if(!empty($this->authorMostReadArticles)):
    $authorMostReadArticles = $this->partial(
        $partialViewPath.'_authorMostReadArticles.phtml',
        array(
            "authorMostReadArticles"=>$this->authorMostReadArticles,
            "moneySavingGuideHeader"=>$this->translate('Saving guides by') . " " . $authorName
        )
    );
endif;

$discussion = $this->partial(
        $partialViewPath.'_discussion.phtml',
        array('authorName' => $authorName, 'discussionComments' => $this->discussionComments)
);

$signUpWidgetForm = '';
$signUpWidgetForm = $this->partial(
        $partialViewPath.'_signupForm.phtml',
        array(
                'zendForm' => $this->sidebarWidgetForm,
                'signupFormWidgetType'=> 'sidebarWidget',
                'shopId'=>'',
                'shopLogoOrDefaultImage'=>''
        )
);
?>
<div class="row">
    <div id="content" class="col-md-8 col-sm-8">
        <?php echo $authorDetails;?>
        <?php echo $authorMostReadArticles.$discussion;?>
    </div>
    <aside class="col-md-4 col-sm-4" id="sidebar">
    <?php 
    $frontendSidebarHelper = new FrontEnd_Helper_SidebarWidgetFunctions();
    echo $frontendSidebarHelper->popularCategoryWidget().
    $frontendSidebarHelper->popularShopWidget().
    $frontendSidebarHelper->socialMediaWidget().
    $signUpWidgetForm;
    ?>
    </aside>
</div>
