<div onclick="window.location = '<?php echo HTTP_PATH_LOCALE ;?>'" class="crose-button-addtofavorite"><img width="10" height="10" src="<?php echo HTTP_PATH;?>public/images/front_end/cross-black.png"></div>
<div class="new-signup-form new-signup-form-new">
   <h2 class="text-center mt40">
   		<strong> <?php echo $this->translate('Join kortingscode.nl'); ?></strong>
    </h2>
    
	<p class="mb20">
       <?php  echo $this->translate('Get free access to an exclusive Members-Only discounts codes!'); ?>
    </p>
	
	<a rel="nofollow" class="mt20" href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link ('inschrijven'). '/' .  FrontEnd_Helper_viewHelper::__link('stap1');?>">
		<button  class="directSignupButton" value="<?php echo  FrontEnd_Helper_viewHelper::__link('DIRECT ACCOUNT AANMAKEN') ?>"><?php echo  FrontEnd_Helper_viewHelper::__link('DIRECT ACCOUNT AANMAKEN') ?></button>
	</a>
	
    <div class="already-ac">
	    <?php echo $this->translate('Already a member?'); ?>
	    <a href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('login') ?>">
	    <?php echo $this->translate('Login'); ?>
	    </a>
	 </div>
</div>