<?php 
$this->minifyHeadScript()->prependFile ( HTTP_PATH."public/js/front_end/jquery.placeholder.js");
$this->minifyHeadScript()->prependFile ( HTTP_PATH."public/js/front_end/resetpwd.js" );
 ?>
 <script>
   $(function() {
    // Invoke the plugin
    $('input, textarea').placeholder();
   
   });
</script>
 
<div class='new-outer'>
 <div class="new-signup-outer-round mt40">
 		<div style="display: none" id="passwordset" class="yelloww-error-box-code margin_none"><strong><?php echo $this->translate("Uw wachtwoord is gereset!")?></strong></div>
		<div style="display: none" id="usernotfound" class="yelloww-error-box-code margin_none"><strong><?php echo $this->translate("This link seems to be invalid or expired..")?></strong></div>
		<h2>
       		<?php echo $this->translate('Nieuw wachtwoord aanmaken') ?>
       	</h2>
        <span><?php echo $this->translate('Vul hieronder je nieuwe wachtwoord in:') ?></span>
        <?php if($this->flag){?>
        <form name="resetpwd" id="resetpwd" method="post" action="" autocomplete="off">
			<input type="hidden"  id="forgotid" name="forgotid"  value="<?php echo $this->forgotid; ?>"/>
	        <div class="login-form">
		   		 <div class="error-msg"></div>
		            <div class="login-form-row">
		            	<input class="textLine" placeholder='********' type="password" tabindex="1" id="pwd" name="pwd" /><label class="lblerrcls"></label>
		            </div>
		            
		            <div class="login-form-row">
		            	<input  class="textLine" placeholder='********'  type="password" tabindex="2" id="repwd" name="repwd" /><label class="lblerrcls"></label>
		            </div>
		            
		            <div class="blue_btn">
		            	<a tabindex="3" onclick="resetPasswordUser();" href="javascript:void(0);"><?php echo $this->translate('verstuur') ?></a>
		            </div>
		           
		       <div class="clr"></div>
	       </div> 
       </form>
       </div>
       <?php  }else{ ?>
       <div>
       <center>
	       <?php if($this->messageSuccess!='' || $this->messageError!='' ){?>
			<br>
			<div class ="yelloww-error-box-code margin_none">
			
			<?php if($this->messageSuccess!=''){?>
			
			<span class="successserver"><?php echo $this->messageSuccess; ?></span>
			
			<?php }?>
			<?php if($this->messageError!=''){?>
			
			<span class="errorserver"><?php echo $this->messageError; ?></span>
			
			<?php } ?>
			</div>
		</center>
		</div>
			<?php 
		}?>
    <?php }
   	echo $this->render('login/login_footer_member.phtml')?>

 