<div class="login-top-messages">
            	<h1 class="mt40"><span><?php echo $this->translate('E-mail verstuurd!');?></span></h1>
                <h5 class="mt15"><?php echo $this->translate('We hebben je een e-mail verstuurd. Volg de instructies om een nieuw wachtwoord aan te maken.');?></h5>
                <a class="mt10 fl text-blue-link" href="<?php echo HTTP_PATH_LOCALE?>login"><b><< <?php echo $this->translate('Terug naar login');?></b></a>
            </div>
        <div class="separator mt40">&nbsp;</div>