<?php 
    $this->minifyHeadScript()->prependFile ( HTTP_PATH."public/js/front_end/profile.js" ); 
?>
<div class="new-outer"><div id="successMsg"></div></div>
<div class="profile-bg">
	<div class="new-outer">
		<?php if(count($this->offers) > 0): ?>
			<div class="mark-spencer-mid-left" style='width: 1000px !important;'>
			<h2><?php echo $this->translate('Member only codes');?></h2>
				<?php 
					$k = 0;
					foreach ($this->offers as $paginatorCodes):
						$this->offers[$k]['marginCounter'] = 4;
						$k++;
					endforeach;
					echo $this->partialLoop('partials/offer.phtml', $this->offers); 
				?>
			</div>
			<?php endif;?>
		<form action="" method='post' id='profileForm'>
			<div class="new-outer-round mt40">
			<?php if($this->userdetail['firstName']!='' && $this->userdetail['firstName']!=null){ ?>
			 <h1 class="text-center mt40"><?php echo $this->translate('Beste ') . $this->userdetail['firstName'] . ',' . $this->translate(' hoe is het ?'); ?></h1>
		   	<?php }?>
		    <p class="text-center font-weight-normal"><?php echo $this->translate('Hier kun je je profiel aanpassen en je email instellingen wijzigen');?></p>
		    <div class="new-profile-form-outer">
	    	
	    		<input type="hidden" value="<?php echo $this->userdetail['id'];?>" id="userId" name="userId">
		    	<div class="new-form-left-small fl">
		    		<span class="profile-row">
			            <label><?php echo $this->translate('Voornaam');?></label>
			            <input class="textLine" type="text" value="<?php echo $this->userdetail['firstName'];?>" name='firstName' id='firstName'/>
		            </span>
		            <span class="profile-row">
			            <label><?php echo $this->translate('Email adres');?></label>
			            <input class="textLine" type="text" value="<?php echo $this->userdetail['email'];?>" name='emailAddress' id='emailAddress'/>
		            </span>
		            <span class="profile-row">
			            <label><?php echo $this->translate('Geslacht');?></label>
			            <Select name='gender'>
			            	<option value=""><?php echo $this->translate('Select'); ?></option>
			            	<option value="male" <?php echo $this->userdetail['gender'] == '0' ? 'selected=selected' : '' ?>><?php echo $this->translate('Male');?></option>
			            	<option value="female" <?php echo $this->userdetail['gender'] == '1' ? 'selected=selected' : '' ?>><?php echo $this->translate('Female');?></option>
			            </Select>
		            </span>
		            <span class="profile-row">
			            <label><?php echo $this->translate('Postcode - 0000AA'); ?></label>
			            <input class="half textLine" type="text" value="<?php echo $this->userdetail['postalCode'];?>" name='postCode' id='postCode'/>
		        	</span>
		        </div>
		        <div class="new-form-left-small fr">
		        	<span class="profile-row">
			            <label><?php echo $this->translate('Achternaam'); ?></label>
			            <input class="textLine" type="text" value="<?php echo $this->userdetail['lastName'];?>" name='lastName' id='lastName'/>
		            </span>
		            <span class="profile-row">
			            <label><?php echo $this->translate('Wachtwoord'); ?></label>
			            <a class="mt10 fl text-blue-link" href="javascript:void(0)" onclick = "showForgotPasswordPopup()"><?php echo $this->translate('Verander je wachtwoord.'); ?></a>
		            </span>
		            <span class="profile-row">
		            <label><?php echo $this->translate('Geboortedatum'); ?></label>
		            <?php 
		            	$dob = array_reverse(explode('-',$this->userdetail['dateOfBirth']));
		            	//echo "<pre>"; print_r($dob); die;
		            ?>
		            <Select class="day comboBox" name="birthDay" id="birthDay">
		            	<option value="">DD</option>
		            	<?php 
		            		for($i=1; $i<32; $i++) :
		            		
		            	?>
	                            	<option value='<?php echo $i;?>' <?php echo $i == $dob[0] ? 'selected = selected' : '';?> ><?php echo $i;?></option>
	                            <?php 
	                            	endfor; 
	                            ?>
		            </Select>
		            <Select class="month comboBox" name="birthMonth" id="birthMonth">
		            	<option value=""><?php echo $this->translate('MM'); ?></option>
		            	<?php for($j=1; $j<13; $j++) :?>
	                            	<option value='<?php echo $j;?>' <?php echo $j == $dob[1] ? 'selected = selected' : '';?>><?php echo $j;?></option>
	                            <?php endfor; ?>
		            </Select>
		            <Select class="year comboBox" name="birthYear" id="birthYear">
		            	<option value=""><?php echo $this->translate('YYYY'); ?></option>
		            	<?php 
	                        	$year = date("Y") - 50;
	 
								for ($k = 0; $k <= 50; ++$k) :
									
							?>		
								 	<option value='<?php echo $year;?>' <?php echo $year == $dob[2] ? 'selected = selected' : '';?>><?php echo $year;?></option>
						<?php 	
								  ++$year;
								endfor;
						?>
		            </Select>
		            </span>
					<span class='validationPlacement'></span>
		        </div>
	        
		  	</div>
		    </div>
		   
			<div class="new-outer-round mt40" style="margin-bottom:30px;">
				<p class="text-center font-weight-normal mt10"><?php echo $this->translate('E-mail & Nieuwsbrief instellingen:');?></p>
				<div class="proofil-checks mt40">
					<span class="p-checkbox"><input align="top" type="checkbox" name="weekly" <?php if($this->userdetail['weeklyNewsLetter']){echo 'checked=checked';} ?>/></span>
					<h4><?php echo $this->translate('Dé Kortingscode.nl wekelijkse nieuwsbrief');?></h4>
					<p><?php echo $this->translate('De nieuwsbrief van Kortingscode.nl wordt de komende tijd vrijwel elke week verbeterd. Ons uiteindelijke doel: De gebruiker een persoonlijke kortingsoverzicht kunnen bieden met alleen maar shops waarin jij echt geinteresseerd bent.  ');?></p>
				</div>
				</form>
				<div class="submit-button-profile">
					<a class="submit-button-profile" href="javascript:void(0)" id="profileUpdateBtn"><img src="<?php echo HTTP_PATH; ?>public/images/front_end/profile-update.png" border="0" /></a>
				</div>
			</div>
	</div>
</div>