<?php 
	$request = Zend_Registry::get('request');
	
	$module   = strtolower($request->getParam('lang'));
	$controller = strtolower($request->getControllerName());
	$action     = strtolower($request->getActionName());

	# check module specific view exists or not
	if (file_exists (APPLICATION_PATH . '/modules/'  . $module . '/views/scripts/partials/_user_widget.phtml')){
				
		# set module specific view script path
		$path =  APPLICATION_PATH . '/modules/'  . $module . '/views/' ;
	} else{
				
		# set default module view script path
		$path =  APPLICATION_PATH . '/views/' ;
	}

	$view = new Zend_View();
	$view->setBasePath($path);
	echo $view->render('partials/_user_widget.phtml');
?>