<?php
$domain = $_SERVER['HTTP_HOST'];
if (! Auth_VisitorAdapter::hasIdentity() && ($domain == "kortingscode.nl" || $domain == "www.kortingscode.nl")) :
?>
	<form id="formOneHomePage" action="<?php echo HTTP_PATH . FrontEnd_Helper_viewHelper::__link('inschrijven') .'/'. FrontEnd_Helper_viewHelper::__link('stap2')?>" method="post">
    	<div class="sign-up-home-new">
        	<h4 class="text-center text-white" style="font-size:18px;"><?php echo $this->translate('Maak direct een gratis account aan op de vernieuwde kortingscode.nl !')?></h4>
        	<input onkeypress="if(event.which == 13) {  signUpFromHandler(); event.preventDefault(); }" type="text" placeholder="<?php echo $this->translate('e-mailadres');?>" id="emailAddressHomepage" name="emailAddress" label="emailAddress"/>
        	<a href="javascript:void(0)" onclick="signUpFromHandler();" id="stepOneFormSubmit" alt="<?php echo $this->translate('DOE MEE!');?>"><?php echo $this->translate('DOE MEE!');?></a>
    	</div>
	</form>
<?php 
endif; 
?>