<?php 
 $this->headTitle()->append($this->translate('Searchbar'));
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/jquery.validate.js");
 $this->headScript()->appendFile  ( PUBLIC_PATH . "/js/back_end/searchbar.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.dataTables.min.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/dataTableComman.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery-ui-1.8.16.custom.min.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
 $this->headLink ()->appendStylesheet ( PUBLIC_PATH . "/css/jquery-ui-1.8.16.custom.css" );
 
 $keywordAction = $this->editKeyword[0]['action'];
?>

<div class="wrap columns-2" id="editKeyword">
   <h1><?php echo $this->translate('Edit Redirect/Connect keyword in searchbar'); ?><button class="btn ml10" type="button" onClick="window.location.href='<?php echo HTTP_PATH ;?>admin/searchbar<?php echo '#'.$this->qstring; ?>'"><?php echo $this->translate('Cancel'); ?></button></h1>
        <form method="POST" enctype=multipart/form-data name="editKeywordForm" id="editKeywordForm">
        <input type="hidden" name='selectedShopId' id='selectedShopId' value="" />
        <input type="hidden" value="<?php echo $this->editKeyword[0]['id'];?>" name='id' id='id' />
        <input type="hidden" name='qString' id='qString' value='<?php echo $this->qstring; ?>' />
          <div id="poststuff" class="metabox-holder has-right-sidebar">
              <div id="post-body">
              <div>
               <div class="mainpage-content">
               <div class="mainpage-content-line">
                   <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Keyword'); ?></strong></label></div>
                       <div class="mainpage-content-right">
                         <div class="mainpage-content-right-inner-right-other" style="width:250px;"></div>
                          <div class="mainpage-content-right-inner-left-other">
                          <input type="text" class="span3" placeholder="<?php echo $this->translate('Keyword'); ?>"  name="keyword" id="keyword"  value="<?php echo $this->editKeyword[0]['keyword']?>"></div>
                          </div>
                        </div>
                        
                        <div class="mainpage-content-line">
                         <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Action'); ?></strong></label></div>
                        <div class="mainpage-content-right">
                          <div class="mainpage-content-right-inner-left-other">
                           <div data-toggle="buttons-checkbox" class="btn-group">
                          <button id='btnredirect'  type="button" onclick="changeAction(this,0)" name="redirect" class="<?php if($keywordAction==0){echo "btn btn-primary";}else{echo "btn";}?>"><?php echo $this->translate("Redirect") ; ?></button>
                          <button id='btnconnect'  style="border-radius: 0 4px 4px 0;" type="button" onclick="changeAction(this,1)" name="connect" class="<?php if($keywordAction==1){echo "btn btn-primary";}else{echo "btn";}?>"><?php echo $this->translate("Connect") ; ?></button>
                         
                         <input value="<?php echo $keywordAction; ?>" class="display-none" type="checkbox"  name="actionType" id="actionType" checked="<?php echo $keywordAction==0 ? 'checked' : ''; ?>"/>
                         <input type="hidden" value='<?php echo $keywordAction ?>' id='checkBoxVal'/>
                         
                         </div>
                          </div>
                         </div>
                        </div>
                        <div class="mainpage-content-line mt10">
                          <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Redirect To'); ?></strong></label></div>
                            <div class="mainpage-content-right">
                                <div class="mainpage-content-right-inner-right-other" style="width:250px;"></div>
                                <div class="mainpage-content-right-inner-left-other">
                                <?php if($keywordAction==0){?>
                                <input type="text" placeholder="<?php echo $this->translate('Redirect to'); ?>" class="span3" name="redirectTo" id="redirectTo" value="<?php echo $this->editKeyword[0]['url']?>">
                                <?php }else{?>
                                <input type="text" placeholder="<?php echo $this->translate('Redirect to'); ?>" class="span3" name="redirectTo" id="redirectTo" disabled="disabled">
                                <?php }?>
                                
                               </div>
                            </div>
                        </div>
                       
                        <div class="mainpage-content-line mt10" id='addButton'>
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Connect to'); ?></strong></label></div>
                            <div class="mainpage-content-right">
                            <div class="mainpage-content-right-inner-right-other" style="margin-top:2px;">
                            <div data-toggle="buttons-checkbox" class="btn-group">
                                <button type="button" onclick="addShop();" name="addStore" id="addStore" class="btn btn-primary"><?php echo $this->translate("ADD STORE")?></button>
                            </div>
                            </div>
                            <div class="mainpage-content-right-inner-left-other">
                            <div>
                            <input type="text" placeholder="<?php echo $this->translate('Search shop'); ?>" class="span3" name="connectTo" id="connectTo">
                           </div>
                           </div>
                           </div>
                           </div>
                       
                      
                        <div class="mainpage-content-line mt10" id="listShop" style="display:block">
                            <div class="mainpage-content-left"></div>
                            <div class="mainpage-content-right">
                                <ul id="shopListul-li">
                                    <?php 
                                    $ids ='';
                                    $j = 0;
                                    foreach ($this->editKeyword as $s)
                                    { 
                                        $li =  '<li class="search-add" id="'.$s['sid'].'" type="'.$s['sid'].'">';
                                        $li .= '<a href="javascript:void(0);" onClick="deleteShop('.$s['sid'] .')">
                                            <img src="'.IMG_PATH.'kc-search-cross.png"/></a>'.$s['name'].'</li>';
                                        echo $li;
                                        $j++;
                                        if ($j == count($this->editKeyword)) {
                                            $ids.= $s['sid'];
                                         } else {
                                            $ids.= $s['sid'].',';
                                        }
                                    }
                                    $a = rtrim(str_replace(",", " ", $ids));
                                    $gIds =  str_replace(" ", ",", $a); 
                                    ?>
                                </ul>
                                <input type="hidden" id="selectedShopForSearchbar" name="selectedShopForSearchbar" value="<?php echo $gIds; ?>">
                                <div class="clear mb10"></div>
                            </div>
                        </div>
                         
                         <!-- hide show div  -->
                        </div>
                        </div>
                      </div>
                    <br class="clear">
               </div>    
               <div class="mainpage-content-colorbox">
               <button type="submit" id="editKeyword" class="btn btn-large btn-primary fl"><?php echo $this->translate('SAVE CHANGES'); ?>
                </button>
                <a href="javascript:void(0);" onclick="window.location.href='<?php echo HTTP_PATH ;?>admin/searchbar'" class="fl m10" ><strong><?php echo $this->translate('CANCEL'); ?></strong>
                </a>
                <a id="deleteButton" class="fl red mt10" href="javascript:void(0);"  onclick="deleteKeywordByEdit();"><strong>
                <?php echo $this->translate('DELETE'); ?></strong>
                </a>
            </div>
            <!-- /poststuff -->
            </form>
</div>