<?php 
 $this->headTitle()->append($this->translate('Landing Pages'));
 $this->headScript()->appendFile(PUBLIC_PATH . "js/jquery.dataTables.min.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/jquery.validate.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "js/dataTableComman.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.NobleCount.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/jquery.textareaCounter.plugin.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/ckeditor/ckeditor.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/ckeditor/config.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/select2.min.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/editLandingPages.js");
?>
<div id="imbullbody-content">
    <?php echo $this->flashMessages(); ?>
    <div id="landingPagesEdit">
        <div class="wrap columns-2">
            <h1>
                <?php echo $this->translate('Edit Landing Page'); ?>
                <button class="btn ml10" type="button" onClick="window.location.href='<?php echo HTTP_PATH ;?>admin/landingpages'"><?php echo $this->translate('Cancel'); ?></button>
            </h1>

            <form method="POST" name="editLandingPage" id="editLandingPage">
                <div class="mainpage-content">
                    <div class="mainpage-content-line">
                        <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Online'); ?></strong></label></div>
                        <div class="mainpage-content-right">
                            <div data-toggle="buttons-checkbox" class="btn-group mb20">
                                <input type="hidden" id="status" name="status" value="<?php echo isset($this->landingPage['status']) ? $this->landingPage['status'] : 1; ?>">
                                <div class="btn-group" role="group">
                                    <button type="button" class="btn" id="statusActive" onClick="setStatus('statusActive')">
                                        <?php echo $this->translate('Yes'); ?>
                                    </button>
                                    <button type="button" class="btn" id="statusInactive" onClick="setStatus('statusInactive')">
                                        <?php echo $this->translate('No'); ?>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="mainpage-content-line mb10">
                        <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Shop Name'); ?></strong></label></div>
                        <div class="mainpage-content-right">
                            <div class="mainpage-content-right-inner-right-other"></div>
                            <div class="mainpage-content-right-inner-left-other">
                                <select name="shopName" class="combobox" id="shopName">
                                    <option value=""></option>
                                    <?php
                                    foreach ($this->shops as $shop) :
                                        echo "<option value=".$shop->id.">".$shop->name."</option>";
                                    endforeach;
                                    ?>
                                </select>
                                <input type="hidden" name="selectedShop" id="selectedShop" value="<?php echo isset($this->landingPage['selectedShop']) ? $this->landingPage['selectedShop'] : ''; ?>">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="mainpage-content">
                    <div class="mainpage-content-line">
                        <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Permalink'); ?></strong></label></div>
                        <div class="mainpage-content-right">
                            <div class="mainpage-content-right-inner-left"><label id="permalinkLabel"><?php echo $this->translate('http://www.kortingscode.nl/gad/'); ?></label></div>
                            <div class="mainpage-content-right-inner-right-other"></div>
                            <div class="mainpage-content-right-inner-right-full">
                                <input type="text" class="span3" style="margin-bottom: 0;" placeholder="<?php echo $this->translate('Permalink'); ?>" name="permalink" id="permalink" value="<?php echo isset($this->landingPage['permalink']) ? $this->landingPage['permalink'] : ''; ?>">
                                <span id="permalinkNote" class="nobel disabled word-count btop shop-wordcount-width"><?php echo $this->translate('Permalink must contain only letters, numbers, underscores or dashes.') ?></span>
                            </div>
                        </div>
                    </div>
                    <div class="mainpage-content-line">
                        <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Title'); ?></strong></label></div>
                        <div class="mainpage-content-right">
                            <div class="mainpage-content-right-inner-right-other"></div>
                            <div class="mainpage-content-right-inner-left-other">
                                <input type="text" class="span3" placeholder="<?php echo $this->translate('Title'); ?>" name="title" id="title" style="margin-bottom: 0;" value="<?php echo isset($this->landingPage['title']) ? $this->landingPage['title'] : ''; ?>">
                                <span id="titleLeft" class="nobel disabled btop word-count shop-wordcount-width"></span>
                            </div>
                        </div>
                    </div>
                    <div class="mainpage-content-line">
                        <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Subtitle'); ?></strong></label></div>
                        <div class="mainpage-content-right">
                            <div class="mainpage-content-right-inner-right-other"></div>
                            <div class="mainpage-content-right-inner-left-other">
                                <input type="text" class="span3 ignore" placeholder="<?php echo $this->translate('Subtitle'); ?>" name="subTitle" id="subTitle" style="margin-bottom: 0;" value="<?php echo isset($this->landingPage['subTitle']) ? $this->landingPage['subTitle'] : ''; ?>">
                                <span id="subTitleLeft" class="nobel disabled btop word-count shop-wordcount-width"></span>
                            </div>
                        </div>
                    </div>
                    <div class="mainpage-content-line">
                        <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Overwrite Title'); ?></strong></label></div>
                        <div class="mainpage-content-right">
                            <div class="mainpage-content-right-inner-right-other"></div>
                            <div class="mainpage-content-right-inner-left-other">
                                <input type="text" class="span3 ignore" placeholder="<?php echo $this->translate('Overwrite Title'); ?>" name="overwriteTitle" id="overwriteTitle" style="margin-bottom: 0;" value="<?php echo isset($this->landingPage['overwriteTitle']) ? $this->landingPage['overwriteTitle'] : ''; ?>">
                                <span id="overwriteTitleLeft" class="nobel disabled btop word-count shop-wordcount-width"></span>
                            </div>
                        </div>
                    </div>
                    <div class="mainpage-content-line">
                        <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Google/Meta Description'); ?></strong></label></div>
                        <div class="mainpage-content-right">
                            <div class="mainpage-content-right-inner-right-other"></div>
                            <div class="mainpage-content-right-inner-left-other">
                                <textarea class="input-xlarge mbot bbot ignore" id="metaDescription" name="metaDescription" placeholder="<?php echo $this->translate ( 'Meta Description' );?>" rows="3"><?php echo isset($this->landingPage['metaDescription']) ? $this->landingPage['metaDescription'] : ''; ?></textarea>
                                <input type="text" class="input-xlarge disabled btop word-count"  id="metaDescriptionLeft" disabled="disabled">
                            </div>
                        </div>
                    </div>

                    <div class="mainpage-content-line mb10">
                        <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Landing Page Content'); ?></strong></label></div>
                        <div class="mainpage-content-right">
                            <div class="mainpage-content-right-inner-right-other"></div>
                            <div class="mainpage-content-right-inner-left-other">
                                <textarea rows="3" id="pageContent" name="pageContent" placeholder="<?php echo $this->translate('Landing Page Content')?>" class="input-xlarge mbot bbot ignore word_count"><?php echo isset($this->landingPage['pageContent']) ? $this->landingPage['pageContent'] : ''; ?></textarea>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="mainpage-content-colorbox">
                    <button id="publishPageButton" type="submit" class="btn btn-large btn-primary fl"><?php echo $this->translate('PUBLISH PAGE'); ?></button>
                    <a class="fl m10" href="javascript:void(0);" onClick="window.location.href='<?php echo HTTP_PATH ;?>admin/landingpages'" ><strong><?php echo $this->translate('CANCEL'); ?></strong></a>
                </div>
                <input type="hidden" name="editId" id="editId" class="hide ignore" value="<?php echo isset($this->landingPage['id']) ? $this->landingPage['id'] : ''; ?>"/>
            </form>
        </div>
    </div>
</div>
