<?php 
 $this->headTitle()->append($this->translate('Landing Pages'));
 $this->headScript()->appendFile(PUBLIC_PATH . "js/jquery.dataTables.min.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "js/dataTableComman.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/bootbox.min.js");
 $this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/landingPages.js");
?>
<div id="landingPagesList">
   <div class="wrap columns-2">
       <?php echo $this->flashMessages(); ?>
        <h1 class="fl"><?php echo $this->translate('Landing Pages'); ?>
            <button class="btn ml10" type="button" onClick="window.location.href='<?php echo HTTP_PATH ;?>admin/landingpages/create'">
            <?php echo $this->translate('Add new Landing Page'); ?>
            </button>
        </h1>
        <div class="clear"></div>
        <table class="table table-bordered table-striped" id="LandingPagesListTbl" cellpadding="0" cellspacing="0">
            <thead>
                <tr>
                    <th><?php echo $this->translate('id');?></th>
                    <th><?php echo $this->translate('Landing Page Title');?></th>
                    <th><?php echo $this->translate('Shop Name');?></th>
                    <th><?php echo $this->translate('Permalink');?></th>
                    <th><?php echo $this->translate('Offers');?></th>
                    <th><?php echo $this->translate('Online');?></th>
                    <th><?php echo $this->translate('Offline Since');?></th>
                    <th><?php echo $this->translate('Action');?></th>
                </tr>
            </thead>
        </table> 
  </div>
</div>
        