<?php
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/datepicker.css" );
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/timepicker.css" );
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "js/back_end/openwysiwyg_v1.4.7/styles/wysiwyg.css" );
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/back_end/bootstrap-combobox.css" );
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/jquery.ui.widget.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/jquery.iframe-transport.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/jquery.fileupload.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/bootstrap-typeahead.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/select2.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/bootbox.min.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/jquery.textareaCounter.plugin.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/bootstrap-datepicker.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/bootstrap-timepicker.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/date.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.NobleCount.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/ckeditor/ckeditor.js");
$this->headScript ()->appendFile (PUBLIC_PATH . "js/back_end/ckeditor/config.js" );
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/addoffer.js");
$date = date("Y-m-d");
$today = time();
$twoMonthsLater = date('t-m-Y');
$role =  Zend_Auth::getInstance()->getIdentity()->users->id;
$code = "kortingscodeoffernews";
$secret = base64_encode($code);
?>
<script type="text/javascript">
    var CKEDITOR_BASEPATH = "<?php echo PUBLIC_PATH . "js/back_end/ckeditor/" ; ?>" ;
</script>
<?php echo $this->headTitle()->append('Create Offer');?>
<div class="wrap columns-2">
    <div class='wrap columns-2'>
        <?php 
        if ($this->messageSuccess!='' || $this->messageError!='' ) 
        {
            ?>
            <br><div class ="mainpage-content-colorbox success">
            <?php 
            if ($this->messageSuccess!='') 
            {
                ?>
                <span class="successserver"><?php echo $this->messageSuccess; ?></span>
                <?php 
            }
            if ($this->messageError!='') {?>
                <span class="errorserver"><?php echo $this->messageError; ?></span>
                <?php 
            } ?>
            </div>
        <?php } ?>
    </div>
        
    <form action="<?php echo HTTP_PATH; ?>admin/offer/saveoffer" name="addOffer" 
        id="addOffer" method="POST" enctype="multipart/form-data" autocomplete="off">
        <h1><?php echo $this->translate('Create Offer');?>
            <button type="button" onClick="window.location.href='<?php echo HTTP_PATH; ?>admin/offer'" 
            href="#" class="btn ml10"><?php echo $this->translate('Cancel'); ?>
            </button>
        </h1>
        <input type="hidden" name='offerImageSelect' id='offerImageSelect' value='' />
        <input type="hidden" id="saveAndAddnewId" name="saveAndAddnew" value="false" />
        <div class="row-fluid">
            <div class="span6">
                <div class="mainpage-content">
                    <div class="row-fluid mb10">
                        <div class="span4">
                            <strong><?php echo $this->translate('Name of Store'); ?></strong>
                        </div>
                        <div class="span8">
                            <select onchange="getShopDetail(this.value);" style="width : 250px;" name="whichshop" 
                            class="combobox" id="whichshop">
                            <option value=""></option>
                            <?php
                            for ($i=0;$i<count($this->shopList);$i++) {
                                if (trim($this->shopList[$i]['name'])!='') {
                                    $shopname = substr($this->shopList[$i]['name'],0,70);
                                    ?>
                                    <option value="<?php echo $this->shopList[$i]['id']; ?>">
                                        <?php echo $shopname; ?>
                                    </option>
                                    <?php
                                }
                            }
                            ?>
                            </select>
                            <input type="hidden" name="selctedshop" id="selctedshop" value="">
                        </div>
                    </div>
                    <div class="row-fluid mb10"></div>
                    <div class="row-fluid mb10" id="offertypeDiv">
                        <div class="span4">
                            <strong><?php echo $this->translate('Type of Discount'); ?></strong>
                        </div>
                        <div class="span8">
                            <div data-toggle="buttons-checkbox" class="btn-group mb20">
                                <input type="checkbox" id="couponCodeCheckbox" name="couponCodeCheckbox" 
                                    checked="checked" value="coupon" style="display:none;">
                                <input type="checkbox" id="newsCheckbox" name="newsCheckbox" 
                                    value="news" style="display:none;">
                                <input type="checkbox" id="saleCheckbox" name="saleCheckbox" 
                                    value="sale" style="display:none;">
                                <input type="checkbox" id="printableCheckbox" name="printableCheckbox" 
                                    value="printable" style="display:none;">
                                <button type="button" class="btn btn-primary" 
                                    style="border-radius: 4px 0 0 4px;" 
                                    id="couponCode" onClick="selectDiscountType('couponCode')">
                                    <?php echo $this->translate('Coupon'); ?>
                                </button>
                                <button type="button" class="btn" id="sale" 
                                    onClick="selectDiscountType('sale')">
                                    <?php echo $this->translate('Sale'); ?>
                                </button>
                                <button type="button" class="btn" id="printable" 
                                    onClick="selectDiscountType('printable')">
                                    <?php echo $this->translate('Printable'); ?>
                                </button>
                            </div>           
                        </div>
                    </div>
                </div>
            </div>
            <div class="span6">
                <div class="mainpage-content">
                    <div class="row-fluid mb10" id="aboutShopNoteDiv">
                        <div class="span4">
                            <strong><?php echo $this->translate('Note from this shop:'); ?></strong>
                        </div>
                        <div class="span8">
                            <div class="" id="shopNotes">&nbsp;</div>
                        </div>
                    </div>
                    <div class="row-fluid mb10">
                        <div class="span4">
                            <strong><?php echo $this->translate('Code Alert visitors count'); ?></strong>
                        </div>
                        <div class="span8">
                            <span id="code-alert-visitors-count">&nbsp;</span>
                        </div>
                    </div>
                    <div class="row-fluid mb10" id="aboutNertworkDiv">
                        <div class="span4">
                            <strong><?php echo $this->translate('Network'); ?></strong>
                        </div>
                        <div class="span8">
                            <div id="shopNetwork">&nbsp;</div>
                            <input type="hidden" name="strictConfirmation" id="strictConfirmation" value="0" />
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="mainpage-content">
            <div class="row-fluid">
                <div class="span2">
                    <label><strong><?php echo $this->translate('Title'); ?></strong></label>
                </div>
                <div class="span8">
                    <input type="text" id="addofferTitle"  name="addofferTitle" 
                        placeholder="<?php echo $this->translate('This account is important, etc');?>" class="span10 mbot bbot">
                        <input type="text" disabled="disabled" 
                        value="<?php echo $this->translate('Offer title length 0 characters');?>" id="metaTextLeft" 
                        class="span10 disabled btop word-count">
                </div>
                <div class="span2"></div>
            </div>
            <div class="row-fluid general-code-cont">
                <div class="span2" id="ccode">
                    <label><strong><?php echo $this->translate('Coupon code'); ?></strong></label>
                </div>
                <div class="span8">
                    <input type="text" name="couponCode" id="couponCodeTxt" 
                    placeholder="<?php echo $this->translate('centerparks'); ?>" class="span10">
                </div>
                <div class="span2">
                    <label></label>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span2">
                    <label><strong><?php echo $this->translate('Start Date'); ?></strong></label>
                </div>
                <div class="span2">
                    <div data-date-format="dd-mm-yyyy" data-date="<?php echo date('d-m-Y');?>" id="dp3" 
                    class="input-append date">
                        <input readonly="readonly" type="text"  value="<?php echo date('d-m-Y');?>"  
                            placeholder="<?php echo $this->translate('Sunday, April 1');?>" 
                            class="span2 ignore2 date-time-cusor-style" 
                            id="offerStartDate" name="offerStartDate">
                        <span class="add-on"><i class="icon-th"></i></span>
                    </div>
                </div>
                <div class="span2">    
                    <div class="input-append bootstrap-timepicker-component" style="display: inline-block;">
                        <input readonly="readonly" type="text" id="offerstartTime" name="offerstartTime" 
                            class="input-small timepicker-default ignore2 date-time-cusor-style">
                        <span class="add-on">
                            <i class="icon-time" style="background-position: -47px -24px;"></i>
                        </span>
                    </div>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span2">
                    <label><strong><?php echo $this->translate('End Date'); ?></strong></label>
                </div>
                <div class="span2">
                    <div data-date-format="dd-mm-yyyy" data-date="<?php echo $twoMonthsLater;?>" id="dp4" 
                        class="input-append date">
                        <input readonly="readonly"  type="text" value="<?php echo $twoMonthsLater; ?>" 
                            placeholder="<?php echo $this->translate('Sunday, April 1');?>" name="offerEndDate" id="offerEndDate" 
                            class="span2 ignore2 date-time-cusor-style">
                        <span class="add-on"><i class="icon-th"></i></span>
                    </div>
                </div>
                <div class="span2">   
                    <div class="input-append bootstrap-timepicker-component" style="display: inline-block;">
                        <input readonly="readonly" type="text" name="offerendTime" id="offerendTime" 
                        class="input-small timepicker-default ignore2 date-time-cusor-style">
                        <span class="add-on">
                            <i class="icon-time" style="background-position: -47px -24px;"></i>
                        </span>
                    </div>
                </div>    
            </div>
            <div class="row-fluid">
                <div class="span2"><label>
                    <strong><?php echo $this->translate('Terms and Conditions'); ?></strong></label>
                </div>
                <div class="span10">
                    <textarea id="termsAndcondition" class="input-xlarge mbot bbot ignore word_count" 
                    name="termsAndcondition" 
                    placeholder="<?php echo $this->translate('Terms & Conditions')?>"></textarea>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span2"></div>
            </div>
            <span id="couponDiv">
                <div class="row-fluid">
                    <div class="span2"></div>
                    <div class="span10">
                        <div class="category-error"></div>
                        <div class="categories" style="position:relative;" id="offertilesimg" name="tiles">
                            <input style='display:none' type="checkbox" 
                            name="selectedTiles[]" id='selectedTiles'  class="tiles" />
                            <ul class='imgTiles' id='imgLiForTiles'>
                                <?php
                                    if (count(@$this->tiles['couponCode'])) :
                                        foreach($this->tiles['couponCode'] as $tiles):
                                            if (file_exists(ROOT_PATH . $tiles['path'] . 'thum_small_' . $tiles['name'])) :
                                                $imgTilesCode = PUBLIC_PATH_LOCALE . $tiles['path'] . 'thum_small_' . $tiles['name'];
                                            else :
                                                $imgTilesCode = PUBLIC_PATH .'images/NoImage/NoImage_95x80.png';
                                            endif;
                                            echo '<li id="'.$tiles['id'].'">'.
                                                    '<a href="javascript:void(0)" onclick="selectOfferImage(' . $tiles['id'] . ')" id="'.$tiles['id'].'">'.
                                                        '<img id="offertileimg" title="kortingsbon" src="'.$imgTilesCode.'" class="liimg">'.
                                                    '</a>'.
                                                    '<div class="hideShow" style="display:block" id="divShow_'.$tiles['id'].'">'.
                                                        '<a data-toggle="modal" href="_#myModal" onclick="setValueInHidden('.$tiles['id'].')">'.
                                                            '<img src="'.PUBLIC_PATH.'/images/back_end/edit-icon-txt.png">'.
                                                        '</a>'.
                                                        '<a href="javascript:void(0);" style="display:none" id="selectImg_'.$tiles['id'].'" class="unselect">'.
                                                            '<img src="'.PUBLIC_PATH.'/images/back_end/tick.png">'.
                                                        '</a>'.
                                                    '</div>'.
                                                '</li>';
                                        endforeach;
                                    endif;
                                ?>
                                <li id='before'>
                                    <a href="_#myModal"  data-toggle="modal" onClick="hideDeleteButton();"><img src="<?php echo PUBLIC_PATH;?>/images/back_end/plus.png"></a>
                                    <div>
                                        <a href="javascript:void(0);"></a>
                                        <a href="javascript:void(0);" style="display: none;"></a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="span2"></div>
                    <div class="span8"><div class="category-error"></div></div>
                </div>
            </span>
            <span id="saleDiv">
                <div class="row-fluid">
                    <div class="span2"></div>
                    <div class="span10">
                        <div class="clear line"></div>
                        <div>
                            <div class="category-error"></div>
                            <div id="offertilesimg" class='mainpage-content-right-inner-left-other'>
                                <input style='display:none' type="checkbox" name="saleTiles[]" id='saleTiles'  
                                class="tiles" />
                                <ul class='imgTiles' id='imgLiForTiles'>
                                    <?php
                                        if(count($this->tiles['sale'])) :
                                            foreach($this->tiles['sale'] as $tiles):
                                                if(file_exists(ROOT_PATH . $tiles['path'] . 'thum_small_' . $tiles['name'])) :
                                                    $imgTilesSale = PUBLIC_PATH_LOCALE . $tiles['path'] . 'thum_small_' . $tiles['name'];
                                                else :
                                                    $imgTilesSale = PUBLIC_PATH.'images/NoImage/NoImage_95x80.png';
                                                endif;
                                                echo '<li id="'.$tiles['id'].'">'.
                                                        '<a href="javascript:void(0)" onclick="selectOfferImage('.$tiles['id'].')" id="'.$tiles['id'].'">'.
                                                            '<img id="offertileimg" title="kortingsbon" src="'.$imgTilesSale.'" class="liimg">'.
                                                        '</a>'.
                                                        '<div class="hideShow" style="display:block" id="divShow_'.$tiles['id'].'">'.
                                                            '<a data-toggle="modal" href="_#myModal" onclick="setValueInHidden('.$tiles['id'].')">'.
                                                                '<img src="'.PUBLIC_PATH.'/images/back_end/edit-icon-txt.png">'.
                                                            '</a>'.
                                                            '<a href="javascript:void(0);" style="display:none" id="selectImg_'.$tiles['id'].'" class="unselect">'.
                                                                '<img src="'.PUBLIC_PATH.'/images/back_end/tick.png">'.
                                                            '</a>'.
                                                        '</div>'.
                                                    '</li>';
                                            endforeach;
                                        endif; ?>
                                   <li id='before'>
                                    <a href="_#myModal" onClick="hideDeleteButton();" 
                                    data-toggle="modal">
                                    <img src="<?php echo PUBLIC_PATH;?>/images/back_end/plus.png"></a>
                                        <div>
                                            <a href="javascript:void(0);"></a>
                                            <a href="javascript:void(0);" style="display: none;"></a>
                                        </div>
                                   </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>    
            </span>
            <span id="printDiv" style="display:none;">
                <div class="row-fluid">
                    <div class="span2"></div>
                    <div class="span10">    
                        <div class="clear line"></div>
                        <div data-toggle="buttons-checkbox" class="btn-group mb20">
                            <button type="button" class="btn btn-primary" id="uploadOfferOption" 
                                onClick="printOption('uploadOfferOption')" >
                                <?php echo $this->translate('Upload Offer (pdf or jpg)'); ?>
                            </button>
                            <button type="button" class="btn" id="userefurlOption" 
                                onClick="printOption('userefurlOption')" >
                                <?php echo $this->translate('Use Ref URL / URL'); ?>
                            </button>
                        </div>
                        <input type="checkbox" value="uploadoffer" id="uploadoffercheck" 
                            name="uploadoffercheck" style="display:none;" checked="checked">
                        <div class="mainpage-content-right-inner-right-other uploadOfferMessage"></div>
                        <div class="mainpage-content-right-inner-left-other" id="uploadofferDiv">
                            <input type="file" class="ignore" name="uploadoffer" id = "uploadoffer" 
                            onchange="checkFileType(event)" /><span>
                            <?php echo $this->translate('Upload .jpg or .pdf file only (Maximum file size: 2MB)')?>
                            </span>
                        </div>
                        <input type="checkbox" value="offerrefurl" id="offerrefurlcheck" 
                            name="offerrefurlcheck" style="display:none;">
                        <div class="mainpage-content-right-inner-right-other offerrefurlMessage"></div>
                        <div class="mainpage-content-right-inner-left-other" id="offerrefurlDiv" 
                            style="display:none;">
                            <input type="text" class="span3" name="offerrefurlPR" id = "offerrefurlPR" 
                            placeholder="<?php echo $this->translate('Ref url');?>" />
                        </div>
                        <!-- offer tiles code starts here -->
                        <div id="offertilesimg" class='mainpage-content-right-inner-left-other'>
                            <ul class='imgTiles' id='imgLiForTiles'>
                                <?php
                                    if(count($this->tiles['printable'])) :
                                        foreach($this->tiles['printable'] as $tiles):
                                            if(file_exists(ROOT_PATH . $tiles['path'] . 'thum_small_' . $tiles['name'])) :
                                                $imgTilesPrint = PUBLIC_PATH_LOCALE . $tiles['path'] . 'thum_small_' . $tiles['name'];
                                            else :
                                                $imgTilesPrint = PUBLIC_PATH.'images/NoImage/NoImage_95x80.png';
                                            endif;
                                            echo '<li id="'.$tiles['id'].'">'.
                                                    '<a href="javascript:void(0)" onclick="selectOfferImage('.$tiles['id'].')" id="'.$tiles['id'].'">'.
                                                        '<img id="offertileimg" title="kortingsbon" src="'.$imgTilesPrint.'" class="liimg">'.
                                                    '</a>'.
                                                    '<div class="hideShow" style="display:block" id="divShow_'.$tiles['id'].'">'.
                                                        '<a data-toggle="modal" href="_#myModal" onclick="setValueInHidden('.$tiles['id'].')">'.
                                                            '<img src="'.PUBLIC_PATH.'images/back_end/edit-icon-txt.png">'.
                                                        '</a>'.
                                                        '<a href="javascript:void(0);" style="display:none" id="selectImg_'.$tiles['id'].'" class="unselect">'.
                                                            '<img src="'.PUBLIC_PATH.'images/back_end/tick.png">'.
                                                        '</a>'.
                                                    '</div>'.
                                                '</li>';
                                        endforeach;
                                    endif; ?>
                                <li id='before'>
                                    <a href="_#myModal" onClick="hideDeleteButton();" 
                                    data-toggle="modal">
                                    <img src="<?php echo PUBLIC_PATH;?>/images/back_end/plus.png"></a>
                                    <div>
                                        <a href="javascript:void(0);"></a>
                                        <a href="javascript:void(0);" style="display: none;"></a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>        
            </span>
        </div>
        
        <div class="mainpage-content mainpage-content-buttons" id="offerButtons">
            <div class="row-fluid">
                <div class="span12">
                    <button id='addOfferBtn' onclick="jQuery('#saveAndAddnewId').val(false);" 
                        type="submit" class="btn btn-large btn-primary fl mr15">
                        <?php echo $this->translate('backend_ADD OFFER'); ?>
                    </button>
                    <button id="saveAndAddnew" onclick="jQuery('#saveAndAddnewId').val(true);" 
                        class="btn btn-large btn-primary fl" type="submit">
                        <?php echo $this->translate('Save and Add New Offer');?>
                    </button>
                        <a href="<?php echo HTTP_PATH; ?>admin/offer" class="fl m10">
                            <strong class="ml10">
                                <?php echo $this->translate('CANCEL'); ?>
                            </strong>
                        </a>
                </div>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span2">
                <label><strong><?php echo $this->translate('Show Hidden Options'); ?></strong></label>
            </div>
            <div class="span10">
                <div data-toggle="buttons-checkbox" class="btn-group ">
                <button type="button" id="optionsOnbtn" class="btn">
                    <?php echo $this->translate('On'); ?>
                </button>
                <button type="button" id="optionsoffbtn" class="btn mr10 btn-primary" 
                    style="border-radius: 0 4px 4px 0;">
                    <?php echo $this->translate('Off'); ?>
                </button>
               </div>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span2"></div>
        </div> 
        <div id="offerOption" style = "display:none;">                  
            <div class="mainpage-content">
                <div class="row-fluid">
                    <div class="span2 mb10">
                        <label><strong><?php echo $this->translate('Offer Position'); ?></strong></label>
                    </div>
                    <div class="span10">
                        <div data-toggle="buttons-checkbox" class="btn-group mb10">
                            <input type="text" name="offerPosition" id="offerPosition" 
                                placeholder="<?php echo $this->translate('backend_offer position');?>" 
                                class="input-small mbot bbot ignore span3"/>
                        </div>
                    </div>
                </div>
                <div class="row-fluid" id="visibiliyDiv">
                    <div class="span2 mb10">
                        <label><strong><?php echo $this->translate('Visibility'); ?></strong></label>
                    </div>
                    <div class="span10">
                        <div data-toggle="buttons-checkbox" class="btn-group">
                            <button type="button" class="btn btn-primary"  id="default" 
                                onClick="selectOfferType('default')">
                                <?php echo $this->translate('Default'); ?>
                            </button>
                            <input type="checkbox" checked="checked" class="display-none" 
                                name="defaultoffercheckbox" id="defaultoffercheckbox" value="defaultoffercheckbox">
                            <button type="button" class="btn" style="border-radius: 0 4px 4px 0;" 
                                id="memberOnly" onClick="selectOfferType('memberOnly')">
                                <?php echo $this->translate('Members Only'); ?>
                            </button>
                            <input type="checkbox" name="memberonlycheckbox" class="display-none" 
                                id="memberonlycheckbox" value="defaultoffercheckbox">
                          </div>
                    </div>
                </div>
                <div id="membersOnlyDiv" style="display:none;">
                    <div class="row-fluid mb10">
                        <div class="span2"><strong><?php echo $this->translate('From which shop?'); ?></strong></div>
                          <div class="span10">
                            <div class="btn-group" data-toggle="buttons-checkbox" >
                                <button type="button" id="existingShop" name="existingShop" 
                                    class="btn btn-primary"><?php echo $this->translate('Existing Shop'); ?>
                                </button>
                                <input type="checkbox" checked="checked" class="display-none" 
                                    name="existingShopCheckbox" id="existingShopCheckbox" value="existingShopCheckbox">
                                <button type="button" id="notExistingShop" name="notExistingShop" 
                                    class="btn" style="border-radius: 0 4px 4px 0;">
                                    <?php echo $this->translate('Not Existing Shop'); ?>
                                </button>
                                <input type="checkbox" checked="checked" class="display-none" 
                                    name="notExistingShopCheckbox" id="notExistingShopCheckbox" 
                                    value="notExistingShopCheckbox">
                                <input type="hidden" name="fromWhichShop" value="1" id="fromWhichShop">
                            </div>
                        </div>
                    </div>
                </div>
                <div id="notExistShop" style="display:none;">
                    <div class="row-fluid">
                        <div class="span2">
                            <label><strong><?php echo $this->translate('Shop Name'); ?></strong></label>
                        </div>
                        <div class="span10">
                            <div class="mainpage-content-right-inner-right-other"></div>
                            <div class="mainpage-content-right-inner-left-other">
                                <input type="text" class="span3"  id="newShop" name="newShop" 
                                placeholder="<?php echo $this->translate('Shop Name');?>">
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span2">
                            <label><strong><?php echo $this->translate('Upload Logo'); ?></strong></label>
                        </div>
                        <div class="span10">
                            <div class="mainpage-content-right-inner-right-other"></div>
                            <div style="margin-right: 0px;" class="mainpage-content-right-inner-left-other">
                                <input  data-max-size="2097152" type="file" name="logoFile" 
                                id="logoFile" class="ignore" />
                                <span id="logo_file_message" class="help-inline" 
                                style="display: inline-block; padding-bottom: 5px; margin-left: 10px;">
                                <?php echo $this->translate('Upload .jpg or .png file only (Maximum file size: 2MB, Ratio 2:01)'); ?></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="offertitledetail">
                    <div class="row-fluid">
                       <div class="span2">
                            <label><strong><?php echo $this->translate('Deeplinking is'); ?></strong></label>
                        </div>
                        <div class="span10">
                            <div data-toggle="buttons-checkbox" class="btn-group ">
                            <button type="button" id="deepLinkOnbtn" class="btn">
                            <?php echo $this->translate('On'); ?></button>
                            <button type="button" id="deepLinkoofbtn" class="btn mr10 btn-primary" 
                            style="border-radius: 0 4px 4px 0;"><?php echo $this->translate('Off'); ?></button>
                            <input type="checkbox" name="deepLinkStatus" value="1" id="deepLinkStatus" 
                            style="display:none;">
                           </div>
                        </div>
                    </div>    
                    <div class="row-fluid">
                        <div class="span2">
                            <label><strong><?php echo $this->translate('Ref URL'); ?></strong></label>
                        </div>
                        <div class="span10">
                            <div class="mainpage-content-right-inner-right-other"></div>
                            <div class="mainpage-content-right-inner-left-other">
                                <input type="text" id="offerRefUrl" disabled="disabled" 
                                name = "offerRefUrl"  placeholder="<?php echo $this->translate('Ref. Url');?>" class="span3">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span2"></div>
                    <div class="span10">
                        <div id='error-message' class="error-message category-error mainpage-content-right-inner-right-other"></div>
                         <div class="categories" style="position:relative;" name="category">
                          <?php for($i = 0;  $i < count($this->catList) ; $i++ ){ ?>
                            <div class="square-btn-offer">
                            <input type="checkbox" value="<?php echo $this->catList[$i][0]['id']; ?>" 
                            class="" name="selectedcategories[]" 
                            id="category-<?php echo $this->catList[$i][0]['id']; ?>" />
                            <?php if (trim($this->catList[$i][0]['name'])!='') {
                            $categoryIconPath = '';
                            $icons = $this->catList[$i][0];
                            # check an icon is available of not
                            if(file_exists(ROOT_PATH.$icons['categoryicon']['path']."thum_medium_".$icons['categoryicon']['name'])) {
                                $categoryIconPath = PUBLIC_PATH_LOCALE.$icons['categoryicon']['path']."thum_medium_".$icons['categoryicon']['name'];
                            } else {
                                $categoryIconPath = HTTP_PATH ."public/images/NoImage/NoImage50x50.jpg";
                            }
                            ?>
                            <button type="button" name="selectCategory" 
                                title="<?php echo $this->catList[$i][0]['name'];?>" class="btn square-btn" 
                                id="categoryBtn-<?php echo $this->catList[$i][0]['id'];?>" 
                                onClick="addCategory('<?php echo $this->catList[$i][0]['id']; ?>')">
                                <img alt="Baby &amp; Kinderen" src="<?php echo $categoryIconPath ;?>">
                             </button>
                             <div class="clear"></div>
                                 <span class="image-description-text">
                                     <?php echo strlen($this->catList[$i][0]['name']) < 20 ? $this->catList[$i][0]['name'] : substr($this->catList[$i][0]['name'],0,20).'..'; ?>
                                 </span>

                            </div>
                          <?php } } ?>
                        </div>
                    </div>
                </div>
                <div class="row-fluid" id="attachpagesDiv">
                    <?php if(count($this->pages) > 0) : ?>
                    <div id="attachToPage">
                        <div class="span2">
                            <label>
                                <strong><?php echo $this->translate('Attach to pages'); ?></strong>
                            </label>
                        </div>
                        <div class="span10">
                            <div class="web-address-list multiselect">
                                <ul><?php for($i=0;$i<count($this->pages);$i++){?>
                                    <li class="list_1" style ="font-weight:normal;">
                                        <input type="checkbox" value="<?php echo $this->pages[$i]['id']; ?>" 
                                        name="attachedpages[]" style="display: none;"> &nbsp;
                                        <?php echo $this->pages[$i]['pageTitle']; ?>
                                    </li>
                                <?php }?>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <?php endif;?>
                </div>
                <div class="row-fluid mb10" id='extraOptions'>
                    <div class="span2">
                        <label><strong><?php echo $this->translate('Extra options'); ?></strong></label>
                    </div>
                    <div class="span10">
                        <div data-toggle="buttons-checkbox" class="btn-group ">
                            <input type="checkbox" name="exclusivecheckbox" id="exclusivecheckbox"
                                value="1" style="display:none;" />
                            <input type="checkbox" name="editorpickcheckbox" id="editorpickcheckbox" 
                                value="2" style="display:none;"  />
                            <input type="checkbox" checked='checked' name="nonecheckbox" id="nonecheckbox" 
                                value="0" style="display:none;"  />
                            <button type="button" class="btn" value="exclusive" 
                                style="border-radius: 4px 0 0 4px;" onCLick = "exclusiveeditorpick(event)">
                                <?php echo $this->translate('Exclusive Code'); ?>
                            </button>
                            <button type="button"  class="btn" value = "editorpic" 
                                onCLick = "exclusiveeditorpick(event)">
                                <?php echo $this->translate('Recommended'); ?>
                            </button>
                            <button type="button" style="border-radius: 0 4px 4px 0;" 
                                class="btn btn-primary" value = "none" onCLick = "exclusiveeditorpick(event)">
                                <?php echo $this->translate('None'); ?>
                            </button>
                       </div>
                    </div>
                </div>
                <div class="row-fluid mb10">
                    <div class="span2">
                        <label>
                            <strong><?php echo $this->translate('Code alert'); ?></strong>
                        </label>
                    </div>
                    <div class="span10">
                        <div data-toggle="buttons-checkbox" class="btn-group ">
                            <button type="button" class="btn" value="yes" onClick="codeAlertToggle(event);">
                                <?php echo $this->translate('Yes'); ?>
                            </button>
                            <button type="button" class="btn btn-primary" style="border-radius: 0 4px 4px 0;" 
                                value="no" onClick="codeAlertToggle(event);">
                                <?php echo $this->translate('No'); ?>
                            </button>
                            <input type="hidden" value="0" name="codealertcheckbox" id="codealertcheckbox">
                       </div>
                    </div>
                </div>
                <div class="row-fluid mb10" id="extendedOfferDivDown">
                    <div class="span2">
                        <label><strong><?php echo $this->translate('Extended offer'); ?></strong></label>
                    </div>
                    <div class="span10">
                        <div data-toggle="buttons-checkbox" class="btn-group ">
                            <button type="button" class="btn" value="yes" id="extendedYes" 
                                onClick="extenOffer(event);"><?php echo $this->translate('Yes'); ?>
                            </button>
                            <button type="button" class="btn btn-primary" id="extendedNo" 
                                style="border-radius: 0 4px 4px 0;"  value="no" onClick="extenOffer(event);">
                                <?php echo $this->translate('No'); ?>
                            </button>
                            <input type="checkbox" value="1" name="extendedoffercheckbox" 
                                id="extendedoffercheckbox" style="display:none;">
                       </div>
                    </div>
                </div>
                <div style="display:none;" id="extendedoffer-container">
                    <div class="row-fluid">
                        <div class="span2">
                            <label>
                                <strong><?php echo $this->translate('Extended Title'); ?></strong>
                            </label>
                        </div>
                        <div class="span10">
                            <div class="mainpage-content-right-inner-right-other"></div>
                            <div class="mainpage-content-right-inner-left-other">
                                <input type="text" name="extendedTitle" id="extendedTitle" 
                                    placeholder="<?php echo $this->translate('This account is important, etc');?>" 
                                    class="input-xlarge mbot bbot ignore span3"/>
                                <input type="text" disabled="disabled" 
                                    value="<?php echo $this->translate('Extended title length 0 characters');?>" 
                                    id="extendedTitleLeft" class="input-xlarge disabled btop word-count">
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span2">
                            <label><strong><?php echo $this->translate('Meta Title'); ?></strong></label>
                        </div>
                        <div class="span10">
                            <div class="mainpage-content-right-inner-right-other"></div>
                            <div class="mainpage-content-right-inner-left-other">
                                <input type="text" name="extendedOfferTitle" id="extendedOfferTitle" 
                                placeholder="<?php echo $this->translate('This account is important, etc');?>" 
                                class="input-xlarge mbot bbot ignore span3"/>
                                <span id="metaTitleLeft" 
                                class="disabled btop word-count nobel offer-wordcount-width"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span2">
                            <label>
                                <strong><?php echo $this->translate('Meta Description'); ?></strong>
                            </label>
                        </div>
                        <div class="span10">
                            <div class="mainpage-content-right-inner-right-other"></div>
                            <div class="mainpage-content-right-inner-left-other">
                                <textarea class="input-xlarge mbot bbot ignore" id="extendedOfferMetadesc" 
                                name="extendedOfferMetadesc" 
                                placeholder="<?php echo $this->translate('Een Center Parcs actiecode of kortingscode is zo gevonden op Actiecode.nl. Wij hebben codes en korting beschikbaar voor lente zomer, herfst & winter.');?>" rows="3"></textarea>
                                <span id="metaDescLeft" 
                                class="disabled btop word-count nobel offer-wordcount-width"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span2">
                            <label><strong>
                            <?php echo $this->translate('Permalink'); ?></strong>
                            </label>
                        </div>
                        <div class="span10">
                            <div class="mainpage-content-right-inner-right-other"></div>
                            <div class="mainpage-content-right-inner-left-other">
                                <input type="text" name="extendedOfferRefurl" 
                                id="extendedOfferRefurl" 
                                placeholder="<?php echo $this->translate('permalink'); ?>" class="span3 ignore">
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span2">
                            <label>
                                <strong>
                                <?php echo $this->translate('Full info about the Coupon'); ?>
                                </strong>
                            </label>
                        </div>
                        <div class="span10">
                            <div class="mainpage-content-right-inner-right-other"></div>
                            <div class="mainpage-content-right-inner-left-other">
                                <textarea id="couponInfo" name="couponInfo"></textarea>
                           </div>
                      </div>
                   </div>
                </div>
                <div class="row-fluid">
                    <div class="span12">
                        <div class="mainpage-content alert-error strict-confirmation-alert hide">
                            <input id="enableSaveButtons" type="checkbox">
                                <p><?php
                                    echo $this->translate('This Shop has STRICT CONFIRMATION Enabled, 
                                    Before you place this coupon be sure you got confirmation from Tom, Arthur or Jochem.'); ?>
                                </p>
                        </div>
                    </div>    
                </div>
            </div>    
            <div class="mainpage-content-colorbox" id="offerEndButtons">
                <button id='addOfferBtn' onclick="jQuery('#saveAndAddnewId').val(false);" 
                type="submit" class="btn btn-large btn-primary fl mr15">
                <?php echo $this->translate('backend_ADD OFFER'); ?></button>
                <button id="saveAndAddnew" onclick="jQuery('#saveAndAddnewId').val(true);" 
                class="btn btn-large btn-primary fl" type="submit">
                <?php echo $this->translate('Save and Add New Offer');?></button>
                
                <a href="<?php echo HTTP_PATH; ?>admin/offer" class="fl m10">
                    <strong class="ml10"><?php echo $this->translate('CANCEL'); ?></strong>
                </a>
            </div>
        </div>
    </form>
</div>
<div class="modal display-none popup-width" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="wrap columns-2">
        <form name="menuForm" id="menuForm" enctype="multipart/form-data">
            <input type="hidden" name="offerId" id="offerId" value="">
            <div class="m-item-popup-hdr"><?php echo $this->translate('Menu item');?></div>
                <div id="poststuff" class="metabox-holder has-right-sidebar">
                    <div id="post-body">
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Label');?></strong></label></div>
                            <div class="mainpage-content-right-inner-right-other display-none"></div>
                            <div class="mainpage-content-right">
                                <input type="text" placeholder="Label.." class="span3" name="label" id="label">
                            </div>
                        </div>
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Icon');?></strong></label></div>
                            <div class="mainpage-content-right-inner-right-other display-none"></div>
                            <div class="mainpage-content-right">
                                <div class="fileupload fileupload-new" data-provides="fileupload">
                                    <input type="file" id="tileUpload" name="tileupload[]"/>
                                </div>
                                <span id="imageName"></span>
                             </div>
                         </div>

                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Sort');?></strong></label></div>
                             <div class="mainpage-content-right-inner-right-other display-none"></div>
                                <div class="mainpage-content-right">
                                <input type="text" name="position" id="position" placeholder="1" class="span3">
                            </div>
                        </div>
                     </div>
                     <br class="clear">
                    </div>

                    <div class="m-item-popup-btm">
                        <input type="hidden" name='forDelete' id='forDelete' value='' />
                        <input type="hidden" id="hidimage" name="hidimage" value="">
                        <input type="hidden" id="hidimagepath" name="hidimagepath" value="">
                        <input type="hidden" id="hidimageext" name="hidimageext" value="">
                        <input type="hidden" id="hidtype" name="hidtype" value="">
                        <button id="submitButton" class="btn btn-large btn-primary fl" type="submit"><?php echo $this->translate('SAVE CHANGES');?></button>
                        <button class="btn ml10 m5" data-dismiss="modal"><?php echo $this->translate('Cancel');?></button>
                        <button style='display: none' id='deleteImage' class="btn ml10 m5 red" data-dismiss="modal"><?php echo $this->translate('Delete');?></button>
                    </div>
                    <!-- /poststuff -->
               </form>
          </div>
    </div>