<?php 
$this->minifyHeadScript()->prependFile("public/js/front_end/socialmedia.js");
$partialViewPath = 'partials/';
$offers = '';
if(!empty($this->offers)):
    $offers .= '<header class="heading-box">
            <h2>'.$this->translate('Offers matching search results').'</h2>
        </header>';
    $offers .= $this->partial(
        $partialViewPath. '_offer.phtml',
        array(
            'offers' => $this->offers,
            'offersType'=>'searchedOffers',
            'shopName' => '',
            'shop' => '',
            'zendForm'=>$this->form
        )
    );
else:
    $offers .= '<div class="message">
            <div class="holder">
                <span class="ico-warning"></span>
                <span class="text">
                    <span>'.$this->translate('Sorry, no vouchercodes found with the search input').'!</span>
                </span>
            </div>
        </div>';
endif;

$signUpWidgetForm = '';
$signUpWidgetForm = $this->partial(
    $partialViewPath.'_signupForm.phtml',
    array(
       'zendForm' => $this->sidebarWidgetForm,
       'SignupFormWidgetType'=> 'sidebarWidget',
       'shopId'=>'',
       'shopLogoOrDefaultImage'=>''
    )
);

$popularStores = '';
if(count($this->popularStores)){
    $popularStores = $this->partial(
        'search/_popular-stores.phtml',
        array(
           'popularStores' => $this->popularStores,
           'offers' => count($this->offers)
        )
    );
}

$pageAction = 'search';
if (LOCALE == '') :
    $pageAction = 'zoeken';
endif;
?>
<div class="banner-block">
    <img class="image" src="<?php echo $this->pageLogo; ?>" alt="image description">
    <div class="bar">
        <span><?php echo $this->translate('Results for'); ?> '<?php echo $this->searchedKeyword; ?>'</span>
        <a href="<?php echo HTTP_PATH_LOCALE.$pageAction.'/'; ?>" class="btn btn-default btn-xs btn-remove"><span class="glyphicon glyphicon-remove"></span> <?php echo $this->translate('Clear search'); ?></a>
    </div>
</div>
<div class="row">
    <div id="content" class="col-md-8 col-sm-8">
        <?php
        echo $popularStores;
        echo $offers;
        ?>
    </div>
    <aside id="sidebar" class="col-md-4 col-sm-4"> 
        <?php
        echo $signUpWidgetForm; 
        echo FrontEnd_Helper_viewHelper::socialMediaWidget(); 
        ?>
    </aside>
</div>