<?php 
$this->minifyHeadScript()->appendFile("public/js/front_end/socialmedia.js");
$imagePath = isset($this->pageHeaderImage['path']) ? $this->pageHeaderImage['path'] : '';
$imageName = isset($this->pageHeaderImage['name']) ? $this->pageHeaderImage['name'] : '';
$pageImagePath = PUBLIC_PATH_CDN.$imagePath.$imageName;
$pageHeaderPartial = new FrontEnd_Helper_PageHeaderPartialFunctions();
$searchString = $this->translate('Results for'). " " . $this->searchedKeyword;
echo $pageHeaderPartial->getCategoryOrPageHeader($searchString, $pageImagePath);

$partialViewPath = 'partials/';
$offers = '<div class="message">
            <div class="holder">
                <span class="ico-warning"></span>
                <span class="text">
                    <span>'.$this->translate('Sorry, no vouchercodes found with the search input').'!</span>
                </span>
            </div>
        </div>';
if(!empty($this->offers)):
    $offers = '<header class="heading-box">
            <h2>'.$this->translate('Offers matching search results').'</h2>
        </header>';
    $offers .= $this->partial(
        $partialViewPath. '_offer.phtml',
        array(
            'offers' => $this->offers,
            'offersType'=>'searchedOffers',
            'shopName' => '',
            'shop' => '',
            'zendForm'=>''
        )
    );
endif;

$signUpWidgetForm = '';
$signUpWidgetForm = $this->partial(
    $partialViewPath.'_signupForm.phtml',
    array(
       'zendForm' => $this->sidebarWidgetForm,
       'signupFormWidgetType'=> 'sidebarWidget',
       'shopId'=>'',
       'shopLogoOrDefaultImage'=>''
    )
);

$popularStores = '';
if(count($this->popularStores)){
    $popularStores = $this->partial(
        'search/_popular-stores.phtml',
        array(
           'popularStores' => $this->popularStores,
           'offers' => count($this->offers)
        )
    );
}

?>
<div class="row">
    <div id="content" class="col-md-8 col-sm-8">
        <?php echo $popularStores.$offers; ?>
    </div>
    <aside id="sidebar" class="col-md-4 col-sm-4"> 
        <?php 
        $frontendHelper = new FrontEnd_Helper_viewHelper();
        echo $signUpWidgetForm.$frontendHelper->socialMediaWidget();?>
    </aside>
</div>