<!-- start affiliate network list -->
<?php 
  $this->headTitle()->append($this->translate('Refresh vanish'));
?>
<div id="affiliateNetworkList">
   <div class="wrap columns-2">
		
		
		<?php if($this->messageSuccess!='' || $this->messageError!='' ){?>
		<br><div class ="mainpage-content-colorbox success">
		<?php if($this->messageSuccess!=''){?>
		<span class="success"><?php echo $this->messageSuccess; ?></span>
		<?php }?>
		<?php if($this->messageError!=''){?>
		<span class="error"><?php echo $this->messageError; ?></span>
		<?php } ?>
		</div>
		<?php 
		}?> 
		 
       <h1><?php echo $this->translate('Refresh vanish'); ?> 
      </h1>

            
         

    </div>
    </div>
 <!-- end affiliate network -->

 
 
 
 
 
 
