<header class="heading-box text-advice">
    <h2><?php echo $this->moneySavingGuideHeader; ?></h2>
</header>
<section class="section tips-section tips-section-2">
<?php
foreach ($this->authorMostReadArticles as $authorMostReadArticle) {
    $authorMostReadArticle = (object) $authorMostReadArticle;
    $authorMostReadArticle = isset($authorMostReadArticle->articles) ? $authorMostReadArticle->articles : (array) $authorMostReadArticle;
    $articleImage = !empty($authorMostReadArticle['thumbnail']) ? PUBLIC_PATH_CDN.$authorMostReadArticle['thumbnail']['path']. $authorMostReadArticle['thumbnail']['name'] : '';
    ?>
    <article class="block">
        <a href="<?php echo HTTP_PATH_LOCALE.'plus/'.$authorMostReadArticle['permalink']?>">
            <div class="image saving-guide-image-wrapper">
                <img src="<?php echo $articleImage;?>" width="120" alt="<?php echo $authorMostReadArticle['title'];?>">
                <span class="title"><?php echo FrontEnd_Helper_viewHelper::__translate('FLIPIT PLUS');?></span>
            </div>
            <div class="box">
                <h2><?php echo $authorMostReadArticle['title'];?></h2>
                <?php echo $authorMostReadArticle['content'];?>
            </div>
        </a>
    </article>
<?php
}?>
</section>