<header class="heading-box text-ask">
    <h2>
<?php
$headerName  = isset($this->shopName) ? $this->shopName : $this->authorName;
echo $this->shopName!= '' 
    ?  $this->translate('Ask a question about'). ' ' . $headerName 
    :  $this->translate('Ask a question');
?>
    </h2>
    <strong>
<?php
echo $this->shopName!= '' 
    ? $this->translate('Ask us anything about'). ' '. $headerName.' '. $this->translate('and their discounts') 
    : $this->translate('Ask us anything about'). ' '. $this->translate('discounts');
?>
    </strong>
</header>
<section id="disqus_thread" class="section section-comments"></section>
<script type="text/javascript">
    var disqus_shortname = '<?php echo $this->translate('disqus_shortname');?>';
</script>
<?php
echo $this->inlineScript()->appendFile($this->baseUrl("public/js/front_end/disqus.js"));
?>
<noscript><?php echo $this->translate('Please enable JavaScript to view the'); ?>
    <a href="http://disqus.com/?ref_noscript">
<?php
echo $this->translate('comments powered by Disqus.');
?>
    </a>
</noscript>
<a href="http://disqus.com" class="dsq-brlink">
<?php
echo $this->translate('comments powered by');
?>
    <span class="logo-disqus">
<?php
echo $this->translate('Disqus');
?>
    </span>
</a>
