<?php
$authorName = '';
if (isset($this->editorInformation['firstName'])) {
    $authorName = FrontEnd_Helper_AuthorPartialFunctions::
        getAuthorName($this->editorInformation['firstName'], $this->editorInformation['lastName']);
}
$editorImagePath = '';
if (isset($this->editorInformation['profileimage']['name'])) {
    $editorImagePath =
        HTTP_PATH_CDN 
        .ltrim($this->editorInformation['profileimage']['path'], "/")
        .'' .$this->editorInformation['profileimage']['name'];
}
?>
<article class="block">
    <div class="intro intro-2">
        <div class="author-info">
            <div class="img-thumbnail">
                <img title="<?php echo $authorName; ?>" 
                    alt="<?php echo $authorName; ?>" src="<?php echo $editorImagePath; ?>" class="img-responsive">
            </div>
            <div class="textbox">
                <h3><?php echo $authorName; ?></h3>
                <span class="text"><?php echo $this->editorWidgetInformation[0]['subtitle']; ?></span>
            </div>
        </div>
        <?php
        echo  preg_replace('/(<a\b[^><]*)>/i', '$1 style="color: #0077cc;text-decoration: underline;">',
        FrontEnd_Helper_viewHelper::replaceStringVariable($this->editorWidgetInformation[0]['description'])); ?>
    </div>
</article>