<?php 
	$footerLinks = new FrontEnd_Helper_viewHelper();
	$footer = $footerLinks->getFooterLinks();
?>

<div class="home-footer-new">
	<div class="CTA">
		<div class="container" id="user_footer">
			<?php 
			 
			 
			$requestObj = Zend_Controller_Front::getInstance()->getRequest();
				if(strtolower($requestObj->getControllerName())!='freesignup'){
					
					if(strtolower($requestObj->getActionName())!='step3' && strtolower($requestObj->getActionName())!='step1' && strtolower($requestObj->getActionName())!='step2'){
				
						$this->locale = LOCALE != 'en' ? LOCALE  : '';
						$link = $this->locale. '/login/userfooter';
						echo $this->esi($link); 
					
					}
				}
		   ?>
			
		</div>
	</div>

	<div class="footerlinks">
		<div class="container">
			<div class="kcode-links-lt">
				<ul>
					<div class="footerdivider"></div>
						<?php echo $footer[0]['middleColumn1']; ?>
					<div class="footerdivider"></div>
						<?php echo $footer[0]['middleColumn2']; ?>
				    <div class="footerdivider"></div>
						<?php echo $footer[0]['middleColumn3']; ?>
		           	<div class="footerdivider"></div>
		        </ul>
			</div>
		</div>
	</div>

	<div class="socialbalk">
		<div class="container" style="margin-top:40px;">

		<?php echo $footer[0]['topFooter']; ?>
		
		<?php echo $footer[0]['bottomFooter']; ?>
		</div>
	</div>
</div>