<?php 
$footer = FrontEnd_Helper_viewHelper::getFooterData();
?> 
<footer id="footer">
	<div class="bottom-panel">
		<div class="container">
			<div class="text">
				<h2><?php echo $this->translate('Subscribe now'); ?></h2>
				<span><?php echo $this->translate('Become a saving superstar'); ?>! <br><?php echo $this->translate('And get exclusive codes'); ?></span>
			</div>
			<form role="form" class="email-form form-inline">
				<div class="form-group">
					<input type="email" class="form-control" placeholder="Your Email Address">
				</div>
				<button type="submit" class="orange btn btn-default">submit</button>
			</form>
			<div class="social">
				<?php echo $footer[0]['middleColumn1'];?>
			</div>
		</div>
	</div>
	<div class="container bottom-nav">
		<div class="row">
			<?php echo $footer[0]['middleColumn2'];?>
			<?php echo $footer[0]['middleColumn3'];?>
			<?php echo $footer[0]['middleColumn4'];?>
		</div>
	</div>

	<div class="container add-block">
	<?php echo $footer[0]['bottomFooter'];?>
	</div>
</footer>