<?php 
    $footerLinks = new FrontEnd_Helper_viewHelper();
    $footer = $footerLinks->getFooterLinks();
?> 
<footer id="footer">
			<div class="holder">
				<div class="container">
					<div class="row">
						<div class="add-navigation">
							<nav class="box col-md-3 col-sm-4 col-xs-4">
								<h3>Kortingscode</h3>
								<?php echo $footer[0]['middleColumn1']; ?>
							</nav>
							<nav class="box col-md-3 col-sm-4 col-xs-4">
								<h3>Help</h3>
								<?php echo $footer[0]['middleColumn2']; ?>
							</nav>
							<nav class="box col-md-3 col-sm-4 col-xs-4">
								<h3>Over Flipit</h3>
								<?php echo $footer[0]['middleColumn3']; ?>
							</nav>
						</div>
						<div class="box col-md-3 col-sm-12">
							<strong class="logo"><a href="#">FlipIt</a></strong>
							<p>Alle kortingscodes geïdentificeerd als "Exclusief"
							 mogen niet worden gepubliceerd zonder schriftelijke
							 toestemming van <a href="#">Flipit.com</a></p>
							<ul class="add-list">
								<li>Flipit <a href="#">België</a></li>
								<li>Volg ons op <a href="#">Facebook</a> en leer <a href="#">meer over onze missie</a>!</li>
								<li>Terug naar landen selectie</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<div class="container">
				<div class="bar">
					<p>Alle kortingscodes geïdentificeerd als "Exclusief" mogen niet worden gepubliceerd in een medium
					 zonder uitdrukkelijke schriftelijke toestemming van kortingscode.nl. Alle aanbiedingen zijn zorgvuldig
					 uitgekozen	door onze redactie en zijn correct op het moment van publicatie.</p>
					<span>Copyright &copy; 2009-2012 Imbull BV. Kortingscode.nl. Alle logos &copy; behoren aan hun respectievelijke eigenaren. | All Rechten voorbehouden.</span>
					<nav class="add-nav">
						<ul>
							<li><a href="#">Privacy</a></li>
							<li><a href="#">Disclaimer</a></li>
							<li><a href="#">In de media</a></li>
							<li><a href="#">FAQ</a></li>
							<li><a href="#">Contact</a></li>
							<li><a href="#">Top 50</a></li>
							<li><a href="#">Hyves</a></li>
							<li><a href="#">Facebook</a></li>
							<li><a href="#">Twitter</a></li>
							<li><a href="#">RSS feed</a></li>
						</ul>
					</nav>
				</div>
			</div>
		</footer>
