<?php 
$footer = FrontEnd_Helper_viewHelper::getFooterData();
?> 
<footer id="footer">
    <div class="holder">
        <div class="container">
            <div class="row">
                <div class="add-navigation">
                    <nav class="box col-md-3 col-sm-4 col-xs-4">
                        <h3><?php echo $this->translate('Kortingscode');?></h3>
<?php
echo $footer[0]['middleColumn1'];
?>
                    </nav>
                    <nav class="box col-md-3 col-sm-4 col-xs-4">
                        <h3><?php echo $this->translate('Help');?></h3>
<?php
echo $footer[0]['middleColumn2'];
?>
                    </nav>
                    <nav class="box col-md-3 col-sm-4 col-xs-4">
                        <h3><?php echo $this->translate('Over Flipit');?></h3>
<?php 
echo $footer[0]['middleColumn3'];
?>
                    </nav>
                </div>
                    <div class="box col-md-3 col-sm-12">
<?php
echo $footer[0]['middleColumn4'];
?>
                    </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="bar">
<?php
echo $footer[0]['bottomFooter'];
?>
        </div>
    </div>
</footer>
