<?php 
$translateSession = new Zend_Session_Namespace('Transl8');
if (!empty($translateSession->onlineTranslationActivated)): ?>
    <div class="inline-translation-bar">
        Inline translation active! <a href="<?php echo HTTP_PATH; ?>trans/stopinlinetranslation">Stop inline translation and return to Admin</a>
    </div>
<?php 
endif;
 
if(LOCALE == ''):
    $logoCssClass = 'logo kortingscode';
    $siteName = 'kortingscode';
else :
    $logoCssClass = 'logo flipit';
    $siteName = 'FlipIt';
endif
?>
<header id="header">
    <div class="top-panel">
        <div class="container">
            <span class="slogan"><?php echo $this->translate('save money with online discount codes and save pointers');?></span>
            <a class="menu-account" href="javascript:void(0);"><?php echo $this->translate('account menu');?></a>
                <?php
                $this->locale = LOCALE != 'en' ? LOCALE : '';
                $userMenuLink = $this->locale. '/login/usermenu';
                echo $this->esi($userMenuLink);
                ?>
        </div>
    </div>
    <div class="navigation">
        <div class="container">
            <strong class="<?php echo $logoCssClass; ?>">
                <a href="<?php echo LOCALE == '' ? 
                    'http://www.kortingscode.nl' : 'http://www.flipit.com/'.LOCALE ;?>">
                    <?php echo $siteName;?>
                </a>
            </strong>
            <a href="#" class="menu-opener"><span class="glyphicon glyphicon-search"></span></a>
            <div class="nav-bar">
            <?php 
            $currentControllerName = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
            if($currentControllerName != 'index') { ?>
                <div class="search-box">
                    <a href="#" class="opener"><span class="glyphicon glyphicon-search"></span></a>
                <?php
                $localePartialPath = APPLICATION_PATH . '/modules/'. LOCALE .'/views/scripts/partials/';
                $basePartialViewPath = new Zend_View();
                $basePartialViewPath->setScriptPath(APPLICATION_PATH . '/views/scripts/partials/');
                $localePartialViewPath = new Zend_View();
                $localePartialViewPath->setScriptPath($localePartialPath);
                $loadFile = '_headerSearch.phtml';
                if (file_exists($localePartialPath . $loadFile)) :
                    echo $localePartialViewPath->render($loadFile);
                else:
                    echo $basePartialViewPath->render($loadFile);
                endif;
                ?>
                </div>
                <?php 
            }
            echo FrontEnd_Helper_viewHelper::generateMainMenu($this->controllerName, $this->action);
            ?>
            </div>
        </div>
    </div>
</header>