<?php 
if (empty($_SERVER['HTTP_X_VARNISH']) || isset($_COOKIE['passCache'])) {
    ?>
    <script type="text/javascript" src='/public/js/jquery-1.7.2.min.js'></script>
    <?php
}

$translateSession = new Zend_Session_Namespace('Transl8');
if (!empty($translateSession->onlineTranslationActivated)): ?>
    <div class="inline-translation-bar">
        Inline translation active!
        <a href="<?php echo HTTP_PATH_LOCALE; ?>trans/stopinlinetranslation">Stop inline translation and return to Admin</a>
    </div>
<?php 
endif;

$httpScheme = FrontEnd_Helper_viewHelper::getServerNameScheme();

if(LOCALE == ''):
    $logoCssClass = 'logo kortingscode';
    $logoPath = HTTP_PATH.'public/images/kortingscode-logo.png';
    $websiteName = 'http://'.$httpScheme.'.kortingscode.nl';
else :
    $logoCssClass = 'logo flipit';
    $logoPath = HTTP_PATH.'public/images/flipit-logo-'.LOCALE.'.png';
    $websiteName = 'http://'.$httpScheme.'.flipit.com/'.LOCALE;
endif;
?>
<header id="header">
    <div class="top-panel">
        <div class="container">
            <span class="slogan"><?php 
            echo FrontEnd_Helper_viewHelper::replaceStringVariable(
                FrontEnd_Helper_viewHelper::__translate('save money with online discount codes and save pointers')
            );?>
            </span>
            <?php
                $this->locale = LOCALE != 'en' ? LOCALE : '';
                $userMenuLink = $this->locale. '/login/usermenu';
                echo $this->esi($userMenuLink);
            ?>
        </div>
    </div>
    <div class="navigation">
        <div class="container">
            <div class="holder1">
                <strong>
                    <a href="<?php echo $websiteName;?>">
                        <img 
                        alt="<?php echo FrontEnd_Helper_viewHelper::__form('form_website logo alt');?>"
                        class="<?php echo $logoCssClass;?>" src="<?php echo $logoPath;?>"
                        title="<?php echo FrontEnd_Helper_viewHelper::__form('form_website logo title');?>"/>
                    </a>
                </strong>
                <a href="<?php echo $websiteName;?>" class="menu-opener"><span class="glyphicon glyphicon-search"></span></a>
                <a class="search-opener" href="<?php echo $websiteName;?>"><span class="glyphicon glyphicon-search"></span></a>
                <div class="nav-bar">
                <?php 
                $sessionNamespace = new Zend_Session_Namespace('ErrorPage');
                $currentControllerName = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
                if($currentControllerName != 'index' && $sessionNamespace->ErrorPage == false)
                {
                    ?>
                    <div class="search-box">
                        <a href="<?php echo $websiteName;?>" class="opener"><span class="glyphicon glyphicon-search"></span></a>
                    <?php
                    $localePartialPath = APPLICATION_PATH . '/modules/'. LOCALE .'/views/scripts/partials/';
                    $basePartialViewPath = new Zend_View();
                    $basePartialViewPath->setScriptPath(APPLICATION_PATH . '/views/scripts/partials/');
                    $localePartialViewPath = new Zend_View();
                    $localePartialViewPath->setScriptPath($localePartialPath);
                    $loadFile = '_headerSearch.phtml';
                    if (file_exists($localePartialPath . $loadFile)) :
                        echo $localePartialViewPath->render($loadFile);
                    else:
                        echo $basePartialViewPath->render($loadFile);
                    endif;
                    ?>
                    </div>
                    <?php 
                }
                $sessionNamespace->ErrorPage = '';
                echo FrontEnd_Helper_layoutContent::generateMainMenu();
                ?>
                </div>
            </div>
        </div>
    </div>
</header>
