<?php
$this->minifyHeadScript()->appendFile("/public/js/front_end/search.js");
$searchBoxCssClass = LOCALE == '' ? 'kortingscode' : '';
$searchSlideClass = LOCALE != '' ? 'flipit-slide' : '';
?>
<div class="slide <?php echo $searchSlideClass;?>">
    <form role="form" id="search-form" class="search-form email-form">
        <input 
            placeholder="<?php echo FrontEnd_Helper_viewHelper::__form('form_Type in a Store e.g. Avis');?>" 
            class="form-control <?php echo $searchBoxCssClass;?>" id='searchFieldHeader' 
            name='searchFieldHeader' type='text'/>
        <input id='searchedKeyword' name='searchedKeyword' type='hidden'/>
        <a href='javascript:void(0);'  id='searchbuttonHeader'>
           <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
        </a>
    </form>
</div>

