<?php
if ($this->zendForm!='' && $this->zendForm!=null) {
    $signUpForm = $this->partial(
        'partials/_signupwidget.phtml',
        array(
            'signupFormWidgetType'=>$this->signupFormWidgetType,
            'zendForm'=>$this->zendForm,
            'codesWidget' => $this->codesWidget,
            'formAction' => $this->formAction
        )
    );
    
    $visitorId = 0;
    if (Auth_VisitorAdapter::hasIdentity()):
        $visitorId = Auth_VisitorAdapter::getIdentity()->id;
    endif;
    $shopId = $this->shopId=='' ? 0 : $this->shopId;

    if (\KC\Repository\Visitor::getFavoriteShopsForUser($visitorId, $shopId)==false):
        if ($this->signupFormWidgetType== 'widgetWithinOffers') {?>
            <div class="block block-form <?php echo $shopId==0 ? 'block-form-2' : ''.' block-form-background';?>">
                <div class="holder" style="padding: 0;">
                <?php echo $signUpForm;?>
                </div>
            </div>
            <?php 
        } else {
            echo $signUpForm;
        }
    endif;
}
