<?php   
$mostReadArticles = $this->mostReadArticles;
?>
<div class="slideshow-area">
    <div class="container">
        <div class="slideshow carousel slide" id="carousel-example-generic" data-ride="carousel">
            <div class="mask carousel-inner">
                <?php 
                $carouselCounter = 0;
                $carouselIndicators = '';
                foreach ($mostReadArticles as $mostReadArticle) {
                    if (
                        !empty($mostReadArticle['featuredimagename'])
                        && $mostReadArticle['featuredImageStatus'] == 1
                    ) {
                        $mostReadArticleImage = 
                            !empty($mostReadArticle['featuredimagename'])
                            ? PUBLIC_PATH_CDN
                            .$mostReadArticle['featuredimagepath'] 
                            .$mostReadArticle['featuredimagename']
                            : '';
                    } else {
                        $mostReadArticleImage = 
                            !empty($mostReadArticle['thumbnailname'])
                            ? PUBLIC_PATH_CDN
                            .$mostReadArticle['thumbnailpath'] 
                            .$mostReadArticle['thumbnailname']
                            : '';
                    }

                    $mostReadArticleTitle = mb_strlen($mostReadArticle['title']) > 50 ? 
                                            mb_substr($mostReadArticle['title'], 0,50)
                                            .'..' : $mostReadArticle['title'];
                    $articleUpdatedAtDate = $mostReadArticle['created_at'];
                    $articleUpdatedAtDate = new Zend_Date($articleUpdatedAtDate->date);
                    $articleUpdatedAtDate = $articleUpdatedAtDate->get(Zend_Date::DATE_LONG);
                    $activeClass = '';
                    if($carouselCounter == 0) {
                        $activeClass = 'active';
                    }
                    $carouselIndicators .= '<li data-target="#carousel-example-generic"
                        data-slide-to="'.$carouselCounter.'"
                        class="'.$activeClass.'">'.$carouselCounter.'</li>';
                    ?>
                    <div class="slide item <?php echo $activeClass;?>">
                        <img class="visual" src="<?php echo $mostReadArticleImage;?>" width="450px"
                            alt="<?php echo $mostReadArticleTitle;?>" title="<?php echo $mostReadArticleTitle;?>">
                        <span class="category dark-pink"><?php echo $this->translate('Featured');?></span>
                        <div class="text-holder">
                            <div class="text-frame">
                                <h2>
                                    <a href="<?php echo HTTP_PATH_LOCALE.FrontEnd_Helper_viewHelper::getPagePermalink()
                                    .'/'.$mostReadArticle['permalink'];?>">
                                        <?php echo $mostReadArticleTitle;?>
                                    </a>
                                </h2>
                                <em class="date"><?php echo $articleUpdatedAtDate;?></em>
                            </div>
                        </div>
                    </div>
                    <?php
                    $carouselCounter++;
                }
                ?>
            </div>
            <a class="left carousel-control btn-prev" href="#carousel-example-generic" role="button" data-slide="prev">
                <?php echo $this->translate('Prev');?>
            </a>
            <a class="btn-next right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <?php echo $this->translate('Next');?>
            </a>
            <ul class="switcher-2 carousel-indicators">
                <?php echo $carouselIndicators; ?>
            </ul>
        </div>
    </div>
</div>