<?php   
$mostReadArticles = $this->articles;
?>
<div class="slideshow-area">
    <div class="container">
        <div id="myCarousel" class="carousel slide slideshow" data-ride="carousel">
            <div class="mask">
                <div class="slideset carousel-inner">
                <?php $carouselCounter = 0;
                $carouselIndicators = '';
                foreach ($mostReadArticles as $mostReadArticle) {
                    $mostReadArticleImage = PUBLIC_PATH_CDN
                                            .$mostReadArticle['articles']['thumbnail']['path'] 
                                            .$mostReadArticle['articles']['thumbnail']['name'];
                    $mostReadArticleTitle = mb_strlen($mostReadArticle['articles']['title']) > 40 ? 
                                            mb_substr($mostReadArticle['articles']['title'], 0,40)
                                            .'..' : $mostReadArticle['articles']['title'];
                    $articleUpdatedAtDate = new Zend_Date($mostReadArticle['articles']['created_at']);
                    $articleUpdatedAtDate = $articleUpdatedAtDate->get(Zend_Date::DATE_LONG); 
                    $activeClass = '';
                    if($carouselCounter == 0) {
                        $activeClass = 'active';
                    }
                    $carouselIndicators .= '<li data-target="#myCarousel" data-slide-to="'.$carouselCounter.'"
                      class="'.$activeClass.'"></li>';
                ?>
                    <div class="slide item <?php if($carouselCounter == 0) { echo 'active'; } ?>">
                        <div class="holder">
                            <a href="<?php echo HTTP_PATH_LOCALE.'plus/'.$mostReadArticle['articles']['permalink'];?>">
                            <img class="visual" src="/public/images/front_end/slide01.jpg" width="563" height="391"
                                alt="<?php echo $mostReadArticleTitle;?>">
                                </a>
                            <span class="category dark-pink"><?php echo $this->translate('Featured');?></span>
                            <div class="text-holder carousel-caption">
                                <div class="text-frame">
                                    <h2>
                                        <a 
                                        href="<?php echo HTTP_PATH_LOCALE.'plus/'
                                        .$mostReadArticle['articles']['permalink'];?>">
                                            <?php echo $mostReadArticleTitle;?>
                                        </a>
                                    </h2>
                                    <em class="date"><?php echo $articleUpdatedAtDate;?></em>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php
                $carouselCounter++;
            }
            ?>
                </div>
            </div>
            <a href="#myCarousel" class="btn-prev left carousel-control" role="button" data-slide="prev">Previous</a>
            <a href="#myCarousel" class="btn-next right carousel-control" role="button" data-slide="next">Next</a>
            <ul class="switcher-2 carousel-indicators">
               <?php echo $carouselIndicators; ?>
            </ul>
        </div>
    </div>
</div>         
  
  