<?php $this->partial('offer/_jsFileForOfferPartial.phtml'); ?>
<script type="text/javascript">
    var domainName = "<?php echo HTTP_PATH; ?>";
</script>
<?php
$class = "section";
if (zend_Controller_Front::getInstance()->getRequest()->getControllerName()=='Favourite' 
    && zend_Controller_Front::getInstance()->getRequest()->getActionName()=='sharesocialcode') {
    $class = "";
}
?>
<section class="<?php echo $class; ?>">
<?php
$offerCounter = '';
$visitorInformation = '';

foreach ($this->offers as $offer) {
    $offerCounter++;
    $offer = (object) $offer;
    $offerBounceRate = "/out/offer/".$offer->id;
    $offerPartial = new FrontEnd_Helper_OffersPartialFunctions();
    $daysTillOfferExpires = $offerPartial->getDaysTillOfferExpires($offer->endDate);
    $urlToShow = $offerPartial->getUrlToShow($offer);
    $offerTitle = FrontEnd_Helper_viewHelper::replaceStringVariableForOfferTitle($offer->title);
    $termsAndConditions = $offerPartial->getOfferTermsAndCondition($offer);
    $userLoggedInOrNot = $offerPartial->getUserIsLoggedInOrNot();
    $couponCode = $offer->couponCode;
    if (isset($offer->couponCodeType) && $offer->couponCodeType == 'UN') {
         $couponCode = '';
    }

    $defaultText = '';
    $offerClass = "active";
    $offerHolderClass = "offer-holder";
    if ($offer->exclusiveCode == '1') {
        $offerClass = "orange-block";
    }
    if ($offer->userGenerated == '1') {
        $offerClass = "";
        $offerHolderClass = "";
        $urlToShow = 'javascript:void(0);';
        if ($offer->approved == '1') {
            $offerClass = "social-block"; 
            $offerHolderClass = "offer-holder";
            $urlToShow = $offerPartial->getUrlToShow($offer);
        }
        $defaultText = FrontEnd_Helper_viewHelper::__translate('This code is not verified');
    }

    $esiLocale = LOCALE != 'en' ? LOCALE . '/' : '';
    ?>
    <article class="block <?php echo $offerClass; ?>">
        <div class="holder <?php echo $offerHolderClass; ?>" id="<?php echo $offer->id; ?>">
    <?php 
    echo $offerPartial->getCommonRedirectUrlForOffer(
        $offer,
        $urlToShow,
        $offerBounceRate,
        $this->offersType,
        'offerImage'
    );
    ?>
            <div class="box">
                <div class="text">
                    <p> <?php
                        $membersOnly = isset($offer->Visability) && $offer->Visability == 'MEM'
                            ? '<span class="members-only-image"></span><span class="members-only">'.$this->translate("Members Only").'</span>'
                            : '';
                        echo $membersOnly.$offerPartial->getOfferOptionAndOfferDates($offer, $daysTillOfferExpires);
                        ?>
                    </p>
                    <?php 
                    if ($offer->Visability == 'MEM') {
                        echo $this->esi($esiLocale.'signup/signupmembersonlytitle?shopId='.$offer->shop['id']
                            .'&signupFormWidgetType=widgetWithinOffers&offerId='.$offer->id.'&shopLogoOrDefaultImage=');
                    } else {
                        echo $offerPartial->getCommonRedirectUrlForOffer(
                            $offer,
                            $urlToShow,
                            $offerBounceRate,
                            $offerTitle,
                            'offerTitle'
                        ); 
                    }
                    ?>
                </div>
                <div class="buttons" id="offerButton<?php echo $offer->id ;?>">
    <?php
    $permalink = $this->offersType=='categoryOffers' ? $this->categoryPermaLink : $offer->shop['permalink'];

    if ($offer->Visability == 'MEM') {
        echo $this->esi($esiLocale.'signup/signupwidgetcodes?shopId='.$offer->shop['id']
            .'&signupFormWidgetType=widgetWithinOffers&offerId='.$offer->id.'&shopLogoOrDefaultImage=');
    } else {
        echo $offerPartial->getCommonRedirectUrlForOffer(
            $offer,
            $urlToShow,
            $offerBounceRate,
            $permalink,
            'mainOfferClickoutButton'
        );
        echo $offerPartial->getSecondButtonforOffer($offer, $urlToShow, $offerBounceRate, $permalink); 
    }
    ?>
                </div>
                <div class="the-code" id="offerCodeDiv<?php echo $offer->id ;?>">
                    <span class="instruction">
                        <strong><?php echo $this->translate('enter this code at checkout')?></strong>
                    </span>
                    <strong class="code-value"><?php echo $couponCode;?></strong>
                </div>
                <ul class="view-list">
    <?php 
    if (isset($offer->extendedOffer) && $offer->extendedOffer =='1') {
        $extendedOffer = 1;
    } else {
        $extendedOffer = 0;
    }
    $offerBottomOfferExclusiveOrEditor = $offerPartial->getOfferExclusiveOrEditor($offer);
    $offerBottomRecomendedLink = '';
    if (intval($offer->editorPicks)) == 1) {
        $contentManagerId = isset($offer->shop['contentManagerId']) ? $offer->shop['contentManagerId'] : '';
        $contentManagerId = !empty($this->shop['contentManagerId']) 
            ? $this->shop['contentManagerId'] 
            : $contentManagerId;
        $shopEditor = $offerPartial->getShopEditor($contentManagerId);
        $offerBottomRecomendedLink = $offerPartial->getShopEditorHtml($shopEditor);
        $offerBottomOfferExclusiveOrEditor = $offerBottomRecomendedLink;
    } 
    $offerBottomDaysTillExpireText = '';
    if ($daysTillOfferExpires <=3) {
        $offerBottomDaysTillExpireText = $offerPartial->getDaysTillExpire($daysTillOfferExpires);
    }
    $offerBottomTermsAndConditionLink = '';
    $offerBottomExtendedLink = '';
    $offerBottomViewAllShopsLink = '';
    $showHyphen =  '';
    if ($this->offersType!='extendedOffer') {
        if ($termsAndConditions != '') {
            $offerBottomTermsAndConditionLink = $offerPartial->getTermAndConditionsLink($offer, $termsAndConditions);
        }
        $offerBottomExtendedLink =  $offerPartial->getExtendedOfferLink($offer);
        if($this->offersType!='simple'):
            $offerBottomViewAllShopsLink =  $offerPartial->getViewAllCodeLink(
                $offer->shop['name'],
                $offer->shop['permalink'],
                $showHyphen
            );
        endif;
    } else {
        $offerBottomViewAllShopsLink = $offerPartial->getViewAllCodeLink($offer->shop['name'], $offer->shop['permalink'], '');
    }
    ?>
                </ul>
            </div>
        </div>
    <?php
    if ($this->offersType!='extendedOffer') {
            $style = '';
    } else {
            $style = 'style="display:block;"';
    }
    ?>
    
        <hr class="alt2">
        <div class="recommended-outerDiv">
            <div class="recommended-arrow"></div>
            <div class="recommendedOffer">
            <?php 
            echo
                $offerBottomOfferExclusiveOrEditor
                .$offerBottomDaysTillExpireText
                .$offerBottomViewAllShopsLink
                .$offerBottomExtendedLink
                .$offerBottomTermsAndConditionLink;
            if ($offer->discountType == "CD") {
                $offerBottomNumberOfUsedCode = $this->esi($this->locale.'offer/offer-view-count?offerId='.$offer->id);
            }
            ?>
            </div>
        </div>

        <div class="offer-box" id="websiteOfferLink<?php echo $offer->id ;?>" <?php echo $style;?>>
            <hr class="alt2">
            <div class="offer">
                <span><?php echo $this->translate('Grab this offer now:');?></span>
                <a target = "_blank" href="<?php echo $urlToShow;?>" rel= "nofollow">
                <?php echo $this->translate('Open ');?>
                <?php echo $offer->shop['name']; ?>
                <?php echo $this->translate(' website');?>
                </a>
            </div>
        </div>
        <?php
        if ($offer->userGenerated == 1) { ?>
            <input type="hidden" id="userGenerated" alt="<?php echo $offer->id ;?>" value="1" />
        <?php } ?>
        <div  class="terms-block" id='termAndConditions<?php echo $offer->id ;?>'>
            <h2><?php echo $this->translate('Terms &amp; Conditions');
            if (!empty($defaultText)) { echo ' : <span class="social-term-font">' .$defaultText.'</span>'; }?></h2>
            <ol class="num-list">
            <?php echo $termsAndConditions;?>
            </ol>
        </div>
    </article>
    <?php
    if($offerCounter == 1) :
        if($this->offersType=='simple' || $this->offersType=='top20' || $this->offersType=='offerPage'
            || $this->offersType=='offerWithPagenation' || $this->offersType=='newestOffer'):
            $this->locale = LOCALE != 'en' ? LOCALE . '/' : '';
            echo $this->esi($this->locale.'signup/signupwidgetlarge?shopId='.$this->currentStoreInformation[0]['id']
                .'&signupFormWidgetType=widgetWithinOffers&shopLogoOrDefaultImage=');
        endif;
    endif;
    if ($this->offersType=='simple') {
        if ($offer->shop['showcustomtext'] == 1
            && $offerCounter == $offer->shop['customtextposition']) { ?>
            <article class="block">
                <div class="holder" style="">
                    <?php echo $offer->shop['customtext'];?>
                </div>
            </article>
    <?php 
        }
    }
}
if ($this->offersType!='extendedOffer') {
    if ($this->offersType == 'newestOffer'
        || $this->offersType=='offerWithPagenation'
        || $this->offersType=='offerPage') {
        echo $this->paginationControl($this->offers, 'Sliding', '/partials/_pagination.phtml');
    }
    if (isset($this->pageType) && $this->pageType == 'howToGuide') {
        $domainName = LOCALE == '' ? HTTP_PATH : HTTP_PATH_LOCALE;
        echo '<a class="link-box" href="'.$domainName.$offer->shop['permalink'].'">
                <hr class="alt2">
                '.$this->translate('View all voucher codes from').' '.$offer->shop['name'].'
            </a>';
    }
    ?>
    </section>
    <?php 
}