<?php $this->partial('offer/_jsFileForOfferPartial.phtml'); ?>
<script type="text/javascript">
    var domainName = "<?php echo HTTP_PATH; ?>";
</script>
<section class="section">
<?php
$offerCounter = '';
$visitorInformation = '';
if (!empty(Auth_VisitorAdapter::getIdentity()->id)) {
    $visitorInformation = Visitor::getUserDetails(Auth_VisitorAdapter::getIdentity()->id);
}

foreach ($this->offers as $offer) {
    $offerCounter++;
    $offer = (object) $offer;
    $offerBounceRate = "/out/offer/".$offer->id;
    $offerPartial = new FrontEnd_Helper_OffersPartialFunctions();
    $daysTillOfferExpires = $offerPartial->getDaysTillOfferExpires($offer->endDate);
    $urlToShow = $offerPartial->getUrlToShow($offer);
    $offerTitle = FrontEnd_Helper_viewHelper::replaceStringVariable($offer->title);
    $termsAndConditions = $offerPartial->getOfferTermsAndCondition($offer);
    $userLoggedInOrNot = $offerPartial->getUserIsLoggedInOrNot();
    $couponCode = $offer->couponCode;
    if (isset($offer->couponCodeType) && $offer->couponCodeType == 'UN') {
         $couponCode = '';
    }
    ?>
    <article class="block <?php echo $offer->exclusiveCode == '1' ? "orange-block" : "active"; ?>">
        <div class="holder offer-holder" id="<?php echo $offer->id; ?>">
    <?php 
    echo $offerPartial->getCommonRedirectUrlForOffer(
        $offer,
        $urlToShow,
        $offerBounceRate,
        $this->offersType,
        'offerImage'
    );
    ?>
            <div class="box">
                <div class="text">
                    <p> <?php
                        $membersOnly = isset($offer->Visability) && $offer->Visability == 'MEM'
                            ? '<span class="members-only-image"></span><span class="members-only">'.$this->translate("Member").'</span>'
                            : '';
                        echo $membersOnly.$offerPartial->getOfferOptionAndOfferDates($offer, $daysTillOfferExpires);
                        ?>
                    </p>
                    <?php 
                    echo $offerPartial->getCommonRedirectUrlForOffer(
                        $offer,
                        $urlToShow,
                        $offerBounceRate,
                        $offerTitle,
                        'offerTitle'
                    );
                    ?>
                </div>
                <div class="buttons" id="offerButton<?php echo $offer->id ;?>">
    <?php
    $permalink = $this->offersType=='categoryOffers' ? $this->categoryPermaLink : $offer->shop['permalink'];
    if (!empty($visitorInformation)) {
        echo $offerPartial->getCommonRedirectUrlForOffer(
            $offer,
            $urlToShow,
            $offerBounceRate,
            $permalink,
            'mainOfferClickoutButton'
        );
        echo $offerPartial->getSecondButtonforOffer($offer, $urlToShow, $offerBounceRate, $permalink);
    } else {
        if ($offer->Visability == 'MEM') {
            echo $this->esi($this->locale.'signup/signupwidgetcodes?shopId='.$offer->shop['id']
                .'&signupFormWidgetType=widgetWithinOffers&shopLogoOrDefaultImage=');
        } else {
            echo $offerPartial->getCommonRedirectUrlForOffer(
                $offer,
                $urlToShow,
                $offerBounceRate,
                $permalink,
                'mainOfferClickoutButton'
            );
            echo $offerPartial->getSecondButtonforOffer($offer, $urlToShow, $offerBounceRate, $permalink); 
        }
    }
    ?>
                </div>
                <?php if (!empty($visitorInformation)) { ?>
                    <div class="the-code" id="offerCodeDiv<?php echo $offer->id ;?>">
                        <span class="instruction">
                            <strong><?php echo $this->translate('enter this code at checkout')?></strong>
                        </span>
                        <strong class="code-value"><?php echo $couponCode;?></strong>
                    </div>
                <?php } else {
                    if ($offer->Visability != 'MEM') {?>     
                        <div class="the-code" id="offerCodeDiv<?php echo $offer->id ;?>">
                            <span class="instruction">
                                <strong><?php echo $this->translate('enter this code at checkout')?></strong>
                            </span>
                            <strong class="code-value"><?php echo $couponCode;?></strong>
                        </div>
                    <?php
                    }
                }
                ?>
                <ul class="view-list">
    <?php 
    if (isset($offer->extendedOffer) && $offer->extendedOffer =='1') {
        $extendedOffer = 1;
    } else {
        $extendedOffer = 0;
    }
    $showHyphen = $termsAndConditions != '' || $extendedOffer == 1 ? '<li> -</li>' : '';
    if ($this->offersType!='extendedOffer') {
        if ($termsAndConditions != '') {
            echo $offerPartial->getTermAndConditionsLink($offer, $termsAndConditions);
        }
        
        echo $offerPartial->getExtendedOfferLink($offer);
        if($this->offersType!='simple'):
            echo $offerPartial->getViewAllCodeLink($offer->shop['name'], $offer->shop['permalink'], $showHyphen);
        endif;
    } else {
        echo $offerPartial->getViewAllCodeLink($offer->shop['name'], $offer->shop['permalink'], '');
    }
    ?>
                </ul>
            </div>
        </div>
    <?php
    if ($this->offersType!='extendedOffer') {
            $style = '';
    } else {
            $style = 'style="display:block;"';
    }
    ?>
        <div class="offer-box" id="websiteOfferLink<?php echo $offer->id ;?>" <?php echo $style;?>>
            <hr class="alt2">
            <div class="offer">
                <span><?php echo $this->translate('Grab this offer now:');?></span>
                <a target = "_blank" href="<?php echo $urlToShow;?>" rel= "nofollow">
                <?php echo $this->translate('Open ');?>
                <?php echo $offer->shop['name']; ?>
                <?php echo $this->translate(' website');?>
                </a>
            </div>
        </div>
        <?php if ($termsAndConditions != '') : ?>
        <div  class="terms-block" id='termAndConditions<?php echo $offer->id ;?>'>
            <h2><?php echo $this->translate('Terms &amp; Conditions');?></h2>
            <ol class="num-list">
            <?php echo $termsAndConditions;?>
            </ol>
        </div>
        <?php endif; ?>
    </article>
    <?php
    if($offerCounter == 1) :
        if($this->offersType=='simple' || $this->offersType=='top20' || $this->offersType=='offerPage'
            || $this->offersType=='offerWithPagenation' || $this->offersType=='newestOffer'):
            $this->locale = LOCALE != 'en' ? LOCALE . '/' : '';
            echo $this->esi($this->locale.'signup/signupwidgetlarge?shopId='.$this->currentStoreInformation[0]['id']
                .'&signupFormWidgetType=widgetWithinOffers&shopLogoOrDefaultImage=');
        endif;
    endif;
}
if ($this->offersType!='extendedOffer') {
    if ($this->offersType == 'newestOffer'
        || $this->offersType=='offerWithPagenation'
        || $this->offersType=='offerPage') {
        echo $this->paginationControl($this->offers, 'Sliding', '/partials/_pagination.phtml');
    }
    if (isset($this->pageType) && $this->pageType == 'howToGuide') {
        $domainName = LOCALE == '' ? HTTP_PATH : HTTP_PATH_LOCALE;
        echo '<a class="link-box" href="'.$domainName.$offer->shop['permalink'].'">
                <hr class="alt2">
                '.$this->translate('View all voucher codes from').' '.$offer->shop['name'].'
            </a>';
    }
    ?>
    </section>
    <?php 
}