<?php 
//header('location:'. HTTP_PATH); die; exit;
$permalink = ltrim($_SERVER['REQUEST_URI'], '/');
$myfav = explode('myfavorite', $permalink);

if($myfav[0] == '') {
      $permalink = FrontEnd_Helper_viewHelper::__link(rtrim('mijn-favorieten'));
}

$permalink = rtrim($permalink, '/');
preg_match("/[^\/]+$/", $permalink, $matches);

if(intval(@$matches[0]) > 0 && intval(@$matches[0]) < 4) {

	if(intval($matches[0]) > intval($this->pageCount)) {
		$permalink = explode('/'.$matches[0],$permalink);
        $permalink = $permalink[0];
		header('location:'. HTTP_PATH.$permalink);  
	}
    $permalink = explode('/'.$matches[0],$permalink);
    $permalink = $permalink[0];
     
      
} else if(intval(@$matches[0]) > 3) {
	
	header('location:'. HTTP_PATH.$permalink); 
	
} else {
	
	$permalink = $permalink;
	
}

$splitVal = explode('?', $permalink);
$this->headLink( array( 'rel' => 'canonical','href' => HTTP_PATH . strtolower($splitVal[0])));


if($this->pageCount > 1)
{

      if($this->current - 1 != 0) {
            
            if($this->current==2) {
                  
                  $this->headLink( array( 'rel' => 'prev','href' => HTTP_PATH . $permalink));
                  
            }else{
                  
                  $this->headLink( array( 'rel' => 'prev','href' => HTTP_PATH . $permalink .'/'. ($this->current - 1) ));
            }
            
      }
      if($this->current <= 2) {
            
            if($this->current=='1') {
                  
                  $splitVal = explode('?', $permalink);
                  $permalink = $splitVal[0];
            }
            if($this->current+1 <= $this->pageCount):
           		
            	$this->headLink( array( 'rel' => 'next','href' => HTTP_PATH . $permalink .'/'. ($this->current + 1)));
            
            endif;
            
      }
     // print_r($this->pagesInRange);
      foreach ($this->pagesInRange as $pages) {?>
	      <?php 
	      if($pages < 4 ) {
	      	
	          $page = "";
	          
	          if($pages > 1) {
	          	
	                $page = "/".$pages;
	          }
	          
	        //  echo "CURRENT=== ". $this->current;
	          
	         ?>
	        
	        <a href="<?php echo HTTP_PATH . $permalink . $page; ?>">
	        <div class="paging-col1 <?php echo ($pages == $this->current) ? "paging-col1-selected" : "" ?>">
	        <?php echo $pages;?></div> </a>
	    
	     	<?php 
	      } 
	     
	      else if(isset($this->next) && $pages < 4) { ?>      
	          
	          <?php  echo 'else if';?>                
	          <a href="<?php echo HTTP_PATH . $permalink . $page ?>"><div class="paging-rightarrow"> &nbsp; </div> </a>
	            
	          <?php 
	     }
      }
      ?> 
<?php 
}
?>
