<?php 
$permalink = ltrim($_SERVER['REQUEST_URI'], '/');
$myfavorite = explode('myfavorite', $permalink);

if ($myfavorite[0] == '') :
    $permalink = FrontEnd_Helper_viewHelper::__link(rtrim('mijn-favorieten'));
endif;

$permalink = rtrim($permalink, '/');
preg_match("/[^\/]+$/", $permalink, $permalinkMatches);
if (intval($permalinkMatches[0]) > 0 && intval($permalinkMatches[0]) < 4) :
    $permalink = explode('/'.$permalinkMatches[0], $permalink);
    $permalink = $permalink[0];
elseif (intval($permalinkMatches[0]) > 3) :
    $redirector = $this->getHelper('Redirector');
    $redirector->gotoUrl('error');
else:
    $permalink = $permalink;
endif;

$permalinkAfterQueryString = explode('?', $permalink);
$this->headLink(array('rel' => 'canonical', 'href' => HTTP_PATH . strtolower($permalinkAfterQueryString[0])));

if ($this->pageCount > 1) :
    if ($this->current - 1 != 0) :
        if ($this->current==2) :
            $this->headLink(array('rel' => 'prev', 'href' => HTTP_PATH . $permalink));
        else:
            $this->headLink(array('rel' => 'prev', 'href' => HTTP_PATH . $permalink .'/'. ($this->current - 1)));
        endif;
    endif;

    if ($this->current <= 2) :
        if ($this->current == 1) :
            $permalinkAfterQueryString = explode('?', $permalink);
            $permalink = $permalinkAfterQueryString[0];
        endif;
        if ($this->current+1 <= $this->pageCount):
            $this->headLink(array('rel' => 'next', 'href' => HTTP_PATH . $permalink .'/'. ($this->current + 1)));
        endif;
    endif;

    echo '<ul class="pagination">';
    foreach ($this->pagesInRange as $pageNumber) :
        if ($pageNumber < 4 ) :
            $pageNumberAfterSlash = '';
            if ($pageNumber > 1) :
                $pageNumberAfterSlash = "/".$pageNumber;
            endif;
            ?>
            <li class="<?php echo ($pageNumber == $this->current) ? "active" : "" ?>">
                <a href="<?php echo HTTP_PATH . $permalink . $pageNumberAfterSlash; ?>">
                <?php echo $pageNumber;?> 
                <?php if ($pageNumber == $this->current) : ?>
                <span class="sr-only">(current)</span>
                <?php endif; ?>
                </a>
            </li>
            <?php
        elseif (isset($this->next) && $pageNumber < 4) : ?>
            <li class="next"> <a href="<?php echo HTTP_PATH . $permalink . $pageNumberAfterSlash ?>">&gt;</a></li>
            <?php
        endif;
    endforeach;
    echo "</ul>";
endif;