<header class='heading-box text-shop'>
    <h2>
        <?php echo $this->headerText;?>
    </h2>
</header>
<section class="section">
    <div class='block'>
        <div class='holder'>
        <ul class="shops">
            <?php
        foreach ($this->popularStores as $popularStore)
        { 
            $popularStore = isset($popularStore['popularshops'])
                ?  $popularStore['popularshops'] 
                :  $popularStore;
            $popularStoreImage =
                isset($popularStore['logo']) ? 
                PUBLIC_PATH_CDN.ltrim($popularStore['logo']['path'], '/')."thum_medium_".$popularStore['logo']['name'] 
                : PUBLIC_PATH_CDN.ltrim($popularStore['imgpath'], '/')."thum_medium_".$popularStore['imgname'];    
            echo '<li>
                <a href="' .HTTP_PATH_LOCALE. $popularStore['permaLink']. '">
                    <img src="' . $popularStoreImage . '"  
                    alt="' .$popularStore['name'] . '" title="' .$popularStore['name'] . '" />
                </a>
            </li>';
        }
        ?>
        </ul>
    </div>
    </div>
</section>
