<article class="section section-2">
    <h2>
    <?php echo $this->headerText;?>
    </h2>
    <ul class="shops shops-2">
        <?php
        foreach ($this->popularStores as $popularStore)
        { 
            $popularStore = isset($popularStore['popularshops'])
                ?  $popularStore['popularshops'] 
                :  $popularStore;
            $popularStoreImage =
                isset($popularStore['logo']) ? 
                PUBLIC_PATH_CDN.ltrim($popularStore['logo']['path'], '/')
                ."thum_big_".$popularStore['logo']['name'] : PUBLIC_PATH_CDN.ltrim($popularStore['imgpath'], '/')."thum_big_".$popularStore['imgname'];    
            echo '<li>
                <a href="' .HTTP_PATH_LOCALE. $popularStore['permaLink']. '">
                    <img src="' . $popularStoreImage . '"  
                    alt="' .$popularStore['name'] . '"  width="122" title="' .$popularStore['name'] . '" />
                </a>
            </li>';
        }
        ?>
    </ul>
</article>