<?php
if(!isset($_COOKIE['registered_user'])) {
    if ($this->zendForm!='' && $this->zendForm!=null) {
        $signUpForm = $this->partial(
            'partials/_signupwidget.phtml',
            array(
                'signupFormWidgetType'=>$this->signupFormWidgetType,
                'zendForm'=>$this->zendForm,
            )
        );
        
        $visitorId = 0;
        if(Auth_VisitorAdapter::hasIdentity()):
            $visitorId = Auth_VisitorAdapter::getIdentity()->id;
        endif;
        $shopId = $this->shopId=='' ? 0 : $this->shopId;

        $shopLogoOrDefaultImage = '<div class="ico-mail"></div>';
        if($shopId!=0) {
            $shop = Shop::getShopLogoByShopId($shopId);
            if($shop!='') {
                $shopLogoImage = PUBLIC_PATH_CDN.ltrim($shop['logo']['path'], "/").'thum_medium_'. $shop['logo']['name'];
                $shopLogoOrDefaultImage = '<img alt="' . $shop['permaLink']. '" src="'. $shopLogoImage .'">';
            }
        }

        if (Visitor::getFavoriteShopsForUser($visitorId, $shopId)==false):
            if ($this->signupFormWidgetType== 'widgetWithinOffers') {?>
                <div class="block block-form <?php echo $shopId==0 ? 'block-form-2' : ''?>">
                    <div class="holder">
                        <div class="<?php echo $this->shopId=='' ? 'ico-box' : 'icon'?>">
                        <?php echo $shopLogoOrDefaultImage;?>
                        </div>
                    <?php echo $signUpForm;?>
                    </div>
                </div>
                <?php 
            } else {
                echo $signUpForm;
            }
        endif;
    }
}