<?php 
$visitorInformation = Visitor::getUserDetails(Auth_VisitorAdapter::getIdentity()->id);
?>
<nav class="account-box">
    <ul>
        <li>
           <span class="glyphicon glyphicon-user"></span>
           <span class='show-on-web'>
               <a href="<?php echo HTTP_PATH_LOCALE 
               . FrontEnd_Helper_viewHelper::__link('link_inschrijven') . "/" 
               . FrontEnd_Helper_viewHelper::__link('link_profiel');?>">
               <?php echo FrontEnd_Helper_viewHelper::__form('form_Welcome') . " ";?>
               </a>
            </span>
           <!--<a href="<?php echo HTTP_PATH_LOCALE 
               . FrontEnd_Helper_viewHelper::__link('link_inschrijven') . "/" 
               . FrontEnd_Helper_viewHelper::__link('link_profiel');?>" class="name">
               <?php //echo $visitorInformation[0]['firstName'];?>
           </a>-->
        </li>
        <li>
          <a href="<?php echo HTTP_PATH_LOCALE 
          . FrontEnd_Helper_viewHelper::__link('link_mijn-favorieten') . "/" 
          . FrontEnd_Helper_viewHelper::__link('link_memberonlycodes');?>">
          <?php echo FrontEnd_Helper_viewHelper::__form('form_Your offers');?>
          </a>
        </li>
        <li>
          <a href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('link_mijn-favorieten');?>">
          <?php echo FrontEnd_Helper_viewHelper::__form('form_Your brands');?>
          </a>
        </li>
        <li>
            <a href=" <?php echo HTTP_PATH_LOCALE 
            . FrontEnd_Helper_viewHelper::__link('link_login') .'/'
            . FrontEnd_Helper_viewHelper::__link('link_logout'); ?>">
              <?php echo FrontEnd_Helper_viewHelper::__form('form_Sign Out');?>
            </a>
        </li>
    </ul>
</nav>