<?php 
	// check user logged in or not
	if (! Auth_VisitorAdapter::hasIdentity() ) :
		// this get left side widget of login and free sign up
		echo FrontEnd_Helper_viewHelper::gethomeSections("loginwedget", 0);
	else: ?>
		<?php $hash = md5(Auth_VisitorAdapter::getIdentity()->id.microtime()); ?>
		<h4 class="text-white text-center"><?php echo $this->translate('Welkom') ." ". Auth_VisitorAdapter::getIdentity()->firstName; ?></h4>
		<p class="benefits-txt text-center mt10"><?php echo $this->translate('Als lid van Kortingscode.nl krijg jij toegang tot exclusieve codes en acties!'); ?></p>
		<div class="logged-direct-icon">
		<img src="<?php echo HTTP_PATH;?>public/images/front_end/money-bag-black.png" width="" height="" alt="New Icon" />
		</div>
		<div class="profile-btn-cont">
			<input class='direct-login-input-btn' type="button"  onclick="window.location = '<?php echo HTTP_PATH_LOCALE; ?>mijn-favorieten?hash=<?php echo $hash; ?>';"  value='<?php echo $this->translate("BEKIJK JE VOORDELEN NU");?>'/>
		</div>

<?php endif; ?>