<?php
	$loginwidgetFooter = new FrontEnd_Helper_viewHelper();
	$logwidgetFooter = $loginwidgetFooter->getloginwidgetFooter();
	// check user logged in or not
	// $logwidgetFooter is right bottom widget of login and free sign up in footer
	if ( ! Auth_VisitorAdapter::hasIdentity()): ?>
		<?php echo $logwidgetFooter; ?>
	<?php else:?>
		<h4 class="mt10"><?php echo $this->translate('Welkom') ." ". Auth_VisitorAdapter::getIdentity()->firstName; ?></h4>
		<p class="text-gray text-center mt15"><?php echo $this->translate('Als lid van Kortingscode.nl krijg jij toegang tot exclusieve codes en acties!'); ?></p>
		<div class="logged-direct-icon"></div>
		<input class="direct-login-input-btn margin-bottom-custom" style="float:right; margin-top:-61px;" type="button"  onclick="window.location = '<?php echo HTTP_PATH_LOCALE; ?>mijn-favorieten';"  value='<?php echo $this->translate("BEKIJK JE VOORDELEN NU");?>'/>
		<?php /*<input type="button" onclick="window.location = '<?php echo HTTP_PATH_LOCALE; ?>mijn-favorieten?hash=<?php echo $hash; ?>';" class="view-benifits-btn margin-bottom-custom" style="float:right; margin-top:-61px;" /> */?> 
	<?php endif; ?>
