<div>
    <table width="100%" align="center" cellpadding="0" cellspacing="0">
        <tbody>
        <tr>
            <td height="5"></td>
        </tr>
        <?php if(!empty($bannerImage)) { ?>
            <tr>
                <td align="center">
                    <?php if(!empty($bannerUrl)) { ?><a href="<?php echo $bannerUrl; ?>" target="_blank"> <?php } ?>
                        <img src="<?php echo $urls['publicPathCdn'].urldecode($bannerImage); ?>" width="615" alt="<?php echo urldecode($bannerImage); ?>" title="<?php echo urldecode($bannerImage); ?>" style="display:block">
                    <?php if(!empty($bannerUrl)) { ?></a> <?php } ?>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <table width="100%" align="center" cellpadding="0" cellspacing="0">
        <tbody>
        <tr>
            <td height="46"></td>
        </tr>
        <?php if(!empty($footerText)) { ?>
        <tr>
            <td align="center" style="padding:0 0 25px; font:12px/20px Arial,Helvetica,sans-serif; color:#878a8d">
                <?php echo $footerText; ?>
            </td>
        </tr>
        <?php } ?>
        <tr>
            <td align="center" style="text-decoration:none; color:#878a8d; padding:0 0 37px; font:14px/17px Arial,Helvetica,sans-serif; color:#33383e">
                <a href="http://mandrillapp.com/track/click/15439343/www.kortingscode.nl?p=eyJzIjoiQXA5Rzdjck5hamJ5LXcxbVFKUlRCOGRpSG9vIiwidiI6MSwicCI6IntcInVcIjoxNTQzOTM0MyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvd3d3LmtvcnRpbmdzY29kZS5ubFxcXC9pbmxvZ2dlblxcXC9kaXJlY3Rsb2dpbnVuc3Vic2NyaWJlXFxcL1VtRnRaWE5vUUhkbFlpMW1iR2xuYUhRdWJtdz1cXFwvYTk4MTNiNjBjZDY1ZWYxZjRmNGQ4MjgxYzA3ZDg5MjNcIixcImlkXCI6XCJhZDU3OTNkNGQzMTQ0ZWYzYTc1ODY0ZmZkOTM5NDhiYlwiLFwidXJsX2lkc1wiOltcIjNjNTdjZTkwNmIzYTE4NzNkNjEyMTRiMzM2NGJmYTI1NGMyMTgyYTVcIl19In0" target="_blank" style="text-decoration:none; color:#33383e">Uitschrijven</a>
                |
                <a href="http://mandrillapp.com/track/click/15439343/www.kortingscode.nl?p=eyJzIjoiMUw1TzludjlsS3UzTDhoTC1XV2tNZThHeUhjIiwidiI6MSwicCI6IntcInVcIjoxNTQzOTM0MyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvd3d3LmtvcnRpbmdzY29kZS5ubFxcXC9pbmxvZ2dlblxcXC9kaXJlY3QtaW5sb2dnZW5cXFwvY21GdFpYTm9RSGRsWWkxbWJHbG5hSFF1Ym13PVxcXC9hOTgxM2I2MGNkNjVlZjFmNGY0ZDgyODFjMDdkODkyM1wiLFwiaWRcIjpcImFkNTc5M2Q0ZDMxNDRlZjNhNzU4NjRmZmQ5Mzk0OGJiXCIsXCJ1cmxfaWRzXCI6W1wiNjRmNTgwNTlmYjRhOGVmY2FkYmQ3Yzg1OGJkMTE2MGI1NGVmNzY5YlwiXX0ifQ" target="_blank" style="text-decoration:none; color:#33383e">Wijzig je profiel</a>
                |
                <a href="http://mandrillapp.com/track/click/15439343/www.kortingscode.nl?p=eyJzIjoiNDFnSGpNOTY3QU5HVmFYMmxCN2dFVjR1NnJjIiwidiI6MSwicCI6IntcInVcIjoxNTQzOTM0MyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvd3d3LmtvcnRpbmdzY29kZS5ubFxcXC9pbmZvXFxcL2NvbnRhY3RcIixcImlkXCI6XCJhZDU3OTNkNGQzMTQ0ZWYzYTc1ODY0ZmZkOTM5NDhiYlwiLFwidXJsX2lkc1wiOltcIjliMzM4MTU3MDVlNWVkMzA0N2JmZGJjOWU5OGY1MGE4YzVkNzE2OTJcIl19In0" target="_blank" style="text-decoration:none; color:#33383e">Contact</a>
            </td>
        </tr>
        <tr>
            <td align="center">
                <a href="#" target="_blank">
                    <img src="<?php echo $footerLogo; ?>" border="0" alt="<?php echo $websiteName; ?>" title="<?php echo $websiteName; ?>" style="vertical-align:top">
                </a>
            </td>
        </tr>
        </tbody>
    </table>
</div>