<tr>
    <td bgcolor="#0077cc">
        <table width="600" align="center" bgcolor="#0077cc" cellpadding="0" cellspacing="0" style="">
            <tbody>
            <tr>
                <td colspan="2" height="22"></td>
            </tr>
            <tr>
                <td width="205"></td>
                <td width="431"><a href="<?php echo rtrim(HTTP_PATH_LOCALE, '/'); ?>" target="_blank"><img src="<?php echo $headerLogo; ?>" border="0" alt="<?php echo $websiteName; ?>" title="<?php echo $websiteName; ?>" style="vertical-align:top"></a> </td>
            </tr>
            <tr>
                <td colspan="2" height="20"></td>
            </tr>
            </tbody>
        </table>
    </td>
</tr>
<?php if(!empty($bannerImage)) { ?>
    <tr>
        <td bgcolor="#0077cc">
            <?php if(!empty($bannerUrl)) { ?><a href="<?php echo $bannerUrl; ?>" target="_blank"> <?php } ?>
                <img src="<?php echo $bannerImage; ?>" width="615" alt="Header Banner" title="Header Banner" style="display:block">
                <?php if(!empty($bannerUrl)) { ?></a> <?php } ?>
        </td>
    </tr>
<?php } ?>