<head>
<meta charset="utf-8"/>
<title>Flipit.com | Changing The Way We Save</title>
<meta name="viewport" content="user-scalable=yes, width=device-width, initial-scale=1.0" />
<link href="http://www.flipit.com" rel="canonical" />
<?php
if (APPLICATION_ENV == 'development') {
    $lessCssPath = "/public/css/front_end/";
    $this->headLink(array("rel"=>"stylesheet/less", 'href'=>$lessCssPath.'all.less'));
    echo $this->headLink(array("rel"=>"stylesheet/less", 'href'=>$lessCssPath.'ie.less'));
} else {
    echo $this->headLink()
        ->prependStylesheet("/public/css/front_end/all.css");
}
?>
<link href='http://fonts.googleapis.com/css?family=Cookie' rel='stylesheet' type='text/css'>
<!--[if IE]>
<link type="text/css" media="all" rel="stylesheet" href="<?php echo HTTP_PATH;?>public/front_end/css/ie.css">
<script type="text/javascript" src="<?php echo HTTP_PATH;?>public/front_end/js/ie.js"></script>
<![endif]-->
<link href="<?php echo HTTP_PATH;?>public/flipit/images/favicon.ico" rel="shortcut icon" type="image/x-icon" />
<meta name="msvalidate.01" content="44C2028411B932A2DCC28359FD20685F" />
<meta property="og:title" content="Flipit.com">
<meta property="og:description" content="Changing The Way We Save" />
<meta property="og:image" content="http://www.flipit.com/public/be/images/upload/media/flipit.png">
<meta property="og:url" content="http://www.flipit.com">
<meta property="og:site_name" content="Flipit.com" />
<meta title="Flipit.com – Your Global Promo Code and Coupon Portal" />
<meta name="description" content="Get discounts in <?php echo date('F'); ?> at thousands of online stores with promo codes from Flipit.com. Find the best coupons with the world’s largest discounts website." />
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-17691171-3', 'flipit.com');
    ga('send', 'pageview'); 
</script>