<head>
<meta charset="utf-8"/>
<title>Flipit.com | Changing The Way We Save</title>
<meta name="viewport" content="user-scalable=yes, width=device-width, initial-scale=1.0" />
<link href="http://www.flipit.com" rel="canonical" />
<link href="<?php echo HTTP_PATH;?>public/flipit/css/style.css" rel="stylesheet" type="text/css" />
<link href="<?php echo HTTP_PATH;?>public/flipit/images/favicon.ico" rel="shortcut icon" type="image/x-icon" />
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
<script type="text/javascript" src="http://use.typekit.com/shn5sjh.js"></script>
<script type="text/javascript" src="<?php echo HTTP_PATH;?>public/js/front_end/socialmedia.js"></script>
<meta name="msvalidate.01" content="44C2028411B932A2DCC28359FD20685F" />
<meta property="og:title" content="Flipit.com">
<meta property="og:description" content="Changing The Way We Save" />
<meta property="og:image" content="http://www.flipit.com/public/be/images/upload/media/flipit.png">
<meta property="og:url" content="http://www.flipit.com">
<meta property="og:site_name" content="Flipit.com" />
<meta name="description" content="Flipit is the easiest way to save money online. Find free coupons, local discount codes and exclusive deals for thousands of online stores." />
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-17691171-3', 'flipit.com');
    ga('send', 'pageview'); 
</script>