<?php
if (APPLICATION_ENV == 'development') {
    $headScript = $this->HeadScript();
} else {
    $headScript = $this->minifyHeadScript();
}
$headScript->prependFile("/public/js/front_end/less/dist/less-1.7.0.js")
    ->prependFile("/public/js/front_end/jquery.main.js")
    ->prependFile("/public/js/jquery-ui-1.8.16.custom.min.js")
    ->prependFile("/public/js/jquery-1.7.2.min.js");
echo $headScript;