<?php if (Auth_VisitorAdapter::hasIdentity()): ?>
    <?php
        $userid = Auth_VisitorAdapter::getIdentity()->id;
        //$detail = Visitor::getuserdetails($userid);
        $hash = md5($userid.microtime());
    ?>
    <div class="dropdown">
        <a class="account" href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('link_mijn-favorieten') ?>?hash=<?php echo $hash; ?>"><img style="float:left;" src="<?php echo HTTP_PATH; ?>public/images/front_end/img-man.png" alt="user" />
            <span><strong><?php echo $this->translate('Mijn profiel');?></strong></span>
        </a>
    </div>
    <ul style="float:right;">
		<li class="none"><a href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper:: __link('link_info/privacy-cookies');?>" ><?php echo $this->translate('Cookies');?></a></li>
		<li class="none"><a href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('link_nieuws') ?>"><?php echo $this->translate('News');?></a></li>
        <li><a href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('link_login') .'/'. FrontEnd_Helper_viewHelper::__link('link_logout') ?>"><?php echo $this->translate('Uitloggen');?></a></li>
        <li><a href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('link_mijn-favorieten') .'/'. FrontEnd_Helper_viewHelper::__link('link_memberonlycodes') ?>"><?php echo $this->translate('Member-Only');?></a></li>
    </ul>
<?php else: ?>
    <ul>
        <li style="width:81px;"><img src="<?php echo HTTP_PATH; ?>public/images/front_end/img-man.png" alt="user" /><a class="text-orange-link" rel="nofollow" href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('link_inschrijven').'/'.FrontEnd_Helper_viewHelper::__link('link_stap1') ?>"><?php echo $this->translate('Inschrijven');?></a></li>
        <li class="none"><a rel="nofollow" href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('link_login') ?>"><?php echo $this->translate('Inloggen');?></a></li>
        <li class="none"><a href="<?php echo HTTP_PATH_LOCALE?>info/privacy-cookies"><?php echo $this->translate('Cookies');?></a></li>
        <li class="none"><a href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('link_nieuws')?>"><?php echo $this->translate('News');?></a></li>
        <li><a  href="<?php echo HTTP_PATH_LOCALE . FrontEnd_Helper_viewHelper::__link('link_login') .'/'. FrontEnd_Helper_viewHelper::__link('link_dummy') ?>"><?php echo $this->translate('Member-Only');?></a></li>
    </ul>
<?php endif; ?>