<!DOCTYPE html>
<html>
<?php echo $this->render('partials/_head.phtml'); ?>
<link rel="alternate" hreflang="nl-BE" href="http://www.flipit.com/be" />
<link rel="alternate" hreflang="fr-FR" href="http://www.flipit.com/fr" />
<link rel="alternate" hreflang="de-CH" href="http://www.flipit.com/ch" />
<link rel="alternate" hreflang="en-IN" href="http://www.flipit.com/in" />
<link rel="alternate" hreflang="pl-PL" href="http://www.flipit.com/pl" />
<link rel="alternate" hreflang="de-DE" href="http://www.flipit.com/de" />
<link rel="alternate" hreflang="es-ES" href="http://www.flipit.com/es" />
<link rel="alternate" hreflang="en-US" href="http://www.flipit.com/us" />
<link rel="alternate" hreflang="en-AU" href="http://www.flipit.com/au" />
<link rel="alternate" hreflang="pt-BR" href="http://www.flipit.com/br" />
<link rel="alternate" hreflang="pt-PT" href="http://www.flipit.com/pt" />
<link rel="alternate" hreflang="de-AT" href="http://www.flipit.com/at" />
<link rel="alternate" hreflang="it-IT" href="http://www.flipit.com/it" />
<link rel="alternate" hreflang="sv-SE" href="http://www.flipit.com/se" />
<link rel="alternate" hreflang="en-CA" href="http://www.flipit.com/ca" />
<link rel="alternate" hreflang="en-SG" href="http://www.flipit.com/sg" />
<link rel="alternate" hreflang="en-NZ" href="http://www.flipit.com/nz" />
<link rel="alternate" hreflang="x-default" href="http://www.flipit.com" />
</head>
<body class="splash-page">
<?php
$mostPopularCoupon = FrontEnd_Helper_layoutContent::getMostPopularCouponOnEarth(); 
if (!empty($mostPopularCoupon['locale']) && !empty($mostPopularCoupon['mostPopularCoupon'])) { 
    $countryName = FrontEnd_Helper_viewHelper::getCountryNameByLocale($mostPopularCoupon['locale']);
    $localeName = $mostPopularCoupon['locale'] == 'en' ? '' : $mostPopularCoupon['locale'].'/';
    $domainName = $mostPopularCoupon['locale'] == 'en' ? 'http://www.kortingscode.nl/' : 'http://www.flipit.com/'.$localeName;
    $offerPartial = new FrontEnd_Helper_OffersPartialFunctions();
    $daysTillOfferExpires = $offerPartial->getDaysTillOfferExpires($mostPopularCoupon['mostPopularCoupon'][0]['endDate']);
    $offerExpiryDate =  $offerPartial->getOfferDates((object) $mostPopularCoupon['mostPopularCoupon'][0], $daysTillOfferExpires);
}
?>
    <div id="wrapper">
        <div class="container">
            <div class="panel-box win-min-height">
                <strong class="logo-panel"><a href="http://www.flipit.com/">flipt Changing the way we save</a></strong>
                <span class="alt-text">CHoose RegioN:</span>
                <div class="region-box">
                    <span class="flag"><img src="<?php echo PUBLIC_PATH;?>images/front_end/img-34.png" alt="img-34" width="16" height="11" /></span><span class="text">Country Detected:  <a href="#">Sweden | Sverige</a></span>
                </div>
                <div class="links-cols">
                    <div class="row">
                    <div class="col-xs-6">
                        <strong class="title">ASIA</strong>
                        <ul>
                            <li><a href="http://www.flipit.com/in">India</a></li>
                            <li><a href="#">Indonesia</a></li>
                            <li><a href="#">Malaysia | Malasja</a></li>
                            <li><a href="http://www.flipit.com/sg">Singapore</a></li>
                        </ul>
                        <strong class="title">africa</strong>
                        <ul>
                            <li><a href="#">South Africa</a></li>
                        </ul>
                        <strong class="title">australia</strong>
                        <ul>
                            <li><a href="http://www.flipit.com/au">Australia</a></li>
                        </ul>
                        <strong class="title">NORTH AND SOUTH AMERICA</strong>
                        <ul>
                            <li><a href="http://www.flipit.com/br">Brazil | Brasil</a></li>
                            <li><a href="http://www.flipit.com/ca">Canada</a></li>
                            <li><a href="http://www.flipit.com/us">United States</a></li>
                        </ul>
                    </div>
                    <div class="col-xs-6">
                        <strong class="title">EUROPE</strong>
                        <ul>
                            <li><a href="http://www.flipit.com/at">Austria | Österreich</a></li>
                            <li><a href="http://www.flipit.com/be">Belgium | België</a></li>
                            <li><a href="#">Denmark | Danmark</a></li>
                            <li><a href="#">Finland | Suomi</a></li>
                            <li><a href="http://www.flipit.com/fr">France</a></li>
                            <li><a href="http://www.flipit.com/de">Germany | Deutschland</a></li>
                            <li><a href="http://www.flipit.com/it">Italy | Italia</a></li>
                            <li><a href="#">Norway | Norge</a></li>
                            <li><a href="http://www.flipit.com/pl">Poland | Polska</a></li>
                            <li><a href="http://www.flipit.com/es">Spain | España</a></li>
                            <li><a href="http://www.flipit.com/se">Sweden | Sverige</a></li>
                            <li><a href="http://www.flipit.com/ch">Switzerland | Schweiz</a></li>
                            <li><a href="#">United Kingdom</a></li>
                        </ul>
                    </div>
                    </div>
                </div>
                <?php 
                    if (!empty($mostPopularCoupon['locale']) && !empty($mostPopularCoupon['mostPopularCoupon'])) { 
                ?>        
                <span class="alt-text">Most Popular Coupon ON EARTH</span>
                <div class="sponsor-box">
                    <span class="image">
                        <a href="<?php echo $domainName.$mostPopularCoupon['mostPopularCoupon'][1]['permaLink']; ?>">
                            <img src="<?php echo PUBLIC_PATH_CDN.$localeName.ltrim($mostPopularCoupon['mostPopularCoupon'][2]['path'], '/').$mostPopularCoupon['mostPopularCoupon'][2]['name']; ?>" alt="image description" width="86" height="44" />
                        </a>    
                    </span>
                    <div class="text-box">
                         <a href="<?php echo $domainName.$mostPopularCoupon['mostPopularCoupon'][1]['permaLink']; ?>">
                            <strong>Flipit <?php echo $countryName; ?> - <?php echo $mostPopularCoupon['mostPopularCoupon'][1]['name']; ?> </strong>
                        </a>
                        <p><span class="mark"><?php echo $offerExpiryDate; ?></span>
                            <?php echo $mostPopularCoupon['mostPopularCoupon'][0]['exclusiveCode'] != '' ? 
                            '<span class="mark2">Exclusive</span>' : '' ; ?></p>
                        <a href="<?php echo $domainName.$mostPopularCoupon['mostPopularCoupon'][1]['permaLink']; ?>"><?php echo $mostPopularCoupon['mostPopularCoupon'][0]['title']; ?></a>
                    </div>
                </div>
                <?php 
                    }
                ?>
            </div>
            <div class="bg-stretch">
                <img src="<?php echo PUBLIC_PATH;?>images/front_end/img-33.jpg" alt="img-33" />
            </div>
        </div>
    </div>
</body>
</html>

 