<?php
$link = $this->httpPathLocale.FrontEnd_Helper_viewHelper::__link('link_top-20');
$codeAlertSubject = !empty($this->mandrillNewsletterSubject) ? $this->mandrillNewsletterSubject : '';
$topOffer = (object) $this->codeAlert;
$offerPartial = new FrontEnd_Helper_OffersPartialFunctions();
$daysTillOfferExpires = $offerPartial->getDaysTillOfferExpires($topOffer->endDate);
$exclusiveCode = '';
$exclusiveImage = '';
if( isset($topOffer->exclusiveCode) && $topOffer->exclusiveCode == 1) {
    $exclusiveCode = FrontEnd_Helper_viewHelper::__email('email_exclusive');
    $exclusiveImage = $this->httpPath."public/images/star.png";         
}
$utmParameters = $this->mailType != 'welcome'
    ? '?popup='.$topOffer->id.'&utm_source=transactional&utm_medium=email&utm_campaign='
    .$codeAlertSubject.'&type=code#'.$topOffer->id : '?popup='.$topOffer->id.'&type=code#'.$topOffer->id;
?>
<tr>
    <td bgcolor="#ffffff">
        <table width="100%" cellpadding="0" cellspacing="0">
            <tbody><tr>
                <td bgcolor="#ea973d" align="center" 
                    style="padding:12px 0 11px; font:18px/18px Arial, Helvetica, sans-serif; color:#373736;">
                    <span style="text-decoration:none; color:#ffffff;">
                        <?php echo FrontEnd_Helper_viewHelper::__email('email_New Code Alert');?>
                    </span>
                </td>
            </tr>
            <tr>
                <td style="padding:28px 10px 30px 29px; border-bottom:1px solid #eaeaea;">
                    <table width="100%" cellpadding="0" cellspacing="0">
                        <tbody><tr>
                            <td valign="top" width="132" style="border:1px solid #dddddd; border-radius:5px;">
                                <table width="100%" cellpadding="0" cellspacing="0">
                                    <tbody><tr>
                                        <td height="66" align="center">
                                            <a href="<?php echo $this->httpPathLocale.$topOffer->shop['permaLink'].$utmParameters; ?>" style="text-decoration:none; color:#fff;">
                                                <img src="<?php echo $this->publicPathCdn.ltrim($topOffer->shop['logo']['path'],'/').'thum_big_'.$topOffer->shop['logo']['name']; ?>" style="vertical-align:top;" 
                                                width="132" height="66" alt="<?php echo $topOffer->shop['name']; ?>" title="<?php echo $topOffer->shop['name']; ?>">
                                            </a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td bgcolor="#ea973d" align="center" 
                                            style="border-radius:0 0 4px 4px;
                                            box-shadow:0 0 4px rgba(0,0,0,0.15);
                                            padding:6px 0 5px; 
                                            font:11px/17px Arial, Helvetica, sans-serif; 
                                            color:#fff;">
                                            <a href="<?php echo $this->httpPathLocale.$topOffer->shop['permaLink'].$utmParameters; ?>" style="text-decoration:none; color:#fff;"><?php echo FrontEnd_Helper_viewHelper::__email('email_CODE'); ?></a>
                                        </td>
                                    </tr>
                                </tbody></table>
                            </td>
                            <td width="30"></td>
                            <td valign="top">
                                <table width="100%" cellpadding="0" cellspacing="0">
                                    <tbody><tr>
                                        <td>
                                            <table width="100%" cellpadding="0" cellspacing="0">
                                                <tbody><tr>
                                                    <td width="91" 
                                                        style="padding:0 0 2px; 
                                                        font:14px/17px Arial, Helvetica, sans-serif; 
                                                        color:#363636;">
                                                        <span style="float: left;"><a href="<?php echo $this->httpPathLocale.$topOffer->shop['permaLink'];?>" style="text-decoration:none; color:#363636;"><?php echo $topOffer->shop['name']; ?></a></span>
                                                        <span style="margin-right: 5px; margin-left: 5px; float: left; font:14px/17px Arial, Helvetica, sans-serif; color: #e89438;">
                                                        <?php echo $exclusiveCode; ?>
                                                        </span>
                                                    </td>  
                                                </tr>
                                            </tbody></table>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td style="padding:0 0 15px; 
                                        font:16px/22px Arial, Helvetica, sans-serif; 
                                        color:#0077cc;"><a href="<?php echo $this->httpPathLocale.$topOffer->shop['permaLink'].$utmParameters; ?>" 
                                        style="text-decoration:underline; 
                                        color:#0077cc;"><?php echo $topOffer->title; ?></a></td>
                                    </tr>
                                    <tr>
                                        <td style="font:12px/17px Arial, Helvetica, sans-serif; 
                                        color:#32383e;"><?php echo BackEnd_Helper_MandrillHelper::getOfferDates($topOffer, $daysTillOfferExpires, $this->locale); ?></td>
                                    </tr>
                                </tbody></table>
                            </td>
                        </tr>
                    </tbody></table>
                </td>
            </tr>
            <tr>
                <td bgcolor="#fafafa" align="center" style="padding:12px 0 11px; 
                font:bold 14px/17px Arial, Helvetica, sans-serif; color:#373736;">
                <a href="<?php echo $link.$utmParameters; ?>" style="text-decoration:none; color:#373736;"><?php echo FrontEnd_Helper_viewHelper::__email('email_Bekijk meer van onze top aanbiedingen');?> &gt;</a>
                </td>
            </tr>
        </tbody></table>
    </td>
</tr>