<table width="100%" align="center" cellpadding="0" cellspacing="0">
    <?php 
    if (!empty($this->newsLetterFooterImage['path'])) {
        ?>
        <tr><td height="5"></td></tr>
        <tr>
            <td align="center">
                <?php 
                if (!empty($this->newsLetterFooterImage['footerurl'])) {
                    ?>
                    <a target = "_blank" href="<?php echo $this->newsLetterFooterImage['footerurl']; ?>">
                    <?php 
                }
                ?>
                <img style="display: block" width='615'
                    alt="<?php echo urldecode($this->newsLetterFooterImage['name']); ?>" 
                    title="<?php echo urldecode($this->newsLetterFooterImage['name']); ?>" 
                    src="<?php echo $this->publicPathCdn.$this->newsLetterFooterImage['path']
                    .urldecode($this->newsLetterFooterImage['name']); ?>">
               <?php 
                if (!empty($this->newsLetterFooterImage['footerurl'])
                ) {
                    ?>
                    </a>
                    <?php
                }
                ?>
            </td>
        </tr>
        <?php 
    }
    ?>
</table>