<?php
$link = $this->httpPathLocale.FrontEnd_Helper_viewHelper::__link('link_top-50');
if($this->categoryInformation != null) {
    $categoryInformation = explode('|', $this->categoryInformation);
    $link = $this->httpPathLocale.FrontEnd_Helper_viewHelper::__link('link_categorieen').'/'.$categoryInformation[1];
    ?>
    <tr><td height="45"></td></tr>
    <tr>
        <td style="padding:0 0 25px 29px; font:24px/27px Arial, Helvetica, sans-serif; color:#32383e;">
            <?php echo FrontEnd_Helper_viewHelper::__email('email_Popular category:'). ' ' .$categoryInformation[0]; ?>
        </td>
    </tr>
    <?php 
    }
?>
<tr>
    <td bgcolor="#ffffff" style="border:1px solid #e4e4e4; border-radius:5px;">
        <table width="100%" cellpadding="0" cellspacing="0">
            <tbody>
                <?php
                    foreach ($this->topOffers as $topOffer) {
                        $topOffer = (object) $topOffer;
                        if (isset($this->testStatus) && $this->testStatus == 'doc2') { 
                            $shopData = $topOffer->shopOffers;
                            $permalink = $shopData['permaLink'];
                            $testStatus = 'doc2';
                        } else {
                            $shopData = $topOffer->shop;
                            $permalink = $shopData['permalink'];
                            $testStatus = '';
                        }
                        $offerPartial = new FrontEnd_Helper_OffersPartialFunctions();
                        $daysTillOfferExpires = $offerPartial->getDaysTillOfferExpires($topOffer->endDate);
                        if (!empty($topOffer->shop)) {
                            $urlToShow = $offerPartial->getUrlToShowForEmail($topOffer, $this->httpPathLocale);
                        } else {
                            $urlToShow = $offerPartial->getUrlToShow($topOffer, $this->httpPathLocale);
                        }
                        $exclusiveCode = '';
                        $exclusiveImage = '';
                        if( isset($topOffer->exclusiveCode) && $topOffer->exclusiveCode == 1) {
                            $exclusiveCode = FrontEnd_Helper_viewHelper::__email('email_exclusive');
                            $exclusiveImage = "style='background:url(".$this->httpPath."public/images/exclusive-star.png) no-repeat right top #fef6ec;'";                 
                        }

                        $utmParameters = $this->mailType != 'welcome'
                            ? '?utm_source=transactional&utm_medium=email&utm_campaign='
                            .date('d-m-Y').'&type=code#'.$topOffer->id
                            : '?type=code#'.$topOffer->id;
                 ?>
                <tr <?php echo $exclusiveImage; ?>>
                    <td style="padding:28px 10px 30px 29px; border-bottom:1px solid #eaeaea;">
                        <table width="100%" cellpadding="0" cellspacing="0">
                            <tbody><tr>
                                <td width="132" >
                                    <table width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #dddddd; border-radius:5px;">
                                        <tbody><tr>
                                            <td height="66" align="center"><a href="<?php echo $this->httpPathLocale.$permalink.$utmParameters; ?>" style="text-decoration:none; color:#fff;"><img src="<?php echo $this->publicPathCdn.ltrim($shopData['logo']['path'],'/').'thum_big_'.$shopData['logo']['name']; ?>" style="vertical-align:top;" width="132" height="66" alt="<?php echo $shopData['name']; ?>" title="<?php echo $shopData['name']; ?>"></a></td>
                                        </tr>
                                        <tr>
                                            <td bgcolor="#ea973d" align="center" style="border-radius:0 0 4px 4px; box-shadow:0 0 4px rgba(0,0,0,0.15); padding:6px 0 5px; font:11px/17px Arial, Helvetica, sans-serif; color:#fff;"><a href="<?php echo $this->httpPathLocale.$permalink.$utmParameters; ?>" style="text-decoration:none; color:#fff;"><?php echo FrontEnd_Helper_viewHelper::__email('email_CODE'); ?></a></td>
                                        </tr>
                                    </tbody></table>
                                </td>
                                <td width="30"></td>
                                <td valign="top">
                                    <table width="100%" cellpadding="0" cellspacing="0">
                                        <tbody><tr>
                                            <td style="padding:0 0 2px; font:14px/17px Arial, Helvetica, sans-serif; color:#363636;"><a href="<?php echo $this->httpPathLocale.$permalink;?>" style="text-decoration:none; color:#363636;"><?php echo $shopData['name'];?></a>&nbsp;<span style="color: #e89438; display: inline-block;"><?php echo $exclusiveCode; ?></span></td>
                                        </tr>
                                        <tr>
                                            <td style="padding:0 0 15px; font:16px/22px Arial, Helvetica, sans-serif; color:#0077cc;"><a href="<?php echo $this->httpPathLocale.$permalink.$utmParameters; ?>" style="text-decoration:underline; color:#0077cc;"><?php echo $topOffer->title; ?></a></td>
                                        </tr>
                                        <tr>
                                            <td style="font:12px/17px Arial, Helvetica, sans-serif; color:#32383e;"><?php echo BackEnd_Helper_MandrillHelper::getOfferDates($topOffer, $daysTillOfferExpires, $this->locale, $testStatus); ?></td>
                                        </tr>
                                    </tbody></table>
                                </td>
                            </tr>
                        </tbody></table>
                    </td>
                </tr>
                <?php } ?>
            <tr>
                <td bgcolor="#fafafa" align="center" style="border-radius:0 0 4px 4px; padding:12px 0 11px; font:bold 14px/17px Arial, Helvetica, sans-serif; color:#373736;"><a href="<?php echo $link.$utmParameters; ?>" style="text-decoration:none; color:#373736;"><?php echo FrontEnd_Helper_viewHelper::__email('email_Bekijk meer van onze top aanbiedingen');?> &gt;</a></td>
            </tr>
        </tbody></table>
    </td>
</tr>