<?php
$publicPath = 'http://www.flipit.com/public/images/front_end/';
?>
<table width="100%" align="center" cellpadding="0" cellspacing="0">
    <tr>
        <td bgcolor="#0077cc">
            <table width="600" align="center" bgcolor="#0077cc" cellpadding="0" cellspacing="0"
                style="background:url(<?php
            echo  $publicPath.'emails/stamp_01-kc.jpg';
            ?>) no-repeat right bottom;">
                <tr><td colspan="2" height="22"></td></tr>
                <tr>
                    <td width="205"></td>
                    <td width="431">
                    </td>
                </tr>
                <tr><td colspan="2" height="20"></td></tr>
            </table>
        </td>
    </tr>
    <tr>
        <td bgcolor="#ffffff" style="border:1px solid #e4e4e4; border-radius:5px;">
            <table width="100%" cellpadding="0" cellspacing="0">
                <tr>
                    <td style="padding:28px 10px 30px 29px; border-bottom:1px solid #eaeaea;">
                    <table width="100%" cellpadding="0" cellspacing="0">
                        <tbody><tr><td height="36"></td></tr>
                        <tr>
                            <td style="padding:0 0 21px; font:23px/27px Arial, Helvetica, sans-serif; color:#32383e;">
                            Dear Flipit admin,</td>
                        </tr>
                        <tr>
                            <td style="padding:0 0 15px; font:14px/21px Arial, Helvetica, sans-serif; color:#373736;">
                            The password for the global shop export script is:</td>
                        </tr>
                        <tr>
                            <td style="padding:0 0 30px; font:14px/17px Arial, Helvetica, sans-serif; color:#373736;">
                            <?php echo $this->password; ?>
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:0 0 10px; font:14px/17px Arial, Helvetica, sans-serif; color:#373736;">
                            Regards,</td>
                        </tr>
                        <tr>
                            <td style="font:14px/17px Arial, Helvetica, sans-serif; color:#373736;">
                                Flipit team
                            </td>
                        </tr>
                        <tr><td height="36"></td></tr>
                        </tbody>
                    </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>