<?php 
foreach ($this->favouriteShopsOffers as $favouriteShopsOffer) {
    $shopImage = 
        PUBLIC_PATH_CDN.ltrim($favouriteShopsOffer['shop']['logo']['path'], "/")
        . "thum_big_" . $favouriteShopsOffer['shop']['logo']['name'];

    $permaLink = isset($favouriteShopsOffer["shop"]["permaLink"]) 
        ?  $favouriteShopsOffer["shop"]["permaLink"]
        : $favouriteShopsOffer["shop"]["permalink"];

    $activeOffers = isset($favouriteShopsOffer['activeCount']) 
        ? $favouriteShopsOffer['activeCount'] 
        : Shop::getActiveOffersCount($favouriteShopsOffer['shop']['id']);

    $activeOffers = isset($favouriteShopsOffer['activeCount']) 
        ? $activeOffers 
        : $activeOffers[0]['activeCount'];
    ?>
    <article class="block col-sm-6">
        <div class="holder">
            <a href="<?php echo HTTP_PATH_LOCALE. $permaLink;?>"  
            class="code code-2">
                <div class="center">
                    <div class="code-holder">
                        <img src="<?php echo $shopImage;?>" width="132"
                        alt="<?php echo $favouriteShopsOffer['shop']['name'];?>">
                    </div>
                </div>
                <footer class="bottom"><?php echo $this->translate('code');?></footer>
            </a>
            <div class="box">
                <div class="text">
                    <a href="<?php echo HTTP_PATH_LOCALE. $permaLink;?>"  
                    class="link">
                    <?php echo $favouriteShopsOffer['title'];?>
                    </a>
                    <p>
                        <?php 
                        echo $this->translate('and'). " " . $activeOffers. " " 
                        .$this->translate('other active codes for');
                        ?>
                        <a href="<?php echo HTTP_PATH_LOCALE. $permaLink;?>">
                        <?php echo $favouriteShopsOffer['shop']['name'];?>
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </article>
    <?php
}
echo $this->paginationControl($this->favouriteShopsOffers, 'Sliding', '/partials/_pagination.phtml');