 <?php
 foreach ($this->favouriteShops as $favouriteShop) :
    $shopImage = PUBLIC_PATH_CDN.ltrim($favouriteShop['shops'][0]['logo']['path'], "/")
        .  "thum_big_" . $favouriteShop['shops'][0]['logo']['name'];
    ?>   
    <article class="box">
        <div class="text-holder">
            <a href="<?php echo $favouriteShop['shops'][0]['permaLink'];?>" class="img-ico">
                <img src="<?php echo $shopImage;?>" width="132" alt="<?php echo $favouriteShop['name'];?>">
            </a>
            <div class="text">
                <a href="<?php echo $favouriteShop['shops'][0]['permaLink'];?>" class="link">
                <?php echo $favouriteShop['name'];?>
                </a>
                <p>
                <?php if($favouriteShop['activeCount'] > 0):?>
                    <a href="<?php echo $favouriteShop['shops'][0]['permaLink'];?>" class="active-offer">
                    <?php echo $favouriteShop['activeCount']. " " . $this->translate('active offers');?>
                    </a>
                <?php endif;?>
                </p>
                <a href='<?php echo HTTP_PATH_LOCALE. 'store/addtofavourite?permalink='
                . FrontEnd_Helper_viewHelper::__link('link_mijn-favorieten') .'&shopId='
                . base64_encode($favouriteShop['shops'][0]['id']);?>'
                class="pop btn btn-default remove-fovourite">
                    <em><?php echo $this->translate('I FOLLOW THIS');?></em>
                    <strong><?php echo $this->translate('REMOVE');?></strong>
                </a>
            </div>
        </div>
    </article>
    <?php
endforeach;