<?php 
foreach ($this->favouriteShopsOffers as $favouriteShopsOffer) {
    $shopImage = 
        PUBLIC_PATH_CDN.ltrim($favouriteShopsOffer['shop']['logo']['path'], "/")
        . "thum_big_" . $favouriteShopsOffer['shop']['logo']['name'];

    $permaLink = isset($favouriteShopsOffer["shop"]["permaLink"]) 
        ?  $favouriteShopsOffer["shop"]["permaLink"]
        : $favouriteShopsOffer["shop"]["permalink"];

    $activeOffers = isset($favouriteShopsOffer['activeCount']) 
        ? $favouriteShopsOffer['activeCount'] 
        : Shop::getActiveOffersCount($favouriteShopsOffer['shop']['id']);

    $activeOffers = isset($favouriteShopsOffer['activeCount']) 
        ? $activeOffers 
        : $activeOffers[0]['activeCount'];
    $showFavouriteButton = true;
    if(!empty($favouriteShopsOffer['shop']['favoriteshops'])) {
        foreach ($favouriteShopsOffer['shop']['favoriteshops'] as $favouriteShops) {
            if($favouriteShops['visitorId'] == Auth_VisitorAdapter::getIdentity()->id) {
                $showFavouriteButton = false;
            }
        }
    }
    ?>
    <article class="block col-sm-6">
        <div class="holder">
            <div>
                <a href="<?php echo HTTP_PATH_LOCALE. $permaLink;?>"  
                class="code code-2">
                    <div class="center">
                        <div class="code-holder">
                            <img src="<?php echo $shopImage;?>" width="132"
                            alt="<?php echo $favouriteShopsOffer['shop']['name'];?>">
                        </div>
                    </div>
                    <footer class="bottom"><?php echo $this->translate('code');?></footer>
                </a>
                <?php if($showFavouriteButton) { ?>
                <a
                href='<?php echo HTTP_PATH_LOCALE. 'store/addtofavourite?permalink='
                . FrontEnd_Helper_viewHelper::__link('link_mijn-favorieten') ."/"
                . FrontEnd_Helper_viewHelper::__link('link_memberonlycodes').'&shopId='
                . base64_encode($favouriteShopsOffer['shop']['id']);?>' class="pop btn btn-default">
                    <span class="glyphicon red-heart glyphicon-heart"></span>
                    <span><?php echo $this->translate('Favourite');?></span>
                </a>
                <?php } ?>
            </div>
            <div class="box">
                <div class="text">
                    <a href="<?php echo HTTP_PATH_LOCALE. $permaLink;?>"  
                    class="link">
                    <?php echo $favouriteShopsOffer['title'];?>
                    </a>
                    <p>
                        <?php 
                        echo $this->translate('and'). " " . $activeOffers. " " 
                        .$this->translate('other active codes for');
                        ?>
                        <a href="<?php echo HTTP_PATH_LOCALE. $permaLink;?>">
                        <?php echo $favouriteShopsOffer['shop']['name'];?>
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </article>
    <?php
}