<?php 
echo $this->minifyHeadLink()->appendStylesheet("/public/css/jquery-ui.min.css");
?>
<div class="title">
    <?php 
    echo $this->translate('Hey'). " ";
    $visitorFirstName = isset($this->userDetails['firstName']) 
        ? $this->userDetails['firstName'] 
        : $this->translate('Guest');
    echo $visitorFirstName;
    ?>
    <small><?php echo $this->translate('How are you? Let’s save some money for you!');?></small>
</div>
<?php
$socialcodeForm = $this->zendForm;
foreach ($socialcodeForm->getElements() as $formElement) {
    $formElement->getDecorator('label')->setOption('tag', null);
}
$rowClass = !empty($this->offers) ? '' : 'socialCodeRow';
?>
<div class="section">
    <div class="row <?php echo $rowClass;?>">
    <div class="col-lg-5 col-md-5 col-sm-5">
        <?php 
        if($this->successMessage!='' || $this->errorMessage!='') :
            ?>
            <div id='socialCodeDiv' class="widget <?php echo $rowClass;?>">
                <h1><?php echo $this->translate('Share your social codes');?>
                    <small>
                    <?php 
                    echo $this->translate('Did your a new coupon code worth sharing with flipit community?');
                    ?>
                    </small>
                </h1>
                <strong class="sub-title">
                    <?php echo $this->translate('Thank you for sharing your offer!');?>
                </strong>
                <div class="sub-text">
                    <p>
                    <?php echo $this->translate('Thanks for sharing your coupon with the Flipit Community! Our team will check the details and publish the code');?>
                    </p>
                </div>
                <?php
                $sharecodeLink = 
                HTTP_PATH_LOCALE.FrontEnd_Helper_viewHelper::__link('link_sharesocialcode');
                ?>
                <a href="<?php echo $sharecodeLink;?>">
                    <?php echo $this->translate('Share coupon codes for other shops');?>
                </a>
            </div>
            <?php
        else :
            ?>
            <form id="socialcodeForm" class="widget-form <?php echo $rowClass;?>" name="socialcodeForm" method="POST" action="">
                <div class="title">
                    <h1><?php echo $this->translate('Share your social codes');?>
                        <small>
                        <?php 
                        echo $this->translate('Did your a new coupon code worth sharing with flipit community?');
                        ?>
                        </small>
                    </h1>
                </div>
                <?php echo $socialcodeForm->nickname->renderViewHelper();?>
                <span class="fake-select">
                    <?php echo $socialcodeForm->store->renderViewHelper();?>
                </span>
                <?php echo $socialcodeForm->title->renderViewHelper();?>
                <?php echo $socialcodeForm->offerUrl->renderViewHelper();?>
                <div class="select-box">
                    <?php echo $socialcodeForm->code->renderViewHelper();?>
                    <?php echo $socialcodeForm->expireDate->renderViewHelper();?>
                </div>
                <?php echo $socialcodeForm->offerDetails->renderViewHelper();?>
                <button type='submit' id='sharecode' class="submit btn blue btn-primary">
                    <?php echo $this->translate('SHARE CODE');?>
                </button>
            </form>
            <?php
        endif;
        ?>
        </div>
        <?php 
        if(!empty($this->offers)):?>
            <div class="col-lg-7 col-md-7 col-sm-7">
        <?php  echo $this->partial(
                'partials/_offer.phtml',
                array(
                    'offers' => $this->offers,
                    'offersType'=>'simple',
                    'shopName' =>'',
                    'shopId' =>'',
                    'zendForm'=>''
                )
            );
        ?>
            </div>
        <?php  endif; ?>
    </div>
</div>
