<?php
$favouriteViewPath = "favourite/";
$favouriteShopsOffers = '<div class = "no-record txt-center">' . $this->translate('No record found') .'</div>'; 
if(!empty($this->favouriteShopsOffers)) {
    $favouriteShopsOffers = $this->partial(
        $favouriteViewPath.'_favouriteShopsOffers.phtml',
        array(
           'favouriteShopsOffers'=> $this->favouriteShopsOffers,
       )
    );
}
$firstCharacterOfUserName = mb_substr($this->userDetails['firstName'], 0, 1);
?>
<section class="profile-box">
    <?php 
    $visitorFirstName = isset($this->userDetails['firstName']) ? $this->userDetails['firstName'] : '';
    echo FrontEnd_Helper_viewHelper::accountTabPanel($visitorFirstName);
    ?>
    <div class="youroffers-page">
        <div class="section">
            <div class="row">
            <?php echo $favouriteShopsOffers; ?>    
            </div>
        </div>
    </div>
</section>
