<?php
$profileImage = '';
if (!empty($this->userDetails['visitorimage'])) {
    $profileImage = 
        PUBLIC_PATH_CDN
        .ltrim($this->userDetails['visitorimage']['path'],"/")
        .$this->userDetails['visitorimage']['name'];
}
$signupViewPath = "favourite/";
$favouriteShopsOffers = $this->partial(
    $signupViewPath.'_favouriteShopsOffers.phtml',
    array(
       'favouriteShopsOffers'=> $this->favouriteShopsOffers,
   )
);
?>
<div class="header-block">
    <div class="icon icon-small">
        <img src="<?php echo $profileImage;?>" width="90"
        alt="<?php echo $this->userDetails['firstName'];?>">
    </div>
    <div class="box">
        <h1>
        <?php echo FrontEnd_Helper_viewHelper::__translate('Hi'). " " 
        . $this->userDetails['firstName'];?>,
        </h1>
        <strong><?php echo FrontEnd_Helper_viewHelper::__translate('Welcome to your personal coupon page');?></strong>
    </div>
</div>
<div class="section">
    <div class="row">
    <?php echo $favouriteShopsOffers; ?>    
    </div>
</div>
