<?php
$signupViewPath = "favourite/";
$favouriteShopsOffers = $this->partial(
    $signupViewPath.'_favouriteShopsOffers.phtml',
    array(
       'favouriteShopsOffers'=> $this->favouriteShopsOffers,
   )
);
?>
<div class="header-block">
    <div class="icon icon-small">
        <div class='img-box'>i</div>
    </div>
    <div class="box">
        <h1>
        <?php echo FrontEnd_Helper_viewHelper::__translate('Hi'). " " 
        . $this->userDetails['firstName'];?>,
        </h1>
        <strong><?php echo FrontEnd_Helper_viewHelper::__translate('Welcome to your personal coupon page');?></strong>
    </div>
</div>
<div class="section">
    <div class="row">
    <?php echo $favouriteShopsOffers; ?>    
    </div>
</div>
