<?php
$favouriteViewPath = "favourite/";
$recordNotFound = '<div class = "no-record txt-center">' . $this->translate('No record found') .'</div>'; 
$popularShops = $recordNotFound;
if(!empty($this->popularShops)) :
    $popularShops = $this->partial(
        $favouriteViewPath . '_popularStores.phtml',
        array('popularShops' => $this->popularShops)
    );
endif;
$favouriteShops = $recordNotFound; 
if(!empty($this->favouriteShops)) :
    $favouriteShops = $this->partial(
        $favouriteViewPath . '_favouriteStores.phtml',
            array('favouriteShops' => $this->favouriteShops)
    );
endif;
$searchBrandForm = $this->form;
// Remove <dt> from label generation
foreach ($searchBrandForm->getElements() as $formElement) {
    $formElement->getDecorator('label')->setOption('tag', null);
}
if($this->successMessage!='' || $this->errorMessage!='') : ?>
    <div id="messageDiv" class="yellow-box-error-box-code myprofile-messagebox">
        <span class='glyphicon glyphicon-warning-sign'></span>
        <strong><?php echo $this->successMessage!='' ? $this->successMessage : $this->errorMessage;?></strong>
    </div>
    <?php 
endif;
?>
<div class="title-box">
    <h1>
        <?php
        $visitorFirstName = isset($this->userDetails['firstName']) ? $this->userDetails['firstName'] : '';
        echo $this->translate('Hey'). " " . $visitorFirstName;
        ?>
    </h1>
    <?php echo $this->translate('How are you? Let’s save some money for you!');?>
</div>
<div class="row">
    <div id="content" class="col-sm-8">
        <div class="section">
            <header class="heading">
                <div class="hold">
                    <?php 
                    if(count($this->favouriteShops) > 0) :
                        $messageWithAlreadyAddedBrand = 
                            $this->translate('You follow'). " " .count($this->favouriteShops) . " "
                            .$this->translate('brands already, that’s great.');
                        $messageAddMore = $this->translate('Why not add some more?');
                     else:
                        $messageWithAlreadyAddedBrand = 
                            $this->translate("You have not follow any brand from brands list");
                        $messageAddMore = $this->translate("Please seach and follow the brand");
                    endif;
                    ?>
                    <?php echo $messageWithAlreadyAddedBrand;?>
                    <span class="mark-text"><?php echo $messageAddMore;?></span>
                </div>
                <div class="search-area">
                    <form method="POST" role="form" class="search-form">
                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                        <div class="area">
                            <?php echo $searchBrandForm->searchBrand->renderViewHelper(); ?>
                        </div>
                    </form>
                </div>
            </header>
            <div class="row row-area">
            <?php echo $popularShops;?>
            </div>
        </div>
    </div>
    <aside id="sidebar" class="col-sm-4">
        <article class="block white">
            <header class="heading">
                <?php echo $this->translate('Brands you already follow.');?>
                <span class="mark-text"><?php echo $messageAddMore;?></span>
            </header>
            <div class="box-area">
            <?php echo $favouriteShops; ?>
            </div>
        </article>
    </aside>
</div>