<?php 
$this->headScript()->appendFile(PUBLIC_PATH . "/js/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/login.js");
// $this->headScript()->appendFile(PUBLIC_PATH . "/js/common.js");
?>
<form name="form1" action='' id="form1"  method="post">
	<div class="login-box-outer">
		<div class="login-logo">
	    	<img src="<?php echo PUBLIC_PATH?>images/back_end/imbull-login-logo.jpg" border="0" />
	    </div>
		<div class="login-box">
	    	<div class="login-box-heading"><?php echo $this->translate('CMS LOGIN');?></div>
	    	
	    	<div class='login-input error' id='error-msg' style = "height : 14px; margin-top: 15px; ">
	    	<?php
	    	  	echo $this->message;
	    	 	
	    	?></div>
	    	<div class="input-prepend login-input" >
	    	
	          	<span class="add-on"><i class="icon-user"></i></span><input type="text" maxlength="254" placeholder="<?php echo $this->translate("Username")?>" name="uname" id="uname" autofocus="autofocus" value="<?php if($this->personemail!='') echo $this->personemail;{?><?php }?>">
	          	
	        </div>
	        <div class="input-prepend login-input1">
	          <span class="add-on"><i class="icon-lock"></i></span><input type="password"  maxlength="20" placeholder="<?php echo $this->translate("Password")?>" name="pwd" id="pwd">
	        </div>
	        <div class="button-outer">
	
	        <button type="submit" name="button" id="button" class="btn btn-large btn-primary"><?php echo $this->translate('LOGIN');?></button>
					<a href="<?php echo HTTP_PATH;?>admin/auth/forgotpassword"><?php echo $this->translate('Forgot Password?');?></a>
					
	        </div>
	    </div>
	</div>
</form>