<?php 
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/datepicker.css" );
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "css/timepicker.css" );
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/addpage.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/bootbox.min.js");
$this->headScript ()->appendFile ( PUBLIC_PATH . "/js/jquery.NobleCount.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/jquery.textareaCounter.plugin.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/bootstrap-datepicker.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/bootstrap-timepicker.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/ckeditor/ckeditor.js");
$this->headScript ()->appendFile ( PUBLIC_PATH . "js/back_end/ckeditor/config.js" );
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/date.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/widget-location.js");
$publishDate = date('d-m-Y');
$publishHHM = date('H').':'.date('i');

$publishDateOrginal = $this->pageDetail['publishDate'];
$publishDateOrginal =  $publishDateOrginal->format('Y-m-d H:i:00');

 $currentTime = strtotime(date('d-m-Y H:i:00')); 
 $publishTime = strtotime($publishDateOrginal); 



  if(isset($this->pageDetail['publishDate']) && $publishDateOrginal!='0000-00-00 00:00:00'){
        $publishDateTime = explode(' ', $publishDateOrginal);
        $publishDate = date('d-m-Y',strtotime($publishDateTime[0]));
        $publishHHM =  explode(':',$publishDateTime[1]);
        $publishHHM = $publishHHM[0].':'.$publishHHM[1];
   }
  
   $status = $this->translate('Draft');
  if($this->pageDetail['publish']=='1'){
    
    if($publishTime>=$currentTime){
        $status = $this->translate('Scheduled');
       $publishText = $this->translate('Scheduled for:');   
    }else{
        $status = $this->translate('Published');
        $publishText = $this->translate('Published on:');
    }
  }else{
    if($publishTime>=$currentTime){
        $status = $this->translate('Draft');
        $publishText = $this->translate('Scheduled for:');
    }else{
        $status = $this->translate('Draft');
        $publishText = $this->translate('Published on:');
    }
  }
?>
<?php echo $this->headTitle()->append('Edit Page');?>
<script type="text/javascript">

var CKEDITOR_BASEPATH = "<?php echo PUBLIC_PATH . "js/back_end/ckeditor/" ; ?>" ;

</script>
<div class="wrap columns-2">
        
        
          <h1>
              <?php  echo $this->translate('Edit Page'); ?>
              <button type = "button" 
                  onClick="window.location.href='<?php echo HTTP_PATH;?>admin/page<?php echo '#'.$this->qstring; ?>'" 
                  class="btn ml10" ><?php echo $this->translate('Cancel'); ?>
              </button>
              <button type="button" class="btn btn-primary ml10" id='prefillData'>
                  <?php echo $this->translate('Pre-fill'); ?>
              </button>
              <button type = "button" onclick="showLightBoxForWidgetLocation()" class="btn ml10">
                  <?php echo $this->translate('backend_Set widget location'); ?>
              </button>
          </h1>
            <div class="btn-group mb20" data-toggle="buttons-checkbox">
                
                <button class="btn <?php if($this->pageDetail['pageType']=='default'){?>btn-primary <?php }?>" id="defaultPagebtn" onClick="selectPagetype('defaultPagebtn')"><?php echo $this->translate('Default Page'); ?></button>                     
                <button class="btn <?php if($this->pageDetail['pageType']=='offer'){?>btn-primary <?php }?>" id="offerListpageBtn" onClick="selectPagetype('offerListpageBtn')"><?php echo $this->translate('Offer List Page'); ?></button>
                
              </div>
           <form id="addPageform" name="addPageform" enctype="multipart/form-data" method="POST" action="<?php echo HTTP_PATH;?>admin/page/updatepage">
           <input type="hidden" value="<?php echo $this->role; ?>" name='role' id='role' />
           <input type="checkbox" <?php if($this->pageDetail['pageType']=='offer'){?>checked="checked"<?php }?> name="selectedpageType" value="1" id="selectedpageType" class="display-none">
            <input type="hidden" name='qString' id='qString' value='<?php echo $this->qstring; ?>' />
            <div class="metabox-holder has-right-sidebar" id="poststuff">
              <div class="inner-sidebar" id="side-info-column">
                <div class="meta-box-sortables ui-sortable" id="side-sortables">
                  <div class="postbox " id="submitdiv">
                    <div class="sidebar-heading">
                        <p><?php  echo $this->translate('Publish');  ?></p>
                    </div>
                    <div class="sidebar-content-box">
                        <button class="btn" type="submit" onClick="$('#savePage').val('draft')" href="#" id="saveDraftbtn" ><?php echo $this->translate('Save Draft'); ?></button>
                    </div>
                     <input type="hidden" name="savePagebtn" id="savePage" value="">
                    <div class="sidebar-content-box">
                        <?php echo $this->translate('Status:'); ?> <strong><?php echo $status; ?></strong>
                    </div>
                   <div class="sidebar-content-box">
                        <?php echo $publishText; ?> <?php echo $publishDateOrginal; ?> <strong><a href="javascript:;" onClick="showPublishDate()" id="editpublishLink"><?php echo $this->translate('Edit'); ?></a></strong>
                     <span id="publishlater" class="display-none">
                      <input type="text" style="width:110px;margin-top:3px;" value="<?php echo $publishDate;?>" placeholder="Publish Date" id="publishDate" name="publishDate" class="span3">
                      <input type="text" style="width:48px;margin-top:3px;" value = "<?php echo $publishHHM; ?>" placeholder="HH" id="publishTimehh" name="publishTimehh" class="span3">
                     </span>
                    </div>
                    
                    <div class="sidebar-box-footer">
                
                     <a  style="margin-top: 5px!important;" href ='javascript:void(0)' onClick='moveToTrash("<?php echo $this->pageDetail['id'] ?>")'  class="red trash-link" id="movetotrash"><?php echo $this->translate('Move to Trash')?></a>
                
                     <?php    if($this->pageDetail['publish']=='1'){ ?>
                    <button name="savePagebtn" onClick="$('#savePage').val('publish')" class="btn btn-primary fr" href="#" id="publishBtn"><?php echo $this->translate('Update'); ?></button><a class="fr m5" href="<?php echo HTTP_PATH;?>admin/page" id="publishcancelBtn"><?php echo $this->translate('Cancel'); ?></a>
                   <?php }else{?>
                   <button name="savePagebtn" onClick="$('#savePage').val('publish')" class="btn btn-primary fr" href="#" id="publishBtn"><?php echo $this->translate('Publish'); ?></button><a class="fr m5" href="<?php echo HTTP_PATH;?>admin/page" id="publishcancelBtn"><?php echo $this->translate('Cancel'); ?></a>
                   <?php }?>
                    </div>
                  </div>
                  
                  <div class="postbox " id="submitdiv">
                    <div class="sidebar-heading">
                        <p><?php echo $this->translate('Page Attributes');?></p>
                    </div>
                    <div class="sidebar-content-box">
                        <p><?php echo $this->translate('Template'); ?></p>
                        <select id="pageTemplate" name="pageTemplate" onchange="moneysavingtemp(this.value)" >
                            <option value=""><?php echo $this->translate('Select Template'); ?></option>
                            <?php
                            $display = 'block;';
                            foreach($this->pageAttributes as $pageattr){ 
                            if($this->pageDetail['pageType']=='offer' && $pageattr['id']>3) {
                                 $display = 'none;';
                            }
                            ?>
                             <option value="<?php echo $pageattr['id'];?>" style="display:<?php echo $display;?>" <?php if($this->pageDetail['page']['id']==$pageattr['id']){?>selected="selected" <?php }?>><?php echo $pageattr['name'];?></option>  
                        <?php    
                            } 

                          ?>
                            </select>
                           
          <div id="artcatg-div"   > 
             <?php
                $pagecatg = array();
                if (isset($this->pageDetail['moneysaving']) && is_array($this->pageDetail['moneysaving'])) {
                    foreach($this->pageDetail['moneysaving'] as $pageatrcatg){
                        $pagecatg[]= $pageatrcatg['categoryid'];
                    }
                }
             ?>  
                    <p><?php echo $this->translate('Article categories'); ?></p>
                <div class="web-address-list multiselect">
                    <ul style=" width: 217px;" >
                        <?php 
                        
                                               
                        foreach($this->artcategory as $atrcatg){ ?>
                            <li class="list_<?php echo $atrcatg['id']; if( count($this->pageDetail['moneysaving']) > 0 ){ if(in_array($atrcatg['id'],$pagecatg)){ echo ' selected'; } }?> " >
                                <input <?php if( count($this->pageDetail['moneysaving']) > 0 ){ if(in_array($atrcatg['id'],$pagecatg)){ ?>checked="checked"<?php } } ?>  type="checkbox"  name="artcatgs[]" value="<?php echo $atrcatg['id']; ?>" style="display:none;" />
                                <?php echo $atrcatg['name'];?>
                            </li>
                        <?php } ?>
                    </ul>
                </div>  
            </div>     
                 
                            
          </div>
                    
                    <div class="sidebar-content-box">
                        <p><?php echo $this->translate('Author');?></p>
                        <select id="pageAuthor" name="pageAuthor" onChange="setAuthorName()">
                            <option value=""><?php echo $this->translate('Select'); ?></option>
                            <?php foreach($this->authorList as $author ){ ?>
                           <option style="width:200px;" <?php if($this->pageDetail['contentManagerId']==$author['id']){?> selected="selected" <?php }?> title="<?php echo $author['fname'] . " " . $author['lname'];?>" value="<?php echo $author['id'];?>" ><?php echo $author['fname'] . " " . $author['lname']; ?></option>  
                            <?php }?>
                         </select>
                      <input type="hidden" name="selectedpageAuthorName" value="<?php echo $this->pageDetail['contentManagerName']; ?>" id="selectedpageAuthorName" value="">   
                    </div>
                
                 <?php if($this->roleId=='1' || $this->roleId=='2'){ ?>
                 <div class="sidebar-content-box">
                        <p><?php echo $this->translate('Lock Page'); ?></p>
                        <div data-toggle="buttons-checkbox" class="btn-group">
                            
                            <button  type="button" class="btn <?php if($this->pageDetail['pageLock']=='1'){?>btn-primary <?php }?>" id="lockbtnYes" onClick="lockPageStatus('lockbtnYes')" ><?php echo $this->translate('Yes');?></button>                     
                            <button style="border-radius:0 4px 4px 0;" type="button" class="btn <?php if($this->pageDetail['pageLock']!='1'){?>btn-primary <?php }?>" onClick="lockPageStatus('lockbtnNo')" id="lockbtnNo"><?php echo $this->translate('No'); ?></button>
                            <input type="checkbox" <?php if($this->pageDetail['pageLock']=='1'){?>checked="checked"<?php }?> name="lockPageStatuschk" class="display-none" id="lockPageStatuschk" value="1">
                         </div>
                    </div>
                     <div class="sidebar-content-box">
                        <p><?php echo $this->translate('Show Sitemap'); ?></p>
                        <div data-toggle="buttons-checkbox" class="btn-group">
                            <button  type="button" 
                                class="btn <?php if ($this->pageDetail['showsitemap']=='1') {?> btn-primary <?php }?>" 
                                id="showSitemapYes" onClick="showSitemapStatus('showSitemapYes')">
                                <?php echo $this->translate('Yes');?>
                            </button>                     
                            <button type="button"
                                class="btn borderradius4px <?php if ($this->pageDetail['showsitemap']!='1') {?>btn-primary <?php }?>"
                                onClick="showSitemapStatus('showSitemapNo')" id="showSitemapNo">
                                <?php echo $this->translate('No'); ?>
                            </button>
                            <input type="hidden"<?php if ($this->pageDetail['showsitemap']=='1') {?> checked="checked" <?php }?> 
                                name="showSitemapStatuscheck"  id="showSitemapStatuscheck" value="<?php echo $this->pageDetail['showsitemap']; ?>">
                         </div>
                    </div>

                    <div class="sidebar-content-box">
                        <p><?php echo $this->translate('Show In Mobile Menu'); ?></p>
                        <div data-toggle="buttons-checkbox" class="btn-group">
                            <button  type="button" 
                                class="btn <?php if ($this->pageDetail['showinmobilemenu']=='1') {?> btn-primary <?php }?>" 
                                id="showMobileMenuYes" onClick="showMobileMenuStatus('showMobileMenuYes')">
                                <?php echo $this->translate('Yes');?>
                            </button>                     
                            <button type="button"
                                class="btn borderradius4px <?php if ($this->pageDetail['showinmobilemenu']!='1') {?>btn-primary <?php }?>"
                                onClick="showMobileMenuStatus('showMobileMenuNo')" id="showMobileMenuNo">
                                <?php echo $this->translate('No'); ?>
                            </button>
                            <input type="hidden"<?php if ($this->pageDetail['showinmobilemenu']=='1') {?> checked="checked" <?php }?> 
                                name="showMobileMenuStatuscheck"  id="showMobileMenuStatuscheck" value="<?php echo $this->pageDetail['showinmobilemenu']; ?>">
                         </div>
                    </div>

                    <?php } ?>
                  </div>
                  <div class="postbox " id="submitdiv">
                    <div class="sidebar-heading">
                        <p><?php echo $this->translate('Sidebar');?></p>
                    </div>
                    <div class="sidebar-content-box" >
                        <div class="sidebar-content-box-left" style="overflow-y:scroll;height:50px;" id='storesDiv'>
                     
                         <ul id="widgetListul-li">
                            <?php 
                            $i=0;
                           
                            foreach($this->widgetList as $widgetList){
                            $widgetArry[]=$widgetList['id'];
                            $class = 'grid-line1';
                            if($i%2 != 0){
                            $class = 'grid-line2';
                            }
                            ?>
                            <li class="<?php echo $class; ?>" value="<?php echo $widgetList['id'];?>" type="<?php echo $i; ?>"><?php echo $widgetList['title'];?></li>
                            <?php 
                            $i++;
                            }?>
                          </ul> 
                         <input type="hidden" id="selectedWigetForPage" name="selectedWigetForPage" value="">
                       </div>
                        <div class="sidebar-content-box-right">
                            <button type = "button" class="btn addwidget" href="#"><?php echo $this->translate('Add Widgets'); ?></button>
                            <button type = "button" class="btn deletewidget" href="#"><?php echo $this->translate('Delete'); ?></button>
                            <button type = "button" class="btn up" href="#"><?php echo $this->translate('Move Up');?></button>
                            <button type = "button" class="btn down" href="#"><?php echo $this->translate('Move Down'); ?></button>
                        </div>
                        
                        <div id="widgetListUserdefined" class="display-none" >
                         <span class="error" id="selectWidgetError" style="padding: 50px;display:none;"><?php echo $this->translate('Please select widget'); ?></span>
                         <select id="widgetListUserdefinedSelect">
                         <option value=""><?php echo $this->translate('Select');?></option>
                         <?php   
                        foreach($this->widgetListUserDefined as $widgetList){ 
                         if(!in_array($widgetList['id'], $widgetArry)){
                            ?>
                         <option value="<?php echo $widgetList['id'];?>"  ><?php  echo $widgetList['title']; ?> </option>
                          <?php } 
                          
                          
                         }
                       /*  foreach($this->widgetList as $widgetList){ 
                         if(!in_array($widgetList['id'], $widgetArry)){
                            ?>
                         <option value="<?php echo $widgetList['id'];?>"  ><?php  echo $widgetList['title']; ?> </option>
                          <?php } 
                          
                          
                         } */?>  
                          </select>
                          <br><button type = "button" id="publishBtn" onClick="addWidget()" href="#" class="btn btn-primary fr" style="float:left;"><?php echo $this->translate('Add Widget'); ?></button>
                          &nbsp;&nbsp;<button type="button" type = "button" onClick="hideWidget();" class="btn ml10" href="#"><?php echo $this->translate('Cancel');?></button>
                        </div>
                    </div>
                  </div>
                </div>
              </div>
              <div id="post-body">
                <div id="post-body-content">
                    <div class="mainpage-content">
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Page title'); ?></strong></label></div>
                            <div class="mainpage-content-right"><input type="text" value="<?php echo $this->pageDetail['pageTitle']; ?>" name="pageTitle" id="pageTitle" class="span3" placeholder="<?php echo $this->translate('Page title'); ?>"></div>
                            <div class="mainpage-content-right" style="height : 20px;"></div>
                        </div>
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left">
                                <label>
                                    <strong><?php echo $this->translate('backend_Page subtitle'); ?></strong>
                                </label>
                            </div>
                            <div class="mainpage-content-right">
                                <input type="text" value="<?php echo $this->pageDetail['subtitle']; ?>"
                                    name="subtitle" id="subtitle" class="span3"
                                    placeholder="<?php echo $this->translate('backend_Page subtitle'); ?>">
                            </div>
                            <div class="mainpage-content-right" style="height : 20px;"></div>
                        </div>
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Permalink'); ?></strong></label></div>
                            <div class="mainpage-content-right"><div class="mainpage-content-right-inner-left"><label><?php echo $this->translate('http://www.kortingscode.nl/'); ?></label></div><div class="mainpage-content-right-inner-right"><input <?php echo ($this->role == '3' || $this->role == '4') ? "disabled=disabled" : "" ;  ?> type="text" class="span3" value="<?php echo $this->pageDetail['permalink']; ?>" name="pagepermalink" id="pagepermalink" placeholder="<?php echo $this->translate('permalink'); ?>"></div>
                            <?php if($this->role == '3' || $this->role == '4'){ ?>
                                <input type="hidden" value="<?php echo $this->pageDetail['permaLink']?>" name="pagepermalink" id="pagepermalink">
                            <?php }?>   
                            <div class="mainpage-content-right" style="float:left;margin:-9px 0 6px 0; height : 20px; width : 511px;"></div> 
                            </div>
                          </div>

                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left">
                                <label><strong><?php echo $this->translate('Thumbnail'); ?></strong></label>
                            </div>
                            <div class="mainpage-content-right">
                                <?php 
                                $pageImage = '';
                                if($this->pageDetail['logo']) {
                                    if(
                                        isset($this->pageDetail['logo']['name']) 
                                        && $this->pageDetail['logo']['name']!=''
                                    ) {
                                        $pageImage = PUBLIC_PATH_CDN.$this->pageDetail['logo']['path']
                                        .$this->pageDetail['logo']['name'];
                                    }
                                ?>
                                <div class='browse-container'>    
                                    <img class='image-container' src="<?php echo $pageImage;?>"  
                                    alt="pageLogo" align="top">
                                    <a  class="red" 
                                    onclick="deleteImage(<?php echo $this->pageDetail['logo']['id']; ?>,
                                    <?php echo $this->pageDetail['id']; ?>)" 
                                    href="javascript:void(0);" id="deleteButton">
                                    <strong><?php echo $this->translate('DELETE');?></strong>
                                    </a>
                                </div>
                                <?php }?>
                                <div class="mainpage-content-right-inner-left-other">
                                    <div>
                                        <input type="file" 
                                        onchange="checkFileType(event)" class="ignore" 
                                        name="logoFile" id="pageImage">
                                    </div>
                                    <div>
                                    <?php echo $this->translate('Image Size: 175px x 175px (*.jpg or *.png file only)'); ?>
                                    </div>
                                    <div 
                                    class="mainpage-content-right"
                                    id="imagerrorDiv" 
                                    style="float:left;margin:-9px 0 6px 0; height : 20px; width : 511px;">  
                                    </div> 
                                </div>
                            </div>
                        </div>  

                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left">
                                <label><strong><?php echo $this->translate('Header Image'); ?></strong></label>
                            </div>
                            <div class="mainpage-content-right">
                                <?php 
                                $headerImage = '';
                                if($this->pageDetail['pageHeaderImageId']) {
                                    if(
                                        isset($this->pageDetail['pageHeaderImageId']['name']) 
                                        && $this->pageDetail['pageHeaderImageId']['name']!=''
                                    ) {
                                    $headerImage = PUBLIC_PATH_CDN.$this->pageDetail['pageHeaderImageId']['path']
                                    .$this->pageDetail['pageHeaderImageId']['name'];
                                }
                                ?>
                                <div class='browse-container'>    
                                    <img class='image-container'  src="<?php echo $headerImage;?>"  
                                    alt="pageHeaderImage" align="top">
                                    <a  class="red" 
                                    onclick="deleteImage(<?php echo $this->pageDetail['pageHeaderImageId']['id']; ?>,
                                    <?php echo $this->pageDetail['id']; ?>)" 
                                    href="javascript:void(0);" id="deleteButton">
                                    <strong><?php echo $this->translate('DELETE');?></strong>
                                    </a>
                                </div>
                                <?php }?>
                                <div class="mainpage-content-right-inner-left-other">
                                    <div>
                                        <input type="file" 
                                        onchange="checkFileType(event)" class="ignore" 
                                        name="headerFile" id="pageHeaderImage">
                                    </div>
                                    <div>
                                    <?php echo $this->translate('Image Size: 1170px x 304px (*.jpg or *.png file only)'); ?>
                                    </div>
                                    <div class="mainpage-content-right" id="imagerrorDiv" 
                                    style="float:left;margin:-9px 0 6px 0; height : 20px; width : 511px;">
                                    </div> 
                                </div>
                            </div> 
                        </div>


                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left">
                                <label><strong><?php echo $this->translate('Home Page Image'); ?></strong></label>
                            </div>
                            <div class="mainpage-content-right">
                                <?php 
                                $homepageimage = '';
                                if($this->pageDetail['homepageimage']) {
                                    if(
                                        isset($this->pageDetail['homepageimage']['name']) 
                                        && $this->pageDetail['homepageimage']['name']!=''
                                    ) {
                                    $homepageimage = PUBLIC_PATH_CDN.$this->pageDetail['homepageimage']['path']
                                    .$this->pageDetail['homepageimage']['name'];
                                }
                                ?>
                                <div class='browse-container'>    
                                    <img class='image-container'  src="<?php echo $homepageimage;?>"  
                                    alt="homepageImage" align="top">
                                    <a  class="red" 
                                    onclick="deleteImage(<?php echo $this->pageDetail['homepageimage']['id']; ?>,
                                    <?php echo $this->pageDetail['id']; ?>)" 
                                    href="javascript:void(0);" id="deleteButton">
                                    <strong><?php echo $this->translate('DELETE');?></strong>
                                    </a>
                                </div>
                                <?php }?>
                                <div class="mainpage-content-right-inner-left-other">
                                    <div>
                                        <input type="file" 
                                        onchange="checkFileType(event)" class="ignore" 
                                        name="homepageFile" id="homepageImage">
                                    </div>
                                    <div>
                                    <?php echo $this->translate('Image Size: 70px x 70px (*.jpg or *.png file only)'); ?>
                                    </div>
                                    <div class="mainpage-content-right" id="imagerrorDiv" 
                                    style="float:left;margin:-9px 0 6px 0; height : 20px; width : 511px;">
                                    </div> 
                                </div>
                            </div> 
                        </div>

                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Meta title'); ?></strong></label></div>
                            <div class="mainpage-content-right"><input type="text" name="pagemetaTitle" id="pagemetaTitle" placeholder="<?php echo $this->translate('Meta title');?>" class="input-xlarge mbot bbot ignore" value="<?php echo $this->pageDetail['metaTitle']; ?>"/>
                            <span id="metaTextLeft" class="input-xlarge disabled btop word-count nobel wordcount-width"></span>
                            <!--<input type="text" class="span3" placeholder="<?php //echo $this->translate('Meta Title'); ?>" maxlength="68" value="<?php //echo $this->pageDetail['metaTitle']; ?>" name="pagemetaTitle" id="pagemetaTitle"></div>-->
                            </div>
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Meta Description'); ?></strong></label></div>
                            <div class="mainpage-content-right"><textarea class="input-xlarge mbot bbot ignore" id="pagemetaDesc" name="pagemetaDesc" placeholder="<?php echo $this->translate ( 'Meta Description' );?>" rows="3"><?php echo $this->pageDetail['metaDescription']; ?></textarea>
                            <span id="metaDescLeft" class="input-xlarge disabled btop word-count nobel wordcount-width"></span>
                            <!--<textarea class="input-xlarge mbot bbot ignore" name="pagemetaDesc" id="pagemetaDesc" placeholder="<?php //echo $this->translate('Meta Description'); ?>"  maxlength="150" rows="3"><?php //echo $this->pageDetail['metaDescription']; ?></textarea>
                            <input type="text" class="input-xlarge disabled btop word-count"  id="metaTextLeft" value = "Characters Left: 160" placeholder="Word Count: 28" disabled="disabled">-->
                            </div>
                        </div>
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Custom Header Text'); ?></strong></label></div>
                            <div class="mainpage-content-right"><textarea class="input-xlarge mbot bbot ignore" id="pageCustomHeader" name="pageCustomHeader" placeholder="<?php echo $this->translate ( 'Custom Header Text' );?>" rows="3"><?php echo $this->pageDetail['customHeader']; ?></textarea>
                            <input type="text" disabled="disabled" value="<?php echo $this->translate("Page custom header length ").strlen($this->pageDetail['customHeader']). $this->translate(' characters');?>" id="pageCustomHeaderLeft" class="input-xlarge disabled btop word-count">
                            </div>
                        </div>
                    </div>
                    </div>
                   
                <div id="mainpage-content">    
                	<textarea class="input-xlarge" name="pageDesc" id="pageDesc" placeholder="<?php echo $this->translate('Page Description'); ?>" rows="3"><?php echo htmlspecialchars($this->pageDetail['content']); ?></textarea>
                </div>  
                <br><div id="offerconstraint" <?php if($this->pageDetail['pageType']=='default'){?>class="display-none" <?php }?>> 
                   
                <div class="mainpage-content">
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Maximum Offers on Page'); ?></strong></label></div>
                            <div class="mainpage-content-right"><input type="text" name="maxOffer" value="<?php echo $this->pageDetail['maxOffers']; ?>" id="maxOffer" class="span3" placeholder="<?php echo $this->translate('Maximum Offer'); ?>"></div>
                        </div>
                        <div class="mainpage-content-line">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Offers Order'); ?></strong></label></div>
                           <div class="btn-group" data-toggle="buttons-checkbox">
                                        <button type="button" onClick="setOffersOrder('ascendingOffer')" id="ascendingOffer" class="btn <?php if($this->pageDetail['oderOffers']==1){?>btn-primary <?php }?>">ascending</button>                     
                                        <button type="button" onClick="setOffersOrder('decendingOffer')" id="decendingOffer" class="btn <?php if($this->pageDetail['oderOffers']==0){?>btn-primary <?php }?>">descending</button>
                                        <input type="checkbox" id="offersOrderchk" value="1" name="offersOrderchk" checked="checked" class="display-none">
                            </div>
                        </div>
                 </div>
                    <div class="edit-page-box-new">
                        <div class="mainpage-content-line">
                            <label class="checkbox">
                                <input type="checkbox" value="1" <?php if($this->pageDetail['enableTimeConstraint']=='1'){?>checked="checked"<?php }?> onClick="constraint(event,'time')" id="timeCostraintchk" name="timeCostraintchk"> <strong><?php echo $this->translate('Enable time Constraint');?></strong>
                            </label>
                            <div class="line"></div>
                            <div class="edit-page-feilds <?php if($this->pageDetail['enableTimeConstraint']!='1'){?> display-none <?php }?>" id="showTimeConstraint">
                                <div class="fl">
                                <select id="postwithin" name="postwithin">
                                    <option value="1" <?php if($this->pageDetail['timeType']=='1'){?> selected="selected" <?php }?>><?php echo $this->translate('Posted within'); ?></option>
                                    <option value="2" <?php if($this->pageDetail['timeType']=='2'){?> selected="selected" <?php }?>><?php echo $this->translate('Expires in'); ?></option>
                                 </select>
                                </div>
                                <div class="fl ml15">
                                    <input type="text" id="numberofDays" value="<?php echo $this->pageDetail['timenumberOfDays']; ?>" name="numberofDays"  class="span1 ml15" placeholder="10">                                   
                                </div>
                                <div class="fl ml15">                                  
                                    <p class="mr15"><?php echo $this->translate('Days'); ?></p>
                                </div>
                               
                            </div>
                        </div>
                        
                        </div>
                        <div class="edit-page-box-new">
                            <div class="mainpage-content-line">
                                <label class="checkbox">
                                    <input type="checkbox" value="1" <?php if($this->pageDetail['enableWordConstraint']=='1'){?>checked="checked"<?php }?> onClick="constraint(event,'word')" id="wordCostraintchk" name="wordCostraintchk"> <strong><?php echo $this->translate('Word constraint'); ?></strong>
                                </label>
                                <div class="line"></div>
                                <div class="edit-page-feilds <?php if($this->pageDetail['enableWordConstraint']!='1'){?> display-none <?php }?>" id="wordConstraint">
                                    <div class="fl mr15">
                                    <input type="text" id="wordConstraintTxt" value="<?php echo $this->pageDetail['wordTitle']; ?>" name = "wordConstraintTxt" class="span5" placeholder="<?php echo $this->translate('Word Constraint'); ?>"> 
                                    </div>                                
                                 </div>
                            </div>                        
                        </div>
                        
                        <div class="edit-page-box-new">
                            <div class="mainpage-content-line">
                                <label class="checkbox">
                                    <input type="checkbox" <?php if($this->pageDetail['awardConstratint']=='1'){?>checked="checked"<?php }?> value="1" onClick="constraint(event,'award')" id="awardCostraintchk" name="awardCostraintchk" > <strong><?php echo $this->translate('Awards');?></strong>
                                </label>
                                <div class="line"></div>
                                <div class="edit-page-feilds <?php if($this->pageDetail['awardConstratint']!='1'){?> display-none <?php }?>" id="awardConstraint">
                                    <div class="fl mr15">
                                        <select id="select02" id="awardConstraintDropdown" name="awardConstraintDropdown">
                                            <option value="1" <?php if($this->pageDetail['awardType']=='1'){?> selected="selected" <?php }?>><?php echo $this->translate('Free shipping'); ?></option>
                                            <option value="2" <?php if($this->pageDetail['awardType']=='2'){?> selected="selected" <?php }?>><?php echo $this->translate('Order today,delivered tomorrow'); ?></option>
                                        </select>                                        
                                    </div>                                
                                 </div>
                            </div>                        
                        </div>
                        
                        <div class="edit-page-box-new">
                            <div class="mainpage-content-line">
                                <label class="checkbox">
                                    <input type="checkbox" <?php if($this->pageDetail['enableClickConstraint']=='1'){?>checked="checked"<?php }?> value="1" onClick="constraint(event,'clicks')" id="clickCostraintchk" name="clickCostraintchk"> <strong><?php echo $this->translate('Clickouts'); ?></strong>
                                </label>
                                <div class="line"></div>
                                <div class="edit-page-feilds <?php if($this->pageDetail['enableClickConstraint']!='1'){?> display-none <?php }?>" id="clickConstraint">
                                    <div class="fl mr15">
                                    <input id="clickConstraintTxt" value="<?php echo $this->pageDetail['numberOfClicks']; ?>" name="clickConstraintTxt" type="text" class="span3" placeholder="<?php echo $this->translate('Clickouts'); ?>"> 
                                    </div>
                                    <div class="fl">
                                        <p class="mr15"><?php echo $this->translate('Of clickouts'); ?></p>
                                    </div>                                
                                 </div>
                            </div>                        
                        </div>
                <div class="mainpage-content">
                        <strong><?php echo $this->translate('Show offer types'); ?></strong>                               
                        <div class="line"></div>
                        <div class="mainpage-content-line mb10">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Coupon'); ?></strong></label></div>
                            <div class="mainpage-content-right">
                                <div class="btn-group" data-toggle="buttons-checkbox">
                                    <button id="regularCoupon" onClick="offerType('regularCoupon','coupon','regular')" type = "button" class="btn <?php if($this->pageDetail['couponRegular']=='1'){?> btn-primary <?php }?>"><?php echo $this->translate('Regular');?></button>                     
                                    <button id="editorPickCoupon" onClick="offerType('editorPickCoupon','coupon','editor')" type = "button" class="btn <?php if($this->pageDetail['couponEditorPick']=='1'){?> btn-primary <?php }?>"><?php echo $this->translate('Editors pick'); ?></button>
                                    <button id="exclusiveCoupon" onClick="offerType('exclusiveCoupon','coupon','exclusive')" type = "button" class="btn <?php if($this->pageDetail['couponExclusive']=='1'){?> btn-primary <?php }?>"><?php echo $this->translate('Exclusive'); ?></button>
                                  </div>
                                  <input type="checkbox" <?php if($this->pageDetail['couponRegular']=='1'){?> checked="checked" <?php }?> id="coupconCoderegularchk" name="coupconCoderegularchk" value="1" class="display-none"> 
                                  <input type="checkbox" <?php if($this->pageDetail['couponEditorPick']=='1'){?> checked="checked" <?php }?> id="coupconCodeeditorchk" name="coupconCodeeditorchk" value="1" class="display-none"> 
                                  <input type="checkbox" <?php if($this->pageDetail['couponExclusive']=='1'){?> checked="checked" <?php }?> id="coupconCodeeclusivechk" name="coupconCodeeclusivechk" value="1" class="display-none"> 
                            </div>
                        </div>
                        <?php /* ?>
                        <div class="mainpage-content-line mb10">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Sale'); ?></strong></label></div>
                            <div class="mainpage-content-right">
                                <div class="btn-group" data-toggle="buttons-checkbox">
                                    <button id="regularSale" type = "button" onClick="offerType('regularSale','sale','regular')" class="btn <?php if($this->pageDetail['saleRegular']=='1'){?> btn-primary <?php }?>"><?php echo $this->translate('Regular'); ?></button>                     
                                    <button id="editorPickSale" type = "button" onClick="offerType('editorPickSale','sale','editor')" class="btn <?php if($this->pageDetail['saleEditorPick']=='1'){?> btn-primary <?php }?>"><?php echo $this->translate('Editors pick'); ?></button>
                                    <button id="exclusiveSale" type = "button" onClick="offerType('exclusiveSale','sale','exclusive')" class="btn <?php if($this->pageDetail['saleExclusive']=='1'){?> btn-primary <?php }?>"><?php echo $this->translate('Exclusive'); ?></button>
                                  </div>
                                   <input type="checkbox" id="saleregularchk" <?php if($this->pageDetail['saleRegular']=='1'){?> checked="checked" <?php }?> name="saleregularchk" value="1" class="display-none"> 
                                   <input type="checkbox" id="saleeditorchk" <?php if($this->pageDetail['saleEditorPick']=='1'){?> checked="checked" <?php }?> name="saleeditorchk" value="1" class="display-none"> 
                                  <input type="checkbox" id="saleeclusivechk" <?php if($this->pageDetail['saleExclusive']=='1'){?> checked="checked" <?php }?> name="saleeclusivechk" value="1" class="display-none">
                            </div>
                        </div>
                         <div class="mainpage-content-line mb10">
                            <div class="mainpage-content-left"><label><strong><?php echo $this->translate('Printable'); ?></strong></label></div>
                            <div class="mainpage-content-right">
                                <div class="btn-group" data-toggle="buttons-checkbox">
                                    <button id="regularPrintable" type = "button" onClick="offerType('regularPrintable','printable','regular')" class="btn <?php if($this->pageDetail['printableRegular']=='1'){?> btn-primary <?php }?>"><?php echo $this->translate('Regular');?></button>                     
                                    <button id="editorPickPrintable" type = "button" onClick="offerType('editorPickPrintable','printable','editor')" class="btn <?php if($this->pageDetail['printableEditorPick']=='1'){?> btn-primary <?php }?>"><?php echo $this->translate('Editors pick'); ?></button>
                                    <button id="exclusivePrintable" type = "button" onClick="offerType('exclusivePrintable','printable','exclusive')" class="btn <?php if($this->pageDetail['printableExclusive']=='1'){?> btn-primary <?php }?>"><?php echo $this->translate('Exclusive');?></button>
                                  </div>
                                   <input type="checkbox" id="printableregularchk" name="printableregularchk" <?php if($this->pageDetail['printableRegular']=='1'){?> checked="checked" <?php }?> value="1" class="display-none"> 
                                   <input type="checkbox" id="printableeditorchk" name="printableeditorchk"  <?php if($this->pageDetail['printableEditorPick']=='1'){?> checked="checked" <?php }?> value="1" class="display-none"> 
                                   <input type="checkbox" id="printableexclusivechk" name="printableexclusivechk" <?php if($this->pageDetail['printableExclusive']=='1'){?> checked="checked" <?php }?> value="1" class="display-none">
                            </div>
                        </div>  
                        <?php */ ?>                      
                    </div>
                    
                    
                    <div style="height:28px;" class="mainpage-content">
                        <div class="mainpage-content-line m10">
                            <div class="fl">
                                <strong><?php echo $this->translate('Show as page when creating offers?'); ?></strong>
                            </div>
                            <label class="checkbox fl ml15">
                                 <input type="radio" name="showPage" value = "1" <?php if($this->pageDetail['showPage']=='1'){?> checked="checked" <?php }?>> <?php echo $this->translate('Yes'); ?>
                            </label>
                            <label class="checkbox fl ml15">
                                 <input type="radio" name="showPage" value = "0" <?php if($this->pageDetail['showPage']!='1'){?> checked="checked" <?php }?>> <?php echo $this->translate('No'); ?>
                            </label>                           
                        </div>                        
                     </div> 
                 </div>                    
                        
                        
                        
                    </div>
                </div>
              </div>
              <input type="hidden" name="pageId" id="pageId" value="<?php echo $this->pageId; ?>" >
            </form>  
              <br class="clear">
</div>
<?php 
$pageId = !empty($this->pageDetail['id']) ? $this->pageDetail['id'] : '';
echo $this->partial('widgetlocation/_widget-location.phtml', array('pageType' => 'page', 'relatedId' => $pageId));
?>