<div style="margin:0; padding:0; background-color:#f0f0f0">
<table width="100%" cellspacing="0" cellpadding="0" bgcolor="#f0f0f0">
<tbody>
    <?php if (isset($data['header_text']) && !empty($data['header_text'])) { ?>
    <tr>
        <td bgcolor="#32383e" align="center" style="padding:12px 0 15px; font:12px/14px Arial,Helvetica,sans-serif; color:#fffefe">
            <?php echo $data['header_text']; ?>
        </td>
    </tr>
    <?php } ?>
    <tr>
        <td>
        <table width="100%" cellpadding="0" cellspacing="0">
            <tbody>
            <tr>
                <td valign="top" width="50%">
                    <table width="100%" cellpadding="0" cellspacing="0">
                        <tbody>
                        <tr>
                            <td height="140" bgcolor="#0077cc">&nbsp;</td>
                        </tr>
                        </tbody>
                    </table>
                </td>
                <td valign="top" width="600">
                    <div>
                    <table width="100%" cellpadding="0" cellspacing="0">
                        <tbody>
                        <tr>
                            <td>
                             <table width="100%" align="center" cellpadding="0" cellspacing="0">
                                <tbody>
                                <?php echo $data['header']; ?>
                                <?php echo $data['content']; ?>
                        </tbody>
                        </table>
                    </td>
                    </tr>
                </tbody>
                </table>
            </div>
            </td>
            <td valign="top" width="50%">
                <table width="100%" cellpadding="0" cellspacing="0" bgcolor="#0077cc">
                    <tbody>
                    <tr>
                        <td height="140" bgcolor="#0077cc" style="">&nbsp;</td>
                    </tr>
                    </tbody>
                </table>
            </td>
        </tr>
    </tbody>
    </table>
    </td>
    </tr>
</tbody>
</table>
<?php echo $data['footer']; ?>