<?php
$numOfShops = 0;
$mobileClass = '';
foreach ($this->popularShops as $popularShop) :
    if ($numOfShops >= $this->numOfPopularShopsVisibleOnMobile) :
        $mobileClass = 'hidden-xs';
    endif;
    $shopImage = PUBLIC_PATH_CDN.ltrim($popularShop['imgpath'], "/")
        .  "thum_big_" . $popularShop['imgname'];
    ?>
    <article class="block col-sm-6 col-xs-6 <?php echo $mobileClass; ?>">
        <div class="text-holder">
            <div class="text-holder">
                <a href="<?php echo $popularShop['permaLink']; ?>" class="img-ico">
                    <img width="132" src="<?php echo $shopImage; ?>" 
                    alt="<?php echo $popularShop['name']; ?>" title="<?php echo $popularShop['name']; ?>" >
                </a>
                <div class="text">
                    <a href="<?php echo HTTP_PATH_LOCALE. $popularShop["permaLink"];?>" class="link">
                        <?php echo $popularShop['name']; ?>
                    </a>
                    <p>
                        <?php 
                        if($popularShop['activeCount'] > 0):
                            ?>
                            <a href="<?php echo HTTP_PATH_LOCALE. $popularShop["permaLink"];?>" 
                            class="active-offer">
                            <?php echo $popularShop['activeCount'] . " "  .$this->translate('active offers');?>
                            </a>
                        <?php
                        else:
                            echo "&nbsp;";
                        endif;
                        ?>
                    </p>
                    <a
                    href='<?php echo HTTP_PATH_LOCALE. 'store/addtofavourite?permalink='
                    . FrontEnd_Helper_viewHelper::__link('link_mijn-favorieten') .'&shopId='
                    . base64_encode($popularShop['id']);?>'>
                        <button class="pop btn btn-default" type="button">
                            <span class="glyphicon glyphicon-heart"></span>
                            <span class='follow-text'><?php echo $this->translate('love');?></span>
                        </button>
                    </a>
                </div>
            </div>
        </div>
    </article>
    <?php
    $numOfShops++;
endforeach;