<?php 
$this->headTitle()->append($this->translate('Robot File Management'));
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/jquery.validate.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/back_end/robot-management.js");
$this->headScript()->appendFile(PUBLIC_PATH . "js/back_end/select2.min.js");
?>
<div class="wrap columns-2" id="addNewKeyword">
    <?php
        if ($this->messageSuccess!='' || $this->messageError!='' ) {?>
           <br>
            <div class ="mainpage-content-colorbox success">
                <?php if ($this->messageSuccess!='') { ?>
                        <span class="successserver"><?php echo $this->messageSuccess; ?></span>
                <?php } if ($this->messageError!='') { ?>
                            <span class="errorserver"><?php echo $this->messageError; ?></span>
                <?php } ?>
            </div>
    <?php } ?>
        
    <h1><?php echo $this->translate('Update Robot file'); ?>
        <button class="btn ml10" type="button" onClick="window.location.href='<?php echo HTTP_PATH ;?>admin/robot'">
                <?php echo $this->translate('Cancel'); ?>
        </button>
    </h1>
    <form method="post" id="updateRobotForm" action="<?php echo HTTP_PATH ;?>admin/robot/updaterobotcontent" >
        <div class="mainpage-content mb300">
            <div class="mainpage-content-line mb10">
                <div class="mainpage-content-left">
                    <label><strong><?php echo $this->translate('Website'); ?></strong></label>
                </div>
                <div class="mainpage-content-right oveflow-hidden">
                    <div class="mainpage-content-right-inner-left-other fl oh">
                        <select name ="website" id='website' class='select-width' onchange="getContent(this);" >
                            <option selected="selected" disabled="disabled" value="0">
                                <?php echo $this->translate('Select Website');?>
                            </option>       
                                <option value="1">Flipit</option>
                                <option value="2">Kortingscode</option>      
                        </select>
                    </div>
                    <div class="mainpage-content-right-inner-right-other focus error">
                        <span for="locale" class="error help-inline"></span>
                    </div>
                </div>
            </div>
            <div class="mainpage-content-line mb10" id = "robotContent" style = "display:none;">
                <div class="mainpage-content-left">
                    <label>
                        <strong><?php echo $this->translate('Robot File Content'); ?></strong>
                    </label>
                </div>
                <div class="mainpage-content-right">
                    <textarea name = "content" rows = "10" cols = "7" id="fileContent"></textarea> 
                    <div class="clear"></div>
                </div>
            </div>
            <div class="clear"></div>
            <div class="mainpage-content-colorbox" id = "updateButton" style = "display:none;">
                <button id="updateseenIdButton" type="submit" class="btn btn-large btn-primary fl" value="" name="form">
                    <?php echo $this->translate('Update File'); ?>
                </button>
                <a class="fl m10" href="<?php echo HTTP_PATH ;?>admin/robot">
                    <strong><?php echo $this->translate('CANCEL'); ?></strong>
                </a>
            </div>
        </div>
    </form> 
</div>