<?php  
$articleview = $this->articleview;
$userview = $this->udetails;
if(!empty($articleview)) :
	 $this->minifyHeadScript()->prependFile (HTTP_PATH."public/js/front_end/moneysaving.js" );
     
	 $headerSearch = new FrontEnd_Helper_viewHelper(); 
     $page = $this->page;
     $breadcrumb = "<a href='".HTTP_PATH_LOCALE."plus' style='color:#6a6a6a'>".$this->translate('Bespaar Wijzer')."</a>";
  	 $headerSearch = new FrontEnd_Helper_viewHelper(); 
	 echo $this->partial('partials/_headerSearch.phtml',array('breadcrumb' => $breadcrumb));
	 
	
?> 
<style>
.img-radius{
-webkit-border-radius: 5px;
-moz-border-radius: 5px;
border-radius: 5px;

}
</style>

        <!-- Guide Outer Starts -->
        <div class="new-outer">
        <div class="guide-outer-new">
        
          <!-- plus Left Starts -->
        	<div>
            	<div class="plus-left-heading">
            	  <h1><strong><?php echo $articleview['title'];  ?></strong></h1>
                  <!-- <p class="mt5">Comparison and tips for all tariffs including iPhone 4S</p> -->
                  <h4 class="mt10"><?php echo $this->translate('Written by'); ?> <span class="text-blue"><?php echo @$articleview['authorname'];?></span></h4>
            	</div>
                <div>
                	<?php
	          			$url = "http://www.kortingscode.nl/"; 
	          			$title = "";
	          			$socialMedia = new FrontEnd_Helper_viewHelper();
	       	  			echo $socialMedia->socialMediaWidget($url, $title,'moneysavingguide');
       				?>
                </div>
               <!-- Separator Starts -->
		        <div class="separator mt10">&nbsp;</div>
		        <!-- Separator Ends -->
              <!-- plus Right Starts -->
          <div class="fl">	
          	<!-- Last Update Starts -->
            	<div class="last-update">
                	  
                    <p class="mt10"><strong>
                    	
                    	<?php 
                    	      $img = HTTP_PATH ."public/images/front_end/guide-cal.png";
                    		  $update = strtotime($articleview['updated_at']);
                    		  $udate = date('d M Y', $update);
                			  echo $udate;
                			  
                			  
                		?>
                		<img src="<?php echo $img; ?>" border="0" class="fl" />
                	</strong></p>
                   
                     <!--<h6 class="mt15"><?php //echo $this->translate('Edited by'); ?>: <?php //echo $articleview['authorname'];?> </h6>-->
       	      </div>
              <!-- Last Update Ends -->
              

          </div>
          <!-- plus Right Ends -->
            
            
              <!-- Quick Outer Starts -->
             <div class="guide-chantal-left">
                	<?php  	
						  	$img = PUBLIC_PATH_CDN.$articleview['articleImage']['path'].$articleview['articleImage']['name'];
						
                   ?>
                      	<img src="<?php echo $img; ?>" class="img-radius"/>
                	
            </div>
			
			
			
          <!-- Quick Outer Ends -->  
          
            
            
          </div>
          <!-- plus Left Ends -->
          <div class="ct-content-outer">
            <div class="guide-content-new">
            	<div class="guide-chantal-right-bot">
		            <?php  
		           //$description = strip_tags($articleview['content'],$allowed_tags);
		           // $countChar = substr_count($description, 0);
		            echo $articleview['content']; ?> 
		        </div>
            
            </div>
            <div class="guide-content-new-right-scroll">
            	<h4>Ga Naar Hoofdstuk</h4>
            	<ul>
            		<li><h5><a href="javascript:;">Goedkoopste abonnementen</a></h5></li>
            		<li><h5><a href="javascript:;">Goedkoopste abonnementen</a></h5></li>
            		<li><h5><a href="javascript:;">Goedkoopste abonnementen</a></h5></li>
            	</ul>
            	<div class="side-cor"></div>
            </div>
           </div>
            
        </div>
        </div>
        <!-- Guide Outer Ends -->
        
       
        
        <!-- Guide Outer Starts -->
        <div class="new-outer">
          <div class="guide-outer">
          	 
             <!-- Guide Outer Left Starts -->
    		  <div class="guide-outer-left">
                  	 <!-- Guide Left Common Ends -->
                     
                              <!-- Separator Starts -->
        		  <div class="separator mt20">&nbsp;</div>
      			  <!-- Separator Ends -->
                  
                  
                        <!-- About Col1 Starts -->
                    	<div class="about-col1 bg-none mt20 bdr-none p-none">
                        	<div class="white-box2">
                        	
                        		<img src="<?php echo $img; ?>" style="width: 120px;height: 91px;" />
                        	
                        	</div>
                            <div class="about-col1-right ml15">
                            	<div class="about-col1-heading text-black">
                            	  <h3><strong><?php echo @$userview['firstName'];?></strong>
                            	  <?php 
                            	  $view = new Zend_View();
                            	  $view->setScriptPath(APPLICATION_PATH . '/views/scripts/');
                            	  echo $view->render('partials/deal.phtml');
                            	  ?>
                            	  <?php /*<img src="<?php echo HTTP_PATH; ?>public/images/front_end/btn-deal-guru.png" width="68" height="19" hspace="10" align="absmiddle" />*/?>
                            	  
                            	  </h3>
                            	</div>
                            	<div class="about-col1-para text-black"><?php if(@$userview['mainText'] != ''){ echo @$userview['mainText']; }else{ echo "N/A"; }  ?></div>
                            </div>
                        </div>
                        <!-- About Col1 Ends -->
                        
                         <!-- Separator Starts -->
        		  <div class="separator ">&nbsp;</div>
      			  <!-- Separator Ends -->
      			  
      			  
      			  
      			  </div>
                    
                    <!-- Join US Outer Starts -->
               <?php 
					$permalink = ltrim($_SERVER['REQUEST_URI'], '/');
					$permalink = explode('/page/',$permalink);
					$arr = array ();
					if(Auth_VisitorAdapter::hasIdentity()):
					$arr ['userId'] = Auth_VisitorAdapter::getIdentity()->id;
				endif;
					$arr ['controllerName'] = $this->controllerName; 
					echo FrontEnd_Helper_viewHelper::getSidebarWidget ( $arr, $permalink[0] )
			  ?>
                    <!-- Join US Outer Ends -->
             
             </div>
             </div>
             <!-- Guide Outer Right Ends -->
<?php else:?>
          
<center>
	<div style='border:solid 1px gray'>
		<h2>
			<?php echo $this->translate('Oops This Page Does Not Exist')?>
		</h2>
	</div>
</center>
          
<?php endif;?>
     